Repository artsy/force, pull requests merged in 2018-10, with the labels that each got.

#2948 [Stitch] Update import path based on TS refactor
  package.json
  src/desktop/index.js
  src/desktop/lib/global_client_setup.coffee
  src/mobile/index.js
  src/mobile/lib/global_client_setup.coffee
  yarn.lock
Labels: Merge On Green

#2949 @damassi => Mount auction results app ahead of artist to support stand-alone auction page
  src/desktop/apps/auction_lots/index.coffee
  src/desktop/index.js
Labels: Merge On Green

#2960 update reaction
  package.json
  yarn.lock
Labels: Merge On Green

#2958 @sweir27 => Include a feature flag for BNMO, make accessible in Sharify
  src/desktop/config.coffee
  src/lib/setup_sharify.js
Labels: Merge On Green

#2964 Upgrade to the latest Reaction
  package.json
  yarn.lock
Labels: Merge On Green

#2968 Update to latest reaction for BNMO changes
  package.json
  yarn.lock
Labels: Merge On Green

#2951 Show error modal when createOrder mutation fails
  src/desktop/apps/artwork/client/errorModal.tsx
  src/desktop/apps/artwork/components/auction/test/view.coffee
  src/desktop/apps/artwork/components/auction/view.coffee
  src/desktop/apps/artwork/components/commercial/test/view.coffee
  src/desktop/apps/artwork/components/commercial/view.coffee
  src/mobile/apps/artwork/components/meta_data/test/view.coffee
  src/mobile/apps/artwork/components/meta_data/view.coffee
  yarn.lock
Labels: Merge On Green

#2973 Upgrade to the latest Reaction
  package.json
  yarn.lock
Labels: Merge On Green

#2986 trivial readme update
  README.md
Labels: Merge On Green

#3000 Upgrade Reaction to 5.7.4
  package.json
  yarn.lock
Labels: Merge On Green

#2997 [Toolchain] Revert webpack caching on certain loaders
  webpack.config.js
Labels: Toolchain

#3002 Fix: properly open FAQ page on buy now works
  src/desktop/apps/artwork/components/commercial/templates/questions.jade
  src/desktop/apps/artwork/components/commercial/view.coffee
Labels: Merge On Green

#3003 No longer listen on FAQ modal hook
  package.json
  src/desktop/apps/order2/client.js
  yarn.lock
Labels: Merge On Green

#3004 Deploy
  package.json
  src/desktop/apps/artwork/components/commercial/templates/questions.jade
  src/desktop/apps/artwork/components/commercial/view.coffee
  src/desktop/apps/order2/client.js
  webpack.config.js
  yarn.lock
Labels: Toolchain

#3007 Officially close Collect A/B test
  src/desktop/apps/collect2/__tests__/maybeShowOldCollect.jest.js
  src/desktop/apps/collect2/client.js
  src/desktop/apps/collect2/maybeShowOldCollect.js
  src/desktop/apps/collect2/server.js
  src/desktop/components/split_test/running_tests.coffee
  src/desktop/config.coffee
  src/desktop/index.js
  src/lib/setup_sharify.js
  src/mobile/apps/browse/index.coffee
Labels: Jira Synced

#3008 Deploy
  .vscode/extensions.json
  .vscode/settings.json
  src/desktop/apps/collect2/__tests__/maybeShowOldCollect.jest.js
  src/desktop/apps/collect2/client.js
  src/desktop/apps/collect2/maybeShowOldCollect.js
  src/desktop/apps/collect2/server.js
  src/desktop/components/split_test/running_tests.coffee
  src/desktop/config.coffee
  src/desktop/index.js
  src/lib/setup_sharify.js
  src/mobile/apps/browse/index.coffee
  webpack.config.js
Labels: Jira Synced, Toolchain

#3009 @mzikherman => Bump reaction, collect URL update
  package.json
  yarn.lock
Labels: Merge On Green

#3010 Deploy fix collect URL on BNMO banner
  package.json
  yarn.lock
Labels: Merge On Green

#3006 removing never released credit card logo for partner on artwork page
  src/desktop/apps/artwork/components/partner_stub/index.jade
  src/desktop/apps/artwork/components/partner_stub/public/icons/creditcard.svg
  src/desktop/apps/artwork/components/partner_stub/query.coffee
  src/mobile/apps/artwork/components/meta_data/templates/partner.jade
  src/mobile/apps/artwork/components/partner/query.coffee
Labels: Jira Synced

#3013 Bump reaction
  package.json
  yarn.lock
Labels: Merge On Green

#2985 @zephraph => Upgrade to Webpack 4, take 2
  .babelrc
  package.json
  src/desktop/lib/global_client_setup.coffee
  src/lib/global_modules.js
  src/lib/webpack-dev-server.js
  webpack.config.js
  yarn.lock
Labels: Toolchain

#3041 Actually run mutation to create an offer order when "make offer" button is clicked
  src/desktop/apps/artwork/components/commercial/test/view.coffee
  src/desktop/apps/artwork/components/commercial/view.coffee
  src/lib/components/create_offer_order/index.tsx
  src/lib/components/create_offer_order/mutation.js
  src/mobile/apps/artwork/components/meta_data/test/view.coffee
  src/mobile/apps/artwork/components/meta_data/view.coffee
Labels: Jira Synced
