Repository artsy/force, pull requests merged in 2019-05, with the labels that each got.

#3973 Hokusai health check
  .circleci/config.yml
  Dockerfile
  hokusai/build.yml
  hokusai/config.yml
  hokusai/development.yml
  hokusai/test.yml
  package.json
  yarn.lock
Labels: Jira Synced

#3985 Revert "Remove duplicate flickity"
  package.json
  yarn.lock
Labels: Merge On Green

#3993 Add reCAPTCHA 3 scripts and fire homepage event
  .env.oss
  src/desktop/apps/artists/test/template.test.coffee
  src/desktop/apps/fair/test/templates.test.coffee
  src/desktop/apps/fair_organizer/test/template.test.coffee
  src/desktop/apps/home/templates/index.jade
  src/desktop/components/main_layout/templates/scripts.jade
  src/lib/setup_sharify.js
  test.config.js
Labels: Jira Synced

#3995 End A/B test for new search results page
  src/desktop/apps/search/client/index.coffee
  src/desktop/apps/search2/client.tsx
  src/desktop/apps/search2/server.tsx
  src/desktop/components/split_test/running_tests.coffee
  src/mobile/apps/search/client.coffee
Labels: Jira Synced, Merge On Green

#4019 Forgot default value for env var #trivial
  src/desktop/config.coffee
Labels: Merge On Green

#4021 Deploy
  package.json
  src/desktop/config.coffee
  src/lib/setup_sharify.js
  src/mobile/config.coffee
  yarn.lock
Labels: Merge On Green

#4017 Gallery Insights / x Flaky test
  src/desktop/apps/articles/templates/team_channel.jade
  src/desktop/components/email/stylesheets/editorial_signup.styl
  src/desktop/components/email/stylesheets/index.styl
  src/desktop/components/email/test/gallery_insights.test.coffee
Labels: Jira Synced

#4003 Improve copy when user submits auction registration form without a required field
  src/desktop/apps/auction_support/client/registration_form.coffee
  src/desktop/apps/auction_support/test/client/registration_form.test.coffee
  src/desktop/components/credit_card/client/error_handling_form.coffee
  src/mobile/apps/auction_support/client/registration_form.coffee
  src/mobile/apps/auction_support/test/client/registration_form.test.coffee
  src/mobile/components/credit_card/client/error_handling_form.coffee
Labels: Jira Synced

#4031 Patches flickity
  patches/react-flickity-component+3.2.0.patch
Labels: Merge On Green

#4043 GALL-1563: Remove the gallery insights blog
  src/desktop/config.coffee
Labels: Merge On Green

#4047 Deploy recaptcha events, tracking changes, and new nav
  package.json
  patches/react-flickity-component+3.2.0.patch
  src/desktop/analytics/bidding.js
  src/desktop/analytics/inquiry_questionnaire.js
  src/desktop/apps/auth2/components/AuthStatic.tsx
  src/desktop/apps/auth2/components/MobileAuthStatic.tsx
  src/desktop/apps/auth2/components/ModalContainer.tsx
  src/desktop/components/main_layout/client.coffee
  src/desktop/components/main_layout/header/templates/index.jade
  src/desktop/components/main_layout/header/view.coffee
  src/desktop/components/main_layout/templates/scripts.jade
  src/desktop/components/main_layout/test/templates.test.coffee
  src/desktop/components/react/stitch_components/NavBar.tsx
  src/desktop/components/react/stitch_components/index.tsx
  src/desktop/config.coffee
  src/desktop/lib/global_client_setup.tsx
  src/lib/setup_sharify.js
  src/mobile/components/avant_garde_tabs/index.styl
  src/mobile/components/layout/templates/main.jade
  src/mobile/config.coffee
  yarn.lock
Labels: Jira Synced

#4056 Add missing Cookie import
  src/desktop/components/main_layout/client.coffee
Labels: Merge On Green

#4062 Deploy
  .circleci/config.yml
  package.json
  src/desktop/apps/auction/reducers/__tests__/artworkBrowser.test.js
  src/desktop/apps/personalize/routes.js
  src/desktop/apps/personalize/test/routes.jest.ts
  src/desktop/apps/personalize/test/routes.test.js
  src/desktop/apps/user/components/delete_my_account/test/view.test.coffee
  src/desktop/components/inquiry_questionnaire/test/views/inquiry.test.coffee
  src/mobile/apps/auction_support/test/client/registration_form.test.coffee
  src/mobile/components/layout/templates/main.jade
  yarn.lock
Labels: Merge On Green

#4082 [NavBar] QA
  src/desktop/components/react/stitch_components/NavBar.tsx
Labels: Merge On Green

#4078 Auth errors via query render a message
  src/desktop/apps/home/client/auth_router.coffee
Labels: Jira Synced

#4084 [TRIVIAL] Remove desktop /auth import
  src/desktop/index.js
Labels: Merge On Green

#4079 Remove unused mediator listeners
  src/desktop/apps/artist/client.tsx
  src/desktop/apps/collect/__tests__/client.jest.js
  src/desktop/apps/collect/client.js
Labels: Jira Synced

#4091 Adjust z-index in StagingBanner
  src/desktop/components/react/stitch_components/StagingBanner.tsx
Labels: Merge On Green

#4098 Handle ad render logic
  src/desktop/apps/article/__tests__/helpers.jest.tsx
  src/desktop/apps/article/__tests__/third_party_ads_enabled.jest.ts
  src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
  src/desktop/apps/article/components/NewsArticle.tsx
  src/desktop/apps/article/components/layouts/Article.tsx
  src/desktop/apps/article/helpers.tsx
  src/desktop/apps/article/routes.ts
  src/desktop/apps/articles/routes.ts
Labels: Jira Synced

#4058 Old Auth forms support reCAPTCHA, token is passed to server
  src/desktop/components/artist_page_cta/view.coffee
  src/desktop/components/auth_modal/gdpr_signup.styl
  src/desktop/components/auth_modal/templates/_gdpr_signup.jade
  src/desktop/components/marketing_signup_modal/index.coffee
  src/desktop/models/logged_out_user.coffee
Labels: Jira Synced

#4099 DISCO-927: Block /search/ from robots
  src/desktop/apps/sitemaps/routes.coffee
  src/desktop/apps/sitemaps/test/routes.test.coffee
Labels: Jira Synced

#4119 @joeyAghion => [Image Uploading] Drop redundant gemini config, consolidate on @artsy/gemup #migration
  package.json
  src/desktop/apps/consign/client/actions.js
  src/desktop/components/gemini_form/view.coffee
  src/desktop/components/json_page/client/editor.coffee
  src/desktop/config.coffee
  src/desktop/lib/global_client_setup.tsx
  src/lib/setup_sharify.js
  yarn.lock
Labels: Jira Synced, Merge On Green

#4128 Update the search URL that is disallowed in robots.txt
  src/desktop/apps/sitemaps/routes.coffee
  src/desktop/apps/sitemaps/test/routes.test.coffee
Labels: Jira Synced

#4129 Exclude tests from sharify window.alert
  src/desktop/config.coffee
  src/mobile/config.coffee
Labels: Merge On Green

#3761 [A/B Test] Add instant.page A/B test #migration
  src/desktop/components/main_layout/templates/instant-page.jade
  src/desktop/components/split_test/running_tests.coffee
  src/desktop/config.coffee
  src/desktop/lib/global_client_setup.tsx
  src/lib/setup_sharify.js
Labels: Merge On Green

#4126 Remove unused class from right-click-prevention
  src/desktop/components/prevent_right_click/index.jade
Labels: Jira Synced
