Repository artsy/force, pull requests merged in 2019-02, with the labels that each got.

#3453 [package] Update dd-trace client.
  package.json
  yarn.lock
Labels: Jira Synced

#3474 [package] Update dd-trace client again.
  package.json
  yarn.lock
Labels: Jira Synced

#3475 Deploy
  package.json
  yarn.lock
Labels: Jira Synced

#3482 isSuper is passed down to reaction
  src/desktop/apps/article/components/layouts/Article.tsx
Labels: Merge On Green

#3487 Remove progress bar in prod
  webpack/envs/production.js
Labels: Merge On Green

#3496 Upgrade sentry to latest @sentry/node / @sentry/browser
  package.json
  src/desktop/components/main_layout/templates/scripts.jade
  src/desktop/lib/global_client_setup.coffee
  src/lib/setup.js
  src/mobile/components/layout/bootstrap.coffee
  src/mobile/components/layout/templates/scaffold.jade
  webpack/envs/base.js
  yarn.lock
Labels: Merge On Green

#3479 Fixed bug in article AMP controller (GROW-1071)
  src/desktop/apps/article/routes.js
  src/desktop/models/article.coffee
Labels: Jira Synced

#3508 Deploy force to production
  package.json
  src/desktop/apps/article/routes.js
  src/desktop/components/main_layout/templates/scripts.jade
  src/desktop/models/article.coffee
  src/lib/setup.js
  src/mobile/components/layout/templates/scaffold.jade
  webpack/envs/base.js
  yarn.lock
Labels: Jira Synced

#3506 refactor custom title to account for artist name
  src/desktop/apps/auth2/routes.ts
Labels: Jira Synced

#3557 [SC] Hot-patch Reaction and Stitch to test a fix for the CSS bloat.
  patches/@artsy/reaction+13.0.6.patch
  patches/@artsy/stitch+6.0.0.patch
  src/desktop/apps/artist/server.tsx
  src/desktop/apps/artwork2/server.tsx
  src/desktop/apps/collect/server.tsx
  src/desktop/apps/collections/server.tsx
  src/desktop/apps/isomorphic-relay-example/server.tsx
  src/desktop/apps/order2/routes.tsx
Labels: Merge On Green

#3586 Remove force-nginx and reinstate readinessProbe #PLATFORM-1192
  hokusai/production.yml
Labels: Jira Synced

#3582 GALL-1416: Shorten backbone-super-sync cache time on fair overview page
  src/desktop/apps/fair/routes.coffee
  src/desktop/collections/ordered_sets.coffee
  src/desktop/components/info_menu/index.coffee
  src/desktop/models/fair.coffee
  src/desktop/models/ordered_set.coffee
  src/desktop/test/models/ordered_set.coffee
Labels: Jira Synced

#3580 Add SSR reproduction app
  src/desktop/apps/ssr-experiments/App.tsx
  src/desktop/apps/ssr-experiments/client.tsx
  src/desktop/apps/ssr-experiments/routes.tsx
  src/desktop/apps/ssr-experiments/server.tsx
  src/desktop/assets/ssr-experiments.tsx
  src/desktop/index.js
Labels: Jira Synced

#3612 Remove make offer feature flag env vars
  src/desktop/config.coffee
  src/lib/setup_sharify.js
  src/mobile/config.coffee
Labels: Jira Synced

#3624 Remove duplicate dependencies from webpack bundles
  package.json
  yarn.lock
Labels: Jira Synced

#3635 @mzikherman => Bump Reaction and test fix
  package.json
  src/desktop/apps/article/components/__tests__/InfiniteScrollArticle.jest.tsx
  yarn.lock
Labels: Merge On Green

#3626 Add auto-scaling to Kubernetes config
  hokusai/production.yml
  hokusai/staging.yml
Labels: Jira Synced

#3640 Fix rate limiting defaults so they don't error
  src/desktop/config.coffee
Labels: Merge On Green

#3630 [Toolchain] Precompile server-side code with Webpack
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  package.json
  scripts/start.sh
  src/config.js
  src/desktop/apps/article/index.ts
  src/desktop/apps/articles/index.js
  src/desktop/apps/auction/index.js
  src/desktop/apps/auctions2/index.js
  src/desktop/apps/auth2/index.ts
  src/desktop/apps/categories/index.js
  src/desktop/apps/consign/index.js
  src/desktop/apps/isomorphic-relay-example/client.js
  src/desktop/apps/isomorphic-relay-example/components/Layout.js
  src/desktop/apps/isomorphic-relay-example/components/Meta.js
  src/desktop/apps/isomorphic-relay-example/components/Nav.js
  src/desktop/apps/isomorphic-relay-example/routes.js
  src/desktop/apps/isomorphic-relay-example/routes/artist/ArtistArtworks.js
  src/desktop/apps/isomorphic-relay-example/routes/artist/ArtistRoute.js
  src/desktop/apps/isomorphic-relay-example/routes/artsy/ArtsyRoute.js
  src/desktop/apps/isomorphic-relay-example/routes/auction/AuctionRoute.js
  src/desktop/apps/isomorphic-relay-example/routes/home/HomeRoute.js
  src/desktop/apps/isomorphic-relay-example/routes/react-loadable/Example1.js
  src/desktop/apps/isomorphic-relay-example/routes/react-loadable/Example2.js
  src/desktop/apps/isomorphic-relay-example/routes/react-loadable/ReactLoadableClientRoute.js
  src/desktop/apps/isomorphic-relay-example/routes/react-loadable/ReactLoadableServerRoute.js
  src/desktop/apps/isomorphic-relay-example/server.tsx
  src/desktop/apps/react_example/client.js
  src/desktop/apps/react_example/components/App.js
  src/desktop/apps/react_example/components/DOM.js
  src/desktop/apps/react_example/components/clientSideJadeView.jade
  src/desktop/apps/react_example/components/meta.jade
  src/desktop/apps/react_example/components/myJadeView.jade
  src/desktop/apps/react_example/index.js
  src/desktop/apps/react_example/routes.js
  src/desktop/assets/isomorphic-relay.js
  src/desktop/assets/react_example.coffee
  src/desktop/config.coffee
  src/desktop/index.js
  src/index.js
  src/lib/environment.js
  src/lib/memory_profiler.js
  src/lib/middleware/assetMiddleware.ts
  src/lib/middleware/error_handler.coffee
  src/lib/setup.js
  src/lib/webpack-dev-server.js
  webpack/envs/baseConfig.js
  webpack/envs/ciConfig.js
  webpack/envs/debug.js
  webpack/envs/debugConfig.js
  webpack/envs/developmentConfig.js
  webpack/envs/index.js
  webpack/envs/productionConfig.js
  webpack/envs/serverConfig.js
  webpack/index.js
  webpack/utils/getCSSManifest.js
  webpack/utils/getEntrypoints.js
  webpack/utils/omitIf.js
  yarn.lock
Labels: Jira Synced, Toolchain

#3644 Add bundlesize to budget size for largest bundles
  .circleci/config.yml
  package.json
  webpack/envs/ciConfig.js
Labels: Merge On Green
