Repository artsy/force, pull requests merged in 2019-01, with the labels that each got.

#3257 DISCO-629: Remove unused MarketInsights components for Artwork page
  src/desktop/apps/artwork/components/artists/market_insights.js
  src/desktop/assets/artists_artworks.coffee
Labels: Jira Synced

#3270 @mzikherman => Bump Reaction for some BNMO blockers on the new artwork page
  package.json
  yarn.lock
Labels: Merge On Green

#3306 Deploy some updates
  package.json
  src/desktop/apps/consign/components/describe_work_desktop/index.js
  src/desktop/apps/consign/components/describe_work_mobile/index.js
  yarn.lock
Labels: Jira Synced

#3286 Use the correct URL scheme for news articles
  src/desktop/apps/sitemaps/routes.coffee
  src/desktop/apps/sitemaps/templates/news.jade
  src/desktop/apps/sitemaps/test/routes.coffee
  src/desktop/apps/sitemaps/test/templates.coffee
Labels: Jira Synced

#3315 Adjusting display to check for profile owner when displaying search result
  src/desktop/apps/search/templates/search_result.jade
  src/desktop/models/search_result.coffee
  src/desktop/test/models/search_result.coffee
  src/mobile/components/search_results/result.jade
  src/mobile/models/search_result.coffee
  src/mobile/test/models/search_result.coffee
Labels: Jira Synced

#3322 Deploy
  package.json
  src/desktop/apps/artist/server.tsx
  src/desktop/apps/artwork/components/artist_artworks/index.jade
  src/desktop/apps/artwork/components/auction_artworks/index.jade
  src/desktop/apps/artwork/components/auction_artworks/test/index.coffee
  src/desktop/apps/artwork/components/partner_artworks/index.jade
  src/desktop/apps/artwork/components/related_artworks/templates/masonry.jade
  src/desktop/apps/artwork/components/show_artworks/index.jade
  src/desktop/apps/artwork2/server.tsx
  src/desktop/apps/auction/components/artwork_browser/ArtworksByFollowedArtists.js
  src/desktop/apps/auction/components/artwork_browser/PromotedSaleArtworks.js
  src/desktop/apps/react_example/components/myJadeView.jade
  src/desktop/apps/search/templates/search_result.jade
  src/desktop/apps/show/components/artwork_columns_metaphysics/template.jade
  src/desktop/apps/show/components/artwork_columns_metaphysics/view.coffee
  src/desktop/apps/show/templates/columns.jade
  src/desktop/apps/sitemaps/routes.coffee
  src/desktop/apps/sitemaps/templates/news.jade
  src/desktop/apps/sitemaps/test/routes.coffee
  src/desktop/apps/sitemaps/test/templates.coffee
  src/desktop/components/artwork_columns/stitch_template.jade
  src/desktop/components/artwork_columns/view.coffee
  src/desktop/components/artwork_item/templates/stitch_artwork.jade
  src/desktop/components/artwork_masonry/index.jade
  src/desktop/components/artwork_masonry/view.coffee
  src/desktop/components/react/stitch_components/ReactionArtworkGrid.tsx
  src/desktop/components/react/stitch_components/ReactionFillwidth.tsx
  src/desktop/components/react/stitch_components/index.tsx
  src/desktop/components/react/stitch_components/utils/mapToRelayConnection.ts
  src/desktop/config.coffee
  src/desktop/index.js
  src/desktop/lib/global_client_setup.coffee
  src/desktop/models/search_result.coffee
  src/desktop/test/models/search_result.coffee
  src/lib/setup.js
  src/lib/setup_sharify.js
  src/mobile/components/search_results/result.jade
  src/mobile/index.js
  src/mobile/lib/global_client_setup.coffee
  src/mobile/models/search_result.coffee
  src/mobile/test/models/search_result.coffee
  yarn.lock
Labels: Jira Synced

#3329 Fix-sentry-841841080
  src/mobile/apps/artwork/components/image/templates/image_module.jade
Labels: Merge On Green, bug-bash

#3337 Update icon path
  package.json
  src/desktop/components/react/stitch_components/ReactionTooltipQuestion.tsx
  yarn.lock
Labels: Merge On Green

#3316 PLATFORM-1066 - Adds staging banner
  src/desktop/components/main_layout/header/templates/index.jade
  src/desktop/components/react/stitch_components/StagingBanner.tsx
  src/desktop/components/react/stitch_components/index.tsx
Labels: Jira Synced

#3346 Exclude partner articles and classic articles from news sitemap
  src/desktop/apps/sitemaps/routes.coffee
  src/desktop/apps/sitemaps/test/routes.coffee
Labels: Jira Synced

#3351 update artsy eigen web association
  yarn.lock
Labels: Jira Synced

#3355 Hide "coming soon" videos from RSS feed
  src/desktop/apps/rss/routes.js
  src/desktop/apps/rss/test/routes.test.js
Labels: Jira Synced

#3365 Release fix
  yarn.lock
Labels: Merge On Green

#3366 Release
  package.json
  src/desktop/apps/artist/client.tsx
  src/desktop/apps/artist/server.tsx
  src/desktop/apps/artwork2/client.tsx
  src/desktop/apps/artwork2/server.tsx
  src/desktop/apps/editorial_features/components/gucci/client.js
  src/desktop/apps/editorial_features/components/gucci/components/App.tsx
  src/desktop/apps/editorial_features/components/gucci/components/__tests__/App.test.js
  src/desktop/apps/editorial_features/components/gucci/components/nav/__tests__/fixed_header.test.js
  src/desktop/apps/editorial_features/components/gucci/components/nav/__tests__/header.test.js
  src/desktop/apps/editorial_features/components/gucci/components/nav/__tests__/sections_nav.test.js
  src/desktop/apps/editorial_features/components/gucci/components/nav/fixed_header.tsx
  src/desktop/apps/editorial_features/components/gucci/components/nav/header.jsx
  src/desktop/apps/editorial_features/components/gucci/components/nav/header.tsx
  src/desktop/apps/editorial_features/components/gucci/components/nav/sections_nav.jsx
  src/desktop/apps/editorial_features/components/gucci/components/nav/sections_nav.tsx
  src/desktop/apps/editorial_features/components/gucci/components/section/section.jsx
  src/desktop/apps/editorial_features/components/gucci/components/section/section.tsx
  src/desktop/apps/editorial_features/components/gucci/components/section/section_text.jsx
  src/desktop/apps/editorial_features/components/gucci/components/section/section_text.tsx
  src/desktop/apps/editorial_features/components/gucci/components/section/section_video.tsx
  src/desktop/apps/editorial_features/components/gucci/components/series/series_footer.jsx
  src/desktop/apps/editorial_features/components/gucci/components/series/series_footer.tsx
  src/desktop/apps/editorial_features/components/gucci/components/series/series_header.tsx
  src/desktop/apps/editorial_features/components/gucci/templates/head.jade
  src/desktop/apps/editorial_features/routes.coffee
  src/desktop/apps/order2/client.js
  src/desktop/apps/order2/routes.tsx
  src/desktop/apps/rss/routes.js
  src/desktop/apps/rss/test/routes.test.js
  src/desktop/apps/sitemaps/routes.coffee
  src/desktop/apps/sitemaps/test/routes.coffee
  src/desktop/components/main_layout/header/templates/index.jade
  src/desktop/components/react/stitch_components/StagingBanner.tsx
  src/desktop/components/react/stitch_components/index.tsx
  yarn.lock
Labels: Jira Synced

#3359 Serve 404 page when order is not found
  src/desktop/apps/order2/__tests__/routes.jest.js
  src/desktop/apps/order2/routes.tsx
Labels: Jira Synced

#3368 Make nav menu consistent across the app
  src/desktop/components/main_layout/header/templates/small_screen_dropdown_menu.jade
Labels: Jira Synced

#3380 Release
  package.json
  src/desktop/apps/artsy_in_miami/components/MiamiFairWeekPage.js
  src/desktop/apps/home/stylesheets/index.styl
  src/desktop/apps/order2/__tests__/routes.jest.js
  src/desktop/apps/order2/routes.tsx
  src/desktop/components/fair_week_marketing/PageScaffold.js
  src/desktop/components/main_layout/header/templates/small_screen_dropdown_menu.jade
  src/desktop/components/main_layout/stylesheets/body.styl
  src/desktop/components/stylus_lib/index.styl
  src/lib/template_helpers.js
  yarn.lock
Labels: Jira Synced

#3398 fix calling window.Sailthru before it is defined #BUGS-727
  src/desktop/components/main_layout/templates/scripts.jade
Labels: Jira Synced

#3397 Use safe navigation to access partner name
  src/mobile/models/artwork.coffee
Labels: Jira Synced

#3400 Redefines carousel arrow offset from 30 to 10 pixels
  src/desktop/apps/galleries_institutions/components/primary_carousel/index.styl
Labels: Jira Synced

#3399 Explicitly checks for existence of city before searching for city.name
  src/mobile/apps/galleries_institutions/templates/partner.jade
Labels: Jira Synced, bug-bash

#3401 Deploy bumps to reaction@11.2.14 and palette@2.34.2
  package.json
  src/desktop/components/main_layout/templates/scripts.jade
  yarn.lock
Labels: Jira Synced

#3404 [Bugfix] Add JS to error page
  src/desktop/components/error_handler/index.css
  src/desktop/components/error_handler/index.jade
  src/desktop/components/error_handler/index.styl
  src/desktop/components/error_handler/test/template.coffee
Labels: Jira Synced, bug-bash

#3408 Add polyfill for object.entries for older browsers
  package.json
  src/desktop/lib/global_client_setup.coffee
  yarn.lock
Labels: Jira Synced

#3406 Update timeout copy for bid processing
  src/desktop/apps/auction_support/client/bid_form.coffee
  src/mobile/apps/feature/client/bid_page.coffee
Labels: Jira Synced

#3410 [Bugfix] Only interact with carousel if images
  src/desktop/apps/artists/client/carousel.coffee
Labels: Jira Synced

#3416 Update max-height on slider in mobile web to not cut off large shows
  src/mobile/components/show_more_works/index.coffee
Labels: Jira Synced

#3412 [Bugfix] Constrain related auctions image size
  src/desktop/components/react/auction_block/index.styl
Labels: Jira Synced

#3409 [Bugfix] Artist page crashes if artist doesn't have a thumbnail
  src/desktop/apps/artists/templates/index.jade
Labels: Jira Synced

#3417 Bump the number of shows from premium partners which we highlight from 3 -> 6
  src/desktop/apps/galleries_institutions/components/primary_carousel/fetch.coffee
Labels: Jira Synced

#3428 Add stub for new search bar and hide behind flag
  src/desktop/components/main_layout/header/templates/large_screen_header.jade
  src/desktop/components/react/stitch_components/SearchBar.tsx
  src/desktop/components/react/stitch_components/index.tsx
Labels: Merge On Green

#3434 [Toolchain] Break Webpack config into smaller pieces
  package.json
  scripts/assets.sh
  scripts/test.sh
  src/desktop/apps/order2/server.js
  src/desktop/index.js
  src/index.js
  src/lib/webpack-dev-server.js
  src/mobile/apps/artwork/client/index.coffee
  webpack.config.js
  webpack/envs/base.js
  webpack/envs/ci.js
  webpack/envs/development.js
  webpack/envs/index.js
  webpack/envs/production.js
  webpack/index.js
  webpack/utils/environment.js
  webpack/utils/getEntrypoints.js
  yarn.lock
Labels: Toolchain

#3444 Restore order app
  src/desktop/index.js
Labels: Merge On Green

#3431 Validate Metaphysics' staging schema on pull request builds as well
  .circleci/config.yml
Labels: Jira Synced

#3446 Deploy
  .circleci/config.yml
  package.json
  scripts/assets.sh
  scripts/test.sh
  src/desktop/apps/order2/server.js
  src/desktop/index.js
  src/index.js
  src/lib/webpack-dev-server.js
  src/mobile/apps/artwork/client/index.coffee
  webpack.config.js
  webpack/envs/base.js
  webpack/envs/ci.js
  webpack/envs/development.js
  webpack/envs/index.js
  webpack/envs/production.js
  webpack/index.js
  webpack/utils/environment.js
  webpack/utils/getEntrypoints.js
  yarn.lock
Labels: Toolchain

#3447 @damassi => [RecordArtworkView] Reenable recording an artwork view on new artwork page
  src/desktop/apps/artwork2/client.tsx
  src/lib/components/record_artwork_view/index.js
Labels: Merge On Green

#3440 Add ability to customize mobile sign up form using query string
  src/desktop/apps/auth2/__tests__/routes.jest.js
  src/desktop/apps/auth2/components/MobileAuthStatic.tsx
  src/desktop/apps/auth2/routes.ts
Labels: Jira Synced

#3402 [Article] fix display year in article dates
  src/desktop/components/article_figure/mixin.jade
  src/desktop/models/article.coffee
Labels: Jira Synced
