Repository artsy/force, pull requests merged in 2019-10, with the labels that each got.

#4609 Handle redirecting amp links in series and video articles
  src/desktop/apps/article/__tests__/routes.jest.ts
  src/desktop/apps/article/index.ts
  src/desktop/apps/article/routes.ts
Labels: Jira Synced

#4614 [Test] Disable /collection test for now
  src/test/acceptance/collection.js
Labels: Merge On Green, Test

#4615 Deploy
  package.json
  src/test/acceptance/collection.js
  yarn.lock
Labels: Test

#4627 [config] Make IP filter disableable in an effort to reduce cost.
  src/lib/setup.js
Labels: Jira Synced

#4635 Always load in stripe.js
  src/desktop/components/main_layout/templates/scripts.jade
Labels: Jira Synced

#4638 Deploy
  CONTRIBUTING.md
  package.json
  scripts/build_review_app.sh
  src/desktop/apps/artist/components/Meta.js
  src/desktop/apps/artist/components/__tests__/Meta.jest.js
  src/desktop/apps/artist/server.tsx
  src/desktop/components/main_layout/templates/scripts.jade
  src/desktop/components/split_test/server_split_test.coffee
  src/lib/middleware/same_origin.coffee
  yarn.lock
Labels: Jira Synced

#4476 Stitch collections hubs nav from Reaction into homepage
  src/desktop/apps/home/queries/initial.coffee
  src/desktop/apps/home/routes.coffee
  src/desktop/apps/home/stylesheets/hubs_entry.styl
  src/desktop/apps/home/stylesheets/index.styl
  src/desktop/apps/home/templates/hubs_entry.jade
  src/desktop/apps/home/templates/index.jade
  src/desktop/components/react/stitch_components/CollectionsHubsHomepageNav.tsx
  src/desktop/components/react/stitch_components/index.tsx
  src/mobile/apps/home/routes.coffee
  src/mobile/apps/home/stylesheets/index.styl
  src/mobile/apps/home/templates/page.jade
Labels: Jira Synced

#4659 Deploy
  package.json
  src/desktop/apps/home/queries/initial.coffee
  src/desktop/apps/home/routes.coffee
  src/desktop/apps/home/stylesheets/hubs_entry.styl
  src/desktop/apps/home/stylesheets/index.styl
  src/desktop/apps/home/templates/hubs_entry.jade
  src/desktop/apps/home/templates/index.jade
  src/desktop/components/react/stitch_components/CollectionsHubsHomepageNav.tsx
  src/desktop/components/react/stitch_components/index.tsx
  src/lib/middleware/hsts.coffee
  src/mobile/apps/home/routes.coffee
  src/mobile/apps/home/stylesheets/index.styl
  src/mobile/apps/home/templates/page.jade
  yarn.lock
Labels: Jira Synced

#4674 [package] Update Reaction/react-html-parser to work well on the server
  package.json
  src/index.js
  yarn.lock
Labels: Merge On Green

#4676 [Lib] Bump reaction@21.7.8
  package.json
  yarn.lock
Labels: Merge On Green

#4696 [webpack] Drop graphql-js and relay network server from client bundles.
  package.json
  webpack/envs/baseConfig.js
  yarn.lock
Labels: Jira Synced

#4698 Revert "[webpack] Drop graphql-js and relay network server from client bundles."
  webpack/envs/baseConfig.js
Labels: Merge On Green

#4717 [Lib] Remove reference to arc
  package.json
  yarn.lock
Labels: Merge On Green

#4703 Use h1 for /auctions page title
  src/desktop/apps/auctions/stylesheets/index.styl
  src/desktop/apps/auctions/templates/index.jade
Labels: Merge On Green

#4667 Grow- 1407 Editorial RSS feed broken
  src/desktop/apps/rss/routes.js
  src/desktop/apps/rss/test/routes.test.js
Labels: Jira Synced

#4582 [GROW-1513] setup collection hub entrypoints a/b test
  src/desktop/apps/collect/client.js
  src/desktop/apps/collect/server.tsx
  src/desktop/apps/home/routes.coffee
  src/desktop/components/split_test/running_tests.coffee
  src/mobile/apps/home/routes.coffee
Labels: Jira Synced

#4742 Deploy
  package.json
  src/desktop/apps/collect/client.js
  src/desktop/apps/collect/server.tsx
  src/desktop/apps/home/routes.coffee
  src/desktop/components/split_test/running_tests.coffee
  src/mobile/apps/home/routes.coffee
  yarn.lock
Labels: Jira Synced

#4744 [GROW-1544] Launch Artist Page signup modal to 100% of users
  src/desktop/apps/artist/components/__tests__/cta.jest.ts
  src/desktop/apps/artist/components/cta.ts
  src/desktop/assets/artist.styl
  src/desktop/assets/artists_artworks.styl
  src/desktop/components/artist_page_cta/index.styl
  src/desktop/components/artist_page_cta/templates/index.jade
  src/desktop/components/artist_page_cta/templates/overlay.jade
  src/desktop/components/artist_page_cta/templates/register.jade
  src/desktop/components/artist_page_cta/templates/row.jade
  src/desktop/components/artist_page_cta/test/template.test.coffee
  src/desktop/components/artist_page_cta/view.coffee
Labels: Jira Synced

#4751 @eessex => [Middleware] Skip AB test middleware in test
  src/lib/setup.js
Labels: Merge On Green

#4766 [GROW-1628] Homepage entrypoints experiment viewed
  src/desktop/apps/home/client/index.coffee
  src/mobile/apps/home/client/view.coffee
Labels: Jira Synced

#4768 Update all magazine references to editorial
  src/desktop/apps/articles/templates/meta/articles.jade
  src/desktop/apps/articles/templates/section.jade
  src/desktop/apps/editorial_features/components/eoy/templates/index.jade
  src/desktop/apps/editorial_features/components/gucci/components/nav/__tests__/header.test.js
  src/desktop/apps/editorial_features/components/gucci/components/nav/header.tsx
  src/desktop/apps/editorial_features/components/venice_2017/templates/nav.jade
  src/desktop/apps/home/templates/featured_articles.jade
  src/desktop/components/article/templates/super_article_sticky_header.jade
  src/desktop/components/main_layout/footer/mobile_footer_menu.jade
  src/desktop/components/main_layout/header/templates/more.jade
  src/mobile/apps/articles/meta/articles.jade
  src/mobile/apps/articles/templates/section.jade
Labels: Jira Synced

#4769 Deploy
  package.json
  src/desktop/apps/articles/templates/meta/articles.jade
  src/desktop/apps/articles/templates/section.jade
  src/desktop/apps/editorial_features/components/eoy/templates/index.jade
  src/desktop/apps/editorial_features/components/gucci/components/nav/__tests__/header.test.js
  src/desktop/apps/editorial_features/components/gucci/components/nav/header.tsx
  src/desktop/apps/editorial_features/components/venice_2017/templates/nav.jade
  src/desktop/apps/home/client/index.coffee
  src/desktop/apps/home/templates/featured_articles.jade
  src/desktop/components/article/templates/super_article_sticky_header.jade
  src/desktop/components/main_layout/footer/mobile_footer_menu.jade
  src/desktop/components/main_layout/header/templates/more.jade
  src/mobile/apps/articles/meta/articles.jade
  src/mobile/apps/articles/templates/section.jade
  src/mobile/apps/home/client/view.coffee
  yarn.lock
Labels: Jira Synced
