Repository artsy/force, pull requests merged in 2019-08, with the labels that each got.

#4383 Deploy: Bidder Registration, Vanguard, Recaptcha, Reaction bump
  .circleci/config.yml
  package.json
  src/desktop/apps/article/__tests__/editorial_features.jest.ts
  src/desktop/apps/article/editorial_features.ts
  src/desktop/apps/article/queries/relatedArticles.js
  src/desktop/apps/article/queries/seriesRelatedArticles.ts
  src/desktop/apps/auction_reaction/client.tsx
  src/desktop/apps/auction_reaction/routes.tsx
  src/desktop/apps/auction_reaction/server.tsx
  src/desktop/apps/auction_reaction/templates/index.jade
  src/desktop/apps/auction_support/stylesheets/index.styl
  src/desktop/apps/auction_support/templates/bid-form.jade
  src/desktop/apps/auction_support/templates/registration.jade
  src/desktop/apps/partner2/client/contact.coffee
  src/desktop/apps/partner2/stylesheets/contact.styl
  src/desktop/apps/partner2/templates/contact.jade
  src/desktop/apps/partner2/test/client/contact.test.coffee
  src/desktop/assets/auction_reaction.styl
  src/desktop/assets/auction_reaction.ts
  src/desktop/components/main_layout/templates/scripts.jade
  src/desktop/config.coffee
  src/desktop/index.js
  src/lib/setup_sharify.js
  src/mobile/apps/auction_support/stylesheets/index.styl
  src/mobile/apps/auction_support/templates/registration.jade
  src/mobile/apps/partner_profile/templates/contact.jade
  yarn.lock
Labels: Jira Synced

#4405 [GROW-1463] closes artist page signup a/b test
  src/desktop/apps/artist/components/__tests__/cta.jest.ts
  src/desktop/apps/artist/components/cta.ts
  src/desktop/components/split_test/running_tests.coffee
Labels: Jira Synced

#4403 Fix registration copy
  src/desktop/apps/auction/components/layout/ConfirmRegistrationModal.tsx
Labels: Jira Synced

#4396 [Refactor] Consolidate /collect routes under single app
  package.json
  src/desktop/apps/collect/client.js
  src/desktop/apps/collect/server.tsx
  src/desktop/apps/collections/client.js
  src/desktop/apps/collections/server.tsx
  src/desktop/apps/ssr-experiments/App.tsx
  src/desktop/assets/collections.js
  src/desktop/assets/collections.styl
  src/desktop/index.js
  yarn.lock
Labels: Merge On Green

#4411 Reintroduce updated auction registration modals
  src/desktop/apps/auction/actions/app.js
  src/desktop/apps/auction/components/DOM.js
  src/desktop/apps/auction/components/Layout.js
  src/desktop/apps/auction/components/__tests__/DOM.jest.js
  src/desktop/apps/auction/components/__tests__/Layout.test.js
  src/desktop/apps/auction/components/layout/ConfirmRegistrationModal.tsx
  src/desktop/apps/auction/components/layout/RegistrationModal.tsx
  src/desktop/apps/auction/components/layout/__tests__/ConfirmRegistrationModal.jest.tsx
  src/desktop/apps/auction/reducers/app.js
  src/desktop/apps/auction/routes.js
  src/desktop/apps/auction_support/client/accept_conditions_of_sale_modal.coffee
  src/desktop/apps/auction_support/stylesheets/accept_conditions_of_sale_modal.styl
  src/desktop/apps/auction_support/stylesheets/index.styl
  src/desktop/apps/auction_support/templates/accept_conditions_of_sale_modal.jade
  src/desktop/apps/auction_support/test/client/accept_conditions_of_sale_modal.test.coffee
Labels: Jira Synced

#4407 Deploy
  .circleci/config.yml
  package.json
  src/desktop/apps/article/__tests__/helpers.jest.tsx
  src/desktop/apps/article/components/__tests__/EditButton.jest.tsx
  src/desktop/apps/article/components/__tests__/InfiniteScrollArticle.jest.tsx
  src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.jest.tsx
  src/desktop/apps/article/components/__tests__/NewsArticle.jest.tsx
  src/desktop/apps/article/components/layouts/__tests__/Article.jest.tsx
  src/desktop/apps/articles/components/AuthWrapper.tsx
  src/desktop/apps/artist/components/__tests__/cta.jest.ts
  src/desktop/apps/artist/components/cta.ts
  src/desktop/apps/auction/actions/app.js
  src/desktop/apps/auction/components/DOM.js
  src/desktop/apps/auction/components/Layout.js
  src/desktop/apps/auction/components/__tests__/DOM.jest.js
  src/desktop/apps/auction/components/__tests__/Layout.test.js
  src/desktop/apps/auction/components/artwork_rail/ArtworkRail.js
  src/desktop/apps/auction/components/layout/ConfirmRegistrationModal.tsx
  src/desktop/apps/auction/components/layout/RegistrationModal.tsx
  src/desktop/apps/auction/components/layout/__tests__/ConfirmRegistrationModal.jest.tsx
  src/desktop/apps/auction/components/layout/active_bids/MyActiveBids.js
  src/desktop/apps/auction/reducers/app.js
  src/desktop/apps/auction/routes.js
  src/desktop/apps/auction_support/client/accept_conditions_of_sale_modal.coffee
  src/desktop/apps/auction_support/stylesheets/accept_conditions_of_sale_modal.styl
  src/desktop/apps/auction_support/stylesheets/index.styl
  src/desktop/apps/auction_support/templates/accept_conditions_of_sale_modal.jade
  src/desktop/apps/auction_support/test/client/accept_conditions_of_sale_modal.test.coffee
  src/desktop/apps/authentication/components/ModalContainer.tsx
  src/desktop/apps/collect/client.js
  src/desktop/apps/collect/server.tsx
  src/desktop/apps/collections/client.js
  src/desktop/apps/collections/server.tsx
  src/desktop/apps/ssr-experiments/App.tsx
  src/desktop/assets/collections.js
  src/desktop/assets/collections.styl
  src/desktop/components/react/masonry_grid/Reveal.js
  src/desktop/components/split_test/running_tests.coffee
  src/desktop/index.js
  test.config.js
  yarn.lock
Labels: Jira Synced

#4427 [Lib] Downgrade react@16.8.6
  package.json
  yarn.lock
Labels: Jira Synced, Merge On Green

#4430 Production Deploy
  package.json
  src/desktop/apps/authentication/__tests__/helpers.jest.js
  src/desktop/apps/authentication/helpers.ts
  yarn.lock
Labels: Jira Synced

#4447 PURCHASE-1415 - Fixes mobile breakpoint for injected page content
  src/desktop/apps/page/index.styl
  src/mobile/apps/page/index.styl
Labels: Jira Synced
