Repository artsy/force, pull requests merged in 2020-11, with the labels that each got.

#6567 Deploy
  data/schema.graphql
  hokusai/build.yml
  hokusai/development.yml
  hokusai/templates/docker-compose-service.yml.j2
  hokusai/test.yml
  package.json
  src/v2/Components/NavBar/NavItem.tsx
  src/v2/Components/NavBar/NavItemPanel.tsx
  src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
  src/v2/Components/NavBar/__tests__/NavItem.jest.tsx
  yarn.lock
Labels: Jira Synced

#6576 [FX-2403] Truncates press release
  src/v2/Apps/Show/Routes/ShowInfo.tsx
Labels: Merge On Green

#6577 [FX-2402] Sets a minHeight for very short pages
  src/v2/Apps/Show/ShowSubApp.tsx
Labels: Merge On Green

#6579 [FX-2421] Matches nav item ordering with desktop
  src/v2/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
  src/v2/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.jest.tsx
Labels: Merge On Green

#6581 Use border on text component instead of using a Separator on consign2
  src/v2/Apps/Consign/Components/HowToSell.tsx
  src/v2/Apps/Consign/Components/SellArtDifferently.tsx
Labels: Merge On Green

#6582 feat: Add second contact block and update copy on /consign2
  src/v2/Apps/Consign/Components/ContactUs.tsx
  src/v2/Apps/Consign/ConsignApp.tsx
Labels: Merge On Green

#6586 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6588 feat: Add skeleton loading state when fetching price estimates on /consign2
  src/v2/Apps/Consign/Components/GetPriceEstimate/ArtistInsightResult.tsx
  src/v2/Apps/Consign/Components/GetPriceEstimate/EstimateResults.tsx
Labels: Squash On Green

#6599 bugfix: Add 'roles' to passport's userKeys
  src/lib/setup.js
Labels: Merge On Green

#6578 Deploy
  data/schema.graphql
  package.json
  src/desktop/apps/artists/index.styl
  src/desktop/apps/artists/templates/index.jade
  src/desktop/apps/artists/templates/letter.jade
  src/desktop/apps/artists/templates/meta.jade
  src/desktop/apps/fairs/test/client.test.js
  src/desktop/components/prevent_right_click/index.jade
  src/desktop/models/additional_image.coffee
  src/desktop/models/artwork.coffee
  src/desktop/test/models/artwork.test.js
  src/lib/current_user.coffee
  src/lib/setup.js
  src/mobile/apps/art_fairs/test/template.test.js
  src/mobile/apps/artists/index.styl
  src/mobile/apps/artists/routes.coffee
  src/mobile/apps/artists/templates/index.jade
  src/typings/gravity.d.ts
  src/v2/Apps/Artist/__tests__/routes.jest.tsx
  src/v2/Apps/Artist/routes.tsx
  src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/v2/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.jest.tsx
  src/v2/Apps/Consign/Components/ContactUs.tsx
  src/v2/Apps/Consign/Components/GetPriceEstimate/ArtistInsightResult.tsx
  src/v2/Apps/Consign/Components/GetPriceEstimate/ConsignPriceEstimateContext.tsx
  src/v2/Apps/Consign/Components/GetPriceEstimate/EstimateResults.tsx
  src/v2/Apps/Consign/Components/HowToSell.tsx
  src/v2/Apps/Consign/Components/SellArtDifferently.tsx
  src/v2/Apps/Consign/ConsignApp.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Apps/Show/Components/ShowArtworksEmptyState.tsx
  src/v2/Apps/Show/Routes/ShowInfo.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/ShowSubApp.tsx
  src/v2/Apps/Show/__tests__/ShowArtworksEmptyState.jest.tsx
  src/v2/Apps/Show/__tests__/ShowViewingRoom.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Artwork/ArtworkActions.fixture.ts
  src/v2/Artsy/Router/PermanentRedirectException.tsx
  src/v2/Artsy/Router/buildClientApp.tsx
  src/v2/Artsy/Router/buildServerApp.tsx
  src/v2/Components/Artwork/FillwidthItem.tsx
  src/v2/Components/Artwork/GridItem.tsx
  src/v2/Components/Lightbox/Lightbox.tsx
  src/v2/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
  src/v2/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.jest.tsx
  src/v2/DevTools/setupTestWrapper.tsx
  src/v2/Utils/__tests__/user.jest.ts
  src/v2/Utils/user.ts
  src/v2/__generated__/ConsignPriceEstimateContext_ArtistInsights_Query.graphql.ts
  src/v2/__generated__/FairExhibitorsQuery.graphql.ts
  src/v2/__generated__/FairExhibitors_Query.graphql.ts
  src/v2/__generated__/FairExhibitors_fair.graphql.ts
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/ShowArtworksEmptyState_Test_Query.graphql.ts
  src/v2/__generated__/ShowArtworksEmptyState_show.graphql.ts
  src/v2/__generated__/routes_FairExhibitorsQuery.graphql.ts
  src/v2/__generated__/routes_ShowQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#6604 fix: [Consign2] Move files to vanity-files-artsy.net
  src/v2/Apps/Consign/Components/GetPriceEstimate/EstimateResults.tsx
  src/v2/Apps/Consign/Components/Header.tsx
  src/v2/Apps/Consign/Components/SellWithArtsy.tsx
Labels: Merge On Green

#6605 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6607 fix: [Consign2] Wire up links
  src/v2/Apps/Consign/Components/Header.tsx
  src/v2/Apps/Consign/Components/SellWithArtsy.tsx
  src/v2/Apps/Consign/ConsignApp.tsx
Labels: Merge On Green

#6608 fix: [Consign2] Replace src with srcSet
  src/v2/Apps/Consign/Components/InDemandNow/ConsignInDemandNow.tsx
  src/v2/Apps/Consign/Components/InDemandNow/ConsignTopArtists.tsx
  src/v2/__generated__/ConsignInDemandNowQuery.graphql.ts
Labels: Merge On Green

#6609 feat(fair): show up to 5 marketing collections on fair page
  src/v2/Apps/Fair/Components/FairCollections/FairCollections.tsx
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/__generated__/FairApp_Query.graphql.ts
  src/v2/__generated__/FairApp_fair.graphql.ts
  src/v2/__generated__/FairCollections_fair.graphql.ts
  src/v2/__generated__/routes_FairQuery.graphql.ts
Labels: Jira Synced

#6613 @mzikherman => fix: include totalCount for fair exhibitors query
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/__generated__/FairExhibitorsQuery.graphql.ts
  src/v2/__generated__/FairExhibitors_Query.graphql.ts
  src/v2/__generated__/FairExhibitors_fair.graphql.ts
  src/v2/__generated__/routes_FairExhibitorsQuery.graphql.ts
Labels: Merge On Green

#6612 fix: allow works from 2020 to show up in that time period bucket
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.jest.tsx
Labels: Merge On Green

#6630 feat: Price estimate flow first QA pass
  src/v2/Apps/Consign/Components/GetPriceEstimate/ArtistInsightResult.tsx
  src/v2/Apps/Consign/Components/GetPriceEstimate/ConsignArtistAutosuggest.tsx
  src/v2/Apps/Consign/Components/GetPriceEstimate/ConsignPriceEstimateContext.tsx
  src/v2/Apps/Consign/Components/GetPriceEstimate/EstimateResults.tsx
  src/v2/Apps/Consign/Components/GetPriceEstimate/GetPriceEstimate.tsx
  src/v2/Apps/Consign/Components/SectionContainer.tsx
  src/v2/__generated__/ConsignPriceEstimateContext_ArtistInsights_Query.graphql.ts
  src/v2/__generated__/ConsignPriceEstimateContext_SearchConnection_Query.graphql.ts
Labels: Squash On Green

#6632 [FX-2380] Uses correctly sized images
  src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
  src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesApp.jest.tsx
  src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesHeader_artistSeries.graphql.ts
  src/v2/__generated__/routes_ArtistSeriesQuery.graphql.ts
Labels: Squash On Green

#6637 Revert "[Experiment] [Novo] Check performance when extracting stuff from old shell "
  .gitignore
  Dockerfile
  hokusai/production.yml
  hokusai/staging.yml
  package.json
  scripts/acceptance.sh
  scripts/smoke_test.sh
  scripts/start.sh
  src/common-app.js
  src/common-middleware.js
  src/current.js
  src/desktop/lib/webpackPublicPath.ts
  src/index.dev.js
  src/index.js
  src/lib/DOMParser.js
  src/lib/manifest.ts
  src/lib/memory_profiler.js
  src/lib/middleware/__tests__/pageCacheMiddleware.jest.ts
  src/lib/middleware/__tests__/unsupportedBrowser.jest.ts
  src/lib/middleware/assetMiddleware.ts
  src/lib/middleware/csrfTokenMiddleware.ts
  src/lib/middleware/intercom.ts
  src/lib/middleware/ipFilter.ts
  src/lib/middleware/morganMiddleware.ts
  src/lib/middleware/pageCacheMiddleware.ts
  src/lib/middleware/sessionMiddleware.ts
  src/lib/middleware/unless.ts
  src/lib/middleware/unsupportedBrowser.ts
  src/lib/setup.js
  src/lib/tti-init.js
  src/novo/src/client.tsx
  src/novo/src/server.ts
  src/test/acceptance/helpers/index.js
  src/v2/Apps/getAppNovoRoutes.tsx
  src/v2/Artsy/Router/buildAppRoutes.tsx
  src/v2/Artsy/Router/buildServerApp.tsx
  tsconfig.json
  webpack/envs/clientCommonConfig.js
  webpack/envs/clientDevelopmentConfig.js
  webpack/envs/clientNovoDevelopmentConfig.js
  webpack/envs/clientNovoProductionConfig.js
  webpack/envs/clientProductionConfig.js
  webpack/envs/index.js
  webpack/envs/serverConfig.js
  webpack/index.js
  webpack/utils/env.js
  webpack/utils/getCSSManifest.js
  yarn.lock
Labels: Merge On Green

#6643 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts
  src/v2/__generated__/routes_ArtistSeriesQuery.graphql.ts
Labels: Merge On Green

#6639 [HACK-8] Fix AddToCalendar link construction and convert to react
  src/desktop/apps/auction/components/layout/auction_info/AuctionInfoDesktop.tsx
  src/desktop/apps/auction/components/layout/auction_info/__tests__/AuctionInfoDesktop.jest.jsx
  src/desktop/components/add_to_calendar/react.js
  src/v2/Components/AddToCalendar/AddToCalendar.tsx
  src/v2/Components/AddToCalendar/__tests__/AddToCalendar.jest.tsx
  src/v2/Components/AddToCalendar/__tests__/helpers.jest.ts
  src/v2/Components/AddToCalendar/helpers.ts
Labels: hackathon

#6648 chore: setup env flag for new show page
  src/desktop/apps/show/routes.coffee
  src/desktop/assets/analytics.ts
  src/desktop/config.coffee
  src/lib/setup_sharify.js
  src/mobile/apps/show/routes.coffee
  src/typings/sharify.d.ts
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/ShowSubApp.tsx
  src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
  src/v2/Apps/Show/routes.tsx
Labels: Jira Synced

#6651 feat: Update title and meta description for /consign2
  src/v2/Apps/Consign/Components/ConsignMeta.tsx
Labels: Merge On Green

#6645 feat: a more complete form for responding to a consignment offer
  src/v2/Apps/Consign/OfferDetail/Components/OfferSummary.tsx
  src/v2/Apps/Consign/OfferDetail/Components/ResponseForm.tsx
  src/v2/Apps/Consign/OfferDetail/Components/StickyFooter.tsx
  src/v2/Apps/Consign/OfferDetail/Components/SubmissionSummary.tsx
  src/v2/Apps/Consign/OfferDetail/Components/Summary.tsx
  src/v2/Apps/Consign/OfferDetail/OfferDetailApp.tsx
  src/v2/Apps/Consign/OfferDetail/Operations/CreateOfferResponse.ts
  src/v2/Apps/Consign/OfferDetailApp.tsx
  src/v2/Apps/Consign/consignRoutes.tsx
  src/v2/__generated__/CreateOfferResponseMutation.graphql.ts
  src/v2/__generated__/OfferDetailApp_offer.graphql.ts
  src/v2/__generated__/OfferSummary_offer.graphql.ts
  src/v2/__generated__/ResponseForm_offer.graphql.ts
  src/v2/__generated__/SubmissionSummary_offer.graphql.ts
  src/v2/__generated__/Summary_offer.graphql.ts
  src/v2/__generated__/consignRoutes_OfferDetailQuery.graphql.ts
Labels: Squash On Green

#6653 feat: Add TemporaryOffer, ArtworkCredits, new average sale price graph for /consign2
  src/v2/Apps/Consign/Components/ArtworkCredits.tsx
  src/v2/Apps/Consign/Components/InDemandNow/ConsignInDemandNow.tsx
  src/v2/Apps/Consign/Components/SellWithArtsy.tsx
  src/v2/Apps/Consign/Components/TemporaryOffer.tsx
  src/v2/Apps/Consign/ConsignApp.tsx
Labels: Merge On Green

#6659 fix: [Consign2] More qa items
  src/v2/Apps/Consign/Components/ContactUs.tsx
  src/v2/Apps/Consign/Components/InDemandNow/ConsignTopArtists.tsx
  src/v2/__generated__/ConsignTopArtistsQuery.graphql.ts
Labels: Squash On Green

#6664 fix: update show page hasViewingRoom determination to use connection
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/routes_ShowQuery.graphql.ts
Labels: Jira Synced

#6670 [FX-2382] Adds alt tags to header images
  src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
Labels: Merge On Green

#6671 [FX-2424] Removes older microdata sitelinks markup
  src/desktop/components/search_bar/templates/index.jade
  src/v2/Components/Search/SearchBar.tsx
Labels: Merge On Green

#6674 Feat: consign2 copy updates
  src/v2/Apps/Consign/Components/ContactUs.tsx
  src/v2/Apps/Consign/Components/FAQ.tsx
  src/v2/Apps/Consign/Components/GetPriceEstimate/ArtistInsightResult.tsx
  src/v2/Apps/Consign/Components/GetPriceEstimate/GetPriceEstimate.tsx
Labels: Squash On Green

#6685 fix: More consign2 QA
  package.json
  src/desktop/assets/analytics.ts
  src/v2/Apps/Consign/Components/ArtworkCredits.tsx
  src/v2/Apps/Consign/Components/ContactUs.tsx
  src/v2/Apps/Consign/Components/GetPriceEstimate/ArtistInsightResult.tsx
  src/v2/Apps/Consign/Components/Header.tsx
  src/v2/Apps/Consign/Components/HowToSell.tsx
  src/v2/Apps/Consign/Components/ReadMore.tsx
  src/v2/Apps/Consign/Components/SellArtDifferently.tsx
  src/v2/Apps/Consign/Components/SellWithArtsy.tsx
  src/v2/Apps/Consign/Components/SoldRecently.tsx
  src/v2/Apps/Consign/Components/TemporaryOffer.tsx
  src/v2/Artsy/Router/buildClientApp.tsx
  yarn.lock
Labels: Merge On Green

#6691 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/AuthenticityCertificateTestQuery.graphql.ts
  src/v2/__generated__/BuyerGuaranteeTestQuery.graphql.ts
  src/v2/__generated__/SecurePaymentTestQuery.graphql.ts
  src/v2/__generated__/VerifiedSellerTestQuery.graphql.ts
Labels: Merge On Green

#6692 Deploy
  data/schema.graphql
  src/v2/__generated__/AuthenticityCertificateTestQuery.graphql.ts
  src/v2/__generated__/BuyerGuaranteeTestQuery.graphql.ts
  src/v2/__generated__/SecurePaymentTestQuery.graphql.ts
  src/v2/__generated__/VerifiedSellerTestQuery.graphql.ts
Labels: Merge On Green

#6695 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6696 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6701 fix: Remove Stashed Webpack Config
  webpack/envs/clientNovoProductionConfig.js
Labels: Merge On Green

#6702 fix: Update TemporaryOffer expiration date and add test
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/TemporaryOffer.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/TemporaryOffer.jest.tsx
Labels: Merge On Green

#6709 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6714 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6723 feature: New Dev Task
  package.json
  scripts/start.sh
Labels: Merge On Green

#6732 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green
