Repository artsy/force, pull requests merged in 2020-01, with the labels that each got.

#4860 [GROW-1661] Launch global nav bar experiment
  CONTRIBUTING.md
  src/desktop/components/main_layout/client.coffee
  src/desktop/components/main_layout/header/templates/index.jade
  src/desktop/components/react/stitch_components/NavBarTest.tsx
  src/desktop/components/react/stitch_components/index.tsx
  src/desktop/components/split_test/running_tests.coffee
Labels: Jira Synced

#4895 Deploy
  CONTRIBUTING.md
  src/desktop/components/main_layout/client.coffee
  src/desktop/components/main_layout/header/templates/index.jade
  src/desktop/components/react/stitch_components/NavBarTest.tsx
  src/desktop/components/react/stitch_components/index.tsx
  src/desktop/components/split_test/running_tests.coffee
  src/mobile/components/layout/stylesheets/footer.styl
  src/mobile/components/layout/templates/footer.jade
Labels: Jira Synced

#4911 Remove webpack bundle analyzer
  bundle-analyzer.config.js
  package.json
  webpack/envs/ciConfig.js
  yarn.lock
Labels: Version: Trivial

#4919 Fix list spacing in markdown pages
  src/desktop/apps/page/index.styl
Labels: Merge On Green

#4918 Deploy
  package.json
  src/desktop/apps/page/index.styl
  src/desktop/apps/show/templates/index.jade
  src/mobile/apps/show/helpers/view_helpers.coffee
  src/mobile/apps/show/routes.coffee
  src/mobile/apps/show/templates/index.jade
  src/mobile/apps/show/test/helpers/view_helpers.test.coffee
  src/test/acceptance/fixtures/metaphysics/collection.json
  yarn.lock
Labels: Jira Synced

#4928 Revert "Remove auction_support apps and related bid/reg support"
  src/desktop/analytics/artwork.js
  src/desktop/apps/auction_reaction/routes.jest.ts
  src/desktop/apps/auction_reaction/routes.tsx
  src/desktop/apps/auction_reaction/server.tsx
  src/desktop/apps/auction_support/client/bid_form.coffee
  src/desktop/apps/auction_support/client/index.coffee
  src/desktop/apps/auction_support/client/registration_form.coffee
  src/desktop/apps/auction_support/index.coffee
  src/desktop/apps/auction_support/mixins/conditions_of_sale.js
  src/desktop/apps/auction_support/routes.coffee
  src/desktop/apps/auction_support/stylesheets/conditions_of_sale_checkbox.styl
  src/desktop/apps/auction_support/stylesheets/index.styl
  src/desktop/apps/auction_support/templates/artwork-info.jade
  src/desktop/apps/auction_support/templates/bid-form.jade
  src/desktop/apps/auction_support/templates/bidding-closed.jade
  src/desktop/apps/auction_support/templates/conditions-of-sale-checkbox.jade
  src/desktop/apps/auction_support/templates/conditions-of-sale-message.jade
  src/desktop/apps/auction_support/templates/registration-error.jade
  src/desktop/apps/auction_support/templates/registration-form-confirmation.jade
  src/desktop/apps/auction_support/templates/registration-form.jade
  src/desktop/apps/auction_support/templates/registration.jade
  src/desktop/apps/auction_support/test/client/bid_form.test.coffee
  src/desktop/apps/auction_support/test/client/registration_form.test.coffee
  src/desktop/apps/auction_support/test/routes.test.coffee
  src/desktop/apps/auction_support/test/templates.test.coffee
  src/desktop/config.coffee
  src/lib/setup_sharify.js
  src/mobile/apps/auction_support/client/index.coffee
  src/mobile/apps/auction_support/client/registration_form.coffee
  src/mobile/apps/auction_support/stylesheets/index.styl
  src/mobile/apps/auction_support/templates/registration-error.jade
  src/mobile/apps/auction_support/templates/registration-form.jade
  src/mobile/apps/auction_support/templates/registration.jade
  src/mobile/apps/auction_support/test/client/registration_form.test.coffee
  src/mobile/apps/auction_support/test/templates.test.coffee
  src/mobile/apps/feature/client/bid_page.coffee
  src/mobile/apps/feature/index.coffee
  src/mobile/apps/feature/routes.coffee
  src/mobile/apps/feature/stylesheets/bid.styl
  src/mobile/apps/feature/stylesheets/index.styl
  src/mobile/apps/feature/templates/bid_page.jade
  src/mobile/apps/feature/templates/confirm_page.jade
  src/mobile/apps/feature/test/client/bid_page.test.coffee
  src/mobile/apps/feature/test/routes.test.coffee
  src/mobile/apps/feature/test/templates.test.coffee
  src/mobile/assets/mobile_all.coffee
Labels: Merge On Green

#4944 Removes FOSSA badge. #trivial
  README.md
Labels: Merge On Green

#4948 Replace broken dependency references
  package.json
  yarn.lock
Labels: Merge On Green

#4955 FX-1745: Close navbar a/b test and revert back to control
  src/desktop/components/main_layout/client.coffee
  src/desktop/components/main_layout/header/templates/index.jade
  src/desktop/components/react/stitch_components/NavBarTest.tsx
  src/desktop/components/react/stitch_components/index.tsx
  src/desktop/components/split_test/running_tests.coffee
Labels: Merge On Green

#4960 @mzikherman => [Package] Bump Reaction to 24.1.6
  package.json
  yarn.lock
Labels: Merge On Green

#4962 @mzikherman => [Package] Bump Reaction to 24.1.7
  package.json
  yarn.lock
Labels: Merge On Green

#4970 Configure env feature flag for request condition report feature
  src/desktop/config.coffee
  src/lib/setup_sharify.js
Labels: Merge On Green

#4980 Updates welcome image credit
  src/desktop/apps/home/welcome.coffee
Labels: Merge On Green

#4979 Refactor overview layout factory to hopefully make more sense
  src/desktop/apps/partner2/client/overview_layout_factory.coffee
  src/desktop/apps/partner2/test/client/overview_layout_factory.test.coffee
Labels: Merge On Green

#4981 I missed one line when I renamed 'purchase' to 'purchases'
  src/desktop/apps/purchases/server.tsx
Labels: Merge On Green

#4984 Rename repcaptcha to recaptcha
  package.json
  src/desktop/components/inquiry_questionnaire/test/views/account.test.ts
  src/desktop/components/inquiry_questionnaire/views/account.coffee
  src/desktop/components/inquiry_questionnaire/views/inquiry.coffee
  src/desktop/components/marketing_signup_modal/index.coffee
  yarn.lock
Labels: Merge On Green
