Repository artsy/force, pull requests merged in 2020-09, with the labels that each got.

#6199 Revert "Decaffeinate mobile/assets"
  src/mobile/assets/mobile_all.coffee
  src/mobile/assets/mobile_all.ts
  src/mobile/assets/mobile_articles.coffee
  src/mobile/assets/mobile_articles.ts
  src/mobile/assets/mobile_artists.coffee
  src/mobile/assets/mobile_artists.ts
  src/mobile/assets/mobile_favorites_following.coffee
  src/mobile/assets/mobile_favorites_following.ts
  src/mobile/assets/mobile_openseadragon.coffee
  src/mobile/assets/mobile_openseadragon.ts
  src/mobile/assets/mobile_show.coffee
  src/mobile/assets/mobile_show.ts
  src/mobile/assets/mobile_user.coffee
  src/mobile/assets/mobile_user.ts
  src/typings/sharify.d.ts
Labels: Merge On Green

#6198 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6206 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6215 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6218 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6207 Load schema from staging/release branch instead of live environment
  scripts/validateSchemas.js
Labels: Merge On Green

#6219 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6231 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6240 Fix broken links in README
  README.md
Labels: Merge On Green

#6225 Remove and migrate notification files
  src/desktop/analytics/notifications.js
  src/desktop/apps/notifications/client/mobile.coffee
  src/desktop/apps/notifications/client/sidebar.coffee
  src/desktop/assets/analytics.ts
Labels: Merge On Green

#6224 Deprecate search/layered search/fair analyticsHooks
  src/desktop/analytics/fair.js
  src/desktop/analytics/layered_search.js
  src/desktop/analytics/search.js
  src/desktop/apps/fair/client/for_you.coffee
  src/desktop/apps/fair/client/overview.coffee
  src/desktop/apps/search/client/index.coffee
  src/desktop/apps/search/test/client/index.test.js
  src/desktop/assets/analytics.ts
  src/desktop/components/fair_layout/client/nav.coffee
  src/desktop/components/search_bar/test/view.test.js
  src/desktop/components/search_bar/view.coffee
Labels: Merge On Green

#6130 Begin deepcrawl automator integration
  .circleci/config.yml
Labels: Merge On Green

#6247 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6254 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6256 @anandaroop => [Search] Use toString on search term, to avoid GraphQL type crash on term
  src/v2/Apps/Search/routes.tsx
  src/v2/__generated__/routes_SearchResultsArtistsQuery.graphql.ts
  src/v2/__generated__/routes_SearchResultsEntityQuery.graphql.ts
  src/v2/__generated__/routes_SearchResultsTopLevelQuery.graphql.ts
Labels: Merge On Green

#6259 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6271 Fixes pixel to spacing scale value conversion
  src/v2/Apps/Artist/Components/ArtistHeader.tsx
  src/v2/Apps/Artist/Components/ArtistIndicator.tsx
Labels: Merge On Green

#6278 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6284 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6282 chore(type): Update desktop fairs landing page typography
  src/desktop/apps/fairs/stylesheets/index.styl
  src/desktop/apps/fairs/templates/index.jade
  src/desktop/components/main_layout/stylesheets/buttons.styl
Labels: Merge On Green

#6288 [typography] Desktop homepage conversion
  src/desktop/apps/home/components/artists_to_follow/stylesheets/index.styl
  src/desktop/apps/home/components/followed_artists/index.styl
  src/desktop/apps/home/components/followed_artists/templates/context.jade
  src/desktop/apps/home/components/related_artists_context/annotation.jade
  src/desktop/apps/home/stylesheets/featured_items.styl
  src/desktop/apps/home/stylesheets/hero_units.styl
  src/desktop/apps/home/stylesheets/modules.styl
  src/desktop/apps/home/templates/hero_unit.jade
  src/desktop/components/artist_cell/index.styl
  src/desktop/components/artwork_brick_rail/index.styl
  src/desktop/components/artwork_brick_rail/templates/index.jade
  src/desktop/components/artwork_metadata_stub/index.styl
  src/desktop/components/featured_shows/index.styl
  src/desktop/components/follow_button/artist_suggestions.jade
  src/desktop/components/follow_button/index.styl
  src/desktop/components/main_layout/footer/index.styl
  src/desktop/components/main_layout/stylesheets/buttons.styl
  src/desktop/components/merry_go_round/index.styl
  src/desktop/components/recently_viewed_artworks/index.jade
  src/desktop/components/slider/index.jade
  src/lib/palette.styl
  src/v2/Components/CollectionsHubsHomepageNav.tsx
Labels: Merge On Green

#6290 Revert heading of collect page for SEO juiciness
  cypress/integration/collect.spec.js
  src/test/acceptance/collect.js
  src/v2/Apps/Collect/Routes/Collect/index.tsx
Labels: Merge On Green

#6286 Deploy
  data/schema.graphql
  hokusai/production.yml
  src/desktop/apps/fairs/stylesheets/index.styl
  src/desktop/apps/fairs/templates/index.jade
  src/desktop/apps/home/components/artists_to_follow/stylesheets/index.styl
  src/desktop/apps/home/components/followed_artists/index.styl
  src/desktop/apps/home/components/followed_artists/templates/context.jade
  src/desktop/apps/home/components/related_artists_context/annotation.jade
  src/desktop/apps/home/stylesheets/featured_items.styl
  src/desktop/apps/home/stylesheets/hero_units.styl
  src/desktop/apps/home/stylesheets/modules.styl
  src/desktop/apps/home/templates/hero_unit.jade
  src/desktop/apps/partner2/templates/meta.jade
  src/desktop/apps/partner2/test/templates.test.js
  src/desktop/components/artist_cell/index.styl
  src/desktop/components/artwork_brick_rail/index.styl
  src/desktop/components/artwork_brick_rail/templates/index.jade
  src/desktop/components/artwork_metadata_stub/index.styl
  src/desktop/components/featured_shows/index.styl
  src/desktop/components/follow_button/artist_suggestions.jade
  src/desktop/components/follow_button/index.styl
  src/desktop/components/main_layout/footer/index.styl
  src/desktop/components/main_layout/stylesheets/buttons.styl
  src/desktop/components/merry_go_round/index.styl
  src/desktop/components/recently_viewed_artworks/index.jade
  src/desktop/components/slider/index.jade
  src/lib/palette.styl
  src/mobile/apps/art_fairs/index.styl
  src/mobile/apps/art_fairs/templates/index.jade
  src/mobile/apps/art_fairs/test/template.test.js
  src/mobile/components/layout/stylesheets/buttons.styl
  src/v2/Apps/Collect/Routes/Collect/index.tsx
  src/v2/Components/CollectionsHubsHomepageNav.tsx
  src/v2/Components/CollectionsHubsNav.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/FollowedArtistsFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/GalleryFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/InstitutionFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/OptionText.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
Labels: Jira Synced

#6263 Implement order history for XS screens
  src/v2/Apps/Purchase/Components/PurchaseHistory.tsx
  src/v2/Apps/Purchase/__tests__/PurchaseApp.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/Components/NavBar/Menus/UserMenu.tsx
  src/v2/Components/NavBar/Menus/__tests__/UserMenu.jest.tsx
  src/v2/__generated__/PurchaseAppTestQuery.graphql.ts
  src/v2/__generated__/PurchaseHistoryQuery.graphql.ts
  src/v2/__generated__/PurchaseHistory_me.graphql.ts
  src/v2/__generated__/routes_PurchaseQuery.graphql.ts
Labels: Jira Synced, Merge On Green

#6297 Typography cleanup: Search results page
  src/v2/Apps/Search/Components/SendFeedback.tsx
  src/v2/Apps/Search/Components/ZeroState.tsx
  src/v2/Apps/Search/SearchApp.tsx
Labels: Merge On Green

#6299 [Typography] Update mobile auctions landing page (and fix fairs)
  src/mobile/apps/art_fairs/index.styl
  src/mobile/apps/art_fairs/templates/past-fairs.jade
  src/mobile/apps/auctions/index.styl
  src/mobile/apps/auctions/templates/index.jade
  src/mobile/components/avant_garde_tabs/index.styl
Labels: Merge On Green

#6296 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6304 fix: Correct a faulty href in submenu data
  src/v2/Components/NavBar/menuData.ts
Labels: Merge On Green

#6306 @anandaroop => [Filter] Expose 18th Century & Earlier period filter
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.jest.tsx
Labels: Merge On Green

#6302 Search results typography followup: minor changes
  src/v2/Apps/Search/Components/ZeroState.tsx
  src/v2/Apps/Search/SearchApp.tsx
  src/v2/Apps/Search/__tests__/SearchApp.jest.tsx
Labels: Merge On Green

#6312 Tweaks to legibility of auction clock
  src/desktop/components/clock/index.styl
  src/desktop/components/clock/view.coffee
  src/mobile/apps/fair_info/test/routes.test.js
Labels: Merge On Green

#6313 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6315 [Typography] Update responsive collection and collections landing pages
  src/v2/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
  src/v2/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
  src/v2/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/v2/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
  src/v2/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
  src/v2/Apps/Collect/Routes/Collection/Components/Header/FeaturedArtists.tsx
  src/v2/Apps/Collect/Routes/Collection/Components/Header/index.tsx
  src/v2/Apps/Collect/Routes/Collections/Components/CollectionsGrid.tsx
  src/v2/Apps/Collect/Routes/Collections/index.tsx
Labels: Merge On Green

#6331 Puts back data-test attr for desktop
  src/v2/Apps/Artist/Components/ArtistHeader.tsx
Labels: Merge On Green

#6339 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6340 Require type check before deploying to staging
  .circleci/config.yml
Labels: Merge On Green

#6346 chore [a11y]: replace auction result anchors with buttons
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
Labels: Merge On Green

#6351 fix: display auction result sale date without considering local time zone
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/v2/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
Labels: Jira Synced, Merge On Green

#6353 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6354 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6350 Deploy
  .eslintrc.js
  data/schema.graphql
  src/desktop/assets/analytics.ts
  src/desktop/config.coffee
  src/lib/setup_sharify.js
  src/mobile/config.coffee
  src/typings/sharify.d.ts
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/v2/Apps/IdentityVerification/IdentityVerificationApp/WrongOwner.tsx
  src/v2/Apps/IdentityVerification/IdentityVerificationApp/index.tsx
  src/v2/Apps/IdentityVerification/__fixtures__/routes_IdentityVerificationAppQuery.ts
  src/v2/Apps/IdentityVerification/__tests__/IdentityVerificationApp.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
  src/v2/Artsy/Relay/createRelaySSREnvironment.ts
  src/v2/Artsy/Relay/middleware/metaphysicsExtensionsLoggerMiddleware.ts
  src/v2/Components/__stories__/Gene.story.tsx
  src/v2/Components/__stories__/ModalDialog.story.tsx
  src/v2/Components/__stories__/Tag.story.tsx
  src/v2/Utils/__tests__/logger.jest.ts
  src/v2/__generated__/IdentityVerificationAppTestQuery.graphql.ts
  src/v2/__generated__/IdentityVerificationApp_me.graphql.ts
  src/v2/__generated__/routes_IdentityVerificationAppQuery.graphql.ts
Labels: Jira Synced

#6327 Implement order management for M/X/XL
  src/desktop/components/user_interests/test/view.test.js
  src/v2/Apps/Purchase/Components/PurchaseHistory.tsx
  src/v2/Apps/Purchase/__tests__/PurchaseApp.jest.tsx
  src/v2/Apps/ViewingRoom/Components/ViewingRoomCarousel.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/Components/NavBar/Menus/UserMenu.tsx
  src/v2/__generated__/PurchaseAppTestQuery.graphql.ts
  src/v2/__generated__/PurchaseHistoryQuery.graphql.ts
  src/v2/__generated__/PurchaseHistory_me.graphql.ts
  src/v2/__generated__/routes_PurchaseQuery.graphql.ts
Labels: Jira Synced

#6359 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6360 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6342 New CTAs for user with pending identity verification
  src/desktop/apps/auction/components/layout/auction_info/Registration.tsx
  src/desktop/apps/auction/components/layout/auction_info/__tests__/Registration.jest.js
  src/desktop/apps/auction/queries/v2/me.ts
Labels: Jira Synced

#6362 Includes HTML styling on ReadMore instances
  src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromArtsy.tsx
  src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
Labels: Merge On Green

#6365 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6367 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6369 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6372 chore: move WIP fairs page from /fair2 to /fair
  src/v2/Apps/Fair/Components/FairFollowedArtists.tsx
  src/v2/Apps/Fair/Components/FairHeader.tsx
  src/v2/Apps/Fair/Components/__tests__/FairHeader.jest.tsx
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/Apps/Fair/FairSubApp.tsx
  src/v2/Apps/Fair/routes.tsx
Labels: Jira Synced

#6376 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6382 @dzucconi => [Fair] Tweak route path regexp to handle linking to artworks tab w/ query params
  src/v2/Apps/Fair/routes.tsx
Labels: Merge On Green
