Repository artsy/force, pull requests merged in 2020-06, with the labels that each got.

#5692 @pvinis => [Cypress] Adjust Gagosian description for profile test
  cypress/integration/partnerProfile.spec.js
  src/v2/Components/Gene/__tests__/GeneRelatedLinks.jest.tsx
Labels: Merge On Green, Test

#5694 Conversation not updated correctly when new messages is entered by collector
  src/v2/Apps/Conversation/Components/Reply.tsx
  src/v2/Apps/Conversation/Mutation/SendConversationMessage.ts
Labels: Jira Synced

#5659 Utilizes ModalBase to lock scroll on mobile filters
  src/v2/Components/v2/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx
Labels: Merge On Green

#5689 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5691 Fixes a bug where user sees error message telling them to accept conditions of sale after they've already checked the checkbox
  src/v2/Apps/Auction/Components/BidForm.tsx
  src/v2/Apps/Auction/Components/RegistrationForm.tsx
Labels: Merge On Green

#5701 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5697 Upgrades to styled-system v5
  package.json
  src/v2/Apps/Conversation/ConversationApp.tsx
  src/v2/Assets/Theme.ts
  src/v2/Components/Artwork/GridItem.tsx
  src/v2/Components/Icon.tsx
  src/v2/Components/NavBar/NavBar.tsx
  src/v2/Components/NavBar/NavItem.tsx
  src/v2/Utils/Section.tsx
  yarn.lock
Labels: Review App

#5704 Revert "Size bucket filtering [FX-1948]"
  src/v2/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/SizeFilter.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/v2/Apps/Components/SizeFilter.jest.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeRangeFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/SizeRangeFilter.jest.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/index.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkQueryFilter.tsx
  src/v2/Components/v2/ArtworkFilter/Utils/isDefaultFilter.tsx
  src/v2/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/v2/ArtworkFilter/index.tsx
  src/v2/__generated__/ArtworkFilter_viewer.graphql.ts
  src/v2/__generated__/ArtworkQueryFilterQuery.graphql.ts
Labels: Jira Synced

#5699 Fix a bug where user gets unhelpful error message when encountering Stripe error on bid+register form
  src/v2/Apps/Auction/Components/BidForm.tsx
  src/v2/Apps/Auction/Components/RegistrationForm.tsx
  src/v2/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/v2/Apps/Auction/Routes/__tests__/ConfirmBid.jest.tsx
  src/v2/Apps/Auction/Routes/__tests__/Register.jest.tsx
Labels: Merge On Green

#5720 Make path lookup safer
  src/lib/datadog.ts
Labels: Merge On Green

#5717 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5708 Size bucket filtering v2 [FX-1948]
  src/v2/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/Artist/Routes/Works/index.tsx
  src/v2/Apps/Artist/routes.tsx
  src/v2/Apps/Collect/Routes/Collection/CollectionAppQuery.tsx
  src/v2/Apps/Collect/Routes/Collection/index.tsx
  src/v2/Apps/Collect/collectRoutes.tsx
  src/v2/Apps/Components/SizeFilter.jest.tsx
  src/v2/Apps/Components/SizeFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeRangeFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/SizeRangeFilter.jest.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/index.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkQueryFilter.tsx
  src/v2/Components/v2/ArtworkFilter/Utils/isDefaultFilter.tsx
  src/v2/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/v2/ArtworkFilter/index.tsx
  src/v2/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ArtistArtworkFilter_artist.graphql.ts
  src/v2/__generated__/ArtworkFilter_viewer.graphql.ts
  src/v2/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/v2/__generated__/CollectionAppQuery.graphql.ts
  src/v2/__generated__/Collection_collection.graphql.ts
  src/v2/__generated__/Works_Test_Query.graphql.ts
  src/v2/__generated__/Works_artist.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/routes_WorksQuery.graphql.ts
Labels: Jira Synced

#5722 Deploy
  src/v2/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/Artist/Routes/Works/index.tsx
  src/v2/Apps/Artist/routes.tsx
  src/v2/Apps/Collect/Routes/Collection/CollectionAppQuery.tsx
  src/v2/Apps/Collect/Routes/Collection/index.tsx
  src/v2/Apps/Collect/collectRoutes.tsx
  src/v2/Apps/Components/SizeFilter.jest.tsx
  src/v2/Apps/Components/SizeFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeRangeFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/SizeRangeFilter.jest.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/index.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkQueryFilter.tsx
  src/v2/Components/v2/ArtworkFilter/Utils/isDefaultFilter.tsx
  src/v2/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/v2/ArtworkFilter/index.tsx
  src/v2/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ArtistArtworkFilter_artist.graphql.ts
  src/v2/__generated__/ArtworkFilter_viewer.graphql.ts
  src/v2/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/v2/__generated__/CollectionAppQuery.graphql.ts
  src/v2/__generated__/Collection_collection.graphql.ts
  src/v2/__generated__/Works_Test_Query.graphql.ts
  src/v2/__generated__/Works_artist.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/routes_WorksQuery.graphql.ts
Labels: Jira Synced

#5737 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5741 Instrument Datadog Redis Tracing
  src/lib/datadog.ts
Labels: Merge On Green

#5750 Remove failing slack alerts
  .circleci/config.yml
Labels: Merge On Green

#5753 @damassi => [Assets] Skip profile check for erroneous asset route
  src/desktop/apps/profile/routes.coffee
  src/desktop/apps/profile/test/routes.test.coffee
Labels: Merge On Green

#5754 Date of the last message not updated in conversation
  src/v2/Apps/Conversation/Components/Conversation.tsx
Labels: Jira Synced

#5756 Correct conversation optimistic response to use messagesConnection
  src/v2/Apps/Conversation/Mutation/SendConversationMessage.ts
Labels: Merge On Green

#5760 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5765 [AppShell] Add `debug-routes` app for baseline tests
  src/v2/Apps/Debug/debugRoutes.tsx
  src/v2/Apps/getAppRoutes.tsx
Labels: Merge On Green

#5761 Deploy
  .circleci/config.yml
  data/schema.graphql
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarExtraLinks.jest.tsx
  src/v2/Apps/Debug/debugRoutes.tsx
  src/v2/Apps/Order/Components/__tests__/StickyFooter.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
  src/v2/Apps/getAppRoutes.tsx
  src/v2/Artsy/Analytics/Schema/Values.ts
  src/v2/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/v2/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/v2/__generated__/AuctionResults_Test_Query.graphql.ts
  src/v2/__generated__/routes_AuctionResultsQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#5777 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5770 Use the error modal to display any error message on the registration form
  src/v2/Apps/Auction/Components/RegistrationForm.tsx
  src/v2/Apps/Auction/Components/__stories__/RegistrationForm.story.tsx
  src/v2/Apps/Auction/Routes/Register/index.tsx
  src/v2/Apps/Auction/Routes/__tests__/Register.jest.tsx
Labels: Merge On Green

#5778 Add Cohesion tracking to artist Top Works content
  src/v2/Apps/Artist/Components/ArtistTopWorksRail/ArtistTopWorksRail.tsx
  src/v2/Apps/Artist/Components/ArtistTopWorksRail/__tests__/ArtistTopWorksRail.jest.tsx
  src/v2/__generated__/ArtistTopWorksRail_artist.graphql.ts
  src/v2/__generated__/Works_Test_Query.graphql.ts
  src/v2/__generated__/routes_OverviewQuery.graphql.ts
  src/v2/__generated__/routes_WorksQuery.graphql.ts
Labels: Merge On Green

#5771 Display error messages from Stripe as a credit card field error
  src/v2/Apps/Auction/Components/Form/__tests__/helpers.jest.tsx
  src/v2/Apps/Auction/Components/Form/helpers.tsx
  src/v2/Apps/Auction/Components/RegistrationForm.tsx
  src/v2/Apps/Auction/Operations/CreateCreditCardAndUpdatePhone.ts
  src/v2/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/v2/Apps/Auction/Routes/Register/index.tsx
  src/v2/Apps/Auction/Routes/__fixtures__/MutationResults/createCreditCardAndUpdatePhone.ts
  src/v2/Apps/Auction/Routes/__tests__/ConfirmBid.jest.tsx
  src/v2/Apps/Auction/Routes/__tests__/Register.jest.tsx
Labels: Merge On Green

#5787 [Toolchain] Fix storybooks
  .storybook/webpack.config.js
Labels: Toolchain

#5796 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5790 Upgrades @artsy/palette => 11.0.x
  package.json
  src/v2/Apps/Conversation/Components/Details.tsx
  src/v2/Components/ArtistCard.tsx
  src/v2/Components/Search/Suggestions/SuggestionItem.tsx
  src/v2/Components/__tests__/__snapshots__/Artwork.jest.tsx.snap
  yarn.lock
Labels: Merge On Green

#5800 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5803 Possibly fix the loading issue on the auction registration form
  src/desktop/apps/auction_reaction/client.tsx
Labels: Merge On Green

#5802 Fix cohesion TS errors in tracking Notable Works rail content
  package.json
  src/v2/Apps/Artist/Components/ArtistTopWorksRail/ArtistTopWorksRail.tsx
  src/v2/Artsy/Analytics/Schema/index.ts
  yarn.lock
Labels: Merge On Green

#5811 Fixes an issue where spinner does not show up on registration and bid+register forms
  src/v2/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/v2/Apps/Auction/Routes/Register/index.tsx
Labels: Merge On Green

#5813 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5809 Render attachments in conversation threads and details
  src/v2/Apps/Conversation/Components/Details.tsx
  src/v2/Apps/Conversation/Components/Message.tsx
  src/v2/__generated__/Details_conversation.graphql.ts
  src/v2/__generated__/Message_message.graphql.ts
  src/v2/__generated__/SendConversationMessageMutation.graphql.ts
  src/v2/__generated__/routes_DetailQuery.graphql.ts
Labels: Merge On Green

#5820 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5784 [PURCHASE-1953] style show inquiry item and refactor Item component
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/__tests__/Conversation.jest.tsx
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/routes_DetailQuery.graphql.ts
Labels: Jira Synced

#5817 Make Artist Page Rails "Fully bleed" Screen on Mobile
  cypress/integration/artist.spec.js
  src/v2/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionsRail.tsx
  src/v2/Apps/Artist/Components/ArtistTopWorksRail/ArtistTopWorksRail.tsx
  src/v2/Apps/Artist/Components/ArtistTopWorksRail/__tests__/ArtistTopWorksRail.jest.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/WorksForSaleRail.tsx
  src/v2/Apps/Artist/Routes/Overview/__tests__/index.jest.tsx
  src/v2/Apps/Artist/Routes/Works/__tests__/Works.jest.tsx
  src/v2/Components/Artwork/Fillwidth.tsx
  src/v2/Components/Artwork/FillwidthItem.tsx
  src/v2/Components/Artwork/__tests__/Details.jest.tsx
  src/v2/Components/RecentlyViewed.tsx
  src/v2/Components/__stories__/Carousel.story.tsx
Labels: Merge On Green

#5825 Revert "followup after changes on formattedEndAt on MP [GALL-2988]"
  data/schema.graphql
  package.json
  scripts/sync-schema-local.sh
  scripts/sync-schema-pull.sh
  src/v2/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
  src/v2/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts
  src/v2/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts
  src/v2/__generated__/ViewingRoomApp_UnfoundTest_Query.graphql.ts
  src/v2/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
  src/v2/__generated__/routes_ViewingRoomQuery.graphql.ts
Labels: Jira Synced

#5812 Deploy
  cypress/integration/artist.spec.js
  data/schema.graphql
  package.json
  scripts/sync-schema-local.sh
  scripts/sync-schema-pull.sh
  src/v2/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionsRail.tsx
  src/v2/Apps/Artist/Components/ArtistTopWorksRail/ArtistTopWorksRail.tsx
  src/v2/Apps/Artist/Components/ArtistTopWorksRail/__tests__/ArtistTopWorksRail.jest.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/WorksForSaleRail.tsx
  src/v2/Apps/Artist/Routes/Overview/__tests__/index.jest.tsx
  src/v2/Apps/Artist/Routes/Works/__tests__/Works.jest.tsx
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/Details.tsx
  src/v2/Apps/Conversation/Components/Message.tsx
  src/v2/Apps/Conversation/Components/Reply.tsx
  src/v2/Apps/Conversation/Components/__tests__/Conversation.jest.tsx
  src/v2/Apps/Conversation/Mutation/SendConversationMessage.ts
  src/v2/Apps/Conversation/routes.tsx
  src/v2/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
  src/v2/Components/Artwork/Fillwidth.tsx
  src/v2/Components/Artwork/FillwidthItem.tsx
  src/v2/Components/Artwork/__tests__/Details.jest.tsx
  src/v2/Components/FlashBanner/__tests__/FlashBanner.jest.tsx
  src/v2/Components/FlashBanner/index.tsx
  src/v2/Components/RecentlyViewed.tsx
  src/v2/Components/__stories__/Carousel.story.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/GalleryFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/InstitutionFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/Details_conversation.graphql.ts
  src/v2/__generated__/Message_message.graphql.ts
  src/v2/__generated__/SendConversationMessageMutation.graphql.ts
  src/v2/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts
  src/v2/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts
  src/v2/__generated__/ViewingRoomApp_UnfoundTest_Query.graphql.ts
  src/v2/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
  src/v2/__generated__/routes_DetailQuery.graphql.ts
  src/v2/__generated__/routes_ViewingRoomQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#5826 Deploy
  src/desktop/apps/consign/components/choose_artist/index.js
  src/desktop/apps/consign/components/location_autocomplete/index.js
  src/desktop/apps/consign/components/upload_photo/index.js
Labels: Jira Synced

#5829 Revert "Revert "followup after changes on formattedEndAt on MP [GALL-2988]""
  data/schema.graphql
  package.json
  scripts/sync-schema-local.sh
  scripts/sync-schema-pull.sh
  src/v2/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
  src/v2/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts
  src/v2/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts
  src/v2/__generated__/ViewingRoomApp_UnfoundTest_Query.graphql.ts
  src/v2/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
  src/v2/__generated__/routes_ViewingRoomQuery.graphql.ts
Labels: Jira Synced, Merge On Green

#5833 Deploy
  .env.oss
  package.json
  src/desktop/apps/about/index.coffee
  src/desktop/apps/about/routes.coffee
  src/desktop/apps/about/test/routes.test.coffee
  src/desktop/apps/auction_lots/client/index.coffee
  src/desktop/apps/auction_lots/index.coffee
  src/desktop/apps/auction_lots/routes.coffee
  src/desktop/apps/auction_lots/stylesheets/index.styl
  src/desktop/apps/auction_lots/templates/artist.jade
  src/desktop/apps/auction_lots/templates/detail.jade
  src/desktop/apps/auction_lots/test/routes.test.coffee
  src/desktop/apps/editorial_features/components/venice_2017/client/index.coffee
  src/desktop/apps/editorial_features/components/venice_2017/templates/video_description.jade
  src/desktop/apps/editorial_features/index.coffee
  src/desktop/apps/editorial_features/routes.coffee
  src/desktop/apps/editorial_features/test/routes.test.coffee
  src/desktop/assets/auctions.coffee
  src/desktop/assets/auctions.styl
  src/desktop/config.coffee
  src/desktop/index.ts
  src/v2/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionsRail.tsx
  yarn.lock
Labels: Jira Synced

#5839 @dzucconi => [Artists] Update page to use Metaphysics V2
  src/desktop/apps/artists/query.coffee
  src/desktop/apps/artists/routes.coffee
  src/desktop/components/artist_cell/query2.coffee
Labels: Merge On Green

#5840 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5847 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5836 Deploy
  data/schema.graphql
  hokusai/staging.yml
  package.json
  src/desktop/apps/artists/query.coffee
  src/desktop/apps/artists/routes.coffee
  src/desktop/components/artist_cell/query2.coffee
  src/mobile/apps/home/routes.coffee
  src/mobile/apps/home/templates/page.jade
  src/mobile/apps/home/test/routes.test.coffee
  src/v2/Apps/ViewingRoom/ViewingRoomsApp.tsx
  src/v2/Apps/ViewingRoom/__tests__/ViewingRoomsApp.jest.tsx
  src/v2/Apps/ViewingRoom/routes.tsx
  src/v2/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
  src/v2/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.jest.tsx
  src/v2/Components/NavBar/NavBar.tsx
  src/v2/Components/__stories__/NavBar.story.tsx
  src/v2/__generated__/ViewingRoomsApp_Test_Query.graphql.ts
  src/v2/__generated__/ViewingRoomsApp_viewingRooms.graphql.ts
  src/v2/__generated__/routes_ViewingRoomsAppQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#5845 [GALL-3003] - Adding Body to VR display.
  src/v2/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomBody.tsx
  src/v2/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomPullQuote.tsx
  src/v2/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorks.tsx
  src/v2/Apps/ViewingRoom/Routes/Statement/ViewingRoomStatementRoute.tsx
  src/v2/Apps/ViewingRoom/Routes/Statement/__tests__/ViewingRoomStatementRoute.jest.tsx
  src/v2/__generated__/ViewingRoomBody_viewingRoom.graphql.ts
  src/v2/__generated__/ViewingRoomStatementRoute_Test_Query.graphql.ts
  src/v2/__generated__/ViewingRoomStatementRoute_viewingRoom.graphql.ts
  src/v2/__generated__/routes_ViewingRoomStatementRouteQuery.graphql.ts
Labels: Merge On Green

#5848 Up the limit on number of items in a set to show in a feature (still no pagination)
  src/v2/Apps/Feature/Components/FeatureSet.tsx
Labels: Merge On Green

#5843 Initial artist series page
  src/v2/Apps/ArtistSeries/ArtistSeriesApp.tsx
  src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
  src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesApp.jest.tsx
  src/v2/Apps/ArtistSeries/routes.tsx
  src/v2/Apps/getAppRoutes.tsx
  src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_artistSeries.graphql.ts
  src/v2/__generated__/ArtistSeriesHeader_artistSeries.graphql.ts
  src/v2/__generated__/routes_ArtistSeriesQuery.graphql.ts
Labels: Merge On Green

#5850 Update metaphysics schema
  src/v2/__generated__/FeatureApp_Test_Query.graphql.ts
  src/v2/__generated__/FeatureSet_set.graphql.ts
  src/v2/__generated__/routes_FeatureQuery.graphql.ts
Labels: Merge On Green

#5849 Deploy
  data/schema.graphql
  src/desktop/apps/user/components/tabs/index.styl
  src/v2/Apps/ArtistSeries/ArtistSeriesApp.tsx
  src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
  src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesApp.jest.tsx
  src/v2/Apps/ArtistSeries/routes.tsx
  src/v2/Apps/Feature/Components/FeatureSet.tsx
  src/v2/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomBody.tsx
  src/v2/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomPullQuote.tsx
  src/v2/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorks.tsx
  src/v2/Apps/ViewingRoom/Routes/Statement/ViewingRoomStatementRoute.tsx
  src/v2/Apps/ViewingRoom/Routes/Statement/__tests__/ViewingRoomStatementRoute.jest.tsx
  src/v2/Apps/getAppRoutes.tsx
  src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_artistSeries.graphql.ts
  src/v2/__generated__/ArtistSeriesHeader_artistSeries.graphql.ts
  src/v2/__generated__/ViewingRoomBody_viewingRoom.graphql.ts
  src/v2/__generated__/ViewingRoomStatementRoute_Test_Query.graphql.ts
  src/v2/__generated__/ViewingRoomStatementRoute_viewingRoom.graphql.ts
  src/v2/__generated__/routes_ArtistSeriesQuery.graphql.ts
  src/v2/__generated__/routes_ViewingRoomStatementRouteQuery.graphql.ts
Labels: Jira Synced

#5853 Add data attrs for integrity tests to auth form links
  src/v2/Components/Authentication/Footer.tsx
  src/v2/Components/Authentication/commonElements.tsx
Labels: Merge On Green
