Repository artsy/force, pull requests merged in 2020-10, with the labels that each got.

#6383 Includes artwork id in details key to force re-render
  src/v2/Apps/Artwork/ArtworkApp.tsx
Labels: Merge On Green

#6380 @sweir27 => [Fair] Tweak display of collections to include count of works
  src/v2/Apps/Fair/Components/FairCollections/FairCollection.tsx
  src/v2/Apps/Fair/Components/__tests__/FairCollection.jest.tsx
  src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
  src/v2/__generated__/FairApp_Query.graphql.ts
  src/v2/__generated__/FairCollection_Query.graphql.ts
  src/v2/__generated__/FairCollection_collection.graphql.ts
  src/v2/__generated__/routes_FairQuery.graphql.ts
Labels: Merge On Green

#6366 feat: artwork page - link to user idv flow if applicable
  src/desktop/apps/auction/components/layout/auction_info/Registration.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarBidAction.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarBidAction.ts
  src/v2/Utils/identityVerificationRequirements.ts
  src/v2/__generated__/ArtworkSidebarBidAction_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarBidAction_me.graphql.ts
  src/v2/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Squash On Green

#6373 feat: implement redirection logic for new /fair page
  src/desktop/apps/fair/fairRedirection.ts
  src/desktop/apps/fair/index.coffee
  src/desktop/apps/fair/test/fairRedirection.jest.ts
  src/desktop/apps/fair_info/index.coffee
  src/desktop/config.coffee
Labels: Squash On Green

#6389 fix: Add Missing Release Script
  package.json
Labels: Merge On Green

#6396 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/v2/__generated__/ArtistsQuery.graphql.ts
  src/v2/__generated__/Artists_gene.graphql.ts
  src/v2/__generated__/ArtworkFilterArtworkGrid2_filtered_artworks.graphql.ts
  src/v2/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/v2/__generated__/CollectionAppQuery.graphql.ts
  src/v2/__generated__/Collection_collection.graphql.ts
  src/v2/__generated__/Dropdown_aggregation.graphql.ts
  src/v2/__generated__/FairArtworksQuery.graphql.ts
  src/v2/__generated__/FairArtworks_Query.graphql.ts
  src/v2/__generated__/GeneArtworks_gene.graphql.ts
  src/v2/__generated__/TagArtworks_tag.graphql.ts
  src/v2/__generated__/Works_Test_Query.graphql.ts
  src/v2/__generated__/Works_artist.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/routes_ArtistSeriesQuery.graphql.ts
  src/v2/__generated__/routes_FairArtworksQuery.graphql.ts
  src/v2/__generated__/routes_WorksQuery.graphql.ts
Labels: Merge On Green

#6398 Removes hack to force re-rendering of ArtworkDetails
  src/v2/Apps/Artwork/ArtworkApp.tsx
Labels: Merge On Green

#6403 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6404 Update modal text for pending auction reservation due to IDV
  src/desktop/apps/auction/components/layout/ConfirmRegistrationModal.tsx
  src/desktop/apps/auction/components/layout/__tests__/ConfirmRegistrationModal.jest.tsx
  src/v2/Components/Auction/PostRegistrationModal.tsx
Labels: Jira Synced

#6415 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ShowInstallShots_show.graphql.ts
  src/v2/__generated__/routes_ShowQuery.graphql.ts
Labels: Merge On Green

#6418 chore: Deprecate unused jquery filter analytics
  src/desktop/analytics/artworks_filter.js
  src/desktop/assets/analytics.ts
  src/desktop/components/filter2/dropdown/view.coffee
  src/desktop/components/filter2/view.coffee
  src/mobile/analytics/commercial_filter.js
  src/mobile/assets/mobile_analytics.ts
  src/mobile/components/filter2/view.coffee
Labels: Merge On Green

#6427 chore(FX-2330): Migrate mWeb /art_fairs to Metaphysics V2
  src/mobile/apps/art_fairs/client/art_fairs.coffee
  src/mobile/apps/art_fairs/query.coffee
  src/mobile/apps/art_fairs/routes.coffee
Labels: Jira Synced

#6428 chore(FX-2329): Migrate desktop /fairs client to V2
  src/desktop/apps/fairs/client/index.coffee
Labels: Jira Synced, Squash On Green

#6411 Deploy
  .circleci/config.yml
  data/schema.graphql
  package.json
  src/desktop/analytics/artist_page.js
  src/desktop/analytics/artwork_rail.js
  src/desktop/analytics/artworks_filter.js
  src/desktop/analytics/genes.js
  src/desktop/analytics/home.js
  src/desktop/apps/consign/stylesheets/index.styl
  src/desktop/apps/fairs/client/index.coffee
  src/desktop/apps/home/client/hero_unit_view.coffee
  src/desktop/apps/home/client/index.coffee
  src/desktop/apps/home/client/setup_home_page_modules.coffee
  src/desktop/apps/home/components/new_for_you/index.coffee
  src/desktop/assets/analytics.ts
  src/desktop/assets/artists_artworks.styl
  src/desktop/components/artwork_rail/client/view.coffee
  src/desktop/components/artwork_rail/stylesheets/index.styl
  src/desktop/components/artwork_rail/templates/index.jade
  src/desktop/components/artwork_rail/templates/loading.jade
  src/desktop/components/filter2/dropdown/view.coffee
  src/desktop/components/filter2/view.coffee
  src/mobile/analytics/commercial_filter.js
  src/mobile/apps/art_fairs/client/art_fairs.coffee
  src/mobile/apps/art_fairs/query.coffee
  src/mobile/apps/art_fairs/routes.coffee
  src/mobile/assets/mobile_analytics.ts
  src/mobile/components/filter2/view.coffee
  src/v2/Apps/Artist/Components/__tests__/ArtistConsignButton.jest.tsx
  src/v2/Apps/Fair/Components/FairFollowedArtists.tsx
  src/v2/Apps/Fair/Components/__tests__/FairFollowedArtists.jest.tsx
  src/v2/Apps/Fair/Routes/FairArtworks.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
  src/v2/Apps/Fair/routes.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
  src/v2/Apps/Show/__tests__/ShowInstallShots.jest.tsx
  src/v2/Apps/Show/components/ShowInstallShots.tsx
  src/v2/Apps/Show/components/ShowMeta.tsx
  src/v2/Apps/Show/routes.tsx
  src/v2/Apps/getAppRoutes.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
  src/v2/Components/v2/ArtworkFilter/Utils/fetchFollowedArtists.ts
  src/v2/__generated__/ArtistConsignButton_Test_Query.graphql.ts
  src/v2/__generated__/FairApp_Query.graphql.ts
  src/v2/__generated__/FairFollowedArtists_fair.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/ShowInstallShots_show.graphql.ts
  src/v2/__generated__/ShowMeta_show.graphql.ts
  src/v2/__generated__/fetchFollowedArtistsQuery.graphql.ts
  src/v2/__generated__/routes_FairQuery.graphql.ts
  src/v2/__generated__/routes_ShowQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#6426 chore: Consolidate logout handling / remove auth:logged-out analyticsHook
  src/desktop/analytics/helpers.ts
  src/desktop/lib/global_client_setup.tsx
  src/mobile/apps/partner_profile/test/artist.test.js
  src/mobile/apps/partner_profile/test/client/artworks.test.js
  src/mobile/apps/shows/test/view.test.js
  src/mobile/apps/user/client/view.coffee
  src/mobile/apps/user/test/view.jest.ts
  src/mobile/apps/user/test/view.test.js
  src/mobile/components/layout/bootstrap.coffee
  src/mobile/components/layout/test/layout.jest.ts
  src/mobile/components/layout/test/layout.test.js
Labels: Merge On Green

#6439 Remove 'this' from GeneArtistView tests
  src/mobile/apps/gene/test/view.test.js
Labels: Merge On Green

#6440 chore: Address decaf/jquery issues in mocha tests
  src/mobile/apps/fair/test/client/exhibitors.test.js
  src/mobile/apps/favorites_following/test/client/following.test.js
  src/mobile/apps/home/test/client_view.test.js
  src/mobile/apps/shows/test/view.test.js
  src/mobile/apps/unsubscribe/test/client.test.js
Labels: Merge On Green

#6437 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6445 bugfix: Fix leaky magazine test
  src/mobile/apps/articles/test/client/articles.test.js
Labels: Merge On Green

#6446 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6450 bugfix: cleanup flakey Fair feed test
  src/mobile/apps/fair/test/client/feed.test.js
Labels: Merge On Green

#6452 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6436 feat: new user setting tabs
  src/desktop/apps/user/stylesheets/index.styl
  src/desktop/apps/user/templates/layout.jade
  src/desktop/components/react/stitch_components/index.tsx
  src/v2/Apps/Purchase/Components/OrderRow.tsx
  src/v2/Apps/Purchase/Components/PurchaseHistory.tsx
  src/v2/Apps/Purchase/Utils/orderHelper.tsx
  src/v2/Apps/Purchase/__tests__/PurchaseApp.jest.tsx
  src/v2/Apps/Purchase/routes.tsx
  src/v2/Components/UserSettings/UserSettingsTabs.tsx
  src/v2/Components/UserSettings/__tests__/UserSettingsTabs.jest.tsx
  src/v2/__generated__/OrderRow_order.graphql.ts
  src/v2/__generated__/PurchaseAppTestQuery.graphql.ts
  src/v2/__generated__/PurchaseHistoryQuery.graphql.ts
  src/v2/__generated__/PurchaseHistory_me.graphql.ts
  src/v2/__generated__/routes_PurchaseQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#6460 trivial: Add data attrs for integrity to bid buttons
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
Labels: Merge On Green

#6461 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/SearchResultsEntityQuery.graphql.ts
  src/v2/__generated__/routes_SearchResultsEntityQuery.graphql.ts
Labels: Merge On Green

#6462 @dzucconi => [Show] Rename to uppercase Components/ folder
  src/v2/Apps/Show/Components/ShowAbout.tsx
  src/v2/Apps/Show/Components/ShowArtworks.tsx
  src/v2/Apps/Show/Components/ShowContextualLink.tsx
  src/v2/Apps/Show/Components/ShowHeader.tsx
  src/v2/Apps/Show/Components/ShowInstallShots.tsx
  src/v2/Apps/Show/Components/ShowMeta.tsx
  src/v2/Apps/Show/Components/ShowViewingRoom.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/__tests__/ShowArtworks.jest.tsx
  src/v2/Apps/Show/__tests__/ShowContextualLink.jest.tsx
  src/v2/Apps/Show/__tests__/ShowInstallShots.jest.tsx
Labels: Squash On Green

#6455 [FX-2206] Show info page
  src/v2/Apps/Show/Components/ShowAbout.tsx
  src/v2/Apps/Show/Components/ShowArtworks.tsx
  src/v2/Apps/Show/Components/ShowInfoLocation.tsx
  src/v2/Apps/Show/Components/ShowInstallShots.tsx
  src/v2/Apps/Show/Components/ShowPartnerEntityHeader.tsx
  src/v2/Apps/Show/Routes/ShowInfo.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/ShowSubApp.tsx
  src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
  src/v2/Apps/Show/__tests__/ShowInfo.jest.tsx
  src/v2/Apps/Show/routes.tsx
  src/v2/__generated__/ShowAbout_show.graphql.ts
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/ShowInfoLocation_show.graphql.ts
  src/v2/__generated__/ShowInfo_Test_Query.graphql.ts
  src/v2/__generated__/ShowInfo_show.graphql.ts
  src/v2/__generated__/ShowInstallShots_show.graphql.ts
  src/v2/__generated__/ShowPartnerEntityHeader_partner.graphql.ts
  src/v2/__generated__/ShowSubApp_show.graphql.ts
  src/v2/__generated__/routes_ShowInfoQuery.graphql.ts
  src/v2/__generated__/routes_ShowQuery.graphql.ts
  src/v2/__generated__/routes_ShowSubAppQuery.graphql.ts
Labels: Merge On Green

#6463 @damassi => [Dev] Add plug in to warn about case insensitive imports
  package.json
  webpack/envs/clientDevelopmentConfig.js
  yarn.lock
Labels: Merge On Green

#6466 @dzucconi => [Show] Add context card for a fair
  src/v2/Apps/Show/Components/ShowContextCard.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/__tests__/ShowContextCard.jest.tsx
  src/v2/Components/FairCard.tsx
  src/v2/__generated__/FairCard_fair.graphql.ts
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/ShowContextCard_Test_Query.graphql.ts
  src/v2/__generated__/ShowContextCard_show.graphql.ts
  src/v2/__generated__/routes_ShowQuery.graphql.ts
Labels: Merge On Green

#6470 bugfix: move backbone jquery declaration in flakey test
  src/mobile/apps/fair/test/client/for_you.test.js
Labels: Squash On Green

#6443 refactor: Consolidate pageType/pageSlug logic
  src/desktop/analytics/main_layout.ts
  src/desktop/analytics/timeOnPageListener.ts
  src/desktop/apps/artsy-v2/apps/artist/artistMiddleware.tsx
  src/desktop/apps/artsy-v2/apps/artwork/artworkClient.tsx
  src/desktop/apps/artsy-v2/apps/search/searchMiddleware.tsx
  src/desktop/apps/artsy-v2/client.tsx
  src/desktop/apps/artsy-v2/server.tsx
  src/desktop/apps/artsy-v2/utils/__tests__/getPageType.jest.ts
  src/desktop/apps/artsy-v2/utils/getPageType.ts
  src/lib/__tests__/getPageType.jest.ts
  src/lib/getPageType.ts
  src/lib/middleware/__tests__/pageCacheMiddleware.jest.ts
  src/lib/middleware/pageCacheMiddleware.ts
  src/mobile/analytics/before_ready.ts
  src/mobile/assets/mobile_analytics.ts
  src/typings/sharify.d.ts
Labels: Squash On Green

#6471 @dzucconi => [Show] Add context card for a partner
  src/v2/Apps/Show/Components/ShowContextCard.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/__tests__/ShowContextCard.jest.tsx
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/ShowContextCard_Test_Query.graphql.ts
  src/v2/__generated__/ShowContextCard_show.graphql.ts
  src/v2/__generated__/routes_ShowQuery.graphql.ts
Labels: Squash On Green

#6473 ShowPartnerEntityHeader follow button uses typesafe props
  src/v2/Apps/Show/Components/ShowPartnerEntityHeader.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/ShowSubApp.tsx
  src/v2/Components/FollowButton/FollowProfileButton.tsx
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/ShowInfo_Test_Query.graphql.ts
  src/v2/__generated__/ShowSubApp_show.graphql.ts
  src/v2/__generated__/routes_ShowInfoQuery.graphql.ts
  src/v2/__generated__/routes_ShowQuery.graphql.ts
  src/v2/__generated__/routes_ShowSubAppQuery.graphql.ts
Labels: Merge On Green

#6480 Returns string for non-nullable field
  src/v2/Apps/Feature/__tests__/fixtures.ts
Labels: Squash On Green

#6484 fix(FX-2324): Move scrollY to previous position after content change
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
Labels: Jira Synced

#6489 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6490 fix: Missing Package Async
  package.json
  yarn.lock
Labels: Merge On Green

#6486 enhancement: Purchase history enhancements
  src/v2/Apps/Purchase/Components/OrderRow.tsx
  src/v2/Apps/Purchase/PurchaseApp.tsx
  src/v2/Apps/Purchase/__tests__/PurchaseApp.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/Components/NavBar/Menus/MobileNavMenu/LoggedInLinks.tsx
  src/v2/Components/NavBar/Menus/UserMenu.tsx
  src/v2/Components/NavBar/Menus/__tests__/UserMenu.jest.tsx
  src/v2/Components/NavBar/__tests__/NavBarTracking.jest.tsx
  src/v2/__generated__/OrderRow_order.graphql.ts
  src/v2/__generated__/PurchaseAppTestQuery.graphql.ts
  src/v2/__generated__/PurchaseHistoryQuery.graphql.ts
  src/v2/__generated__/routes_PurchaseQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#6498 fix: update labels for fair page sections
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
Labels: Squash On Green

#6505 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6510 fix: Start Inspect
  scripts/start.sh
Labels: Merge On Green

#6512 fix: apply new fair redirection logic to mobile fair app
  src/mobile/apps/fair/index.coffee
Labels: Jira Synced

#6514 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6516 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6520 fix: Don't try to render missing images in Artist Series rail
  cypress/integration/collections.spec.js
  src/v2/Components/ArtistSeriesRail/ArtistSeriesItem.tsx
  src/v2/Components/ArtistSeriesRail/__tests__/ArtistSeriesItem.jest.tsx
Labels: Merge On Green

#6519 [consign2] Add Header and Get Price Estimate sections
  src/v2/Apps/Consign/Components/GetPriceEstimate.tsx
  src/v2/Apps/Consign/Components/Header.tsx
  src/v2/Apps/Consign/Components/SectionContainer.tsx
  src/v2/Apps/Consign/ConsignApp.tsx
Labels: Squash On Green

#6522 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6525 feat: Add Selling Art Differently section
  src/v2/Apps/Consign/Components/SellArtDifferently.tsx
  src/v2/Apps/Consign/ConsignApp.tsx
Labels: Squash On Green

#6528 fix: render 404 page when fair is not found
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/Apps/Fair/routes.tsx
  src/v2/__generated__/routes_FairArtworksQuery.graphql.ts
  src/v2/__generated__/routes_FairExhibitorsQuery.graphql.ts
  src/v2/__generated__/routes_FairInfoQuery.graphql.ts
  src/v2/__generated__/routes_FairQuery.graphql.ts
  src/v2/__generated__/routes_FairSubAppQuery.graphql.ts
Labels: Jira Synced

#6544 fix: Decaffeination Export Error
  src/mobile/collections/install_shots.coffee
  src/mobile/models/install_shot.ts
Labels: Squash On Green

#6538 Deploy
  package.json
  src/lib/setup.js
  src/mobile/collections/install_shots.coffee
  src/mobile/models/install_shot.ts
  src/v2/Apps/Consign/Components/HowToSell.tsx
  src/v2/Apps/Consign/Components/SellArtDifferently.tsx
  src/v2/Apps/Consign/ConsignApp.tsx
  src/v2/Apps/Show/Components/ShowViewingRoom.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/ShowSubApp.tsx
  src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
  src/v2/Apps/Show/__tests__/ShowViewingRoom.jest.tsx
  src/v2/Apps/Show/routes.tsx
  src/v2/Apps/ViewingRoom/Components/ViewingRoomsFeaturedRail.tsx
  src/v2/Apps/ViewingRoom/Components/ViewingRoomsLatestGrid.tsx
  src/v2/Components/ViewingRoomCard.tsx
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/ShowViewingRoom_Test_Query.graphql.ts
  src/v2/__generated__/ShowViewingRoom_show.graphql.ts
  src/v2/__generated__/routes_ShowInfoQuery.graphql.ts
  src/v2/__generated__/routes_ShowQuery.graphql.ts
  src/v2/__generated__/routes_ShowSubAppQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#6552 Uses appropriate image versions for small thumbs on viewing room cards
  src/v2/Apps/ViewingRoom/Components/ViewingRoomsLatestGrid.tsx
  src/v2/Apps/ViewingRoom/__tests__/ViewingRoomsApp.jest.tsx
  src/v2/__generated__/ViewingRoomsApp_Test_Query.graphql.ts
  src/v2/__generated__/ViewingRoomsLatestGrid_ViewingRoomsAppQuery.graphql.ts
  src/v2/__generated__/ViewingRoomsLatestGrid_viewingRooms.graphql.ts
  src/v2/__generated__/routes_ViewingRoomsAppQuery.graphql.ts
Labels: Merge On Green

#6556 [FX-2370] Minor show2 Q/A items
  src/v2/Apps/Show/Components/ShowInstallShots.tsx
  src/v2/Apps/Show/ShowSubApp.tsx
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowInstallShots_show.graphql.ts
  src/v2/__generated__/ShowSubApp_show.graphql.ts
  src/v2/__generated__/routes_ShowQuery.graphql.ts
  src/v2/__generated__/routes_ShowSubAppQuery.graphql.ts
Labels: Squash On Green

#6554 feat: [Consign2] Add remaining sections
  src/v2/Apps/Artist/Routes/Consign/Components/SectionContainer.tsx
  src/v2/Apps/Consign/Components/ContactUs.tsx
  src/v2/Apps/Consign/Components/FAQ.tsx
  src/v2/Apps/Consign/Components/InDemandNow/DemandRank.tsx
  src/v2/Apps/Consign/Components/ReadMore.tsx
  src/v2/Apps/Consign/Components/SectionContainer.tsx
  src/v2/Apps/Consign/Components/SellWithArtsy.tsx
  src/v2/Apps/Consign/Components/SoldRecently.tsx
  src/v2/Apps/Consign/ConsignApp.tsx
Labels: Merge On Green

#6558 Fix onboarding search results
  src/v2/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
  src/v2/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
  src/v2/__generated__/ArtistSearchResultsQuery.graphql.ts
  src/v2/__generated__/ArtistSearchResults_viewer.graphql.ts
  src/v2/__generated__/GeneSearchResultsQuery.graphql.ts
  src/v2/__generated__/GeneSearchResults_viewer.graphql.ts
Labels: Squash On Green

#6561 bugfix: check for missing analytics libs before firing
  src/desktop/analytics/helpers.ts
  src/desktop/lib/global_client_setup.tsx
Labels: Merge On Green

#6568 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green
