Repository artsy/force, pull requests merged in 2020-05, with the labels that each got.

#5518 Update Circle CI config node+yarn orb versions
  .circleci/config.yml
Labels: Merge On Green

#5525 [2FA] Pass through OTP in login request to Gravity
  package.json
  src/desktop/models/logged_out_user.coffee
  src/desktop/test/models/logged_out_user.test.coffee
  yarn.lock
Labels: Merge On Green

#5500 Add a section to docs on authenticating locally
  CONTRIBUTING.md
Labels: Version: Trivial

#5370 Automate review app building via CircleCI
  .circleci/config.yml
  .circleci/deploy_event.sh
  docs/creating_review_app.md
  hokusai/config.yml
  scripts/build_review_app.sh
  scripts/update_review_app.sh
Labels: Merge On Green

#5552 Fixes issue where new feature page wouldn't show if you're part of the client nav experiment group
  src/desktop/apps/feature-reaction/server.tsx
Labels: Merge On Green

#5554 Add new feature page routing to mobile web
  src/mobile/apps/feature/routes.coffee
  src/mobile/apps/feature/test/routes.test.coffee
Labels: Merge On Green

#5579 Add lab feature to reveal 2FA enrollment UI
  src/desktop/apps/user/pages/settings/index.jade
Labels: Merge On Green

#5584 Exclude more reaction apps from pageview tracking
  src/desktop/analytics/main_layout.js
Labels: Merge On Green

#5602 Removes adminOnly middleware on new feature routes
  src/desktop/apps/feature-reaction/server.tsx
  src/desktop/apps/viewing-room/server.tsx
Labels: Merge On Green

#5640 Some post-reaction-merge cleanup
  .circleci/config.yml
  CONTRIBUTING.md
  data/schema.graphql
  package.json
  scripts/start.sh
  scripts/validateSchemas.js
  src/v2/Apps/Conversation/Components/Conversation.tsx
Labels: Merge On Green

#5641 Update metaphysics schema
  src/v2/__generated__/ArtistConsignMarketTrends_artist.graphql.ts
  src/v2/__generated__/ArtistConsignPageViews_artist.graphql.ts
  src/v2/__generated__/ConsignRoute_Test_Query.graphql.ts
  src/v2/__generated__/routes_ArtistConsignQuery.graphql.ts
Labels: Merge On Green

#5643 No tests on staging or release
  .circleci/config.yml
Labels: Merge On Green

#5644 [CI] Remove workflow queue
  .circleci/config.yml
Labels: Merge On Green

#5645 [Analytics] Fix double firing
  src/desktop/assets/analytics.coffee
  src/desktop/lib/global_client_setup.tsx
Labels: Merge On Green

#5664 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/CreateBackupSecondFactorsMutation.graphql.ts
  src/v2/__generated__/DisableSecondFactorMutation.graphql.ts
  src/v2/__generated__/EnableSecondFactorMutation.graphql.ts
Labels: Merge On Green

#5665 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5656 Selected conversation missing "select" state
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/ConversationSnippet.tsx
  src/v2/Apps/Conversation/Components/Conversations.tsx
  src/v2/Apps/Conversation/Routes/Conversation/index.tsx
  src/v2/__generated__/Conversation_me.graphql.ts
  src/v2/__generated__/routes_DetailQuery.graphql.ts
Labels: Jira Synced

#5666 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5672 #trivial add data attrs for order form steps
  src/v2/Apps/Order/Routes/Payment/index.tsx
  src/v2/Apps/Order/Routes/Review/index.tsx
  src/v2/Apps/Order/Routes/Shipping/index.tsx
Labels: Merge On Green

#5681 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#5683 [Toolchain] Update express-reloadable to watch v2 files
  src/lib/setup.js
Labels: Toolchain
