Repository artsy/force, pull requests merged in 2020-12, with the labels that each got.

#6735 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/CreateCreditCardAndUpdatePhoneMutation.graphql.ts
Labels: Merge On Green

#6738 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6747 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6749 feature: Bundle Luxon in Utility Chunk
  webpack/envs/clientNovoProductionConfig.js
Labels: Merge On Green

#6748 feature: Preload
  src/novo/src/index.ejs
Labels: Merge On Green

#6755 chore: Fix prettier formatter
  .vscode/settings.json
Labels: Merge On Green

#6757 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6760 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6765 fix(fx-2527): handles 404 in routes
  src/v2/Apps/Artists/Routes/ArtistsByLetter.tsx
  src/v2/Apps/Artists/artistsRoutes.tsx
Labels: Squash On Green

#6770 chore(fx-2515): installs/enables eslint jest plugin
  .eslintrc.js
  package.json
  yarn.lock
Labels: Merge On Green

#6781 fix: enable client-side-hot-reload
  src/novo/src/client.tsx
Labels: Merge On Green

#6783 feature: Hot Reload Refactor
  src/common-app.js
  src/novo/src/routes.ts
  src/novo/src/server.ts
Labels: Merge On Green

#6785 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/CreateAppSecondFactorMutation.graphql.ts
  src/v2/__generated__/CreateSmsSecondFactorMutation.graphql.ts
Labels: Merge On Green

#6774 Confirm password before changing 2fa settings
  src/v2/Components/Authentication/Validators.tsx
  src/v2/Components/ConfirmPasswordModal/Mutations/ConfirmPassword.ts
  src/v2/Components/ConfirmPasswordModal/__tests__/ConfirmPasswordModal.jest.tsx
  src/v2/Components/ConfirmPasswordModal/index.tsx
  src/v2/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
  src/v2/Components/UserSettings/TwoFactorAuthentication/Components/DisableFactorConfirmation.tsx
  src/v2/Components/UserSettings/TwoFactorAuthentication/Components/Mutation/DisableSecondFactor.ts
  src/v2/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
  src/v2/__generated__/ConfirmPasswordMutation.graphql.ts
Labels: Merge On Green

#6792 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6794 bug: Add white-space: pre-wrap style to artwork details, exhitibion history, literature, and provenance
  src/v2/Apps/Artwork/Components/ArtworkDetails/index.tsx
Labels: Merge On Green

#6793 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6804 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6828 fix: Remove eslint object sort plugin
  .eslintrc.js
  package.json
  yarn.lock
Labels: Merge On Green

#6829 Update COA language on artwork page
  src/v2/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
Labels: Jira Synced

#6830 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6808 chore: Convert `desktop/lib` to TypeScript
  src/desktop/apps/about/index.coffee
  src/desktop/apps/armory_week/index.ts
  src/desktop/apps/art_keeps_going/server.tsx
  src/desktop/apps/artsy_in_miami/index.ts
  src/desktop/apps/auctions2/index.js
  src/desktop/apps/basel_week/index.ts
  src/desktop/apps/consign/index.js
  src/desktop/apps/contact/index.coffee
  src/desktop/apps/eoy_2016/index.coffee
  src/desktop/apps/frieze_week/index.ts
  src/desktop/apps/frieze_week_london/index.ts
  src/desktop/apps/gallery_partnerships/index.coffee
  src/desktop/apps/how_auctions_work/index.coffee
  src/desktop/apps/jobs/index.coffee
  src/desktop/apps/marketing_signup_modals/index.coffee
  src/desktop/apps/partnerships/index.coffee
  src/desktop/apps/press/index.coffee
  src/desktop/apps/ssr-experiments/server.tsx
  src/desktop/components/filter2/dropdown/label_map.coffee
  src/desktop/components/json_page/README.md
  src/desktop/lib/admin_only.ts
  src/desktop/lib/denylist.coffee
  src/desktop/lib/global_client_setup.tsx
  src/desktop/lib/positronql.ts
  src/desktop/lib/template_modules.coffee
  src/desktop/lib/template_modules.ts
  src/desktop/test/lib/admin_only.test.js
  src/desktop/test/lib/positronql.test.js
  src/lib/middleware/locals.ts
Labels: Merge On Green

#6836 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6838 feat(fx-2466/fx-2571): medium/classifications modal
  src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/v2/Apps/Artwork/Components/ArtworkDetailsMediumModal.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarClassification.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarClassification.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebarClassificationsModal.tsx
  src/v2/Apps/Artwork/Components/__tests__/ArtworkDetailsMediumModal.jest.tsx
  src/v2/Apps/Artwork/Components/__tests__/ArtworkSidebarClassificationsModal.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Artwork/ArtworkDetails.ts
  src/v2/Components/ArtworkClassifications.tsx
  src/v2/__generated__/ArtworkDetailsAdditionalInfo_artwork.graphql.ts
  src/v2/__generated__/ArtworkDetailsMediumModal_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkDetailsMediumModal_artwork.graphql.ts
  src/v2/__generated__/ArtworkDetailsQuery.graphql.ts
  src/v2/__generated__/ArtworkDetails_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarClassificationsModalQuery.graphql.ts
  src/v2/__generated__/ArtworkSidebarClassificationsModal_viewer.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Merge On Green

#6841 fix: Novo Script Loader
  cypress/integration/partnerProfile.spec.js
  src/lib/scriptLoader.ts
Labels: Merge On Green

#6845 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6847 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/CreateCreditCardAndUpdatePhoneMutation.graphql.ts
  src/v2/__generated__/UpdateUserInformationMutation.graphql.ts
Labels: Merge On Green

#6853 fix: Collection Test Retry
  cypress/integration/collection.spec.js
Labels: Merge On Green

#6855 fix: Docker Packages Folder
  .dockerignore
  Dockerfile
Labels: Merge On Green
