Repository artsy/force, pull requests merged in 2020-02, with the labels that each got.

#5000 Remove appShell related code that was causing 404 on staging and prod
  src/desktop/apps/purchases/server.tsx
Labels: Merge On Green

#5003 Remove unused stitch components
  src/desktop/components/react/stitch_components/index.tsx
Labels: Merge On Green

#5014 Deploy
  package.json
  src/desktop/apps/article/components/FollowButton.ts
  src/desktop/apps/article/components/InfiniteScrollArticle.tsx
  src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
  src/desktop/apps/article/components/__tests__/App.jest.tsx
  src/desktop/apps/article/components/__tests__/InfiniteScrollArticle.jest.tsx
  src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.jest.tsx
  src/desktop/apps/article/components/layouts/Article.tsx
  src/desktop/apps/article/components/layouts/__tests__/Article.jest.tsx
  yarn.lock
Labels: Jira Synced

#5024 Bundle Splitting take 2
  .babelrc
  cypress/integration/home.spec.js
  package.json
  src/desktop/apps/experimental-app-shell/client.tsx
  src/desktop/apps/experimental-app-shell/server.tsx
  src/desktop/components/main_layout/templates/experimental_app_shell.jade
  src/lib/webpack-dev-server.js
  webpack/envs/baseConfig.js
  yarn.lock
Labels: Toolchain

#5033 Deploy
  package.json
  src/desktop/components/main_layout/templates/react_blank_index.jade
  src/mobile/components/layout/templates/main.jade
  src/mobile/components/marketing_signup_modal/README.md
  src/mobile/components/marketing_signup_modal/index.jade
  src/mobile/components/marketing_signup_modal/index.styl
  yarn.lock
Labels: Toolchain

#5041 [Toolchain] Implement Webpack/@loadable-components bundle splitting
  .babelrc
  cypress/integration/home.spec.js
  package.json
  scripts/acceptance.sh
  src/desktop/apps/artist/client.tsx
  src/desktop/apps/artwork/client.tsx
  src/desktop/apps/collect/client.js
  src/desktop/apps/experimental-app-shell/client.tsx
  src/desktop/apps/experimental-app-shell/server.tsx
  src/desktop/components/main_layout/templates/experimental_app_shell.jade
  src/lib/webpack-dev-server.js
  webpack/envs/baseConfig.js
  yarn.lock
Labels: Toolchain

#5051 Deploy
  .babelrc
  cypress/integration/home.spec.js
  package.json
  scripts/acceptance.sh
  src/desktop/analytics/account_creation.js
  src/desktop/apps/artist/client.tsx
  src/desktop/apps/artist/server.tsx
  src/desktop/apps/artwork/client.tsx
  src/desktop/apps/collect/client.js
  src/desktop/apps/collect/server.tsx
  src/desktop/apps/experimental-app-shell/client.tsx
  src/desktop/apps/experimental-app-shell/server.tsx
  src/desktop/assets/fairs.styl
  src/desktop/assets/main_layout.styl
  src/desktop/components/auth_modal/eigen.coffee
  src/desktop/components/auth_modal/gdpr_signup.styl
  src/desktop/components/auth_modal/index.styl
  src/desktop/components/auth_modal/maps.coffee
  src/desktop/components/auth_modal/templates/_gdpr_signup.jade
  src/desktop/components/auth_modal/templates/_header.jade
  src/desktop/components/auth_modal/templates/_login_footer.jade
  src/desktop/components/auth_modal/templates/_signup_footer.jade
  src/desktop/components/auth_modal/templates/forgot.jade
  src/desktop/components/auth_modal/templates/login.jade
  src/desktop/components/auth_modal/templates/register.jade
  src/desktop/components/auth_modal/templates/reset.jade
  src/desktop/components/auth_modal/templates/signup.jade
  src/desktop/components/auth_modal/test/eigen.test.coffee
  src/desktop/components/auth_modal/test/templates.test.coffee
  src/desktop/components/auth_modal/test/view.test.coffee
  src/desktop/components/auth_modal/view.coffee
  src/desktop/components/fair_layout/client/header.coffee
  src/desktop/components/fair_layout/test/client/header.test.coffee
  src/desktop/components/inquiry_questionnaire/helpers.coffee
  src/desktop/components/inquiry_questionnaire/views/account.coffee
  src/desktop/components/main_layout/header/test/view.coffee
  src/desktop/components/main_layout/templates/experimental_app_shell.jade
  src/desktop/components/react/gdpr/GDPRCheckbox.js
  src/desktop/components/split_test/running_tests.coffee
  src/desktop/config.coffee
  src/lib/middleware/pageCacheMiddleware.ts
  src/lib/setup.js
  src/lib/webpack-dev-server.js
  webpack/envs/baseConfig.js
  yarn.lock
Labels: Toolchain

#5081 [Clientside Nav] Fix path to orders
  src/desktop/apps/experimental-app-shell/order/orderMiddleware.tsx
Labels: Merge On Green

#5083 Remove trailing ? from article redirect slug
  src/desktop/apps/article/gallery_insights_redirects.ts
Labels: Merge On Green

#5092 Ensure dynamic chunks get cdn url prefix
  src/lib/middleware/assetMiddleware.ts
  webpack/envs/productionConfig.js
Labels: Merge On Green

#5106 Move cdn envs to docker image
  Dockerfile
  hokusai/test.yml
Labels: Merge On Green

#5109 Remove trailing ? from article redirect slug
  src/desktop/apps/article/gallery_insights_redirects.ts
Labels: Merge On Green

#5110 Hard-code CDN for now
  Dockerfile
  src/desktop/apps/experimental-app-shell/apps/search/searchMiddleware.tsx
  src/desktop/lib/global_client_setup.tsx
  webpack/envs/baseConfig.js
Labels: Merge On Green

#5099 [ClientSide Routing] Launch v3 AB test / Simplify A/B testing
  .babelrc
  package.json
  src/desktop/apps/experimental-app-shell/apps/artwork/artworkClient.tsx
  src/desktop/apps/experimental-app-shell/client.tsx
  src/desktop/apps/experimental-app-shell/server.tsx
  src/desktop/assets/main_layout.styl
  src/desktop/components/split_test/middleware.coffee
  src/desktop/components/split_test/running_tests.coffee
  src/desktop/components/split_test/skipIfClientSideRoutingEnabled.ts
  src/desktop/components/split_test/splitTestContext.ts
  src/desktop/components/view_in_room/index.styl
  src/desktop/components/view_in_room/view.coffee
  src/desktop/index.js
  src/index.js
  src/lib/setup.js
  yarn.lock
Labels: Toolchain

#5115 Deploy
  .babelrc
  package.json
  src/desktop/apps/experimental-app-shell/apps/artwork/artworkClient.tsx
  src/desktop/apps/experimental-app-shell/client.tsx
  src/desktop/apps/experimental-app-shell/server.tsx
  src/desktop/assets/main_layout.styl
  src/desktop/components/split_test/middleware.coffee
  src/desktop/components/split_test/running_tests.coffee
  src/desktop/components/split_test/skipIfClientSideRoutingEnabled.ts
  src/desktop/components/split_test/splitTestContext.ts
  src/desktop/components/view_in_room/index.styl
  src/desktop/components/view_in_room/view.coffee
  src/desktop/index.js
  src/index.js
  src/lib/setup.js
  yarn.lock
Labels: Toolchain

#5117 @damassi => [App Shell] Move guard into middleware, and always mount
  src/desktop/apps/experimental-app-shell/server.tsx
  src/desktop/components/split_test/skipIfClientSideRoutingEnabled.ts
  src/desktop/index.js
Labels: Merge On Green

#5112 Add conversation app
  src/desktop/apps/conversations/client.tsx
  src/desktop/apps/conversations/server.tsx
  src/desktop/assets/conversations.styl
  src/desktop/assets/conversations.tsx
  src/desktop/index.js
Labels: Merge On Green

#5121 [Experiment] Update path
  src/desktop/apps/experimental-app-shell/server.tsx
Labels: Merge On Green

#5130 Deploy
  package.json
  yarn.lock
Labels: Jira Synced

#5131 [MX-210] - Add domain verification file for apple sign in
  src/desktop/public/apple-developer-domain-association.txt
Labels: Merge On Green

#5133 [MX-210] - Move verification file to correct folder
  src/desktop/public/.well-known/apple-developer-domain-association.txt
Labels: Merge On Green

#5132 Deploy
  .nvmrc
  src/desktop/public/.well-known/apple-developer-domain-association.txt
  yarn.lock
Labels: Jira Synced

#5136 [MX-210] - Change verification file to staging file
  src/desktop/public/.well-known/apple-developer-domain-association.txt
Labels: Merge On Green

#5139 [MX-218] - Change verification file to prod file
  src/desktop/public/.well-known/apple-developer-domain-association.txt
Labels: Merge On Green

#5138 [Clientside Nav] Move to conventional A/B test structure
  cypress/integration/artist.spec.js
  package.json
  src/desktop/apps/auction_support/index.coffee
  src/desktop/apps/experimental-app-shell/client.tsx
  src/desktop/apps/experimental-app-shell/server.tsx
  src/desktop/components/main_layout/templates/experimental_app_shell.jade
  src/desktop/components/split_test/middleware.coffee
  src/desktop/components/split_test/skipIfClientSideRoutingEnabled.ts
  src/desktop/components/split_test/splitTestContext.ts
  src/index.js
  src/lib/setup.js
  yarn.lock
Labels: Merge On Green

#5140 Deploy
  package.json
  src/desktop/public/.well-known/apple-developer-domain-association.txt
  yarn.lock
Labels: Jira Synced
