Repository artsy/force, pull requests merged in 2021-01, with the labels that each got.

#6859 Add recaptcha key to local auth instructions
  CONTRIBUTING.md
Labels: Merge On Green

#6872 bugfix: Fix pagination bug with non-artworkgrid components
  src/v2/Apps/Artist/Routes/Articles/ArtistArticles.tsx
  src/v2/Apps/Artist/Routes/Shows/ArtistShows.tsx
  src/v2/Apps/Artists/artistsRoutes.tsx
  src/v2/Apps/Search/searchRoutes.tsx
  src/v2/Components/Pagination/useComputeHref.ts
  src/v2/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
Labels: Merge On Green

#6880 Revert "chore: Switch auction_registrations to use mp v2"
  src/desktop/apps/user/components/auction_registrations/query.coffee
  src/desktop/apps/user/components/auction_registrations/view.coffee
Labels: Merge On Green

#6711 feature: Example demonstrating how to create a new app
  src/v2/Apps/Example/README.md
  src/v2/Apps/Example/Routes/Example/ExampleApp.tsx
  src/v2/Apps/Example/Routes/ExampleArtist/ExampleArtistApp.tsx
  src/v2/Apps/Example/Routes/ExampleArtwork/ExampleArtworkApp.tsx
  src/v2/Apps/Example/Routes/Welcome/WelcomeApp.tsx
  src/v2/Apps/Example/exampleRoutes.tsx
  src/v2/Apps/getAppRoutes.tsx
  src/v2/__generated__/ExampleApp_system.graphql.ts
  src/v2/__generated__/ExampleArtistApp_artist.graphql.ts
  src/v2/__generated__/ExampleArtworkApp_artwork.graphql.ts
  src/v2/__generated__/exampleRoutes_ArtistQuery.graphql.ts
  src/v2/__generated__/exampleRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/exampleRoutes_ExampleQuery.graphql.ts
Labels: Jira Synced

#6900 fix(AuctionResults):Display 'bought in' based on boughtIn flag from Metaphysics
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
  src/v2/__generated__/ArtistAuctionResultItem_auctionResult.graphql.ts
  src/v2/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/v2/__generated__/AuctionResults_Test_Query.graphql.ts
  src/v2/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
Labels: Squash On Green

#6908 chore(deps): bumps palette
  package.json
  yarn.lock
Labels: Merge On Green

#6856 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6911 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6914 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6922 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtworkSidebarQuery.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/AuctionTimerQuery.graphql.ts
  src/v2/__generated__/AuctionTimer_sale.graphql.ts
  src/v2/__generated__/ConsignInDemandNowQuery.graphql.ts
  src/v2/__generated__/ConsignPriceEstimateContext_ArtistInsights_Query.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
Labels: Merge On Green

#6930 Update metaphysics schema
  data/schema.graphql
  yarn.lock
Labels: Merge On Green

#6935 fix: Collection Redirect
  src/common-middleware.ts
  src/novo/src/server.ts
Labels: Merge On Green

#6939 feat: change Classification -> Rarity for filter heading
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/AttributionClassFilter.tsx
Labels: Merge On Green

#6937 Ensure stitch exists before attempting to use when stitching in footer
  src/desktop/components/main_layout/footer/template.jade
Labels: Merge On Green

#6941 Update footer links and add download app badge
  src/v2/Components/DownloadAppBadge.tsx
  src/v2/Components/Footer.tsx
  src/v2/Components/__tests__/DownloadAppBadge.jest.tsx
Labels: Merge On Green

#6942 feat: add new medium types to medium filter
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
Labels: Merge On Green

#6943 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6950 fix: Misspelled Artist
  src/desktop/lib/webpackPublicPath.ts
Labels: Merge On Green

#6952 revert: Missed Artwork Files
  src/desktop/lib/webpackPublicPath.ts
Labels: Merge On Green

#6954 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6957 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green
