Repository artsy/force, pull requests merged in 2021-12, with the labels that each got.

#8969 feat(FX-3595): Filter pills interaction
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/Utils/isCustomValue.ts
  src/v2/Components/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/FiltersPills.tsx
  src/v2/Components/ArtworkFilter/Utils/allowedFilters.ts
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/FiltersPills.jest.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/v2/Components/SavedSearchAlert/Utils/extractPills.ts
  src/v2/Components/SavedSearchAlert/Utils/getNamePlaceholder.tsx
Labels: Jira Synced

#8978 Deploy
  package.json
  src/v2/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/v2/Apps/Order/Components/__tests__/TransactionDetailsSummary.jest.tsx
  src/v2/Apps/Order/Routes/Status/index.tsx
  src/v2/Apps/Order/Utils/__tests__/currencyUtils.jest.ts
  src/v2/Apps/Order/Utils/currencyUtils.ts
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/Utils/isCustomValue.ts
  src/v2/Components/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/FiltersPills.tsx
  src/v2/Components/ArtworkFilter/Utils/allowedFilters.ts
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/FiltersPills.jest.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/v2/Components/SavedSearchAlert/Utils/extractPills.ts
  src/v2/Components/SavedSearchAlert/Utils/getNamePlaceholder.tsx
  src/v2/__generated__/AcceptTestQuery.graphql.ts
  src/v2/__generated__/CounterTestQuery.graphql.ts
  src/v2/__generated__/NewPaymentTestQuery.graphql.ts
  src/v2/__generated__/Offer2TestQuery.graphql.ts
  src/v2/__generated__/OfferTestQuery.graphql.ts
  src/v2/__generated__/PaymentTestQuery.graphql.ts
  src/v2/__generated__/RespondCounterOfferMutation.graphql.ts
  src/v2/__generated__/RespondTestQuery.graphql.ts
  src/v2/__generated__/ReviewTestQuery.graphql.ts
  src/v2/__generated__/ShippingTestQuery.graphql.ts
  src/v2/__generated__/StatusQuery.graphql.ts
  src/v2/__generated__/TransactionDetailsSummaryItemTestQuery.graphql.ts
  src/v2/__generated__/TransactionDetailsSummaryItem_order.graphql.ts
  src/v2/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/v2/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/v2/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/v2/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/v2/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/v2/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/v2/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/v2/__generated__/orderRoutes_StatusQuery.graphql.ts
  src/v2/jest.envSetup.ts
  yarn.lock
Labels: Jira Synced

#8917 feat(FX-3603): Fair sticky logo animation
  src/v2/Apps/Fair/Components/FairHeader/FairHeader.tsx
  src/v2/Apps/Fair/Components/FairHeader/FairHeaderIcon.tsx
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeaderIcon.tsx
  src/v2/Assets/Animations.tsx
  src/v2/Components/ProfileIcon.tsx
  src/v2/Components/__tests__/ProfileIcon.jest.tsx
  src/v2/__generated__/FairApp_Test_Query.graphql.ts
  src/v2/__generated__/FairApp_fair.graphql.ts
  src/v2/__generated__/FairHeaderIcon_fair.graphql.ts
  src/v2/__generated__/FairHeader_Test_Query.graphql.ts
  src/v2/__generated__/FairHeader_fair.graphql.ts
  src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerHeaderIcon_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerHeader_Test_Query.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairQuery.graphql.ts
Labels: Jira Synced

#8996 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8997 feat(GRO-683): implements password module
  src/typings/sharify.d.ts
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsPassword.tsx
  src/v2/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
  src/v2/Apps/Settings/Routes/EditSettings/useUpdateSettingsPassword.ts
  src/v2/Utils/__tests__/auth.jest.ts
  src/v2/Utils/auth.ts
  src/v2/__generated__/useUpdateSettingsPasswordMutation.graphql.ts
Labels: Merge On Green

#8992 feat(FX-3560): Display filters pills in "Save Alert" modal
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/FiltersPills.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Utils/FilterPillsContext.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/FiltersPills.jest.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/Components/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModel.tsx
  src/v2/Components/SavedSearchAlert/Utils/extractPills.ts
  src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertForm.jest.tsx
  src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
Labels: Jira Synced

#9003 fix(GRO-690): ports over backup codes module
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactor.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactorBackupCodes.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactorBackupCodesDialog.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/index.ts
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/useCreateSettingsBackupSecondFactorsMutation.ts
  src/v2/Apps/Settings/Routes/EditSettings/Components/__tests__/SettingsEditSettingsTwoFactor.jest.tsx
  src/v2/__generated__/SettingsEditSettingsTwoFactorBackupCodesDialogQuery.graphql.ts
  src/v2/__generated__/SettingsEditSettingsTwoFactorBackupCodesDialog_me.graphql.ts
  src/v2/__generated__/SettingsEditSettingsTwoFactorBackupCodes_me.graphql.ts
  src/v2/__generated__/SettingsEditSettingsTwoFactor_Test_Query.graphql.ts
  src/v2/__generated__/SettingsEditSettingsTwoFactor_me.graphql.ts
  src/v2/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
  src/v2/__generated__/useCreateSettingsBackupSecondFactorsMutation.graphql.ts
Labels: Merge On Green

#9004 feat: Apply resizing logic to RSS feed items GROW-692
  src/desktop/apps/rss/templates/news.jade
  src/desktop/apps/rss/test/news.test.js
Labels: Merge On Green

#8995 (FX-3617): total count of filters
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/Utils/__tests__/getSelectedFiltersCounts.jest.ts
  src/v2/Components/ArtworkFilter/Utils/getSelectedFIltersCounts.ts
  src/v2/Components/ArtworkFilter/index.tsx
Labels: Jira Synced

#9020 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/createSavedSearchAlertMutation.graphql.ts
Labels: Merge On Green

#8584 AddressForm refactor with fix for broken registration form issue
  src/v2/Apps/Auction/Components/BidForm.tsx
  src/v2/Apps/Auction/Components/RegistrationForm.tsx
  src/v2/Apps/Order/Components/__tests__/PaymentPicker.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/v2/Components/AddressForm.tsx
  src/v2/Components/__tests__/Utils/addressForm.ts
Labels: Jira Synced

#9026 chore(palette-v3): Migrate BidForm to v3
  src/v2/Apps/Auction/Components/BidForm.tsx
  src/v2/Apps/Auction/Components/CreditCardInstructions.tsx
  src/v2/Apps/Auction/Components/LotInfo.tsx
  src/v2/Apps/Auction/Components/PricingTransparency.tsx
  src/v2/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/v2/Apps/Auction/Routes/__tests__/ConfirmBid.jest.tsx
  src/v2/Apps/Auction/Routes/__tests__/Utils/ConfirmBidTestPage.tsx
  src/v2/Components/Auction/ConditionsOfSaleCheckbox.tsx
  src/v2/Components/CountrySelect.tsx
Labels: Merge On Green

#8944 feat(FX-3607): Upon email alert click scroll down to artwork grid immediately
  src/v2/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
  src/v2/Utils/Hooks/useScrollTo.ts
Labels: Jira Synced

#9031 Deploy
  src/v2/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
  src/v2/Utils/Hooks/useScrollTo.ts
Labels: Jira Synced

#9035 fix(GRO-688): 2fa progress
  .eslintrc.js
  src/v2/Components/ConfirmPasswordModal/index.tsx
  src/v2/Components/PasswordInput.tsx
  src/v2/Utils/Hooks/useMutation.ts
Labels: Merge On Green

#9030 fix(FX-3642): Add sizes to the allowed filters list
  src/v2/Components/ArtworkFilter/SavedSearch/Utils/constants.ts
Labels: Jira Synced

#9033 Deploy
  .eslintrc.js
  package.json
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Utils/constants.ts
  src/v2/Components/ConfirmPasswordModal/index.tsx
  src/v2/Components/PasswordInput.tsx
  src/v2/Utils/Hooks/useMutation.ts
  yarn.lock
Labels: Jira Synced

#9045 GRO-685: Migrating Settings Email Preferences Module to /Settings2
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsEmailPreferences/SettingsEditSettingsEmailPreferences.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactor.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/__tests__/SettingsEditSettingsEmailPreferences.jest.tsx
  src/v2/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
  src/v2/__generated__/SettingsEditSettingsEmailPreferences_Test_Query.graphql.ts
  src/v2/__generated__/SettingsEditSettingsEmailPreferences_me.graphql.ts
  src/v2/__generated__/SettingsEditSettingsRoute_me.graphql.ts
  src/v2/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
Labels: Merge On Green

#9036 fix(NX-3028): fix missing border in collector attachments
  src/v2/Apps/Conversation/Components/Message.tsx
Labels: Jira Synced

#9034 fix(FX-3636): Do not send initial values as saved search criteria
  src/v2/Components/ArtworkFilter/SavedSearch/Utils/__tests__/savedSearchCriteria.jest.ts
  src/v2/Components/ArtworkFilter/SavedSearch/Utils/savedSearchCriteria.tsx
Labels: Jira Synced, Squash On Green

#9064 fix(partner): improves image quality
  src/v2/Apps/Partner/Components/PartnerShows/ShowBanner.tsx
  src/v2/__generated__/ShowBanner_Test_Query.graphql.ts
  src/v2/__generated__/ShowBanner_show.graphql.ts
  src/v2/__generated__/ShowBannersRailRendererQuery.graphql.ts
  src/v2/__generated__/partnerRoutes_ShowsQuery.graphql.ts
Labels: Merge On Green

#9069 chore: replace superagent with fetch
  src/v2/Apps/Artwork/Server/__tests__/handleArtworkImageDownload.jest.ts
  src/v2/Apps/Artwork/Server/handleArtworkImageDownload.ts
Labels: Merge On Green

#9052 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/addAssetToConsignmentMutation.graphql.ts
  src/v2/__generated__/createSavedSearchAlertMutation.graphql.ts
Labels: Merge On Green

#9008 feat(FX-3618): filters count for filter facets
  src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesArtworksFilter.jest.tsx
  src/v2/Apps/Collect/Routes/Collection/Components/__tests__/CollectionArtworksFilter.jest.tsx
  src/v2/Apps/Gene/Components/__tests__/GeneArtworkFilter.jest.tsx
  src/v2/Apps/Search/Routes/__tests__/SearchResultsArtworks.jest.tsx
  src/v2/Apps/Show/__tests__/ShowArtworks.jest.tsx
  src/v2/Apps/Tag/Components/__tests__/TagArtworkFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistNationalityFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtworkLocationFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/AttributionClassFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/MaterialsFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PartnersFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ResultOption.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ResultsFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ResultsFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter.jest.tsx
  src/v2/Components/ArtworkFilter/Utils/__tests__/getSelectedFiltersCounts.jest.ts
  src/v2/Components/ArtworkFilter/Utils/getSelectedFIltersCounts.ts
  src/v2/Components/ArtworkFilter/Utils/getTotalSelectedFiltersCount.ts
  src/v2/Components/ArtworkFilter/Utils/useFilterLabelCountByKey.ts
  src/v2/Components/ArtworkFilter/index.tsx
Labels: Jira Synced

#9067 feat: add copy and download buttons to 2fa recovery modal
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactorBackupCodesActions.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactorBackupCodesDialog.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/BackupSecondFactorReminder.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/__tests__/SettingsEditSettingsTwoFactorBackupCodesActions.jest.tsx
Labels: Squash On Green

#9075 feature: Remove Backbone (and gang) from Modern Pages
  src/lib/middleware/__tests__/handleArtworkImageDownload.jest.ts
  src/lib/middleware/handleArtworkImageDownload.ts
  src/middleware.ts
  src/v2/Apps/Artwork/artworkRoutes.tsx
Labels: Merge On Green

#9085 fix: Prevent duplicate pageview event in search GRO-653
  src/v2/Components/Search/Suggestions/SuggestionItem.tsx
Labels: Merge On Green

#9077 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9078 Deploy
  .eslintrc.js
  data/schema.graphql
  package.json
  src/lib/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts
  src/v2/Apps/Auction/Components/Form/helpers.tsx
  src/v2/Apps/Auction/Components/LotInfo.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsLinkedAccounts.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/__tests__/SettingsEditSettingsLinkedAccounts.jest.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/useUnlinkSettingsLinkedAccount.ts
  src/v2/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/ArtworkGridFilterPills.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/Pills.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/__tests__/Pills.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkGridFilterPills.jest.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/v2/Components/SavedSearchAlert/Utils/extractPills.ts
  src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
  src/v2/Components/SavedSearchAlert/__tests__/extractPills.ts
  src/v2/Components/Search/Suggestions/SuggestionItem.tsx
  src/v2/__generated__/ConfirmBidValidTestQuery.graphql.ts
  src/v2/__generated__/LotInfo_artwork.graphql.ts
  src/v2/__generated__/SettingsEditSettingsLinkedAccounts_Test_Query.graphql.ts
  src/v2/__generated__/SettingsEditSettingsLinkedAccounts_me.graphql.ts
  src/v2/__generated__/SettingsEditSettingsRoute_me.graphql.ts
  src/v2/__generated__/auctionRoutes_ConfirmBidQuery.graphql.ts
  src/v2/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
  src/v2/__generated__/useUnlinkSettingsLinkedAccountMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#9088 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9055 feat(FX-3641): Show Create Alert button when user both logged in and out
  src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerFollowButton.tsx
  src/v2/Apps/FairOrginizer/Components/__tests__/FairOrganizerFollowButton.jest.tsx
  src/v2/Components/Artwork/SaveButton/useSaveArtwork.ts
  src/v2/Components/ArtworkFilter/SavedSearch/Components/ArtworkGridFilterPills.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
  src/v2/Components/ArtworkFilter/__tests__/CreateAlertButton.jest.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/Components/Authentication/Types.ts
  src/v2/Components/FollowButton/FollowArtistButton.tsx
  src/v2/Components/FollowButton/FollowGeneButton.tsx
  src/v2/Components/FollowButton/FollowProfileButton.tsx
  src/v2/Components/FollowButton/__tests__/FollowArtistButton.jest.tsx
  src/v2/Components/FollowButton/__tests__/FollowGeneButton.jest.tsx
  src/v2/Components/FollowButton/__tests__/FollowProfileButton.jest.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/v2/Utils/Hooks/useAuthIntent/__tests__/useAuthIntent.jest.ts
  src/v2/Utils/Hooks/useAuthIntent/index.ts
  src/v2/Utils/__tests__/openAuthModal.jest.ts
  src/v2/Utils/openAuthModal.ts
Labels: Jira Synced

#9089 Deploy
  data/schema.graphql
  src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerFollowButton.tsx
  src/v2/Apps/FairOrginizer/Components/__tests__/FairOrganizerFollowButton.jest.tsx
  src/v2/Components/Artwork/SaveButton/useSaveArtwork.ts
  src/v2/Components/ArtworkFilter/SavedSearch/Components/ArtworkGridFilterPills.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
  src/v2/Components/ArtworkFilter/__tests__/CreateAlertButton.jest.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/Components/Authentication/Types.ts
  src/v2/Components/FollowButton/FollowArtistButton.tsx
  src/v2/Components/FollowButton/FollowGeneButton.tsx
  src/v2/Components/FollowButton/FollowProfileButton.tsx
  src/v2/Components/FollowButton/__tests__/FollowArtistButton.jest.tsx
  src/v2/Components/FollowButton/__tests__/FollowGeneButton.jest.tsx
  src/v2/Components/FollowButton/__tests__/FollowProfileButton.jest.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/v2/Utils/Hooks/useAuthIntent/__tests__/useAuthIntent.jest.ts
  src/v2/Utils/Hooks/useAuthIntent/index.ts
  src/v2/Utils/__tests__/openAuthModal.jest.ts
  src/v2/Utils/openAuthModal.ts
Labels: Jira Synced

#9094 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9093 fix: validates authentication and signs out if invalid
  src/v2/Apps/Authentication/__tests__/authenticationRoutes.jest.tsx
  src/v2/Apps/Components/AppShell.tsx
  src/v2/System/Router/__tests__/RouterLink.jest.tsx
  src/v2/Utils/Hooks/__tests__/useAuthValidation.jest.tsx
  src/v2/Utils/Hooks/useAuthValidation.ts
  src/v2/__generated__/useAuthValidationQuery.graphql.ts
Labels: Merge On Green

#9096 chore: Skipping rounding for custom size values
  src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter.jest.tsx
Labels: Jira Synced

#8994 feat(NX-3011): new Offer Submission inputs and calculation
  src/v2/Apps/Collect/Routes/Collections/Components/CollectionsCategory.tsx
  src/v2/Apps/Order/Components/OfferInput.tsx
  src/v2/Apps/Order/Components/OfferNote.tsx
  src/v2/Apps/Order/Components/PriceOptions.tsx
  src/v2/Apps/Order/Components/__tests__/OfferNote.jest.tsx
  src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/__generated__/Offer2TestQuery.graphql.ts
  src/v2/__generated__/OfferTestQuery.graphql.ts
  src/v2/__generated__/Offer_order.graphql.ts
  src/v2/__generated__/PriceOptions_Test_Query.graphql.ts
  src/v2/__generated__/PriceOptions_artwork.graphql.ts
  src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
Labels: Jira Synced

#9102 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9105 feat: set up for developing one trust styling
  src/v2/Components/OneTrustConsentStyles.ts
Labels: Merge On Green

#9108 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9111 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9112 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9106 chore: add tracking for price options
  src/v2/Apps/Order/Components/PriceOptions.tsx
  src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/__generated__/Offer2TestQuery.graphql.ts
  src/v2/__generated__/OfferTestQuery.graphql.ts
  src/v2/__generated__/Offer_order.graphql.ts
  src/v2/__generated__/PriceOptions_Test_Query.graphql.ts
  src/v2/__generated__/PriceOptions_order.graphql.ts
  src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
Labels: Jira Synced

#9103 Deploy
  data/schema.graphql
  src/lib/middleware/__tests__/handleArtworkImageDownload.jest.ts
  src/lib/middleware/handleArtworkImageDownload.ts
  src/middleware.ts
  src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/v2/Apps/Artwork/artworkRoutes.tsx
  src/v2/Apps/Collect/Routes/Collections/Components/CollectionsCategory.tsx
  src/v2/Apps/Order/Components/OfferInput.tsx
  src/v2/Apps/Order/Components/OfferNote.tsx
  src/v2/Apps/Order/Components/PriceOptions.tsx
  src/v2/Apps/Order/Components/__tests__/OfferNote.jest.tsx
  src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/Components/OneTrustConsentStyles.ts
  src/v2/__generated__/ArtworkActions_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkActions_artwork.graphql.ts
  src/v2/__generated__/Offer2TestQuery.graphql.ts
  src/v2/__generated__/OfferTestQuery.graphql.ts
  src/v2/__generated__/Offer_order.graphql.ts
  src/v2/__generated__/PriceOptions_Test_Query.graphql.ts
  src/v2/__generated__/PriceOptions_artwork.graphql.ts
  src/v2/__generated__/PriceOptions_order.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
Labels: Jira Synced

#9116 chore: expand OfferInput to take an onBlur callback
  src/v2/Apps/Order/Components/OfferInput.tsx
Labels: Squash On Green

#9121 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green
