Repository artsy/force, pull requests merged in 2021-06, with the labels that each got.

#7663 Deploy
  data/schema.graphql
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtistList.tsx
  src/v2/Apps/Partner/Components/PartnerHeader/index.tsx
  src/v2/Apps/Partner/Components/__tests__/PartnerHeader.jest.tsx
  src/v2/Apps/Partner/partnerRoutes.tsx
  src/v2/Components/Authentication/TermsOfServiceCheckbox.tsx
  src/v2/Components/Footer/Footer.tsx
  src/v2/Components/Footer/__tests__/Footer.jest.tsx
  src/v2/Components/UserSettings/TwoFactorAuthentication/__tests__/helpers.jest.ts
  src/v2/Utils/__tests__/url.jest.ts
  src/v2/__generated__/PartnerApp_Test_Query.graphql.ts
  src/v2/__generated__/PartnerHeader_Test_Query.graphql.ts
  src/v2/__generated__/PartnerHeader_partner.graphql.ts
  src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts
Labels: Jira Synced

#7678 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7661 chore: removes relay queries to use static vanity urls
  src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
  src/v2/Apps/BuyerGuarantee/Routes/__tests__/BuyerGuaranteeIndex.jest.tsx
  src/v2/Apps/BuyerGuarantee/buyerGuaranteeRoutes.tsx
  src/v2/__generated__/BuyerGuaranteeIndexNonAdmin_Test_Query.graphql.ts
  src/v2/__generated__/BuyerGuaranteeIndex_authenticityImage.graphql.ts
  src/v2/__generated__/BuyerGuaranteeIndex_headerImage.graphql.ts
  src/v2/__generated__/BuyerGuaranteeIndex_moneyBackGuaranteeImage.graphql.ts
  src/v2/__generated__/BuyerGuaranteeIndex_securePaymentImage.graphql.ts
  src/v2/__generated__/buyerGuaranteeRoutes_BuyerGuaranteeQuery.graphql.ts
Labels: Squash On Green

#7689 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7679 Deploy
  data/schema.graphql
  package.json
  src/desktop/lib/webpackPublicPath.ts
  src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
  src/v2/Apps/BuyerGuarantee/Routes/__tests__/BuyerGuaranteeIndex.jest.tsx
  src/v2/Apps/BuyerGuarantee/buyerGuaranteeRoutes.tsx
  src/v2/Apps/Order/Routes/Accept/index.tsx
  src/v2/Apps/Order/Routes/NewPayment/index.tsx
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Order/Routes/Payment/index.tsx
  src/v2/Apps/Order/Routes/Shipping/index.tsx
  src/v2/Apps/Partner/Components/NavigationTabs/index.tsx
  src/v2/Apps/Partner/Components/Overview/ArticlesRail.tsx
  src/v2/Apps/Partner/Components/Overview/ArtistsRail.tsx
  src/v2/Apps/Partner/Components/Overview/ArtworksRail.tsx
  src/v2/Apps/Partner/Components/Overview/NearbyGalleryCard.tsx
  src/v2/Apps/Partner/Components/Overview/ShowBannersRail/ShowBannersDesktopCarousel.tsx
  src/v2/Apps/Partner/Components/Overview/ShowBannersRail/ShowBannersMobileCarousel.tsx
  src/v2/Apps/Partner/Components/Overview/ShowBannersRail/ShowBannersRail.tsx
  src/v2/Apps/Partner/Components/Overview/ShowBannersRail/ShowBannersRailPlaceholder.tsx
  src/v2/Apps/Partner/Components/Overview/ShowBannersRail/index.tsx
  src/v2/Apps/Partner/Components/Overview/ShowBannersRailPlaceholder.tsx
  src/v2/Apps/Partner/Components/Overview/ShowsRail.tsx
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtistItem.tsx
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistsCarousel/PartnerArtistsCarousel.tsx
  src/v2/Apps/Partner/Components/PartnerHeader/index.tsx
  src/v2/Apps/Partner/Components/PartnerMeta/index.tsx
  src/v2/Apps/Partner/Components/__tests__/Overview/ArtistsRail.jest.tsx
  src/v2/Apps/Partner/Components/__tests__/PartnerHeader.jest.tsx
  src/v2/Apps/Partner/PartnerApp.tsx
  src/v2/Apps/Partner/Routes/Artists/ArtistsRoute.tsx
  src/v2/Apps/Partner/Routes/Overview/index.tsx
  src/v2/Apps/Partner/Utils/PartnerArtistsLoadingContext.tsx
  src/v2/Apps/Partner/Utils/PartnerShowBannersContex.tsx
  src/v2/Apps/Partner/partnerRoutes.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx
  src/v2/__generated__/ArtistsRail_Test_Query.graphql.ts
  src/v2/__generated__/ArtistsRail_partner.graphql.ts
  src/v2/__generated__/BuyerGuaranteeIndexNonAdmin_Test_Query.graphql.ts
  src/v2/__generated__/BuyerGuaranteeIndex_authenticityImage.graphql.ts
  src/v2/__generated__/BuyerGuaranteeIndex_headerImage.graphql.ts
  src/v2/__generated__/BuyerGuaranteeIndex_moneyBackGuaranteeImage.graphql.ts
  src/v2/__generated__/BuyerGuaranteeIndex_securePaymentImage.graphql.ts
  src/v2/__generated__/ShowBannersDesktopCarousel_shows.graphql.ts
  src/v2/__generated__/ShowBannersMobileCarousel_shows.graphql.ts
  src/v2/__generated__/ShowBannersRailRendererQuery.graphql.ts
  src/v2/__generated__/ShowBannersRail_partner.graphql.ts
  src/v2/__generated__/buyerGuaranteeRoutes_BuyerGuaranteeQuery.graphql.ts
  src/v2/__generated__/partnerRoutes_OverviewQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#7690 feat(PX-3737): update COA copy in modal on Artwork Page
  src/v2/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
Labels: Jira Synced

#7671 feat: App download banner
  src/v2/Components/DownloadAppBadge.tsx
  src/v2/Components/Footer/Footer.tsx
  src/v2/Components/Footer/FooterDownloadAppBanner.tsx
  src/v2/Components/Footer/__tests__/Footer.jest.tsx
  src/v2/Utils/getRandom.ts
Labels: Squash On Green

#7700 hotfix: show viewing room content when logged out
  src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
Labels: Squash On Green

#7703 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7712 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7710 fix: [Artist2] Overview QA items
  src/v2/Apps/Artist2/Components/Artist2Header.tsx
  src/v2/Apps/Artist2/Routes/AuctionResults/Components/SortSelect.tsx
  src/v2/Apps/Artist2/Routes/Overview/ArtistOverviewRoute.tsx
  src/v2/Apps/Artist2/Routes/Overview/Components/Artist2CareerHighlights.tsx
  src/v2/Apps/Artist2/Routes/Overview/Components/Artist2CurrentArticlesRail.tsx
  src/v2/Apps/Artist2/Routes/Overview/Components/Artist2CurrentShowsRail.tsx
  src/v2/Apps/Artist2/Routes/Overview/Components/Artist2Genes.tsx
  src/v2/Apps/Artist2/Routes/Overview/Components/Artist2RelatedArtistsRail.tsx
  src/v2/Components/ArtistInsight.tsx
  src/v2/Components/SelectedCareerAchievements.tsx
  src/v2/__generated__/Artist2CurrentArticlesRail_artist.graphql.ts
  src/v2/__generated__/Artist2CurrentShowsRail_artist.graphql.ts
  src/v2/__generated__/Artist2Header_artist.graphql.ts
  src/v2/__generated__/Artist2RoutesTopLevelQuery.graphql.ts
  src/v2/__generated__/artist2Routes_OverviewQuery.graphql.ts
Labels: Merge On Green

#7717 fix: [Artist2] Rest of QA
  src/desktop/components/artistSignupModal/artistSignupModal.tsx
  src/middleware.ts
  src/v2/Apps/Artist2/Artist2App.tsx
  src/v2/Apps/Artist2/Routes/Articles/ArtistArticlesRoute.tsx
  src/v2/Apps/Artist2/Routes/AuctionResults/Artist2AuctionResults.tsx
  src/v2/Apps/Artist2/Routes/CV/ArtistCVRoute.tsx
  src/v2/Apps/Artist2/Routes/CV/Components/ArtistCVGroup.tsx
  src/v2/Apps/Artist2/Routes/Overview/Components/Artist2CareerHighlights.tsx
  src/v2/Apps/Artist2/Routes/Overview/Components/Artist2NotableWorksRail.tsx
  src/v2/Apps/Artist2/Routes/Shows/ArtistShowsRoute.tsx
  src/v2/Apps/Artist2/Routes/WorksForSale/Components/Artist2ArtworkFilter.tsx
  src/v2/Apps/Artist2/Routes/WorksForSale/Components/ZeroState.tsx
  src/v2/Apps/Artist2/artist2Routes.tsx
  src/v2/Components/ArtistSeriesRail/ArtistSeriesItem.tsx
  src/v2/Components/RouteTabs.tsx
  src/v2/Components/SelectedCareerAchievements.tsx
  src/v2/Components/__tests__/SelectedCareerAchievements.jest.tsx
  src/v2/__generated__/Artist2App_artist.graphql.ts
  src/v2/__generated__/Artist2ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/Artist2ArtworkFilter_artist.graphql.ts
  src/v2/__generated__/Artist2CareerHighlights_artist.graphql.ts
  src/v2/__generated__/Artist2RoutesTopLevelQuery.graphql.ts
  src/v2/__generated__/ArtistCVGroupQuery.graphql.ts
  src/v2/__generated__/ArtistCVRoute_viewer.graphql.ts
  src/v2/__generated__/ArtistShowsRoute_viewer.graphql.ts
  src/v2/__generated__/OverviewRoute_Test_Query.graphql.ts
  src/v2/__generated__/SelectedCareerAchievementsTestQuery.graphql.ts
  src/v2/__generated__/SelectedCareerAchievements_artist.graphql.ts
  src/v2/__generated__/artist2Routes_CVQuery.graphql.ts
  src/v2/__generated__/artist2Routes_OverviewQuery.graphql.ts
  src/v2/__generated__/artist2Routes_ShowsQuery.graphql.ts
  src/v2/__generated__/artist2Routes_WorksForSaleQuery.graphql.ts
  src/v2/__generated__/artistRoutes_OverviewQuery.graphql.ts
Labels: Merge On Green

#7718 fix(navbar): prevents doubled auth buttons
  src/v2/Apps/Components/AppShell.tsx
  src/v2/Components/AuthBanner.tsx
  src/v2/Components/NavBar/NavBar.tsx
  src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
Labels: Merge On Green

#7722 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7741 fix: Update tests for new Artist page
  src/v2/Apps/Artist/ArtistApp.tsx
  src/v2/Apps/Artist/Components/ArtistHeader.tsx
  src/v2/Apps/Artist/Components/FollowArtist2Button.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistRelatedArtistsRail.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistWorksForSaleRail.tsx
Labels: Merge On Green

#7746 feat: Bring back consign promo space and update GRO-364
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/PromoSpace.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/TemporaryOffer.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/TemporaryOffer.jest.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/__tests__/ConsignApp.jest.tsx
Labels: Squash On Green

#7749 lib: Upgrade styled-components@5.x
  package.json
  src/v2/Components/__tests__/__snapshots__/Artwork.jest.tsx.snap
  src/v2/Components/__tests__/__snapshots__/Input.jest.tsx.snap
  src/v2/Components/__tests__/__snapshots__/PasswordInput.jest.tsx.snap
  src/v2/Components/__tests__/__snapshots__/QuickInput.jest.tsx.snap
  src/v2/jest.envSetup.ts
  yarn.lock
Labels: Merge On Green

#7751 fix: More lazy loading on images
  src/v2/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
  src/v2/Components/ImageLink.tsx
Labels: Squash On Green

#7752 bugfix: [Collect] Fix image lazy load
  src/v2/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx
  src/v2/Apps/Artwork/Components/OtherWorks/index.tsx
  src/v2/Apps/FeatureAKG/Components/SelectedWorks.tsx
  src/v2/Apps/WorksForYou/WorksForYouFeed.tsx
  src/v2/Components/ArtworkGrid/ArtworkGrid.tsx
  src/v2/Components/ImageLink.tsx
Labels: Merge On Green

#7721 feat: Remove ads and signup banner in articles for eigen
  src/desktop/apps/article/__tests__/helpers.jest.tsx
  src/desktop/apps/article/__tests__/routes.jest.ts
  src/desktop/apps/article/components/App.tsx
  src/desktop/apps/article/components/InfiniteScrollArticle.tsx
  src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
  src/desktop/apps/article/components/NewsArticle.tsx
  src/desktop/apps/article/components/layouts/Article.tsx
  src/desktop/apps/article/components/layouts/Classic.tsx
  src/desktop/apps/article/helpers.tsx
  src/desktop/apps/article/routes.tsx
Labels: Jira Synced

#7758 fix: add extra decimal to fix rounding issue
  src/v2/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
  src/v2/Components/ArtistMarketInsights.tsx
  src/v2/Components/SelectedCareerAchievements.tsx
Labels: Merge On Green

#7762 fix(GRO-371): Updates popovers; prevents artist suggestion popover from overflowing
  package.json
  src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkPopoutPanel.tsx
  src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
  src/v2/Apps/Artwork/Components/ArtworkImageBrowser/MediocrePopover.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/v2/Apps/Artwork/Components/PricingContextModal.tsx
  src/v2/Components/FollowArtistPopover/FollowArtistPopoverRow.tsx
  src/v2/Components/FollowArtistPopover/__tests__/FollowArtistPopover.jest.tsx
  src/v2/Components/FollowArtistPopover/index.tsx
  src/v2/Components/FollowButton/Button.tsx
  src/v2/Components/FollowButton/FollowArtistButton.tsx
  src/v2/Components/FollowButton/__tests__/Button.jest.tsx
  src/v2/Components/Popover/index.tsx
  src/v2/Components/Popover/types.ts
  src/v2/Utils/Hooks/useClickOutside.ts
  src/v2/__generated__/ArtworkSidebarArtists_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarQuery.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/FollowArtistPopoverQuery.graphql.ts
  src/v2/__generated__/FollowArtistPopoverRowMutation.graphql.ts
  src/v2/__generated__/FollowArtistPopoverRow_artist.graphql.ts
  src/v2/__generated__/FollowArtistPopover_Test_Query.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Squash On Green

#7625 toolchain: [Danger] Add guard to protect against <QueryRenderer> imports
  .circleci/config.yml
  dangerfile.ts
  package.json
  yarn.lock
Labels: Merge On Green

#7768 toolchain: Add danger rule warning about routes smoke test
  dangerfile.ts
Labels: Merge On Green

#7775 fix: prevents popover from showing unless you are logged in
  src/v2/Components/FollowButton/FollowArtistButton.tsx
Labels: Squash On Green

#7774 feat(FX-2994): location filter at fair artworks filters
  src/v2/Apps/Fair/Routes/FairArtworks.tsx
  src/v2/Apps/Fair/fairRoutes.tsx
Labels: Jira Synced

#7756 fix: restores tracking to route tabs
  src/v2/Components/RouteTabs.tsx
  src/v2/Components/UserSettings/UserSettingsTabs.tsx
Labels: Squash On Green

#7769 feat: Confirm artwork modal for web inquiry checkout
  src/v2/Apps/Conversation/Components/CollapsibleArtworkDetails.tsx
  src/v2/Apps/Conversation/Components/ConfirmArtworkButton.tsx
  src/v2/Apps/Conversation/Components/ConfirmArtworkModal.tsx
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConfirmArtwork.jest.tsx
  src/v2/Apps/Conversation/Mutation/MakeInquiryOfferMutation.ts
  src/v2/__generated__/CollapsibleArtworkDetails_artwork.graphql.ts
  src/v2/__generated__/ConfirmArtworkButton_artwork.graphql.ts
  src/v2/__generated__/ConfirmArtworkModalQuery.graphql.ts
  src/v2/__generated__/ConfirmArtworkModal_Test_Query.graphql.ts
  src/v2/__generated__/ConfirmArtworkModal_artwork.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/MakeInquiryOfferMutation.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Jira Synced

#7779 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/SetShippingMutation.graphql.ts
Labels: Merge On Green

#7781 fix: Updated ConfirmArtworkModal deps to system instead of artsy
  src/v2/Apps/Conversation/Components/ConfirmArtworkModal.tsx
Labels: Squash On Green

#7782 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7687 Artist Auction Results performance percentage
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/v2/Components/AuctionResultPerformance.tsx
  src/v2/__generated__/ArtistAuctionResultItem_auctionResult.graphql.ts
  src/v2/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/v2/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
  src/v2/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
Labels: Jira Synced, Merge On Green

#7789 fix: news articles layout on Eigen
  src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
Labels: Jira Synced, Squash On Green

#7780 feat: add Zendesk integration to auctions pages
  src/desktop/apps/auction/components/Layout.tsx
  src/desktop/apps/auction/components/layout/auction_info/Registration.tsx
  src/desktop/components/main_layout/templates/scripts.jade
  src/desktop/config.coffee
  src/lib/setup_sharify.js
  src/typings/sharify.d.ts
  src/v2/Apps/Artwork/Components/ArtworkMeta.tsx
  src/v2/Apps/Auction/Routes/Register/index.tsx
  src/v2/Apps/Order/OrderApp.tsx
  src/v2/Components/ZendeskWrapper.tsx
  src/v2/__generated__/ArtworkMeta_artwork.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Squash On Green

#7792 feat: Rearrange sign up field order GRO-269
  src/v2/Components/Authentication/Desktop/SignUpForm.tsx
Labels: Squash On Green

#7794 docs: Add info about adding global script tags
  docs/best_practices.md
Labels: Squash On Green

#7793 feat(GRO-214): sets up HomeApp
  cypress/integration/home2.spec.ts
  src/v2/Apps/Home/Components/HomeHeroUnit.tsx
  src/v2/Apps/Home/Components/HomeInfoBlurb.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Apps/Home/__tests__/HomeApp.jest.tsx
  src/v2/Apps/Home/homeRoutes.tsx
  src/v2/System/Router/__tests__/buildClientApp.jest.tsx
  src/v2/System/Router/__tests__/buildServerApp.jest.tsx
  src/v2/System/SystemContext.tsx
  src/v2/System/__tests__/SystemContext.jest.tsx
  src/v2/__generated__/HomeApp_Test_Query.graphql.ts
  src/v2/__generated__/HomeApp_homePage.graphql.ts
  src/v2/__generated__/HomeHeroUnit_heroUnit.graphql.ts
  src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts
  src/v2/routes.tsx
Labels: Squash On Green

#7801 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7796 Deploy
  Dockerfile
  cypress/integration/home2.spec.ts
  data/schema.graphql
  package.json
  src/dev.js
  src/v2/Apps/Home/Components/HomeHeroUnit.tsx
  src/v2/Apps/Home/Components/HomeInfoBlurb.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Apps/Home/__tests__/HomeApp.jest.tsx
  src/v2/Apps/Home/homeRoutes.tsx
  src/v2/Apps/Order/Components/AddressModal.tsx
  src/v2/Apps/Order/Components/SavedAddressItem.tsx
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/v2/Components/Address/AddressModalFields.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx
  src/v2/Components/Lightbox/Lightbox.tsx
  src/v2/Components/Lightbox/__tests__/Lightbox.jest.tsx
  src/v2/System/Router/__tests__/buildClientApp.jest.tsx
  src/v2/System/Router/__tests__/buildServerApp.jest.tsx
  src/v2/System/SystemContext.tsx
  src/v2/System/__tests__/SystemContext.jest.tsx
  src/v2/Utils/Hooks/useRouteComplete.ts
  src/v2/__generated__/HomeApp_Test_Query.graphql.ts
  src/v2/__generated__/HomeApp_homePage.graphql.ts
  src/v2/__generated__/HomeHeroUnit_heroUnit.graphql.ts
  src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts
  src/v2/index.ejs
  src/v2/routes.tsx
  webpack/envs/clientCommonConfig.js
  webpack/envs/clientDevelopmentConfig.js
  webpack/envs/clientProductionConfig.js
  webpack/envs/commonEnv.js
  webpack/envs/commonLoaders.js
  webpack/envs/commonPlugins.js
  webpack/envs/legacyDevelopmentConfig.js
  webpack/envs/legacyProductionConfig.js
  webpack/envs/serverConfig.js
  yarn.lock
Labels: Jira Synced

#7798 feat: CTA component (with all states and MO button)
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/ConversationCTA.tsx
  src/v2/Apps/Conversation/Components/OpenInquiryModalButton.tsx
  src/v2/Apps/Conversation/Components/Reply.tsx
  src/v2/Apps/Conversation/Components/ReviewOfferCTA.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConversationCTA.jest.tsx
  src/v2/Apps/Conversation/Routes/Conversation/index.tsx
  src/v2/Apps/Conversation/__tests__/Reply.jest.tsx
  src/v2/Utils/Hooks/__tests__/useEventTiming.jest.tsx
  src/v2/Utils/Hooks/useEventTiming.tsx
  src/v2/__generated__/ConversationCTA_Test_Query.graphql.ts
  src/v2/__generated__/ConversationCTA_conversation.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/Conversation_me.graphql.ts
  src/v2/__generated__/OpenInquiryModalButtonQuery.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Jira Synced

#7818 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7816 fix: removes Zendesk script from auctions pages
  src/desktop/components/main_layout/templates/scripts.jade
  src/v2/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/v2/Components/ZendeskWrapper.tsx
Labels: Merge On Green

#7821 Revert "chore: (GRO-381) remove sign in with apple feature flag"
  src/desktop/apps/user/components/linked_accounts/index.jade
  src/desktop/apps/user/components/linked_accounts/test/view.test.js
  src/desktop/config.coffee
  src/lib/setup_sharify.js
  src/mobile/config.coffee
  src/typings/sharify.d.ts
  src/v2/Components/Authentication/Footer.tsx
  src/v2/Components/Authentication/__tests__/Desktop/ForgotPasswordForm.jest.tsx
  src/v2/Components/Authentication/__tests__/Desktop/LoginForm.jest.tsx
  src/v2/Components/Authentication/__tests__/Desktop/SignUpForm.jest.tsx
  src/v2/Components/Authentication/__tests__/FormSwitcher.jest.tsx
Labels: Jira Synced

#7755 feat: Introduce market signals to auction result tab
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStatsInfoButton.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStatsPlaceholder.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/MarketStats.jest.tsx
  src/v2/Utils/__tests__/formatLargeNumber.jest.ts
  src/v2/Utils/formatLargeNumber.ts
  src/v2/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/v2/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
  src/v2/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/v2/__generated__/MarketStatsQuery.graphql.ts
  src/v2/__generated__/MarketStats_Test_Query.graphql.ts
  src/v2/__generated__/MarketStats_priceInsightsConnection.graphql.ts
  src/v2/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
Labels: Jira Synced

#7823 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7827 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7817 Deploy
  data/schema.graphql
  docs/best_practices.md
  package.json
  src/desktop/components/main_layout/templates/scripts.jade
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStatsInfoButton.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStatsPlaceholder.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/MarketStats.jest.tsx
  src/v2/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/v2/Components/Authentication/Desktop/LoginForm.tsx
  src/v2/Components/ZendeskWrapper.tsx
  src/v2/Utils/__tests__/formatLargeNumber.jest.ts
  src/v2/Utils/formatLargeNumber.ts
  src/v2/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/v2/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
  src/v2/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/v2/__generated__/MarketStatsQuery.graphql.ts
  src/v2/__generated__/MarketStats_Test_Query.graphql.ts
  src/v2/__generated__/MarketStats_priceInsightsConnection.graphql.ts
  src/v2/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#7822 bugfix: [Artist] Fix falsy bug in header follower count
  src/v2/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
  src/v2/Apps/Artist/Components/ArtistHeader/__tests__/ArtistHeader.jest.tsx
Labels: Merge On Green

#7815 Style fixes for inbox
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/ConversationHeader.tsx
  src/v2/Apps/Conversation/Components/ConversationListHeader.tsx
  src/v2/Apps/Conversation/Routes/Conversation/index.tsx
Labels: Jira Synced

#7830 fix(skeleton): removes done usage
  package.json
  src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStatsPlaceholder.tsx
  src/v2/Apps/Auctions/Components/AuctionArtworksRail/__tests__/AuctionArtworksRailPlaceholder.jest.tsx
  src/v2/Apps/Auctions/Components/AuctionArtworksRailPlaceholder.tsx
  src/v2/Apps/Fair/Components/FairExhibitorRail/FairExhibitorRailPlaceholder.tsx
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetailsPlaceholder.tsx
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtistListPlaceholder.tsx
  yarn.lock
Labels: Squash On Green

#7833 revert the revert: (GRO-381) apple sign in feature flag removal
  src/desktop/apps/user/components/linked_accounts/index.jade
  src/desktop/apps/user/components/linked_accounts/test/view.test.js
  src/desktop/config.coffee
  src/lib/setup_sharify.js
  src/mobile/config.coffee
  src/typings/sharify.d.ts
Labels: Merge On Green

#7836 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7839 fix: align columns on auction results page
  src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx
Labels: Jira Synced

#7842 fix (CX-1618): change label name for auction house filter
  src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx
Labels: Jira Synced

#7853 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7845 fix: Inquiry Modal
  src/v2/Apps/Artwork/ArtworkApp.tsx
  src/v2/Apps/Order/OrderApp.tsx
  src/v2/Apps/Order/Utils/openAskSpecialistInquireableModal.ts
  src/v2/Apps/Order/__tests__/OrderApp.jest.tsx
  src/v2/Utils/legacyAssetDll.tsx
Labels: Merge On Green

#7856 feat(GRO-214): adds featured shows grid
  src/v2/Apps/Home/Components/HomeFeaturedCategoriesRail.tsx
  src/v2/Apps/Home/Components/HomeFeaturedShows.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Apps/Home/__tests__/HomeFeaturedShows.jest.tsx
  src/v2/__generated__/HomeFeaturedShowsQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedShows_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedShows_orderedSet.graphql.ts
Labels: Squash On Green

#7857 feat(GRO-214): adds featured articles rail
  src/v2/Apps/Home/Components/HomeFeaturedArticles.tsx
  src/v2/Apps/Home/Components/HomeFeaturedCategoriesRail.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Apps/Home/__tests__/HomeFeaturedArticles.jest.tsx
  src/v2/__generated__/HomeFeaturedArticlesQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedArticles_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedArticles_articles.graphql.ts
Labels: Squash On Green

#7851 feature: Stub out new /auctions v2 routes
  src/desktop/config.coffee
  src/lib/setup_sharify.js
  src/typings/sharify.d.ts
  src/v2/Apps/Auctions/AuctionsApp.tsx
  src/v2/Apps/Auctions/Routes/Artworks/ArtworksRoute.tsx
  src/v2/Apps/Auctions/Routes/Auctions/AuctionsRoute.tsx
  src/v2/Apps/Auctions/auctionsRoutes.tsx
  src/v2/__generated__/ArtworksRoute_viewer.graphql.ts
  src/v2/__generated__/AuctionsRoute_viewer.graphql.ts
  src/v2/__generated__/auctionsRoutes_Artworks_AuctionsQuery.graphql.ts
  src/v2/__generated__/auctionsRoutes_Auctions_AuctionsQuery.graphql.ts
Labels: Merge On Green

#7860 feat(GRO-214): remaining rails
  src/v2/Apps/Home/Components/HomeArtworkModuleContext.tsx
  src/v2/Apps/Home/Components/HomeArtworkModuleRail.tsx
  src/v2/Apps/Home/Components/HomeFeaturedEventsRail.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Apps/Home/__tests__/HomeApp.jest.tsx
  src/v2/Apps/Home/homeRoutes.tsx
  src/v2/Components/Artwork/ShelfArtwork.tsx
  src/v2/__generated__/HomeApp_Test_Query.graphql.ts
  src/v2/__generated__/HomeApp_orderedSet.graphql.ts
  src/v2/__generated__/HomeArtworkModuleContext_Test_Query.graphql.ts
  src/v2/__generated__/HomeArtworkModuleContext_context.graphql.ts
  src/v2/__generated__/HomeArtworkModuleRailQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedEventsRail_orderedSet.graphql.ts
  src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts
Labels: Squash On Green

#7862 sentry: Add dedupe lib and filter out issues
  package.json
  src/lib/analytics/sentryFilters.ts
  src/lib/setupSentryClient.ts
  yarn.lock
Labels: Merge On Green

#7866 Deploy
  cypress/integration/artist.spec.js
  cypress/integration/collect.spec.js
  package.json
  src/desktop/components/fair_layout/templates/head.jade
  src/desktop/components/main_layout/templates/head.jade
  src/desktop/components/split_test/README.md
  src/desktop/components/split_test/running_tests.coffee
  src/desktop/components/split_test/split_test.coffee
  src/desktop/components/split_test/test/split_test.test.js
  src/desktop/config.coffee
  src/lib/analytics/sentryFilters.ts
  src/lib/middleware/__tests__/locals.jest.ts
  src/lib/middleware/locals.ts
  src/lib/middleware/proxyReflection.ts
  src/middleware.ts
  src/test/lib/middleware/proxyReflection.jest.ts
  src/v2/Apps/Artist/ArtistApp.tsx
  src/v2/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
  src/v2/Apps/Artist/Components/ArtistHeader/__tests__/ArtistHeader.jest.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistNotableWorksRail.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistRelatedArtistsRail.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/__tests__/ArtistNotableWorksRail.jest.tsx
  src/v2/Apps/Artist/__tests__/ArtistApp.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/InDemandNow/ConsignInDemandNow.tsx
  src/v2/Apps/Partner/Components/NavigationTabs/index.tsx
  src/v2/Apps/Partner/partnerRoutes.tsx
  src/v2/Components/ArtistMarketInsights.tsx
  src/v2/Components/ArtistSeriesRail/__tests__/ArtistSeriesItem.jest.tsx
  src/v2/Components/SelectedCareerAchievements.tsx
  src/v2/Components/__stories__/Headers.story.tsx
  src/v2/Components/__tests__/SelectedCareerAchievements.jest.tsx
  src/v2/__generated__/NavigationTabs_Test_PartnerQuery.graphql.ts
  src/v2/__generated__/NavigationTabs_partner.graphql.ts
  src/v2/__generated__/PartnerApp_Test_Query.graphql.ts
  src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts
  src/v2/__generated__/partnerRoutes_ShowsQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#7878 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7884 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7883 fix: Remove React Spring
  package.json
  src/v2/Components/NavBar/NavItemPanel.tsx
  src/v2/System/Router/PageLoader.tsx
  yarn.lock
Labels: Merge On Green

#7871 chore: upgrade artsy-eigen-web-association
  yarn.lock
Labels: Jira Synced

#7887 Update metaphysics schema
  data/schema.graphql
  yarn.lock
Labels: Merge On Green

#7888 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7885 feat: Rearrange modules on fairs page
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorial.tsx
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx
  src/v2/Apps/Fair/Components/__tests__/FairEditorialItem.jest.tsx
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/__generated__/FairApp_Test_Query.graphql.ts
  src/v2/__generated__/FairEditorialItem_Test_Query.graphql.ts
  src/v2/__generated__/FairEditorialItem_article.graphql.ts
  src/v2/__generated__/fairRoutes_FairQuery.graphql.ts
Labels: Jira Synced

#7890 feat: (PURCHASE-2790) remove message count from conversation snippet
  src/v2/Apps/Conversation/Components/ConversationSnippet.tsx
  src/v2/__generated__/ConversationAppTestQuery.graphql.ts
  src/v2/__generated__/ConversationListQuery.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationSnippet_conversation.graphql.ts
  src/v2/__generated__/conversationRoutes_ConversationQuery.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Squash On Green

#7846 Render “respond-to/confirm offer” page in modal
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/ConversationCTA.tsx
  src/v2/Apps/Conversation/Components/Details.tsx
  src/v2/Apps/Conversation/Components/OrderModal.tsx
  src/v2/Apps/Conversation/Components/Reply.tsx
  src/v2/Apps/Conversation/Components/ReviewOfferCTA.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConversationCTA.jest.tsx
  src/v2/Apps/Conversation/Utils/returnOrderModalDetails.tsx
  src/v2/Apps/Conversation/__tests__/Reply.jest.tsx
  src/v2/Apps/Order/OrderApp.tsx
  src/v2/Components/NavBar/MinimalNavBar.tsx
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#7903 feat(home): updates above the fold design/layout
  package.json
  src/v2/Apps/Home/Components/HomeCarousel.tsx
  src/v2/Apps/Home/Components/HomeFeaturedCategoriesRail.tsx
  src/v2/Apps/Home/Components/HomeFeaturedEventsRail.tsx
  src/v2/Apps/Home/Components/HomeHeroUnit.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitLoggedOut.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnits.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitsLarge.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitsSmall.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/index.ts
  src/v2/Apps/Home/Components/HomeSwiper.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Apps/Home/__tests__/HomeApp.jest.tsx
  src/v2/__generated__/HomeApp_Test_Query.graphql.ts
  src/v2/__generated__/HomeApp_homePage.graphql.ts
  src/v2/__generated__/HomeFeaturedEventsRail_orderedSet.graphql.ts
  src/v2/__generated__/HomeHeroUnitsLarge_homePage.graphql.ts
  src/v2/__generated__/HomeHeroUnitsSmall_homePage.graphql.ts
  src/v2/__generated__/HomeHeroUnits_homePage.graphql.ts
  src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts
  yarn.lock
Labels: Squash On Green

#7905 feat(home): improves show event time display
  src/v2/Apps/Home/Components/HomeFeaturedShow.tsx
  src/v2/Apps/Home/Components/HomeFeaturedShows.tsx
  src/v2/Apps/Home/__tests__/HomeFeaturedShows.jest.tsx
  src/v2/__generated__/HomeFeaturedShow_show.graphql.ts
  src/v2/__generated__/HomeFeaturedShowsQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedShows_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedShows_orderedSet.graphql.ts
Labels: Squash On Green

#7906 feat(home): preloads initial hero unit image
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
Labels: Squash On Green
