Repository artsy/force, pull requests merged in 2021-02, with the labels that each got.

#6958 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6961 fix: Add download iOS app badge to desktop footer
  src/v2/Components/Footer.tsx
Labels: Merge On Green

#6962 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6964 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6967 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/v2/__generated__/ArtistsQuery.graphql.ts
  src/v2/__generated__/Artists_gene.graphql.ts
  src/v2/__generated__/ArtworkFilterArtworkGrid_filtered_artworks.graphql.ts
  src/v2/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/v2/__generated__/CollectionAppQuery.graphql.ts
  src/v2/__generated__/Collection_collection.graphql.ts
  src/v2/__generated__/Dropdown_aggregation.graphql.ts
  src/v2/__generated__/FairArtworksQuery.graphql.ts
  src/v2/__generated__/FairArtworks_Query.graphql.ts
  src/v2/__generated__/GeneArtworks_gene.graphql.ts
  src/v2/__generated__/ShowArtworksQuery.graphql.ts
  src/v2/__generated__/TagArtworks_tag.graphql.ts
  src/v2/__generated__/Works_artist.graphql.ts
  src/v2/__generated__/artistRoutes_WorksQuery.graphql.ts
  src/v2/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairArtworksQuery.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
Labels: Merge On Green

#6968 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/v2/__generated__/ArtistsQuery.graphql.ts
  src/v2/__generated__/Artists_gene.graphql.ts
  src/v2/__generated__/ArtworkFilterArtworkGrid_filtered_artworks.graphql.ts
  src/v2/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/v2/__generated__/CollectionAppQuery.graphql.ts
  src/v2/__generated__/Collection_collection.graphql.ts
  src/v2/__generated__/Dropdown_aggregation.graphql.ts
  src/v2/__generated__/FairArtworksQuery.graphql.ts
  src/v2/__generated__/FairArtworks_Query.graphql.ts
  src/v2/__generated__/GeneArtworks_gene.graphql.ts
  src/v2/__generated__/ShowArtworksQuery.graphql.ts
  src/v2/__generated__/TagArtworks_tag.graphql.ts
  src/v2/__generated__/Works_artist.graphql.ts
  src/v2/__generated__/artistRoutes_WorksQuery.graphql.ts
  src/v2/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairArtworksQuery.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
Labels: Merge On Green

#6970 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6972 Fix CoffeeScript issue so "Page"s will render
  src/desktop/apps/page/routes.coffee
Labels: Squash On Green

#6974 Update metaphysics schema
  data/schema.graphql
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/v2/__generated__/CreateAppSecondFactorMutation.graphql.ts
  src/v2/__generated__/CreateSmsSecondFactorMutation.graphql.ts
  src/v2/__generated__/DisableSecondFactorMutation.graphql.ts
  src/v2/__generated__/ShippingTestQuery.graphql.ts
  src/v2/__generated__/orderRoutes_ShippingQuery.graphql.ts
Labels: Squash On Green

#6976 fix(fairs): ensures there is always a single h1
  src/v2/Apps/Fairs/Components/FairsPastFairs.tsx
  src/v2/Apps/Fairs/Routes/FairsIndex.tsx
Labels: Squash On Green

#6978 chore: Describes a common issue when running locally
  CONTRIBUTING.md
Labels: Merge On Green

#6983 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6986 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/v2/__generated__/ArtistsQuery.graphql.ts
  src/v2/__generated__/Artists_gene.graphql.ts
  src/v2/__generated__/ArtworkFilterArtworkGrid_filtered_artworks.graphql.ts
  src/v2/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/v2/__generated__/CollectionAppQuery.graphql.ts
  src/v2/__generated__/Collection_collection.graphql.ts
  src/v2/__generated__/Dropdown_aggregation.graphql.ts
  src/v2/__generated__/FairArtworksQuery.graphql.ts
  src/v2/__generated__/FairArtworks_Query.graphql.ts
  src/v2/__generated__/GeneArtworks_gene.graphql.ts
  src/v2/__generated__/ShowArtworksQuery.graphql.ts
  src/v2/__generated__/TagArtworks_tag.graphql.ts
  src/v2/__generated__/Works_artist.graphql.ts
  src/v2/__generated__/artistRoutes_WorksQuery.graphql.ts
  src/v2/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairArtworksQuery.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
Labels: Merge On Green

#6987 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6995 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#6996 (GRO-188): Updated unsubscribe redirect to anchor tag to Email Preferences
  src/desktop/apps/unsubscribe/index.coffee
Labels: Jira Synced

#7006 fix(fairs): handles mobile view in a consistent fashion
  src/v2/Apps/Fairs/Components/FairsFairRow.tsx
  src/v2/Apps/Fairs/Components/__tests__/FairsFairRow.jest.tsx
  src/v2/Apps/Fairs/Routes/FairsIndex.tsx
  src/v2/__generated__/FairsFairRow_Test_Query.graphql.ts
  src/v2/__generated__/FairsFairRow_fair.graphql.ts
  src/v2/__generated__/FairsIndex_Test_Query.graphql.ts
  src/v2/__generated__/FairsPastFairsQuery.graphql.ts
  src/v2/__generated__/fairsRoutes_FairsQuery.graphql.ts
Labels: Merge On Green

#7014 feature: Registered Event Handlers
  src/lib/mediator.ts
  src/v2/Apps/Artist/Components/__tests__/ArtistHeader.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkDetails/__tests__/RequestConditionReport.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarArtists.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx
  src/v2/Apps/Artwork/Components/__tests__/ArtistInfo.jest.tsx
  src/v2/Apps/Collect/Routes/Collection/Components/Header/__tests__/Header.jest.tsx
  src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
  src/v2/Components/Artwork/SaveButton/__tests__/SaveButton.jest.tsx
  src/v2/Components/FollowButton/__tests__/FollowArtistButton.jest.tsx
  src/v2/Components/FollowButton/__tests__/FollowProfileButton.jest.tsx
  src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
  src/v2/Components/__tests__/ArtistCard.jest.tsx
  src/v2/Utils/__tests__/openAuthModal.jest.ts
  src/v2/Utils/openAuthModal.ts
Labels: Merge On Green

#7018 fix: Nagivate to Search on Enter
  src/v2/Components/Search/SearchBar.tsx
Labels: Merge On Green

#7022 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7023 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7027 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7029 chore: Remove Invalid Lint Rule Ignore
  src/v2/Apps/Artwork/artworkRoutes.tsx
  src/v2/Apps/Auction/auctionRoutes.tsx
  src/v2/Apps/Consign/consignRoutes.tsx
  src/v2/Apps/Debug/debugRoutes.tsx
  src/v2/Apps/Feature/featureRoutes.tsx
  src/v2/Apps/FeatureAKG/featureAKGRoutes.tsx
  src/v2/Apps/IdentityVerification/identityVerificationRoutes.tsx
  src/v2/Apps/Order/orderRoutes.tsx
  src/v2/Apps/Purchase/purchaseRoutes.tsx
Labels: Merge On Green

#7037 fix: correct mutation file names
  src/v2/Apps/Order/Components/AddressModal.tsx
  src/v2/Apps/Order/Mutations/AddressModal.ts
  src/v2/Apps/Order/Mutations/ShippingCreateUserAddress.ts
  src/v2/Apps/Order/Mutations/ShippingOrderAddressUpdate.ts
  src/v2/Apps/Order/Mutations/shippingMutations.ts
  src/v2/Apps/Order/Routes/Shipping/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
Labels: Merge On Green

#7039 feat: Add new payment app to replace stitched user payments tab
  src/desktop/apps/user/index.coffee
  src/desktop/components/react/stitch_components/index.tsx
  src/v2/Apps/Payment/Routes/Payment/PaymentApp.tsx
  src/v2/Apps/Payment/__tests__/PaymentApp.jest.tsx
  src/v2/Apps/Payment/paymentRoutes.tsx
  src/v2/Apps/getAppNovoRoutes.tsx
  src/v2/__generated__/PaymentApp_Test_Query.graphql.ts
  src/v2/__generated__/PaymentApp_me.graphql.ts
  src/v2/__generated__/paymentRoutes_PaymentQuery.graphql.ts
Labels: Jira Synced

#7043 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7047 GRO-174: Adding H1 Tag on artsy.net/articles for SEO
  src/desktop/apps/article/components/App.tsx
  src/desktop/apps/articles/templates/articles.jade
Labels: Jira Synced, Squash On Green

#7059 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7068 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/v2/__generated__/ArtistsQuery.graphql.ts
  src/v2/__generated__/Artists_gene.graphql.ts
  src/v2/__generated__/ArtworkFilterArtworkGrid_filtered_artworks.graphql.ts
  src/v2/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/v2/__generated__/CollectionAppQuery.graphql.ts
  src/v2/__generated__/Collection_collection.graphql.ts
  src/v2/__generated__/Dropdown_aggregation.graphql.ts
  src/v2/__generated__/FairArtworksQuery.graphql.ts
  src/v2/__generated__/FairArtworks_Query.graphql.ts
  src/v2/__generated__/GeneArtworks_gene.graphql.ts
  src/v2/__generated__/ShowArtworksQuery.graphql.ts
  src/v2/__generated__/TagArtworks_tag.graphql.ts
  src/v2/__generated__/Works_artist.graphql.ts
  src/v2/__generated__/artistRoutes_WorksQuery.graphql.ts
  src/v2/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairArtworksQuery.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
Labels: Merge On Green

#7070 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7076 chore: GRO-213: Adding LazyLoadComponent to FooterBanner
  src/v2/Components/Footer.tsx
  src/v2/Components/NavBar/NavBar.tsx
  src/v2/Components/NavBar/NavItem.tsx
  src/v2/Utils/ScrollIntoView.tsx
  src/v2/Utils/scrollHelpers.ts
Labels: Jira Synced, Merge On Green

#7085 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/CreateCreditCardAndUpdatePhoneMutation.graphql.ts
  src/v2/__generated__/UpdateUserInformationMutation.graphql.ts
  src/v2/__generated__/UserEmailPreferencesMutation.graphql.ts
Labels: Merge On Green

#7089 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7090 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green
