Repository artsy/force, pull requests merged in 2021-11, with the labels that each got.

#8776 Deploy
  data/schema.graphql
  package.json
  src/v2/Apps/Auction/Components/BidForm.tsx
  src/v2/Apps/Auction/Components/RegistrationForm.tsx
  src/v2/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/v2/Apps/Auction/Routes/Register/index.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutosuggest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutosuggest.jest.tsx
  src/v2/Apps/Search/Components/GenericSearchResultItem.tsx
  src/v2/Apps/Search/Routes/SearchResultsArtists.tsx
  src/v2/Apps/Search/Routes/SearchResultsEntity.tsx
  src/v2/Apps/Search/Routes/__tests__/SearchResultsArtists.jest.tsx
  src/v2/Apps/Search/Routes/__tests__/SearchResultsEntity.jest.tsx
  src/v2/Apps/Search/SearchApp.tsx
  src/v2/__generated__/RegisterButton_Test_Query.graphql.ts
  src/v2/__generated__/RegisterButton_sale.graphql.ts
  src/v2/__generated__/StatusQuery.graphql.ts
  src/v2/__generated__/Status_order.graphql.ts
  src/v2/__generated__/auction2Routes_TopLevelQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#8781 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/CreateCreditCardAndUpdatePhoneMutation.graphql.ts
  src/v2/__generated__/UpdateUserInformationMutation.graphql.ts
  src/v2/__generated__/UserEmailPreferencesMutation.graphql.ts
  src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
Labels: Merge On Green

#8780 Deploy
  .storybook/preview.js
  data/schema.graphql
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/PhotoDropzone.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/PhotoDropzone.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/fileUtils.jest.ts
  src/v2/Apps/Fairs/Components/FairsFairBanner.tsx
  src/v2/Apps/Fairs/Components/FairsFairRow.tsx
  src/v2/Apps/Fairs/Routes/FairsIndex.tsx
  src/v2/Apps/Home/Components/HomeCarousel.tsx
  src/v2/Apps/Home/Components/HomeCurrentFairs.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnits.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitsLarge.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitsSmall.tsx
  src/v2/Apps/Home/Components/HomeSwiper.tsx
  src/v2/Apps/Partners/Components/PartnersFeaturedCarousel.tsx
  src/v2/Apps/Partners/Components/PartnersFeaturedCarouselCell.tsx
  src/v2/Apps/Partners/Components/__tests__/PartnersFeaturedCarousel.jest.tsx
  src/v2/Apps/Partners/Routes/GalleriesRoute.tsx
  src/v2/Apps/Partners/Routes/InstitutionsRoute.tsx
  src/v2/Apps/Partners/Routes/__tests__/GalleriesRoute.jest.tsx
  src/v2/Apps/Partners/Routes/__tests__/InstitutionsRoute.jest.tsx
  src/v2/Components/HeroCarousel/HeroCarousel.story.tsx
  src/v2/Components/HeroCarousel/HeroCarousel.tsx
  src/v2/Components/HeroCarousel/HeroCarouselLarge.tsx
  src/v2/Components/HeroCarousel/HeroCarouselSmall.tsx
  src/v2/System/Server/sharifyHelpers.ts
  src/v2/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/CreateCreditCardAndUpdatePhoneMutation.graphql.ts
  src/v2/__generated__/FairsFairBanner_fair.graphql.ts
  src/v2/__generated__/FairsFairRow_Test_Query.graphql.ts
  src/v2/__generated__/FairsFairRow_fair.graphql.ts
  src/v2/__generated__/FairsIndex_Test_Query.graphql.ts
  src/v2/__generated__/FairsIndex_viewer.graphql.ts
  src/v2/__generated__/FairsPastFairsQuery.graphql.ts
  src/v2/__generated__/GalleriesRouteFragmentContainer_Test_Query.graphql.ts
  src/v2/__generated__/GalleriesRoute_viewer.graphql.ts
  src/v2/__generated__/HomeCurrentFairsQuery.graphql.ts
  src/v2/__generated__/HomeCurrentFairs_Test_Query.graphql.ts
  src/v2/__generated__/HomeCurrentFairs_viewer.graphql.ts
  src/v2/__generated__/InstitutionsRouteFragmentContainer_Test_Query.graphql.ts
  src/v2/__generated__/InstitutionsRoute_viewer.graphql.ts
  src/v2/__generated__/PartnersFeaturedCarouselCell_profile.graphql.ts
  src/v2/__generated__/PartnersFeaturedCarousel_Test_Query.graphql.ts
  src/v2/__generated__/PartnersFeaturedCarousel_viewer.graphql.ts
  src/v2/__generated__/UpdateUserInformationMutation.graphql.ts
  src/v2/__generated__/UserEmailPreferencesMutation.graphql.ts
  src/v2/__generated__/fairsRoutes_FairsQuery.graphql.ts
  src/v2/__generated__/partnersRoutes_GalleriesRouteQuery.graphql.ts
  src/v2/__generated__/partnersRoutes_InstitutionsRouteQuery.graphql.ts
  src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
Labels: Jira Synced

#8786 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8790 chore(CX-2114): update copy on price-database
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
Labels: Jira Synced

#8791 chore: Github Package Authentication
  package.json
  src/middleware.ts
  yarn.lock
Labels: Merge On Green

#8798 feat(partners): implements filtered partners
  src/v2/Apps/Partners/Components/PartnersFilteredCells.tsx
  src/v2/Apps/Partners/Components/PartnersRail.tsx
  src/v2/Apps/Partners/Components/PartnersRails.tsx
  src/v2/Apps/Partners/Routes/GalleriesRoute.tsx
  src/v2/Apps/Partners/Routes/InstitutionsRoute.tsx
  src/v2/Apps/Partners/Routes/__tests__/GalleriesRoute.jest.tsx
  src/v2/Apps/Partners/Routes/__tests__/InstitutionsRoute.jest.tsx
  src/v2/Components/Cells/PartnerCell.tsx
  src/v2/__generated__/GalleriesRouteFragmentContainer_Test_Query.graphql.ts
  src/v2/__generated__/GalleriesRoute_viewer.graphql.ts
  src/v2/__generated__/InstitutionsRouteFragmentContainer_Test_Query.graphql.ts
  src/v2/__generated__/InstitutionsRoute_viewer.graphql.ts
  src/v2/__generated__/PartnerCellFragmentContainer_Test_Query.graphql.ts
  src/v2/__generated__/PartnerCell_partner.graphql.ts
  src/v2/__generated__/PartnersFilteredCellsQuery.graphql.ts
  src/v2/__generated__/PartnersFilteredCells_viewer.graphql.ts
  src/v2/__generated__/PartnersRail_partnerCategory.graphql.ts
  src/v2/__generated__/PartnersRailsQuery.graphql.ts
  src/v2/__generated__/PartnersRails_viewer.graphql.ts
  src/v2/__generated__/partnersRoutes_GalleriesRouteQuery.graphql.ts
  src/v2/__generated__/partnersRoutes_InstitutionsRouteQuery.graphql.ts
Labels: Merge On Green

#8806 feat(SWA-78): Reintroduce contact information step to submission flow
  src/v2/Apps/Consign/Components/SubmissionStepper.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmission.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmissionInput.ts
  src/v2/Utils/Hooks/useAuthIntent/index.ts
Labels: Merge On Green

#8809 fix(partners): location autocomplete serves all locations
  src/v2/Apps/Partners/Components/PartnersLocationAutocomplete.tsx
  src/v2/__generated__/PartnersLocationAutocompleteQuery.graphql.ts
  src/v2/__generated__/PartnersLocationAutocomplete_Test_Query.graphql.ts
  src/v2/__generated__/PartnersLocationAutocomplete_viewer.graphql.ts
Labels: Merge On Green

#8808 fix: User Page Import
  src/desktop/apps/user/components/categories/view.coffee
Labels: Merge On Green

#8812 Deploy
  .circleci/config.yml
  src/desktop/apps/user/components/categories/view.coffee
  src/v2/Apps/Partners/Components/PartnersLocationAutocomplete.tsx
  src/v2/__generated__/PartnersLocationAutocompleteQuery.graphql.ts
  src/v2/__generated__/PartnersLocationAutocomplete_Test_Query.graphql.ts
  src/v2/__generated__/PartnersLocationAutocomplete_viewer.graphql.ts
Labels: Jira Synced

#8818 fix(router): Make onServerSideRender calls async
  src/v2/Apps/Artwork/Server/__tests__/handleArtworkImageDownload.jest.ts
  src/v2/Apps/Artwork/Server/handleArtworkImageDownload.ts
  src/v2/Apps/Artwork/artworkRoutes.tsx
  src/v2/System/Router/buildServerApp.tsx
Labels: Merge On Green

#8820 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8782 feat(FX-3513): Added alerts_only email frequency option
  src/v2/Apps/Unsubscribe/Components/UnsubscribeLoggedIn.tsx
  src/v2/Components/UserSettings/UserEmailPreferences/index.tsx
Labels: Jira Synced

#8610 feat(FX-3442): Create alert button for Saved Search
  .secrets.baseline
  src/config.ts
  src/lib/setup_sharify.js
  src/typings/sharify.d.ts
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Assets/Animations.tsx
  src/v2/Components/ArtworkFilter/CreateAlertButton.tsx
  src/v2/Components/ArtworkFilter/FiltersPills.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/CreateCreditCardAndUpdatePhoneMutation.graphql.ts
  src/v2/__generated__/UpdateUserInformationMutation.graphql.ts
  src/v2/__generated__/UserEmailPreferencesMutation.graphql.ts
  src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
Labels: Jira Synced

#8825 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/CreateCreditCardAndUpdatePhoneMutation.graphql.ts
  src/v2/__generated__/UpdateUserInformationMutation.graphql.ts
  src/v2/__generated__/UserEmailPreferencesMutation.graphql.ts
  src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
Labels: Merge On Green

#8828 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8816 fix: show no modal message when collector submits offer on unlisted price artworks
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Order/Routes/Respond/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/DevTools/createTestEnv.tsx
  src/v2/__generated__/OfferTestQuery.graphql.ts
  src/v2/__generated__/Offer_order.graphql.ts
  src/v2/__generated__/RespondCounterOfferMutation.graphql.ts
  src/v2/__generated__/RespondTestQuery.graphql.ts
  src/v2/__generated__/Respond_order.graphql.ts
  src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/v2/__generated__/orderRoutes_RespondQuery.graphql.ts
Labels: Merge On Green

#8832 Revert "fix: show no modal message when collector submits offer on unlisted price artworks"
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Order/Routes/Respond/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/DevTools/createTestEnv.tsx
  src/v2/__generated__/OfferTestQuery.graphql.ts
  src/v2/__generated__/Offer_order.graphql.ts
  src/v2/__generated__/RespondCounterOfferMutation.graphql.ts
  src/v2/__generated__/RespondTestQuery.graphql.ts
  src/v2/__generated__/Respond_order.graphql.ts
  src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/v2/__generated__/orderRoutes_RespondQuery.graphql.ts
Labels: Merge On Green

#8833 chore(buttons): use "Show More" / primary variant for pagination buttons
  src/v2/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
  src/v2/Apps/Auctions/Routes/CurrentAuctions.tsx
  src/v2/Apps/Auctions/Routes/PastAuctions.tsx
  src/v2/Apps/Auctions/Routes/UpcomingAuctions.tsx
  src/v2/Apps/Auctions/Routes/__tests__/CurrentAuctions.jest.tsx
  src/v2/Apps/Auctions/Routes/__tests__/PastAuctions.jest.tsx
  src/v2/Apps/Auctions/Routes/__tests__/UpcomingAuctions.jest.tsx
  src/v2/Apps/Fair/Routes/FairArticles.tsx
  src/v2/Apps/Fairs/Components/FairsPastFairs.tsx
  src/v2/Apps/Shows/Components/ShowsCurrentShows.tsx
Labels: Merge On Green

#8834 chore(home): use higher resolution image versions
  src/v2/Apps/Home/Components/HomeFeaturedEventsRail.tsx
  src/v2/__generated__/HomeApp_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedEventsRail_orderedSet.graphql.ts
  src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts
Labels: Merge On Green

#8836 feat(GRO-635): Add unique title on for sale page
  cypress/integration/artist.spec.js
  src/v2/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
  src/v2/Apps/Artist/Utils/__tests__/computeTitle.jest.tsx
  src/v2/Apps/Artist/Utils/computeTitle.ts
Labels: Merge On Green, Jira Synced

#8840 Deploy
  cypress/integration/artist.spec.js
  src/v2/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
  src/v2/Apps/Artist/Utils/__tests__/computeTitle.jest.tsx
  src/v2/Apps/Artist/Utils/computeTitle.ts
Labels: Jira Synced

#8846 feat(GRO-596): Edit profile / About You
  src/v2/Apps/Components/AppToasts.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileAboutYou.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileAboutYou.jest.tsx
  src/v2/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
  src/v2/Apps/Settings/SettingsApp.tsx
  src/v2/Apps/Settings/settingsRoutes.tsx
  src/v2/Components/Inquiry/Hooks/useUpdateMyUserProfile.ts
  src/v2/Components/Inquiry/Views/InquiryBasicInfo.tsx
  src/v2/Components/Inquiry/Views/InquiryCommercialInterest.tsx
  src/v2/Components/Inquiry/__tests__/Views/InquiryBasicInfo.jest.tsx
  src/v2/Components/Inquiry/__tests__/Views/InquiryCommercialInterest.jest.tsx
  src/v2/Components/LocationAutocompleteInput.tsx
  src/v2/Utils/Hooks/Mutations/useUpdateMyUserProfile.ts
  src/v2/__generated__/SettingsEditProfileAboutYou_Test_Query.graphql.ts
  src/v2/__generated__/SettingsEditProfileAboutYou_me.graphql.ts
  src/v2/__generated__/SettingsEditProfileRoute_me.graphql.ts
  src/v2/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts
  src/v2/__generated__/settingsRoutes_PurchasesRouteQuery.graphql.ts
  src/v2/__generated__/settingsRoutes_SavesRouteQuery.graphql.ts
  src/v2/__generated__/settingsRoutes_SettingsRouteQuery.graphql.ts
Labels: Merge On Green

#8843 feat(SWA-97): Provenance field on the Artwork Details page
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/useSubmission.jest.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmissionInput.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
Labels: Squash On Green

#8850 fix(FX-3559): Dropdown filters on /galleries page
  src/desktop/apps/galleries_institutions/components/primary_carousel/fetch.coffee
Labels: Jira Synced

#8845 Deploy
  package.json
  src/desktop/apps/galleries_institutions/components/primary_carousel/fetch.coffee
  src/v2/Apps/Components/AppToasts.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutosuggest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutosuggest.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/useSubmission.jest.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmissionInput.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
  src/v2/Apps/Partners/Components/PartnersFilteredCells.tsx
  src/v2/Apps/Partners/Components/PartnersLocationAutocomplete.tsx
  src/v2/Apps/Partners/Components/PartnersSpecialtyAutocomplete.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileAboutYou.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileAboutYou.jest.tsx
  src/v2/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
  src/v2/Apps/Settings/SettingsApp.tsx
  src/v2/Apps/Settings/settingsRoutes.tsx
  src/v2/Components/Inquiry/Hooks/useUpdateMyUserProfile.ts
  src/v2/Components/Inquiry/Views/InquiryBasicInfo.tsx
  src/v2/Components/Inquiry/Views/InquiryCommercialInterest.tsx
  src/v2/Components/Inquiry/__tests__/Views/InquiryBasicInfo.jest.tsx
  src/v2/Components/Inquiry/__tests__/Views/InquiryCommercialInterest.jest.tsx
  src/v2/Components/LocationAutocompleteInput.tsx
  src/v2/Utils/Hooks/Mutations/useUpdateMyUserProfile.ts
  src/v2/__generated__/PartnersFilteredCellsQuery.graphql.ts
  src/v2/__generated__/PartnersFilteredCells_viewer.graphql.ts
  src/v2/__generated__/PartnersSpecialtyAutocompleteQuery.graphql.ts
  src/v2/__generated__/PartnersSpecialtyAutocomplete_Test_Query.graphql.ts
  src/v2/__generated__/PartnersSpecialtyAutocomplete_viewer.graphql.ts
  src/v2/__generated__/SettingsEditProfileAboutYou_Test_Query.graphql.ts
  src/v2/__generated__/SettingsEditProfileAboutYou_me.graphql.ts
  src/v2/__generated__/SettingsEditProfileRoute_me.graphql.ts
  src/v2/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts
  src/v2/__generated__/settingsRoutes_PurchasesRouteQuery.graphql.ts
  src/v2/__generated__/settingsRoutes_SavesRouteQuery.graphql.ts
  src/v2/__generated__/settingsRoutes_SettingsRouteQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#8810 refactor(PX-4655) - use displayState for calculating statuses on Purchase app
  src/v2/Apps/Purchase/Components/OrderRow.tsx
  src/v2/Apps/Purchase/Utils/orderHelper.tsx
  src/v2/Apps/Purchase/__tests__/PurchaseApp.jest.tsx
  src/v2/Apps/Purchase/__tests__/orderHelper.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/__generated__/OrderRow_order.graphql.ts
  src/v2/__generated__/PurchaseAppTestQuery.graphql.ts
  src/v2/__generated__/PurchaseHistoryQuery.graphql.ts
  src/v2/__generated__/purchaseRoutes_PurchaseQuery.graphql.ts
Labels: Jira Synced

#8854 Deploy
  Dockerfile
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/v2/Apps/Purchase/Components/OrderRow.tsx
  src/v2/Apps/Purchase/Utils/orderHelper.tsx
  src/v2/Apps/Purchase/__tests__/PurchaseApp.jest.tsx
  src/v2/Apps/Purchase/__tests__/orderHelper.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/__generated__/ArtistAuctionResultItem_auctionResult.graphql.ts
  src/v2/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/v2/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
  src/v2/__generated__/OrderRow_order.graphql.ts
  src/v2/__generated__/PurchaseAppTestQuery.graphql.ts
  src/v2/__generated__/PurchaseHistoryQuery.graphql.ts
  src/v2/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
  src/v2/__generated__/purchaseRoutes_PurchaseQuery.graphql.ts
Labels: Jira Synced

#8857 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8855 fix(FX-3562): Unable to click the "view all" buttons on partner page in mobile browser
  src/v2/Apps/Partner/Components/Overview/ArticlesRail.tsx
  src/v2/Apps/Partner/Components/Overview/ArtistsRail.tsx
  src/v2/Apps/Partner/Components/Overview/ArtworksRail.tsx
  src/v2/Apps/Partner/Components/Overview/ShowsRail.tsx
Labels: Jira Synced

#8862 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8863 fix(artist): corrects copy
  src/v2/Apps/Artist/Routes/CV/ArtistCVRoute.tsx
Labels: Merge On Green

#8856 Deploy
  data/schema.graphql
  package.json
  src/v2/Apps/Artist/Routes/CV/ArtistCVRoute.tsx
  src/v2/Apps/Partner/Components/Overview/ArticlesRail.tsx
  src/v2/Apps/Partner/Components/Overview/ArtistsRail.tsx
  src/v2/Apps/Partner/Components/Overview/ArtworksRail.tsx
  src/v2/Apps/Partner/Components/Overview/ShowsRail.tsx
  src/v2/Components/NavBar/NavBar.tsx
  src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/v2/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
  src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
  src/v2/System/Server/sharifyHelpers.ts
  yarn.lock
Labels: Jira Synced

#8870 Deploy
  src/v2/Apps/Fair/Components/FairBooths.tsx
  src/v2/Apps/Fair/Components/__tests__/FairBooths.jest.tsx
  src/v2/__generated__/FairBoothsContainerQuery.graphql.ts
  src/v2/__generated__/FairBoothsQuery.graphql.ts
  src/v2/__generated__/FairBooths_Query.graphql.ts
  src/v2/__generated__/FairBooths_fair.graphql.ts
  src/v2/__generated__/fairRoutes_FairBoothsQuery.graphql.ts
Labels: Jira Synced

#8869 chore: marketing copy updates #trivial
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseSearch.tsx
Labels: Squash On Green

#8858 feat(FX-3517): Added fair logo to sticky menu
  src/v2/Apps/Fair/Components/FairHeader/FairHeader.tsx
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/__generated__/FairApp_Test_Query.graphql.ts
  src/v2/__generated__/FairApp_fair.graphql.ts
  src/v2/__generated__/fairRoutes_FairQuery.graphql.ts
Labels: Jira Synced

#8872 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8874 feat(settings): implements artists you collect/gallery intro
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/SettingsEditProfileArtistsYouCollect.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/SettingsEditProfileArtistsYouCollectRemoveButton.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/useAddArtistYouCollect.ts
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/useRemoveArtistYouCollect.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileYourGalleryIntro.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileYourGalleryIntro.jest.tsx
  src/v2/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
  src/v2/__generated__/SettingsEditProfileArtistsYouCollectAutocompleteQuery.graphql.ts
  src/v2/__generated__/SettingsEditProfileArtistsYouCollect_me.graphql.ts
  src/v2/__generated__/SettingsEditProfileRoute_me.graphql.ts
  src/v2/__generated__/SettingsEditProfileYourGalleryIntro_Test_Query.graphql.ts
  src/v2/__generated__/SettingsEditProfileYourGalleryIntro_me.graphql.ts
  src/v2/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts
  src/v2/__generated__/useAddArtistYouCollectMutation.graphql.ts
  src/v2/__generated__/useRemoveArtistYouCollectMutation.graphql.ts
Labels: Merge On Green

#8883 chore(GRO-660): Change metadata for Price Database
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseMeta.tsx
Labels: Merge On Green, Jira Synced

#8889 feat(partners): lazily load individual rails
  src/v2/Apps/Partners/Components/PartnersRail.tsx
  src/v2/Apps/Partners/Components/PartnersRails.tsx
  src/v2/System/Relay/SystemQueryRenderer.tsx
  src/v2/__generated__/PartnersRailQuery.graphql.ts
  src/v2/__generated__/PartnersRail_partnerCategory.graphql.ts
  src/v2/__generated__/PartnersRailsQuery.graphql.ts
  src/v2/__generated__/PartnersRails_viewer.graphql.ts
Labels: Merge On Green

#8891 docs(best-practices): Update examples
  docs/best_practices.md
  src/v2/DevTools/setupTestWrapper.tsx
Labels: Merge On Green

#8888 Deploy
  .circleci/config.yml
  docs/best_practices.md
  src/desktop/components/main_layout/templates/scripts.jade
  src/mobile/components/layout/templates/scaffold.jade
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
  src/v2/Apps/Partners/Components/PartnersRail.tsx
  src/v2/Apps/Partners/Components/PartnersRails.tsx
  src/v2/DevTools/setupTestWrapper.tsx
  src/v2/System/Relay/SystemQueryRenderer.tsx
  src/v2/__generated__/PartnersRailQuery.graphql.ts
  src/v2/__generated__/PartnersRail_partnerCategory.graphql.ts
  src/v2/__generated__/PartnersRailsQuery.graphql.ts
  src/v2/__generated__/PartnersRails_viewer.graphql.ts
Labels: Jira Synced

#8893 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8847 refactor(NX-2867): refactor inquiryModal and upgrades tests
  docs/best_practices.md
  src/desktop/components/pageable_collection/README.md
  src/v2/Apps/Conversation/Components/ConversationCTA.tsx
  src/v2/Apps/Conversation/Components/OpenInquiryModalButton.tsx
  src/v2/Apps/Conversation/Components/OpenInquiryModalCTA.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConfirmArtwork.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/Conversation.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConversationCTA.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConversationMessages.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/Item.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/Message.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/OpenInquiryModalCTA.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/OrderUpdate.jest.tsx
  src/v2/Apps/Conversation/__tests__/ConversationApp.jest.tsx
  src/v2/__generated__/ConversationCTA_Test_Query.graphql.ts
  src/v2/__generated__/ConversationCTA_conversation.graphql.ts
  src/v2/__generated__/ConversationMessages_Test_Query.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/ConversationPagination_Test_Query.graphql.ts
  src/v2/__generated__/Item_Test_Query.graphql.ts
  src/v2/__generated__/OpenInquiryModalButtonQuery.graphql.ts
  src/v2/__generated__/OpenInquiryModalCTA_Test_Query.graphql.ts
  src/v2/__generated__/OpenInquiryModalCTA_conversation.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Jira Synced

#8894 Deploy
  data/schema.graphql
  docs/best_practices.md
  package.json
  src/desktop/components/pageable_collection/README.md
  src/v2/Apps/Conversation/Components/ConversationCTA.tsx
  src/v2/Apps/Conversation/Components/OpenInquiryModalButton.tsx
  src/v2/Apps/Conversation/Components/OpenInquiryModalCTA.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConfirmArtwork.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/Conversation.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConversationCTA.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConversationMessages.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/Item.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/Message.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/OpenInquiryModalCTA.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/OrderUpdate.jest.tsx
  src/v2/Apps/Conversation/__tests__/ConversationApp.jest.tsx
  src/v2/Apps/Home/Components/HomeFeaturedGalleriesRail.tsx
  src/v2/__generated__/ConversationCTA_Test_Query.graphql.ts
  src/v2/__generated__/ConversationCTA_conversation.graphql.ts
  src/v2/__generated__/ConversationMessages_Test_Query.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/ConversationPagination_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedGalleriesRailQuery.graphql.ts
  src/v2/__generated__/Item_Test_Query.graphql.ts
  src/v2/__generated__/OpenInquiryModalButtonQuery.graphql.ts
  src/v2/__generated__/OpenInquiryModalCTA_Test_Query.graphql.ts
  src/v2/__generated__/OpenInquiryModalCTA_conversation.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#8903 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8879 fix(FX-2928): Track only allowed filter keys in commercial_filter_params_changed
  src/v2/Components/ArtworkFilter/index.tsx
Labels: Jira Synced

#8908 fix(settings): restores old form; reorganization
  src/desktop/components/react/stitch_components/index.tsx
  src/v2/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
  src/v2/Apps/Settings/Routes/EditSettings/SettingsEditSettingsInformation.tsx
  src/v2/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
  src/v2/Apps/Settings/Routes/EditSettings/useUpdateSettingsInformation.ts
  src/v2/Apps/Settings/Routes/Settings/SettingsEditRoute.tsx
  src/v2/Apps/Settings/settingsRoutes.tsx
  src/v2/Components/UserSettings/UserInformation/UpdateUserInformationMutation.ts
  src/v2/Components/UserSettings/UserInformation/index.tsx
  src/v2/__generated__/SettingsEditProfileRoute_me.graphql.ts
  src/v2/__generated__/SettingsEditRoute_me.graphql.ts
  src/v2/__generated__/SettingsEditSettingsInformation_me.graphql.ts
  src/v2/__generated__/SettingsEditSettingsRoute_me.graphql.ts
  src/v2/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts
  src/v2/__generated__/settingsRoutes_SettingsEditProfileRouteQuery.graphql.ts
  src/v2/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
  src/v2/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Merge On Green

#8859 [FX-3343] Remove clickedAppDownload helper
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/SellWithArtsy.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SellWithArtsy.jest.tsx
  src/v2/Components/DownloadAppBadge.tsx
  src/v2/Components/__tests__/DownloadAppBadge.jest.tsx
Labels: Jira Synced

#8864 [FX-3344] Remove clickedArticleGroup helper
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/ReadMore.tsx
Labels: Jira Synced

#8909 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/CreateConsignSubmissionMutation.graphql.ts
Labels: Merge On Green

#8897 feat(SWA-128): Remove login modal from the contact information step
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/v2/Components/Authentication/Types.ts
  src/v2/Utils/Hooks/useAuthIntent/index.ts
Labels: Merge On Green

#8910 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8911 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/CreateConsignSubmissionMutation.graphql.ts
Labels: Merge On Green

#8899 feat(SWA-105): Add logic to determine whether a submission should be created anonymously
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmission.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmissionInput.ts
Labels: Jira Synced

#8920 feat(footer): updates to new image
  src/v2/Components/Footer/FooterDownloadAppBanner.tsx
Labels: Merge On Green

#8849 feat(FX-3443): create saved search alert modal
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/FilterExpandable.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
  src/v2/Components/ArtworkFilter/CreateAlertButton.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/FiltersPills.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Utils/aggregationForFilter.ts
  src/v2/Components/ArtworkFilter/SavedSearch/Utils/constants.ts
  src/v2/Components/ArtworkFilter/SavedSearch/Utils/index.ts
  src/v2/Components/ArtworkFilter/SavedSearch/Utils/savedSearchCriteria.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/types.ts
  src/v2/Components/ArtworkFilter/Utils/getElementParams.ts
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/Components/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/v2/Components/SavedSearchAlert/Mutations/createSavedSearchAlert.ts
  src/v2/Components/SavedSearchAlert/SavedSearchAlertForm.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModel.tsx
  src/v2/Components/SavedSearchAlert/Utils/extractPills.ts
  src/v2/Components/SavedSearchAlert/Utils/getNamePlaceholder.tsx
  src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertForm.jest.tsx
  src/v2/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ArtistArtworkFilter_artist.graphql.ts
  src/v2/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
  src/v2/__generated__/createSavedSearchAlertMutation.graphql.ts
Labels: Jira Synced

#8860 feat(FX-3514): remove exhibitors logo from list on Exhibitors A-Z tab
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorsGroup.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/__generated__/FairExhibitorCard_exhibitor.graphql.ts
  src/v2/__generated__/FairExhibitors_Test_Query.graphql.ts
  src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
Labels: Jira Synced

#8926 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8927 feature: Upload Progress
  packages/publish/uploadToS3.js
Labels: Merge On Green

#8898 feat: Add message to the order summary after purchase
  src/v2/Apps/Order/Components/ArtworkSummaryItem.tsx
  src/v2/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/v2/Components/DownloadAppBadges/DownloadAppBadge.tsx
  src/v2/Components/DownloadAppBadges/DownloadAppBadges.tsx
  src/v2/Components/DownloadAppBadges/__tests__/DownloadAppBadge.jest.tsx
  src/v2/Components/Footer/FooterDownloadAppBanner.tsx
  src/v2/Components/Footer/__tests__/Footer.jest.tsx
  src/v2/__generated__/AcceptTestQuery.graphql.ts
  src/v2/__generated__/CounterTestQuery.graphql.ts
  src/v2/__generated__/NewPaymentTestQuery.graphql.ts
  src/v2/__generated__/OfferTestQuery.graphql.ts
  src/v2/__generated__/PaymentTestQuery.graphql.ts
  src/v2/__generated__/RespondCounterOfferMutation.graphql.ts
  src/v2/__generated__/RespondTestQuery.graphql.ts
  src/v2/__generated__/ReviewTestQuery.graphql.ts
  src/v2/__generated__/ShippingTestQuery.graphql.ts
  src/v2/__generated__/StatusQuery.graphql.ts
  src/v2/__generated__/TransactionDetailsSummaryItemTestQuery.graphql.ts
  src/v2/__generated__/TransactionDetailsSummaryItem_order.graphql.ts
  src/v2/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/v2/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/v2/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/v2/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/v2/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/v2/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/v2/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/v2/__generated__/orderRoutes_StatusQuery.graphql.ts
Labels: Squash On Green

#8914 [Feat]: AlicanAkyuz/swa-118/create error modal hook
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/SubmissionLayout.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/useErrorModal.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/useErrorModal.tsx
Labels: Jira Synced

#8884 chore: adds US$ to USD currency in order app
  src/v2/Apps/Order/Components/OfferHistoryItem.tsx
  src/v2/Apps/Order/Components/OfferSummaryItem.tsx
  src/v2/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/v2/Apps/Order/Components/__tests__/OfferHistoryItem.jest.tsx
  src/v2/Apps/Order/Components/__tests__/TransactionDetailsSummary.jest.tsx
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Accept.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Counter.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Respond.jest.tsx
  src/v2/Apps/Order/Utils/currencyUtils.ts
  src/v2/Apps/Purchase/Components/OrderRow.tsx
  src/v2/Apps/Purchase/__tests__/PurchaseApp.jest.tsx
  src/v2/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/v2/__generated__/AcceptTestQuery.graphql.ts
  src/v2/__generated__/CounterTestQuery.graphql.ts
  src/v2/__generated__/NewPaymentTestQuery.graphql.ts
  src/v2/__generated__/OfferHistoryItemTestQuery.graphql.ts
  src/v2/__generated__/OfferHistoryItem_order.graphql.ts
  src/v2/__generated__/OfferSummaryItem_order.graphql.ts
  src/v2/__generated__/OfferTestQuery.graphql.ts
  src/v2/__generated__/OrderRow_order.graphql.ts
  src/v2/__generated__/PaymentTestQuery.graphql.ts
  src/v2/__generated__/PurchaseAppTestQuery.graphql.ts
  src/v2/__generated__/PurchaseHistoryQuery.graphql.ts
  src/v2/__generated__/RespondCounterOfferMutation.graphql.ts
  src/v2/__generated__/RespondTestQuery.graphql.ts
  src/v2/__generated__/ReviewTestQuery.graphql.ts
  src/v2/__generated__/ShippingTestQuery.graphql.ts
  src/v2/__generated__/StatusQuery.graphql.ts
  src/v2/__generated__/TransactionDetailsSummaryItemTestQuery.graphql.ts
  src/v2/__generated__/TransactionDetailsSummaryItem_order.graphql.ts
  src/v2/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/v2/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/v2/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/v2/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/v2/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/v2/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/v2/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/v2/__generated__/orderRoutes_StatusQuery.graphql.ts
  src/v2/__generated__/purchaseRoutes_PurchaseQuery.graphql.ts
Labels: Squash On Green

#8932 feat(SWA-127): Update Stepper headings for SWA mobile flow
  src/v2/Apps/Consign/Components/SubmissionStepper.tsx
Labels: Merge On Green, Jira Synced

#8943 fix(settings): removes validation for existing password input
  src/desktop/apps/user/components/password/index.jade
Labels: Merge On Green

#8940 fix: Attachment display on conversation sidebar
  src/v2/Apps/Conversation/Components/Details.tsx
Labels: Jira Synced

#8946 fix(partners): updates carousel to use connection
  src/v2/Apps/Partners/Components/PartnersFeaturedCarousel.tsx
  src/v2/__generated__/GalleriesRouteFragmentContainer_Test_Query.graphql.ts
  src/v2/__generated__/InstitutionsRouteFragmentContainer_Test_Query.graphql.ts
  src/v2/__generated__/PartnersFeaturedCarousel_Test_Query.graphql.ts
  src/v2/__generated__/PartnersFeaturedCarousel_viewer.graphql.ts
  src/v2/__generated__/partnersRoutes_GalleriesRouteQuery.graphql.ts
  src/v2/__generated__/partnersRoutes_InstitutionsRouteQuery.graphql.ts
Labels: Merge On Green

#8947 chore(deps): bumps palette
  package.json
  yarn.lock
Labels: Merge On Green

#8948 chore: deletes unnecessary specs
  src/desktop/components/inquiry_questionnaire/test/analytics.jest.ts
  src/desktop/components/inquiry_questionnaire/test/decisions.test.js
  src/desktop/components/inquiry_questionnaire/test/index.test.js
  src/desktop/components/inquiry_questionnaire/test/map.test.js
  src/desktop/components/inquiry_questionnaire/test/views/account.test.ts
  src/desktop/components/inquiry_questionnaire/test/views/affliated.test.js
  src/desktop/components/inquiry_questionnaire/test/views/basic_info.test.js
  src/desktop/components/inquiry_questionnaire/test/views/commercial_interest.test.js
  src/desktop/components/inquiry_questionnaire/test/views/inquiry.test.ts
  src/desktop/components/inquiry_questionnaire/test/views/institutional_affiliations.test.js
  src/desktop/components/inquiry_questionnaire/test/views/setup.ts
  src/desktop/components/inquiry_questionnaire/test/views/specialist.test.js
Labels: Merge On Green

#8937 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8941 feat(FX-3581): analytics tracking for create alert button
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/types.ts
  src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertForm.jest.tsx
Labels: Merge On Green, Jira Synced

#8959 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/addAssetToConsignmentMutation.graphql.ts
Labels: Merge On Green

#8962 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8887 feat(FX-3543): Add filters pills
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/FiltersPills.tsx
  src/v2/Components/ArtworkFilter/__tests__/FiltersPills.jest.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ArtistArtworkFilter_artist.graphql.ts
  src/v2/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
Labels: Jira Synced

#8955 Deploy
  data/schema.graphql
  package.json
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/types.ts
  src/v2/Components/SavedSearchAlert/CreateSavedSearchAlert.tsx
  src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertForm.jest.tsx
  src/v2/__generated__/addAssetToConsignmentMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#8965 chore(FX-3576): full width for "unsubscribe" button on small devices
  src/v2/Apps/Unsubscribe/Components/UnsubscribeLoggedIn.tsx
Labels: Merge On Green, Jira Synced

#8966 fix(partners): adds links to hero units
  src/v2/Apps/Partners/Components/PartnersFeaturedCarouselCell.tsx
  src/v2/Components/ArtworkFilter/__tests__/FiltersPills.jest.tsx
  src/v2/__generated__/GalleriesRouteFragmentContainer_Test_Query.graphql.ts
  src/v2/__generated__/InstitutionsRouteFragmentContainer_Test_Query.graphql.ts
  src/v2/__generated__/PartnersFeaturedCarouselCell_profile.graphql.ts
  src/v2/__generated__/PartnersFeaturedCarousel_Test_Query.graphql.ts
  src/v2/__generated__/partnersRoutes_GalleriesRouteQuery.graphql.ts
  src/v2/__generated__/partnersRoutes_InstitutionsRouteQuery.graphql.ts
Labels: Merge On Green

#8958 [PLATFORM-3744] Set artifacts for smoke-test-on-live-env in case of failure
  .circleci/config.yml
Labels: Jira Synced

#8792 feat(SWA-84): AutocompleteInput component from Palette instead Autosuggest
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutosuggest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
  src/v2/__generated__/ArtistAutocomplete_SearchConnection_Query.graphql.ts
Labels: Jira Synced

#8970 Deploy
  .circleci/config.yml
  package.json
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/SellWithArtsy.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SellWithArtsy.jest.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/__tests__/ConsignApp.jest.tsx
  src/v2/Apps/Order/Utils/__tests__/currencyUtils.jest.ts
  src/v2/Apps/Order/Utils/currencyUtils.ts
  src/v2/Apps/Settings/Routes/Saves/Components/SettingsSavesProfiles.tsx
  src/v2/Apps/Settings/Routes/Saves/Components/__tests__/SettingsSavesProfiles.jest.tsx
  src/v2/Apps/Settings/Routes/Saves/SettingsSavesRoute.tsx
  src/v2/Components/EntityHeaders/FairEntityHeader.tsx
  src/v2/Components/EntityHeaders/FairOrganizerEntityHeader.tsx
  src/v2/Components/EntityHeaders/PartnerEntityHeader.tsx
  src/v2/Components/EntityHeaders/PlaceholderEntityHeader.tsx
  src/v2/__generated__/FairEntityHeader_fair.graphql.ts
  src/v2/__generated__/FairOrganizerEntityHeader_fairOrganizer.graphql.ts
  src/v2/__generated__/PartnerEntityHeader_partner.graphql.ts
  src/v2/__generated__/SettingsSavesProfilesQuery.graphql.ts
  src/v2/__generated__/SettingsSavesProfiles_me.graphql.ts
  src/v2/jest.envSetup.ts
  yarn.lock
Labels: Jira Synced

#8975 Deploy
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutosuggest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
  src/v2/__generated__/ArtistAutocomplete_SearchConnection_Query.graphql.ts
Labels: Jira Synced
