Repository artsy/force, pull requests merged in 2021-04, with the labels that each got.

#7285 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7282 feature: Enable Gene Routes
  src/desktop/lib/webpackPublicPath.ts
  src/v2/routes.tsx
Labels: Merge On Green

#7286 feat: Break out Palette v3 Molecules into stories
  .storybook/main.js
  src/v2/Apps/Auctions/Components/__tests__/AuctionArtworksRail.jest.tsx
  src/v2/Apps/Auctions/Components/__tests__/AuctionArtworksRailArtworks.jest.tsx
  src/v2/Apps/Auctions/Components/__tests__/AuctionArtworksRailPlaceholder.jest.tsx
  src/v2/Apps/Auctions/Routes/__tests__/CurrentAuctions.jest.tsx
  src/v2/Apps/Auctions/Routes/__tests__/PastAuctions.jest.tsx
  src/v2/Components/__stories__/Carousels.story.tsx
  src/v2/Components/__stories__/Components/ContentHeaderExample.tsx
  src/v2/Components/__stories__/Components/ContentMetadataExample.tsx
  src/v2/Components/__stories__/Components/Page.tsx
  src/v2/Components/__stories__/Components/TombstoneExample.tsx
  src/v2/Components/__stories__/Content.story.tsx
  src/v2/Components/__stories__/Editorial.story.tsx
  src/v2/Components/__stories__/ExampleStory.story.tsx
  src/v2/Components/__stories__/Headers.story.tsx
  src/v2/Components/__stories__/Molecules.story.tsx
Labels: Merge On Green

#7288 fix: fixes build
  src/v2/Apps/Auctions/Components/__tests__/AuctionArtworksRail.jest.tsx
  src/v2/__generated__/AuctionArtworksRail_Test_Query.graphql.ts
  src/v2/__generated__/CurrentAuctions_Test_Query.graphql.ts
  src/v2/__generated__/PastAuctions_Test_Query.graphql.ts
Labels: Squash On Green

#7301 fix: Split getParams functions
  src/v2/Utils/getClientParam.tsx
  src/v2/Utils/getServerParam.tsx
  src/v2/client.tsx
  src/v2/server.ts
Labels: Merge On Green

#7302 feature: Client Modal Bundle
  src/v2/client.tsx
Labels: Merge On Green

#7306 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7307 fix: change materials filter title to material again
  src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MaterialsFilter.tsx
Labels: Merge On Green

#7310 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7312 fix: [Auctions2] QA round 2
  src/v2/Apps/Auctions/AuctionsApp.tsx
  src/v2/Apps/Auctions/Components/AuctionArtworksRail/AuctionArtworksRailArtworks.tsx
  src/v2/Apps/Auctions/Components/AuctionArtworksRail/__tests__/AuctionArtworksRail.jest.tsx
  src/v2/Apps/Auctions/Components/AuctionArtworksRail/__tests__/AuctionArtworksRailArtworks.jest.tsx
  src/v2/Apps/Auctions/Components/AuctionArtworksRailPlaceholder.tsx
  src/v2/Apps/Auctions/Components/MyBids/MyBidsBidItem.tsx
  src/v2/Apps/Auctions/Components/MyBids/__tests__/MyBids.jest.tsx
  src/v2/Apps/Auctions/Components/MyBids/__tests__/MyBidsBidHeader.jest.tsx
  src/v2/Apps/Auctions/Components/MyBids/__tests__/MyBidsBidItem.jest.tsx
  src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail/WorksByArtistsYouFollowRail.tsx
  src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail/__tests__/WorksByArtistsYouFollowRail.jest.tsx
  src/v2/Apps/Auctions/Utils/auctionsHelpers.tsx
  src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts
  src/v2/__generated__/MyBidsBidItem_Test_Query.graphql.ts
  src/v2/__generated__/MyBidsBidItem_saleArtwork.graphql.ts
  src/v2/__generated__/MyBidsQuery.graphql.ts
  src/v2/__generated__/MyBids_Test_Query.graphql.ts
  src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
Labels: Merge On Green

#7308 feat: Add articles pagination
  src/v2/Apps/Partner/Components/NavigationTabs/index.tsx
  src/v2/Apps/Partner/Components/PartnerArticles/helpers/articlesCard.ts
  src/v2/Apps/Partner/Routes/Articles/index.tsx
  src/v2/__generated__/ArticlesQuery.graphql.ts
  src/v2/__generated__/Articles_partner.graphql.ts
  src/v2/__generated__/partnerRoutes_ArticlesQuery.graphql.ts
Labels: Squash On Green

#7316 GRO-277: Update /auctions header layout
  src/v2/Apps/Auctions/AuctionsApp.tsx
Labels: Jira Synced

#7318 chore: Update auction registrations to v2
  src/desktop/apps/user/components/auction_registrations/query.coffee
  src/desktop/apps/user/components/auction_registrations/view.coffee
Labels: Jira Synced

#7328 fix: [Auctions2] - A little more minor QA
  src/v2/Apps/Auctions/AuctionsApp.tsx
  src/v2/Apps/Auctions/Components/MyBids/MyBids.tsx
  src/v2/Apps/Auctions/Components/MyBids/__tests__/MyBids.jest.tsx
  src/v2/Apps/Auctions/auctionsRoutes.tsx
  src/v2/__generated__/MyBidsQuery.graphql.ts
Labels: Merge On Green

#7340 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7338 fix: Add yarn relay to CI script
  .circleci/config.yml
Labels: Merge On Green

#7342 fix: [Auctions2] More spacing QA
  src/v2/Apps/Auctions/AuctionsApp.tsx
  src/v2/Apps/Auctions/auctionsRoutes.tsx
Labels: Merge On Green

#7348 feature: Add BidNow button for only reigstered sales
  src/v2/Apps/Auctions/Components/MyBids/MyBids.tsx
  src/v2/Apps/Auctions/Components/MyBids/__tests__/MyBids.jest.tsx
  src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts
  src/v2/__generated__/MyBids_Test_Query.graphql.ts
  src/v2/__generated__/MyBids_me.graphql.ts
  src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
Labels: Squash On Green

#7351 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7355 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7364 GRO-252 : Consolidate <Footer> into single location inside of <AppShell>
  src/v2/Apps/Artist/ArtistApp.tsx
  src/v2/Apps/ArtistSeries/ArtistSeriesApp.tsx
  src/v2/Apps/Artists/ArtistsApp.tsx
  src/v2/Apps/Artwork/ArtworkApp.tsx
  src/v2/Apps/Auctions/AuctionsApp.tsx
  src/v2/Apps/Components/AppShell.tsx
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/Apps/Fair/FairSubApp.tsx
  src/v2/Apps/Fairs/FairsApp.tsx
  src/v2/Apps/Feature/FeatureApp.tsx
  src/v2/Apps/Gene/GeneApp.tsx
  src/v2/Apps/Partner/PartnerApp.tsx
  src/v2/Apps/Search/SearchApp.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/ShowSubApp.tsx
  src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/v2/Apps/ViewingRoom/ViewingRoomsApp.tsx
  src/v2/Components/FrameWithRecentlyViewed.tsx
Labels: Jira Synced

#7363 First pass for braze sdk integration
  package.json
  src/desktop/config.coffee
  src/lib/braze.ts
  src/lib/setup_sharify.js
  src/typings/sharify.d.ts
  src/v2/client.tsx
  yarn.lock
Labels: Merge On Green

#7373 feat(pagination): supports v3
  package.json
  src/v2/Apps/Artist/Routes/Articles/__tests__/Articles.jest.tsx
  src/v2/Apps/Artist/Routes/Shows/__tests__/Shows.jest.tsx
  src/v2/Components/Pagination/index.tsx
  src/v2/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
  yarn.lock
Labels: Merge On Green

#7378 Fix: Add guard for when sale_artwork is null to avoid crash
  src/v2/Components/Artwork/Details.tsx
Labels: Merge On Green

#7379 fix: restore proper refetching behavior on fair artworks grid
  src/v2/Apps/Fair/Routes/FairArtworks.tsx
  src/v2/__generated__/WorksQuery.graphql.ts
  src/v2/__generated__/partnerRoutes_WorksQuery.graphql.ts
Labels: Merge On Green

#7383 fix(PX-3984): add background for the footer
  src/v2/Apps/Components/AppShell.tsx
Labels: Merge On Green

#7385 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7391 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7392 feat(gene): adds formatted description
  src/v2/Apps/Gene/Routes/GeneShow.tsx
  src/v2/__generated__/GeneShow_Test_Query.graphql.ts
  src/v2/__generated__/GeneShow_gene.graphql.ts
  src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts
Labels: Squash On Green

#7394 Fix: Correct logic causing braze to fail to initialize on the client
  src/lib/braze.ts
Labels: Squash On Green

#7395 feat: show card implementation
  src/v2/Apps/Partner/Components/PartnerShows/ShowCard.tsx
  src/v2/Apps/Partner/Components/__tests__/PartnerShows/ShowCard.jest.tsx
  src/v2/Apps/Partner/Routes/Shows/index.tsx
  src/v2/Apps/Partner/partnerRoutes.tsx
  src/v2/__generated__/ShowCard_Test_Query.graphql.ts
  src/v2/__generated__/ShowCard_show.graphql.ts
  src/v2/__generated__/Shows_partner.graphql.ts
  src/v2/__generated__/partnerRoutes_ShowsQuery.graphql.ts
Labels: Squash On Green

#7397 Fix: Call openSession to register a user's braze session
  src/lib/braze.ts
Labels: Squash On Green

#7398 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7400 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7402 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7404 GRO-278: Add Artsy Curated Auction consignments agreement to front end.
  src/v2/Components/Footer.tsx
Labels: Jira Synced

#7393 GRO-228: Updated Copy Text for ToS and Subscription checkboxes
  src/v2/Components/Authentication/EmailSubscriptionCheckbox.tsx
  src/v2/Components/Authentication/TermsOfServiceCheckbox.tsx
  src/v2/Components/Authentication/__tests__/Desktop/SignUpForm.jest.tsx
Labels: Jira Synced

#7409 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/FollowGeneButtonMutation.graphql.ts
  src/v2/__generated__/GeneSearchResultsFollowGeneMutation.graphql.ts
  src/v2/__generated__/SuggestedGenesFollowGeneMutation.graphql.ts
Labels: Merge On Green

#7410 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7412 feature: Support unfollows in follow gene button
  src/v2/Components/FollowButton/FollowGeneButton.tsx
  src/v2/Components/FollowButton/__tests__/FollowGeneButton.jest.tsx
Labels: Jira Synced

#7405 fix: spacing issue in BNMO messaging
  src/v2/Apps/Order/Routes/Status/index.tsx
Labels: Merge On Green

#7420 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistShowsQuery.graphql.ts
  src/v2/__generated__/CVItemQuery.graphql.ts
Labels: Merge On Green

#7279 fix: bring back ask a question modal to BNMO checkout flow
  src/v2/Apps/Order/OrderApp.tsx
  src/v2/Apps/Order/__tests__/OrderApp.jest.tsx
Labels: Jira Synced

#7425 feat: Sync filter state with url params on gene page
  src/v2/Apps/Gene/Components/GeneArtworkFilter.tsx
  src/v2/Apps/Gene/geneRoutes.tsx
Labels: Jira Synced

#7428 fix(gene): uses hrefs on gene page
  src/v2/Apps/Gene/Routes/GeneShow.tsx
  src/v2/__generated__/GeneShow_Test_Query.graphql.ts
  src/v2/__generated__/GeneShow_gene.graphql.ts
  src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts
Labels: Squash On Green

#7436 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7439 feature: Optimize Fillwidthitem Image for Mobile
  src/v2/Components/Artwork/FillwidthItem.tsx
  src/v2/Utils/resized.ts
  src/v2/__generated__/ArtistRecommendationsPaginationQuery.graphql.ts
  src/v2/__generated__/ArtistRecommendationsRendererQuery.graphql.ts
  src/v2/__generated__/ArtistRecommendations_Test_Query.graphql.ts
  src/v2/__generated__/ArtistsQuery.graphql.ts
  src/v2/__generated__/ArtworkArtistSeries_Query.graphql.ts
  src/v2/__generated__/AuctionArtworksRailArtworksQuery.graphql.ts
  src/v2/__generated__/AuctionArtworksRailArtworks_Test_Query.graphql.ts
  src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts
  src/v2/__generated__/ConsignRoute_Test_Query.graphql.ts
  src/v2/__generated__/FairApp_Test_Query.graphql.ts
  src/v2/__generated__/FairExhibitorRailArtworksQuery.graphql.ts
  src/v2/__generated__/FillwidthItem_artwork.graphql.ts
  src/v2/__generated__/GeneContentsArtistsQuery.graphql.ts
  src/v2/__generated__/OverviewRoute_Test_Query.graphql.ts
  src/v2/__generated__/PartnerArtistDetailsListQuery.graphql.ts
  src/v2/__generated__/PartnerArtistDetailsListRendererQuery.graphql.ts
  src/v2/__generated__/PartnerArtistDetailsQuery.graphql.ts
  src/v2/__generated__/RecentlyViewedQuery.graphql.ts
  src/v2/__generated__/RecentlyViewed_me.graphql.ts
  src/v2/__generated__/SoldRecentlyQuery.graphql.ts
  src/v2/__generated__/SoldRecently_tests_Query.graphql.ts
  src/v2/__generated__/WorksByArtistsYouFollowRail_Test_Query.graphql.ts
  src/v2/__generated__/WorksForSaleRailRendererQuery.graphql.ts
  src/v2/__generated__/WorksForSaleRail_Test_Query.graphql.ts
  src/v2/__generated__/Works_Test_Query.graphql.ts
  src/v2/__generated__/artistRoutes_ArtistConsignQuery.graphql.ts
  src/v2/__generated__/artistRoutes_OverviewQuery.graphql.ts
  src/v2/__generated__/artistRoutes_WorksQuery.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairQuery.graphql.ts
Labels: Squash On Green
