Repository artsy/force, pull requests merged in 2021-07, with the labels that each got.

#7914 fix(GRO-398): fixes header variant
  src/v2/Apps/Home/Components/HomeArtworkModuleContext.tsx
Labels: Squash On Green

#7913 feat(GRO-403): fleshes out meta tags
  src/desktop/components/fair_week_marketing/__tests__/BannerPopUp.jest.tsx
  src/v2/Apps/ArtistSeries/Components/ArtistSeriesMeta.tsx
  src/v2/Apps/BuyerGuarantee/Components/BuyerGuaranteeMeta.tsx
  src/v2/Apps/Fairs/Components/FairsPhonePromo.tsx
  src/v2/Apps/FeatureAKG/__tests__/FeatureAKGRoute.jest.tsx
  src/v2/Apps/Gene/Components/GeneMeta.tsx
  src/v2/Apps/Gene/Routes/__tests__/GeneShow.jest.tsx
  src/v2/Apps/Home/Components/HomeMeta.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Components/MetaTags.tsx
  src/v2/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.jest.tsx
  src/v2/Components/__tests__/MetaTags.jest.tsx
Labels: Squash On Green

#7916 feat(PX-4293): rename Shows tab to Events
  src/v2/Apps/Partner/Components/NavigationTabs/index.tsx
  src/v2/Apps/Partner/Components/__tests__/NavigationTabs.jest.tsx
Labels: Squash On Green

#7924 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7933 feat(home): adds credit line to desktop heroes
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
Labels: Squash On Green

#7935 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7930 Fix for edition set error when artwork has been deleted
  src/v2/Apps/Conversation/Components/ConfirmArtworkModal.tsx
Labels: Jira Synced

#7937 chore(sailthru): removes sailthru
  package.json
  src/desktop/apps/article/templates/classic_meta.jade
  src/desktop/apps/articles/components/AuthWrapper.tsx
  src/desktop/apps/articles/components/__tests__/AuthWrapper.jest.tsx
  src/desktop/apps/articles/test/routes.test.js
  src/desktop/apps/editorial_features/components/eoy/templates/head.jade
  src/desktop/apps/editorial_features/components/gucci/templates/__tests__/head.test.js
  src/desktop/apps/editorial_features/components/gucci/templates/head.jade
  src/desktop/apps/editorial_features/components/venice_2017/templates/head.jade
  src/desktop/apps/editorial_features/routes.coffee
  src/desktop/apps/editorial_features/test/routes.test.js
  src/desktop/components/fair_layout/templates/head.jade
  src/desktop/components/main_layout/templates/blank.jade
  src/desktop/components/main_layout/templates/index.jade
  src/desktop/components/main_layout/templates/minimal_header.jade
  src/desktop/components/main_layout/templates/redesign.jade
  src/desktop/components/main_layout/templates/scripts.jade
  src/desktop/config.coffee
  src/lib/analytics/helpers.ts
  src/lib/setup_sharify.js
  src/mobile/apps/articles/index.coffee
  src/mobile/apps/articles/routes.coffee
  src/mobile/apps/articles/test/routes.test.js
  src/mobile/components/layout/templates/scaffold.jade
  src/mobile/config.coffee
  src/typings/global.d.ts
  src/v2/Apps/Artwork/Components/ArtworkMeta.tsx
  src/v2/index.ejs
  src/v2/server.ts
  yarn.lock
Labels: Squash On Green

#7938 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7940 fix(home): utilizes featured flag for articles
  src/v2/Apps/Home/Components/HomeFeaturedArticles.tsx
  src/v2/__generated__/HomeFeaturedArticlesQuery.graphql.ts
Labels: Squash On Green

#6956 feat(shows): roughs in shows2
  cypress/integration/shows.spec.ts
  src/v2/Apps/Shows/Components/ShowsFeaturedShow.tsx
  src/v2/Apps/Shows/Components/ShowsHeader.tsx
  src/v2/Apps/Shows/Components/ShowsMeta.tsx
  src/v2/Apps/Shows/Components/ShowsShowDates.tsx
  src/v2/Apps/Shows/Routes/ShowsCity.tsx
  src/v2/Apps/Shows/Routes/ShowsIndex.tsx
  src/v2/Apps/Shows/Routes/__tests__/ShowsCity.jest.tsx
  src/v2/Apps/Shows/Routes/__tests__/ShowsIndex.jest.tsx
  src/v2/Apps/Shows/ShowsApp.tsx
  src/v2/Apps/Shows/showsRoutes.tsx
  src/v2/__generated__/ShowsCity_Test_Query.graphql.ts
  src/v2/__generated__/ShowsCity_city.graphql.ts
  src/v2/__generated__/ShowsCity_viewer.graphql.ts
  src/v2/__generated__/ShowsFeaturedShow_show.graphql.ts
  src/v2/__generated__/ShowsHeader_viewer.graphql.ts
  src/v2/__generated__/ShowsIndex_Test_Query.graphql.ts
  src/v2/__generated__/ShowsIndex_featuredShows.graphql.ts
  src/v2/__generated__/ShowsIndex_viewer.graphql.ts
  src/v2/__generated__/ShowsShowDates_show.graphql.ts
  src/v2/__generated__/showsRoutes_ShowsCityQuery.graphql.ts
  src/v2/__generated__/showsRoutes_ShowsIndexQuery.graphql.ts
  src/v2/routes.tsx
Labels: Squash On Green

#7941 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7942 fix(artist): makes artist articles clickable
  src/v2/Apps/Artist/Routes/Articles/ArtistArticlesRoute.tsx
  src/v2/__generated__/ArtistArticlesRouteQuery.graphql.ts
  src/v2/__generated__/ArtistArticlesRoute_Test_Query.graphql.ts
  src/v2/__generated__/ArtistArticlesRoute_artist.graphql.ts
  src/v2/__generated__/artistRoutes_ArticlesQuery.graphql.ts
Labels: Squash On Green

#7943 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7925 feat: fetch bid data for auction artworks on mWeb
  src/desktop/apps/auction/components/artwork_browser/__tests__/fixtures/followedArtistSaleArtworks.js
  src/desktop/apps/auction/components/artwork_browser/main/artwork/BidStatus.js
  src/desktop/apps/auction/queries/worksByFollowedArtists.js
Labels: Jira Synced

#7951 chore: bump Cohesion to 2.9.0
  cypress/integration/partnerProfile.spec.js
  package.json
  yarn.lock
Labels: Squash On Green

#7945 feat: User can keyword filter within artist auction results
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionResultsControls.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/KeywordFilter.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/SortSelect.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/v2/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/v2/__generated__/ArtistAuctionResults_artist.graphql.ts
Labels: Jira Synced, Squash On Green

#7954 chore(home): addresses homepage q/a items
  src/v2/Apps/Home/Components/HomeArtworkModuleContext.tsx
  src/v2/Apps/Home/Components/HomeFeaturedArticles.tsx
  src/v2/Apps/Home/Components/HomeFeaturedCategoriesRail.tsx
  src/v2/Apps/Home/Components/HomeFeaturedShow.tsx
  src/v2/Apps/Home/Components/HomeFeaturedShows.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitCredit.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitLoggedOut.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitsLarge.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitsSmall.tsx
  src/v2/Apps/Home/Components/HomeMeta.tsx
  src/v2/Apps/Home/__tests__/HomeApp.jest.tsx
  src/v2/Apps/Home/__tests__/HomeArtworkModuleContext.jest.tsx
  src/v2/Apps/Home/__tests__/HomeFeaturedArticles.jest.tsx
  src/v2/Apps/Home/__tests__/HomeFeaturedShows.jest.tsx
  src/v2/Components/MetaTags.tsx
  src/v2/Components/__tests__/MetaTags.jest.tsx
  src/v2/__generated__/HomeFeaturedArticlesQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedArticles_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedArticles_articles.graphql.ts
  src/v2/__generated__/HomeFeaturedShow_show.graphql.ts
  src/v2/__generated__/HomeFeaturedShowsQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedShows_Test_Query.graphql.ts
Labels: Squash On Green

#7959 feat(FX-3062): fair artworks alignment
  src/v2/Apps/Fair/Routes/FairArtworks.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/FilterExpandable.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PartnersFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/FilterExpandable.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/PartnersFilter.jest.tsx
Labels: Jira Synced

#7950 chore(shows2): roughs in current shows
  src/v2/Apps/Artists/Components/ArtistsArtistCard.tsx
  src/v2/Apps/Artists/Components/ArtistsCarouselCell.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarPartnerInfo.jest.tsx
  src/v2/Apps/Auctions/Components/AuctionArtworksRail/AuctionArtworksRail.tsx
  src/v2/Apps/Fair/Components/FairExhibitorRail/FairExhibitorRail.tsx
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/Apps/Fairs/Components/FairsFairBanner.tsx
  src/v2/Apps/Feature/Components/FeatureFeaturedLink.tsx
  src/v2/Apps/FeatureAKG/Components/FeaturedArticles.tsx
  src/v2/Apps/Partner/Components/PartnerArticles/ArticleCard.tsx
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetails.tsx
  src/v2/Apps/Partner/Components/PartnerShows/ShowBanner.tsx
  src/v2/Apps/Partner/Components/PartnerShows/ShowCard.tsx
  src/v2/Apps/Show/ShowSubApp.tsx
  src/v2/Apps/Shows/Components/ShowsCurrentShow.tsx
  src/v2/Apps/Shows/Components/ShowsCurrentShows.tsx
  src/v2/Apps/Shows/Components/ShowsHeader.tsx
  src/v2/Apps/Shows/Components/ShowsMeta.tsx
  src/v2/Apps/Shows/Routes/ShowsIndex.tsx
  src/v2/Apps/ViewingRoom/Components/ViewingRoomTabBar.tsx
  src/v2/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
  src/v2/Components/Artwork/FillwidthItem.tsx
  src/v2/Components/Artwork/GridItem.tsx
  src/v2/Components/Artwork/Metadata.tsx
  src/v2/Components/NavBar/NavBarPrimaryLogo.tsx
  src/v2/Components/__tests__/__snapshots__/Artwork.jest.tsx.snap
  src/v2/System/Router/RouterLink.tsx
  src/v2/System/Router/__tests__/RouterLink.jest.tsx
  src/v2/__generated__/ShowsCurrentShow_show.graphql.ts
  src/v2/__generated__/ShowsCurrentShowsQuery.graphql.ts
  src/v2/__generated__/ShowsCurrentShows_viewer.graphql.ts
Labels: Squash On Green

#7970 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7947 fix(FX-2806): refactor auction results filters
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/ArtistAuctionResultsCount.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilterMobileActionSheet.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/MediumFilter.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/SizeFilter.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/KeywordFilter.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/Components/SortSelect.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.jest.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/SizeFilter.jest.tsx
Labels: Jira Synced

#7978 feat(home): adds flash banner to homepage
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Components/FlashBanner/EmailConfirmationCTA.tsx
  src/v2/Components/FlashBanner/EmailConfirmationLinkExpired.tsx
  src/v2/Components/FlashBanner/__tests__/FlashBanner.jest.tsx
  src/v2/Components/FlashBanner/index.tsx
Labels: Squash On Green

#7869 feat(PX-4135): Collector can set an address as default
  src/v2/Apps/Order/Components/AddressModal.tsx
  src/v2/Apps/Order/Components/SavedAddressItem.tsx
  src/v2/Apps/Order/Components/__tests__/AddressModal.jest.tsx
  src/v2/Apps/Order/Mutations/UpdateUserAddress.ts
Labels: Jira Synced

#7981 chore(show): adds scrollbar; minor clean up
  src/v2/Apps/Show/Components/ShowContextCard.tsx
  src/v2/Apps/Show/Components/ShowInstallShots.tsx
  src/v2/Apps/Show/ShowApp.tsx
Labels: Merge On Green

#7976 fix: fetch follow artists
  src/v2/Components/ArtworkFilter/Utils/fetchFollowedArtists.ts
  src/v2/__generated__/fetchFollowedArtistsByFairIdQuery.graphql.ts
  src/v2/__generated__/fetchFollowedArtistsRawQuery.graphql.ts
  src/v2/__generated__/fetchFollowedArtists_response.graphql.ts
Labels: Jira Synced

#7986 fix: fixes watch lot button
  src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
Labels: Squash On Green

#7979 Deploy
  src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
  src/v2/Apps/Home/Components/HomeArtworkModuleRail.tsx
  src/v2/Apps/Home/Components/HomeArtworkModules.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Apps/Order/Components/AddressModal.tsx
  src/v2/Apps/Order/Components/SavedAddressItem.tsx
  src/v2/Apps/Order/Components/__tests__/AddressModal.jest.tsx
  src/v2/Apps/Order/Mutations/UpdateUserAddress.ts
  src/v2/Apps/Order/Routes/Review/index.tsx
  src/v2/Apps/Show/Components/ShowContextCard.tsx
  src/v2/Apps/Show/Components/ShowInstallShots.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Components/ArtworkFilter/Utils/fetchFollowedArtists.ts
  src/v2/Components/FlashBanner/EmailConfirmationCTA.tsx
  src/v2/Components/FlashBanner/EmailConfirmationLinkExpired.tsx
  src/v2/Components/FlashBanner/__tests__/FlashBanner.jest.tsx
  src/v2/Components/FlashBanner/index.tsx
  src/v2/__generated__/fetchFollowedArtistsByFairIdQuery.graphql.ts
  src/v2/__generated__/fetchFollowedArtistsRawQuery.graphql.ts
  src/v2/__generated__/fetchFollowedArtists_response.graphql.ts
Labels: Jira Synced

#7987 fix(details): fixes artist name with multiple artists
  src/v2/Components/Artwork/Details.tsx
Labels: Squash On Green

#7908 alexj105: feat offer status in conversation [PURCHASE-2704] [PURCHASE-2795]
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/ConversationMessages.tsx
  src/v2/Apps/Conversation/Components/ConversationSnippet.tsx
  src/v2/Apps/Conversation/Components/Message.tsx
  src/v2/Apps/Conversation/Components/OrderUpdate.tsx
  src/v2/Apps/Conversation/Components/TimeSince.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConversationMessages.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/OrderUpdate.jest.tsx
  src/v2/Apps/Conversation/Utils/groupMessages.tsx
  src/v2/__generated__/ConversationMessages_events.graphql.ts
  src/v2/__generated__/ConversationMessages_messages.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/Message_message.graphql.ts
  src/v2/__generated__/OrderUpdate_Test_Query.graphql.ts
  src/v2/__generated__/OrderUpdate_event.graphql.ts
  src/v2/__generated__/SendConversationMessageMutation.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Jira Synced

#7990 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#7964 fix[PURCHASE-2793]: remove unwanted warning on redirect from the orders page
  src/v2/Apps/Order/OrderApp.tsx
Labels: Squash On Green

#7995 fix(nav): prevents hamburger click from reloading the page
  src/v2/Components/NavBar/NavBar.tsx
Labels: Squash On Green

#7977 sentry: Add `Illegal Invocation` to list
  src/lib/analytics/sentryFilters.ts
Labels: Squash On Green

#7997 fix(show): improves install shots display
  src/v2/Apps/Show/Components/ShowInstallShots.tsx
Labels: Squash On Green

#7982 FX-3066 feat: Auction House filter is not expanded by default
  src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
Labels: Jira Synced

#7992 feat(FX-2789): filter facet names title
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistNationalityFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtworkLocationFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PartnersFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ResultsFilter.jest.tsx
Labels: Jira Synced

#7972 feat(FX-3049): nav bar update
  src/v2/Components/NavBar/Menus/DropDownMenu/__tests__/DropDownMenu.jest.tsx
  src/v2/Components/NavBar/menuData.ts
Labels: Jira Synced, Squash On Green

#8003 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8004 fix: fixes overflowing artwork grid in firefox
  src/v2/Components/ArtworkFilter/index.tsx
Labels: Squash On Green

#8007 moved timestamp to above order update and fixed mo button styling
  src/v2/Apps/Conversation/Components/OpenInquiryModalButton.tsx
  src/v2/Apps/Conversation/Components/OrderUpdate.tsx
  src/v2/Apps/Conversation/Components/Reply.tsx
Labels: Jira Synced, Squash On Green

#7944 Bugfix: fix refetching on scroll in conversation list
  src/v2/Apps/Conversation/Components/ConversationList.tsx
Labels: Jira Synced

#7893 feat: Sorting of exhibitors on the fair page
  src/v2/Apps/Fair/Components/ExhibitorFilterContext.tsx
  src/v2/Apps/Fair/Components/FairExhibitorSortFilter.tsx
  src/v2/Apps/Fair/Components/__tests__/ExhibitorFilterContext.jest.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Apps/Fair/Routes/FairExhibitorsQuery.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx
  src/v2/Apps/Fair/Utils/IsValidSort.ts
  src/v2/Apps/Fair/Utils/__tests__/IsValidSort.jest.ts
  src/v2/Apps/Fair/fairRoutes.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtworkSortFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/SortFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ArtworkSortFilter.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/Components/SortFilter.tsx
  src/v2/Components/__tests__/SortFilter.jest.tsx
  src/v2/__generated__/FairExhibitorsQuery.graphql.ts
  src/v2/__generated__/FairExhibitors_Query.graphql.ts
  src/v2/__generated__/FairExhibitors_fair.graphql.ts
  src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
Labels: Jira Synced

#8011 feat(FX-3079): rename exhibitors tab to booths
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
Labels: Jira Synced

#8013 feat(FX-3064): base filter alignment + artist series
  src/test/fixtures/aggregations.ts
  src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesArtworksFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/index.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/__generated__/ArtistSeriesArtworksFilter_Query.graphql.ts
Labels: Jira Synced

#8014 feat(FX-3070): gene filter alignment
  src/v2/Apps/Gene/Components/GeneArtworkFilter.tsx
  src/v2/Apps/Gene/Components/__tests__/GeneArtworkFilter.jest.tsx
  src/v2/Apps/Gene/geneRoutes.tsx
  src/v2/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/v2/__generated__/GeneArtworkFilter_Query.graphql.ts
  src/v2/__generated__/GeneArtworkFilter_gene.graphql.ts
  src/v2/__generated__/GeneShow_Test_Query.graphql.ts
  src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts
Labels: Jira Synced

#8017 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8018 feat(FX-3084, FX-3060): update filters order for gallery works
  src/v2/Apps/Show/Components/ShowArtworks.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/__tests__/ShowArtworks.jest.tsx
  src/v2/Apps/Show/showRoutes.tsx
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
Labels: Jira Synced

#8020 Deploy
  data/schema.graphql
  src/v2/Apps/Partner/Components/Overview/SubscriberBanner.tsx
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistsCarousel/PartnerArtistsCarousel.tsx
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistsCarousel/PartnerArtistsCarouselItem.tsx
  src/v2/Apps/Show/Components/ShowArtworks.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/__tests__/ShowArtworks.jest.tsx
  src/v2/Apps/Show/showRoutes.tsx
  src/v2/__generated__/PartnerArtistsCarouselItem_artist.graphql.ts
  src/v2/__generated__/PartnerArtistsCarouselRendererQuery.graphql.ts
  src/v2/__generated__/PartnerArtistsCarousel_partner.graphql.ts
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
Labels: Jira Synced

#8025 Revert "Revert "feat: Sorting of exhibitors on the fair page""
  src/v2/Apps/Fair/Components/ExhibitorFilterContext.tsx
  src/v2/Apps/Fair/Components/FairExhibitorSortFilter.tsx
  src/v2/Apps/Fair/Components/__tests__/ExhibitorFilterContext.jest.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Apps/Fair/Routes/FairExhibitorsQuery.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx
  src/v2/Apps/Fair/Utils/IsValidSort.ts
  src/v2/Apps/Fair/Utils/__tests__/IsValidSort.jest.ts
  src/v2/Apps/Fair/fairRoutes.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtworkSortFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/SortFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ArtworkSortFilter.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/Components/SortFilter.tsx
  src/v2/Components/__tests__/SortFilter.jest.tsx
  src/v2/__generated__/FairExhibitorsQuery.graphql.ts
  src/v2/__generated__/FairExhibitors_Query.graphql.ts
  src/v2/__generated__/FairExhibitors_fair.graphql.ts
  src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
Labels: Jira Synced

#8029 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8037 FX-3071 feat: Added pagination to fair booths page
  src/v2/Apps/Fair/Components/ExhibitorFilterContext.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Apps/Fair/Routes/FairExhibitorsQuery.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx
  src/v2/Apps/Fair/fairRoutes.tsx
  src/v2/__generated__/FairExhibitorsQuery.graphql.ts
  src/v2/__generated__/FairExhibitors_Query.graphql.ts
  src/v2/__generated__/FairExhibitors_fair.graphql.ts
  src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
Labels: Jira Synced

#8021 feat(FX-3090, FX-3065): update filters order for collection
  src/v2/Apps/Collect/Routes/Collection/CollectionAppQuery.tsx
  src/v2/Apps/Collect/Routes/Collection/index.tsx
  src/v2/Apps/Collect/collectRoutes.tsx
  src/v2/__generated__/CollectionQuery.graphql.ts
  src/v2/__generated__/Collection_collection.graphql.ts
  src/v2/__generated__/collectRoutes_CollectionQuery.graphql.ts
Labels: Jira Synced

#8023 feat(FX-3069, FX-3086): search results filter alignment
  src/v2/Apps/Search/Routes/Artworks/index.tsx
  src/v2/Apps/Search/Routes/SearchResultsArtworks.tsx
  src/v2/Apps/Search/Routes/__tests__/SearchResultsArtworks.jest.tsx
  src/v2/Apps/Search/searchRoutes.tsx
  src/v2/__generated__/SearchResultsArtworks_Query.graphql.ts
  src/v2/__generated__/SearchResultsArtworks_viewer.graphql.ts
  src/v2/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
Labels: Jira Synced

#8045 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8041 Deploy
  data/schema.graphql
  src/v2/Apps/Order/Routes/Shipping/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/v2/Apps/Order/Utils/shippingUtils.ts
  src/v2/Apps/Search/Routes/Artworks/index.tsx
  src/v2/Apps/Search/Routes/SearchResultsArtworks.tsx
  src/v2/Apps/Search/Routes/__tests__/SearchResultsArtworks.jest.tsx
  src/v2/Apps/Search/searchRoutes.tsx
  src/v2/System/Relay/createRelaySSREnvironment.ts
  src/v2/__generated__/SearchResultsArtworks_Query.graphql.ts
  src/v2/__generated__/SearchResultsArtworks_viewer.graphql.ts
  src/v2/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
Labels: Jira Synced

#8051 fix: type errors
  package.json
  src/v2/Apps/Conversation/Components/CollapsibleArtworkDetails.tsx
  yarn.lock
Labels: Merge On Green

#8049 Deploy
  package.json
  src/v2/Apps/Conversation/Components/CollapsibleArtworkDetails.tsx
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Order/Components/ShippingAddress.tsx
  src/v2/Apps/Order/Components/ShippingArtaSummaryItem.tsx
  src/v2/Apps/Order/Components/ShippingSummaryItem.tsx
  src/v2/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/v2/Apps/Order/Components/__tests__/TransactionDetailsSummary.jest.tsx
  src/v2/Apps/Order/Mutations/SelectShippingOption.ts
  src/v2/Apps/Order/Routes/Review/index.tsx
  src/v2/Apps/Order/Routes/__fixtures__/MutationResults/setOrderShipping.ts
  src/v2/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx
  src/v2/Apps/Order/__tests__/OrderApp.jest.tsx
  src/v2/Apps/Order/redirects.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/__generated__/AcceptTestQuery.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/CounterTestQuery.graphql.ts
  src/v2/__generated__/NewPaymentTestQuery.graphql.ts
  src/v2/__generated__/OfferTestQuery.graphql.ts
  src/v2/__generated__/PaymentTestQuery.graphql.ts
  src/v2/__generated__/RespondCounterOfferMutation.graphql.ts
  src/v2/__generated__/RespondTestQuery.graphql.ts
  src/v2/__generated__/ReviewTestQuery.graphql.ts
  src/v2/__generated__/Review_order.graphql.ts
  src/v2/__generated__/SelectShippingOptionMutation.graphql.ts
  src/v2/__generated__/ShippingAddress_ship.graphql.ts
  src/v2/__generated__/ShippingArtaSummaryItem_order.graphql.ts
  src/v2/__generated__/ShippingTestQuery.graphql.ts
  src/v2/__generated__/StatusQuery.graphql.ts
  src/v2/__generated__/TransactionDetailsSummaryItemTestQuery.graphql.ts
  src/v2/__generated__/TransactionDetailsSummaryItem_order.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
  src/v2/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/v2/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/v2/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/v2/__generated__/orderRoutes_OrderQuery.graphql.ts
  src/v2/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/v2/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/v2/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/v2/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/v2/__generated__/orderRoutes_StatusQuery.graphql.ts
  src/v2/__generated__/redirects_order.graphql.ts
  yarn.lock
Labels: Jira Synced

#8005 fix: collection filter disappear
  src/v2/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx
  src/v2/Apps/Collect/Routes/Collection/Components/__tests__/CollectionArtworksFilter.jest.tsx
  src/v2/Apps/Collect/Routes/Collection/index.tsx
  src/v2/Apps/Collect/collectRoutes.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/v2/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/v2/__generated__/CollectionArtworksFilter_collection.graphql.ts
  src/v2/__generated__/CollectionQuery.graphql.ts
  src/v2/__generated__/Collection_collection.graphql.ts
  src/v2/__generated__/collectRoutes_CollectionQuery.graphql.ts
Labels: Jira Synced

#8026 feat(FX-3068, FX-3085): collect filter alignment
  src/v2/Apps/Collect/Routes/Collect/index.tsx
  src/v2/Apps/Collect/collectRoutes.tsx
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
Labels: Jira Synced

#8031 feat: (PLATFORM-3135) turn-key dev env
  .env.example
  .env.oss
  .gitignore
  CONTRIBUTING.md
  docs/adding_an_env_var.md
  docs/env_configuration.md
  hokusai/development.yml
  package.json
  packages/publish/uploadToS3.js
  scripts/setup.sh
  scripts/smoke_test.sh
  scripts/start.sh
  src/desktop/config.coffee
  src/dev.js
  src/index.js
  src/lib/setup_sharify.js
  src/loadenv.js
  yarn.lock
Labels: Squash On Green

#8052 Deploy
  .env.example
  .env.oss
  .gitignore
  CONTRIBUTING.md
  docs/adding_an_env_var.md
  docs/env_configuration.md
  hokusai/development.yml
  package.json
  packages/publish/uploadToS3.js
  scripts/setup.sh
  scripts/smoke_test.sh
  scripts/start.sh
  src/desktop/config.coffee
  src/dev.js
  src/index.js
  src/lib/setup_sharify.js
  src/loadenv.js
  src/v2/Apps/Artwork/ArtworkApp.tsx
  src/v2/Apps/Auctions/AuctionsApp.tsx
  src/v2/Apps/Auctions/Components/CuratorialRailsZeroState/CuratorialRailsZeroState.tsx
  src/v2/Apps/Auctions/Components/StandoutLots/StandoutLots.tsx
  src/v2/Apps/Auctions/Components/StandoutLots/__tests__/StandoutLots.jest.tsx
  src/v2/Apps/Auctions/Components/TrendingLots/TrendingLots.tsx
  src/v2/Apps/Auctions/Components/TrendingLots/__tests__/TrendingLots.jest.tsx
  src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail/WorksByArtistsYouFollowRail.tsx
  src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail/__tests__/WorksByArtistsYouFollowRail.jest.tsx
  src/v2/Apps/Auctions/__tests__/AuctionsApp.jest.tsx
  src/v2/Apps/Collect/Routes/Collect/index.tsx
  src/v2/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx
  src/v2/Apps/Collect/Routes/Collection/Components/__tests__/CollectionArtworksFilter.jest.tsx
  src/v2/Apps/Collect/Routes/Collection/index.tsx
  src/v2/Apps/Collect/collectRoutes.tsx
  src/v2/Apps/Order/Components/AddressModal.tsx
  src/v2/Apps/Order/Components/SavedAddresses.tsx
  src/v2/Apps/Order/Components/__tests__/SavedAddresses.jest.tsx
  src/v2/Apps/Order/Mutations/UpdateUserAddress.ts
  src/v2/Apps/Order/OrderApp.tsx
  src/v2/Apps/Order/Routes/Shipping/index.tsx
  src/v2/Apps/Order/Routes/__fixtures__/MutationResults/saveAddress.ts
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/v2/Apps/Order/Utils/shippingUtils.ts
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/Utils/LegacyArtworkDllContainer.tsx
  src/v2/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/v2/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/v2/__generated__/CollectionArtworksFilter_collection.graphql.ts
  src/v2/__generated__/CollectionQuery.graphql.ts
  src/v2/__generated__/Collection_collection.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/collectRoutes_CollectionQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#8070 fix: do not require config for createRelaySSREnvironment
  src/v2/System/Relay/createRelaySSREnvironment.ts
Labels: Merge On Green

#8073 FX-3129 feat: Added /fair-organizer/:slug route
  cypress/integration/fairOrganizer.spec.ts
  src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx
  src/v2/Apps/FairOrginizer/fairOrganizerRoutes.tsx
  src/v2/routes.tsx
Labels: Jira Synced

#8075 FX-2849 feat: Artwork grids page change event
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/ArtworkFilter/index.tsx
Labels: Jira Synced, Squash On Green

#8078 fix[FX-1758]: adds og meta tags to collection pages
  src/v2/Apps/Collect/Routes/Collection/index.tsx
Labels: Merge On Green

#8081 bugfix: Fix non-watched bid amount
  src/v2/Apps/Auctions/Components/MyBids/MyBidsBidItem.tsx
  src/v2/Apps/Auctions/Components/MyBids/__tests__/MyBidsBidItem.jest.tsx
  src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts
  src/v2/__generated__/MyBidsBidItem_Test_Query.graphql.ts
  src/v2/__generated__/MyBidsBidItem_saleArtwork.graphql.ts
  src/v2/__generated__/MyBidsQuery.graphql.ts
  src/v2/__generated__/MyBids_Test_Query.graphql.ts
  src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
Labels: Merge On Green

#8082 FX-3071 Re-open #8037(feat: Add pagination to fair booths new)
  src/v2/Apps/Fair/Components/ExhibitorFilterContext.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Apps/Fair/Routes/FairExhibitorsQuery.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx
  src/v2/Apps/Fair/fairRoutes.tsx
  src/v2/__generated__/FairExhibitorsQuery.graphql.ts
  src/v2/__generated__/FairExhibitors_Query.graphql.ts
  src/v2/__generated__/FairExhibitors_fair.graphql.ts
  src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
Labels: Jira Synced

#8084 fix: use MetaTags for collection pages
  src/v2/Apps/Collect/Routes/Collection/index.tsx
Labels: Squash On Green

#8083 feat(FX-3139): artist's collection filter alignment
  src/v2/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx
  src/v2/Apps/Collect/Routes/Collection/Components/__tests__/CollectionArtworksFilter.jest.tsx
  src/v2/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/v2/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/v2/__generated__/CollectionArtworksFilter_collection.graphql.ts
  src/v2/__generated__/collectRoutes_CollectionQuery.graphql.ts
Labels: Jira Synced

#8093 feature: Preload Fonts ASAP
  src/v2/index.ejs
Labels: Squash On Green

#8098 Revert "Remove unused: desktop/components/error_handler"
  src/desktop/components/error_handler/README.md
  src/desktop/components/error_handler/index.css
  src/desktop/components/error_handler/index.jade
  src/desktop/components/error_handler/index.styl
  src/desktop/components/error_handler/test/template.test.js
Labels: Merge On Green

#8099 fix(types): passes through system query renderer types
  src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/IconicCollectionsRail/ArtistIconicCollectionsRail.tsx
  src/v2/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebarClassificationsModal.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/InDemandNow/ConsignInDemandNow.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/InDemandNow/ConsignTopArtists.tsx
  src/v2/Apps/Home/Components/HomeArtworkModuleRail.tsx
  src/v2/Apps/Home/Components/HomeFeaturedArticles.tsx
  src/v2/Apps/Partner/Components/Overview/ArtworksRail.tsx
  src/v2/Apps/Partner/Components/Overview/NearbyGalleriesRail.tsx
  src/v2/Apps/Partner/Components/Overview/ShowBannersRail/ShowBannersRail.tsx
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetails.tsx
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetailsList/PartnerArtistDetailsList.tsx
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtists.tsx
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistsCarousel/PartnerArtistsCarousel.tsx
  src/v2/Apps/Partner/Components/PartnerShows/ShowPaginatedEvents.tsx
  src/v2/Apps/WorksForYou/index.tsx
  src/v2/Components/ArtworkGridExample.tsx
  src/v2/Components/AuctionTimer.tsx
  src/v2/Components/FlashBanner/index.tsx
  src/v2/Components/FollowArtistPopover/index.tsx
  src/v2/Components/FollowButton/FollowArtistButton.tsx
  src/v2/Components/Onboarding/ArtistsStep/ArtistSearchResults.tsx
  src/v2/Components/Onboarding/ArtistsStep/PopularArtists.tsx
  src/v2/Components/Onboarding/GenesStep/GeneSearchResults.tsx
  src/v2/Components/Onboarding/GenesStep/SuggestedGenes.tsx
  src/v2/Components/RecentlyViewed/RecentlyViewed.tsx
  src/v2/Components/RecentlyViewed/RecentlyViewedV2.tsx
  src/v2/DevTools/__tests__/renderRelayTree.jest.tsx
  src/v2/System/Relay/RootQueryRenderer.tsx
  src/v2/System/Relay/SystemQueryRenderer.tsx
Labels: Squash On Green

#8108 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/FairsFairRow_Test_Query.graphql.ts
  src/v2/__generated__/FairsFairRow_fair.graphql.ts
  src/v2/__generated__/FairsIndex_Test_Query.graphql.ts
  src/v2/__generated__/FairsIndex_viewer.graphql.ts
  src/v2/__generated__/FairsPastFairsQuery.graphql.ts
  src/v2/__generated__/fairsRoutes_FairsQuery.graphql.ts
Labels: Merge On Green
