Repository artsy/force, pull requests merged in 2021-09, with the labels that each got.

#8323 fix(FX-3077): make images lazy load
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorGroupPlaceholder.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorsGroup.tsx
Labels: Jira Synced

#8317 Deploy
  data/schema.graphql
  package.json
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorGroupPlaceholder.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorsGroup.tsx
  yarn.lock
Labels: Jira Synced

#8331 Revert "chore: add admin flag to show VR in PPP"
  src/v2/Apps/Partner/Components/NavigationTabs/index.tsx
  src/v2/Apps/Partner/Components/__tests__/NavigationTabs.jest.tsx
Labels: Squash On Green

#8332 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8330 fix(loadenv): prevent modifying already set env vars
  src/index.js
  src/lib/loadenv.js
  webpack/utils/env.js
Labels: Merge On Green

#8324 fix(FX-3244): Fix artists search results pagination
  src/v2/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/v2/__generated__/SearchResultsArtistsQuery.graphql.ts
  src/v2/__generated__/SearchResultsArtists_viewer.graphql.ts
  src/v2/__generated__/searchRoutes_SearchResultsArtistsQuery.graphql.ts
Labels: Jira Synced

#8333 Deploy
  package.json
  src/index.js
  src/lib/loadenv.js
  src/v2/Apps/FairOrginizer/Components/FairOrganizerLatestArticles.tsx
  src/v2/Apps/FairOrginizer/Components/__tests__/FairOrganizerLatestArticles.jest.tsx
  src/v2/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/v2/__generated__/SearchResultsArtistsQuery.graphql.ts
  src/v2/__generated__/SearchResultsArtists_viewer.graphql.ts
  src/v2/__generated__/searchRoutes_SearchResultsArtistsQuery.graphql.ts
  webpack/utils/env.js
  yarn.lock
Labels: Jira Synced

#8340 fix(artist): fixes consign button link
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistConsignButton.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/__tests__/ArtistConsignButton.jest.tsx
Labels: Merge On Green

#8339 feat(FX-3249): updated exhibitors tab style
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorGroupPlaceholder.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx
  src/v2/__generated__/FairExhibitorCard_partner.graphql.ts
  src/v2/__generated__/FairExhibitors_Test_Query.graphql.ts
  src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
Labels: Jira Synced

#8343 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8344 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/CollectorIntentUpdateCollectorProfileMutation.graphql.ts
  src/v2/__generated__/useUpdateCollectorProfileMutation.graphql.ts
Labels: Merge On Green

#8341 fix: Increase artist auction results default end date
  src/v2/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/v2/Apps/Artist/artistRoutes.tsx
Labels: Jira Synced, Squash On Green

#8351 feat(FX-3248): updated exhibitors links
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorsGroup.tsx
  src/v2/__generated__/FairExhibitorCard_exhibitor.graphql.ts
  src/v2/__generated__/FairExhibitorCard_partner.graphql.ts
  src/v2/__generated__/FairExhibitorsGroup_exhibitorsGroup.graphql.ts
  src/v2/__generated__/FairExhibitors_Test_Query.graphql.ts
  src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
Labels: Jira Synced

#8353 Revert "Revert "feature: Redis Page Cache""
  src/lib/cacheClient.tsx
  src/lib/middleware/__tests__/redisPageCache.jest.ts
  src/lib/middleware/memoryPageCache.ts
  src/lib/middleware/pageCacheCommon.ts
  src/lib/middleware/redisPageCache.ts
  src/middleware.ts
  src/v2/Utils/logger.ts
Labels: Merge On Green

#8310 feat: update fair organizer page to use organizer profile image
  src/v2/Apps/FairOrginizer/Components/DedicatedArticlesBreadcrumbs.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeaderImage.tsx
  src/v2/Apps/FairOrginizer/Components/__tests__/DedicatedArticlesBreadcrumbs.jest.tsx
  src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx
  src/v2/Apps/FairOrginizer/__tests__/FairOrganizerApp.jest.tsx
  src/v2/__generated__/DedicatedArticlesBreadcrumbs_Test_Query.graphql.ts
  src/v2/__generated__/DedicatedArticlesBreadcrumbs_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerApp_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticlesQuery.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerHeaderImage_fairOrganizer.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerDedicatedArticles_Query.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
Labels: Jira Synced

#8329 FX-3209 Updated articles carousel to v3 design
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorial.tsx
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialRailArticles.tsx
  src/v2/Apps/Fair/Components/FairEditorial/__tests__/FairEditorial.jest.tsx
  src/v2/Apps/Fair/Components/FairEditorial/__tests__/FairEditorialRailArticles.jest.tsx
  src/v2/__generated__/FairEditorialRailArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairEditorialRailArticles_fair.graphql.ts
  src/v2/__generated__/FairEditorial_Test_Query.graphql.ts
  src/v2/__generated__/FairEditorial_fair.graphql.ts
  src/v2/__generated__/FairOverview_Test_Query.graphql.ts
  src/v2/__generated__/fairRoutes_FairOverviewQuery.graphql.ts
Labels: Jira Synced

#8359 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8305 feat(FX-3237): Redirect to active fair page
  cypress/integration/fairOrganizer.spec.ts
  src/v2/Apps/FairOrginizer/fairOrganizerRoutes.tsx
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
Labels: Jira Synced

#8361 Revert "Revert "Revert "Revert "feature: Redis Page Cache""""
  src/lib/cacheClient.tsx
  src/lib/middleware/__tests__/redisPageCache.jest.ts
  src/lib/middleware/memoryPageCache.ts
  src/lib/middleware/redisPageCache.ts
  src/lib/middleware/requestRecorder.ts
  src/middleware.ts
  src/v2/Utils/logger.ts
Labels: Merge On Green

#8362 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8364 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8355 (PLATFORM-3537) feat: login form supports on-demand otp
  src/v2/Components/Authentication/Desktop/LoginForm.tsx
  src/v2/Components/Authentication/Types.ts
  src/v2/Components/Authentication/__tests__/Desktop/LoginForm.jest.tsx
  src/v2/Components/Authentication/helpers.ts
Labels: Merge On Green

#8360 Deploy
  cypress/integration/fairOrganizer.spec.ts
  data/schema.graphql
  package.json
  src/lib/cacheClient.tsx
  src/lib/middleware/__tests__/redisPageCache.jest.ts
  src/lib/middleware/memoryPageCache.ts
  src/lib/middleware/redisPageCache.ts
  src/lib/middleware/requestRecorder.ts
  src/middleware.ts
  src/v2/Apps/FairOrginizer/fairOrganizerRoutes.tsx
  src/v2/Apps/Order/Routes/Status/index.tsx
  src/v2/Components/Authentication/Desktop/LoginForm.tsx
  src/v2/Components/Authentication/Types.ts
  src/v2/Components/Authentication/__tests__/Desktop/LoginForm.jest.tsx
  src/v2/Components/Authentication/helpers.ts
  src/v2/Components/Inquiry/Hooks/useCreateUserInterest.ts
  src/v2/Components/Inquiry/Hooks/useInquiryAffiliated.ts
  src/v2/Components/Inquiry/Hooks/useInquiryContext.tsx
  src/v2/Components/Inquiry/Inquiry.tsx
  src/v2/Components/Inquiry/InquiryDialog.tsx
  src/v2/Components/Inquiry/Views/InquiryArtistsInCollection.tsx
  src/v2/Components/Inquiry/Views/InquiryAuctionHousesYouWorkWith.tsx
  src/v2/Components/Inquiry/Views/InquiryBasicInfo.tsx
  src/v2/Components/Inquiry/Views/InquiryCommercialInterest.tsx
  src/v2/Components/Inquiry/Views/InquiryConfirmation.tsx
  src/v2/Components/Inquiry/Views/InquiryDone.tsx
  src/v2/Components/Inquiry/Views/InquiryExistingUser.tsx
  src/v2/Components/Inquiry/Views/InquiryFairsYouAttend.tsx
  src/v2/Components/Inquiry/Views/InquiryGalleriesYouWorkWith.tsx
  src/v2/Components/Inquiry/Views/InquiryHowCanWeHelp.tsx
  src/v2/Components/Inquiry/Views/InquiryInquiry.tsx
  src/v2/Components/Inquiry/Views/InquiryInstitutionalAffiliations.tsx
  src/v2/Components/Inquiry/Views/InquiryLogin.tsx
  src/v2/Components/Inquiry/Views/InquiryResetPassword.tsx
  src/v2/Components/Inquiry/Views/InquirySignUp.tsx
  src/v2/Components/Inquiry/Views/InquirySpecialist.tsx
  src/v2/Components/Inquiry/__tests__/Hooks/useInquiryAffiliated.jest.tsx
  src/v2/Components/Inquiry/__tests__/Views/InquiryBasicInfo.jest.tsx
  src/v2/Components/Inquiry/__tests__/Views/InquiryCommercialInterest.jest.tsx
  src/v2/Components/Inquiry/__tests__/Views/InquiryInstitutionalAffiliations.jest.tsx
  src/v2/Components/Inquiry/__tests__/Views/InquiryLogin.jest.tsx
  src/v2/Components/Inquiry/__tests__/Views/InquiryResetPassword.jest.tsx
  src/v2/Components/Inquiry/__tests__/Views/InquirySignUp.jest.tsx
  src/v2/Components/Inquiry/config.ts
  src/v2/Utils/logger.ts
  src/v2/__generated__/InquiryArtistsInCollectionQuery.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
  src/v2/__generated__/useCreateUserInterestMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#8371 feat(FX-3286): redirect to fair overview
  src/v2/Apps/Fair/Components/FairBoothRail/FairBoothRailArtworks.tsx
  src/v2/Apps/Fair/fairRoutes.tsx
Labels: Jira Synced

#8372 Deploy
  src/v2/Apps/Fair/Components/FairBoothRail/FairBoothRailArtworks.tsx
  src/v2/Apps/Fair/fairRoutes.tsx
Labels: Jira Synced

#8376 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8350 refactor(PURCHASE-2918):BuyerGuarantee page refactoring
  src/v2/Apps/BuyerGuarantee/Components/Feature.tsx
  src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
  src/v2/Apps/Fairs/Routes/FairsIndex.tsx
Labels: Jira Synced

#8302 refactor: migrates Shipping app to use Palette V3
  src/v2/Apps/Order/Components/AddressModal.tsx
  src/v2/Apps/Order/Components/SavedAddressItem.tsx
  src/v2/Apps/Order/Components/SavedAddresses.tsx
  src/v2/Apps/Shipping/shippingRoutes.tsx
  src/v2/Components/Address/AddressModalFields.tsx
  src/v2/Components/Payment/PaymentModal.tsx
  src/v2/Components/UserSettings/UserSettingsAddresses.tsx
Labels: Jira Synced

#8380 feat(inquiry): decision making
  src/v2/Apps/Debug/DebugInquiryApp.tsx
  src/v2/Components/DeepZoom/DeepZoom.tsx
  src/v2/Components/Inquiry/Components/InquiryAffiliatedAutocomplete.tsx
  src/v2/Components/Inquiry/Components/InquiryBackdrop.tsx
  src/v2/Components/Inquiry/Engine.tsx
  src/v2/Components/Inquiry/Hooks/useInquiryContext.tsx
  src/v2/Components/Inquiry/Inquiry.tsx
  src/v2/Components/Inquiry/InquiryDialog.tsx
  src/v2/Components/Inquiry/Views/InquiryBasicInfo.tsx
  src/v2/Components/Inquiry/Views/InquiryCommercialInterest.tsx
  src/v2/Components/Inquiry/Visited.ts
  src/v2/Components/Inquiry/__tests__/Engine.jest.ts
  src/v2/Components/Inquiry/__tests__/Views/InquiryBasicInfo.jest.tsx
  src/v2/Components/Inquiry/__tests__/Views/InquiryCommercialInterest.jest.tsx
  src/v2/Components/Inquiry/__tests__/Visited.jest.ts
  src/v2/Components/Inquiry/config.ts
  src/v2/Components/Inquiry/useInquiry.tsx
  src/v2/System/Relay/SystemQueryRenderer.tsx
  src/v2/__generated__/useInquiryContextQuery.graphql.ts
  src/v2/__generated__/useInquiryContext_me.graphql.ts
Labels: Squash On Green

#8388 fix(homepage): fixes missing image state
  src/v2/Apps/Home/Components/HomeFeaturedEventsRail.tsx
Labels: Squash On Green

#8391 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/useArtworkInquiryRequestMutation.graphql.ts
Labels: Merge On Green

#8390 feat: Remove homepage modules
  src/v2/Apps/Home/Components/HomeArtworkModules.tsx
  src/v2/Apps/Home/Components/HomeFeaturedCategoriesRail.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Apps/Home/__tests__/HomeArtworkModuleContext.jest.tsx
  src/v2/__generated__/HomeApp_Test_Query.graphql.ts
  src/v2/__generated__/HomeArtworkModules_homePage.graphql.ts
  src/v2/__generated__/HomeFeaturedCategoriesRailQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedCategoriesRail_marketingCollections.graphql.ts
  src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts
Labels: Merge On Green

#8395 fix cypress test
  cypress/integration/shows.spec.ts
Labels: Merge On Green

#8394 feat: Update homepage article layout
  src/v2/Apps/Home/Components/HomeFeaturedArticles.tsx
  src/v2/Apps/Home/__tests__/HomeFeaturedArticles.jest.tsx
  src/v2/__generated__/HomeFeaturedArticlesQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedArticles_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedArticles_articles.graphql.ts
Labels: Merge On Green

#8397 Revert "feat: add flag country code dropdown to profile form"
  src/v2/Apps/Order/Components/AddressModal.tsx
  src/v2/Apps/Order/Components/__tests__/AddressModal.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/v2/Apps/Order/Utils/shippingUtils.ts
  src/v2/Utils/countries.ts
Labels: Merge On Green

#8383 fix(FX-3289): Group all numeral together
  src/v2/Apps/Fair/Components/ExhibitorsLetterNav.tsx
  src/v2/Apps/Fair/Components/__tests__/ExhibitorsLetterNav.jest.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Apps/Fair/Utils/getExhibitorSectionId.ts
Labels: Jira Synced

#8407 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistsIndexFragmentContainer_Test_Query.graphql.ts
  src/v2/__generated__/FairsIndex_Test_Query.graphql.ts
  src/v2/__generated__/FeatureApp_Test_Query.graphql.ts
  src/v2/__generated__/HomeApp_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedShowsQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedShows_Test_Query.graphql.ts
  src/v2/__generated__/ShowsIndex_Test_Query.graphql.ts
  src/v2/__generated__/artistsRoutes_ArtistsQuery.graphql.ts
  src/v2/__generated__/fairsRoutes_FairsQuery.graphql.ts
  src/v2/__generated__/featureRoutes_FeatureQuery.graphql.ts
  src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts
  src/v2/__generated__/showsRoutes_ShowsIndexQuery.graphql.ts
  src/v2/__generated__/useArtworkInquiryRequestMutation.graphql.ts
Labels: Merge On Green

#8408 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8410 feat[FX-3291]: add MetaTags to the FairOrganizerApp
  src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx
  src/v2/Apps/FairOrginizer/__tests__/FairOrganizerApp.jest.tsx
  src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerApp_fairOrganizer.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
Labels: Merge On Green

#8402 feat(FX-3303): Added Read More functionality
  src/v2/Apps/Fair/Components/FairOverview/FairAbout.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairOverview.jest.tsx
  src/v2/__generated__/FairAbout_fair.graphql.ts
  src/v2/__generated__/FairOverview_Test_Query.graphql.ts
  src/v2/__generated__/fairRoutes_FairOverviewQuery.graphql.ts
Labels: Jira Synced

#8409 fix(FX-3231): Removed max width of fair article
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx
Labels: Jira Synced

#8401 feat(FX-3280): added back link for fair shows
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx
  src/v2/Apps/Show/Components/ShowHeader.tsx
  src/v2/Apps/Show/Components/ShowNavigationBanner.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/ShowHeader_show.graphql.ts
  src/v2/__generated__/ShowNavigationBanner_show.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
Labels: Jira Synced

#8415 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8398 feat: [Home] Add new featured galleries rail
  src/v2/Apps/Home/Components/HomeFeaturedGalleriesRail.tsx
  src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx
  src/v2/Apps/Home/Components/HomeFeaturedShows.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Apps/Home/__tests__/HomeApp.jest.tsx
  src/v2/Apps/Home/__tests__/HomeFeaturedGalleriesRail.jest.tsx
  src/v2/Apps/Home/__tests__/HomeFeaturedMarketNews.jest.tsx
  src/v2/Apps/Home/homeRoutes.tsx
  src/v2/__generated__/HomeApp_Test_Query.graphql.ts
  src/v2/__generated__/HomeApp_featuredEventsOrderedSet.graphql.ts
  src/v2/__generated__/HomeFeaturedGalleriesRailQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedGalleriesRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedGalleriesRail_orderedSet.graphql.ts
  src/v2/__generated__/HomeFeaturedMarketNewsQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedMarketNews_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedMarketNews_articles.graphql.ts
  src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts
Labels: Merge On Green

#8421 Revert "fix(FX-3231): Removed max width of fair article"
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx
Labels: Squash On Green

#8400 feat: Add autosuggest quick navigation (second try)
  src/v2/Components/Search/SearchBar.tsx
  src/v2/Components/Search/Suggestions/SuggestionItem.tsx
  src/v2/Components/Search/__tests__/SearchBar.jest.tsx
  src/v2/__generated__/SearchBarRefetchQuery.graphql.ts
  src/v2/__generated__/SearchBarSuggestQuery.graphql.ts
  src/v2/__generated__/SearchBarTestQuery.graphql.ts
  src/v2/__generated__/SearchBar_viewer.graphql.ts
Labels: Jira Synced

#8419 fix(FX-3291): adjust meta description on FairOrganizerApp
  src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx
  src/v2/Apps/FairOrginizer/__tests__/FairOrganizerApp.jest.tsx
  src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerApp_fairOrganizer.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
Labels: Jira Synced

#8423 fix(artworkgriditem): uses correct max width; supports srcset
  src/v2/Components/Artwork/Badge.tsx
  src/v2/Components/Artwork/GridItem.tsx
Labels: Merge On Green

#8425 Revert "feat(FX-3280): added back link for fair shows"
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx
  src/v2/Apps/Show/Components/ShowHeader.tsx
  src/v2/Apps/Show/Components/ShowNavigationBanner.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/ShowHeader_show.graphql.ts
  src/v2/__generated__/ShowNavigationBanner_show.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
Labels: Merge On Green, Jira Synced

#8418 feat: [Home] Add current fairs rail
  src/v2/Apps/Home/Components/HomeCurrentFairsRail.tsx
  src/v2/Apps/Home/Components/HomeFeaturedGalleriesRail.tsx
  src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx
  src/v2/Apps/Home/Components/HomeFeaturedShow.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Apps/Home/__tests__/HomeCurrentFairsRail.jest.tsx
  src/v2/__generated__/HomeCurrentFairsRailQuery.graphql.ts
  src/v2/__generated__/HomeCurrentFairsRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeCurrentFairsRail_viewer.graphql.ts
Labels: Squash On Green

#8422 fix(FX-3282): encode search query param
  src/v2/Apps/Search/Components/NavigationTabs.tsx
  src/v2/Components/Search/SearchBar.tsx
Labels: Jira Synced

#8428 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8429 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8420 fix(FX-3231): Aligned articles layout
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItemLink.tsx
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialRailArticles.tsx
  src/v2/Apps/FairOrginizer/Routes/FairOrganizerDedicatedArticles.tsx
  src/v2/__generated__/FairEditorialItemLink_article.graphql.ts
  src/v2/__generated__/FairEditorialItem_Test_Query.graphql.ts
  src/v2/__generated__/FairEditorialItem_article.graphql.ts
  src/v2/__generated__/FairEditorialRailArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairEditorial_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticlesQuery.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerLatestArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairOverview_Test_Query.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerDedicatedArticles_Query.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairOverviewQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#8437 chore: adds feat flag to show/hide country code dropdown menu
  src/v2/Apps/Order/Components/AddressModal.tsx
  src/v2/Apps/Order/Components/__tests__/AddressModal.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
Labels: Merge On Green

#8443 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/CreateUserAddressMutation.graphql.ts
  src/v2/__generated__/UpdateUserAddressMutation.graphql.ts
Labels: Merge On Green

#8370 fix(PURCHASE-2909): Show zendesk only for BNMO artworks exceeding price threshold
  src/v2/Apps/Artwork/Components/ArtworkMeta.tsx
  src/v2/Apps/Order/OrderApp.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/Utils/isExceededZendeskThreshold.ts
  src/v2/__generated__/ArtworkMeta_artwork.graphql.ts
  src/v2/__generated__/OrderApp_order.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/orderRoutes_OrderQuery.graphql.ts
Labels: Jira Synced

#8448 remove clickedArtworkGroup helpers
  src/v2/Apps/Auctions/Components/AuctionArtworksRail/AuctionArtworksRail.tsx
  src/v2/Apps/Auctions/Components/AuctionArtworksRail/AuctionArtworksRailArtworks.tsx
  src/v2/Apps/Auctions/Components/AuctionArtworksRail/__tests__/AuctionArtworksRail.jest.tsx
  src/v2/Apps/Auctions/Components/AuctionArtworksRail/__tests__/AuctionArtworksRailArtworks.jest.tsx
  src/v2/Apps/Auctions/Components/MyBids/MyBidsBidItem.tsx
  src/v2/Apps/Auctions/Components/MyBids/__tests__/MyBidsBidItem.jest.tsx
  src/v2/Apps/Auctions/Components/StandoutLots/StandoutLots.tsx
  src/v2/Apps/Auctions/Components/StandoutLots/__tests__/StandoutLots.jest.tsx
  src/v2/Apps/Auctions/Components/TrendingLots/TrendingLots.tsx
  src/v2/Apps/Auctions/Components/TrendingLots/__tests__/TrendingLots.jest.tsx
  src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail/WorksByArtistsYouFollowRail.tsx
  src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail/__tests__/WorksByArtistsYouFollowRail.jest.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/SoldRecently.tsx
  src/v2/Utils/cohesionHelpers.ts
Labels: Squash On Green

#8455 chore: Sync mp schema & Update HomeArtworkModule types
  data/schema.graphql
  src/v2/Apps/Home/Components/HomeArtworkModuleRail.tsx
  src/v2/Apps/Home/Components/HomeArtworkModules.tsx
  src/v2/__generated__/HomeArtworkModuleRailQuery.graphql.ts
Labels: Merge On Green

#8464 Update metaphysics schema
  src/v2/__generated__/CreateUserAddressMutation.graphql.ts
  src/v2/__generated__/UpdateUserAddressMutation.graphql.ts
Labels: Merge On Green

#8466 bugfix: [Home] Fix homepage module display
  src/v2/Apps/Home/Components/HomeArtworkModules.tsx
Labels: Merge On Green

#8459 feat: update mappings for arta shipping tiers [PX-4585]
  src/v2/Apps/Order/Components/ShippingQuotes.tsx
  src/v2/Apps/Order/Components/__tests__/TransactionDetailsSummary.jest.tsx
  src/v2/Apps/Order/Routes/__fixtures__/MutationResults/setOrderShipping.ts
  src/v2/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
Labels: Jira Synced

#8468 Deploy
  src/v2/Apps/Order/Components/ShippingQuotes.tsx
  src/v2/Apps/Order/Components/__tests__/TransactionDetailsSummary.jest.tsx
  src/v2/Apps/Order/Routes/__fixtures__/MutationResults/setOrderShipping.ts
  src/v2/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
Labels: Jira Synced

#8469 feat: [Home] Add logged-in rails
  src/v2/Apps/Auctions/Components/MyBids/MyBids.tsx
  src/v2/Apps/Home/Components/HomeArtworkModules.tsx
  src/v2/Apps/Home/Components/HomeAuctionLotsRail.tsx
  src/v2/Apps/Home/Components/HomeRecentlyViewedRail.tsx
  src/v2/Apps/Home/Components/HomeWorksByArtistsYouFollowRail.tsx
  src/v2/Apps/Home/Components/HomeWorksForYouTabBar.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Apps/Home/__tests__/HomeRecentlyViewedRail.jest.tsx
  src/v2/Apps/Home/__tests__/HomeWorksByArtistsYouFollowRail.jest.tsx
  src/v2/Apps/Home/__tests__/HomeWorksForYouTabBar.jest.tsx
  src/v2/__generated__/HomeApp_Test_Query.graphql.ts
  src/v2/__generated__/HomeApp_homePage.graphql.ts
  src/v2/__generated__/HomeArtworkModules_homePage.graphql.ts
  src/v2/__generated__/HomeRecentlyViewedRailQuery.graphql.ts
  src/v2/__generated__/HomeRecentlyViewedRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeRecentlyViewedRail_homePage.graphql.ts
  src/v2/__generated__/HomeWorksByArtistsYouFollowRailQuery.graphql.ts
  src/v2/__generated__/HomeWorksByArtistsYouFollowRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeWorksByArtistsYouFollowRail_homePage.graphql.ts
  src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts
Labels: Squash On Green

#8440 fix: Buyer guarantee refactor QA fixes
  src/v2/Apps/BuyerGuarantee/Components/Feature.tsx
  src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
Labels: Jira Synced

#8473 fix: Use PNGs instead of webps for price database
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
Labels: Squash On Green

#8474 cleanup: Use responsive props instead of media
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseSearch.tsx
Labels: Squash On Green

#8478 fix: add some space between shipping options and button
  src/v2/Apps/Order/Routes/Shipping/index.tsx
Labels: Jira Synced

#8480 chore: More // @ts-expect-error cleanup
  .eslintrc.js
  src/desktop/apps/article/__tests__/helpers.jest.tsx
  src/desktop/apps/article/components/__tests__/EditButton.jest.tsx
  src/desktop/apps/article/components/__tests__/InfiniteScrollArticle.jest.tsx
  src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.jest.tsx
  src/desktop/apps/article/components/__tests__/NewsArticle.jest.tsx
  src/desktop/apps/article/components/layouts/__tests__/Article.jest.tsx
  src/desktop/apps/articles/components/__tests__/AuthWrapper.jest.tsx
  src/desktop/apps/consign/client/analytics_middleware.ts
  src/desktop/components/marketing_signup_modal/__test__/triggerMarketingModal.jest.ts
  src/desktop/lib/buildClientAppContext.ts
  src/desktop/lib/deprecated_global_client_setup.tsx
  src/typings/gravity.d.ts
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/v2/Apps/Components/AppShell.tsx
  src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
  src/v2/Components/FlashBanner/__tests__/FlashBanner.jest.tsx
  src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
  src/v2/System/Analytics/__tests__/trackingMiddleware.jest.ts
  src/v2/System/Relay/__tests__/createRelaySSREnvironment.jest.ts
  src/v2/System/Relay/createRelaySSREnvironment.ts
  src/v2/System/Relay/middleware/cache/cacheMiddleware.ts
  src/v2/System/Relay/middleware/metaphysicsErrorHandlerMiddleware.ts
  src/v2/System/SystemContext.tsx
  src/v2/System/__tests__/SystemContext.jest.tsx
  src/v2/Utils/__tests__/user.jest.ts
  src/v2/Utils/user.ts
Labels: Merge On Green

#8481 refactor: Rename useMatchMedia to __internal__useMatchMedia
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/SizeFilter.jest.tsx
  src/v2/Apps/BuyerGuarantee/Components/Feature.tsx
  src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
  src/v2/Apps/BuyerGuarantee/Routes/__tests__/BuyerGuaranteeIndex.jest.tsx
  src/v2/Apps/Fair/Components/ExhibitorsLetterNav.tsx
  src/v2/Apps/Fair/Components/__tests__/ExhibitorsLetterNav.jest.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx
  src/v2/Apps/Order/Components/__tests__/AddressModal.jest.tsx
  src/v2/Apps/Order/Components/__tests__/SavedAddresses.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/v2/Apps/Partner/Components/ScrollToPartnerHeader/index.tsx
  src/v2/Apps/Partner/Components/__tests__/Overview/ArtistsRail.jest.tsx
  src/v2/Apps/Partner/Routes/Artists/ArtistsRoute.tsx
  src/v2/Apps/Partner/Routes/__tests__/Works.jest.tsx
  src/v2/Apps/Shipping/__tests__/ShippingApp.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ArtistNationalityFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ArtistsFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ArtworkLocationFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/AttributionClassFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/MaterialsTermFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/MediumFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/PartnersFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ResultsFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/WaysToBuyFilter.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx
  src/v2/Components/NavBar/NavBar.tsx
  src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
  src/v2/Components/NavBar/__tests__/NavBarTracking.jest.tsx
  src/v2/Components/Toast/ToastComponent.tsx
  src/v2/Components/UserSettings/__tests__/UserSettingsAddresses.jest.tsx
  src/v2/Utils/Hooks/useMatchMedia.ts
Labels: Merge On Green

#8382 feat(FX-3170): refresh search results page
  src/v2/Apps/Search/Components/FallbackIcon.tsx
  src/v2/Apps/Search/Components/GenericSearchResultItem.tsx
  src/v2/Apps/Search/Components/NavigationTabs.tsx
  src/v2/Apps/Search/Components/SearchMeta.tsx
  src/v2/Apps/Search/Components/SearchResultsSkeleton/FilterSidebar.tsx
  src/v2/Apps/Search/Components/SearchResultsSkeleton/GridItem.tsx
  src/v2/Apps/Search/Components/SearchResultsSkeleton/Header.tsx
  src/v2/Apps/Search/Components/SearchResultsSkeleton/index.tsx
  src/v2/Apps/Search/Components/__tests__/NavigationTabs.jest.tsx
  src/v2/Apps/Search/Routes/SearchResultsArtists.tsx
  src/v2/Apps/Search/Routes/SearchResultsArtworks.tsx
  src/v2/Apps/Search/Routes/SearchResultsEntity.tsx
  src/v2/Apps/Search/Routes/__tests__/SearchResultsArtists.jest.tsx
  src/v2/Apps/Search/Routes/__tests__/SearchResultsEntity.jest.tsx
  src/v2/Apps/Search/SearchApp.tsx
  src/v2/Apps/Search/__tests__/SearchApp.jest.tsx
  src/v2/Apps/Search/searchRoutes.tsx
  src/v2/__generated__/SearchApp_Test_Query.graphql.ts
Labels: Jira Synced

#8447 fix(PURCHASE-2923): add zIndex to toast component
  src/v2/Components/Toast/ToastComponent.tsx
Labels: Jira Synced

#8449 feat(FX-3280): navigation banner at fair show page
  src/v2/Apps/Fair/Components/ExhibitorsLetterNav.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx
  src/v2/Apps/Fair/Components/__tests__/FairExhibitorsGroup.jest.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx
  src/v2/Apps/Fair/Utils/useExhibitorsTabOffset.ts
  src/v2/Apps/Show/Components/ShowNavigationBanner.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/ShowNavigationBanner_show.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
Labels: Jira Synced

#8488 fix(FX-3328): search term is undefined when redirect to other page
  src/v2/Apps/Search/SearchApp.tsx
Labels: Jira Synced

#8496 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8499 fix(inquiry): integrity tweaks
  src/v2/Components/Inquiry/Components/InquiryAffiliatedAutocomplete.tsx
  src/v2/Components/Inquiry/Views/InquiryInquiry.tsx
  src/v2/Components/Inquiry/config.ts
  src/v2/Components/LocationAutocompleteInput.tsx
Labels: Merge On Green

#8495 fix: Adjust artist app render or redirect checks
  src/v2/Apps/Artist/ArtistApp.tsx
  src/v2/Apps/Artist/Routes/Overview/Utils/renderOrRedirect.tsx
  src/v2/__generated__/ArtistApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtistApp_artist.graphql.ts
  src/v2/__generated__/ArtistApp_sharedMetadata.graphql.ts
  src/v2/__generated__/artistRoutes_TopLevelQuery.graphql.ts
Labels: Jira Synced

#8503 fix: Route to artist page without partner prefix
  src/v2/Apps/Home/Components/HomeTrendingArtistsRail.tsx
Labels: Merge On Green

#8505 fix(FX-3387): broken links in "current fairs" section
  src/v2/Apps/Home/Components/HomeCurrentFairsRail.tsx
  src/v2/Apps/Home/__tests__/HomeCurrentFairsRail.jest.tsx
Labels: Jira Synced, Squash On Green

#8507 fix(mybids): uses lot label in place of position
  src/v2/Apps/Auctions/Components/MyBids/MyBidsBidItem.tsx
  src/v2/Apps/Auctions/Components/MyBids/__tests__/MyBidsBidItem.jest.tsx
  src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts
  src/v2/__generated__/MyBidsBidItem_Test_Query.graphql.ts
  src/v2/__generated__/MyBidsBidItem_saleArtwork.graphql.ts
  src/v2/__generated__/MyBidsQuery.graphql.ts
  src/v2/__generated__/MyBids_Test_Query.graphql.ts
  src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
Labels: Merge On Green

#8509 fix(FX-3391): Fix copy in web hover menu for Artists
  src/v2/Components/NavBar/menuData.ts
Labels: Jira Synced

#8494 [Home] Add tracking
  src/v2/Apps/Home/Components/HomeAuctionLotsRail.tsx
  src/v2/Apps/Home/Components/HomeCurrentFairsRail.tsx
  src/v2/Apps/Home/Components/HomeFeaturedEventsRail.tsx
  src/v2/Apps/Home/Components/HomeFeaturedGalleriesRail.tsx
  src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx
  src/v2/Apps/Home/Components/HomeFeaturedShow.tsx
  src/v2/Apps/Home/Components/HomeFeaturedShowsRail.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/__tests__/HomeHeroUnit.jest.tsx
  src/v2/Apps/Home/Components/HomeRecentlyViewedRail.tsx
  src/v2/Apps/Home/Components/HomeTrendingArtistsRail.tsx
  src/v2/Apps/Home/Components/HomeWorksByArtistsYouFollowRail.tsx
  src/v2/Apps/Home/__tests__/HomeApp.jest.tsx
  src/v2/Apps/Home/__tests__/HomeAuctionLotsRail.jest.tsx
  src/v2/Apps/Home/__tests__/HomeCurrentFairsRail.jest.tsx
  src/v2/Apps/Home/__tests__/HomeFeaturedGalleriesRail.jest.tsx
  src/v2/Apps/Home/__tests__/HomeFeaturedMarketNews.jest.tsx
  src/v2/Apps/Home/__tests__/HomeFeaturedShowsRail.jest.tsx
  src/v2/Apps/Home/__tests__/HomeRecentlyViewedRail.jest.tsx
  src/v2/Apps/Home/__tests__/HomeTrendingArtistsRail.jest.tsx
  src/v2/Apps/Home/__tests__/HomeWorksByArtistsYouFollowRail.jest.tsx
  src/v2/__generated__/HomeCurrentFairsRailQuery.graphql.ts
  src/v2/__generated__/HomeCurrentFairsRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeCurrentFairsRail_viewer.graphql.ts
  src/v2/__generated__/HomeFeaturedGalleriesRailQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedGalleriesRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedGalleriesRail_orderedSet.graphql.ts
  src/v2/__generated__/HomeFeaturedMarketNewsQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedMarketNews_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedMarketNews_articles.graphql.ts
  src/v2/__generated__/HomeFeaturedShow_show.graphql.ts
  src/v2/__generated__/HomeFeaturedShowsRailQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedShowsRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeHeroUnit_Test_Query.graphql.ts
  src/v2/__generated__/HomeRecentlyViewedRailQuery.graphql.ts
  src/v2/__generated__/HomeRecentlyViewedRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeRecentlyViewedRail_homePage.graphql.ts
  src/v2/__generated__/HomeTrendingArtistsRailQuery.graphql.ts
  src/v2/__generated__/HomeTrendingArtistsRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeTrendingArtistsRail_viewer.graphql.ts
  src/v2/__generated__/HomeWorksByArtistsYouFollowRailQuery.graphql.ts
  src/v2/__generated__/HomeWorksByArtistsYouFollowRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeWorksByArtistsYouFollowRail_homePage.graphql.ts
Labels: Merge On Green

#8521 Update metaphysics schema
  src/v2/__generated__/HomeCurrentFairsRailQuery.graphql.ts
  src/v2/__generated__/HomeCurrentFairsRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeCurrentFairsRail_viewer.graphql.ts
Labels: Merge On Green

#8516 feat: Track user interactions in new checkout flow - order review page [PX-4617]
  src/v2/Apps/Order/Routes/Review/index.tsx
Labels: Jira Synced

#8515 fix(inquiry): reload on close after authentication
  src/v2/Apps/Debug/DebugInquiryApp.tsx
  src/v2/Components/Inquiry/Components/InquiryBackdrop.tsx
  src/v2/Components/Inquiry/Hooks/useInquiryContext.tsx
  src/v2/Components/Inquiry/Inquiry.tsx
  src/v2/Components/Inquiry/Views/InquiryBasicInfo.tsx
  src/v2/Components/Inquiry/Views/InquiryLogin.tsx
  src/v2/Components/Inquiry/Views/InquirySignUp.tsx
  src/v2/Components/Inquiry/__tests__/Views/InquiryLogin.jest.tsx
  src/v2/Components/Inquiry/__tests__/Views/InquirySignUp.jest.tsx
  src/v2/Components/Inquiry/config.ts
Labels: Merge On Green

#8520 feat: implement tracking in force for shipping page [PX-4619]
  src/v2/Apps/Order/Components/BuyerGuarantee.tsx
  src/v2/Apps/Order/Components/SavedAddresses.tsx
  src/v2/Apps/Order/Components/__tests__/SavedAddresses.jest.tsx
  src/v2/Apps/Order/Routes/Review/index.tsx
  src/v2/Apps/Order/Routes/Shipping/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Accept.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Counter.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/v2/Apps/Shipping/__tests__/ShippingApp.jest.tsx
  src/v2/Components/UserSettings/__tests__/UserSettingsAddresses.jest.tsx
Labels: Jira Synced, Squash On Green

#8524 fix: [Home] Fix columns on CurrentFairs
  src/v2/Apps/Home/Components/HomeCurrentFairsRail.tsx
  src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitsLarge.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Components/Masonry.tsx
Labels: Merge On Green
