Repository artsy/force, pull requests merged in 2021-08, with the labels that each got.

#8097 feat(FX-3131): Support following the fair organizer
  src/v2/Apps/FairOrginizer/Components/FairOrganizerFollowButton.tsx
  src/v2/Apps/FairOrginizer/Components/__tests__/FairOrganizerFollowButton.jest.tsx
  src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx
  src/v2/Apps/FairOrginizer/Mutations/FairOrganizerFollowMutation.ts
  src/v2/Apps/FairOrginizer/fairOrganizerRoutes.tsx
  src/v2/__generated__/FairOrganizerApp_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerFollowButton_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerFollowButton_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerFollowMutation.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_Query.graphql.ts
Labels: Jira Synced

#8131 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8134 fix: Cookie Export
  src/desktop/components/cookies/index.ts
Labels: Squash On Green

#8135 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8137 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8139 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8142 fix(navbar): corrects logged out mobile auth buttons
  src/v2/Apps/Components/AppShell.tsx
  src/v2/Components/AuthBanner.tsx
  src/v2/Components/NavBar/NavBar.tsx
  src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
  src/v2/Components/NavBar/constants.ts
Labels: Squash On Green

#8143 fix(navbar): tweaks desktop logged out button vertical alignment
  src/v2/Components/NavBar/NavBar.tsx
Labels: Squash On Green

#8126 fix(FX-2825): analytics event for clearing custom size
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter.jest.tsx
  src/v2/Components/ArtworkFilter/Utils/__tests__/urlFragmentFromState.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
Labels: Jira Synced

#7920 feat: initial real time conversations implementation
  src/v2/Apps/Conversation/Components/ConfirmArtworkModal.tsx
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/ConversationCTA.tsx
  src/v2/Apps/Conversation/Components/ConversationMessages.tsx
  src/v2/Apps/Conversation/Components/NewMessageMarker.tsx
  src/v2/Apps/Conversation/Components/OpenInquiryModalButton.tsx
  src/v2/Apps/Conversation/Components/Reply.tsx
  src/v2/Apps/Conversation/Components/UnreadMessagesToast.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConversationCTA.jest.tsx
  src/v2/Apps/Conversation/Utils/useOnScreen.ts
  src/v2/Apps/Conversation/Utils/usePoll.ts
  src/v2/Apps/Conversation/__tests__/Reply.jest.tsx
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/UnreadMessagesToastQuery.graphql.ts
  src/v2/__generated__/UnreadMessagesToast_conversation.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Jira Synced

#8112 GRO-462: Update sell with artsy landing page
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/ArtsyMissionStatement.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/FAQ.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/SellArtDifferently.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Header.jest.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/v2/Components/FullBleedHeader.tsx
Labels: Jira Synced

#8158 fix(navbar): improves overflow scrolling
  src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuItem.tsx
  src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuTransition.tsx
Labels: Squash On Green

#8115 feat(FX-3133): fair organizer past events
  src/v2/Apps/FairOrginizer/Components/FairOrganizerPastEventRailCell.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerPastEventsRail.tsx
  src/v2/Apps/FairOrginizer/Components/__tests__/FairOrganizerPastEventsRail.jest.tsx
  src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx
  src/v2/Apps/FairOrginizer/__tests__/FairOrganizerApp.jest.tsx
  src/v2/Apps/FairOrginizer/fairOrganizerRoutes.tsx
  src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerApp_pastFairs.graphql.ts
  src/v2/__generated__/FairOrganizerPastEventRailCell_fair.graphql.ts
  src/v2/__generated__/FairOrganizerPastEventsRail_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerPastEventsRail_fairs.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
Labels: Jira Synced

#8103 fix: Hide current password input in settings form conditionally
  src/desktop/apps/user/components/password/index.jade
  src/desktop/apps/user/components/password/view.coffee
Labels: Jira Synced

#8160 chore: Remove feature flag checkers for web inquiry checkout
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/ConversationCTA.tsx
  src/v2/Apps/Conversation/Components/__tests__/Conversation.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConversationCTA.jest.tsx
Labels: Merge On Green

#8147 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8165 revert: Adjust MO button style and move order update timestamp
  src/v2/Apps/Conversation/Components/OpenInquiryModalButton.tsx
  src/v2/Apps/Conversation/Components/OrderUpdate.tsx
  src/v2/Apps/Conversation/Components/Reply.tsx
Labels: Squash On Green

#8166 Remove the Help chat bubble from Inquiry checkout modal
  src/v2/Apps/Order/OrderApp.tsx
  src/v2/Apps/Order/__tests__/OrderApp.jest.tsx
Labels: Jira Synced

#8169 feat(FX-3130): adjust styles on fair organizer page
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeader.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeaderIcon.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerInfo.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerTiming.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/__tests__/FairOrganizerHeader.jest.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/__tests__/FairOrganizerTiming.jest.tsx
  src/v2/Components/InfoSection.tsx
  src/v2/Components/ProfileIcon.tsx
  src/v2/Components/Timer.tsx
  src/v2/Components/__tests__/ProfileIcon.jest.tsx
  src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerHeaderIcon_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerHeader_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerHeader_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerTiming_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerTiming_fair.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
Labels: Jira Synced

#8174 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8102 feat:toast component for save address notifications [PURCHASE-2771]
  src/v2/Apps/Order/Components/AddressModal.tsx
  src/v2/Apps/Order/Components/SavedAddresses.tsx
  src/v2/Apps/Order/Components/__tests__/AddressModal.jest.tsx
  src/v2/Apps/Order/Components/__tests__/SavedAddresses.jest.tsx
  src/v2/Apps/Order/Mutations/DeleteUserAddress.ts
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/v2/Apps/Shipping/__tests__/ShippingApp.jest.tsx
  src/v2/Components/Toast/ToastComponent.tsx
  src/v2/Components/UserSettings/UserSettingsAddresses.tsx
  src/v2/Components/UserSettings/__tests__/UserSettingsAddresses.jest.tsx
  src/v2/__generated__/UserSettingsAddresses_test_Query.graphql.ts
Labels: Jira Synced

#8183 fix(artwork): fixes layout shift in artwork banner
  src/v2/Apps/Artwork/Components/ArtworkBanner/ArtworkBanner.tsx
  src/v2/__generated__/ArtworkBannerQuery.graphql.ts
  src/v2/__generated__/ArtworkBanner_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkBanner_artwork.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Squash On Green

#8184 fix(about): avoids initializing slideshow if selector is missing
  src/desktop/apps/about/client/view.coffee
Labels: Squash On Green

#8181 fix(GRO-480): defer offscreen images
  package.json
  src/v2/Apps/Artwork/Components/ArtistInfo.tsx
  src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/v2/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/v2/Apps/__tests__/Fixtures/Artwork/ArtistInfo.ts
  src/v2/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarArtists.ts
  src/v2/Components/ArtistCard.tsx
  src/v2/Components/__tests__/ArtistCard.jest.tsx
  src/v2/__generated__/ArtistCard_artist.graphql.ts
  src/v2/__generated__/ArtistInfoQuery.graphql.ts
  src/v2/__generated__/ArtistInfo_Test_Query.graphql.ts
  src/v2/__generated__/ArtistInfo_artist.graphql.ts
  src/v2/__generated__/ArtworkDetailsAboutTheWorkFromPartner_artwork.graphql.ts
  src/v2/__generated__/ArtworkDetailsQuery.graphql.ts
  src/v2/__generated__/ArtworkDetails_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkRelatedArtistsPaginationQuery.graphql.ts
  src/v2/__generated__/ArtworkSidebarArtists_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarArtists_artwork.graphql.ts
  src/v2/__generated__/ArtworkSidebarQuery.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/exampleRoutes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Squash On Green

#8157 FX-3135 feat: fair organizer dedicated articles page
  cypress/integration/fairOrganizer.spec.ts
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx
  src/v2/Apps/Fair/Components/__tests__/FairEditorialItem.jest.tsx
  src/v2/Apps/FairOrginizer/Components/DedicatedArticlesBreadcrumbs.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerArticle.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerLatestArticles.tsx
  src/v2/Apps/FairOrginizer/Components/__tests__/DedicatedArticlesBreadcrumbs.jest.tsx
  src/v2/Apps/FairOrginizer/Components/__tests__/FairOrganizerLatestArticles.jest.tsx
  src/v2/Apps/FairOrginizer/Routes/FairOrganizerDedicatedArticles.tsx
  src/v2/Apps/FairOrginizer/Routes/FairOrganizerDedicatedArticlesQuery.tsx
  src/v2/Apps/FairOrginizer/Routes/__tests__/FairOrganizerDedicatedArticles.jest.tsx
  src/v2/Apps/FairOrginizer/fairOrganizerRoutes.tsx
  src/v2/__generated__/DedicatedArticlesBreadcrumbs_Test_Query.graphql.ts
  src/v2/__generated__/DedicatedArticlesBreadcrumbs_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticlesQuery.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticles_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerLatestArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerLatestArticles_fairOrganizer.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerDedicatedArticles_Query.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
Labels: Jira Synced

#8191 chore: adds restricted imports eslint config
  .eslintrc.js
  cypress/integration/artist.spec.js
Labels: Squash On Green

#8152 Migrate payments app to palette v3
  src/v2/Apps/Auction/Routes/__tests__/ConfirmBid.jest.tsx
  src/v2/Apps/Auction/Routes/__tests__/Register.jest.tsx
  src/v2/Apps/Order/Components/CreditCardDetails.tsx
  src/v2/Apps/Order/Components/CreditCardInput.tsx
  src/v2/Apps/Order/Components/__tests__/CreditCardInput.jest.tsx
  src/v2/Apps/Payment/Components/PaymentSection.tsx
  src/v2/Apps/Payment/paymentRoutes.tsx
  src/v2/Components/Address/AddressModalFields.tsx
  src/v2/Components/Mixins.tsx
  src/v2/Components/Payment/PaymentModal.tsx
  src/v2/Components/Payment/SavedCreditCards.tsx
  src/v2/Components/UserSettings/UserSettingsTabs.tsx
Labels: Jira Synced

#8196 fix(unsubscribe): clears up logic when presenting opt out form
  src/v2/Apps/Unsubscribe/UnsubscribeApp.tsx
  src/v2/Apps/Unsubscribe/__tests__/UnsubscribeApp.jest.tsx
Labels: Squash On Green

#8194 Deploy
  .env.example
  .env.oss
  .eslintrc.js
  cypress/integration/about.spec.ts
  cypress/integration/article.spec.ts
  cypress/integration/articles.spec.ts
  cypress/integration/artist.spec.js
  cypress/integration/auctions.spec.ts
  cypress/integration/collect.spec.js
  cypress/integration/contact.spec.ts
  cypress/integration/gallery.spec.ts
  cypress/integration/institution.spec.ts
  cypress/integration/institutions.spec.ts
  cypress/integration/jsonPage.spec.ts
  cypress/integration/shows.spec.ts
  cypress/integration/viewingRooms.spec.ts
  package.json
  src/config.ts
  src/desktop/apps/articles/client/team_channel.coffee
  src/v2/Apps/Auction/Routes/__tests__/ConfirmBid.jest.tsx
  src/v2/Apps/Auction/Routes/__tests__/Register.jest.tsx
  src/v2/Apps/Order/Components/CreditCardDetails.tsx
  src/v2/Apps/Order/Components/CreditCardInput.tsx
  src/v2/Apps/Order/Components/__tests__/CreditCardInput.jest.tsx
  src/v2/Apps/Payment/Components/PaymentSection.tsx
  src/v2/Apps/Payment/paymentRoutes.tsx
  src/v2/Apps/Unsubscribe/UnsubscribeApp.tsx
  src/v2/Apps/Unsubscribe/__tests__/UnsubscribeApp.jest.tsx
  src/v2/Components/Address/AddressModalFields.tsx
  src/v2/Components/Mixins.tsx
  src/v2/Components/Payment/PaymentModal.tsx
  src/v2/Components/Payment/SavedCreditCards.tsx
  src/v2/Components/UserSettings/UserSettingsTabs.tsx
  yarn.lock
Labels: Jira Synced

#8197 lib: Bump reaction
  package.json
  yarn.lock
Labels: Merge On Green

#8180 feature: Palette Charts
  package.json
  src/v2/Apps/Artwork/Components/PricingContext.tsx
  src/v2/Apps/Artwork/Components/__tests__/PricingContext.jest.tsx
  yarn.lock
Labels: Merge On Green

#8189 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8201 fix(FX-3189): Auction timer
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeader.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/__tests__/FairOrganizerHeader.jest.tsx
  src/v2/Components/Timer.tsx
  src/v2/Utils/Hooks/useTimer.tsx
Labels: Jira Synced

#8199 Deploy
  data/schema.graphql
  package.json
  src/v2/Apps/Artwork/Components/PricingContext.tsx
  src/v2/Apps/Artwork/Components/__tests__/PricingContext.jest.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeader.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/__tests__/FairOrganizerHeader.jest.tsx
  src/v2/Components/Timer.tsx
  src/v2/Utils/Hooks/useTimer.tsx
  webpack/envs/clientDevelopmentConfig.js
  webpack/envs/clientPlugins.js
  webpack/envs/clientProductionConfig.js
  yarn.lock
Labels: Jira Synced

#8202 GRO-405: Update artsy.net/auction-partnerships/ page
  src/desktop/apps/partnerships/templates/auction_sections.jade
  src/desktop/apps/partnerships/test/templates.test.js
Labels: Jira Synced

#8204 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8207 chore: Lodash Lockfile
  yarn.lock
Labels: Merge On Green

#8208 Revert Lodash Changes
  package.json
  src/desktop/components/split_test/setup.coffee
  src/desktop/components/split_test/split_test.coffee
  src/lib/cache.js
  src/lib/metaphysics2.coffee
  webpack/envs/clientPlugins.js
  webpack/envs/clientProductionConfig.js
  webpack/envs/commonEnv.js
  webpack/envs/commonLoaders.js
  yarn.lock
Labels: Merge On Green

#8188 feat(FX-3132): Added link to the fair page on fair organizer page, show 404 when there is no profile
  cypress/integration/partnerProfile.spec.js
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeader.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/__tests__/FairOrganizerHeader.jest.tsx
  src/v2/Apps/FairOrginizer/fairOrganizerRoutes.tsx
  src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerHeader_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerHeader_fairOrganizer.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
Labels: Jira Synced

#8220 feat: Disable search box for marketing page GRO-485
  src/desktop/apps/articles/templates/meta/team_channel.jade
Labels: Merge On Green

#8203 feat(FX-3136): Add fair organizer redirect
  src/config.ts
  src/desktop/apps/fair_organizer_redirect/fairOrganizerRedirectionMiddleware.ts
  src/desktop/apps/fair_organizer_redirect/index.ts
  src/desktop/index.ts
  src/lib/setup_sharify.js
  src/typings/sharify.d.ts
Labels: Jira Synced

#8221 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8227 fix(viewing-room): fixes mobile image header
  src/v2/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
Labels: Squash On Green

#8228 feature: Enable Lodash Currying
  webpack/envs/clientPlugins.js
Labels: Squash On Green

#8229 fix(types): adds types for lodash-webpack-plugin
  package.json
  webpack/envs/clientPlugins.js
  yarn.lock
Labels: Squash On Green

#8230 fix: Dont render Zendesk on inquiry artwork
  src/v2/Apps/Artwork/Components/ArtworkMeta.tsx
  src/v2/__generated__/ArtworkMeta_artwork.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Squash On Green

#8234 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8192 feat(FX-3077): exhibitors tab
  src/config.ts
  src/lib/setup_sharify.js
  src/typings/sharify.d.ts
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorGroupPlaceholder.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorsGroup.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/index.ts
  src/v2/Apps/Fair/Components/__tests__/FairExhibitorsGroup.jest.tsx
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.ts
  src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
  src/v2/Apps/Fair/fairRoutes.tsx
  src/v2/__generated__/FairExhibitorCard_partner.graphql.ts
  src/v2/__generated__/FairExhibitorsGroup_exhibitorsGroup.graphql.ts
  src/v2/__generated__/FairExhibitors_Test_Query.graphql.ts
  src/v2/__generated__/FairExhibitors_fair.graphql.ts
  src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
Labels: Jira Synced

#8239 fix(consign): fixes render mismatch
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/SoldRecently.tsx
Labels: Squash On Green

#8242 GRO-469: Updated Trending Lots to remove closed lots
  src/v2/Apps/Auctions/Components/TrendingLots/TrendingLots.tsx
  src/v2/Apps/Auctions/Components/TrendingLots/__tests__/TrendingLots.jest.tsx
  src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts
  src/v2/__generated__/TrendingLots_Test_Query.graphql.ts
  src/v2/__generated__/TrendingLots_viewer.graphql.ts
  src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
Labels: Jira Synced

#8244 fix(FX-3207): align carousel items on fair organizer page
  src/v2/Apps/FairOrginizer/Components/FairOrganizerPastEventsRail.tsx
Labels: Jira Synced

#8214 feat(FX-3158): Fair exhibitors A-Z navigation
  src/v2/Apps/Fair/Components/ExhibitorsLetterNav.tsx
  src/v2/Apps/Fair/Components/__tests__/ExhibitorsLetterNav.jest.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx
  src/v2/__generated__/ExhibitorsLetterNav_Test_Query.graphql.ts
  src/v2/__generated__/ExhibitorsLetterNav_fair.graphql.ts
  src/v2/__generated__/FairExhibitors_Test_Query.graphql.ts
  src/v2/__generated__/FairExhibitors_fair.graphql.ts
  src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
Labels: Jira Synced

#8248 GRO-469: Updated Standout Lots with logic to exclude bidding closed lots
  src/v2/Apps/Auctions/Components/StandoutLots/StandoutLots.tsx
  src/v2/Apps/Auctions/Components/StandoutLots/__tests__/StandoutLots.jest.tsx
  src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts
  src/v2/__generated__/StandoutLots_Test_Query.graphql.ts
  src/v2/__generated__/StandoutLots_viewer.graphql.ts
  src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
Labels: Jira Synced

#8250 GRO-466: Seeing Spacing Issues with Auction Rails
  src/v2/Apps/Auctions/Routes/CurrentAuctions.tsx
  src/v2/Apps/Auctions/Routes/PastAuctions.tsx
  src/v2/Apps/Auctions/Routes/UpcomingAuctions.tsx
Labels: Jira Synced

#8252 fix(headers): limits full-bleed headers to 50vh (sans nav)
  src/v2/Apps/Partner/Components/PartnerHeader/PartnerHeaderImage.tsx
  src/v2/Components/FullBleedHeader.tsx
Labels: Squash On Green

#8253 feature: Node 14
  packages/publish/package.json
Labels: Merge On Green

#8256 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8255 Deploy
  .circleci/config.yml
  .nvmrc
  Dockerfile
  data/schema.graphql
  packages/publish/package.json
  src/v2/Apps/Partner/Components/PartnerHeader/PartnerHeaderImage.tsx
  src/v2/Apps/ViewingRoom/Components/ViewingRoomsFeaturedRail.tsx
  src/v2/Components/Authentication/Desktop/LoginForm.tsx
  src/v2/Components/FullBleedHeader.tsx
Labels: Jira Synced

#8245 feat(FX-3208): hide empty about section
  src/v2/Apps/Fair/Components/FairOverview/FairAbout.tsx
  src/v2/Apps/Fair/Components/FairOverview/FairOverview.tsx
  src/v2/__generated__/FairAbout_fair.graphql.ts
  src/v2/__generated__/FairOverview_Test_Query.graphql.ts
  src/v2/__generated__/FairOverview_fair.graphql.ts
  src/v2/__generated__/fairRoutes_FairOverviewQuery.graphql.ts
Labels: Jira Synced

#8260 fix(headers): sets a minimum height on full-bleed header
  src/v2/Components/FullBleedHeader.tsx
Labels: Squash On Green

#8258 feat(FX-3118): make fair tabs sticky
  src/v2/Apps/Fair/Components/ExhibitorsLetterNav.tsx
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/Apps/Fair/Routes/FairBooths.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Components/Sticky/Sticky.tsx
Labels: Jira Synced

#8266 Revert "feat(FX-3118): make fair tabs sticky"
  src/v2/Apps/Fair/Components/ExhibitorsLetterNav.tsx
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/Apps/Fair/Routes/FairBooths.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Components/Sticky/Sticky.tsx
Labels: Jira Synced

#8267 chore(stories): adds story for handling sticky within app container
  package.json
  src/v2/Components/Sticky/Sticky.story.tsx
  yarn.lock
Labels: Squash On Green

#8269 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8289 feat(FX-3222): move fair booths to overview tab
  src/v2/Apps/Fair/Components/FairBooths.tsx
  src/v2/Apps/Fair/Components/FairOverview/index.ts
  src/v2/Apps/Fair/Components/__tests__/FairBooths.jest.tsx
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/Apps/Fair/Routes/FairBoothsQuery.tsx
  src/v2/Apps/Fair/Routes/FairOverview.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairOverview.jest.tsx
  src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
  src/v2/Apps/Fair/fairRoutes.tsx
  src/v2/__generated__/FairBoothsContainerQuery.graphql.ts
Labels: Jira Synced

#8298 feat(FX-3197): make all filter options Title Cased
  package.json
  src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ResultsFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
  yarn.lock
Labels: Jira Synced

#8290 feat(viewing room): redirect viewing room route /works to /artworks
  src/v2/Apps/ViewingRoom/Components/ViewingRoomTabBar.tsx
  src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
  src/v2/Apps/ViewingRoom/viewingRoomRoutes.tsx
Labels: Jira Synced

#8300 fix(fair organizer): update articles sort order to PUBLISHED_AT_DESC rework
  src/v2/Apps/FairOrginizer/Routes/FairOrganizerDedicatedArticles.tsx
  src/v2/__generated__/FairOrganizerDedicatedArticlesQuery.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticles_fairOrganizer.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerDedicatedArticles_Query.graphql.ts
Labels: Jira Synced

#8263 Convert purchases app to palette v3
  src/v2/Apps/Purchase/Components/OrderRow.tsx
  src/v2/Apps/Purchase/Components/PurchaseHistory.tsx
  src/v2/Apps/Purchase/purchaseRoutes.tsx
Labels: Jira Synced

#8254 feat: Add price in USD to auction results list item
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/v2/__generated__/ArtistAuctionResultItem_auctionResult.graphql.ts
  src/v2/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/v2/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
  src/v2/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
Labels: Jira Synced

#8303 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8306 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green

#8308 fix(fair organizer): sort fairs by -start_at to determine upcoming show
  src/v2/Apps/FairOrginizer/Components/DedicatedArticlesBreadcrumbs.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeader.tsx
  src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx
  src/v2/__generated__/DedicatedArticlesBreadcrumbs_Test_Query.graphql.ts
  src/v2/__generated__/DedicatedArticlesBreadcrumbs_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerApp_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticlesQuery.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerHeader_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerHeader_fairOrganizer.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerDedicatedArticles_Query.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#8304 Deploy
  data/schema.graphql
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/v2/Apps/FairOrginizer/Components/DedicatedArticlesBreadcrumbs.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeader.tsx
  src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx
  src/v2/Apps/ViewingRoom/viewingRoomRoutes.tsx
  src/v2/__generated__/ArtistAuctionResultItem_auctionResult.graphql.ts
  src/v2/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/v2/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
  src/v2/__generated__/DedicatedArticlesBreadcrumbs_Test_Query.graphql.ts
  src/v2/__generated__/DedicatedArticlesBreadcrumbs_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerApp_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticlesQuery.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerHeader_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerHeader_fairOrganizer.graphql.ts
  src/v2/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerDedicatedArticles_Query.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
Labels: Jira Synced

#8309 fix: Always clear search term after navigating away from search results
  src/v2/Components/Search/SearchBar.tsx
Labels: Jira Synced

#8311 fix(FX-3236): update timers on the fair page (remove duplicate, show "closed" state)
  src/v2/Apps/Fair/Components/FairHeader/FairHeader.tsx
  src/v2/Apps/Fair/Components/FairOverview/FairAbout.tsx
  src/v2/Apps/Fair/Components/FairOverview/FairTimer.tsx
  src/v2/Apps/Fair/Components/__tests__/FairHeader.jest.tsx
  src/v2/Apps/Fair/Components/__tests__/FairTimer.jest.tsx
  src/v2/__generated__/FairAbout_fair.graphql.ts
  src/v2/__generated__/FairApp_Test_Query.graphql.ts
  src/v2/__generated__/FairHeader_Test_Query.graphql.ts
  src/v2/__generated__/FairHeader_fair.graphql.ts
  src/v2/__generated__/FairOverview_Test_Query.graphql.ts
  src/v2/__generated__/FairTimer_Test_Query.graphql.ts
  src/v2/__generated__/fairRoutes_FairOverviewQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#8313 Deploy
  src/v2/Apps/Fair/Components/FairHeader/FairHeader.tsx
  src/v2/Apps/Fair/Components/FairOverview/FairAbout.tsx
  src/v2/Apps/Fair/Components/FairOverview/FairTimer.tsx
  src/v2/Apps/Fair/Components/__tests__/FairHeader.jest.tsx
  src/v2/Apps/Fair/Components/__tests__/FairTimer.jest.tsx
  src/v2/__generated__/FairAbout_fair.graphql.ts
  src/v2/__generated__/FairApp_Test_Query.graphql.ts
  src/v2/__generated__/FairHeader_Test_Query.graphql.ts
  src/v2/__generated__/FairHeader_fair.graphql.ts
  src/v2/__generated__/FairOverview_Test_Query.graphql.ts
  src/v2/__generated__/FairTimer_Test_Query.graphql.ts
  src/v2/__generated__/fairRoutes_FairOverviewQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairQuery.graphql.ts
Labels: Jira Synced

#8322 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green
