Repository artsy/force, pull requests merged in 2022-04, with the labels that each got.

#9783 feat: zoom in on image when hovering on artwork grid item
  src/v2/Components/Artwork/ArtworkImage.tsx
  src/v2/Components/Artwork/GridItem.tsx
  src/v2/Components/MagnifyImage.tsx
Labels: Jira Synced

#9796 chore: remove `ENABLE_YOUR_ALERTS_PAGE` flag
  .secrets.baseline
  src/config.ts
  src/lib/setup_sharify.js
  src/typings/sharify.d.ts
  src/v2/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/v2/Components/NavBar/Menus/__tests__/NavBarUserMenu.jest.tsx
  src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
  src/v2/System/Server/sharifyHelpers.ts
Labels: Squash On Green

#9685 refactor: pill entity
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Components/SavedSearchAlert/Components/SavedSearchAlertArtworkGridFilterPills.tsx
  src/v2/Components/SavedSearchAlert/Components/SavedSearchAlertPills.tsx
  src/v2/Components/SavedSearchAlert/Components/__tests__/SavedSearchAlertPills.jest.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/v2/Components/SavedSearchAlert/Utils/extractPills.ts
  src/v2/Components/SavedSearchAlert/__tests__/extractPills.jest.ts
  src/v2/Components/SavedSearchAlert/types.ts
Labels: Squash On Green

#9789 refactor: useFeatureVariant
  src/v2/Components/ArtworkFilter/ArtworkFilters/index.tsx
  src/v2/System/__tests__/useFeatureFlag.jest.tsx
  src/v2/System/useFeatureFlag.tsx
Labels: Jira Synced

#9776 feat(NX-3052): Modify the UI of the edition selection modal
  src/v2/Apps/Conversation/Components/CollapsibleArtworkDetails.tsx
  src/v2/Apps/Conversation/Components/ConfirmArtworkModal.tsx
  src/v2/Apps/Conversation/Components/EditionSelectBox.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConfirmArtwork.jest.tsx
Labels: Jira Synced

#9802 fix: replace data-test tag with the old one
  src/v2/Components/Artwork/SaveButton/NewSaveButton.tsx
Labels: Jira Synced, Squash On Green

#9804 chore(images): adds compression taste-test story
  src/v2/Apps/Partner/Components/__tests__/PartnerViewingRooms/ViewingRoomCard.jest.tsx
  src/v2/Components/__stories__/Image.story.tsx
  src/v2/Components/__tests__/MetaTags.jest.tsx
  src/v2/Utils/resizer.ts
Labels: Merge On Green

#9805 chore(GRO-902): Copy tweak [ci skip]
  src/v2/Apps/Preferences/PreferencesApp.tsx
Labels: Jira Synced

#9680 [GRO-834]: add analytics click event to Home Trove Rail
  src/v2/Apps/Home/Components/HomeTroveArtworksRail.tsx
  src/v2/Apps/Home/__tests__/HomeTroveArtworksRail.jest.tsx
Labels: Jira Synced

#9807 feat(GRO-736): Pages
  cypress/integration/page.spec.ts
  src/desktop/apps/page/index.coffee
  src/desktop/apps/page/index.styl
  src/desktop/apps/page/meta/default.jade
  src/desktop/apps/page/meta/press.jade
  src/desktop/apps/page/meta/privacy.jade
  src/desktop/apps/page/meta/security.jade
  src/desktop/apps/page/meta/terms.jade
  src/desktop/apps/page/routes.coffee
  src/desktop/apps/page/template.jade
  src/desktop/apps/page/test/meta.test.js
  src/desktop/apps/page/test/routes.test.js
  src/desktop/assets/misc.styl
  src/desktop/index.ts
  src/lib/middleware/hardcodedRedirects.ts
  src/v2/Apps/Article/Components/ArticleHTML.tsx
  src/v2/Apps/Auction/Routes/AuctionFAQRoute.tsx
  src/v2/Apps/Page/Components/PageHTML.tsx
  src/v2/Apps/Page/PageApp.tsx
  src/v2/Apps/Page/__tests__/PageApp.jest.tsx
  src/v2/Apps/Page/pageRoutes.tsx
  src/v2/Apps/StaticPage/StaticPageApp.tsx
  src/v2/Apps/StaticPage/staticPageRoutes.tsx
  src/v2/Utils/toStyle.ts
  src/v2/__generated__/PageApp_Test_Query.graphql.ts
  src/v2/__generated__/PageApp_page.graphql.ts
  src/v2/__generated__/pageRoutes_PageQuery.graphql.ts
  src/v2/routes.tsx
Labels: Jira Synced

#9809 chore: page consistency
  src/v2/Apps/MeetTheSpecialists/MeetTheSpecialistsApp.tsx
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
  src/v2/Components/CCPARequest.tsx
  src/v2/Components/Footer/Footer.tsx
  src/v2/Components/Footer/__tests__/Footer.jest.tsx
  src/v2/__generated__/CCPARequestMutation.graphql.ts
Labels: Merge On Green

#9772 feat(NX-3053): Only display edition set selection modal when the artwork is non-unique
  src/v2/Apps/Conversation/Components/ConfirmArtworkButton.tsx
  src/v2/Apps/Conversation/Components/ConfirmArtworkModal.tsx
  src/v2/Apps/Conversation/Components/ConversationCTA.tsx
  src/v2/Apps/Conversation/Components/MakeOfferOnInquiryButton.tsx
  src/v2/Apps/Conversation/Components/OpenInquiryModalCTA.tsx
  src/v2/Apps/Conversation/Components/__tests__/MakeOfferOnInquiryButton.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/OpenInquiryModalCTA.jest.tsx
  src/v2/__generated__/ConversationCTA_Test_Query.graphql.ts
  src/v2/__generated__/ConversationCTA_conversation.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/ConversationPagination_Test_Query.graphql.ts
  src/v2/__generated__/MakeOfferOnInquiryButton_Test_Query.graphql.ts
  src/v2/__generated__/MakeOfferOnInquiryButton_conversation.graphql.ts
  src/v2/__generated__/OpenInquiryModalCTA_Test_Query.graphql.ts
  src/v2/__generated__/OpenInquiryModalCTA_conversation.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Jira Synced

#9813 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/CreateConsignSubmissionMutation.graphql.ts
  src/v2/__generated__/UpdateConsignSubmissionMutation.graphql.ts
Labels: Squash On Green

#9814 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9774 feat(FX-3832): add sort control to alert management UI
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/v2/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
  src/v2/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
  src/v2/__generated__/SavedSearchAlertsApp_me.graphql.ts
  src/v2/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts
  src/v2/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts
Labels: Jira Synced

#9806 fix: remove Authy reference in favour of Google Authenticator
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
Labels: Jira Synced

#9819 feat(GRO-943): /jobs2
  src/v2/Apps/Jobs/JobsApp.tsx
  src/v2/Apps/Jobs/jobsRoutes.tsx
  src/v2/Apps/Page/pageRoutes.tsx
  src/v2/Components/Cells/CellArticle.tsx
  src/v2/__generated__/JobsApp_viewer.graphql.ts
  src/v2/__generated__/jobsRoutes_JobsQuery.graphql.ts
  src/v2/routes.tsx
Labels: Jira Synced

#9810 fix: dont reask for credit card info during bidding
  src/v2/Apps/Auction/Routes/Bid/AuctionBidRoute.tsx
  src/v2/Apps/Auction/Routes/Bid/__tests__/AuctionBidRoute.jest.tsx
Labels: Jira Synced

#9518 [GRO-739] Auction-partnerships2 palette v3 migration
  src/v2/Apps/_AuctionPartnerships2/AuctionPartnershipsApp.tsx
Labels: Jira Synced, Squash On Green

#9825 chore: update dependabot and renovate assignee
  .github/dependabot.yml
  renovate.json
Labels: Jira Synced

#9826 refactor(buyer-guarantee): cleans up buyer-guarantee page
  src/v2/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
  src/v2/Apps/BuyerGuarantee/Components/BuyerGuaranteeIcons.tsx
  src/v2/Apps/BuyerGuarantee/Components/BuyerGuaranteeMeta.tsx
  src/v2/Apps/BuyerGuarantee/Components/BuyerGuaranteeTables.tsx
  src/v2/Apps/BuyerGuarantee/Components/Feature.tsx
  src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
  src/v2/Apps/Order/Components/PriceOptions.tsx
  src/v2/Apps/Settings/Routes/Saves/Components/SettingsSavesArtworks.tsx
  src/v2/Apps/Shows/Routes/ShowsCity.tsx
  src/v2/Apps/ViewingRoom/Routes/Statement/Components/ViewWorksButton.tsx
  src/v2/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorksArtwork.tsx
  src/v2/Utils/Hooks/useScrollTo.ts
Labels: Merge On Green

#9827 fix: fixes mocks
  src/v2/Apps/Settings/Routes/Saves/Components/__tests__/SettingsSavesArtworks.jest.tsx
  src/v2/Apps/Shows/Routes/__tests__/ShowsCity.jest.tsx
Labels: Merge On Green

#9817 fix: sanitising untrusted redirect url
  src/v2/Apps/Authentication/Server/checkForRedirect.ts
  src/v2/Components/Authentication/FormSwitcher.tsx
Labels: Jira Synced

#9818 feat(FX-3864): Replace request for marketingHubCollections with marketingCollections + list of slugs
  src/desktop/components/react/stitch_components/CollectionsHubsHomepageNav.tsx
  src/desktop/components/react/stitch_components/index.tsx
  src/v2/Apps/Collect/Routes/Collect/index.tsx
  src/v2/Apps/Collect/collectRoutes.tsx
  src/v2/Components/CollectionsHubsHomepageNav.tsx
  src/v2/Components/CollectionsHubsNav.tsx
  src/v2/__generated__/Collect_marketingCollections.graphql.ts
  src/v2/__generated__/Collect_marketingHubCollections.graphql.ts
  src/v2/__generated__/CollectionsHubsNav_marketingCollections.graphql.ts
  src/v2/__generated__/CollectionsHubsNav_marketingHubCollections.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
Labels: Jira Synced

#9815 feat: display "Create Alert" button for sold artworks
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlertButton.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/CreateArtworkAlertSection.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/v2/Components/SavedSearchAlert/Components/SavedSearchAlertArtworkGridFilterPills.tsx
  src/v2/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButton.tsx
  src/v2/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButtonContainer.tsx
  src/v2/Components/SavedSearchAlert/Components/__tests__/SavedSearchCreateAlertButtonContainer.jest.tsx
  src/v2/Components/SavedSearchAlert/Utils/__tests__/getAttributionClassValueByLabel.jest.ts
  src/v2/Components/SavedSearchAlert/Utils/getAttributionClassValueByLabel.ts
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarCommercial2_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarCommercial_artwork.graphql.ts
  src/v2/__generated__/ArtworkSidebarCreateAlertButton_artwork.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#9824 docs: unleash a/b test
  docs/unleash_a-b_testing.md
Labels: Jira Synced

#9832 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9831 feat(contact): cleans up page; promotes from /contact2 => /contact; deletes old app
  src/desktop/apps/contact/client/index.coffee
  src/desktop/apps/contact/index.coffee
  src/desktop/apps/contact/routes.coffee
  src/desktop/apps/contact/stylesheets/index.styl
  src/desktop/apps/contact/templates/index.jade
  src/desktop/apps/contact/test/fixture.json
  src/desktop/apps/contact/test/template.test.js
  src/desktop/assets/misc.styl
  src/desktop/assets/misc.ts
  src/desktop/index.ts
  src/v2/Apps/Contact/ContactApp.tsx
  src/v2/Apps/Contact/contactRoutes.tsx
  src/v2/Apps/_Contact2/ContactApp.tsx
  src/v2/routes.tsx
Labels: Merge On Green

#9841 chore(instant-page): Remove INSTANT_PAGE
  .secrets.baseline
  src/config.ts
  src/desktop/components/main_layout/templates/instant-page.jade
  src/desktop/components/main_layout/templates/scripts.jade
  src/lib/setup_sharify.js
Labels: Merge On Green

#9844 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9845 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9835 chore: update title size for "Your Alerts" page
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx
Labels: Jira Synced

#9773 [SWA-297]: submissionId param
  src/v2/Apps/Authentication/Utils/helpers.ts
  src/v2/Apps/Consign/Hooks/__tests__/useConnectUserToSubmission.jest.ts
  src/v2/Apps/Consign/Hooks/useConnectUserToSubmission.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Mutations/addUserToSubmission.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Mutations/index.ts
  src/v2/Utils/Hooks/useAuthIntent/index.ts
  src/v2/__generated__/addUserToSubmissionMutation.graphql.ts
Labels: Jira Synced

#9847 feat(SWA-331): SWA landing page redesign
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/ConsignMeta.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/PromoSpace.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/MarketingLandingApp.tsx
  src/v2/Apps/Consign/consignRoutes.tsx
Labels: Jira Synced

#9849 chore: remove `getAttributionClassValueByLabel` helper
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlertButton.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/CreateArtworkAlertSection.jest.tsx
  src/v2/Components/SavedSearchAlert/Utils/__tests__/getAttributionClassValueByLabel.jest.ts
  src/v2/Components/SavedSearchAlert/Utils/getAttributionClassValueByLabel.ts
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarCommercial2_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarCreateAlertButton_artwork.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/CreateArtworkAlertSection_Test_Query.graphql.ts
  src/v2/__generated__/CreateArtworkAlertSection_artwork.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Squash On Green

#9851 fix: Add scope to Google strategy to fix nil name sign ups
  src/lib/passport/lib/app/lifecycle.js
Labels: Jira Synced

#9853 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9852 chore(mntn pixel): add pixel to gallery inquiry modal
  src/v2/Apps/Components/AppShell.tsx
  src/v2/Components/Authentication/Views/SignUpForm.tsx
  src/v2/Components/Inquiry/useInquiry.tsx
  src/v2/Components/MNTNPixels.tsx
  src/v2/index.ejs
Labels: Jira Synced

#9854 refactor(cells): uses article cell on fair and fair organizer pages
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItemLink.tsx
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialRailArticles.tsx
  src/v2/Apps/Fair/Components/FairEditorial/__tests__/FairEditorialRailArticles.jest.tsx
  src/v2/Apps/Fair/Components/__tests__/FairEditorialItem.jest.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairOverview.jest.tsx
  src/v2/Apps/FairOrginizer/Components/DedicatedArticlesBreadcrumbs.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerArticle.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeader.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerLatestArticles.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerPastEventsRail.tsx
  src/v2/Apps/FairOrginizer/Components/__tests__/DedicatedArticlesBreadcrumbs.jest.tsx
  src/v2/Apps/FairOrginizer/Components/__tests__/FairOrganizerLatestArticles.jest.tsx
  src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx
  src/v2/Apps/FairOrginizer/Routes/FairOrganizerDedicatedArticles.tsx
  src/v2/Apps/FairOrginizer/Routes/__tests__/FairOrganizerDedicatedArticles.jest.tsx
  src/v2/__generated__/FairEditorialItemLink_article.graphql.ts
  src/v2/__generated__/FairEditorialItem_Test_Query.graphql.ts
  src/v2/__generated__/FairEditorialItem_article.graphql.ts
  src/v2/__generated__/FairEditorialRailArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairEditorialRailArticles_fair.graphql.ts
  src/v2/__generated__/FairEditorial_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticlesQuery.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticles_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerLatestArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerLatestArticles_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOverview_Test_Query.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerDedicatedArticles_Query.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairOverviewQuery.graphql.ts
Labels: Merge On Green

#9856 fix(meet-the-specialists): fixes images
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Merge On Green

#9848 chore(FX-3882): update offsets for updated price filter (with histogram)
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilterNew.tsx
Labels: Jira Synced

#9816 feat(FX-3817) Create Artwork Alert when bidding closed
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBiddingClosedMessage.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/v2/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.ts
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarAuctionInfoPollingQuery.graphql.ts
  src/v2/__generated__/ArtworkSidebarBiddingClosedMessage_artwork.graphql.ts
  src/v2/__generated__/ArtworkSidebarCurrentBidInfo_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarCurrentBidInfo_artwork.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#9829 feat(SWA-303): postal code
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
  src/v2/Components/LocationAutocompleteInput.tsx
  src/v2/Components/__tests__/LocationAutocompleteInput.jest.tsx
  src/v2/__generated__/ArtworkDetails_SubmissionFlowTest_Query.graphql.ts
  src/v2/__generated__/ArtworkDetails_submission.graphql.ts
  src/v2/__generated__/consignRoutes_artworkDetailsQuery.graphql.ts
  src/v2/__generated__/consignRoutes_contactInformationQuery.graphql.ts
  src/v2/__generated__/consignRoutes_uploadPhotosQuery.graphql.ts
  src/v2/__generated__/redirects_submission.graphql.ts
Labels: Jira Synced, Squash On Green

#9860 feat(FX-3889): pass Medium pill to saved search alerts on artwork page
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlertButton.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/CreateArtworkAlertSection.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.ts
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarAuctionInfoPollingQuery.graphql.ts
  src/v2/__generated__/ArtworkSidebarCommercial2_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarCreateAlertButton_artwork.graphql.ts
  src/v2/__generated__/ArtworkSidebarCurrentBidInfo_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/CreateArtworkAlertSection_Test_Query.graphql.ts
  src/v2/__generated__/CreateArtworkAlertSection_artwork.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#9855 Deploy
  .circleci/config.yml
  package.json
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBiddingClosedMessage.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/Reply.tsx
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItemLink.tsx
  src/v2/Apps/Fair/Components/FairEditorial/FairEditorialRailArticles.tsx
  src/v2/Apps/Fair/Components/FairEditorial/__tests__/FairEditorialRailArticles.jest.tsx
  src/v2/Apps/Fair/Components/__tests__/FairEditorialItem.jest.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairOverview.jest.tsx
  src/v2/Apps/FairOrginizer/Components/DedicatedArticlesBreadcrumbs.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerArticle.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeader.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerLatestArticles.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerPastEventsRail.tsx
  src/v2/Apps/FairOrginizer/Components/__tests__/DedicatedArticlesBreadcrumbs.jest.tsx
  src/v2/Apps/FairOrginizer/Components/__tests__/FairOrganizerLatestArticles.jest.tsx
  src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx
  src/v2/Apps/FairOrginizer/Routes/FairOrganizerDedicatedArticles.tsx
  src/v2/Apps/FairOrginizer/Routes/__tests__/FairOrganizerDedicatedArticles.jest.tsx
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
  src/v2/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.ts
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilterNew.tsx
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarAuctionInfoPollingQuery.graphql.ts
  src/v2/__generated__/ArtworkSidebarBiddingClosedMessage_artwork.graphql.ts
  src/v2/__generated__/ArtworkSidebarCurrentBidInfo_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarCurrentBidInfo_artwork.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/ConversationPagination_Test_Query.graphql.ts
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/FairEditorialItemLink_article.graphql.ts
  src/v2/__generated__/FairEditorialItem_Test_Query.graphql.ts
  src/v2/__generated__/FairEditorialItem_article.graphql.ts
  src/v2/__generated__/FairEditorialRailArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairEditorialRailArticles_fair.graphql.ts
  src/v2/__generated__/FairEditorial_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticlesQuery.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticles_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerLatestArticles_Test_Query.graphql.ts
  src/v2/__generated__/FairOrganizerLatestArticles_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOverview_Test_Query.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerDedicatedArticles_Query.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairOverviewQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#9840 [PX-4946] Start using new processWithArtsyShippingDomestic fields in checkout flow
  src/v2/Apps/Order/Routes/Shipping/index.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/__generated__/ShippingTestQuery.graphql.ts
  src/v2/__generated__/Shipping_order.graphql.ts
  src/v2/__generated__/orderRoutes_ShippingQuery.graphql.ts
Labels: Jira Synced

#9872 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9871 [GRO-944] universally remove subtitles from Rails at smaller screen widths
  src/v2/Components/Rail/RailHeader.tsx
Labels: Jira Synced

#9880 fix(auction): Restore old urls for older versions of Eigen
  src/v2/Apps/Auction/auctionRoutes.tsx
Labels: Squash On Green

#9881 fix(show): higher quality installation shots; top context bar consistency
  src/v2/Apps/Article/Components/ArticleSeries.tsx
  src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
  src/v2/Apps/Artwork/Components/ArtworkBanner/ArtworkBanner.tsx
  src/v2/Apps/Artwork/Components/ArtworkBanner/__tests__/ArtworkBanner.jest.tsx
  src/v2/Apps/FairOrginizer/Components/DedicatedArticlesBreadcrumbs.tsx
  src/v2/Apps/FairOrginizer/Components/__tests__/DedicatedArticlesBreadcrumbs.jest.tsx
  src/v2/Apps/Show/Components/ShowInstallShots.tsx
  src/v2/Apps/Show/Components/ShowMeta.tsx
  src/v2/Apps/Show/Components/ShowNavigationBanner.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/ShowSubApp.tsx
  src/v2/Apps/Show/__tests__/ShowMeta.jest.tsx
  src/v2/Components/TopContextBar.tsx
  src/v2/Components/__stories__/TopContextBar.story.tsx
  src/v2/__generated__/ArtistSeriesHeader_artistSeries.graphql.ts
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkBanner_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkBanner_artwork.graphql.ts
  src/v2/__generated__/DedicatedArticlesBreadcrumbs_Test_Query.graphql.ts
  src/v2/__generated__/DedicatedArticlesBreadcrumbs_fairOrganizer.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticlesQuery.graphql.ts
  src/v2/__generated__/FairOrganizerDedicatedArticles_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowInstallShots_Test_Query.graphql.ts
  src/v2/__generated__/ShowInstallShots_show.graphql.ts
  src/v2/__generated__/ShowMeta_Test_Query.graphql.ts
  src/v2/__generated__/ShowMeta_show.graphql.ts
  src/v2/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/fairOrganizerRoutes_FairOrganizerDedicatedArticles_Query.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
  src/v2/__generated__/showRoutes_ShowSubAppQuery.graphql.ts
Labels: Merge On Green

#9878 chore: bump minimist
  package.json
  yarn.lock
Labels: Jira Synced

#9889 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9846 fix: no shipping info when price on request
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Labels: Jira Synced

#9891 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/v2/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/v2/__generated__/AuctionArtworkFilterTestQuery.graphql.ts
  src/v2/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/v2/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/v2/__generated__/FairArtworksQuery.graphql.ts
  src/v2/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ShowArtworksQuery.graphql.ts
  src/v2/__generated__/TagArtworkFilterQuery.graphql.ts
  src/v2/__generated__/WorksQuery.graphql.ts
  src/v2/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
  src/v2/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/collectRoutes_CollectionQuery.graphql.ts
  src/v2/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairArtworksQuery.graphql.ts
  src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts
  src/v2/__generated__/partnerRoutes_WorksQuery.graphql.ts
  src/v2/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
  src/v2/__generated__/tagRoutes_TagQuery.graphql.ts
Labels: Squash On Green

#9683 feat: fetch alert pills for edit flow from Metaphysics
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertContext.tsx
  src/v2/Components/SavedSearchAlert/Utils/__tests__/convertLabelsToPills.jest.ts
  src/v2/Components/SavedSearchAlert/Utils/convertLabelsToPills.ts
  src/v2/__generated__/SavedSearchAlertEditFormQuery.graphql.ts
  src/v2/__generated__/SavedSearchAlertEditForm_Test_Query.graphql.ts
  src/v2/__generated__/SavedSearchAlertEditForm_me.graphql.ts
Labels: #FF

#9877 chore: update copy for timing banner for cascading auction
  src/v2/Apps/Auction/Components/AuctionDetails/SaleDetailTimer.tsx
  src/v2/Apps/Auction/Components/AuctionDetails/__tests__/SaleDetailTimer.jest.tsx
Labels: Jira Synced

#9898 chore: removes unsupported-browser app + middleware
  src/desktop/apps/unsupported_browser/index.coffee
  src/desktop/apps/unsupported_browser/index.styl
  src/desktop/apps/unsupported_browser/routes.coffee
  src/desktop/apps/unsupported_browser/template.jade
  src/desktop/apps/unsupported_browser/test/routes.test.js
  src/desktop/apps/unsupported_browser/test/template.test.js
  src/desktop/assets/misc.styl
  src/desktop/index.ts
  src/lib/middleware/__tests__/unsupportedBrowser.jest.ts
  src/lib/middleware/unsupportedBrowser.ts
  src/middleware.ts
Labels: Merge On Green

#9899 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9902 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9904 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9906 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9890 Chore: Removing Galaxy API references
  .env.oss
  .env.test
  .secrets.baseline
  src/config.ts
  src/desktop/components/typeahead/README.md
  src/lib/setup_sharify.js
Labels: Jira Synced

#9908 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9910 feat: migrates article channel 'blogs'
  .secrets.baseline
  cypress/integration/articles.spec.ts
  src/config.ts
  src/desktop/apps/article/templates/amp_mixins.jade
  src/desktop/apps/articles/client/team_channel.coffee
  src/desktop/apps/articles/index.js
  src/desktop/apps/articles/routes.ts
  src/desktop/apps/articles/stylesheets/index.styl
  src/desktop/apps/articles/stylesheets/team_channel.styl
  src/desktop/apps/articles/templates/meta/team_channel.jade
  src/desktop/apps/articles/templates/team_channel.jade
  src/desktop/apps/articles/test/client/team_channel.test.js
  src/desktop/apps/articles/test/routes.test.js
  src/desktop/assets/articles.ts
  src/desktop/components/main_layout/templates/scripts.jade
  src/desktop/components/util/parsely.coffee
  src/desktop/test/helpers/fixtures.js
  src/lib/analytics/helpers.ts
  src/lib/analytics/trackPageView.ts
  src/lib/middleware/hardcodedRedirects.ts
  src/lib/setup_sharify.js
  src/typings/global.d.ts
  src/v2/Apps/Articles/ChannelApp.tsx
  src/v2/Apps/Articles/Components/ChannelArticles.tsx
  src/v2/Apps/Articles/articlesRoutes.tsx
  src/v2/__generated__/ChannelApp_channel.graphql.ts
  src/v2/__generated__/ChannelArticlesQuery.graphql.ts
  src/v2/__generated__/ChannelArticles_channel.graphql.ts
  src/v2/__generated__/articlesRoutes_ChannelQuery.graphql.ts
Labels: Merge On Green

#9905 Deploy
  .env.oss
  .env.test
  .secrets.baseline
  cypress/integration/articles.spec.ts
  cypress/integration/auctions.spec.ts
  data/schema.graphql
  src/config.ts
  src/desktop/apps/article/templates/amp_mixins.jade
  src/desktop/apps/articles/client/team_channel.coffee
  src/desktop/apps/articles/index.js
  src/desktop/apps/articles/routes.ts
  src/desktop/apps/articles/stylesheets/index.styl
  src/desktop/apps/articles/stylesheets/team_channel.styl
  src/desktop/apps/articles/templates/meta/team_channel.jade
  src/desktop/apps/articles/templates/team_channel.jade
  src/desktop/apps/articles/test/client/team_channel.test.js
  src/desktop/apps/articles/test/routes.test.js
  src/desktop/apps/partnerships/index.coffee
  src/desktop/assets/articles.ts
  src/desktop/components/main_layout/templates/scripts.jade
  src/desktop/components/typeahead/README.md
  src/desktop/components/util/parsely.coffee
  src/desktop/test/helpers/fixtures.js
  src/lib/analytics/helpers.ts
  src/lib/analytics/trackPageView.ts
  src/lib/middleware/hardcodedRedirects.ts
  src/lib/setup_sharify.js
  src/typings/global.d.ts
  src/v2/Apps/Articles/ChannelApp.tsx
  src/v2/Apps/Articles/Components/ChannelArticles.tsx
  src/v2/Apps/Articles/articlesRoutes.tsx
  src/v2/Apps/AuctionPartnerships/AuctionPartnershipsApp.tsx
  src/v2/Apps/AuctionPartnerships/auctionPartnershipsRoutes.tsx
  src/v2/__generated__/ChannelApp_channel.graphql.ts
  src/v2/__generated__/ChannelArticlesQuery.graphql.ts
  src/v2/__generated__/ChannelArticles_channel.graphql.ts
  src/v2/__generated__/articlesRoutes_ChannelQuery.graphql.ts
  src/v2/routes.tsx
Labels: Jira Synced

#9912 ci(slack-notifications): remove practice-web
  .circleci/config.yml
Labels: Merge On Green

#9916 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9917 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9919 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9922 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9924 chore: cleanup unleash filters experiment
  docs/unleash_a-b_testing.md
  src/v2/Components/ArtworkFilter/ArtworkFilters/index.tsx
Labels: Jira Synced

#9926 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9927 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9929 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9934 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9935 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/addUserToSubmissionMutation.graphql.ts
Labels: Squash On Green

#9938 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9937 feat: converts jobs2 to use greenhouse data
  src/v2/Apps/Jobs/Components/JobLink.tsx
  src/v2/Apps/Jobs/Components/JobsFilter.tsx
  src/v2/Apps/Jobs/JobApp.tsx
  src/v2/Apps/Jobs/JobsApp.tsx
  src/v2/Apps/Jobs/jobsRoutes.tsx
  src/v2/Apps/Page/Components/PageHTML.tsx
  src/v2/__generated__/JobApp_job.graphql.ts
  src/v2/__generated__/JobLink_job.graphql.ts
  src/v2/__generated__/JobsApp_viewer.graphql.ts
  src/v2/__generated__/JobsFilter_viewer.graphql.ts
  src/v2/__generated__/addUserToSubmissionMutation.graphql.ts
  src/v2/__generated__/jobsRoutes_JobQuery.graphql.ts
  src/v2/__generated__/jobsRoutes_JobsQuery.graphql.ts
Labels: Merge On Green

#9940 fix: fill width/height for MagnifyImage container
  src/v2/Components/MagnifyImage.tsx
Labels: Squash On Green

#9941 fix: ignore touch devices for MagnifyImage component
  src/v2/Components/MagnifyImage.tsx
Labels: Merge On Green, Jira Synced

#9943 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/addUserToSubmissionMutation.graphql.ts
Labels: Squash On Green

#9945 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9873 fix(FX-3804): Incorrect behavior for Artists filter
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
Labels: Jira Synced

#9949 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9932 fix(NX-3092): constraint the height of the conversation list container
  src/v2/Apps/Conversation/Components/ConversationList.tsx
Labels: Jira Synced

#9944 Deploy
  data/schema.graphql
  docs/authentication.md
  src/v2/Apps/Conversation/Components/ConversationList.tsx
  src/v2/Apps/Order/OrderApp.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
  src/v2/__generated__/addUserToSubmissionMutation.graphql.ts
Labels: Jira Synced

#9947 feat: use latest version of artsy managed orbs, and track app version in k8s. (PLATFORM-4103)
  .circleci/config.yml
  hokusai/production.yml
  hokusai/staging.yml
Labels: Jira Synced

#9951 fix: Load price database landing page images via https
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
Labels: Jira Synced

#9900 feat(TX-255): add ACH bank debit as option to payment flow
  src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/v2/Apps/Order/Routes/Payment/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Payment.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx
  src/v2/Components/BankDebitForm/BankDebitForm.tsx
  src/v2/Components/BankDebitForm/BankDebitProvider.tsx
  src/v2/Components/BankDebitForm/Mutations/CreateBankDebitSetupForOrder.ts
  src/v2/__generated__/CreateBankDebitSetupForOrderMutation.graphql.ts
Labels: Jira Synced

#9953 Deploy
  .circleci/config.yml
  hokusai/production.yml
  hokusai/staging.yml
  package.json
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarPartnerInfo.jest.tsx
  src/v2/Apps/Artwork/__tests__/ArtworkApp.jest.tsx
  src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/v2/Apps/Order/Routes/Payment/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Payment.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx
  src/v2/Apps/Page/Components/PageHTML.tsx
  src/v2/Apps/Page/PageApp.tsx
  src/v2/Apps/Press/PressApp.tsx
  src/v2/Apps/Press/pressRoutes.tsx
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
  src/v2/Components/BankDebitForm/BankDebitForm.tsx
  src/v2/Components/BankDebitForm/BankDebitProvider.tsx
  src/v2/Components/BankDebitForm/Mutations/CreateBankDebitSetupForOrder.ts
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarPartnerInfo_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarPartnerInfo_artwork.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/CreateBankDebitSetupForOrderMutation.graphql.ts
  src/v2/__generated__/PressApp_page.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/pressRoutes_InTheMediaQuery.graphql.ts
  src/v2/__generated__/pressRoutes_PressReleasesQuery.graphql.ts
  src/v2/routes.tsx
  yarn.lock
Labels: Jira Synced

#9963 chore: removed swa unleash flag (SWA-349)
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
Labels: Jira Synced

#9964 Deploy
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
Labels: Merge On Green, Jira Synced

#9966 fix(one-trust): ensure that modal appears above one-trust
  src/v2/Apps/Components/AppShell.tsx
Labels: Merge On Green

#9954 [GRO-861] turn on query param flag for fallback artists
  src/v2/Components/FollowArtistPopover/index.tsx
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarArtists_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/FollowArtistPopoverQuery.graphql.ts
  src/v2/__generated__/FollowArtistPopover_Test_Query.graphql.ts
  src/v2/__generated__/FollowArtistPopover_artist.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#9967 Deploy
  .circleci/config.yml
  package.json
  src/v2/Apps/Components/AppShell.tsx
  src/v2/Components/FollowArtistPopover/index.tsx
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarArtists_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/FollowArtistPopoverQuery.graphql.ts
  src/v2/__generated__/FollowArtistPopover_Test_Query.graphql.ts
  src/v2/__generated__/FollowArtistPopover_artist.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#9969 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistIconicCollectionsRailQuery.graphql.ts
  src/v2/__generated__/ArtistIconicCollectionsRail_Test_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesRail_collectionGroup.graphql.ts
  src/v2/__generated__/CollectionsHubRails_linkedCollections.graphql.ts
  src/v2/__generated__/FeaturedCollectionsRails_collectionGroup.graphql.ts
  src/v2/__generated__/Header_collection.graphql.ts
  src/v2/__generated__/OtherCollectionsRail_collectionGroup.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
Labels: Squash On Green

#9955 chore:add info label for popcorn bidding
  src/v2/Components/LotTimer.tsx
  src/v2/Components/__tests__/LotTimer.jest.tsx
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/LotTimer_saleArtwork.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#9975 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistIconicCollectionsRailQuery.graphql.ts
  src/v2/__generated__/ArtistIconicCollectionsRail_Test_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesRail_collectionGroup.graphql.ts
  src/v2/__generated__/CollectionsHubRails_linkedCollections.graphql.ts
  src/v2/__generated__/FeaturedCollectionsRails_collectionGroup.graphql.ts
  src/v2/__generated__/Header_collection.graphql.ts
  src/v2/__generated__/OtherCollectionsRail_collectionGroup.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
Labels: Squash On Green

#9979 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/useAddCreditCardAndUpdateProfileMutation.graphql.ts
  src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Squash On Green

#9972 GRO-979: Add new specialists to /meet-the-specialists
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Jira Synced

#9984 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9978 chore: delete legacy a-b test code
  docs/a-b_testing.md
  src/desktop/components/split_test/index.coffee
  src/desktop/components/split_test/running_tests.coffee
  src/desktop/components/split_test/server_split_test.coffee
  src/desktop/components/split_test/setup.coffee
  src/desktop/components/split_test/splitTestMiddleware.ts
  src/desktop/components/split_test/split_test.coffee
  src/desktop/components/split_test/test/setup.test.js
  src/desktop/components/split_test/test/splitTestMiddleware.jest.ts
  src/desktop/components/split_test/test/split_test.test.js
  src/lib/analytics/helpers.ts
  src/lib/middleware/__tests__/redisPageCache.jest.ts
  src/lib/middleware/redisPageCache.ts
  src/middleware.ts
  src/v2/System/Analytics/__tests__/trackingMiddleware.jest.ts
  src/v2/System/Analytics/trackingMiddleware.ts
Labels: Jira Synced

#9987 Updating to remove second name of a specialist
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Jira Synced

#9985 chore: add fade in effect for image
  src/v2/Components/MagnifyImage.tsx
Labels: Jira Synced

#9976 feat:adds extended to a sale when the end time has been extended
  src/v2/Components/LotTimer.tsx
  src/v2/Components/__tests__/LotTimer.jest.tsx
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/LotTimer_saleArtwork.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Squash On Green, Bidding Engine

#9981 Deploy
  data/schema.graphql
  docs/a-b_testing.md
  src/desktop/components/split_test/index.coffee
  src/desktop/components/split_test/running_tests.coffee
  src/desktop/components/split_test/server_split_test.coffee
  src/desktop/components/split_test/setup.coffee
  src/desktop/components/split_test/splitTestMiddleware.ts
  src/desktop/components/split_test/split_test.coffee
  src/desktop/components/split_test/test/setup.test.js
  src/desktop/components/split_test/test/splitTestMiddleware.jest.ts
  src/desktop/components/split_test/test/split_test.test.js
  src/lib/analytics/helpers.ts
  src/lib/middleware/__tests__/redisPageCache.jest.ts
  src/lib/middleware/redisPageCache.ts
  src/middleware.ts
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/Histogram.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilterNew.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilterNew.jest.tsx
  src/v2/Components/MagnifyImage.tsx
  src/v2/System/Analytics/__tests__/trackingMiddleware.jest.ts
  src/v2/System/Analytics/trackingMiddleware.ts
Labels: Merge On Green, Jira Synced

#9974 fix(FX-3924): double horizontal line on artwork page
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/v2/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
  src/v2/Apps/Artwork/Components/TrustSignals/BuyerGuarantee.tsx
  src/v2/Apps/Artwork/Components/TrustSignals/SecurePayment.tsx
  src/v2/Apps/Artwork/Components/TrustSignals/VerifiedSeller.tsx
  src/v2/Apps/Artwork/Utils/badges.ts
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#9992 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9994 feat: prevent call before mounting
  src/v2/Apps/Consign/Hooks/__tests__/useConnectUserToSubmission.jest.ts
  src/v2/Apps/Consign/Hooks/useConnectUserToSubmission.ts
  src/v2/Components/__tests__/LotTimer.jest.tsx
Labels: Squash On Green

#9990 bug:fixes flakey test that fails in CI off by 1 sec
  src/v2/Components/__tests__/LotTimer.jest.tsx
Labels: Jira Synced

#9988 refactor: Consolidate logic and functionality on sale and lot timer and on web/app
  src/v2/Apps/Auction/Components/AuctionDetails/SaleDetailTimer.tsx
  src/v2/Apps/Auction/Components/AuctionDetails/__tests__/SaleDetailTimer.jest.tsx
  src/v2/Components/Artwork/Details.tsx
  src/v2/Components/LotTimer.tsx
  src/v2/Components/__tests__/LotTimer.jest.tsx
  src/v2/Utils/__tests__/getSaleOrLotTimerInfo.jest.ts
  src/v2/Utils/getSaleOrLotTimerInfo.ts
Labels: Jira Synced

#9998 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9989 feat(Auction): Add phone number into to /confirm-registration if no phone number on file
  src/v2/Apps/Auction/Components/Form/AddressForm.tsx
  src/v2/Apps/Auction/Components/Form/Utils/initialValues.ts
  src/v2/Apps/Auction/Components/Form/Utils/validationSchemas.ts
  src/v2/Apps/Auction/Hooks/__tests__/useCreateTokenAndSubmit.jest.tsx
  src/v2/Apps/Auction/Hooks/useCreateTokenAndSubmit.ts
  src/v2/Apps/Auction/Routes/AuctionConfirmRegistrationRoute.tsx
  src/v2/Apps/Auction/Routes/__tests__/AuctionConfirmRegistrationRoute.jest.tsx
  src/v2/Apps/Order/Components/__tests__/AddressModal.jest.tsx
  src/v2/Components/AddressForm.tsx
  src/v2/Components/__tests__/Utils/addressForm.ts
  src/v2/__generated__/AuctionConfirmRegistrationRouteTestQuery.graphql.ts
  src/v2/__generated__/AuctionConfirmRegistrationRoute_me.graphql.ts
  src/v2/__generated__/auctionRoutes_ConfirmRegistrationRouteQuery.graphql.ts
  tsconfig.json
Labels: Jira Synced

#9977 feat: add a red progress bar on the artwork page when an auction work is within extended bidding period
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionProgressBar.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionTimer.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/LotTimer.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarAuctionProgressBar.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/LotTimer.jest.tsx
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/LotTimer_saleArtwork.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#10004 fix(auth): Fix redirect to existing page on signup
  src/v2/Components/NavBar/NavBar.tsx
  src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
Labels: Merge On Green, Jira Synced

#9995 fix(NX-3130): add a margin to the tertiary button to avoid clashing
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
Labels: Jira Synced
