Repository artsy/force, pull requests merged in 2022-01, with the labels that each got.

#9131 fix: Bump feature total item count
  cypress/integration/partnerProfile.spec.js
  src/v2/Apps/Feature/Components/FeatureSet/FeatureSet.tsx
  src/v2/Apps/Feature/Components/FeatureSet/FeatureSetContainer.tsx
  src/v2/__generated__/FeatureApp_Test_Query.graphql.ts
  src/v2/__generated__/FeatureSetContainer_set.graphql.ts
  src/v2/__generated__/FeatureSet_set.graphql.ts
  src/v2/__generated__/featureRoutes_FeatureQuery.graphql.ts
Labels: Merge On Green

#9129 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/CreateCreditCardAndUpdatePhoneMutation.graphql.ts
  src/v2/__generated__/UpdateUserInformationMutation.graphql.ts
  src/v2/__generated__/UserEmailPreferencesMutation.graphql.ts
  src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Squash On Green

#9084 fix(FX-3603): remove extra offset for exhibitors nav
  src/v2/Apps/Fair/Components/FairHeader/FairHeader.tsx
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx
  src/v2/Apps/Fair/Utils/useExhibitorsTabOffset.ts
  src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
  src/v2/__generated__/FairApp_Test_Query.graphql.ts
  src/v2/__generated__/FairApp_fair.graphql.ts
  src/v2/__generated__/FairExhibitors_Test_Query.graphql.ts
  src/v2/__generated__/FairExhibitors_fair.graphql.ts
  src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#9142 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9144 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9145 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9139 Deploy
  data/schema.graphql
  package.json
  src/v2/Apps/Fair/Components/FairHeader/FairHeader.tsx
  src/v2/Apps/Fair/FairApp.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx
  src/v2/Apps/Fair/Utils/useExhibitorsTabOffset.ts
  src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
  src/v2/__generated__/FairApp_Test_Query.graphql.ts
  src/v2/__generated__/FairApp_fair.graphql.ts
  src/v2/__generated__/FairExhibitors_Test_Query.graphql.ts
  src/v2/__generated__/FairExhibitors_fair.graphql.ts
  src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#9141 fix: Finish auction/:id MPV2 support
  cypress/integration/partnerProfile.spec.js
  src/desktop/apps/auction/actions/artworkBrowser.js
  src/desktop/apps/auction/components/artwork_browser/main/artwork/BidStatus.js
  src/desktop/apps/auction/components/artwork_browser/sidebar/ArtistFilter.js
  src/desktop/apps/auction/queries/filter.js
Labels: Jira Synced

#9154 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9157 fix: Mark deprecated component as such
  src/v2/Components/Toast/ToastComponent.tsx
Labels: Merge On Green

#9158 feat(articles): implements articles index page
  src/v2/Apps/Articles/ArticlesApp.tsx
  src/v2/Apps/Articles/Components/ArticlesIndexArticle.tsx
  src/v2/Apps/Articles/Components/ArticlesIndexArticleShare.tsx
  src/v2/Apps/Articles/Components/ArticlesIndexArticles.tsx
  src/v2/Apps/Articles/Components/__tests__/ArticlesIndexArticles.jest.tsx
  src/v2/Apps/Articles/articlesRoutes.tsx
  src/v2/__generated__/ArticlesApp_viewer.graphql.ts
  src/v2/__generated__/ArticlesIndexArticle_article.graphql.ts
  src/v2/__generated__/ArticlesIndexArticlesQuery.graphql.ts
  src/v2/__generated__/ArticlesIndexArticles_test_Query.graphql.ts
  src/v2/__generated__/ArticlesIndexArticles_viewer.graphql.ts
  src/v2/__generated__/articlesRoutes_ArticlesQuery.graphql.ts
  src/v2/routes.tsx
Labels: Merge On Green

#9160 ci(notifications): Add slack webook notifications
  .circleci/config.yml
Labels: Merge On Green

#9162 security(colors.js): Lock version to 1.4 due to corruption
  package.json
  yarn.lock
Labels: Merge On Green

#9049 Web - Display offer/order information in conversation side drawer
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/DetailsHeader.tsx
  src/v2/Apps/Conversation/Components/DetailsSidebar.tsx
  src/v2/Apps/Conversation/Routes/Conversation/index.tsx
  src/v2/Apps/Conversation/__tests__/DetailsSidebar.jest.tsx
  src/v2/Apps/Order/Components/CreditCardDetails.tsx
  src/v2/Apps/Order/Components/CreditCardSummaryItem.tsx
  src/v2/Apps/Order/Components/ShippingAddress.tsx
  src/v2/Apps/Order/Components/ShippingSummaryItem.tsx
  src/v2/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/v2/Apps/Order/Routes/Status/index.tsx
  src/v2/Apps/Order/Utils/getStatusCopy.tsx
  src/v2/Components/Artwork/Metadata.tsx
  src/v2/__generated__/AcceptTestQuery.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/ConversationPagination_Test_Query.graphql.ts
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/Conversation_me.graphql.ts
  src/v2/__generated__/CounterTestQuery.graphql.ts
  src/v2/__generated__/DetailsSidebar_Test_Query.graphql.ts
  src/v2/__generated__/DetailsSidebar_conversation.graphql.ts
  src/v2/__generated__/Details_conversation.graphql.ts
  src/v2/__generated__/NewPaymentTestQuery.graphql.ts
  src/v2/__generated__/Offer2TestQuery.graphql.ts
  src/v2/__generated__/OfferTestQuery.graphql.ts
  src/v2/__generated__/PaymentTestQuery.graphql.ts
  src/v2/__generated__/RespondCounterOfferMutation.graphql.ts
  src/v2/__generated__/RespondTestQuery.graphql.ts
  src/v2/__generated__/ReviewTestQuery.graphql.ts
  src/v2/__generated__/ShippingTestQuery.graphql.ts
  src/v2/__generated__/StatusQuery.graphql.ts
  src/v2/__generated__/TransactionDetailsSummaryItemTestQuery.graphql.ts
  src/v2/__generated__/TransactionDetailsSummaryItem_order.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
  src/v2/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/v2/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/v2/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/v2/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/v2/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/v2/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/v2/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/v2/__generated__/orderRoutes_StatusQuery.graphql.ts
Labels: Jira Synced

#9136 feat(FX-3545): Add app download buttons to create saved search alert modal
  src/v2/Components/SavedSearchAlert/DownloadAppBanner.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/v2/Components/SavedSearchAlert/__tests__/DownloadAppBanner.jest.tsx
Labels: Jira Synced, Squash On Green

#9166 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9168 feat(articles): promotes /articles2 => /articles
  src/desktop/apps/articles/index.js
  src/desktop/apps/articles/queries/editorial_articles.coffee
  src/desktop/apps/articles/routes.ts
  src/desktop/apps/articles/test/routes.test.js
  src/lib/middleware/hardcodedRedirects.ts
  src/mobile/apps/articles/index.coffee
  src/mobile/apps/articles/routes.coffee
  src/mobile/apps/articles/test/client/articles.test.js
  src/mobile/apps/articles/test/routes.test.js
  src/mobile/assets/mobile_articles.ts
  src/v2/Apps/Articles/Components/ArticlesIndexArticle.tsx
  src/v2/Apps/Articles/Components/ArticlesIndexArticles.tsx
  src/v2/Apps/Articles/Components/__tests__/ArticlesIndexArticles.jest.tsx
  src/v2/Apps/Articles/articlesRoutes.tsx
  src/v2/__generated__/ArticlesIndexArticle_article.graphql.ts
  src/v2/__generated__/ArticlesIndexArticlesQuery.graphql.ts
  src/v2/__generated__/ArticlesIndexArticles_test_Query.graphql.ts
  src/v2/__generated__/ArticlesIndexArticles_viewer.graphql.ts
  src/v2/__generated__/articlesRoutes_ArticlesQuery.graphql.ts
Labels: Merge On Green

#9165 feat: Update copy on auth pages GRO-731
  cypress/integration/userPayments.spec.js
  cypress/integration/userShipping.spec.js
  src/v2/Apps/Authentication/Routes/LoginRoute.tsx
  src/v2/Apps/Authentication/Routes/SignupRoute.tsx
  src/v2/Apps/Authentication/__tests__/authenticationRoutes.jest.tsx
Labels: Merge On Green

#8902 Issue with Buyer’s Premium modal display
  src/v2/Components/AuctionBuyersPremiumDialog.tsx
  src/v2/Components/__tests__/AuctionBuyersPremiumDialog.jest.tsx
Labels: Jira Synced

#9149 [NX-3039] Enable edition sets selection for inquireable artworks
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial2.jest.tsx
Labels: Jira Synced

#9173 feat(contact2): Style page
  src/v2/Apps/_Contact2/ContactApp.tsx
Labels: Merge On Green

#9175 feat(StaticPage): Add /page2/:slug app
  src/v2/Apps/StaticPage/StaticPageApp.tsx
  src/v2/Apps/StaticPage/staticPageRoutes.tsx
  src/v2/Apps/_ArtsyEducation2/ArtsyEducationApp.tsx
  src/v2/Apps/_ArtsyEducation2/artsyEducationRoutes.tsx
  src/v2/Apps/_Terms2/TermsApp.tsx
  src/v2/Apps/_Terms2/termsRoutes.tsx
  src/v2/__generated__/StaticPageApp_page.graphql.ts
  src/v2/__generated__/staticPageRoutes_TopLevelQuery.graphql.ts
  src/v2/routes.tsx
Labels: Merge On Green

#9180 Deploy
  package.json
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/LocationAutocomplete.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/LocationAutocomplete.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/SubmissionLayout.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileAboutYou.tsx
  src/v2/Components/Inquiry/Views/InquiryBasicInfo.tsx
  src/v2/Components/LocationAutocompleteInput.tsx
  src/v2/Components/__tests__/LocationAutocompleteInput.jest.tsx
  src/v2/Typings/global.d.ts
  tsconfig.json
  yarn.lock
Labels: Jira Synced

#9182 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9184 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9179 feat: Add nft medium type to filter
  src/v2/Apps/Artwork/Utils/createCollectUrl.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
Labels: hackathon

#9191 fix: Render dimensions when digits are present
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarSizeInfo.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarMetadata.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarMetadata.ts
Labels: Merge On Green

#9178 chore(FX-3677): update the filter counting logic for name input
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/v2/Components/SavedSearchAlert/Utils/__tests__/getNamePlaceholder.jest.ts
  src/v2/Components/SavedSearchAlert/Utils/getNamePlaceholder.tsx
  src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
Labels: Jira Synced

#9200 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/CreateCreditCardAndUpdatePhoneMutation.graphql.ts
  src/v2/__generated__/UpdateUserInformationMutation.graphql.ts
  src/v2/__generated__/UserEmailPreferencesMutation.graphql.ts
  src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Squash On Green

#9194 chore(FX-3678): correctly track event for create alert button
  src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/__tests__/CreateAlertButton.jest.tsx
Labels: Jira Synced

#9204 Deploy
  src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/__tests__/CreateAlertButton.jest.tsx
Labels: Jira Synced

#9207 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9209 fix(articles): adjusts thumbnail aspect ratio
  src/v2/Apps/Articles/Components/ArticlesIndexArticle.tsx
  src/v2/__generated__/ArticlesIndexArticle_article.graphql.ts
  src/v2/__generated__/ArticlesIndexArticlesQuery.graphql.ts
  src/v2/__generated__/ArticlesIndexArticles_test_Query.graphql.ts
  src/v2/__generated__/articlesRoutes_ArticlesQuery.graphql.ts
Labels: Merge On Green

#9221 remove admin block
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Merge On Green

#9222 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9224 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9212 feat(FX-3682): don't apply highlighted state for artist pill
  src/v2/Components/ArtworkFilter/SavedSearch/Components/ArtworkGridFilterPills.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/Pills.tsx
Labels: Jira Synced

#9225 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/CreateCreditCardAndUpdatePhoneMutation.graphql.ts
  src/v2/__generated__/UpdateUserInformationMutation.graphql.ts
  src/v2/__generated__/UserEmailPreferencesMutation.graphql.ts
  src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Squash On Green

#9086 fix visual bugs in inbox details
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/ConversationHeader.tsx
  src/v2/Apps/Conversation/Components/ConversationList.tsx
  src/v2/Apps/Conversation/Components/DetailsHeader.tsx
  src/v2/Apps/Conversation/Components/DetailsSidebar.tsx
  src/v2/Apps/Conversation/ConversationApp.tsx
  src/v2/Apps/Conversation/Routes/Conversation/index.tsx
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/DetailsSidebar_Test_Query.graphql.ts
  src/v2/__generated__/DetailsSidebar_conversation.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Merge On Green, Jira Synced

#9231 chore: Remove unnecessary TS annotation
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarMetadata.jest.tsx
Labels: Merge On Green

#9234 Meet the specialists page fixes
  src/v2/Apps/MeetTheSpecialists/MeetTheSpecialistsApp.tsx
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
  src/v2/Apps/MeetTheSpecialists/meetTheSpecialistsRoutes.tsx
Labels: Squash On Green

#9235 chore: set offset for pills
  src/v2/Components/ArtworkFilter/SavedSearch/Components/ArtworkGridFilterPills.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/Pills.tsx
Labels: Squash On Green

#9239 refactor(works-for-you2): Promote /works-for-you2 -> /works-for-you
  src/desktop/apps/notifications/client/index.coffee
  src/desktop/apps/notifications/client/mobile.coffee
  src/desktop/apps/notifications/client/react_grid.js
  src/desktop/apps/notifications/client/sidebar.coffee
  src/desktop/apps/notifications/client/url_updater.coffee
  src/desktop/apps/notifications/index.coffee
  src/desktop/apps/notifications/routes.coffee
  src/desktop/apps/notifications/stylesheets/index.styl
  src/desktop/apps/notifications/stylesheets/mobile.styl
  src/desktop/apps/notifications/templates/desktop.jade
  src/desktop/apps/notifications/templates/filter_artist.jade
  src/desktop/apps/notifications/templates/index.jade
  src/desktop/apps/notifications/templates/mobile/artist.jade
  src/desktop/apps/notifications/templates/mobile/empty.jade
  src/desktop/apps/notifications/templates/mobile/index.jade
  src/desktop/apps/notifications/test/client/index.test.js
  src/desktop/apps/notifications/test/client/mobile.test.js
  src/desktop/apps/notifications/test/client/sidebar.test.js
  src/desktop/apps/notifications/test/routes.test.js
  src/desktop/assets/misc.styl
  src/desktop/assets/misc.ts
  src/desktop/index.ts
  src/v2/Apps/WorksForYou/Components/WorksForYouArtistFeed.tsx
  src/v2/Apps/WorksForYou/Components/WorksForYouFeed.tsx
  src/v2/Apps/WorksForYou/MarketingHeader.tsx
  src/v2/Apps/WorksForYou/WorksForYouApp.tsx
  src/v2/Apps/WorksForYou/WorksForYouArtistFeed.tsx
  src/v2/Apps/WorksForYou/WorksForYouFeed.tsx
  src/v2/Apps/WorksForYou/__tests__/WorksForYouApp.jest.tsx
  src/v2/Apps/WorksForYou/index.tsx
  src/v2/Apps/WorksForYou/worksForYouRoutes.tsx
  src/v2/__generated__/WorksForYou2App_viewerFeed.graphql.ts
  src/v2/__generated__/WorksForYou2ArtistFeedPaginationQuery.graphql.ts
  src/v2/__generated__/WorksForYou2ArtistFeed_viewer.graphql.ts
  src/v2/__generated__/WorksForYou2FeedPaginationQuery.graphql.ts
  src/v2/__generated__/WorksForYou2Feed_viewer.graphql.ts
  src/v2/__generated__/WorksForYouApp_test_Query.graphql.ts
  src/v2/__generated__/WorksForYouApp_viewerArtist.graphql.ts
  src/v2/__generated__/WorksForYouApp_viewerFeed.graphql.ts
  src/v2/__generated__/WorksForYouApp_viewerMe.graphql.ts
  src/v2/__generated__/WorksForYouApp_viewerSidebarAggregations.graphql.ts
  src/v2/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
  src/v2/__generated__/WorksForYouArtistFeed_viewer.graphql.ts
  src/v2/__generated__/WorksForYouFeedPaginationQuery.graphql.ts
  src/v2/__generated__/WorksForYouFeed_viewer.graphql.ts
  src/v2/__generated__/WorksForYouQuery.graphql.ts
  src/v2/__generated__/worksForYouRoutes_TopLevelQuery.graphql.ts
  src/v2/routes.tsx
Labels: Merge On Green

#9242 fix(settings2): delete q/a
  src/v2/Apps/Settings/Mutations/DeleteMyAccount.ts
  src/v2/Apps/Settings/Routes/DeleteAccount/DeleteAccountRoute.tsx
  src/v2/Apps/Settings/Routes/DeleteAccount/useDeleteAccount.ts
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsDeleteAccount/SettingsEditSettingsDeleteAccount.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsEmailPreferences/SettingsEditSettingsEmailPreferences.tsx
  src/v2/__generated__/useDeleteAccountMutation.graphql.ts
Labels: Merge On Green

#9215 fix(payment): Buyer can't accept seller's offer when payment requires authentication
  src/v2/Apps/Order/Routes/Accept/index.tsx
Labels: Jira Synced

#9250 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9251 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9248 feat(settings2): rebuilds shipping tab
  src/v2/Apps/Order/Components/SavedAddresses.tsx
  src/v2/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddress.tsx
  src/v2/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddressForm.tsx
  src/v2/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddresses.tsx
  src/v2/Apps/Settings/Routes/Shipping/Components/SettingsShippingRoute.tsx
  src/v2/Apps/Settings/Routes/Shipping/SettingsShippingRoute.tsx
  src/v2/Apps/Settings/Routes/Shipping/useAddAddress.ts
  src/v2/Apps/Settings/Routes/Shipping/useDeleteAddress.ts
  src/v2/Apps/Settings/Routes/Shipping/useEditAddress.ts
  src/v2/Apps/Settings/Routes/Shipping/useSetDefaultAddress.ts
  src/v2/Apps/Settings/Routes/__tests__/UserSettingsAddresses.jest.tsx
  src/v2/Apps/Settings/settingsRoutes.tsx
  src/v2/Apps/Shipping/Routes/Shipping/ShippingApp.tsx
  src/v2/Apps/Shipping/Routes/Shipping/UserSettingsAddresses.tsx
  src/v2/Components/CountrySelect.tsx
  src/v2/Components/Inquiry/Views/InquiryBasicInfo.tsx
  src/v2/Components/Inquiry/util.ts
  src/v2/Utils/compactObject.ts
  src/v2/__generated__/SettingsShippingAddress_address.graphql.ts
  src/v2/__generated__/SettingsShippingAddresses_me.graphql.ts
  src/v2/__generated__/SettingsShippingRoute_me.graphql.ts
  src/v2/__generated__/UserSettingsAddresses_test_Query.graphql.ts
  src/v2/__generated__/settingsRoutes_ShippingRouteQuery.graphql.ts
  src/v2/__generated__/useAddAddressMutation.graphql.ts
  src/v2/__generated__/useDeleteAddressMutation.graphql.ts
  src/v2/__generated__/useEditAddressMutation.graphql.ts
  src/v2/__generated__/useSetDefaultAddressMutation.graphql.ts
Labels: Merge On Green

#9255 Update metaphysics schema
  src/v2/__generated__/useAddAddressMutation.graphql.ts
  src/v2/__generated__/useDeleteAddressMutation.graphql.ts
  src/v2/__generated__/useEditAddressMutation.graphql.ts
  src/v2/__generated__/useSetDefaultAddressMutation.graphql.ts
Labels: Squash On Green

#9208 feat(FX-3681): Sign up flow should skip onboarding when trying to create alert
  src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/__tests__/CreateAlertButton.jest.tsx
  src/v2/Utils/openAuthModal.ts
Labels: Jira Synced

#9259 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/CreateCreditCardAndUpdatePhoneMutation.graphql.ts
  src/v2/__generated__/UpdateUserInformationMutation.graphql.ts
  src/v2/__generated__/UserEmailPreferencesMutation.graphql.ts
  src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Squash On Green

#9264 chore: edit advisory page content
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Merge On Green

#9254 refactor(artwork-filter): Swap in FilterSelect for artwork filters with search
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistNationalityFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtworkLocationFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/FacetFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/MaterialsFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PartnersFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ResultOption.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ResultsFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/Utils/__tests__/useFilterSelectResults.jest.ts
  src/v2/Components/ArtworkFilter/ArtworkFilters/Utils/sortResults.ts
  src/v2/Components/ArtworkFilter/ArtworkFilters/Utils/useFilterSelectResults.ts
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/FacetFilter.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ResultsFilter.jest.tsx
  src/v2/Components/SavedSearchAlert/Utils/extractPills.ts
Labels: Merge On Green

#9267 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9118 feat: new offer submission price range notice
  src/v2/Apps/Order/Components/MinPriceWarning.tsx
  src/v2/Apps/Order/Components/OfferNote.tsx
  src/v2/Apps/Order/Components/PriceOptions.tsx
  src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
  src/v2/Apps/Order/Routes/Offer/index.tsx
Labels: Jira Synced, Squash On Green

#9265 feat(settings2): rebuilds payments tab
  src/v2/Apps/Order/Components/CreditCardInput.tsx
  src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethod.tsx
  src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethodForm.tsx
  src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethods.tsx
  src/v2/Apps/Settings/Routes/Payments/SettingsPaymentsRoute.tsx
  src/v2/Apps/Settings/Routes/Payments/useAddCreditCard.ts
  src/v2/Apps/Settings/Routes/Payments/useDeleteCreditCard.ts
  src/v2/Apps/Settings/Routes/__tests__/SettingsPaymentsRoute.jest.tsx
  src/v2/Components/CreditCardInput/CreditCardInput.tsx
  src/v2/Components/CreditCardInput/CreditCardInputProvider.tsx
  src/v2/Components/CreditCardInput/index.ts
  src/v2/__generated__/SettingsPaymentsMethod_method.graphql.ts
  src/v2/__generated__/SettingsPaymentsMethods_me.graphql.ts
  src/v2/__generated__/SettingsPaymentsRoute_Test_Query.graphql.ts
  src/v2/__generated__/SettingsPaymentsRoute_me.graphql.ts
  src/v2/__generated__/settingsRoutes_PaymentsRouteQuery.graphql.ts
  src/v2/__generated__/useAddCreditCardMutation.graphql.ts
  src/v2/__generated__/useDeleteCreditCardMutation.graphql.ts
Labels: Merge On Green

#9288 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/createSavedSearchAlertMutation.graphql.ts
Labels: Squash On Green

#9289 chore: fix save search bell color
  src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
Labels: Squash On Green

#9253 GRO-703: User sees preference center options matching comp
  src/v2/Apps/_Preferences2/PreferencesApp.tsx
  src/v2/Apps/_Preferences2/__tests__/PreferencesApp.jest.tsx
Labels: Jira Synced

#9287 bugfix(artist-app): Fix missing overview tab
  src/v2/Apps/Artist/Routes/Overview/Utils/hasOverviewContent.ts
  src/v2/Apps/Artist/__tests__/ArtistApp.jest.tsx
Labels: Merge On Green

#9143 feat(GRO-644): Add sign up via Google to Force
  .secrets.baseline
  package.json
  src/config.ts
  src/lib/passport/README.md
  src/lib/passport/example/loggedin.jade
  src/lib/passport/example/login.jade
  src/lib/passport/example/nocsrf.jade
  src/lib/passport/lib/app/index.js
  src/lib/passport/lib/app/locals.js
  src/lib/passport/lib/options.js
  src/lib/passport/lib/passport/callbacks.js
  src/lib/passport/lib/passport/index.js
  src/lib/passport/test/passport/callbacks.js
  src/middleware.ts
  src/typings/sharify.d.ts
  src/v2/Apps/Authentication/Components/AuthStatic.tsx
  src/v2/Apps/Authentication/Components/ModalContainer.tsx
  src/v2/Components/Authentication/Components/AuthenticationFooter.tsx
  src/v2/Components/Authentication/FormSwitcher.tsx
  src/v2/Components/Authentication/ModalManager.tsx
  src/v2/Components/Authentication/Types.ts
  src/v2/Components/Authentication/Views/SignUpForm.tsx
  src/v2/Components/Authentication/__tests__/FormSwitcher.jest.tsx
  src/v2/Components/Authentication/__tests__/ModalManager.jest.tsx
  src/v2/Components/Authentication/__tests__/Views/SignUpForm.jest.tsx
  test.mocha.js
  yarn.lock
Labels: Merge On Green, Jira Synced

#9153 chore(GRO-687): Consolidate error handling
  src/desktop/components/error_handler/README.md
  src/desktop/components/error_handler/index.css
  src/desktop/components/error_handler/index.jade
  src/desktop/components/error_handler/index.styl
  src/desktop/components/error_handler/test/template.test.js
  src/lib/middleware/errorHandler.ts
  src/lib/middleware/errorHandler.tsx
  src/test/lib/middleware/errorHandler.jest.ts
  src/v2/Apps/Components/AppShell.tsx
  src/v2/Apps/Debug/debugRoutes.tsx
  src/v2/Components/ErrorPage.tsx
  src/v2/Components/NavBar/NavBar.tsx
  src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
  src/v2/Components/NavBar/__tests__/NavBarTracking.jest.tsx
  src/v2/System/Router/Boot.tsx
  src/v2/System/Router/ErrorBoundary.tsx
  src/v2/System/Router/RenderStatus.tsx
  src/v2/System/Router/__tests__/ErrorBoundary.jest.tsx
  src/v2/System/Router/__tests__/buildServerApp.jest.tsx
  src/v2/System/Router/buildServerApp.tsx
  src/v2/System/Router/renderServerApp.tsx
  src/v2/index.ejs
  src/v2/server.ts
Labels: Merge On Green

#9291 Expand tests for the preference center
  src/v2/Apps/_Preferences2/__tests__/PreferencesApp.jest.tsx
Labels: Merge On Green

#9274 Conditional removal of "Price includes tax" messaging
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/v2/Utils/user.ts
Labels: Jira Synced
