Repository artsy/force, pull requests merged in 2022-09, with the labels that each got.

#10905 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10906 fix: update SWA content for non-logged-in users
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
Labels: Jira Synced

#10882 fix: Add delay to artwork form for image processing
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx
Labels: Jira Synced

#10909 test: artwork sidebar2 tests
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2ShippingInformation.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2Artists.jest.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2ArtworkTitle.jest.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2ShippingInformation.jest.tsx
  src/__generated__/ArtworkSidebar2Artists_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2ArtworkTitle_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2ShippingInformation_Test_Query.graphql.ts
Labels: Jira Synced

#10910 feat: support maxWorksPerArtist param on /new-for-you page
  src/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx
  src/Apps/NewForYou/NewForYouApp.tsx
  src/Apps/NewForYou/newForYouRoutes.tsx
  src/__generated__/NewForYouApp_viewer.graphql.ts
  src/__generated__/NewForYouArtworksGrid_viewer.graphql.ts
  src/__generated__/newForYouRoutes_TopLevelQuery.graphql.ts
Labels: Jira Synced

#10913 fix: Add my-collection route to history when saving an artwork
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2Artists.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
Labels: Jira Synced

#10904 feat(FX-4147): rework artwork details
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2AuthenticityCertificate.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2Classification.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2Details.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2Details.jest.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/ArtworkSidebar2AuthenticityCertificate_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2Classification_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2Details_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2Details_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#10930 fix: reverted changes made to SWA ThankYou screen
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYouWhenFromMyCollection.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYouWhenFromMyCollection.jest.tsx
Labels: Jira Synced

#10933 fix: fix admin/clear-cache route
  src/Apps/Admin/adminRoutes.tsx
  src/Apps/Admin/adminServerRoutes.tsx
Labels: Jira Synced

#10934 chore: update sepa payment description copy
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/__tests__/Payment.jest.tsx
Labels: Jira Synced

#10928 feat(tx-420): alican/payment method change from review step
  src/Apps/Order/Components/BankAccountPicker.tsx
  src/Components/BankDebitForm/__tests__/BankDebitProvider.jest.tsx
  src/__generated__/BankAccountPickerTestQuery.graphql.ts
  src/__generated__/BankAccountPicker_order.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
Labels: Jira Synced

#10929 feat(FX-4152): position account above inbox in mweb nav
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
  src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
Labels: Jira Synced

#10914 feat: add i18n support in tests
  src/Apps/Artist/Components/ArtistHeader/__tests__/ArtistHeader.jest.tsx
  src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistCareerHighlights.jest.tsx
  src/Components/NavBar/__tests__/NavBar.jest.tsx
  src/DevTools/setupTestWrapper.tsx
  src/System/i18n/i18n.ts
Labels: Jira Synced

#10937 fix: failed test for `ArtworkSidebar2Details`
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2Details.jest.tsx
Labels: Squash On Green

#10924 chore(FX-4197, FX-4195): activity panel improvements
  src/Apps/Notifications/NotificationsApp.tsx
  src/Components/NavBar/Menus/NavBarNewNotifications.tsx
  src/Components/Notifications/NotificationItem.tsx
  src/Components/Notifications/Notifications.tsx
  src/Components/Notifications/NotificationsList.tsx
  src/Components/Notifications/NotificationsTabs.tsx
  src/Components/Notifications/__tests__/Notifications.jest.tsx
Labels: Jira Synced

#10932 feat(FX-4201): display indicator for hamburger menu icon and Activity link when user has unread notifications
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavBarLoggedInActions.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotificationsIndicator.tsx
  src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenuNotificationsIndicator.jest.tsx
  src/Components/NavBar/NavBarNotificationIndicator.tsx
  src/Components/NavBar/helpers.ts
  src/__generated__/NavBarMobileMenuNotificationsIndicatorQuery.graphql.ts
  src/__generated__/NavBarMobileMenuNotificationsIndicator_me.graphql.ts
  src/__generated__/NavBarMobileMenuNotificationsIndicator_test_Query.graphql.ts
Labels: Jira Synced, Squash On Green

#10940 feat: upgrade Cypress to 10.7.0
  .circleci/config.yml
  .dockerignore
  .eslintrc.js
  Dockerfile
  cypress.config.ts
  cypress.json
  cypress/e2e/.gitkeep
  cypress/e2e/about.cy.ts
  cypress/e2e/alerts.cy.ts
  cypress/e2e/artAppraisals.cy.ts
  cypress/e2e/article.cy.ts
  cypress/e2e/articles.cy.ts
  cypress/e2e/artist.cy.js
  cypress/e2e/artistSeries.cy.ts
  cypress/e2e/artists.cy.ts
  cypress/e2e/artwork.cy.js
  cypress/e2e/auction.cy.ts
  cypress/e2e/auctions.cy.ts
  cypress/e2e/categories.cy.ts
  cypress/e2e/collect.cy.js
  cypress/e2e/collection.cy.js
  cypress/e2e/collections.cy.ts
  cypress/e2e/consign.cy.ts
  cypress/e2e/contact.cy.ts
  cypress/e2e/debug.cy.js
  cypress/e2e/fair.cy.ts
  cypress/e2e/fairOrganizer.cy.ts
  cypress/e2e/fairs.cy.ts
  cypress/e2e/feature.cy.ts
  cypress/e2e/flashMessage.cy.ts
  cypress/e2e/galleries.cy.ts
  cypress/e2e/gallery.cy.ts
  cypress/e2e/gene.cy.ts
  cypress/e2e/home.cy.ts
  cypress/e2e/institution.cy.ts
  cypress/e2e/institutionPartnerships.cy.ts
  cypress/e2e/institutions.cy.ts
  cypress/e2e/myCollection.cy.ts
  cypress/e2e/news.cy.ts
  cypress/e2e/notifications.cy.ts
  cypress/e2e/page.cy.ts
  cypress/e2e/partnerProfile.cy.js
  cypress/e2e/search.cy.ts
  cypress/e2e/settings.cy.ts
  cypress/e2e/shows.cy.ts
  cypress/e2e/systemUp.cy.js
  cypress/e2e/tag.cy.ts
  cypress/e2e/terms.cy.js
  cypress/e2e/userPayments.cy.js
  cypress/e2e/userShipping.cy.js
  cypress/e2e/viewingRoom.cy.ts
  cypress/e2e/viewingRooms.cy.ts
  cypress/helpers/artworkGridRenders.ts
  cypress/helpers/visitWithStatusRetries.ts
  dangerfile.ts
  docs/best_practices.md
  package.json
  scripts/smoke_test.sh
  yarn.lock
Labels: Jira Synced

#10941 feat(CX-2874): Add Insights tab to SettingsApp
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
  src/Apps/Settings/SettingsApp.tsx
  src/Apps/Settings/settingsRoutes.tsx
  src/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/Components/NavBar/Menus/__tests__/NavBarUserMenu.jest.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
  src/__generated__/InsightsRoute_me.graphql.ts
  src/__generated__/settingsRoutes_InsightsRouteQuery.graphql.ts
Labels: Jira Synced

#10946 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10947 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10938 feat(CX-2845): Add artist link to MyC artwork details page
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarTitleInfo.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MyCollectionArtworkSidebar.jest.tsx
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
  src/__generated__/MyCollectionArtworkSidebarTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkSidebarTitleInfo_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#10952 fix: Block text injection on settings page GRO-1172
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsLinkedAccounts.tsx
  src/Server/passport/lib/app/lifecycle.js
Labels: Merge On Green

#10953 chore: add ErrorBoundary to the setupTestWrapper
  src/DevTools/setupTestWrapper.tsx
Labels: Jira Synced

#10939 fix: add redirect to my collection from articles page
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Components/BackLink.tsx
  src/Apps/Artist/Components/__tests__/BackLink.jest.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtistCurrentArticlesRail.tsx
  src/Apps/Artist/__tests__/ArtistApp.jest.tsx
  src/Apps/Artist/artistRoutes.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Components/TopContextBar.tsx
Labels: Jira Synced

#10949 feat(TX-611): Allow unsaved SEPA account to be re-used during checkout
  src/Apps/Order/Components/BankAccountPicker.tsx
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/__tests__/Payment.jest.tsx
Labels: Jira Synced

#10936 feat(FX-4196): render empty states for activity panel
  src/Components/Notifications/Notifications.tsx
  src/Components/Notifications/NotificationsEmptyStateByType.tsx
  src/Components/Notifications/NotificationsList.tsx
  src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx
  src/Components/Notifications/__tests__/NotificationsList.jest.tsx
  src/Components/Notifications/types.ts
Labels: Jira Synced

#10945 feat(CX-2875): add MyC Insights Overview
  src/Apps/Settings/Routes/Insights/Components/InsightsOverview.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsOverview.jest.tsx
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
  src/__generated__/InsightsOverviewTestQuery.graphql.ts
  src/__generated__/InsightsOverview_info.graphql.ts
  src/__generated__/InsightsRoute_me.graphql.ts
  src/__generated__/settingsRoutes_InsightsRouteQuery.graphql.ts
Labels: Jira Synced

#10959 feat(FX-4151): Artsy Guarantee section
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2ArtsyGuarantee.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2ArtsyGuarantee.jest.tsx
  src/DevTools/setupTestWrapper.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#10942 feat: update styles of order statuses
  src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
Labels: Jira Synced

#10968 fix: infinite pagination for activity panel dropdown menu
  src/Components/Notifications/NotificationsListScrollSentinel.tsx
Labels: Squash On Green

#10969 Style: adjust title and buttons of the upload/edit form
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx
Labels: Jira Synced

#10966 feat(CX-2885): Add Insights header
  src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
Labels: Jira Synced, Squash On Green

#10971 feat(FX-4248): Partner Info section in ArtworkSidebar2
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2PartnerInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2PartnerInfo.jest.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/ArtworkSidebar2PartnerInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2PartnerInfo_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#10974 fix(FX-4108): Switching between metrics (cm/in) produces duplicate filter pills when custom size is selected
  src/Components/SavedSearchAlert/Components/SavedSearchAlertPills.tsx
Labels: Jira Synced, Squash On Green

#10976 feat(FX-4217): create alert section
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2CreateArtworkAlert.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2.jest.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2CreateArtworkAlert.jest.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/ArtworkSidebar2CreateArtworkAlert_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2CreateArtworkAlert_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#10982 feat: allow prod to run on spot
  hokusai/production.yml
  hokusai/staging.yml
Labels: Jira Synced

#10989 fix: change email consign@ to sell@
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
Labels: Jira Synced

#10990 fix: pass empty types for all tab
  src/Components/Notifications/NotificationsList.tsx
Labels: Squash On Green

#10988 fix: swap fields order for mWeb, year and medium
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
Labels: Jira Synced

#10995 fix: for prod, add toleration for spot node taint
  hokusai/production.yml
Labels: Jira Synced

#10996 fix: change error message
  src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkValidation.ts
Labels: Jira Synced, Squash On Green

#10980 feat:(FX-4219): edition selection artwork screen
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2EditionSets.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2SizeInfo.tsx
  src/__generated__/ArtworkSidebar2EditionSets_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2SizeInfo_piece.graphql.ts
  src/__generated__/ArtworkSidebar2_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#10998 test: remove old relay test tools part IV
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/Apps/Order/Routes/__tests__/__snapshots__/Shipping.jest.tsx.snap
  src/Apps/Order/Utils/shippingUtils.ts
Labels: Jira Synced

#11001 fix: remove banner
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
Labels: Jira Synced

#11005 chore: Let react-i18next handle pluralization on Search results
  src/Apps/Search/Components/ZeroState.tsx
  src/Apps/Search/SearchApp.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced, #FF

#11003 fix(NX-3277): update copy for fraud prevention banner
  src/Apps/Conversation/Components/Conversation.tsx
Labels: Jira Synced

#11010 fix: Only show selected size dimension on My Collection
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MyCollectionArtworkSidebar.jest.tsx
  src/__generated__/MyCollectionArtworkSidebarMetadata_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkSidebarTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11008 feat: Add Get in Touch CTA
  src/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Header.jest.tsx
Labels: Jira Synced

#11014 Redirect to my collection page after editing an artwork
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx
Labels: Jira Synced

#11011 test: remove old relay test tools part V
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/RequestConditionReport.jest.tsx
  src/Apps/IdentityVerification/__tests__/IdentityVerificationApp.jest.tsx
  src/Apps/Order/Components/__tests__/SavedAddresses.jest.tsx
  src/Components/Artwork/SaveButton/__tests__/SaveButton.jest.tsx
  src/DevTools/setupTestWrapper.tsx
  src/__generated__/SavedAddressesInCollectorProfile_Test_Query.graphql.ts
  src/__generated__/SavedAddressesOutsiseCollectorProfile_Test_Query.graphql.ts
Labels: Jira Synced

#11018 feat: Add Sell with Artsy FAQ page
  src/Apps/Consign/Routes/MarketingLanding/FAQApp.tsx
  src/Apps/Consign/consignRoutes.tsx
Labels: Jira Synced

#11021 chore(tracking): remove MNTN tracking pixel
  src/Apps/Components/AppShell.tsx
  src/Components/Authentication/Views/SignUpForm.tsx
  src/Components/Inquiry/useInquiry.tsx
  src/Components/MNTNPixels.tsx
Labels: Merge On Green, Jira Synced

#11024 feat: Add CWA header Get in Touch CTA functionality
  src/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Header.jest.tsx
  src/__generated__/HomeNewWorksForYouRailQuery.graphql.ts
  src/__generated__/createTestEnvCreditCardMutation.graphql.ts
  src/__generated__/createTestEnvOrderMutation.graphql.ts
  src/__generated__/createTestEnv_artwork.graphql.ts
Labels: Jira Synced

#10994 feat(FX-4239): bottom faq swa section in redesigned artwork page
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2Links.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2Links.jest.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/ArtworkSidebar2Links_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2Links_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11007 feat: auto populate the fields in the swa form
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYouWhenFromMyCollection.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYouWhenFromMyCollection.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/createOrUpdateConsignSubmission.ts
  src/Apps/Consign/consignRoutes.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSWASection.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/__tests__/MyCollectionArtwork.jest.tsx
  src/__generated__/ArtworkDetails_SubmissionFlowPrepopulatedTest_Query.graphql.ts
  src/__generated__/ArtworkDetails_myCollectionArtwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/MyCollectionArtwork_artwork.graphql.ts
  src/__generated__/UploadPhotos_myCollectionArtwork.graphql.ts
  src/__generated__/consignRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignRoutes_contactInformationArtworkOwnerQuery.graphql.ts
  src/__generated__/consignRoutes_myCollectionArtworkQuery.graphql.ts
  src/__generated__/consignRoutes_uploadArtworkPhotosQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#11032 fix: Hyphenate 'last-minute'
  src/Apps/Artwork/Components/ArtworkSidebar/LotTimer.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/LotTimer.jest.tsx
  src/Apps/Auction/__tests__/AuctionApp.jest.tsx
  src/Components/CascadingEndTimesBanner.tsx
  src/Components/__tests__/CascadingEndTimesBanner.jest.tsx
Labels: Jira Synced, Squash On Green

#11035 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11034 fix(CX-2913): rename Size to Dimensions in MyC artwork page
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MyCollectionArtworkSidebar.jest.tsx
Labels: Jira Synced

#10999 chore (CX-2731): Add tracking to My Collection
  .secrets.baseline
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx
  src/Apps/MyCollection/Routes/Hooks/__tests__/useMyCollectionTracking.jest.tsx
  src/Apps/MyCollection/Routes/Hooks/useMyCollectionTracking.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx
  src/Apps/Settings/Routes/MyCollection/Components/MyCollectionEmptyState.tsx
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/MyCollectionArtwork_artwork.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#10901 feat(TX-638): Introduce React Context to Payment Route
  src/Apps/Order/Components/BankAccountPicker.tsx
  src/Apps/Order/Components/PollAccountBalance.tsx
  src/Apps/Order/Components/__tests__/BankAccountPicker.jest.tsx
  src/Apps/Order/OrderApp.tsx
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/Payment/PaymentContext/OrderPaymentContext.tsx
  src/Apps/Order/Routes/Payment/PaymentContext/orderPaymentReducer.ts
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/__tests__/Payment.jest.tsx
  src/Apps/Order/Utils/orderUtils.ts
  src/Components/BankDebitForm/BankDebitForm.tsx
  src/Components/BankDebitForm/BankDebitProvider.tsx
  src/Components/BankDebitForm/__tests__/BankDebitForm.jest.tsx
  src/Components/BankDebitForm/__tests__/BankDebitProvider.jest.tsx
Labels: Jira Synced, Squash On Green

#11037 feat: prepopulate fields | fix broken swa flow
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYouWhenFromMyCollection.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYouWhenFromMyCollection.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/createOrUpdateConsignSubmission.ts
  src/Apps/Consign/Routes/SubmissionFlow/Utils/redirects.ts
  src/Apps/Consign/consignFromMyCollectionRoutes.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSWASection.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/__tests__/MyCollectionArtwork.jest.tsx
  src/__generated__/ArtworkDetails_SubmissionFlowPrepopulatedTest_Query.graphql.ts
  src/__generated__/ArtworkDetails_myCollectionArtwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/MyCollectionArtwork_artwork.graphql.ts
  src/__generated__/UploadPhotos_myCollectionArtwork.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_myCollectionArtworkQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_uploadArtworkPhotosQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#11019 feat: use local images while displaying artwork images
  package.json
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormImages.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkImageBrowser/MyCollectionArtworkImageBrowser.tsx
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
  src/Apps/Settings/Routes/MyCollection/constants.ts
  src/Apps/Settings/settingsRoutes.tsx
  src/Components/Artwork/GridItem.tsx
  src/Components/PhotoUpload/Components/PhotoThumbnail.tsx
  src/Utils/localImagesHelpers.ts
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/NotificationItem_item.graphql.ts
  src/__generated__/NotificationItem_test_Query.graphql.ts
  src/__generated__/NotificationsListNextQuery.graphql.ts
  src/__generated__/NotificationsListQuery.graphql.ts
  src/__generated__/NotificationsList_test_Query.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/RejectTestQuery.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/__generated__/orderRoutes_RejectQuery.graphql.ts
  src/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/orderRoutes_StatusQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#11040 fix: issue related to image removal
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/NotificationItem_item.graphql.ts
  src/__generated__/NotificationItem_test_Query.graphql.ts
  src/__generated__/NotificationsListNextQuery.graphql.ts
  src/__generated__/NotificationsListQuery.graphql.ts
  src/__generated__/NotificationsList_test_Query.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/RejectTestQuery.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/__generated__/orderRoutes_RejectQuery.graphql.ts
  src/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/orderRoutes_StatusQuery.graphql.ts
Labels: Jira Synced

#11041 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11016 feat(ArtQuiz): main screen
  src/Apps/ArtQuiz/ArtQuizApp.tsx
  src/Apps/ArtQuiz/ArtQuizContext/ArtQuizContext.tsx
  src/Apps/ArtQuiz/ArtQuizInterface/ArtQuizButtons.tsx
  src/Apps/ArtQuiz/ArtQuizInterface/ArtQuizGridComponents.tsx
  src/Apps/ArtQuiz/ArtQuizInterface/ArtQuizInterface.tsx
Labels: Jira Synced

#10918 feat(art-quiz): add welcome screen
  src/Apps/ArtQuiz/ArtQuizContext/ArtQuizContext.tsx
  src/Components/ArtQuiz/Components/ArtQuizLeftPanel.tsx
  src/Components/ArtQuiz/Views/ArtQuizWelcome.tsx
  src/Components/Onboarding/Components/OnboardingFollows.tsx
  src/Components/Onboarding/Views/OnboardingQuestionOne.tsx
  src/Components/Onboarding/Views/OnboardingQuestionThree.tsx
  src/Components/Onboarding/Views/OnboardingQuestionTwo.tsx
  src/Components/Onboarding/Views/OnboardingWelcome.tsx
  src/Components/SplitLayout.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#11049 feat(CX-2882): add Insights landing page
  src/Apps/Settings/Routes/Insights/Components/InsightsLandingPage.tsx
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
  src/__generated__/InsightsRoute_me.graphql.ts
  src/__generated__/settingsRoutes_InsightsRouteQuery.graphql.ts
Labels: Jira Synced

#11043 feat: add bonhams to PriceDB filters
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
Labels: Jira Synced

#11053 fix: cannot create SEPA bank account if collector already has saved US bank account
  src/Apps/Order/Routes/Payment/index.tsx
Labels: Jira Synced

#11044 chore(TX-686): Clean OrderApp from unused components
  src/Apps/Order/Components/TermsOfServiceCheckbox.tsx
Labels: Jira Synced

#11054 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11047 chore: decrease max height for dropdown activity panel
  src/Components/NavBar/Menus/NavBarNewNotifications.tsx
  src/Components/Notifications/NotificationsTabs.tsx
Labels: Jira Synced

#11060 feat(footer): Add caption to footer
  src/Components/Footer/FooterDownloadAppBanner.tsx
Labels: Merge On Green, Jira Synced

#11063 feat(art-quiz) hook welcome screen to art quiz interface
  src/Apps/ArtQuiz/ArtQuizApp.tsx
  src/Apps/ArtQuiz/ArtQuizContext/ArtQuizContext.tsx
  src/Components/ArtQuiz/Views/ArtQuizWelcome.tsx
Labels: Jira Synced

#11066 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
  src/__generated__/ArtistHeader_Test_Query.graphql.ts
  src/__generated__/ArtistInsightBadges_Test_Query.graphql.ts
  src/__generated__/ArtistInsightBadges_artist.graphql.ts
  src/__generated__/ArtistInsightPills_Test_Query.graphql.ts
  src/__generated__/ArtistInsightPills_artist.graphql.ts
Labels: Squash On Green

#11045 refactor(TX-685): Class components to FC in OrderApp
  src/Apps/Order/Components/OfferInput.tsx
  src/Apps/Order/Components/PhoneNumberForm.tsx
  src/Apps/Order/Components/RevealButton.tsx
  src/Apps/Order/Components/StickyFooter.tsx
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Components/__tests__/StickyFooter.jest.tsx
Labels: Jira Synced

#11070 fix: Remove subtitle from Insights Header
  src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
Labels: Jira Synced

#11056 feat(CX-2780): add back button to MyC Artwork details page
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkBackButton.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
Labels: Jira Synced

#11077 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11076 fix (PX-5256): Remove duplicated call to setShipping mutation on address changes
  src/Apps/Order/Routes/Shipping/index.tsx
Labels: Jira Synced

#11079 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11081 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
  src/__generated__/ArtistHeader_Test_Query.graphql.ts
  src/__generated__/ArtistInsightBadges_Test_Query.graphql.ts
  src/__generated__/ArtistInsightBadges_artist.graphql.ts
  src/__generated__/ArtistInsightPills_Test_Query.graphql.ts
  src/__generated__/ArtistInsightPills_artist.graphql.ts
Labels: Squash On Green

#11084 fix: adjust spasing, MyCollectionArtworkSWASectionMobileLayout component
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx
Labels: Jira Synced

#11087 chore: update date labels for activities
  src/Components/Notifications/__tests__/NotificationItem.jest.tsx
  src/Components/Notifications/__tests__/util.jest.ts
  src/Components/Notifications/util.ts
Labels: Jira Synced, Squash On Green
