Repository artsy/force, pull requests merged in 2022-03, with the labels that each got.

#9496 chore: Price DB copy update
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseMeta.tsx
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseSearch.tsx
Labels: Squash On Green

#9506 fix: Reset form on submission or cancel
  src/v2/Apps/_Preferences2/PreferencesApp.tsx
  src/v2/Apps/_Preferences2/__tests__/PreferencesApp.jest.tsx
Labels: Jira Synced

#9513 refactor: add featureFlags to SystemContext
  src/lib/featureFlags/FeatureFlagProvider.tsx
  src/lib/middleware/featureFlagMiddleware.ts
  src/v2/System/Router/Boot.tsx
  src/v2/System/Router/__tests__/buildClientApp.jest.tsx
  src/v2/System/Router/__tests__/buildServerApp.jest.tsx
  src/v2/System/Router/buildClientApp.tsx
  src/v2/System/Router/buildServerApp.tsx
  src/v2/System/Server/sharifyHelpers.ts
  src/v2/System/SystemContext.tsx
  src/v2/System/__tests__/useFeatureFlag.jest.tsx
  src/v2/System/useFeatureFlag.tsx
  src/v2/client.tsx
  src/v2/server.ts
Labels: Jira Synced

#9519 feat(GRO-755): implements ads
  package.json
  src/v2/Apps/Article/ArticleApp.tsx
  src/v2/Apps/Article/Components/ArticleAd/ArticleAd.story.tsx
  src/v2/Apps/Article/Components/ArticleAd/ArticleAd.tsx
  src/v2/Apps/Article/Components/ArticleAd/index.ts
  src/v2/Apps/Article/Components/ArticleAd/types.ts
  src/v2/Apps/Article/Components/ArticleBody.tsx
  src/v2/Apps/Article/Components/ArticleByline.tsx
  src/v2/Apps/Article/Components/ArticleHTML.tsx
  src/v2/Apps/Article/Components/ArticleVideo.tsx
  src/v2/Utils/Hooks/useSizeAndPosition.ts
  src/v2/__generated__/ArticleBody_test_Query.graphql.ts
  src/v2/__generated__/ArticleByline_article.graphql.ts
  src/v2/__generated__/ArticleInfiniteScrollQuery.graphql.ts
  src/v2/__generated__/NewsIndexArticlesQuery.graphql.ts
  src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
  src/v2/__generated__/articlesRoutes_NewsQuery.graphql.ts
  yarn.lock
Labels: Merge On Green

#9471 feat(FX-3767): Use user’s preferred metric setting for size filter and saved search alerts
  src/v2/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/Artist/artistRoutes.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter.jest.tsx
  src/v2/Components/ArtworkFilter/Utils/__tests__/metrics.jest.ts
  src/v2/Components/ArtworkFilter/Utils/isDefaultFilter.tsx
  src/v2/Components/ArtworkFilter/Utils/metrics.ts
  src/v2/Components/SavedSearchAlert/Components/SavedSearchAlertArtworkGridFilterPills.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertContext.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/v2/Components/SavedSearchAlert/Utils/extractPills.ts
  src/v2/__generated__/ArtistArtworkFilter_me.graphql.ts
  src/v2/__generated__/ArtistWorksForSaleRoute_me.graphql.ts
  src/v2/__generated__/SavedSearchAlertEditFormQuery.graphql.ts
  src/v2/__generated__/SavedSearchAlertEditForm_Test_Query.graphql.ts
  src/v2/__generated__/SavedSearchAlertEditForm_me.graphql.ts
  src/v2/__generated__/SavedSearchAlertEditForm_savedSearch.graphql.ts
  src/v2/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#9486 feat(FX-3759): add slider for price filter
  .secrets.baseline
  package.json
  src/config.ts
  src/desktop/apps/auction/components/artwork_browser/sidebar/rc_slider.styl
  src/lib/setup_sharify.js
  src/typings/sharify.d.ts
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilterNew.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilterNew.jest.tsx
  src/v2/Components/Range.tsx
  src/v2/System/Server/sharifyHelpers.ts
  yarn.lock
Labels: Jira Synced

#9515 feat: change low offer modal in offer submission page
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
Labels: Jira Synced

#9508 fix: conversation list cut off
  src/v2/Apps/Conversation/Components/ConversationList.tsx
Labels: Jira Synced

#9531 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9539 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9540 fix: changes focus visible outline color to blue
  src/v2/Components/FocusVisible.tsx
Labels: Merge On Green

#9541 ci(notifications): Update slack message to be more clear
  .circleci/config.yml
Labels: Squash On Green

#9542 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/OtherAuctionsQuery.graphql.ts
Labels: Squash On Green

#9548 test(geocoding): add test selector for Integrity
  src/v2/Apps/Shows/Components/ShowsHeader.tsx
Labels: Squash On Green

#9535 fix: TX-66 - gracefully handle orders with unpublished artworks.
  src/v2/Apps/Order/Components/ArtworkSummaryItem.tsx
  src/v2/Apps/Order/OrderApp.tsx
  src/v2/Apps/Order/Utils/offerItemExtractor.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/__generated__/AcceptTestQuery.graphql.ts
  src/v2/__generated__/ArtworkSummaryItem_order.graphql.ts
  src/v2/__generated__/CounterTestQuery.graphql.ts
  src/v2/__generated__/NewPaymentTestQuery.graphql.ts
  src/v2/__generated__/Offer2TestQuery.graphql.ts
  src/v2/__generated__/OfferTestQuery.graphql.ts
  src/v2/__generated__/PaymentTestQuery.graphql.ts
  src/v2/__generated__/RejectTestQuery.graphql.ts
  src/v2/__generated__/RespondCounterOfferMutation.graphql.ts
  src/v2/__generated__/RespondTestQuery.graphql.ts
  src/v2/__generated__/ReviewTestQuery.graphql.ts
  src/v2/__generated__/ShippingTestQuery.graphql.ts
  src/v2/__generated__/StatusQuery.graphql.ts
  src/v2/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/v2/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/v2/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/v2/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/v2/__generated__/orderRoutes_RejectQuery.graphql.ts
  src/v2/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/v2/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/v2/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/v2/__generated__/orderRoutes_StatusQuery.graphql.ts
Labels: Jira Synced

#9566 feat: Add price floor to trending lots rail GRO-833
  src/v2/Apps/Auctions/Components/TrendingLotsRail.tsx
  src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts
  src/v2/__generated__/TrendingLotsRail_Test_Query.graphql.ts
  src/v2/__generated__/TrendingLotsRail_viewer.graphql.ts
  src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
Labels: Merge On Green

#9567 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9562 GRO-862: Signed out user flow error for preference center
  src/v2/Apps/_Preferences2/PreferencesApp.tsx
  src/v2/Apps/_Preferences2/preferencesRoutes.tsx
  src/v2/Apps/_Preferences2/useEditNotificationPreferences.tsx
  src/v2/__generated__/PreferencesApp_viewer.graphql.ts
  src/v2/__generated__/preferencesRoutes_PreferencesQuery.graphql.ts
  src/v2/__generated__/useEditNotificationPreferencesMutation.graphql.ts
Labels: Jira Synced

#9568 GRO-852 & GRO-857: SEO Updates for Articles and Price Database
  src/v2/Apps/Articles/ArticlesApp.tsx
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseMeta.tsx
Labels: Jira Synced

#9554 feat: remove helper
  src/v2/Apps/Conversation/Components/ReviewOfferCTA.tsx
Labels: Merge On Green

#9577 fix: Use singular form in page title GRO-865
  src/v2/Apps/_Preferences2/PreferencesApp.tsx
  src/v2/Apps/_Preferences2/__tests__/PreferencesApp.jest.tsx
Labels: Merge On Green

#9575 chore: Removed usage of Make Offer On All Eligible Artworks flag
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial2.jest.tsx
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Order/Routes/Review/index.tsx
  src/v2/Apps/Order/Routes/Status/index.tsx
  src/v2/Apps/Order/Routes/__fixtures__/MutationResults/submitOfferOrder.ts
  src/v2/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Status.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCommercial.ts
  src/v2/__generated__/ReviewSubmitOfferOrderMutation.graphql.ts
Labels: Jira Synced, Squash On Green

#9578 fix: Remove unused dep
  src/v2/Apps/Order/Routes/Review/index.tsx
Labels: Squash On Green

#9582 Updated: Preference Center copy
  src/v2/Apps/_Preferences2/PreferencesApp.tsx
Labels: Merge On Green

#9563 [GRO-834] add Trove Rail to the Artsy homepage
  src/v2/Apps/Home/Components/HomeTroveArtworksRail.tsx
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/Apps/Home/__tests__/HomeTroveArtworksRail.jest.tsx
  src/v2/__generated__/HomeTroveArtworksRailQuery.graphql.ts
  src/v2/__generated__/HomeTroveArtworksRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeTroveArtworksRail_viewer.graphql.ts
Labels: Jira Synced

#9585 fix: Use artwork connection for trove GRO-834
  src/v2/Apps/Home/Components/HomeTroveArtworksRail.tsx
  src/v2/Apps/Home/__tests__/HomeTroveArtworksRail.jest.tsx
  src/v2/__generated__/HomeTroveArtworksRailQuery.graphql.ts
  src/v2/__generated__/HomeTroveArtworksRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeTroveArtworksRail_viewer.graphql.ts
Labels: Merge On Green

#9590 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9584 Deploy
  data/schema.graphql
  package.json
  src/v2/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebar.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/v2/Apps/Fairs/Routes/FairsIndex.tsx
  src/v2/Apps/Home/Components/HomeAuctionLotsRail.tsx
  src/v2/Apps/Home/Components/HomeTroveArtworksRail.tsx
  src/v2/Apps/Home/__tests__/HomeTroveArtworksRail.jest.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/v2/Components/SavedSearchAlert/Utils/__tests__/getNamePlaceholder.jest.ts
  src/v2/Components/SavedSearchAlert/Utils/getNamePlaceholder.tsx
  src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
  src/v2/__generated__/HomeTroveArtworksRailQuery.graphql.ts
  src/v2/__generated__/HomeTroveArtworksRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeTroveArtworksRail_viewer.graphql.ts
  src/v2/__generated__/SavedSearchAlertListItem_item.graphql.ts
  src/v2/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
  src/v2/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
  src/v2/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts
  src/v2/jest.envSetup.ts
  yarn.lock
Labels: Jira Synced

#9555 feat: doesn't display modal when price options are visible
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
Labels: Jira Synced

#9593 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/CreateConsignSubmissionMutation.graphql.ts
Labels: Squash On Green

#9538 feat(FX-3774): Setup QA merchandising A/B test
  src/desktop/components/split_test/running_tests.coffee
  src/desktop/components/split_test/splitTestMiddleware.ts
  src/lib/middleware/__tests__/redisPageCache.jest.ts
  src/lib/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts
  src/lib/setup_sharify.js
  src/middleware.ts
  src/typings/sharify.d.ts
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/Utils/__tests__/getSelectedFiltersCounts.jest.ts
  src/v2/System/Analytics/__tests__/trackingMiddleware.jest.ts
  src/v2/System/Analytics/trackExperimentViewed.tsx
  src/v2/System/Analytics/trackingMiddleware.ts
  src/v2/System/Router/buildClientApp.tsx
  src/v2/System/Server/sharifyHelpers.ts
  src/v2/Utils/__tests__/merchandisingTrial.jest.ts
  src/v2/Utils/merchandisingTrial.ts
Labels: Jira Synced

#9603 Deploy
  docs/adding_a_segment_destination.md
  docs/best_practices.md
  package.json
  src/desktop/components/split_test/running_tests.coffee
  src/desktop/components/split_test/splitTestMiddleware.ts
  src/lib/middleware/__tests__/redisPageCache.jest.ts
  src/lib/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts
  src/lib/setup_sharify.js
  src/middleware.ts
  src/typings/sharify.d.ts
  src/v2/Apps/Article/Components/ArticleBody.tsx
  src/v2/Apps/Article/Components/ArticleByline.tsx
  src/v2/Apps/Article/Components/ArticleHTML.tsx
  src/v2/Apps/Article/Components/ArticleHeader.tsx
  src/v2/Apps/Article/Components/ArticleInfiniteScroll.tsx
  src/v2/Apps/Article/Components/ArticleSeries.tsx
  src/v2/Apps/Article/Components/ArticleSeriesItem.tsx
  src/v2/Apps/Article/Components/ArticleVideo.tsx
  src/v2/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGallery.tsx
  src/v2/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryCaption.tsx
  src/v2/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryFigure.tsx
  src/v2/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryResponsiveBox.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollection.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionImageSet.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionText.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionVideo.tsx
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
  src/v2/Apps/Auction2/Hooks/useAuctionTracking.ts
  src/v2/Components/ArticleShare.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/Utils/__tests__/getSelectedFiltersCounts.jest.ts
  src/v2/Components/EntityTooltip/EntityTooltip.tsx
  src/v2/Components/FullBleedHeader.tsx
  src/v2/System/Analytics/__tests__/trackingMiddleware.jest.ts
  src/v2/System/Analytics/trackExperimentViewed.tsx
  src/v2/System/Analytics/trackingMiddleware.ts
  src/v2/System/Router/buildClientApp.tsx
  src/v2/System/Server/sharifyHelpers.ts
  src/v2/Utils/Hooks/useSizeAndPosition.ts
  src/v2/Utils/__tests__/merchandisingTrial.jest.ts
  src/v2/Utils/merchandisingTrial.ts
  src/v2/__generated__/ArticleBody_article.graphql.ts
  src/v2/__generated__/ArticleBody_test_Query.graphql.ts
  src/v2/__generated__/ArticleInfiniteScrollQuery.graphql.ts
  src/v2/__generated__/ArticleSectionVideo_section.graphql.ts
  src/v2/__generated__/ArticleSeriesItem_article.graphql.ts
  src/v2/__generated__/ArticleSeries_article.graphql.ts
  src/v2/__generated__/ArticleSeries_test_Query.graphql.ts
  src/v2/__generated__/ArticleVideo_article.graphql.ts
  src/v2/__generated__/ArticleVideo_test_Query.graphql.ts
  src/v2/__generated__/ArticleZoomGalleryCaption_figure.graphql.ts
  src/v2/__generated__/ArticleZoomGalleryFigure_figure.graphql.ts
  src/v2/__generated__/ArticleZoomGalleryQuery.graphql.ts
  src/v2/__generated__/NewsIndexArticlesQuery.graphql.ts
  src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
  src/v2/__generated__/articlesRoutes_NewsQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#9608 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9607 fix [CX-2424]: Hide your gallery intro from the collector profile
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/useAddArtistYouCollect.ts
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/useRemoveArtistYouCollect.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileYourGalleryIntro.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileYourGalleryIntro.jest.tsx
  src/v2/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
  src/v2/Utils/Hooks/Mutations/useUpdateMyUserProfile.ts
  src/v2/__generated__/SettingsEditProfileRoute_me.graphql.ts
  src/v2/__generated__/SettingsEditProfileYourGalleryIntro_Test_Query.graphql.ts
  src/v2/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts
  src/v2/__generated__/useAddArtistYouCollectMutation.graphql.ts
  src/v2/__generated__/useRemoveArtistYouCollectMutation.graphql.ts
  src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
Labels: Jira Synced

#9609 feat: Update Price DB proposition
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
Labels: Squash On Green

#9611 Deploy
  data/schema.graphql
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/useAddArtistYouCollect.ts
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/useRemoveArtistYouCollect.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileYourGalleryIntro.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileYourGalleryIntro.jest.tsx
  src/v2/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
  src/v2/Utils/Hooks/Mutations/useUpdateMyUserProfile.ts
  src/v2/__generated__/SettingsEditProfileRoute_me.graphql.ts
  src/v2/__generated__/SettingsEditProfileYourGalleryIntro_Test_Query.graphql.ts
  src/v2/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts
  src/v2/__generated__/useAddArtistYouCollectMutation.graphql.ts
  src/v2/__generated__/useRemoveArtistYouCollectMutation.graphql.ts
  src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
Labels: Jira Synced

#9612 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9615 fix(GRO-880): Fleshes out article meta tags
  src/v2/Apps/Article/ArticleApp.tsx
  src/v2/Apps/Article/Components/ArticleMetaTags.tsx
  src/v2/Components/MetaTags.tsx
  src/v2/Components/__tests__/MetaTags.jest.tsx
  src/v2/__generated__/ArticleApp_article.graphql.ts
  src/v2/__generated__/ArticleMetaTags_article.graphql.ts
  src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
Labels: Merge On Green

#9619 chore(auction2): Last QA
  src/v2/Apps/Auction2/Components/Form/Utils/validationSchemas.ts
  src/v2/Apps/Auction2/Hooks/__tests__/useCreateTokenAndSubmit.jest.tsx
  src/v2/Apps/Auction2/Hooks/useCreateTokenAndSubmit.ts
  src/v2/Apps/Auction2/Queries/useRefreshUserData.ts
  src/v2/Apps/Auction2/Routes/Auction2RegistrationRoute.tsx
  src/v2/Apps/Auction2/Routes/Bid/Auction2BidRoute.tsx
  src/v2/Apps/Auction2/Routes/Bid/Components/AuctionLotInfo.tsx
  src/v2/__generated__/useRefreshUserDataQuery.graphql.ts
Labels: Merge On Green

#9624 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9631 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9639 chore: pass OwnerType to SavedSearchEntity
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButton.tsx
  src/v2/Components/SavedSearchAlert/Components/__tests__/CreateAlertButton.jest.tsx
  src/v2/Components/SavedSearchAlert/Components/__tests__/SavedSearchAlertArtworkGridFilterPills.jest.tsx
  src/v2/Components/SavedSearchAlert/Utils/__tests__/savedSearchCriteria.jest.ts
  src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
  src/v2/Components/SavedSearchAlert/types.ts
Labels: Squash On Green

#9644 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/CreateConsignSubmissionMutation.graphql.ts
Labels: Squash On Green

#9633 chore:update time stamp for auctions detail and add cascading interval label
  src/v2/Apps/Auction/Components/AuctionDetails/AuctionDetails.tsx
  src/v2/Apps/Auction/Components/AuctionDetails/__tests__/AuctionDetails.jest.tsx
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionDetailsTestQuery.graphql.ts
  src/v2/__generated__/AuctionDetails_sale.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
Labels: Squash On Green, Bidding Engine

#9635 Deploy
  data/schema.graphql
  docs/unleash_a-b_testing.md
  package.json
  src/lib/passport/lib/passport/index.js
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/CreateArtworkAlertSection.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/v2/Apps/Auction/Routes/Bid/useSubmitBid.ts
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/index.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx
  src/v2/Components/SavedSearchAlert/Components/SavedSearchAlertArtworkGridFilterPills.tsx
  src/v2/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButton.tsx
  src/v2/Components/SavedSearchAlert/Components/__tests__/CreateAlertButton.jest.tsx
  src/v2/Components/SavedSearchAlert/Components/__tests__/SavedSearchAlertArtworkGridFilterPills.jest.tsx
  src/v2/Components/SavedSearchAlert/DownloadAppBanner.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertContext.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/v2/Components/SavedSearchAlert/Utils/__tests__/savedSearchCriteria.jest.ts
  src/v2/Components/SavedSearchAlert/Utils/extractPills.ts
  src/v2/Components/SavedSearchAlert/Utils/savedSearchCriteria.tsx
  src/v2/Components/SavedSearchAlert/__tests__/DownloadAppBanner.jest.tsx
  src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
  src/v2/Components/SavedSearchAlert/__tests__/extractPills.jest.ts
  src/v2/Components/SavedSearchAlert/__tests__/extractPills.ts
  src/v2/Components/SavedSearchAlert/types.ts
  src/v2/System/useFeatureFlag.tsx
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/v2/__generated__/CreateArtworkAlertSection_Test_Query.graphql.ts
  src/v2/__generated__/CreateArtworkAlertSection_artwork.graphql.ts
  src/v2/__generated__/CreateConsignSubmissionMutation.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#9648 fix(auction): corrects display of tz in production
  src/v2/Apps/Auction/Components/AuctionDetails/__tests__/AuctionDetails.jest.tsx
  src/v2/__generated__/CreateConsignSubmissionMutation.graphql.ts
Labels: Merge On Green

#9650 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ArtistSeriesApp_artistSeries.graphql.ts
  src/v2/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/v2/__generated__/ArtistWorksForSaleRoute_artist.graphql.ts
  src/v2/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/v2/__generated__/AuctionArtworkFilterTestQuery.graphql.ts
  src/v2/__generated__/AuctionArtworkFilter_viewer.graphql.ts
  src/v2/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/v2/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/v2/__generated__/Collection_collection.graphql.ts
  src/v2/__generated__/FairArtworksQuery.graphql.ts
  src/v2/__generated__/FairArtworks_Query.graphql.ts
  src/v2/__generated__/FairArtworks_fair.graphql.ts
  src/v2/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/v2/__generated__/GeneArtworkFilter_Query.graphql.ts
  src/v2/__generated__/GeneArtworkFilter_gene.graphql.ts
  src/v2/__generated__/GeneShow_Test_Query.graphql.ts
  src/v2/__generated__/SavedSearchAlertEditForm_Test_Query.graphql.ts
  src/v2/__generated__/SavedSearchAlertEditForm_artworksConnection.graphql.ts
  src/v2/__generated__/SearchResultsArtworks_Query.graphql.ts
  src/v2/__generated__/SearchResultsArtworks_viewer.graphql.ts
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/ShowArtworksQuery.graphql.ts
  src/v2/__generated__/TagApp_Test_Query.graphql.ts
  src/v2/__generated__/TagArtworkFilterQuery.graphql.ts
  src/v2/__generated__/TagArtworkFilter_Query.graphql.ts
  src/v2/__generated__/TagArtworkFilter_tag.graphql.ts
  src/v2/__generated__/WorksQuery.graphql.ts
  src/v2/__generated__/Works_Query.graphql.ts
  src/v2/__generated__/Works_partner.graphql.ts
  src/v2/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
  src/v2/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/collectRoutes_CollectionQuery.graphql.ts
  src/v2/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairArtworksQuery.graphql.ts
  src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts
  src/v2/__generated__/partnerRoutes_WorksQuery.graphql.ts
  src/v2/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
  src/v2/__generated__/tagRoutes_TagQuery.graphql.ts
Labels: Squash On Green

#9627 [GRO-850] add collector specialists team to meet-the-specialists
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Merge On Green, Jira Synced

#9626 add basic pull request template to force
  pull_request_template.md
Labels: Merge On Green

#9654 Launch preference center
  src/v2/Apps/Preferences/PreferencesApp.tsx
  src/v2/Apps/Preferences/__tests__/PreferencesApp.jest.tsx
  src/v2/Apps/Preferences/preferencesRoutes.tsx
  src/v2/Apps/Preferences/useEditNotificationPreferences.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsEmailPreferences/SettingsEditSettingsEmailPreferences.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsEmailPreferences/useUpdateSettingsEmailPreferences.ts
  src/v2/Apps/Settings/Routes/EditSettings/Components/__tests__/SettingsEditSettingsEmailPreferences.jest.tsx
  src/v2/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
  src/v2/Apps/Unsubscribe/Components/UnsubscribeLoggedIn.tsx
  src/v2/Apps/Unsubscribe/Components/UnsubscribeLoggedOut.tsx
  src/v2/Apps/Unsubscribe/UnsubscribeApp.tsx
  src/v2/Apps/Unsubscribe/__tests__/UnsubscribeApp.jest.tsx
  src/v2/Apps/Unsubscribe/unsubscribeRoutes.tsx
  src/v2/Apps/Unsubscribe/useUnsubscribeEmailPreferences.ts
  src/v2/__generated__/SettingsEditSettingsEmailPreferences_Test_Query.graphql.ts
  src/v2/__generated__/SettingsEditSettingsEmailPreferences_me.graphql.ts
  src/v2/__generated__/SettingsEditSettingsRoute_me.graphql.ts
  src/v2/__generated__/UnsubscribeApp_Test_Query.graphql.ts
  src/v2/__generated__/UnsubscribeApp_me.graphql.ts
  src/v2/__generated__/UnsubscribeLoggedIn_me.graphql.ts
  src/v2/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
  src/v2/__generated__/unsubscribeRoutes_UnsubscribeQuery.graphql.ts
  src/v2/__generated__/useUnsubscribeEmailPreferencesMutation.graphql.ts
  src/v2/__generated__/useUpdateSettingsEmailPreferencesMutation.graphql.ts
  src/v2/routes.tsx
Labels: Jira Synced

#9655 fix(auction): Use artwork grid
  .secrets.baseline
  src/v2/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
  src/v2/Apps/FeatureAKG/__tests__/FeatureAKGRoute.jest.tsx
  src/v2/Components/Artwork/Badge.tsx
  src/v2/Components/Artwork/Details.tsx
  src/v2/Components/Artwork/FlatGridItem.tsx
  src/v2/Components/ArtworkFilter/__tests__/fixtures/ArtworkFilter.fixture.tsx
  src/v2/Components/ArtworkGrid/ArtworkGrid.tsx
  src/v2/Components/ArtworkGrid/ArtworkGridContext.tsx
  src/v2/Components/ArtworkGrid/__tests__/ArtworkGrid.jest.tsx
  src/v2/Components/ArtworkGrid/__tests__/ArtworkGridFixture.ts
  src/v2/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/v2/__generated__/ArtistSeriesArtworksFilter_Query.graphql.ts
  src/v2/__generated__/ArtworkGridExampleQuery.graphql.ts
  src/v2/__generated__/ArtworkGrid_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkGrid_artworks.graphql.ts
  src/v2/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/v2/__generated__/AuctionArtworkFilterTestQuery.graphql.ts
  src/v2/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/v2/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/v2/__generated__/FairArtworksQuery.graphql.ts
  src/v2/__generated__/FairArtworks_Query.graphql.ts
  src/v2/__generated__/FeatureAKGRoute_Test_Query.graphql.ts
  src/v2/__generated__/FlatGridItem_artwork.graphql.ts
  src/v2/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/v2/__generated__/GeneArtworkFilter_Query.graphql.ts
  src/v2/__generated__/GeneShow_Test_Query.graphql.ts
  src/v2/__generated__/OtherWorksQuery.graphql.ts
  src/v2/__generated__/RelatedWorksArtworkGridRefetchQuery.graphql.ts
  src/v2/__generated__/SearchResultsArtworks_Query.graphql.ts
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowArtworksQuery.graphql.ts
  src/v2/__generated__/ShowArtworks_Test_Query.graphql.ts
  src/v2/__generated__/TagApp_Test_Query.graphql.ts
  src/v2/__generated__/TagArtworkFilterQuery.graphql.ts
  src/v2/__generated__/TagArtworkFilter_Query.graphql.ts
  src/v2/__generated__/WorksForYouApp_test_Query.graphql.ts
  src/v2/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
  src/v2/__generated__/WorksForYouFeedPaginationQuery.graphql.ts
  src/v2/__generated__/WorksQuery.graphql.ts
  src/v2/__generated__/Works_Query.graphql.ts
  src/v2/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
  src/v2/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/collectRoutes_CollectionQuery.graphql.ts
  src/v2/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/fairRoutes_FairArtworksQuery.graphql.ts
  src/v2/__generated__/featureAKGRoutes_FeatureAKGQuery.graphql.ts
  src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts
  src/v2/__generated__/partnerRoutes_WorksQuery.graphql.ts
  src/v2/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
  src/v2/__generated__/tagRoutes_TagQuery.graphql.ts
  src/v2/__generated__/worksForYouRoutes_TopLevelQuery.graphql.ts
  src/v2/jest.envSetup.ts
Labels: Merge On Green

#9660 fix(auction): misc bugs
  src/v2/Apps/Auction/Routes/AuctionRegistrationRoute.tsx
  src/v2/Apps/Auction/Routes/__tests__/AuctionRegistrationRoute.jest.tsx
  src/v2/Apps/Auction/auctionRoutes.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/__generated__/AuctionRegistrationRouteTestQuery.graphql.ts
  src/v2/__generated__/AuctionRegistrationRoute_me.graphql.ts
  src/v2/__generated__/auctionRoutes_RegisterRouteQuery.graphql.ts
Labels: Merge On Green

#9659 [GRO-853 & 854]: update metatags for /galleries and /institutions for SEO
  src/v2/Apps/Partners/Routes/GalleriesRoute.tsx
  src/v2/Apps/Partners/Routes/InstitutionsRoute.tsx
Labels: Jira Synced

#9663 fix(auction): fixes time display (again)
  src/v2/Apps/Auction/Components/AuctionDetails/AuctionDetails.tsx
  src/v2/Apps/Auction/Components/AuctionDetails/AuctionDetailsStartTime.tsx
  src/v2/Apps/Auction/Components/AuctionDetails/__tests__/AuctionDetails.jest.tsx
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionDetailsStartTimeQuery.graphql.ts
  src/v2/__generated__/AuctionDetailsStartTime_sale.graphql.ts
  src/v2/__generated__/AuctionDetailsTestQuery.graphql.ts
  src/v2/__generated__/AuctionDetails_sale.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
Labels: Squash On Green

#9666 chore: update slider handle
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilterNew.tsx
  src/v2/Components/Range.tsx
Labels: Jira Synced, Squash On Green

#9668 fix(auction): updates spec
  src/v2/Apps/Auction/Components/__tests__/AuctionArtworkFilter.jest.tsx
Labels: Merge On Green

#9670 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9671 fix(GRO-892): Redirect from the old /sale path to /auction
  src/v2/Apps/Auction/auctionRoutes.tsx
Labels: Merge On Green, Jira Synced

#9673 feat(auctions): Add associated sale rail item
  src/v2/Apps/Auction/AuctionApp.tsx
  src/v2/Apps/Auction/Components/AuctionAssociatedSale.tsx
  src/v2/Apps/Auction/Components/__tests__/AuctionAssociatedSale.jest.tsx
  src/v2/Apps/Auction/__tests__/AuctionApp.jest.tsx
  src/v2/__generated__/ArtistSeriesApp_artistSeries.graphql.ts
  src/v2/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/v2/__generated__/ArtistWorksForSaleRoute_artist.graphql.ts
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionApp_sale.graphql.ts
  src/v2/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/v2/__generated__/AuctionArtworkFilter_viewer.graphql.ts
  src/v2/__generated__/AuctionAssociatedSaleTestQuery.graphql.ts
  src/v2/__generated__/AuctionAssociatedSale_sale.graphql.ts
  src/v2/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/v2/__generated__/Collection_collection.graphql.ts
  src/v2/__generated__/FairArtworksQuery.graphql.ts
  src/v2/__generated__/FairArtworks_fair.graphql.ts
  src/v2/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/v2/__generated__/GeneArtworkFilter_Query.graphql.ts
  src/v2/__generated__/SearchResultsArtworks_viewer.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/TagArtworkFilterQuery.graphql.ts
  src/v2/__generated__/TagArtworkFilter_tag.graphql.ts
  src/v2/__generated__/Works_Query.graphql.ts
  src/v2/__generated__/Works_partner.graphql.ts
  src/v2/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
  src/v2/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
Labels: Jira Synced

#9675 notify #dev on failed prod deploys
  .circleci/config.yml
Labels: Jira Synced

#9678 (Fix): add view all artworks CTA to trove rail
  src/v2/Apps/Home/Components/HomeTroveArtworksRail.tsx
Labels: Merge On Green, Jira Synced

#9664 feat(CX-2409): When the user has the SWA<>MYCollection feature enabled - show updated copy
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
Labels: Jira Synced

#9682 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9686 fix(CX-2450): check if the user is logged in or not when showing updated copy after artwork submission | Force
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
Labels: Jira Synced, Squash On Green

#9681 Deploy
  data/schema.graphql
  package.json
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
  src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeader.tsx
  src/v2/Apps/Fairs/fairsRoutes.tsx
  src/v2/Apps/Home/Components/HomeTroveArtworksRail.tsx
  src/v2/Components/NavBar/NavBar.tsx
  src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/v2/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
  src/v2/Components/NavBar/__tests__/NavBarTracking.jest.tsx
  src/v2/Components/Timer.tsx
  src/v2/Components/__tests__/Timer.jest.tsx
  src/v2/Utils/Hooks/useTimer.tsx
  yarn.lock
Labels: Jira Synced

#9688 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9651 feat(FX-3824): use real data for histogram
  .secrets.baseline
  src/config.ts
  src/lib/setup_sharify.js
  src/typings/sharify.d.ts
  src/v2/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilterNew.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilterNew.jest.tsx
  src/v2/System/Server/sharifyHelpers.ts
Labels: Jira Synced, Squash On Green

#9690 fix: Fix timer to only turn red at 2 mins or less
  src/v2/Components/LotTimer.tsx
  src/v2/Components/__tests__/LotTimer.jest.tsx
Labels: Merge On Green, Bidding Engine

#9698 fix: update detect-secrets baseline
  .secrets.baseline
Labels: Merge On Green

#9694 fix(auction): cleans up associated sale thumbnail
  package.json
  src/v2/Apps/Auction/AuctionApp.tsx
  src/v2/Apps/Auction/Components/AuctionArtworkFilter.tsx
  src/v2/Apps/Auction/Components/AuctionAssociatedSale.tsx
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionAssociatedSaleTestQuery.graphql.ts
  src/v2/__generated__/AuctionAssociatedSale_sale.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
  yarn.lock
Labels: Merge On Green

#9687 fix:Update active bids display to respect closed sales or cascading lots
  src/v2/Apps/Auction/AuctionApp.tsx
  src/v2/Apps/Auction/Components/AuctionActiveBids.tsx
  src/v2/Apps/Auction/Components/__tests__/AuctionActiveBids.jest.tsx
  src/v2/Apps/Auction/__tests__/AuctionApp.jest.tsx
  src/v2/__generated__/AuctionActiveBidsRefetchQuery.graphql.ts
  src/v2/__generated__/AuctionActiveBidsTestQuery.graphql.ts
  src/v2/__generated__/AuctionActiveBids_me.graphql.ts
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionApp_me.graphql.ts
  src/v2/__generated__/AuctionApp_sale.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/useBidderPositionQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
Labels: Jira Synced, Bidding Engine

#9693 feat(NX-3091): Make "Price on Request" text sentence case
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx
  src/v2/Components/Artwork/Details.tsx
  src/v2/Components/Artwork/__tests__/Details.jest.tsx
Labels: Jira Synced

#9695 chore: add horizontal offsets for histogram
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilterNew.tsx
Labels: Jira Synced

#9691 fix(NX-3089): Make sure the conversation's side drawer shows correct order status.
  src/v2/Apps/Conversation/Components/DetailsSidebar.tsx
  src/v2/Apps/Conversation/__tests__/DetailsSidebar.jest.tsx
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/DetailsSidebar_Test_Query.graphql.ts
  src/v2/__generated__/DetailsSidebar_conversation.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Jira Synced

#9646 feat(FX-3788): Add unauthenticated signup/login prompts to Create Alert button
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/CreateArtworkAlertSection.jest.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/SavedSearchAlert/Components/SavedSearchAlertArtworkGridFilterPills.tsx
  src/v2/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButton.tsx
  src/v2/Components/SavedSearchAlert/Components/__tests__/SavedSearchAlertArtworkGridFilterPills.jest.tsx
  src/v2/Components/SavedSearchAlert/Components/__tests__/SavedSearchCreateAlertButton.jest.tsx
  src/v2/Components/SavedSearchAlert/Utils/__tests__/savedSearchCriteria.jest.ts
  src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
  src/v2/Components/SavedSearchAlert/types.ts
  src/v2/Utils/Hooks/useAuthIntent/index.ts
  src/v2/Utils/openAuthModal.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/CreateArtworkAlertSection_Test_Query.graphql.ts
  src/v2/__generated__/CreateArtworkAlertSection_artwork.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#9692 Deploy
  .secrets.baseline
  package.json
  src/config.ts
  src/lib/setup_sharify.js
  src/typings/sharify.d.ts
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/CreateArtworkAlertSection.jest.tsx
  src/v2/Apps/Auction/AuctionApp.tsx
  src/v2/Apps/Auction/Components/AuctionActiveBids.tsx
  src/v2/Apps/Auction/Components/AuctionArtworkFilter.tsx
  src/v2/Apps/Auction/Components/AuctionAssociatedSale.tsx
  src/v2/Apps/Auction/Components/AuctionDetails/CascadingEndTimesBanner.tsx
  src/v2/Apps/Auction/Components/__tests__/AuctionActiveBids.jest.tsx
  src/v2/Apps/Auction/__tests__/AuctionApp.jest.tsx
  src/v2/Apps/Conversation/Components/DetailsSidebar.tsx
  src/v2/Apps/Conversation/__tests__/DetailsSidebar.jest.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Components/Artwork/Details.tsx
  src/v2/Components/Artwork/__tests__/Details.jest.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilterNew.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/LotTimer.tsx
  src/v2/Components/SavedSearchAlert/Components/SavedSearchAlertArtworkGridFilterPills.tsx
  src/v2/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButton.tsx
  src/v2/Components/SavedSearchAlert/Components/__tests__/SavedSearchAlertArtworkGridFilterPills.jest.tsx
  src/v2/Components/SavedSearchAlert/Components/__tests__/SavedSearchCreateAlertButton.jest.tsx
  src/v2/Components/SavedSearchAlert/Utils/__tests__/savedSearchCriteria.jest.ts
  src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
  src/v2/Components/SavedSearchAlert/types.ts
  src/v2/Components/__tests__/LotTimer.jest.tsx
  src/v2/System/Server/sharifyHelpers.ts
  src/v2/Utils/Hooks/useAuthIntent/index.ts
  src/v2/Utils/openAuthModal.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/AuctionActiveBidsRefetchQuery.graphql.ts
  src/v2/__generated__/AuctionActiveBidsTestQuery.graphql.ts
  src/v2/__generated__/AuctionActiveBids_me.graphql.ts
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionApp_me.graphql.ts
  src/v2/__generated__/AuctionApp_sale.graphql.ts
  src/v2/__generated__/AuctionAssociatedSaleTestQuery.graphql.ts
  src/v2/__generated__/AuctionAssociatedSale_sale.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/CreateArtworkAlertSection_Test_Query.graphql.ts
  src/v2/__generated__/CreateArtworkAlertSection_artwork.graphql.ts
  src/v2/__generated__/DetailsSidebar_Test_Query.graphql.ts
  src/v2/__generated__/DetailsSidebar_conversation.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
  src/v2/__generated__/useBidderPositionQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#9703 fix: Switched isOfferableFromInquiry check to isOfferable
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/__tests__/Conversation.jest.tsx
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/ConversationPagination_Test_Query.graphql.ts
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Jira Synced

#9701 feat: Price DB 4th copy update
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
Labels: Jira Synced

#9707 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9702 enh: add rebuild to detect-secrets
  .circleci/config.yml
  .secrets.baseline
  package.json
  scripts/detect-secrets.sh
Labels: Jira Synced

#9706 chore(deps): downgrades palette
  package.json
  yarn.lock
Labels: Merge On Green

#9709 Deploy
  .circleci/config.yml
  .secrets.baseline
  data/schema.graphql
  package.json
  scripts/detect-secrets.sh
  src/desktop/components/split_test/running_tests.coffee
  src/lib/setup_sharify.js
  src/typings/sharify.d.ts
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/__tests__/Conversation.jest.tsx
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/Utils/__tests__/getSelectedFiltersCounts.jest.ts
  src/v2/System/Analytics/trackingMiddleware.ts
  src/v2/System/Router/buildClientApp.tsx
  src/v2/System/Server/sharifyHelpers.ts
  src/v2/Utils/__tests__/merchandisingTrial.jest.ts
  src/v2/Utils/merchandisingTrial.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/ConversationPagination_Test_Query.graphql.ts
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#9711 Revert "chore(deps): update dep typescript from 4.3.5 to v4.6.2"
  package.json
  yarn.lock
Labels: Merge On Green

#9714 feat: change copies from input field in Offer
  src/v2/Apps/Order/Components/MinPriceWarning.tsx
  src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
Labels: Jira Synced

#9716 feat(NOSF2): reverse order of options for range price
  src/v2/Apps/Order/Components/PriceOptions.tsx
  src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
Labels: Squash On Green

#9729 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/CreateConsignSubmissionMutation.graphql.ts
  src/v2/__generated__/UpdateConsignSubmissionMutation.graphql.ts
Labels: Squash On Green

#9728 chore: Price DB 4th copy update
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
Labels: Jira Synced

#9725 fix(settings): resets form after updates
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/useUpdateSettingsInformation.ts
  src/v2/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Jira Synced

#9730 Deploy
  package.json
  src/v2/Apps/Auction/Components/AuctionDetails/AuctionDetails.tsx
  src/v2/Apps/Auction/Components/AuctionDetails/AuctionDetailsStartTime.tsx
  src/v2/Apps/Auction/Components/AuctionDetails/SaleDetailTimer.tsx
  src/v2/Apps/Auction/Components/AuctionDetails/__tests__/SaleDetailTimer.jest.tsx
  src/v2/Apps/Auctions/Components/MyBids/MyBidsBidHeader.tsx
  src/v2/Apps/Auctions/Components/MyBids/MyBidsBidItem.tsx
  src/v2/Apps/Auctions/Components/MyBids/__tests__/MyBidsBidItem.jest.tsx
  src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/useUpdateSettingsInformation.ts
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionDetailsStartTimeQuery.graphql.ts
  src/v2/__generated__/AuctionDetailsStartTime_sale.graphql.ts
  src/v2/__generated__/AuctionDetailsTestQuery.graphql.ts
  src/v2/__generated__/AuctionDetails_sale.graphql.ts
  src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts
  src/v2/__generated__/MyBidsBidHeader_Test_Query.graphql.ts
  src/v2/__generated__/MyBidsBidHeader_sale.graphql.ts
  src/v2/__generated__/MyBidsBidItem_Test_Query.graphql.ts
  src/v2/__generated__/MyBidsBidItem_saleArtwork.graphql.ts
  src/v2/__generated__/MyBidsQuery.graphql.ts
  src/v2/__generated__/MyBids_Test_Query.graphql.ts
  src/v2/__generated__/SaleDetailTimer_sale.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
  src/v2/__generated__/useUpdateSettingsInformationMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#9736 fix(featureflags): return empty object regardless when setting up feature flags
  src/lib/middleware/featureFlagMiddleware.ts
Labels: Merge On Green

#9718 feat: remove clickable from low offer notice text
  src/v2/Apps/Order/Components/MinPriceWarning.tsx
  src/v2/Apps/Order/Components/PriceOptions.tsx
  src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
Labels: Jira Synced

#9724 refactor: add 'your alerts' to settings app
  src/lib/middleware/hardcodedRedirects.ts
  src/lib/middleware/userRequiredMiddleware.ts
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/v2/Apps/Settings/SettingsApp.tsx
  src/v2/Apps/Settings/settingsRoutes.tsx
  src/v2/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
  src/v2/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts
Labels: Jira Synced

#9743 chore(GRO-844): Don't send values that aren't used by Gravity
  data/schema.graphql
  src/v2/Apps/Preferences/PreferencesApp.tsx
  src/v2/__generated__/PreferencesApp_viewer.graphql.ts
  src/v2/__generated__/preferencesRoutes_PreferencesQuery.graphql.ts
  src/v2/__generated__/useEditNotificationPreferencesMutation.graphql.ts
Labels: Jira Synced

#9745 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/useEditNotificationPreferencesMutation.graphql.ts
Labels: Squash On Green

#9744 feat(GRO-856): shuffled featured partners carousel
  src/lib/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts
  src/v2/Apps/Partners/Components/PartnersFeaturedCarousel.tsx
  src/v2/Apps/Partners/Components/__tests__/PartnersFeaturedCarousel.jest.tsx
  src/v2/Apps/Partners/Routes/__tests__/GalleriesRoute.jest.tsx
  src/v2/Apps/Partners/Routes/__tests__/InstitutionsRoute.jest.tsx
  src/v2/Utils/Hooks/__tests__/useStableShuffle.jest.tsx
  src/v2/Utils/Hooks/useStableShuffle.ts
Labels: Merge On Green, Jira Synced

#9738 chore:update copy for active bids
  src/v2/Apps/Auction/Components/AuctionActiveBids.tsx
  src/v2/Apps/Auction/Components/__tests__/AuctionActiveBids.jest.tsx
  src/v2/Apps/Auction/Routes/Bid/Components/AuctionLotInfo.tsx
  src/v2/__generated__/AuctionActiveBidsRefetchQuery.graphql.ts
  src/v2/__generated__/AuctionActiveBidsTestQuery.graphql.ts
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionBidRouteQuery.graphql.ts
  src/v2/__generated__/AuctionBidRouteTestQuery.graphql.ts
  src/v2/__generated__/AuctionLotInfo_saleArtwork.graphql.ts
  src/v2/__generated__/auctionRoutes_BidRouteQuery.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/useBidderPositionQuery.graphql.ts
Labels: Merge On Green, Jira Synced

#9740 feat(TX-259): Update Stripe
  package.json
  yarn.lock
Labels: Jira Synced

#9752 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9753 Update metaphysics schema
  src/v2/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts
Labels: Squash On Green

#9757 fix(auction): prevents overflowing text from breaking out of column in Firefox
  src/v2/Components/ArtworkGrid/ArtworkGrid.tsx
Labels: Merge On Green

#9759 chore: use displayValue instead of value for filter criteria
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
  src/v2/__generated__/SavedSearchAlertListItem_item.graphql.ts
  src/v2/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
  src/v2/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
  src/v2/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts
  src/v2/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts
Labels: Squash On Green

#9762 fix(GRO-926): optimizes artist avatar; show cell
  src/v2/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
  src/v2/Apps/Artist/Components/ArtistHeader/__tests__/ArtistHeader.jest.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistCurrentShowsRail.tsx
  src/v2/__generated__/ArtistApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtistCurrentShowsRailQuery.graphql.ts
  src/v2/__generated__/ArtistCurrentShowsRail_Test_Query.graphql.ts
  src/v2/__generated__/ArtistCurrentShowsRail_artist.graphql.ts
  src/v2/__generated__/ArtistHeader_Test_Query.graphql.ts
  src/v2/__generated__/ArtistHeader_artist.graphql.ts
  src/v2/__generated__/artistRoutes_TopLevelQuery.graphql.ts
Labels: Jira Synced

#9572 chore: add MNTN tracking pixels
  src/desktop/components/main_layout/templates/scripts.jade
  src/v2/Apps/Components/AppShell.tsx
  src/v2/Components/Authentication/Views/SignUpForm.tsx
  src/v2/Components/MNTNTrackingPixel.tsx
  src/v2/Utils/Hooks/useLoadScript.ts
  src/v2/index.ejs
Labels: Merge On Green, Jira Synced

#9764 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9758 feat: added price histogram to the artist series page
  src/v2/Apps/ArtistSeries/artistSeriesRoutes.tsx
Labels: Jira Synced

#9766 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9769 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9778 Prefix Google maps key with PUBLIC_ to indicate that it's intentionally exposed in HTML and not a vulnerability
  .secrets.baseline
  src/config.ts
  src/desktop/components/geo/index.coffee
  src/desktop/components/util/google_maps.coffee
  src/desktop/components/util/test/google_maps.test.js
  src/desktop/test/models/partner_location.jest.ts
  src/lib/setup_sharify.js
  src/typings/sharify.d.ts
  src/v2/Apps/Partner/Components/PartnerContacts/partnerContactUtils.ts
  src/v2/Components/LocationAutocompleteInput.tsx
  src/v2/System/Server/sharifyHelpers.ts
Labels: Merge On Green, Jira Synced

#9770 chore: Hardcode cascading interval message copy and fix spacing
  src/v2/Apps/Auction/AuctionApp.tsx
  src/v2/Apps/Auction/Components/AuctionDetails/AuctionDetails.tsx
  src/v2/Apps/Auction/Components/AuctionDetails/CascadingEndTimesBanner.tsx
  src/v2/Apps/Auction/Hooks/Utils/helpers.ts
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionApp_sale.graphql.ts
  src/v2/__generated__/AuctionDetailsTestQuery.graphql.ts
  src/v2/__generated__/AuctionDetails_sale.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
Labels: Squash On Green

#9771 GRO-767: Supporting the Creation of "Women Owned" Gallery Attribute
  src/v2/Apps/Partner/PartnerApp.tsx
  src/v2/Components/EntityHeaders/EntityHeaderPartner.tsx
  src/v2/__generated__/PartnerCell_partner.graphql.ts
Labels: Jira Synced

#9780 slack notify dev when validate_production_schema fails
  .circleci/config.yml
Labels: Merge On Green, Jira Synced

#9782 Update metaphysics schema
  src/v2/__generated__/PartnerCell_partner.graphql.ts
Labels: Squash On Green

#9786 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9790 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green
