Repository artsy/force, pull requests merged in 2022-12, with the labels that each got.

#11460 feat(CX-3177): add saved and follows to collector profile
  src/Apps/CollectorProfile/Routes/SavesAndFollows/CollectorProfileSavesAndFollowsRoute.tsx
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/__generated__/CollectorProfileSavesAndFollowsRoute_me.graphql.ts
  src/__generated__/collectorProfileRoutes_SavesAndFollowsRouteQuery.graphql.ts
Labels: Jira Synced

#11467 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useCreateArtworkMutation.graphql.ts
  src/__generated__/useUpdateArtworkMutation.graphql.ts
Labels: Squash On Green

#11465 fix: broken link from artwork page to auction house
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetailsAboutTheWorkFromPartner.jest.tsx
  src/__generated__/ArtworkDetailsAboutTheWorkFromPartner_Test_Query.graphql.ts
  src/__generated__/ArtworkDetailsAboutTheWorkFromPartner_artwork.graphql.ts
  src/__generated__/ArtworkDetailsQuery.graphql.ts
  src/__generated__/ArtworkDetails_Test_Query.graphql.ts
Labels: Jira Synced, Squash On Green

#11475 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11484 Update timeout
  src/Apps/Home/Components/HomeContentCards/HomeContentCards.tsx
Labels: Merge On Green

#11474 feat(FX-4476): activity panel notifications counts
  src/Components/Notifications/NotificationItem.tsx
  src/Components/Notifications/__tests__/NotificationItem.jest.tsx
  src/__generated__/NotificationItem_item.graphql.ts
  src/__generated__/NotificationItem_test_Query.graphql.ts
  src/__generated__/NotificationsListNextQuery.graphql.ts
  src/__generated__/NotificationsListQuery.graphql.ts
  src/__generated__/NotificationsList_test_Query.graphql.ts
Labels: Jira Synced

#11488 fix: update Spacer props
  src/Apps/CollectorProfile/Components/CollectorProfileHeader/CollectorProfileHeader.tsx
Labels: Jira Synced

#11490 feat: Update info on specialist page GRO-1422
  src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Merge On Green

#11491 fix(cellpartnerartist): guard for artists without artworks
  src/Components/Cells/CellPartnerArtist.tsx
Labels: Merge On Green

#11492 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11384 feat(GRO-1437): rebuilds auth dialog
  src/Apps/Debug/DebugAuth.tsx
  src/Apps/Debug/debugRoutes.tsx
  src/Components/AuthDialog/AuthDialog.tsx
  src/Components/AuthDialog/AuthDialogContext.tsx
  src/Components/AuthDialog/Components/AuthDialogSocial.tsx
  src/Components/AuthDialog/Components/AuthTermsCheckboxes.tsx
  src/Components/AuthDialog/Hooks/__tests__/useAfterAuthenticationRedirect.jest.ts
  src/Components/AuthDialog/Hooks/useAfterAuthentication.ts
  src/Components/AuthDialog/Hooks/useAfterAuthenticationRedirect.ts
  src/Components/AuthDialog/Hooks/useElligibleForOnboarding.ts
  src/Components/AuthDialog/README.md
  src/Components/AuthDialog/Views/AuthDialogForgotPassword.tsx
  src/Components/AuthDialog/Views/AuthDialogLogin.tsx
  src/Components/AuthDialog/Views/AuthDialogSignUp.tsx
  src/Components/AuthDialog/Views/__tests__/AuthDialogForgotPassword.jest.tsx
  src/Components/AuthDialog/Views/__tests__/AuthDialogLogin.jest.tsx
  src/Components/AuthDialog/Views/__tests__/AuthDialogSignUp.jest.tsx
  src/Components/AuthDialog/index.ts
  src/Components/AuthDialog/useAuthDialog.tsx
  src/Utils/EnableRecaptcha.tsx
  src/Utils/Hooks/useAuthIntent/index.tsx
  src/Utils/__tests__/auth.jest.ts
  src/Utils/__tests__/sanitizeRedirect.jest.ts
  src/Utils/auth.ts
  src/Utils/recaptcha.ts
  src/Utils/sanitizeRedirect.ts
  src/__generated__/AuthDialogSignUpQuery.graphql.ts
  src/__generated__/AuthDialogSignUp_requestLocation.graphql.ts
Labels: Merge On Green

#11493 docs: best practices
  docs/best_practices.md
Labels: Jira Synced

#11503 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/UpdateConversationMutation.graphql.ts
Labels: Squash On Green

#11504 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11506 feat: add tracking to my collection landing page logged out
  src/Apps/Settings/Routes/MyCollection/Components/MyCollectionEmptyState.tsx
Labels: Jira Synced

#11511 fix(CX-322): /my-collection/artworks/new is opening for logged out user
  src/Server/middleware/userRequiredMiddleware.ts
Labels: Jira Synced, Squash On Green

#11510 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useAddCreditCardAndUpdateProfileMutation.graphql.ts
  src/__generated__/useCreateArtworkMutation.graphql.ts
  src/__generated__/useUpdateArtworkMutation.graphql.ts
  src/__generated__/useUpdateMyUserProfileMutation.graphql.ts
  src/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Squash On Green

#11505 feat(CX-3178): update account page
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileAboutYou.tsx
  src/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
  src/Apps/Settings/Routes/EditSettings/Components/__tests__/SettingsEditSettingsInformation.jest.tsx
  src/Apps/Settings/Routes/EditSettings/Components/useUpdateSettingsInformation.ts
  src/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
  src/__generated__/SettingsEditProfileRoute_me.graphql.ts
  src/__generated__/SettingsEditSettingsInformation_Test_Query.graphql.ts
  src/__generated__/SettingsEditSettingsInformation_me.graphql.ts
  src/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts
  src/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
  src/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Jira Synced, Squash On Green

#11513 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11512 docs: fix typo
  docs/best_practices.md
Labels: Merge On Green

#11515 docs: links
  docs/best_practices.md
Labels: Jira Synced

#11514 feat(CX-3224): update settings header
  src/Apps/Settings/SettingsApp.tsx
  src/Components/TopContextBar.tsx
Labels: Jira Synced

#11517 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11519 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11518 feat(FX-4468): Add skeleton loader for activity panel
  src/Components/Notifications/NotificationsList.tsx
  src/Components/Notifications/NotificationsListPlaceholder.tsx
Labels: Jira Synced

#11522 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11523 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11527 chore(deps): bumps @artsy/img
  package.json
  src/Utils/resizer.ts
  yarn.lock
Labels: Merge On Green

#11524 feat(DO-558): add upcoming auctions filter
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.jest.tsx
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
Labels: Jira Synced

#11530 feat(FX-4492): add lot label even when lot is closed
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
Labels: Jira Synced

#11532 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11533 fix(CX-3173): Update collector profile info fields
  src/Apps/CollectorProfile/Components/CollectorProfileHeader/Components/CollectorProfileHeaderInfo.tsx
Labels: Jira Synced

#11531 feat(FX-4478): Re-position elements in the menu (mWeb)
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotifications.tsx
  src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
  src/__generated__/NavBarMobileMenuNotificationsQuery.graphql.ts
  src/__generated__/NavBarMobileMenuNotifications_me.graphql.ts
Labels: Jira Synced

#11538 fix(fullbleedheader): consistency pass on layout of full bleed header…
  src/Apps/About/AboutApp.tsx
  src/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx
  src/Components/FullBleedHeader/FullBleedHeader.tsx
Labels: Merge On Green

#11540 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11541 fix(CX-3224): Remove "Back to Collector Profile" button
  src/Apps/Settings/SettingsApp.tsx
  src/Components/TopContextBar.tsx
Labels: Jira Synced

#11542 fix: add play store signing sha to assetlinks.json
  src/public/.well-known/assetlinks.json
Labels: Jira Synced

#11537 refactor(FX-4494): Clean up `force-enable-new-activity-panel` feature flag
  src/Components/NavBar/Menus/NavBarNotifications.tsx
  src/Components/NavBar/Menus/__tests__/NavBarNotifications.jest.tsx
  src/Components/NavBar/Menus/index.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavBarLoggedInActions.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuInboxNotificationCount.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotifications.tsx
  src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
  src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenuInboxNotificationCount.jest.tsx
  src/Components/NavBar/__tests__/NavBar.jest.tsx
  src/__generated__/NavBarMobileMenuInboxNotificationCountQuery.graphql.ts
  src/__generated__/NavBarMobileMenuInboxNotificationCount_me.graphql.ts
  src/__generated__/NavBarMobileMenuInboxNotificationCount_test_Query.graphql.ts
  src/__generated__/NavBarNotificationsQuery.graphql.ts
  src/__generated__/NavBarNotifications_me.graphql.ts
Labels: Jira Synced

#11547 fix(sell): reverts full bleed header consistency pass
  src/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx
Labels: Merge On Green

#11549 feat(CX-3236): change route 'collector-profile/collection' to 'collector-profile/my-collection'
  src/Apps/CollectorProfile/CollectorProfileApp.tsx
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/Server/middleware/hardcodedRedirects.ts
Labels: Jira Synced, Squash On Green

#11516 feat: Update Edit Profile page
  src/Apps/CollectorProfile/Components/CollectorProfileHeader/CollectorProfileHeader.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileHeader/Components/CollectorProfileHeaderAvatar.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileHeader/__tests__/CollectorProfileHeader.jest.tsx
  src/Apps/CollectorProfile/Utils/ValidationSchemas.ts
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
  src/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileFields.jest.tsx
  src/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
  src/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
  src/Apps/Settings/SettingsApp.tsx
  src/__generated__/SettingsEditProfileFields_Test_Query.graphql.ts
  src/__generated__/SettingsEditProfileFields_me.graphql.ts
  src/__generated__/SettingsEditProfileRoute_me.graphql.ts
  src/__generated__/SettingsEditSettingsRoute_me.graphql.ts
  src/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts
  src/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
Labels: Jira Synced

#11554 feat(artquiz): adds toast email confirmation
  src/Apps/ArtQuiz/Components/ArtQuizResultsTabs.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Merge On Green

#11555 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11536 fix: Edit artwork form back button
  .secrets.baseline
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx
Labels: Squash On Green

#11552 feat: add MyC artworks to the my collection tab on collector profile
  src/Apps/CollectorProfile/Routes/MyCollection/CollectorProfileMyCollectionRoute.tsx
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
  src/__generated__/collectorProfileRoutes_MyCollectionRouteQuery.graphql.ts
Labels: Jira Synced

#11556 feat: add Insights to the my collection tab on collector profile
  src/Apps/CollectorProfile/Routes/Insights/CollectorProfileInsightsRoute.tsx
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
  src/__generated__/collectorProfileRoutes_InsightsRouteQuery.graphql.ts
Labels: Jira Synced

#11557 fix: remove title from insights page
  src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
Labels: Jira Synced, Squash On Green

#11562 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11570 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11574 fix(appshell): fixes double scroll area on footer-less pages
  src/Apps/Components/AppShell.tsx
Labels: Merge On Green

#11572 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11558 chore(FX-4086): improvements for lot number and lot close labels
  src/Components/Artwork/Details.tsx
Labels: Jira Synced, Squash On Green

#11583 fix(art-quiz): updates copy
  src/System/i18n/locales/en-US/translation.json
Labels: Merge On Green

#11585 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11578 feat(CX-2939): consignment inquiry flow web
  src/Apps/Consign/Routes/ConsignmentInquiry/Components/ConsignmentInquiryForm.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/Components/ConsignmentInquiryFormAbandonEdit.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/ConsignmentInquiry.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/ConsignmentInquiryConfirmation.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/ConsignmentInquiryContainer.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/__tests__/ConsignmentInquiry.jest.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/utils/useCreateConsignmentInquiry.ts
  src/Apps/Consign/Routes/ConsignmentInquiry/utils/validation.ts
  src/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx
  src/Apps/Consign/consignRoutes.tsx
  src/Utils/recaptcha.ts
  src/__generated__/ConsignmentInquiry_Test_Query.graphql.ts
  src/__generated__/ConsignmentInquiry_me.graphql.ts
  src/__generated__/consignRoutes_ConsignmentInquiryAppQuery.graphql.ts
  src/__generated__/useCreateConsignmentInquiryMutation.graphql.ts
Labels: Jira Synced

#11586 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11588 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11579 feat: My Collection artwork upload steps
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtworkStep.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormContext.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx
Labels: Jira Synced, Squash On Green

#11577 refactor(FX-4334): Reorganize About the work section
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromArtsy.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsPartnerInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetailsAdditionalInfo.jest.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetailsPartnerInfo.jest.tsx
  src/Apps/Artwork/Components/ArtworkDetails/index.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarSizeInfo.tsx
  src/Apps/Artwork/useArtworkDimensions.tsx
  src/__generated__/ArtworkDetailsAboutTheWorkFromArtsy_artwork.graphql.ts
  src/__generated__/ArtworkDetailsAdditionalInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkDetailsAdditionalInfo_artwork.graphql.ts
  src/__generated__/ArtworkDetailsPartnerInfoQuery.graphql.ts
  src/__generated__/ArtworkDetailsPartnerInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkDetailsPartnerInfo_artwork.graphql.ts
  src/__generated__/ArtworkDetailsQuery.graphql.ts
  src/__generated__/ArtworkDetails_Test_Query.graphql.ts
  src/__generated__/ArtworkDetails_artwork.graphql.ts
Labels: Jira Synced, Squash On Green

#11592 fix: broken submissions link
  src/Apps/Consign/Routes/MarketingLanding/Components/CtaBanner.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/CtaSection.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/CtaBanner.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/CtaSection.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Header.jest.tsx
Labels: Jira Synced

#11561 feat(CX-3244): review the settings routes and change them to collector profile where needed
  src/Apps/Artist/Components/BackLink.tsx
  src/Apps/Artist/Components/__tests__/BackLink.jest.tsx
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYouWhenFromMyCollection.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYouWhenFromMyCollection.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Apps/Consign/consignFromCollectorProfileMyCollectionRoutes.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormHeader.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionEditArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkBackButton.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkImageBrowser/MyCollectionArtworkNoImageComponent.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkRequestPriceEstimateSection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/__tests__/MyCollectionArtwork.jest.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateConfirmation.jest.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateConfirmation.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/__tests__/PriceEstimateContactInformation.jest.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Components/CareerHighlightModalPromoStep.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightPromoCard.tsx
  src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx
  src/Apps/Settings/Routes/Insights/Components/InsightsLandingPage.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
  src/Apps/Settings/Routes/MyCollection/Components/MyCollectionEmptyState.tsx
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
  src/Components/Artwork/GridItem.tsx
  src/Components/Artwork/Metadata.tsx
  src/Components/Artwork/__tests__/Metadata.jest.tsx
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionArtworkFormQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_priceEstimateContactInformationQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_contactInformationMeQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_myCollectionArtworkQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_uploadArtworkPhotosQuery.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#11595 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/Review_order.graphql.ts
  src/__generated__/SetShippingMutation.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/Status_order.graphql.ts
Labels: Squash On Green

#11603 fix(img): adds positron config
  package.json
  src/Utils/resizer.ts
  yarn.lock
Labels: Merge On Green

#11606 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11609 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/AcceptRouteSetOrderPaymentMutation.graphql.ts
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/ConversationCTA_Test_Query.graphql.ts
  src/__generated__/ConversationCTA_conversation.graphql.ts
  src/__generated__/ConversationMessages_Test_Query.graphql.ts
  src/__generated__/ConversationMessages_events.graphql.ts
  src/__generated__/CounterSubmitMutation.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/Counter_order.graphql.ts
  src/__generated__/CreditCardPickerTestQuery.graphql.ts
  src/__generated__/CreditCardPicker_order.graphql.ts
  src/__generated__/DetailsSidebar_conversation.graphql.ts
  src/__generated__/NewPaymentRouteSetOrderPaymentMutation.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/Offer_order.graphql.ts
  src/__generated__/OrderUpdate_Test_Query.graphql.ts
  src/__generated__/OrderUpdate_event.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/RejectOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/Respond_order.graphql.ts
  src/__generated__/ReviewSubmitOfferOrderWithConversationMutation.graphql.ts
  src/__generated__/ReviewSubmitOrderMutation.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/SetShippingMutation.graphql.ts
  src/__generated__/SettingsPurchasesQuery.graphql.ts
  src/__generated__/SettingsPurchasesRow_order.graphql.ts
  src/__generated__/SettingsPurchases_Test_Query.graphql.ts
  src/__generated__/ShippingSummaryItem_order.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/Shipping_order.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/Status_order.graphql.ts
  src/__generated__/createMockNetworkLayerTestMutationResultsMutation.graphql.ts
  src/__generated__/orderRoutes_OrderQuery.graphql.ts
  src/__generated__/redirects_order.graphql.ts
Labels: Squash On Green

#11607 fix(NX-3342): artwork detail wasn't closable on medium-size screens
  src/Apps/Conversation/Components/ConversationHeader.tsx
  src/Apps/Conversation/Components/DetailsHeader.tsx
Labels: Jira Synced

#11613 chore(deps): bumps img
  package.json
  yarn.lock
Labels: Merge On Green

#11605 feat(GRO-1481): fully responsive, 100% width/height scaling box
  src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryFigure.tsx
  src/Components/FullscreenBox.tsx
  src/Components/__stories__/FullscreenBox.story.tsx
Labels: Merge On Green

#11599 feat(art-quiz): connect quiz artworks screen to MP
  src/Apps/ArtQuiz/Components/ArtQuizCard.tsx
  src/Apps/ArtQuiz/Components/ArtQuizMain.tsx
  src/Apps/ArtQuiz/Hooks/useDislikeArtwork.ts
  src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
  src/Apps/ArtQuiz/artQuizRoutes.tsx
  src/__generated__/ArtQuizArtworks_me.graphql.ts
  src/__generated__/artQuizRoutes_ArtworksQuery.graphql.ts
  src/__generated__/artQuizRoutes_WelcomeQuery.graphql.ts
  src/__generated__/useDislikeArtworkMutation.graphql.ts
Labels: Jira Synced

#11617 fix(app-shell): temporarily removes height/overflow
  src/Apps/Components/AppShell.tsx
Labels: Merge On Green

#11619 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11620 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useCreateConsignmentInquiryMutation.graphql.ts
Labels: Squash On Green

#11621 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11566 feat(CX-3239): Add image upload to collector profile
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.jest.tsx
  src/Apps/CollectorProfile/Utils/ValidationSchemas.ts
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/UploadPhotosForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormImages.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileImage/Components/LocalImagePreview.tsx
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileImage/SettingsEditProfileImage.tsx
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileImage/utils/constants.tsx
  src/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileFields.jest.tsx
  src/Components/PhotoUpload/Utils/fileUtils.ts
  src/Components/PhotoUpload/__tests__/fileUtils.jest.ts
  src/Utils/localImagesHelpers.ts
  src/Utils/typeSupport.ts
  src/__generated__/SettingsEditProfileFields_Test_Query.graphql.ts
  src/__generated__/SettingsEditProfileFields_me.graphql.ts
  src/__generated__/SettingsEditProfileImage_me.graphql.ts
  src/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts
  src/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
Labels: Jira Synced

#11614 feat(art-quiz): trigger button animations on swipe
  src/Apps/ArtQuiz/ArtQuizApp.tsx
  src/Apps/ArtQuiz/Components/ArtQuizButton.tsx
  src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
Labels: Merge On Green

#11627 fix(artist): corrects logic for querying for fair booths
  src/Apps/Artist/Routes/CV/ArtistCVRoute.tsx
  src/Apps/Artist/Routes/CV/Components/ArtistCVGroup.tsx
  src/__generated__/ArtistCVGroup_artist.graphql.ts
  src/__generated__/ArtistCVRoute_Test_Query.graphql.ts
  src/__generated__/ArtistCVRoute_viewer.graphql.ts
  src/__generated__/artistRoutes_CVQuery.graphql.ts
Labels: Merge On Green

#11622 chore(FX-4527): updated the logic of displaying the "contact gallery" button for the partner
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarPartnerInfo.jest.tsx
  src/__generated__/ArtworkSidebarPartnerInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarPartnerInfo_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11628 fix: Hide collected artists when not existing in upload flow
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
Labels: Squash On Green

#11612 fix: Simplify SWA phone number validation
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
Labels: Jira Synced

#11630 feat: ignore header offset when `isEigen` is true
  src/Components/NavBar/useNavBarHeight.ts
Labels: Jira Synced

#11634 fix: Remove skip button from MyC artist upload step
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormHeader.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx
Labels: Squash On Green

#11636 fix: add artwork button
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
  src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#11637 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11635 fix(NX-3209): Remove isActionable check from OrderModal
  src/Apps/Conversation/Components/Conversation.tsx
Labels: Jira Synced

#11639 fix(CX-3279): trim the name
  src/Apps/CollectorProfile/Utils/ValidationSchemas.ts
Labels: Jira Synced

#11632 Deploy
  README.md
  data/schema.graphql
  src/Apps/CollectorProfile/Components/CollectorProfileHeader/Components/CollectorProfileHeaderInfo.tsx
  src/Apps/CollectorProfile/Utils/ValidationSchemas.ts
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
  src/Apps/Conversation/Components/Conversation.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormHeader.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx
  src/Components/NavBar/useNavBarHeight.ts
  src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts
Labels: Jira Synced

#11640 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11633 fix: Increase MyC upload flow artist step font size
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
Labels: Squash On Green

#11625 feat(CX-3240): add id and email verification to edit profile page
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
  src/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileFields.jest.tsx
  src/Apps/Settings/Routes/EditProfile/helpers/useHandleVerification.tsx
  src/Apps/Settings/Routes/EditProfile/helpers/verifyEmail.ts
  src/Apps/Settings/Routes/EditProfile/helpers/verifyID.ts
  src/__generated__/verifyEmailMutation.graphql.ts
  src/__generated__/verifyIDMutation.graphql.ts
Labels: Jira Synced

#11642 fix(NX-3408): Set the iframe to use the total width
  src/Apps/Conversation/Components/OrderModal.tsx
Labels: Jira Synced

#11631 feat(CX-3225): update the navigation menu Web and mWeb
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsOverview.jest.tsx
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
  src/Apps/Settings/SettingsApp.tsx
  src/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/Components/NavBar/Menus/__tests__/NavBarUserMenu.jest.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotifications.tsx
Labels: Jira Synced

#11643 feat(CX-3276): add new route for mediam sale price
  src/Apps/MyCollectionInsights/myCollectionInsightsCollectorProfileRoutes.tsx
  src/Apps/Settings/Routes/Insights/Components/InsightsMedianSalePrice.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsMedianSalePrice.jest.tsx
  src/__generated__/myCollectionInsightsCollectorProfileRoutesQuery.graphql.ts
  src/routes.tsx
Labels: Jira Synced, Squash On Green

#11629 feat: My Collection form artist avatar
  .secrets.baseline
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/ArtistGridItem.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormMain.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionEditArtwork.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkFormHelpers.ts
  src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkModel.ts
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx
  src/Components/EntityHeaders/EntityHeaderArtist.tsx
  src/__generated__/ArtistAutocomplete_SearchConnection_Query.graphql.ts
  src/__generated__/ArtistGridItem_artist.graphql.ts
  src/__generated__/MyCollectionArtworkFormArtistStep_me.graphql.ts
  src/__generated__/MyCollectionCreateArtworkTest_Query.graphql.ts
  src/__generated__/MyCollectionEditArtworkTest_Query.graphql.ts
  src/__generated__/MyCollectionEditArtwork_artwork.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionArtworkFormQuery.graphql.ts
  src/__generated__/myCollectionRoutes_MyCollectionArtworkFormQuery.graphql.ts
  src/__generated__/myCollectionRoutes_MyCollectionArtworkUploadQuery.graphql.ts
Labels: Jira Synced

#11638 feat: app layouts
  src/Apps/ArtQuiz/artQuizRoutes.tsx
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/__tests__/ArtistApp.jest.tsx
  src/Apps/Artist/artistRoutes.tsx
  src/Apps/Authentication/authenticationRoutes.tsx
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/Apps/Components/AppContainer.tsx
  src/Apps/Components/AppShell.tsx
  src/Apps/Components/Layouts/Components/LayoutFooter.tsx
  src/Apps/Components/Layouts/Components/LayoutMain.tsx
  src/Apps/Components/Layouts/Components/LayoutNav.tsx
  src/Apps/Components/Layouts/LayoutBlank.tsx
  src/Apps/Components/Layouts/LayoutContainerOnly.tsx
  src/Apps/Components/Layouts/LayoutDefault.tsx
  src/Apps/Components/Layouts/LayoutLogoOnly.tsx
  src/Apps/Components/Layouts/LayoutNavOnly.tsx
  src/Apps/Components/Layouts/README.md
  src/Apps/Components/Layouts/__stories__/Layout.story.tsx
  src/Apps/Components/Layouts/index.tsx
  src/Apps/Consign/consignFromCollectorProfileMyCollectionRoutes.tsx
  src/Apps/Consign/consignFromMyCollectionRoutes.tsx
  src/Apps/Consign/consignRoutes.tsx
  src/Apps/Conversation/Routes/Conversation/index.tsx
  src/Apps/Conversation/conversationRoutes.tsx
  src/Apps/MyCollection/myCollectionRoutes.tsx
  src/Apps/MyCollectionInsights/myCollectionInsightsCollectorProfileRoutes.tsx
  src/Apps/MyCollectionInsights/myCollectionInsightsRoutes.tsx
  src/Apps/Order/orderRoutes.tsx
  src/Components/Footer/Footer.tsx
  src/Components/NavBar/MinimalNavBar.tsx
  src/Components/NavBar/NavBar.tsx
  src/System/Router/ErrorBoundary.tsx
  src/System/Router/Route.tsx
  src/System/Router/Utils/findCurrentRoute.tsx
  src/Utils/typeSupport.ts
Labels: Merge On Green

#11646 fix: Adjust My Collection form spacing between inputs
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
Labels: Squash On Green

#11649 fix(CX-3284): Update Setting icon size in Collector Profile
  src/Apps/CollectorProfile/Components/CollectorProfileHeader/CollectorProfileHeader.tsx
Labels: Jira Synced

#11645 fix(CX-3283): add log out button to mWeb menu
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileSubMenu.tsx
Labels: Jira Synced

#11648 fix(CX-3278): Add Text area for bio in Collector Profile
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
Labels: Jira Synced

#11644 feat(CX-3277): Add local image in Collector Profile
  src/Apps/CollectorProfile/Components/CollectorProfileHeader/CollectorProfileHeader.tsx
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileImage/Components/LocalImagePreview.tsx
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileImage/SettingsEditProfileImage.tsx
Labels: Jira Synced

#11653 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11652 feat(CX-3157): Force - Add Medium to SWA Form
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/acceptableCategoriesForSubmission.ts
  src/__generated__/ArtworkDetails_SubmissionFlowPrepopulatedTest_Query.graphql.ts
  src/__generated__/ArtworkDetails_SubmissionFlowTest_Query.graphql.ts
  src/__generated__/ArtworkDetails_myCollectionArtwork.graphql.ts
  src/__generated__/ArtworkDetails_submission.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_myCollectionArtworkQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_uploadArtworkPhotosQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_myCollectionArtworkQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_uploadArtworkPhotosQuery.graphql.ts
  src/__generated__/consignRoutes_artworkDetailsQuery.graphql.ts
  src/__generated__/consignRoutes_contactInformationQuery.graphql.ts
  src/__generated__/consignRoutes_uploadPhotosQuery.graphql.ts
  src/__generated__/redirects_submission.graphql.ts
Labels: Jira Synced

#11651 Deploy
  data/schema.graphql
  src/Apps/CollectorProfile/Components/CollectorProfileHeader/CollectorProfileHeader.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/acceptableCategoriesForSubmission.ts
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileImage/Components/LocalImagePreview.tsx
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileImage/SettingsEditProfileImage.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileSubMenu.tsx
  src/__generated__/ArtworkDetails_SubmissionFlowPrepopulatedTest_Query.graphql.ts
  src/__generated__/ArtworkDetails_SubmissionFlowTest_Query.graphql.ts
  src/__generated__/ArtworkDetails_myCollectionArtwork.graphql.ts
  src/__generated__/ArtworkDetails_submission.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_myCollectionArtworkQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_uploadArtworkPhotosQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_myCollectionArtworkQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_uploadArtworkPhotosQuery.graphql.ts
  src/__generated__/consignRoutes_artworkDetailsQuery.graphql.ts
  src/__generated__/consignRoutes_contactInformationQuery.graphql.ts
  src/__generated__/consignRoutes_uploadPhotosQuery.graphql.ts
  src/__generated__/redirects_submission.graphql.ts
Labels: Jira Synced

#11610 feat: My Collection artwork upload Artwork step
  .secrets.baseline
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtworkStep.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArworkSearch.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Utils/useCreateOrUpdateArtwork.ts
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#11658 fix(CX-3225): navigation menu, address comments
  src/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/Components/NavBar/Menus/__tests__/NavBarUserMenu.jest.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/Search/SearchInputContainer.tsx
Labels: Jira Synced

#11659 fix(CX-3287): Show the Upload Artwork button only if the header is sticky
  src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
Labels: Jira Synced, Squash On Green

#11654 feat(CX-3271): Remove zip code from swa form
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
Labels: Jira Synced, Squash On Green

#11494 feat: Enable personal artists in My Collection upload flow
  .secrets.baseline
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkValidation.ts
  src/Apps/MyCollection/Routes/EditArtwork/Utils/useCreateOrUpdateArtwork.ts
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx
Labels: Jira Synced

#11656 Deploy
  .secrets.baseline
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtworkStep.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArworkSearch.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkValidation.ts
  src/Apps/MyCollection/Routes/EditArtwork/Utils/useCreateOrUpdateArtwork.ts
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx
  src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
  src/Components/Artwork/Details.tsx
  src/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/Components/NavBar/Menus/__tests__/NavBarUserMenu.jest.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/Search/SearchInputContainer.tsx
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
Labels: Jira Synced

#11660 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
