Repository artsy/force, pull requests merged in 2022-10, with the labels that each got.

#11095 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11105 chore(relay): Add official relay devtools extension to VSCode config
  .vscode/extensions.json
  Dockerfile
  apollo.config.js
  package.json
  yarn.lock
Labels: Merge On Green

#11098 feat: update stripe legal text styles
  src/Components/BankDebitForm/BankDebitProvider.tsx
Labels: Jira Synced

#11107 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11110 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11038 feat(FX-4149): commercial and auction sections
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2Artists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2ArtsyGuarantee.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2AuctionTimer.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2BiddingClosedMessage.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2CommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2EditionSets.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2EstimatedValue.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2CommercialButtons.jest.tsx
  src/Components/Artwork/SidebarExpandable.tsx
  src/DevTools/MockBoot.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/ArtworkApp_me.graphql.ts
  src/__generated__/ArtworkSidebar2AuctionTimer_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2BiddingClosedMessage_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2CommercialButtonsOfferOrderMutation.graphql.ts
  src/__generated__/ArtworkSidebar2CommercialButtonsOrderMutation.graphql.ts
  src/__generated__/ArtworkSidebar2CommercialButtons_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2CommercialButtons_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2EditionSets_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2EstimatedValue_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2_me.graphql.ts
  src/__generated__/ArtworkSidebarAuctionInfoPollingQuery.graphql.ts
  src/__generated__/ArtworkSidebarCurrentBidInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCurrentBidInfo_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11115 fix: remove blue highlight from guarantee icons
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2ArtsyGuarantee.tsx
Labels: Jira Synced

#11113 feat: create request price estimate block cta UI only
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworRequestPriceEstimateSection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
Labels: Jira Synced

#11117 fix(FX-4317): artsy guarantee learn more link opens new tab
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2ArtsyGuarantee.tsx
Labels: Jira Synced

#11114 fix: broken shipping tests
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
Labels: Jira Synced

#11119 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11116 fix(FX-4315): hide artsy guarantee in some cases
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2.jest.tsx
  src/__generated__/ArtworkSidebar2_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11123 refactor: remove @ts-ignore RELAY UPGRADE 13 leftovers
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionInfoPolling.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2AuctionTimer.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2BiddingClosedMessage.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2CommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2CommercialButtons.jest.tsx
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Settings/Routes/Auctions/SettingsAuctionsRoute.tsx
  src/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
  src/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
Labels: Jira Synced, Squash On Green

#11124 fix: add missing media tag
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
Labels: Jira Synced

#11097 fix: cannot save a new shipping address if last saved address removed on shipping page
  src/Apps/Order/Routes/Shipping/index.tsx
Labels: Jira Synced

#11122 fix: separator fix in auctions
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
Labels: Jira Synced

#11133 chore: updates version of detect secrets
  .secrets.baseline
Labels: Merge On Green

#11125 chore: remove feature flag related logic phase-3
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkImageBrowser/MyCollectionArtworkNoImageComponent.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkImageBrowser/__tests__/MyCollectionArtworkImageBrowser.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
Labels: Jira Synced

#11128 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArticleBody_test_Query.graphql.ts
  src/__generated__/ArticleInfiniteScrollQuery.graphql.ts
  src/__generated__/ArticleZoomGalleryQuery.graphql.ts
  src/__generated__/ArticleZoomGallery_test_Query.graphql.ts
  src/__generated__/NewsIndexArticlesQuery.graphql.ts
  src/__generated__/RssArticlesQuery.graphql.ts
  src/__generated__/articleRoutes_ArticleQuery.graphql.ts
  src/__generated__/articlesRoutes_NewsQuery.graphql.ts
Labels: Squash On Green

#11132 feat(article): allows unpublished artworks to be viewed within articles
  src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGallery.tsx
  src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryCaption.tsx
  src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryFigure.tsx
  src/Apps/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionCaption.tsx
  src/Apps/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionImage.tsx
  src/__generated__/ArticleBody_test_Query.graphql.ts
  src/__generated__/ArticleInfiniteScrollQuery.graphql.ts
  src/__generated__/ArticleSectionImageCollectionCaption_figure.graphql.ts
  src/__generated__/ArticleSectionImageCollectionImage_figure.graphql.ts
  src/__generated__/ArticleZoomGalleryCaption_figure.graphql.ts
  src/__generated__/ArticleZoomGalleryFigure_figure.graphql.ts
  src/__generated__/ArticleZoomGalleryQuery.graphql.ts
  src/__generated__/ArticleZoomGallery_article.graphql.ts
  src/__generated__/ArticleZoomGallery_test_Query.graphql.ts
  src/__generated__/NewsIndexArticlesQuery.graphql.ts
  src/__generated__/articleRoutes_ArticleQuery.graphql.ts
  src/__generated__/articlesRoutes_NewsQuery.graphql.ts
Labels: Merge On Green

#11131 feat(CX-2876): Add Career Highlights carousel in MyC Insights
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightCard.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightPromoCard.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightRail.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/__tests__/InsightsCareerHighlightRail.jest.tsx
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
  src/Apps/Settings/Routes/Insights/Utils/getCareerHighlight.tsx
  src/__generated__/InsightsCareerHighlightRailTestQuery.graphql.ts
  src/__generated__/InsightsCareerHighlightRail_me.graphql.ts
  src/__generated__/InsightsRoute_me.graphql.ts
  src/__generated__/settingsRoutes_InsightsRouteQuery.graphql.ts
Labels: Jira Synced

#11138 fix: Hide Career Highlights carousel behind feature flag
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
Labels: Jira Synced, Squash On Green

#11141 fix(FX-4319): commercial buttons section overflow
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2CommercialButtons.tsx
Labels: Jira Synced

#11145 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11135 feat: Initialize SWA form images when submitting an artwork from My Collection
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/UploadPhotosForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
  src/Components/PhotoUpload/Components/PhotoThumbnail.tsx
  src/Components/PhotoUpload/Utils/fileUtils.ts
  src/Components/PhotoUpload/Utils/uploadFileToS3.tsx
  src/__generated__/UploadPhotos_SubmissionMyCollectionFlowTest_Query.graphql.ts
  src/__generated__/UploadPhotos_myCollectionArtwork.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_uploadArtworkPhotosQuery.graphql.ts
Labels: Jira Synced

#11151 chore(FX-4321): change Contact For Price checks
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetailsPlaceholder.tsx
  src/Components/Artwork/Details.tsx
Labels: Jira Synced

#11149 fix(FX-4320): make artworksidebar2classification more defensive
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2Classification.tsx
Labels: Jira Synced

#11152 fix: Adjust error message when initial artwork image loading fails in SWA flow
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/UploadPhotosForm.tsx
  src/Components/PhotoUpload/Components/PhotoThumbnail.tsx
  src/Components/PhotoUpload/Utils/uploadFileToS3.tsx
  src/Components/PhotoUpload/__tests__/PhotoThumbnail.jest.tsx
Labels: Jira Synced, Squash On Green

#11147 feat(FX-4363): Activity panel: Remove artworks counter
  src/Components/Notifications/NotificationItem.tsx
  src/Components/Notifications/__tests__/NotificationItem.jest.tsx
  src/__generated__/NotificationItem_item.graphql.ts
  src/__generated__/NotificationItem_test_Query.graphql.ts
  src/__generated__/NotificationsListNextQuery.graphql.ts
  src/__generated__/NotificationsListQuery.graphql.ts
  src/__generated__/NotificationsList_test_Query.graphql.ts
Labels: Jira Synced

#11153 fix: Update Price Estimate page copy
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/__tests__/PriceEstimateContactInformation.jest.tsx
Labels: Jira Synced

#11160 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11162 fix: remove timely formatting
  src/Apps/Auction/Components/AuctionAssociatedSale.tsx
  src/Apps/Auction/Components/__tests__/AuctionAssociatedSale.jest.tsx
Labels: Jira Synced

#11148 feat: Create Confirmation Page | request Price Estimate
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYouWhenFromMyCollection.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateConfirmation.jest.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateConfirmation.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/__tests__/PriceEstimateContactInformation.jest.tsx
  src/Apps/MyCollection/myCollectionRoutes.tsx
  src/Components/ConfirmationScreenComponent.tsx
Labels: Jira Synced

#11163 feat: add test ids for cypress
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2CommercialButtons.tsx
Labels: Jira Synced

#11146 feat(art quiz): Create loading results page
  src/Apps/ArtQuiz/Components/ArtQuizResultsLoader.tsx
  src/Apps/ArtQuiz/__tests__/ArtQuizResultsLoader.jest.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#11172 feat: web deployment to prefer spot tier
  hokusai/production.yml
  hokusai/staging.yml
Labels: Jira Synced

#11170 feat(FX-4365): Change copy of Alert's tab empty state
  src/Components/Notifications/NotificationsEmptyStateByType.tsx
  src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx
Labels: Jira Synced

#11158 feat(CX-2879): Add Median Sale Price to MyC Insights
  src/Apps/Settings/Routes/Insights/Components/InsightsMedianSalePrice.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsMedianSalePrice.jest.tsx
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
  src/__generated__/InsightsMedianSalePriceTestQuery.graphql.ts
  src/__generated__/InsightsMedianSalePrice_me.graphql.ts
  src/__generated__/InsightsRoute_me.graphql.ts
  src/__generated__/settingsRoutes_InsightsRouteQuery.graphql.ts
Labels: Jira Synced

#11159 refactor: artwork actions render logic
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkDownloadButton.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/UtilButton.tsx
  src/__generated__/ArtworkActions_Test_Query.graphql.ts
  src/__generated__/ArtworkActions_artwork.graphql.ts
  src/__generated__/ArtworkDownloadButton_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11173 chore(art taste quiz): Add INTL to Welcome Screen
  src/Apps/ArtQuiz/ArtQuizWelcome.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#11150 feat(FX-4329): Auctions Registration Countdown in Banner
  src/Apps/Artwork/Components/ArtworkTopContextBar/ArtworkTopContextBar.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/RegistrationAuctionTimer.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/__tests__/ArtworkTopContextBar.jest.tsx
  src/Components/TopContextBar.tsx
  src/__generated__/ArtworkTopContextBar_Test_Query.graphql.ts
  src/__generated__/ArtworkTopContextBar_artwork.graphql.ts
  src/__generated__/RegistrationAuctionTimer_sale.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11181 update auction registration credit card note
  src/Apps/Auction/Components/Form/AddressFormWithCreditCard.tsx
Labels: Jira Synced

#11182 fix: adjust the design of confirmation pages | SWA, Price estimate
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYouWhenFromMyCollection.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormImages.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateConfirmation.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/__tests__/PriceEstimateContactInformation.jest.tsx
  src/Apps/MyCollection/myCollectionRoutes.tsx
  src/Apps/Settings/Routes/Insights/Components/InsightsMedianSalePrice.tsx
  src/Components/ConfirmationScreenComponent.tsx
Labels: Jira Synced

#11183 chore(FX-4367): Empty state version should have 40px padding between tabs and copy
  src/Components/Notifications/NotificationsEmptyStateByType.tsx
Labels: Jira Synced

#11189 fix: change artsy guarantee logic to be either of isOfferable/isOfferableFromInquiry
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
Labels: Jira Synced, Squash On Green

#11190 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11180 fix: Update Insights page
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
Labels: Jira Synced

#11191 fix: add as-h1 to make smoke tests pass
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2ArtworkTitle.tsx
Labels: Jira Synced, Squash On Green

#11179 fix(CX-2736): request price estimate and SWA sections | UI update
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkRequestPriceEstimateSection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASectionSubmitted.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/__generated__/MyCollectionArtworkInsights_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11192 fix: remove back button
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateConfirmation.jest.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateConfirmation.tsx
Labels: Jira Synced, Squash On Green

#10970 feat[FX-4095]: use curated collection pages instead of genes
  src/Apps/Gene/Server/__tests__ /redirectGeneToCollection.jest.ts
  src/Apps/Gene/Server/redirectGeneToCollection.ts
  src/Apps/Gene/Utils/geneToCollectionMap.ts
  src/Apps/Gene/geneRoutes.tsx
  src/Apps/Home/Components/HomeTroveArtworksRail.tsx
  src/Apps/Home/__tests__/HomeTroveArtworksRail.jest.tsx
  src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
  src/Components/NavBar/menuData.ts
  src/Components/Onboarding/Components/OnboardingMarketingCollection.tsx
  src/Components/Onboarding/Components/__tests__/OnboardingMarketingCollection.jest.tsx
  src/Components/Onboarding/Views/OnboardingArtistsOnTheRise.tsx
  src/Components/Onboarding/Views/OnboardingCuratedArtworks.tsx
  src/Components/Onboarding/Views/OnboardingTopAuctionLots.tsx
  src/Server/analytics/__tests__/brazeMessagingIntegration.jest.ts
  src/__generated__/HomeTroveArtworksRailQuery.graphql.ts
  src/__generated__/HomeTroveArtworksRail_Test_Query.graphql.ts
  src/__generated__/HomeTroveArtworksRail_viewer.graphql.ts
  src/__generated__/OnboardingMarketingCollectionQuery.graphql.ts
  src/__generated__/OnboardingMarketingCollection_Test_Query.graphql.ts
  src/__generated__/OnboardingMarketingCollection_marketingCollection.graphql.ts
Labels: Merge On Green, Jira Synced

#11196 fix: correct redirect for collection
  src/Apps/Gene/Utils/geneToCollectionMap.ts
Labels: Merge On Green

#11197 fix: show edition set size on single edition works
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2Details.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2Details.jest.tsx
  src/__generated__/ArtworkSidebar2Details_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2Details_artwork.graphql.ts
  src/__generated__/ArtworkSidebar2_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#11205 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11166 fix: Only show last error message in SWA photo upload form
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Components/PhotoUpload/Components/PhotoThumbnail.tsx
  src/Components/PhotoUpload/__tests__/PhotoThumbnail.jest.tsx
Labels: Jira Synced

#11194 fix: my collection UI updates
  .secrets.baseline
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkArtistMarket.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkAuctionResults.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkComparables.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkDemandIndex/index.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx
Labels: Jira Synced

#11207 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11208 feat: Add MyC Insights meta title
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
Labels: Jira Synced

#11188 chore(art-quiz): clean up art-quiz post palette update
  package.json
  src/Apps/ArtQuiz/ArtQuizMain.tsx
  src/Apps/ArtQuiz/Components/ArtQuizGridComponents.tsx
  yarn.lock
Labels: Merge On Green

#11206 feat(FX-4381): Activity Panel tracking
  src/Components/NavBar/NavBarLoggedInActions.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
  src/Components/Notifications/NotificationItem.tsx
  src/Components/Notifications/NotificationsTabs.tsx
Labels: Jira Synced

#11193 fix(TX-828): Postal code validation in shipping step address form
  src/Apps/Order/Components/__tests__/CreditCardPicker.jest.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/Apps/Order/Utils/__tests__/formValidators.jest.tsx
  src/Apps/Order/Utils/formValidators.tsx
  src/Components/__tests__/Utils/addressForm.ts
Labels: Jira Synced

#11213 fix: add spacer when artwork is Sold
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2CommercialButtons.tsx
Labels: Jira Synced

#11214 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11212 feat(CX-2942): create median sale price screen wrapper
  src/Apps/MyCollectionInsights/Routes/MyCollectionInsightsMedianSalePriceAtAuction/MyCollectionInsightsMedianSalePriceAtAuction.tsx
  src/Apps/MyCollectionInsights/myCollectionInsightsRoutes.tsx
  src/Apps/Settings/Routes/Insights/Components/InsightsMedianSalePrice.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsMedianSalePrice.jest.tsx
  src/routes.tsx
Labels: Jira Synced, Squash On Green

#11218 fix: removes serif reference
  src/Apps/Feature/Components/FeatureFeaturedLink.tsx
Labels: Merge On Green

#11220 refactor: remove sidebar inlined render functions
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2CommercialButtons.tsx
Labels: Jira Synced, Squash On Green

#11219 fix: fixed variant in artwork details
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2Details.tsx
Labels: Jira Synced, Squash On Green

#11217 feat: query formatted notification date from Metaphysics
  src/Components/Notifications/NotificationItem.tsx
  src/Components/Notifications/__tests__/NotificationItem.jest.tsx
  src/Components/Notifications/__tests__/util.jest.ts
  src/Components/Notifications/util.ts
  src/__generated__/NotificationItem_item.graphql.ts
  src/__generated__/NotificationItem_test_Query.graphql.ts
  src/__generated__/NotificationsListNextQuery.graphql.ts
  src/__generated__/NotificationsListQuery.graphql.ts
  src/__generated__/NotificationsList_test_Query.graphql.ts
Labels: Jira Synced, Squash On Green

#11221 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11223 chore(deps): bumps palette
  package.json
  yarn.lock
Labels: Merge On Green

#11225 feat(TX-665): add spacing to saving payment spinner
  src/Apps/Order/Components/SavingPaymentSpinner.tsx
Labels: Jira Synced, Squash On Green

#11224 feat(FX-4386): add analytics to expandable sidebar sections
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2.jest.tsx
  src/Components/Artwork/SidebarExpandable.tsx
Labels: Jira Synced

#11171 feat(FX-4322): Auctions Watch Lot - In Product Information Overlay
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkAuctionRegistrationPanel.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkAuctionRegistrationPanel.jest.tsx
  src/Components/Timer.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/ArtworkActionsSaveButton_artwork.graphql.ts
  src/__generated__/ArtworkActions_Test_Query.graphql.ts
  src/__generated__/ArtworkAuctionRegistrationPanelQuery.graphql.ts
  src/__generated__/ArtworkAuctionRegistrationPanel_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11226 fix(FX-4326): artworksidebar > partner link should not be underlined
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2PartnerInfo.tsx
Labels: Jira Synced

#11234 chore: update pull request template
  pull_request_template.md
Labels: Jira Synced

#11235 chore(deps): bumps palette
  package.json
  yarn.lock
Labels: Merge On Green

#11232 fix: follow buttons’ tracking payloads
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Components/FollowButton/FollowGeneButton.tsx
  src/Components/FollowButton/FollowProfileButton.tsx
  src/Components/FollowButton/__tests__/useFollowButtonTracking.jest.ts
  src/Components/FollowButton/useFollowButtonTracking.ts
Labels: Jira Synced

#11236 fix: remove is sold from artsy guarantee check
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2.jest.tsx
Labels: Jira Synced

#11215 perf(TX-689): Extend error logging in payment route
  src/Apps/Order/Components/BankAccountPicker.tsx
  src/Apps/Order/Components/PollAccountBalance.tsx
  src/Apps/Order/Components/__tests__/BankAccountPicker.jest.tsx
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Components/BankDebitForm/BankDebitForm.tsx
  src/Components/BankDebitForm/BankDebitProvider.tsx
  src/Components/BankDebitForm/__tests__/BankDebitForm.jest.tsx
  src/Components/BankDebitForm/__tests__/BankDebitProvider.jest.tsx
  src/Utils/logger.ts
Labels: Jira Synced

#11227 feat(FX-4388): display register to bid popover after auth flow
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
  src/Utils/Hooks/useAuthIntent/index.ts
Labels: Jira Synced

#11228 feat(CX-2943): add select artist modal to median sale price
  src/Apps/MyCollectionInsights/Routes/MyCollectionInsightsMedianSalePriceAtAuction/Components/MyCollectionInsightsSelectArtistModal.tsx
  src/Apps/MyCollectionInsights/Routes/MyCollectionInsightsMedianSalePriceAtAuction/MyCollectionInsightsMedianSalePriceAtAuction.tsx
  src/Apps/MyCollectionInsights/myCollectionInsightsRoutes.tsx
  src/__generated__/MyCollectionInsightsMedianSalePriceAtAuction_artist.graphql.ts
  src/__generated__/myCollectionInsightsRoutesQuery.graphql.ts
Labels: Jira Synced

#11238 fix(i18n): globally mocks translation function
  jest.config.js
  src/Apps/ArtQuiz/__tests__/ArtQuizResultsLoader.jest.tsx
  src/Apps/Artist/Routes/CV/Components/ArtistCVGroup.tsx
  src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2ArtsyGuarantee.jest.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
  src/Components/NavBar/__tests__/NavBar.jest.tsx
  src/Components/Notifications/__tests__/MarkAllAsReadPanel.jest.tsx
  src/Components/Notifications/__tests__/Notifications.jest.tsx
  src/DevTools/mockReactI18n.tsx
  src/DevTools/setupTestWrapper.tsx
  src/System/i18n/config.ts
  src/System/i18n/i18n.ts
Labels: Merge On Green

#11240 fix(theme): uses a single theme provider
  src/Apps/Components/AppShell.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/Onboarding/Components/OnboardingFollows.tsx
  src/Components/Onboarding/Components/OnboardingProgress.tsx
  src/Components/Onboarding/Views/OnboardingFollowArtists.tsx
  src/System/Router/Boot.tsx
Labels: Merge On Green

#11241 feat(GRO-1325): additional follow description copy
  src/Components/Onboarding/Components/OnboardingFollows.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Merge On Green

#11242 fix: Type guard in logger
  src/Utils/logger.ts
Labels: Squash On Green

#11127 feat(art-quiz): create results page structure
  src/Apps/ArtQuiz/ArtQuizResults.tsx
  src/Apps/ArtQuiz/ArtQuizWelcome.tsx
  src/Apps/ArtQuiz/__tests__/ArtQuizResults.jest.tsx
  src/Apps/ArtQuiz/__tests__/ArtQuizResultsLoader.jest.tsx
  src/Apps/ArtQuiz/artQuizRoutes.ts
  src/System/i18n/locales/en-US/translation.json
Labels: Merge On Green, Jira Synced

#11248 perf(TX-702): improve error logging in review route
  src/Apps/Order/Routes/Review/index.tsx
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/Review_order.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
Labels: Jira Synced

#11250 chore: register to bid popover improvements
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
Labels: Jira Synced

#11255 fix: Restore artist follow count to all breakpoints GRO-1382
  src/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
Labels: Merge On Green

#11249 feat:PX-5250 unlisted artwork banner
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/UnlistedBannerModal.tsx
  src/Components/UnlistedArtworkBanner.tsx
  src/Components/__tests__/UnlistedArtworkBanner.jest.tsx
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/UnlistedArtworkBanner_Test_Query.graphql.ts
  src/__generated__/UnlistedArtworkBanner_partner.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11260 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11082 feat(artwork): Update video carousel to support order
  scripts/sync-schema-local.sh
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowserLarge.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowserSmall.tsx
  src/__generated__/ArtworkImageBrowserLarge_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowserLarge_artwork.graphql.ts
  src/__generated__/ArtworkImageBrowserSmall_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowserSmall_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11262 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11263 fix: wraps performance observer initialization in a try/catch
  src/Utils/Hooks/useImagePerformanceObserver.ts
Labels: Merge On Green

#11268 fix: Check price estimate requests
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkRequestPriceEstimateSection.tsx
  src/__generated__/MyCollectionArtworkRequestPriceEstimateSection_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11267 test(TX-853): testing logger
  src/Apps/Order/Routes/Payment/index.tsx
  src/Utils/__tests__/logger.jest.ts
Labels: Jira Synced

#11266 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useAddCreditCardAndUpdateProfileMutation.graphql.ts
  src/__generated__/useUpdateMyUserProfileMutation.graphql.ts
  src/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Squash On Green

#11273 fix: error type
  src/Apps/Order/Routes/Payment/index.tsx
Labels: Squash On Green
