Repository artsy/force, pull requests merged in 2022-06, with the labels that each got.

#10183 feat(art-appraisals): Stub out app
  cypress/integration/artAppraisals.spec.ts
  src/v2/Apps/ArtAppraisals/ArtAppraisalsApp.tsx
  src/v2/Apps/ArtAppraisals/artAppraisalsRoutes.tsx
  src/v2/routes.tsx
Labels: Jira Synced

#10191 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10192 chore: update metaphysics graphql schema
  data/schema.graphql
  src/v2/__generated__/PaymentRouteSetOrderPaymentMutation.graphql.ts
  src/v2/__generated__/commitMutationTest1Mutation.graphql.ts
  src/v2/__generated__/useSetPaymentMutation.graphql.ts
Labels: Squash On Green

#10194 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10195 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10201 chore(webpack): optimize
  package.json
  src/dev.js
  src/v2/Apps/Home/HomeApp.tsx
  webpack/envs/clientDevelopmentConfig.js
  webpack/envs/splitChunks.js
  webpack/utils/env.js
  yarn.lock
Labels: Merge On Green

#10206 chore: update metaphysics graphql schema
  data/schema.graphql
  src/v2/__generated__/IdentityVerificationAppTestQuery.graphql.ts
  src/v2/__generated__/IdentityVerificationApp_me.graphql.ts
  src/v2/__generated__/identityVerificationRoutes_IdentityVerificationAppQuery.graphql.ts
Labels: Squash On Green

#10204 chore(FX-4005): display "Saved" label when artwork is saved
  src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
Labels: Jira Synced

#10211 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10196 feat: re-enable new color filtering palette
  src/v2/Apps/Collect/Routes/Collect/Utils/__tests__/getMetadata.jest.ts
  src/v2/Apps/Collect/Routes/Collect/Utils/getMetadata.ts
  src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.jest.tsx
Labels: Jira Synced

#10214 chore: update metaphysics graphql schema
  data/schema.graphql
  src/v2/__generated__/ArtistApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtistApp_artist.graphql.ts
  src/v2/__generated__/ArtistApp_sharedMetadata.graphql.ts
  src/v2/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
  src/v2/__generated__/ArtistHeader_Test_Query.graphql.ts
  src/v2/__generated__/SelectedCareerAchievementsTestQuery.graphql.ts
  src/v2/__generated__/SelectedCareerAchievements_artist.graphql.ts
  src/v2/__generated__/artistRoutes_TopLevelQuery.graphql.ts
Labels: Squash On Green

#10222 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10187 feat: update Payment step to work with new set payment mutation
  src/v2/Apps/Order/Components/Mutations/useSetPayment.ts
  src/v2/Apps/Order/Components/SetPayment.tsx
  src/v2/Apps/Order/OrderApp.tsx
  src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/v2/Apps/Order/Routes/Payment/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Payment.jest.tsx
  src/v2/Apps/Order/Utils/__tests__/commitMutation.jest.tsx
  src/v2/Apps/Order/redirects.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/__generated__/PaymentTestQuery.graphql.ts
  src/v2/__generated__/Payment_order.graphql.ts
  src/v2/__generated__/orderRoutes_OrderQuery.graphql.ts
  src/v2/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/v2/__generated__/redirects_order.graphql.ts
  src/v2/__generated__/useSetPaymentMutation.graphql.ts
Labels: Jira Synced

#10227 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10223 feat(FX-3997): Expand New 'Save' Styling to ShelfArtwork component
  src/v2/Components/Artwork/ShelfArtwork.tsx
Labels: Jira Synced

#10188 feat(NX-3139): pass webview event to Eigen after offer submission
  src/typings/global.d.ts
  src/v2/Apps/Order/Routes/Review/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/v2/__generated__/ReviewTestQuery.graphql.ts
  src/v2/__generated__/Review_order.graphql.ts
  src/v2/__generated__/orderRoutes_ReviewQuery.graphql.ts
Labels: Jira Synced

#10218 feat(art-appraisals): Add page content
  src/desktop/apps/sitemaps/helpers.ts
  src/v2/Apps/ArtAppraisals/ArtAppraisalsApp.tsx
Labels: Jira Synced

#10236 fix: removes offset; removes double focus
  src/v2/Apps/ArtAppraisals/ArtAppraisalsApp.tsx
Labels: Merge On Green

#10237 feat: Add lot countdown timer + progress bar in bid modal
  src/v2/Apps/Auction/Routes/Bid/AuctionBidRoute.tsx
  src/v2/Apps/Auction/Routes/Bid/__tests__/AuctionBidRoute.jest.tsx
  src/v2/__generated__/AuctionBidRouteQuery.graphql.ts
  src/v2/__generated__/AuctionBidRouteTestQuery.graphql.ts
  src/v2/__generated__/AuctionBidRoute_artwork.graphql.ts
  src/v2/__generated__/auctionRoutes_BidRouteQuery.graphql.ts
Labels: Jira Synced

#10234 enhancement(FX-4016): Add new hover behavior to artwork cards in ArtworkShelf
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistNotableWorksRail.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistWorksForSaleRail.tsx
  src/v2/Apps/Auctions/Components/AuctionArtworksRail.tsx
  src/v2/Apps/Auctions/Components/StandoutLotsRail.tsx
  src/v2/Apps/Auctions/Components/TrendingLotsRail.tsx
  src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/SoldRecentlyOnArtsy.tsx
  src/v2/Apps/Fair/Components/FairBoothRail/FairBoothRailArtworks.tsx
  src/v2/Apps/Home/Components/HomeAuctionLotsRail.tsx
  src/v2/Apps/Home/Components/HomeRecentlyViewedRail.tsx
  src/v2/Apps/Home/Components/HomeWorksByArtistsYouFollowRail.tsx
  src/v2/Components/Artwork/ShelfArtwork.tsx
Labels: Jira Synced

#10242 Revert "enhancement(FX-4016): Add new hover behavior to artwork cards in ArtworkShelf"
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistNotableWorksRail.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistWorksForSaleRail.tsx
  src/v2/Apps/Auctions/Components/AuctionArtworksRail.tsx
  src/v2/Apps/Auctions/Components/StandoutLotsRail.tsx
  src/v2/Apps/Auctions/Components/TrendingLotsRail.tsx
  src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/SoldRecentlyOnArtsy.tsx
  src/v2/Apps/Fair/Components/FairBoothRail/FairBoothRailArtworks.tsx
  src/v2/Apps/Home/Components/HomeAuctionLotsRail.tsx
  src/v2/Apps/Home/Components/HomeRecentlyViewedRail.tsx
  src/v2/Apps/Home/Components/HomeWorksByArtistsYouFollowRail.tsx
  src/v2/Components/Artwork/ShelfArtwork.tsx
Labels: Merge On Green, Jira Synced

#10244 fix(FX-4020): Jumping state for "Notable Works" rail on artwork page
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistNotableWorksRail.tsx
Labels: Jira Synced, Squash On Green

#10186 Send trending sort for artist artwork grids based on Unleash flag
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilter.jest.tsx
  src/v2/Apps/Artist/Routes/WorksForSale/Utils/__tests__/getDefaultSort.jest.ts
  src/v2/Apps/Artist/Routes/WorksForSale/Utils/getDefaultSort.ts
  src/v2/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
  src/v2/__generated__/ArtistArtworkFilterTestQuery.graphql.ts
Labels: Jira Synced

#10232 chore: add test attributes
  src/v2/Apps/Order/Components/PaymentPicker.tsx
  src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx
Labels: Jira Synced

#10249 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10252 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10253 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10254 refactor: converts artist consign to v3
  src/v2/Apps/Artist/Routes/Consign/ArtistConsignRoute.tsx
  src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
  src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/ArtistConsignHeaderImages.tsx
  src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/index.tsx
  src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
  src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignMarketTrends.tsx
  src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignMeta.tsx
  src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignPageViews.tsx
  src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
  src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
  src/v2/Apps/Artist/Routes/Consign/Components/SectionContainer.tsx
  src/v2/Apps/Artist/Routes/Consign/Components/Subheader.tsx
  src/v2/Apps/Artist/Routes/Consign/Components/__tests__/ArtistConsignMeta.jest.tsx
  src/v2/Apps/Artist/Routes/Consign/__tests__/ArtistConsignRoute.jest.tsx
  src/v2/Apps/Artist/artistRoutes.tsx
  src/v2/__generated__/ArtistConsignHeaderImages_artist.graphql.ts
  src/v2/__generated__/ArtistConsignHeader_artist.graphql.ts
  src/v2/__generated__/ArtistConsignRoute_Test_Query.graphql.ts
  src/v2/__generated__/artistRoutes_ArtistConsignQuery.graphql.ts
Labels: Merge On Green

#10258 refactor: updates indentity verification to v3
  src/v2/Apps/IdentityVerification/Error.tsx
  src/v2/Apps/IdentityVerification/IdentityVerificationApp/CompleteFailed.tsx
  src/v2/Apps/IdentityVerification/IdentityVerificationApp/CompletePassed.tsx
  src/v2/Apps/IdentityVerification/IdentityVerificationApp/CompleteWatchlistHit.tsx
  src/v2/Apps/IdentityVerification/IdentityVerificationApp/WrongOwner.tsx
  src/v2/Apps/IdentityVerification/IdentityVerificationApp/index.tsx
  src/v2/Apps/IdentityVerification/Processing.tsx
  src/v2/Apps/IdentityVerification/__tests__/IdentityVerificationApp.jest.tsx
  src/v2/Apps/IdentityVerification/__tests__/Utils/IdentityVerificationAppTestPage.tsx
  src/v2/Apps/IdentityVerification/identityVerificationRoutes.tsx
Labels: Merge On Green

#10264 lib(update): Update eigen-www
  package.json
  yarn.lock
Labels: Merge On Green

#10269 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10255 fix: "Works for You" page does not display correctly in Firefox
  src/v2/Apps/WorksForYou/WorksForYouApp.tsx
Labels: Jira Synced

#10268 [ENHANCEMENT]: AlicanAkyuz/TX-403/UI-improvements-checkout-flow
  src/v2/Apps/Order/Components/BankDebitDetails.tsx
  src/v2/Apps/Order/Components/PaymentMethodSummaryItem.tsx
  src/v2/Apps/Order/Components/WireTransferDetails.tsx
  src/v2/Apps/Order/Components/__tests__/WireTransferDetails.jest.tsx
  src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/v2/Apps/Order/Routes/Review/index.tsx
  src/v2/Apps/Order/Routes/Status/index.tsx
Labels: Jira Synced

#10263 feat: unauthenticated users can start Identity Verification
  src/lib/middleware/__tests__/userRequiredMiddleware.jest.ts
  src/lib/middleware/userRequiredMiddleware.ts
  src/v2/Apps/IdentityVerification/IdentityVerificationApp/WrongOwner.tsx
  src/v2/Apps/IdentityVerification/IdentityVerificationApp/index.tsx
  src/v2/Apps/IdentityVerification/__fixtures__/routes_IdentityVerificationAppQuery.ts
  src/v2/Apps/IdentityVerification/__tests__/IdentityVerificationApp.jest.tsx
  src/v2/Apps/IdentityVerification/__tests__/routes.jest.tsx
  src/v2/Apps/IdentityVerification/identityVerificationRoutes.tsx
  src/v2/__generated__/IdentityVerificationAppTestQuery.graphql.ts
  src/v2/__generated__/IdentityVerificationApp_identityVerification.graphql.ts
  src/v2/__generated__/IdentityVerificationApp_me.graphql.ts
  src/v2/__generated__/identityVerificationRoutes_IdentityVerificationAppQuery.graphql.ts
Labels: Jira Synced

#10273 [fix]: AlicanRachelKiril/pull-paymentMethod-upon-setting-payment
  src/v2/Apps/Order/Routes/Payment/index.tsx
  src/v2/Apps/Order/Routes/__fixtures__/MutationResults/setOrderPayment.ts
  src/v2/__generated__/PaymentRouteSetOrderPaymentMutation.graphql.ts
Labels: Squash On Green

#10278 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10277 enhancement: return 404 when identity verification does not exist
  src/v2/Apps/IdentityVerification/IdentityVerificationApp/index.tsx
  src/v2/Apps/IdentityVerification/__tests__/IdentityVerificationApp.jest.tsx
Labels: Jira Synced

#10279 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10250 feat(colors): add brown color filter option
  src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.jest.tsx
Labels: Jira Synced, Do not merge

#10281 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10282 fix: removes dead spec
  cypress/integration/campaign.spec.ts
Labels: Merge On Green

#10283 fix: scroll to booths container
  src/v2/Apps/Fair/Routes/FairOverview.tsx
  src/v2/Apps/Fair/Routes/__tests__/FairOverview.jest.tsx
Labels: Squash On Green

#10290 refactor(v2): removes more code; removes serif completely
  src/desktop/apps/editorial_features/components/gucci/components/nav/header.tsx
  src/desktop/components/react/stitch_components/index.tsx
  src/desktop/lib/logoutHandler.ts
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/BackupSecondFactor/__tests__/index.jest.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/BackupSecondFactor/index.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/__tests__/TwoFactorAuthentication.jest.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/__tests__/fixtures.ts
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/index.tsx
  src/v2/Components/ArtistInsightsModal.tsx
  src/v2/Components/Auction/AuctionRegistrationModal.tsx
  src/v2/Components/Auction/__tests__/AuctionRegistrationModal.jest.tsx
  src/v2/Components/Auction/__tests__/PostRegistrationModal.jest.tsx
  src/v2/Components/Authentication/Components/AuthenticationModal.tsx
  src/v2/Components/FlashBanner/index.tsx
  src/v2/Components/Modal/FlashModal.tsx
  src/v2/Components/Modal/Modal.tsx
  src/v2/Components/Modal/ModalCta.tsx
  src/v2/Components/Modal/ModalHeader.tsx
  src/v2/Components/Modal/ModalWrapper.tsx
  src/v2/Components/Modal/__tests__/Modal.jest.tsx
  src/v2/Components/Modal/__tests__/ModalCta.jest.tsx
  src/v2/Components/SelectedCareerAchievements.tsx
  src/v2/Components/__tests__/SelectedCareerAchievements.jest.tsx
  src/v2/System/Router/Boot.tsx
  src/v2/__generated__/BackupSecondFactor_me.graphql.ts
  src/v2/__generated__/TwoFactorAuthenticationQuery.graphql.ts
  src/v2/__generated__/TwoFactorAuthenticationRefetchQuery.graphql.ts
  src/v2/__generated__/TwoFactorAuthenticationTestQuery.graphql.ts
  src/v2/__generated__/TwoFactorAuthentication_me.graphql.ts
Labels: Merge On Green

#10292 chore: bump jsprim
  yarn.lock
Labels: Squash On Green

#10293 chore: update metaphysics graphql schema
  data/schema.graphql
  src/v2/__generated__/AcceptRouteSetOrderPaymentMutation.graphql.ts
  src/v2/__generated__/AcceptTestQuery.graphql.ts
  src/v2/__generated__/ConversationCTA_Test_Query.graphql.ts
  src/v2/__generated__/ConversationCTA_conversation.graphql.ts
  src/v2/__generated__/ConversationMessages_Test_Query.graphql.ts
  src/v2/__generated__/ConversationMessages_events.graphql.ts
  src/v2/__generated__/CounterSubmitMutation.graphql.ts
  src/v2/__generated__/CounterTestQuery.graphql.ts
  src/v2/__generated__/Counter_order.graphql.ts
  src/v2/__generated__/DetailsSidebar_conversation.graphql.ts
  src/v2/__generated__/NewPaymentRouteSetOrderPaymentMutation.graphql.ts
  src/v2/__generated__/NewPaymentTestQuery.graphql.ts
  src/v2/__generated__/Offer2TestQuery.graphql.ts
  src/v2/__generated__/OfferTestQuery.graphql.ts
  src/v2/__generated__/Offer_order.graphql.ts
  src/v2/__generated__/OrderUpdate_Test_Query.graphql.ts
  src/v2/__generated__/OrderUpdate_event.graphql.ts
  src/v2/__generated__/PaymentPickerEigenTestQuery.graphql.ts
  src/v2/__generated__/PaymentPickerTestQuery.graphql.ts
  src/v2/__generated__/PaymentPicker_order.graphql.ts
  src/v2/__generated__/PaymentRouteSetOrderPaymentMutation.graphql.ts
  src/v2/__generated__/PaymentTestQuery.graphql.ts
  src/v2/__generated__/RespondTestQuery.graphql.ts
  src/v2/__generated__/Respond_order.graphql.ts
  src/v2/__generated__/ReviewSubmitOfferOrderWithConversationMutation.graphql.ts
  src/v2/__generated__/ReviewSubmitOrderMutation.graphql.ts
  src/v2/__generated__/ReviewTestQuery.graphql.ts
  src/v2/__generated__/SetShippingMutation.graphql.ts
  src/v2/__generated__/SettingsPurchasesQuery.graphql.ts
  src/v2/__generated__/SettingsPurchasesRow_order.graphql.ts
  src/v2/__generated__/SettingsPurchases_Test_Query.graphql.ts
  src/v2/__generated__/ShippingSummaryItem_order.graphql.ts
  src/v2/__generated__/ShippingTestQuery.graphql.ts
  src/v2/__generated__/Shipping_order.graphql.ts
  src/v2/__generated__/StatusQuery.graphql.ts
  src/v2/__generated__/Status_order.graphql.ts
  src/v2/__generated__/commitMutationTest1Mutation.graphql.ts
  src/v2/__generated__/createMockNetworkLayerTestMutationResultsMutation.graphql.ts
  src/v2/__generated__/orderRoutes_OrderQuery.graphql.ts
  src/v2/__generated__/redirects_order.graphql.ts
  src/v2/__generated__/useSetPaymentMutation.graphql.ts
Labels: Squash On Green

#10295 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10296 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10297 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10246 chore(FX-4007): replace hover to click on rightmost navigation bar elements
  src/v2/Components/NavBar/NavBarLoggedInActions.tsx
  src/v2/Components/NavBar/__tests__/NavBarTracking.jest.tsx
Labels: Jira Synced

#10248 chore(FX-3972): track analytics for Trending Sort A/B test
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
Labels: Jira Synced

#10294 refactor(v2): replaces more modals
  src/v2/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
  src/v2/Apps/Artwork/Components/ArtworkDetails/index.tsx
  src/v2/Apps/Artwork/Components/ArtworkDetailsMediumModal.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx
  src/v2/Apps/Artwork/Components/__tests__/ArtworkDetailsMediumModal.jest.tsx
  src/v2/Apps/IdentityVerification/IdentityVerificationApp/index.tsx
  src/v2/Apps/IdentityVerification/__tests__/IdentityVerificationApp.jest.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/ApiErrorModal.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/SmsSecondFactor/__tests__/SmsSecondFactor.jest.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
  src/v2/Components/Modal/ErrorModal.tsx
  src/v2/Components/Modal/__tests__/ErrorModal.jest.tsx
Labels: Merge On Green

#10299 fix: fixes spec
  src/v2/Apps/Artwork/Components/ArtworkDetails/__tests__/RequestConditionReport.jest.tsx
Labels: Merge On Green

#10302 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10303 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10304 refactor(v2): removes modal dialog; majority of sans
  .eslintrc.js
  src/v2/Apps/Order/Components/ConditionsOfSaleDisclaimer.tsx
  src/v2/Apps/Order/Dialogs.tsx
  src/v2/Apps/Order/Routes/__tests__/Accept.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer2.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Reject.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Respond.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/BackupSecondFactor/BackupSecondFactorModalContent.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/BackupSecondFactor/Mutation/CreateBackupSecondFactors.ts
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/__tests__/fixtures.ts
  src/v2/Components/ArtistInsight.tsx
  src/v2/Components/Modal/ModalDialog.tsx
  src/v2/Components/Modal/__tests__/ModalDialog.jest.tsx
  src/v2/__generated__/BackupSecondFactorModalContentQuery.graphql.ts
  src/v2/__generated__/BackupSecondFactorModalContent_me.graphql.ts
  src/v2/__generated__/CreateBackupSecondFactorsMutation.graphql.ts
Labels: Merge On Green

#10311 chore(deps): bumps palette
  package.json
  yarn.lock
Labels: Merge On Green

#10313 fix(auction): wait for mount on bid route
  src/v2/Apps/Auction/Routes/Bid/AuctionBidRoute.tsx
  src/v2/Apps/Auction/Routes/Bid/__tests__/AuctionBidRoute.jest.tsx
Labels: Merge On Green

#10314 chore: update metaphysics graphql schema
  data/schema.graphql
  src/v2/__generated__/ArtistApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtistApp_artist.graphql.ts
  src/v2/__generated__/ArtistApp_sharedMetadata.graphql.ts
  src/v2/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
  src/v2/__generated__/ArtistHeader_Test_Query.graphql.ts
  src/v2/__generated__/ArtistMetaCanonicalLink_artist.graphql.ts
  src/v2/__generated__/SelectedCareerAchievementsTestQuery.graphql.ts
  src/v2/__generated__/SelectedCareerAchievements_artist.graphql.ts
  src/v2/__generated__/artistRoutes_TopLevelQuery.graphql.ts
Labels: Squash On Green

#10315 Fix typos
  src/v2/Apps/Auction/Routes/Bid/__tests__/useSubmitBid.jest.tsx
  src/v2/Apps/Auction/Routes/Bid/useSubmitBid.ts
  src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethodForm.tsx
  src/v2/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddressForm.tsx
Labels: Merge On Green

#10319 fix(FX-4043): Alert Management page pills styling after palette upgrade
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
Labels: Jira Synced

#10325 fix: temporarily removes zendesk
  src/v2/Apps/Artwork/Components/ArtworkMeta.tsx
Labels: Merge On Green

#10326 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10328 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10308 feat(NX-3140): add purchase submitted message in conversations
  src/v2/Apps/Conversation/Components/OrderUpdate.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConversationMessages.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/OrderUpdate.jest.tsx
  src/v2/__generated__/ConversationMessages_Test_Query.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/OrderUpdate_Test_Query.graphql.ts
  src/v2/__generated__/OrderUpdate_event.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Jira Synced

#10305 bugfix(New For You) - Fix grid ordering, expand and cap page size, add login messaging
  src/v2/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx
  src/v2/Apps/NewForYou/NewForYouApp.tsx
  src/v2/Apps/NewForYou/__tests__/NewForYouApp.jest.tsx
  src/v2/Apps/NewForYou/newForYouRoutes.tsx
  src/v2/__generated__/NewForYouApp_test_Query.graphql.ts
  src/v2/__generated__/NewForYouArtworksGridQuery.graphql.ts
  src/v2/__generated__/NewForYouArtworksGrid_viewer.graphql.ts
  src/v2/__generated__/newForYouRoutes_TopLevelQuery.graphql.ts
Labels: Merge On Green, Jira Synced

#10333 fix: removes google retargeting script
  src/v2/Apps/Artwork/Components/ArtworkMeta.tsx
Labels: Merge On Green

#10334 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10337 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10344 test: remove old relay test tools part III
  src/v2/Apps/Order/Components/__tests__/PaymentPicker.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer2.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Reject.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Respond.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Status.jest.tsx
Labels: Jira Synced

#10346 chore: update metaphysics graphql schema
  data/schema.graphql
  src/v2/__generated__/Offer2TestQuery.graphql.ts
  src/v2/__generated__/PaymentPickerEigenTestQuery.graphql.ts
Labels: Squash On Green

#10349 feat: implements institution-partnerships
  cypress/integration/institutionPartnerships.spec.ts
  src/desktop/apps/partnerships/client/index.coffee
  src/desktop/apps/partnerships/client/router.coffee
  src/desktop/apps/partnerships/client/view.coffee
  src/desktop/apps/partnerships/index.coffee
  src/desktop/apps/partnerships/public/images/auction-browser-1.png
  src/desktop/apps/partnerships/public/images/auction-browser-2.png
  src/desktop/apps/partnerships/public/images/auction-devices.png
  src/desktop/apps/partnerships/public/images/auction-kiosk.png
  src/desktop/apps/partnerships/public/images/auction-logos.png
  src/desktop/apps/partnerships/public/images/auction-projection.png
  src/desktop/apps/partnerships/public/images/auction-social-fb.png
  src/desktop/apps/partnerships/public/images/auction-social-instagram.png
  src/desktop/apps/partnerships/public/images/auction-social-twitter.png
  src/desktop/apps/partnerships/public/images/auction-team-alessandra.png
  src/desktop/apps/partnerships/public/images/auction-team-christine.png
  src/desktop/apps/partnerships/public/images/auction-team-colin.png
  src/desktop/apps/partnerships/public/images/auction-team-liz.png
  src/desktop/apps/partnerships/public/images/auction-team-rebecca.png
  src/desktop/apps/partnerships/public/images/browser-window.jpg
  src/desktop/apps/partnerships/public/images/mobile-window.png
  src/desktop/apps/partnerships/routes.coffee
  src/desktop/apps/partnerships/stylesheets/edit.styl
  src/desktop/apps/partnerships/stylesheets/index.styl
  src/desktop/apps/partnerships/stylesheets/marketo.styl
  src/desktop/apps/partnerships/templates/auction_sections.jade
  src/desktop/apps/partnerships/templates/common_section_mixins.jade
  src/desktop/apps/partnerships/templates/content.jade
  src/desktop/apps/partnerships/templates/hero_unit.jade
  src/desktop/apps/partnerships/templates/index.jade
  src/desktop/apps/partnerships/templates/institution_sections.jade
  src/desktop/apps/partnerships/templates/meta.jade
  src/desktop/apps/partnerships/templates/nav.jade
  src/desktop/apps/partnerships/test/client/router.test.js
  src/desktop/apps/partnerships/test/client/view.test.js
  src/desktop/apps/partnerships/test/fixture/auction_content.json
  src/desktop/apps/partnerships/test/fixture/content.json
  src/desktop/apps/partnerships/test/routes.test.js
  src/desktop/apps/partnerships/test/templates.test.js
  src/desktop/assets/partners.styl
  src/desktop/assets/partners.ts
  src/desktop/index.ts
  src/v2/Apps/InstitutionPartnerships/Components/InstitutionPartnershipsProfiles.tsx
  src/v2/Apps/InstitutionPartnerships/Components/InstitutionPartnershipsShows.tsx
  src/v2/Apps/InstitutionPartnerships/InstitutionPartnershipsApp.tsx
  src/v2/Apps/InstitutionPartnerships/institutionPartnershipsRoutes.tsx
  src/v2/__generated__/InstitutionPartnershipsProfilesQuery.graphql.ts
  src/v2/__generated__/InstitutionPartnershipsProfiles_orderedSet.graphql.ts
  src/v2/__generated__/InstitutionPartnershipsShowsQuery.graphql.ts
  src/v2/__generated__/InstitutionPartnershipsShows_orderedSet.graphql.ts
  src/v2/routes.tsx
Labels: Merge On Green

#10356 chore: upgrade stripe libs
  yarn.lock
Labels: Jira Synced, Squash On Green

#10358 fix: various layout consistency fixes
  src/v2/Apps/Artist/ArtistApp.tsx
  src/v2/Apps/Artist/Components/BackLink.tsx
  src/v2/Apps/Artist/Components/__tests__/BackLink.jest.tsx
  src/v2/Apps/Artist/Routes/CV/ArtistCVRoute.tsx
  src/v2/Apps/Artist/Routes/CV/Components/ArtistCVGroup.tsx
  src/v2/Apps/Artist/Routes/CV/__tests__/ArtistCVRoute.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarClassification.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebarClassificationsModal.tsx
  src/v2/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
  src/v2/Apps/Artwork/Components/__tests__/ArtworkSidebarClassificationsModal.jest.tsx
  src/v2/Components/TopContextBar.tsx
  src/v2/__generated__/ArtistApp_Test_Query.graphql.ts
  src/v2/__generated__/BackLink_Test_Query.graphql.ts
  src/v2/__generated__/BackLink_artist.graphql.ts
  src/v2/__generated__/artistRoutes_TopLevelQuery.graphql.ts
Labels: Merge On Green

#10367 fix: CTA was not actionable for BN only artworks (CBN)
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/EditionSelectBox.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConfirmArtwork.jest.tsx
  src/v2/__generated__/ConfirmArtworkModalQuery.graphql.ts
  src/v2/__generated__/ConfirmArtworkModal_Test_Query.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/EditionSelectBox_edition.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#10378 Revert "[Coordinated merge] Disable submit button on review step until Stripe is ready"
  src/v2/Apps/Order/Routes/Review/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Review.jest.tsx
Labels: Merge On Green

#10370 feat(NX-3187): add all purchase states in conversations
  src/v2/Apps/Conversation/Components/OrderUpdate.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConversationMessages.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/OrderUpdate.jest.tsx
  src/v2/__generated__/ConversationMessages_Test_Query.graphql.ts
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/OrderUpdate_Test_Query.graphql.ts
  src/v2/__generated__/OrderUpdate_event.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Jira Synced

#10288 enhancement(FX-4016): Add new hover behavior to artwork cards in ArtworkShelf
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistNotableWorksRail.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistWorksForSaleRail.tsx
  src/v2/Apps/Auctions/Components/AuctionArtworksRail.tsx
  src/v2/Apps/Auctions/Components/StandoutLotsRail.tsx
  src/v2/Apps/Auctions/Components/TrendingLotsRail.tsx
  src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/SoldRecentlyOnArtsy.tsx
  src/v2/Apps/Fair/Components/FairBoothRail/FairBoothRailArtworks.tsx
  src/v2/Apps/Home/Components/HomeAuctionLotsRail.tsx
  src/v2/Apps/Home/Components/HomeRecentlyViewedRail.tsx
  src/v2/Apps/Home/Components/HomeWorksByArtistsYouFollowRail.tsx
  src/v2/Components/Artwork/Details.tsx
  src/v2/Components/Artwork/ShelfArtwork.tsx
Labels: Jira Synced, Squash On Green

#10372 chore: bump prismjs
  yarn.lock
Labels: Jira Synced

#10266 feat(GRO-1061): Render artist insights data on Artist overview page
  src/v2/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
  src/v2/Apps/Artist/Components/ArtistHeader/__tests__/ArtistHeader.jest.tsx
  src/v2/Apps/Artist/Components/ArtistInsights/ArtistInsightAchievements.tsx
  src/v2/Apps/Artist/Components/ArtistInsights/ArtistInsightBadges.tsx
  src/v2/Apps/Artist/Components/ArtistInsights/ArtistInsightPills.tsx
  src/v2/Apps/Artist/Components/ArtistInsights/__tests__/ArtistInsightAchievements.jest.tsx
  src/v2/Apps/Artist/Components/ArtistInsights/__tests__/ArtistInsightBadges.jest.tsx
  src/v2/Apps/Artist/Components/ArtistInsights/__tests__/ArtistInsightPills.jest.tsx
  src/v2/Apps/Artist/Components/ArtistInsights/index.ts
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlights.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/__tests__/ArtistCareerHighlights.jest.tsx
  src/v2/Components/ArtistInsight.tsx
  src/v2/Components/SelectedCareerAchievements.tsx
  src/v2/Components/__tests__/ArtistInsight.jest.tsx
  src/v2/Components/__tests__/SelectedCareerAchievements.jest.tsx
  src/v2/__generated__/ArtistApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtistCareerHighlightsQuery.graphql.ts
  src/v2/__generated__/ArtistCareerHighlights_artist.graphql.ts
  src/v2/__generated__/ArtistHeader_Test_Query.graphql.ts
  src/v2/__generated__/ArtistHeader_artist.graphql.ts
  src/v2/__generated__/ArtistInsightAchievements_Test_Query.graphql.ts
  src/v2/__generated__/ArtistInsightAchievements_artist.graphql.ts
  src/v2/__generated__/ArtistInsightBadges_Test_Query.graphql.ts
  src/v2/__generated__/ArtistInsightBadges_artist.graphql.ts
  src/v2/__generated__/ArtistInsightPills_Test_Query.graphql.ts
  src/v2/__generated__/ArtistInsightPills_artist.graphql.ts
  src/v2/__generated__/SelectedCareerAchievementsTestQuery.graphql.ts
  src/v2/__generated__/artistRoutes_TopLevelQuery.graphql.ts
Labels: Merge On Green, Jira Synced

#10385 feat(onboarding): adds animated welcome panel
  src/v2/Apps/Onboarding/Components/OnboardingSplitLayout.tsx
  src/v2/Apps/Onboarding/Components/OnboardingWelcomeAnimatedPanel.tsx
  src/v2/Apps/Onboarding/Views/OnboardingWelcome.tsx
Labels: Merge On Green

#10386 chore: bump-ansi-regex
  yarn.lock
Labels: Jira Synced

#10393 chore(footer): swap out assets
  src/v2/Components/DownloadAppBadges/DownloadAppBadge.tsx
  src/v2/Components/Footer/FooterDownloadAppBanner.tsx
Labels: Jira Synced

#10398 fix(NX-3190): fix bug on CBN flow for edition sets
  src/v2/Apps/Conversation/Components/ConfirmArtworkButton.tsx
  src/v2/Apps/Conversation/Components/ConfirmArtworkModal.tsx
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/ConversationCTA.tsx
  src/v2/Apps/Conversation/Components/OrderModal.tsx
  src/v2/Apps/Conversation/Components/Reply.tsx
Labels: Jira Synced

#10388 feat: Enable NOSF for single editions with listed price
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/__generated__/OfferTestQuery.graphql.ts
  src/v2/__generated__/Offer_order.graphql.ts
  src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
Labels: Jira Synced

#10368 feat(PX-5031): Support EU/NO/GB/CH checkout out flows with artsy shipping
  package.json
  src/v2/Apps/Order/Routes/Shipping/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  yarn.lock
Labels: Jira Synced

#10401 feat(onboarding): animates progress bar
  src/v2/Apps/Onboarding/Components/OnboardingProgress.tsx
  src/v2/Apps/Onboarding/Views/OnboardingQuestionOne.tsx
  src/v2/Apps/Onboarding/Views/OnboardingQuestionThree.tsx
  src/v2/Apps/Onboarding/Views/OnboardingQuestionTwo.tsx
  src/v2/Utils/Hooks/useDebounce.ts
Labels: Merge On Green

#10403 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10405 refactor(v2): more v2 clean up
  docs/migrating_app_palette_v3.md
  src/v2/Apps/Auction/auctionRoutes.tsx
  src/v2/Apps/Components/AppShell.tsx
  src/v2/Apps/Order/Components/SavedAddressItem.tsx
  src/v2/Apps/Order/Components/SavedAddresses.tsx
  src/v2/Apps/Order/Components/TermsOfServiceCheckbox.tsx
  src/v2/Apps/Settings/settingsRoutes.tsx
  src/v2/Components/Address/AddressModalFields.tsx
  src/v2/Components/AddressForm.tsx
  src/v2/Components/Artwork/Details.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/AttributionClassFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/FilterExpandable.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/ShowMore.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
  src/v2/Components/Footer/Footer.tsx
  src/v2/Components/Footer/FooterDownloadAppBanner.tsx
  src/v2/Components/Pagination/index.tsx
  src/v2/Components/Timer.tsx
  src/v2/System/Router/Route.tsx
Labels: Merge On Green

#10407 fix(onboarding): handles options for remaining answer
  src/v2/Apps/Onboarding/Views/OnboardingQuestionThree.tsx
Labels: Merge On Green

#10390 feat: add new payment methods to the order history page.
  src/v2/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
  src/v2/__generated__/SettingsPurchasesQuery.graphql.ts
  src/v2/__generated__/SettingsPurchasesRow_order.graphql.ts
  src/v2/__generated__/SettingsPurchases_Test_Query.graphql.ts
  src/v2/__generated__/settingsRoutes_PurchasesRouteQuery.graphql.ts
Labels: Jira Synced

#10406 chore(RelatedCategories): move to bottom of page
  src/v2/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistGenes.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistRelatedGeneCategories.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/__tests__/ArtistGenes.jest.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/__tests__/ArtistRelatedGeneCategories.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/v2/__generated__/ArtistRelatedGeneCategoriesQuery.graphql.ts
  src/v2/__generated__/ArtistRelatedGeneCategories_Test_Query.graphql.ts
  src/v2/__generated__/ArtistRelatedGeneCategories_artist.graphql.ts
Labels: Jira Synced

#10411 fix(artist-insights): Remove blue chip representation & design cleanup
  src/v2/Apps/Artist/Components/ArtistInsights/ArtistInsightAchievements.tsx
  src/v2/Apps/Artist/Components/ArtistInsights/ArtistInsightBadges.tsx
  src/v2/Apps/Artist/Components/ArtistInsights/ArtistInsightPills.tsx
  src/v2/Apps/Artist/Components/ArtistInsights/__tests__/ArtistInsightBadges.jest.tsx
  src/v2/Apps/Artist/Components/ArtistInsights/__tests__/ArtistInsightPills.jest.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlights.tsx
  src/v2/__generated__/ArtistApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtistCareerHighlightsQuery.graphql.ts
  src/v2/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
  src/v2/__generated__/ArtistHeader_Test_Query.graphql.ts
  src/v2/__generated__/ArtistInsightBadges_Test_Query.graphql.ts
  src/v2/__generated__/ArtistInsightBadges_artist.graphql.ts
  src/v2/__generated__/ArtistInsightPills_Test_Query.graphql.ts
  src/v2/__generated__/ArtistInsightPills_artist.graphql.ts
  src/v2/__generated__/artistRoutes_TopLevelQuery.graphql.ts
Labels: Merge On Green, Jira Synced

#10414 chore: deletes unused code
  src/desktop/assets/artwork.styl
  src/desktop/assets/authentication.styl
  src/desktop/assets/gallery_partnerships.ts
  src/desktop/assets/order.styl
  src/desktop/components/main_layout/stylesheets/embedded.styl
  src/desktop/components/main_layout/stylesheets/index.styl
  src/desktop/components/my_active_bids/README.md
  src/desktop/components/my_active_bids/index.styl
  src/desktop/components/my_active_bids/query.coffee
  src/desktop/components/my_active_bids/template.jade
  src/desktop/components/my_active_bids/view.coffee
  src/desktop/components/zoom/index.coffee
  src/desktop/public/images/about_iphone_bg.jpg
  src/desktop/public/images/about_iphone_plate.png
  src/desktop/public/images/auction_results_sources.jpg
  src/desktop/public/images/cc_brands.png
  src/desktop/public/images/fair-iphone-promo-large.jpg
  src/desktop/public/images/fair-iphone-promo.png
  src/desktop/public/images/geotrust.png
  src/desktop/public/images/preview-iphone.jpg
  src/desktop/public/images/select_arrow.png
  src/desktop/public/images/set_mgmt_nux.jpg
  src/lib/__tests__/metaphysics.jest.ts
  src/lib/metaphysics.ts
Labels: Merge On Green

#10415 fix(GRO-1128): fixes mixed content warnings
  src/desktop/apps/eoy_2016/fixtures/data.json
  src/desktop/components/main_layout/footer/index.styl
  src/v2/Apps/About/AboutApp.tsx
  src/v2/Apps/AuctionPartnerships/AuctionPartnershipsApp.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
  src/v2/Apps/__tests__/Fixtures/Collections.ts
  src/v2/Components/ViewInRoom/ViewInRoomRoom.tsx
Labels: Merge On Green

#10423 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10424 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10425 chore: removes rc-slider dependency
  package.json
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilterNew.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilterNew.jest.tsx
  src/v2/Components/Range.tsx
  yarn.lock
Labels: Merge On Green

#10422 feat(GRO-1097)(onboarding): Build top auction lots screen
  src/v2/Apps/Onboarding/Components/OnboardingGene.tsx
  src/v2/Apps/Onboarding/Components/__tests__/OnboardingGene.jest.tsx
  src/v2/Apps/Onboarding/Views/OnboardingArtistsOnTheRise.tsx
  src/v2/Apps/Onboarding/Views/OnboardingCuratedArtworks.tsx
  src/v2/Apps/Onboarding/Views/OnboardingTopAuctionLots.tsx
  src/v2/__generated__/OnboardingGeneQuery.graphql.ts
  src/v2/__generated__/OnboardingGene_Test_Query.graphql.ts
  src/v2/__generated__/OnboardingGene_gene.graphql.ts
Labels: Jira Synced

#10426 feat(follow): updates buttons to 3.1 style
  src/v2/Apps/Artists/Components/ArtistsCarouselCell.tsx
  src/v2/Apps/Artwork/Components/ArtistInfo.tsx
  src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorGroupPlaceholder.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorsGroup.tsx
  src/v2/Apps/Gene/Routes/GeneShow.tsx
  src/v2/Apps/Partner/Components/Carousel/Carousel.tsx
  src/v2/Apps/Partner/Components/Carousel/DesktopCarousel.tsx
  src/v2/Apps/Partner/Components/Carousel/MobileCarousel.tsx
  src/v2/Apps/Partner/Components/Carousel/index.tsx
  src/v2/Apps/Partner/Components/Carousel/useRailOverflow.ts
  src/v2/Apps/Partner/Components/Overview/NearbyGalleriesRail.tsx
  src/v2/Apps/Partner/Components/Overview/NearbyGalleriesRailPlaceholder.tsx
  src/v2/Apps/Partner/Components/Overview/NearbyGalleryCard.tsx
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetails.tsx
  src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistsCarousel/PartnerArtistsCarouselItem.tsx
  src/v2/Apps/Partner/Components/PartnerHeader/index.tsx
  src/v2/Apps/Partner/Components/__tests__/Overview/NearbyGalleryCard.jest.tsx
  src/v2/Apps/Partner/Routes/Overview/index.tsx
  src/v2/Apps/Partners/Components/PartnersFeaturedCarouselCell.tsx
  src/v2/Components/ArtistRail.tsx
  src/v2/Components/CategoryRail.tsx
  src/v2/Components/EntityHeaders/EntityHeaderArtist.tsx
  src/v2/Components/EntityHeaders/EntityHeaderFair.tsx
  src/v2/Components/EntityHeaders/EntityHeaderFairOrganizer.tsx
  src/v2/Components/EntityHeaders/EntityHeaderGene.tsx
  src/v2/Components/EntityHeaders/EntityHeaderPartner.tsx
  src/v2/Components/FollowArtistPopover/FollowArtistPopoverRow.tsx
  src/v2/Components/FollowButton/Button.tsx
  src/v2/Components/FollowButton/FollowGeneButton.tsx
  src/v2/Components/FollowButton/__tests__/FollowGeneButton.jest.tsx
  src/v2/__generated__/FairExhibitorCard_exhibitor.graphql.ts
  src/v2/__generated__/FairExhibitorsGroup_exhibitorsGroup.graphql.ts
  src/v2/__generated__/FairExhibitors_Test_Query.graphql.ts
  src/v2/__generated__/NearbyGalleriesRailRendererQuery.graphql.ts
  src/v2/__generated__/NearbyGalleriesRail_partners.graphql.ts
  src/v2/__generated__/NearbyGalleryCard_Test_Query.graphql.ts
  src/v2/__generated__/NearbyGalleryCard_partner.graphql.ts
  src/v2/__generated__/Overview_partner.graphql.ts
  src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
  src/v2/__generated__/partnerRoutes_OverviewQuery.graphql.ts
Labels: Merge On Green

#10427 fix(tracking): add correct action type for clicked payment method
  src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/v2/Apps/Order/Routes/__tests__/Payment.jest.tsx
Labels: Merge On Green, Jira Synced

#10351 chore(FX-4052): Hide "Create Alert" button on artwork page if there are no associated artists
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBiddingClosedMessage.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebar.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarAuctionInfoPollingQuery.graphql.ts
  src/v2/__generated__/ArtworkSidebarBiddingClosedMessage_artwork.graphql.ts
  src/v2/__generated__/ArtworkSidebarCommercial2_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarCommercial_artwork.graphql.ts
  src/v2/__generated__/ArtworkSidebarCurrentBidInfo_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#10429 chore(deps): bumps palette
  package.json
  src/v2/Apps/About/AboutApp.tsx
  src/v2/Apps/Articles/ChannelApp.tsx
  src/v2/Apps/Articles/Components/ArticlesIndexArticle.tsx
  src/v2/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
  src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/v2/Apps/Artist/Routes/Overview/Components/ArtistSellWithArtsy.tsx
  src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
  src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsArticles.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarMetadata.tsx
  src/v2/Apps/Artwork/Components/PricingContextModal.tsx
  src/v2/Apps/AuctionPartnerships/AuctionPartnershipsApp.tsx
  src/v2/Apps/Auctions/Components/MyBids/MyBids.tsx
  src/v2/Apps/Auctions/Components/MyBids/MyBidsBidHeader.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/PhoneNumberInput.tsx
  src/v2/Apps/Contact/ContactApp.tsx
  src/v2/Apps/Fair/Components/FairOverview/FairAbout.tsx
  src/v2/Apps/Feature/Components/FeatureFeaturedLink.tsx
  src/v2/Apps/Gene/Routes/GeneShow.tsx
  src/v2/Apps/Home/Components/HomeFeaturedEventsRail.tsx
  src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
  src/v2/Apps/Order/Components/__tests__/OfferNote.jest.tsx
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Partners/Components/PartnersFeaturedCarouselCell.tsx
  src/v2/Apps/Settings/Routes/Auctions/Components/SettingsAuctionsLotStanding.tsx
  src/v2/Apps/Settings/Routes/Auctions/Components/UserRegistrationAuctions.tsx
  src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileYourGalleryIntro.tsx
  src/v2/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddress.tsx
  src/v2/Apps/Show/Components/ShowAbout.tsx
  src/v2/Apps/Show/Components/ShowHeader.tsx
  src/v2/Apps/Show/Components/ShowViewingRoom.tsx
  src/v2/Components/Address/AddressModalFields.tsx
  src/v2/Components/AddressForm.tsx
  src/v2/Components/Artwork/Badge.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilters/index.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/Components/AuctionCard.tsx
  src/v2/Components/Cells/CellArticle.tsx
  src/v2/Components/Cells/CellShow.tsx
  src/v2/Components/CreditCardInput/CreditCardInput.tsx
  src/v2/Components/InfoSection.tsx
  src/v2/Components/Inquiry/Views/InquiryBasicInfo.tsx
  src/v2/Components/Inquiry/Views/InquiryInquiry.tsx
  src/v2/Components/NavBar/Menus/NavBarSubMenu.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/v2/Components/__stories__/Carousels.story.tsx
  src/v2/Components/__stories__/Components/ContentMetadataExample.tsx
  src/v2/Components/__stories__/Content.story.tsx
  src/v2/Components/__stories__/Headers.story.tsx
  yarn.lock
Labels: Merge On Green

#10433 fix(footer): uses dropdown to display wechat qr code
  package.json
  src/v2/Components/Footer/Footer.tsx
  yarn.lock
Labels: Merge On Green
