Repository artsy/force, pull requests merged in 2022-05, with the labels that each got.

#10013 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9993 feat(SWA-330): add new landing page content
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/CtaBanner.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/FAQ.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/Header.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/HowItWorks.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/PromoSpace.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/SoldRecentlyOnArtsy.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/WhySellWithArtsy.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/__tests__/FAQ.jest.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/__tests__/Header.jest.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/__tests__/SoldRecentlyOnArtsy.jest.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/index.ts
  src/v2/Apps/Consign/Routes/NewMarketingLanding/MarketingLandingApp.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/__tests__/MarketingLandingApp.jest.tsx
  src/v2/__generated__/SoldRecentlyOnArtsyQuery.graphql.ts
  src/v2/__generated__/SoldRecentlyOnArtsy_recentlySoldArtworks.graphql.ts
  src/v2/__generated__/SoldRecentlyOnArtsy_tests_Query.graphql.ts
Labels: Jira Synced

#10016 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#10020 fix(auth): More redirects
  src/v2/Apps/Artwork/Components/__tests__/ArtistInfo.jest.tsx
  src/v2/Components/FollowButton/__tests__/FollowArtistButton.jest.tsx
  src/v2/Components/__tests__/ArtistCard.jest.tsx
  src/v2/Utils/__tests__/openAuthModal.jest.ts
  src/v2/Utils/openAuthModal.ts
Labels: Merge On Green, Jira Synced

#10023 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#10021 fix(auction): Add auctionPageView tracking event
  package.json
  src/v2/Apps/Auction/AuctionApp.tsx
  src/v2/Apps/Auction/Hooks/useAuctionTracking.ts
  src/v2/Apps/Auction/__tests__/AuctionApp.jest.tsx
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionApp_me.graphql.ts
  src/v2/__generated__/AuctionApp_sale.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#10019 chore:bid 337 blue banner
  src/v2/Apps/Artwork/ArtworkApp.tsx
  src/v2/Apps/Auction/AuctionApp.tsx
  src/v2/Apps/Auction/Components/AuctionDetails/CascadingEndTimesBanner.tsx
  src/v2/Apps/Auction/Components/AuctionDetails/__tests__/CascadingEndTimesBanner.jest.tsx
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkApp_artwork.graphql.ts
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionApp_sale.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
Labels: Jira Synced, Squash On Green, Bidding Engine

#10031 fix(auction): Link conditions of sale
  src/v2/Apps/Auction/Components/Form/ConditionsOfSaleCheckbox.tsx
  src/v2/Apps/Auction/Components/Form/__tests__/ConditionsOfSaleCheckbox.jest.tsx
  src/v2/Apps/Auction/Routes/AuctionConfirmRegistrationRoute.tsx
Labels: Merge On Green

#10014 feat(SWA-348): turn on new landing page
  cypress/integration/consign.spec.ts
  src/desktop/apps/sitemaps/helpers.ts
  src/lib/middleware/hardcodedRedirects.ts
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/CtaBanner.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/Header.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/SellMeta.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/__tests__/Header.jest.tsx
  src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/index.ts
  src/v2/Apps/Consign/Routes/NewMarketingLanding/MarketingLandingApp.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/SubmissionLayout.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/redirects.ts
  src/v2/Apps/Consign/consignRoutes.tsx
  src/v2/Components/NavBar/NavBar.tsx
  src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/v2/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
Labels: Jira Synced

#10027 feature(new for you): create /new-for-you
  src/v2/Apps/NewForYou/NewForYouApp.tsx
  src/v2/Apps/NewForYou/__tests__/NewForYouApp.jest.tsx
  src/v2/Apps/NewForYou/newForYouRoutes.tsx
  src/v2/routes.tsx
Labels: Jira Synced

#10033 GRO-1003: Update general secondary market seller support email to sell@artsy.net
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/ContactUs.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/FAQ.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/ContactUs.jest.tsx
  src/v2/Apps/Consign/Routes/Offer/Components/StickyFooter.tsx
Labels: Jira Synced

#10038 Revert "chore(deps): update dep typescript from 4.3.5 to v4.6.4"
  package.json
  yarn.lock
Labels: Merge On Green

#10040 fix(FX-3920): use displayName over name in gene pages
  src/v2/Apps/Gene/Components/GeneMeta.tsx
  src/v2/Apps/Gene/Routes/GeneShow.tsx
  src/v2/Apps/Gene/Routes/__tests__/GeneShow.jest.tsx
  src/v2/__generated__/GeneMeta_gene.graphql.ts
  src/v2/__generated__/GeneShow_Test_Query.graphql.ts
  src/v2/__generated__/GeneShow_gene.graphql.ts
  src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts
Labels: Jira Synced

#10039 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistIconicCollectionsRailQuery.graphql.ts
  src/v2/__generated__/ArtistIconicCollectionsRail_Test_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesRail_collectionGroup.graphql.ts
  src/v2/__generated__/CollectionsHubRails_linkedCollections.graphql.ts
  src/v2/__generated__/FeaturedCollectionsRails_collectionGroup.graphql.ts
  src/v2/__generated__/Header_collection.graphql.ts
  src/v2/__generated__/OtherCollectionsRail_collectionGroup.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
Labels: Squash On Green

#10037 feat(auction): Add preview sale states
  src/v2/Apps/Auction/AuctionApp.tsx
  src/v2/Apps/Auction/Components/AuctionCurrentAuctionsRail.tsx
  src/v2/Apps/Auction/__tests__/AuctionApp.jest.tsx
  src/v2/Components/Cells/CellSale.story.tsx
  src/v2/Components/Cells/CellSale.tsx
  src/v2/Components/Cells/__tests__/CellSale.jest.tsx
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionApp_sale.graphql.ts
  src/v2/__generated__/AuctionApp_viewer.graphql.ts
  src/v2/__generated__/AuctionCurrentAuctionsRail_viewer.graphql.ts
  src/v2/__generated__/CellSaleFragmentContainer_Test_Query.graphql.ts
  src/v2/__generated__/CellSaleStoryQuery.graphql.ts
  src/v2/__generated__/CellSale_sale.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
Labels: Jira Synced

#10047 GROW-919: Added New for You page title and header copy
  src/v2/Apps/NewForYou/NewForYouApp.tsx
  src/v2/Apps/NewForYou/__tests__/NewForYouApp.jest.tsx
Labels: Jira Synced

#10049 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#10007 feat(TX-295): ACH payment page redesign
  src/v2/Apps/Order/Components/__mocks__/BankDebitProvider.tsx
  src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/v2/Apps/Order/Routes/__tests__/Payment.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx
  src/v2/Components/BankDebitForm/BankDebitForm.tsx
Labels: Jira Synced

#10052 Revert "feat(auction): Add preview sale states "
  src/v2/Apps/Auction/AuctionApp.tsx
  src/v2/Apps/Auction/Components/AuctionCurrentAuctionsRail.tsx
  src/v2/Apps/Auction/__tests__/AuctionApp.jest.tsx
  src/v2/Components/Cells/CellSale.story.tsx
  src/v2/Components/Cells/CellSale.tsx
  src/v2/Components/Cells/__tests__/CellSale.jest.tsx
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionApp_sale.graphql.ts
  src/v2/__generated__/AuctionApp_viewer.graphql.ts
  src/v2/__generated__/AuctionCurrentAuctionsRail_viewer.graphql.ts
  src/v2/__generated__/CellSaleFragmentContainer_Test_Query.graphql.ts
  src/v2/__generated__/CellSaleStoryQuery.graphql.ts
  src/v2/__generated__/CellSale_sale.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
Labels: Merge On Green

#10061 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#10063 feat: add data-test props for collections page
  src/v2/Apps/Collect/Routes/Collections/Components/CollectionsCategory.tsx
  src/v2/Apps/Collect/Routes/Collections/index.tsx
Labels: Jira Synced

#10064 fix(NX-3130): render tertiary CTA only when artwork is not inquirable.
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarPartnerInfo.jest.tsx
  src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarPartnerInfo_Test_Query.graphql.ts
  src/v2/__generated__/ArtworkSidebarPartnerInfo_artwork.graphql.ts
  src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#10066 [GRO-196] user sees empty state at auction
  src/v2/Apps/Auctions/Components/CuritorialRailsTabBar.tsx
  src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts
  src/v2/__generated__/CuritorialRailsTabBar_viewer.graphql.ts
  src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
Labels: Jira Synced

#10067 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/MakeInquiryOrderMutation.graphql.ts
  src/v2/__generated__/PurchaseOnInquiryButton_conversation.graphql.ts
Labels: Squash On Green

#10071 feat: Temporarily suppress logged out hero GRO-1025
  cypress/integration/home.spec.ts
  src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnits.tsx
Labels: Merge On Green

#10076 chore(press): migrates /press2 => /press; deletes old press app
  src/desktop/apps/press/README.md
  src/desktop/apps/press/index.coffee
  src/desktop/apps/press/routes.coffee
  src/desktop/apps/press/stylesheets/index.styl
  src/desktop/apps/press/templates/in_the_media/index.jade
  src/desktop/apps/press/templates/in_the_media/meta.jade
  src/desktop/apps/press/templates/index.jade
  src/desktop/apps/press/templates/item.jade
  src/desktop/apps/press/templates/press_releases/index.jade
  src/desktop/apps/press/templates/press_releases/meta.jade
  src/desktop/apps/press/test/fixtures/in_the_media.json
  src/desktop/apps/press/test/fixtures/press_releases.json
  src/desktop/apps/press/test/util.test.js
  src/desktop/apps/press/util.coffee
  src/desktop/assets/misc.styl
  src/desktop/index.ts
  src/v2/Apps/Press/PressApp.tsx
  src/v2/Apps/Press/pressRoutes.tsx
Labels: Merge On Green

#10081 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#10080 fix(NX-3130): update button border color to match palette definition
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
Labels: Jira Synced

#10085 fix: update web association, add missing auth endpoints
  package.json
  yarn.lock
Labels: Jira Synced, Squash On Green

#10086 chore(jobs): updates copy
  src/v2/Apps/Jobs/JobApp.tsx
Labels: Merge On Green

#10083 [Documentation]: ExampleApp improvements
  docs/adding_new_app.md
  src/v2/Apps/Example/ExampleApp.tsx
  src/v2/Apps/Example/README.md
  src/v2/Apps/Example/Routes/Welcome/WelcomeRoute.tsx
  src/v2/Apps/Example/__tests__/ExampleApp.jest.tsx
  src/v2/Apps/Example/exampleRoutes.tsx
  src/v2/__generated__/ExampleApp_Test_Query.graphql.ts
Labels: Jira Synced, #FF

#10095 fix: update web association with apple auth callback
  package.json
  yarn.lock
Labels: Squash On Green

#10097 feat(artist): bundle split artist/overview page
  src/v2/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx
Labels: Jira Synced

#10098 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#10100 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/PaymentRouteSetOrderPaymentMutation.graphql.ts
  src/v2/__generated__/commitMutationTest1Mutation.graphql.ts
Labels: Squash On Green

#9278 feat[SWA-210]: Consign Submission Flow uses external id for submissions
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/Mutations/CreateConsignSubmissionMutation.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Mutations/UpdateConsignSubmissionMutation.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createOrUpdateConsignSubmission.ts
  src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/redirects.ts
  src/v2/Apps/Consign/consignRoutes.tsx
  src/v2/__generated__/ArtworkDetails_SubmissionFlowTest_Query.graphql.ts
  src/v2/__generated__/ArtworkDetails_submission.graphql.ts
  src/v2/__generated__/ContactInformation_SubmissionFlowTest_Query.graphql.ts
  src/v2/__generated__/ContactInformation_submission.graphql.ts
  src/v2/__generated__/CreateConsignSubmissionMutation.graphql.ts
  src/v2/__generated__/UpdateConsignSubmissionMutation.graphql.ts
  src/v2/__generated__/UploadPhotos_ImageRefetch_Query.graphql.ts
  src/v2/__generated__/UploadPhotos_SubmissionFlowTest_Query.graphql.ts
  src/v2/__generated__/UploadPhotos_submission.graphql.ts
  src/v2/__generated__/consignRoutes_artworkDetailsQuery.graphql.ts
  src/v2/__generated__/consignRoutes_contactInformationQuery.graphql.ts
  src/v2/__generated__/consignRoutes_uploadPhotosQuery.graphql.ts
  src/v2/__generated__/redirects_submission.graphql.ts
Labels: Jira Synced

#10103 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/useAddCreditCardAndUpdateProfileMutation.graphql.ts
  src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Squash On Green

#10104 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/useDeleteAccountMutation.graphql.ts
Labels: Squash On Green

#10105 feat(FX-3965): add finds under 1000 in artwork links tab
  src/v2/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
  src/v2/Components/NavBar/menuData.ts
Labels: Jira Synced, Squash On Green

#9174 remove(education): Remove link in footer
  src/v2/Components/Footer/Footer.tsx
  src/v2/Components/Footer/__tests__/Footer.jest.tsx
Labels: Merge On Green

#10087 feat(MOPLAT-261): Sentence case on placeholder
  src/v2/Apps/Authentication/Routes/ResetPasswordRoute.tsx
  src/v2/Apps/Authentication/Routes/__tests__/ResetPasswordRoute.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx
  src/v2/Apps/Partners/Components/PartnersLocationAutocomplete.tsx
  src/v2/Apps/Partners/Components/PartnersSpecialtyAutocomplete.tsx
  src/v2/Apps/Partners/Components/__tests__/PartnersLocationAutocomplete.jest.tsx
  src/v2/Apps/Partners/Components/__tests__/PartnersSpecialtyAutocomplete.jest.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/AppSecondFactor/Modal.tsx
  src/v2/Components/Inquiry/Views/InquiryBasicInfo.tsx
  src/v2/Components/__tests__/LocationAutocompleteInput.jest.tsx
Labels: Jira Synced

#10117 chore: Check in graphql diff
  src/v2/__generated__/NewForYouApp_test_Query.graphql.ts
  src/v2/__generated__/NewForYouApp_viewer.graphql.ts
  src/v2/__generated__/NewForYouArtworksGridQuery.graphql.ts
  src/v2/__generated__/NewForYouArtworksGrid_viewer.graphql.ts
  src/v2/__generated__/newForYouRoutes_TopLevelQuery.graphql.ts
Labels: Merge On Green

#10118 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10121 feat(GRO-758): Wires up article analytics
  src/v2/Apps/Article/Components/ArticleAd/ArticleAd.tsx
  src/v2/Apps/Article/Components/ArticleBody.tsx
  src/v2/Apps/Article/Components/ArticleNewsSource.tsx
  src/v2/Apps/Article/Components/ArticleSponsor.tsx
  src/v2/Apps/Article/Components/ArticleVideo.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionVideo.tsx
  src/v2/Apps/Article/Components/__tests__/ArticleBody.jest.tsx
  src/v2/Apps/Article/Components/__tests__/ArticleSeries.jest.tsx
  src/v2/Apps/Article/Components/__tests__/ArticleVideo.jest.tsx
  src/v2/Apps/Article/useArticleTracking.ts
  src/v2/Apps/Articles/Components/__tests__/ArticlesIndexArticles.jest.tsx
  src/v2/Components/ArticleShare.tsx
  src/v2/Components/EntityTooltip/EntityTooltipArtist.tsx
  src/v2/Components/EntityTooltip/EntityTooltipGene.tsx
  src/v2/Components/EntityTooltip/EntityTooltipPartner.tsx
  src/v2/__generated__/ArticleBody_article.graphql.ts
  src/v2/__generated__/ArticleBody_test_Query.graphql.ts
  src/v2/__generated__/ArticleInfiniteScrollQuery.graphql.ts
  src/v2/__generated__/ArticleNewsSource_article.graphql.ts
  src/v2/__generated__/NewsIndexArticlesQuery.graphql.ts
  src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
  src/v2/__generated__/articlesRoutes_NewsQuery.graphql.ts
Labels: Merge On Green

#10125 chore (GRO-1015): Change gene for HomeAuctionLotsRail
  src/v2/Apps/Home/Components/HomeAuctionLotsRail.tsx
  src/v2/Apps/Home/__tests__/HomeAuctionLotsRail.jest.tsx
  src/v2/__generated__/HomeAuctionLotsRailQuery.graphql.ts
  src/v2/__generated__/HomeAuctionLotsRail_Test_Query.graphql.ts
  src/v2/__generated__/HomeAuctionLotsRail_viewer.graphql.ts
Labels: Jira Synced

#10116 chore (GRO-1014): Change gene for StandoutLotsRail
  src/v2/Apps/Auctions/Components/StandoutLotsRail.tsx
  src/v2/Apps/Auctions/Components/__tests__/StandoutLotsRail.jest.tsx
  src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts
  src/v2/__generated__/StandoutLotsRail_Test_Query.graphql.ts
  src/v2/__generated__/StandoutLotsRail_viewer.graphql.ts
  src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
Labels: Jira Synced

#10062 chore(FX-3927): update copy when no artworks available by an artist
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ZeroState.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
  src/v2/Components/ArtworkGrid/ArtworkGrid.tsx
  src/v2/Components/ArtworkGrid/ArtworkGridEmptyState.tsx
Labels: Jira Synced

#10127 Fix schema drift
  data/schema.graphql
  src/v2/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx
  src/v2/__generated__/NewForYouApp_test_Query.graphql.ts
  src/v2/__generated__/NewForYouArtworksGridQuery.graphql.ts
  src/v2/__generated__/NewForYouArtworksGrid_viewer.graphql.ts
  src/v2/__generated__/newForYouRoutes_TopLevelQuery.graphql.ts
Labels: Merge On Green

#10088 test: remove old relay test tools part I
  src/v2/Apps/Order/Routes/Accept/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Accept.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx
  src/v2/DevTools/RootTestPage.tsx
Labels: Jira Synced

#10130 chore(FX-3927): Address post-merge comments
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ZeroState.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
  src/v2/Components/ArtworkGrid/ArtworkGridEmptyState.tsx
Labels: Merge On Green, Jira Synced

#10132 feat: require password for account deletion, if account has password
  src/v2/Apps/Settings/Routes/DeleteAccount/DeleteAccountRoute.tsx
  src/v2/Apps/Settings/settingsRoutes.tsx
  src/v2/__generated__/DeleteAccountRoute_me.graphql.ts
  src/v2/__generated__/settingsRoutes_DeleteAccountRouteQuery.graphql.ts
Labels: Jira Synced

#10136 feat(postie): remove postie 3rd party lib
  src/desktop/components/main_layout/templates/scripts.jade
  src/v2/System/Router/renderServerApp.tsx
  src/v2/index.ejs
Labels: Merge On Green, Jira Synced

#10137 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10140 fix: corrects sizing of badge
  src/v2/Components/Artwork/Badge.tsx
Labels: Merge On Green

#10079 feat(artwork-filter): Add total count to sort
  .secrets.baseline
  src/v2/Components/ArtworkFilter/ArtworkFilters/ArtworkSortFilter.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/fixtures/ArtworkFilter.fixture.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/Components/SortFilter.tsx
  src/v2/__generated__/ArtworkFilter_viewer.graphql.ts
  src/v2/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/v2/__generated__/AuctionAppTestQuery.graphql.ts
  src/v2/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/v2/__generated__/AuctionArtworkFilterTestQuery.graphql.ts
  src/v2/__generated__/SearchResultsArtworks_Query.graphql.ts
  src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
Labels: Jira Synced

#10142 chore: Convert Rail tests to RTL
  src/v2/Apps/Auctions/Components/__tests__/StandoutLotsRail.jest.tsx
  src/v2/Apps/Auctions/Components/__tests__/TrendingLotsRail.jest.tsx
  src/v2/Apps/Auctions/Components/__tests__/WorksByArtistsYouFollowRail.jest.tsx
  src/v2/Components/Artwork/ShelfArtwork.tsx
Labels: Merge On Green

#10145 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10144 feat: add instructions about Google auth during local development
  docs/authentication.md
Labels: Jira Synced

#10147 chore: Convert test to RTL
  src/v2/Apps/Auctions/Components/__tests__/AuctionArtworksRail.jest.tsx
Labels: Merge On Green

#10113 feat(GRO-1028): Onboarding flow implementation
  src/v2/Apps/Onboarding/Components/OnboardingProgress.tsx
  src/v2/Apps/Onboarding/OnboardingApp.tsx
  src/v2/Apps/Onboarding/Views/OnboardingDone.tsx
  src/v2/Apps/Onboarding/Views/OnboardingQuestionOne.tsx
  src/v2/Apps/Onboarding/Views/OnboardingQuestionTwo.tsx
  src/v2/Apps/Onboarding/Views/OnboardingWelcome.tsx
  src/v2/Apps/Onboarding/__tests__/config.jest.ts
  src/v2/Apps/Onboarding/config.ts
  src/v2/Apps/Onboarding/onboardingRoutes.tsx
  src/v2/Apps/Onboarding/useOnboardingContext.tsx
  src/v2/Components/Inquiry/Hooks/useInquiryContext.tsx
  src/v2/Components/Inquiry/config.ts
  src/v2/Utils/WorkflowEngine.tsx
  src/v2/Utils/__tests__/WorkflowEngine.jest.ts
  src/v2/routes.tsx
Labels: Merge On Green, Jira Synced

#10151 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10153 fix(artwork): there may not be any images
  src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
Labels: Merge On Green

#10139 (feat: TX-332): AlicanAkyuz/Wire transfer payment method
  src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/v2/Apps/Order/Routes/Payment/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Payment.jest.tsx
Labels: Jira Synced

#10068 feat(NX-3138): Adjust checkout redirect behavior for Purchase from inquiry
  src/v2/Apps/Conversation/Components/PurchaseOnInquiryButton.tsx
  src/v2/Apps/Order/Routes/Review/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/v2/__generated__/ReviewTestQuery.graphql.ts
  src/v2/__generated__/Review_order.graphql.ts
  src/v2/__generated__/orderRoutes_ReviewQuery.graphql.ts
Labels: Jira Synced

#10150 refactor: add alert to verify email after update
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
Labels: Jira Synced

#10159 bugfix(artwork-lightbox): make lightbox safer
  src/v2/Apps/Artwork/Components/ArtworkLightbox.tsx
  src/v2/Apps/Artwork/Components/__tests__/ArtworkLightbox.jest.tsx
  src/v2/__generated__/ArtworkLightboxTestQuery.graphql.ts
Labels: Merge On Green

#10146 chore(FX-3929): Display `Back to <fair>` banner on fair booth pages regardless of entrypoint
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx
  src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorsGroup.tsx
  src/v2/Apps/Fair/Components/__tests__/FairExhibitorsGroup.jest.tsx
  src/v2/Apps/Fair/Routes/FairExhibitors.tsx
  src/v2/Apps/Show/Components/BackToFairBanner.tsx
  src/v2/Apps/Show/Components/ShowNavigationBanner.tsx
  src/v2/Apps/Show/ShowApp.tsx
  src/v2/Apps/Show/__tests__/BackToFairBanner.jest.tsx
  src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
  src/v2/__generated__/BackToFairBanner_Test_Query.graphql.ts
  src/v2/__generated__/BackToFairBanner_show.graphql.ts
  src/v2/__generated__/FairExhibitorCard_fair.graphql.ts
  src/v2/__generated__/FairExhibitorsGroup_fair.graphql.ts
  src/v2/__generated__/FairExhibitors_Test_Query.graphql.ts
  src/v2/__generated__/FairExhibitors_fair.graphql.ts
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_show.graphql.ts
  src/v2/__generated__/ShowNavigationBanner_show.graphql.ts
  src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
Labels: Jira Synced

#10160 bugfix(works-for-you): Ensure sidebar reports correct artists
  src/v2/Apps/WorksForYou/WorksForYouApp.tsx
  src/v2/Apps/WorksForYou/__tests__/WorksForYouApp.jest.tsx
  src/v2/Apps/WorksForYou/worksForYouRoutes.tsx
  src/v2/__generated__/WorksForYouApp_test_Query.graphql.ts
  src/v2/__generated__/WorksForYouApp_viewerMe.graphql.ts
  src/v2/__generated__/WorksForYouApp_viewerSidebarAggregations.graphql.ts
  src/v2/__generated__/worksForYouRoutes_TopLevelQuery.graphql.ts
Labels: Jira Synced

#10167 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10168 bugfix(artwork-grid): Fix counts display
  src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/v2/Apps/ArtistSeries/Components/ArtistSeriesArtworksFilter.tsx
  src/v2/Apps/Gene/Components/GeneArtworkFilter.tsx
  src/v2/Apps/Partner/Routes/Works/index.tsx
  src/v2/Apps/Show/Components/ShowArtworks.tsx
  src/v2/Apps/Tag/Components/TagArtworkFilter.tsx
  src/v2/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/v2/__generated__/ArtistArtworkFilter_artist.graphql.ts
  src/v2/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/v2/__generated__/ArtistSeriesArtworksFilter_Query.graphql.ts
  src/v2/__generated__/ArtistSeriesArtworksFilter_artistSeries.graphql.ts
  src/v2/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/v2/__generated__/GeneArtworkFilter_Query.graphql.ts
  src/v2/__generated__/GeneArtworkFilter_gene.graphql.ts
  src/v2/__generated__/GeneShow_Test_Query.graphql.ts
  src/v2/__generated__/ShowApp_Test_Query.graphql.ts
  src/v2/__generated__/ShowArtworksQuery.graphql.ts
  src/v2/__generated__/ShowArtworks_Test_Query.graphql.ts
  src/v2/__generated__/ShowArtworks_show.graphql.ts
  src/v2/__generated__/TagApp_Test_Query.graphql.ts
  src/v2/__generated__/TagArtworkFilterQuery.graphql.ts
  src/v2/__generated__/TagArtworkFilter_Query.graphql.ts
  src/v2/__generated__/TagArtworkFilter_tag.graphql.ts
  src/v2/__generated__/WorksQuery.graphql.ts
  src/v2/__generated__/Works_Query.graphql.ts
  src/v2/__generated__/Works_partner.graphql.ts
  src/v2/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
  src/v2/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
  src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts
  src/v2/__generated__/partnerRoutes_WorksQuery.graphql.ts
  src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
  src/v2/__generated__/tagRoutes_TagQuery.graphql.ts
Labels: Jira Synced

#10171 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#10169 Alican akyuz/tx 354/order available payment methods
  src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/v2/Apps/Order/Routes/Payment/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Payment.jest.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/__generated__/PaymentTestQuery.graphql.ts
  src/v2/__generated__/Payment_order.graphql.ts
  src/v2/__generated__/orderRoutes_PaymentQuery.graphql.ts
Labels: Jira Synced

#10176 fix(article): remaining design q/a
  src/v2/Apps/Article/Components/ArticleBody.tsx
  src/v2/Apps/Article/Components/ArticleHero.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollection.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionText.tsx
Labels: Merge On Green

#10179 fix: disable text highlighting within range slider UI
  src/v2/Components/Range.tsx
Labels: Jira Synced, Squash On Green

#10178 chore(footer): replace copy
  src/v2/Apps/Components/__tests__/AppShell.jest.tsx
  src/v2/Components/Footer/FooterDownloadAppBanner.tsx
Labels: Jira Synced

#10181 chore: remove personnel, margin fix
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionInfoPolling.tsx
  src/v2/Apps/AuctionPartnerships/AuctionPartnershipsApp.tsx
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Merge On Green, Jira Synced

#10182 chore: update metaphysics graphql schema
  data/schema.graphql
  src/v2/__generated__/SignUpFormLocationQuery.graphql.ts
  src/v2/__generated__/SignUpFormLocation_tests_Query.graphql.ts
Labels: Squash On Green
