Repository artsy/force, pull requests merged in 2022-11, with the labels that each got.

#11272 chore(FX-4414): display lot label for works in upcoming auctions
  src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
  src/__generated__/ArtworkSidebar2_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar2_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11278 fix: Hide price estimate section when artwork has a submission
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/__tests__/MyCollectionArtwork.jest.tsx
  src/__generated__/MyCollectionArtworkInsights_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Squash On Green

#11279 fix: Always show message when a price estimate has been sent
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkRequestPriceEstimateSection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/__generated__/MyCollectionArtworkInsights_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkRequestPriceEstimateSection_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11281 fix: completely removes fillwidth usage
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
  src/Apps/Fair/Components/FairOverview/FairFollowedArtists.tsx
  src/Apps/Fair/Components/__tests__/FairFollowedArtists.jest.tsx
  src/Apps/Partner/Components/Overview/ArtworksRail.tsx
  src/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistArtworksRail.tsx
  src/Components/Artwork/FillwidthItem.tsx
  src/Utils/fillwidth.ts
  src/Utils/index.ts
  src/__generated__/ArtistConsignRecentlySold_artist.graphql.ts
  src/__generated__/ArtistConsignRoute_Test_Query.graphql.ts
  src/__generated__/FairFollowedArtists_fair.graphql.ts
  src/__generated__/FairOverview_Test_Query.graphql.ts
  src/__generated__/FillwidthItem_artwork.graphql.ts
  src/__generated__/artistRoutes_ArtistConsignQuery.graphql.ts
  src/__generated__/fairRoutes_FairOverviewQuery.graphql.ts
Labels: Merge On Green

#11282 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11271 fix(TX-824): Type guard for credit card picker in new payment
  src/Apps/Order/Routes/NewPayment/index.tsx
Labels: Jira Synced

#11287 fix(navbar): prevents viewing room from breaking at md breakpoint
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavBarItem.tsx
Labels: Merge On Green

#11291 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtworkImageBrowserLarge_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowserSmall_Test_Query.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Squash On Green

#11292 fix(artwork): correctly scales video container
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowserLarge.tsx
  src/Apps/Artwork/Components/ArtworkVideoPlayer/ArtworkVideoPlayer.tsx
  src/__generated__/ArtworkImageBrowserLarge_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowserLarge_artwork.graphql.ts
  src/__generated__/ArtworkImageBrowserSmall_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowser_artwork.graphql.ts
  src/__generated__/ArtworkVideoPlayer_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Merge On Green

#11296 fix(useimageperformanceobserver): rounds to 1x or 2x
  src/Utils/Hooks/__tests__/useImagePerformanceObserver.jest.ts
  src/Utils/Hooks/useImagePerformanceObserver.ts
Labels: Merge On Green

#11297 fix(video): Temporarily remove bg color for now
  src/Apps/Artwork/Components/ArtworkVideoPlayer/ArtworkVideoPlayer.tsx
Labels: Merge On Green

#11299 feat(video): Add analytics
  package.json
  src/Apps/Artwork/Components/ArtworkVideoPlayer/ArtworkVideoPlayer.tsx
  src/Apps/Artwork/Components/ArtworkVideoPlayer/__tests__/ArtworkVideoPlayer.jest.tsx
  src/__generated__/ArtworkImageBrowserLarge_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowserSmall_Test_Query.graphql.ts
  src/__generated__/ArtworkVideoPlayer_Test_Query.graphql.ts
  src/__generated__/ArtworkVideoPlayer_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Merge On Green, Jira Synced

#11300 fix(FX-4425): copy changes on empty activity panel
  src/Components/Notifications/NotificationsEmptyStateByType.tsx
  src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx
Labels: Jira Synced

#11304 perf: make OtherWorksQuery even lazier
  src/Apps/Artwork/Components/OtherWorks/index.tsx
Labels: Jira Synced

#11254 feat(CX-2877): Add Career Highlights Modal
  .secrets.baseline
  src/Apps/Gene/Server/__tests__ /redirectGeneToCollection.jest.ts
  src/Apps/Gene/Server/redirectGeneToCollection.ts
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Components/CareerHighlightModalPromoStep.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Components/CareerHighlightModalStep.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Components/CareerHighlightsModal.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Components/CareerHighlightsSteps.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Components/__tests__/CareerHighlightModalStep.jest.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Hooks/useCareerHighlightsStories.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Hooks/useCareerHighlightsStoriesContext.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Hooks/useCareerHighlightsStoriesModal.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/__tests__/config.jest.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/config.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightCard.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightPromoCard.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightRail.tsx
  src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
  src/Components/Onboarding/Components/OnboardingMarketingCollection.tsx
  src/Components/Onboarding/Components/__tests__/OnboardingMarketingCollection.jest.tsx
  src/Components/Onboarding/Views/OnboardingArtistsOnTheRise.tsx
  src/Components/Onboarding/Views/OnboardingCuratedArtworks.tsx
  src/Components/Onboarding/Views/OnboardingTopAuctionLots.tsx
  src/Server/analytics/__tests__/brazeMessagingIntegration.jest.ts
  src/__generated__/CareerHighlightModalStepTestQuery.graphql.ts
  src/__generated__/CareerHighlightModalStep_careerHighlight.graphql.ts
  src/__generated__/CareerHighlightsStepsQuery.graphql.ts
Labels: Jira Synced

#11313 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11315 chore(storybook): Upgrade to latest enable webpack 5
  .storybook/main.js
  package.json
  src/tests.ts
  yarn.lock
Labels: Merge On Green

#11316 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11317 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11301 chore(TX-836): update deprecated components in order app
  src/Apps/Conversation/Components/OrderModal.tsx
  src/Apps/Order/Components/AddressModal.tsx
  src/Apps/Order/Components/__tests__/AddressModal.jest.tsx
Labels: Jira Synced

#11306 feat(TX-861): improve accessibility tabbing on order app
  src/Apps/Order/Components/SavedAddressItem.tsx
Labels: Jira Synced

#11302 fix(TX-819): Allow new payment if accepting counter offer fails
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/__tests__/OrderApp.jest.tsx
  src/Apps/Order/redirects.tsx
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/Respond_order.graphql.ts
  src/__generated__/orderRoutes_RespondQuery.graphql.ts
Labels: Jira Synced

#11308 feat: update CTA copy and remove Covid message
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Utils/getStatusCopy.tsx
Labels: Jira Synced

#11320 fix: Decrease MyC artwork high demand icon size
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkDemandIndex/HighDemandIcon.tsx
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
  src/Components/Artwork/Details.tsx
Labels: Jira Synced

#11321 fix: edit button accessibility
  src/Apps/Order/Components/SavedAddressItem.tsx
Labels: Jira Synced, Squash On Green

#11322 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11303 fix(GRO-1401): Replace all programmatic scroll with useJump/Jump
  src/Apps/Artist/Routes/Articles/ArtistArticlesRoute.tsx
  src/Apps/Artist/Routes/Articles/__tests__/ArtistArticlesRoute.jest.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/Shows/ArtistShowsRoute.tsx
  src/Apps/Artist/Routes/Shows/Components/ArtistShowsGroup.tsx
  src/Apps/Artists/Routes/ArtistsByLetter.tsx
  src/Apps/Fair/Components/FairBooths.tsx
  src/Apps/FairOrginizer/Routes/FairOrganizerDedicatedArticles.tsx
  src/Apps/FairOrginizer/Routes/__tests__/FairOrganizerDedicatedArticles.jest.tsx
  src/Apps/Partner/Components/PartnerShows/ShowBanner.tsx
  src/Apps/Partner/Components/PartnerShows/ShowEvents.tsx
  src/Apps/Partner/Components/PartnerShows/ShowPaginatedEvents.tsx
  src/Apps/Partner/Components/PartnerViewingRooms/ViewingRoomsPaginated.tsx
  src/Apps/Partner/Routes/Articles/index.tsx
  src/Apps/Partner/Routes/Shows/index.tsx
  src/Apps/Partner/Routes/ViewingRooms/index.tsx
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/Routes/SearchResultsArtists.tsx
  src/Apps/Search/Routes/SearchResultsEntity.tsx
  src/Apps/Search/SearchApp.tsx
  src/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
  src/Components/LoadingArea.tsx
  src/Components/Pagination/index.tsx
  src/Components/Sticky/Sticky.tsx
  src/Utils/Hooks/useJump.tsx
  src/Utils/Hooks/useMatchMedia.ts
  src/Utils/scrollHelpers.ts
  src/__generated__/ArtistArticlesRouteQuery.graphql.ts
  src/__generated__/ArtistArticlesRoute_Test_Query.graphql.ts
  src/__generated__/ArtistArticlesRoute_artist.graphql.ts
  src/__generated__/ArtistShowsGroupQuery.graphql.ts
  src/__generated__/ArtistShowsGroup_artist.graphql.ts
  src/__generated__/ArtistShowsRoute_viewer.graphql.ts
  src/__generated__/ShowEvents_edges.graphql.ts
  src/__generated__/ShowPaginatedEventsQuery.graphql.ts
  src/__generated__/ShowPaginatedEventsRendererQuery.graphql.ts
  src/__generated__/ShowPaginatedEvents_partner.graphql.ts
  src/__generated__/Shows_partner.graphql.ts
  src/__generated__/artistRoutes_ArticlesQuery.graphql.ts
  src/__generated__/artistRoutes_ShowsQuery.graphql.ts
  src/__generated__/partnerRoutes_ShowsQuery.graphql.ts
Labels: Merge On Green

#11326 fix(artist): temporarily removes sticky zero state while investigating infinite loop render bug
  src/Apps/Artist/Routes/WorksForSale/Components/ZeroState.tsx
  src/Components/ArtworkGrid/ArtworkGridEmptyState.tsx
Labels: Merge On Green

#11336 feat(TX-875): Implement new 'us accounts only' design
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/__tests__/Payment.jest.tsx
Labels: Jira Synced

#11335 Feat(CX-3087): reorder swa submission flow
  cypress/e2e/consign.cy.ts
  src/Apps/Consign/Components/SubmissionStepper.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Header.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
  src/Apps/Consign/consignFromMyCollectionRoutes.tsx
  src/Apps/Consign/consignRoutes.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/__generated__/ArtworkDetails_SubmissionFlowTest_Query.graphql.ts
  src/__generated__/ArtworkDetails_submission.graphql.ts
  src/__generated__/UploadPhotos_ImageRefetch_Query.graphql.ts
  src/__generated__/UploadPhotos_SubmissionFlowTest_Query.graphql.ts
  src/__generated__/UploadPhotos_SubmissionMyCollectionFlowTest_Query.graphql.ts
  src/__generated__/UploadPhotos_submission.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_contactInformationMeQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_uploadArtworkPhotosQuery.graphql.ts
  src/__generated__/consignRoutes_artworkDetailsQuery.graphql.ts
  src/__generated__/consignRoutes_contactInformationQuery.graphql.ts
  src/__generated__/consignRoutes_uploadPhotosQuery.graphql.ts
  src/__generated__/redirects_submission.graphql.ts
Labels: Jira Synced

#11342 fix: request price estimate CTA copy
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
Labels: Squash On Green

#11337 feat(CX-3144): Track contact information completed
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
Labels: Jira Synced

#11343 Fix(CX-3146): Add session_id property in UploadPhotos step
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
Labels: Jira Synced

#11348 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11350 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11344 fix: Adjust Demand Icon spacing
  src/Components/Artwork/Details.tsx
Labels: Jira Synced

#11357 fix: disable spaces as full name
  src/Components/Authentication/Validators.tsx
Labels: Jira Synced, Squash On Green

#11359 Fix(CX-3149): Update Career Highlights modal copy
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Components/CareerHighlightModalPromoStep.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Components/CareerHighlightsModal.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightCard.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightPromoCard.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/__tests__/InsightsCareerHighlightRail.jest.tsx
Labels: Jira Synced

#11365 chore: pends shows spec
  cypress/e2e/shows.cy.ts
Labels: Merge On Green

#11366 chore(client): Cleanup client entrypoint
  src/client.tsx
Labels: Merge On Green

#11363 feat: removed the use of `isServer`
  src/Components/NavBar/NavBarLoggedInActions.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotificationsIndicator.tsx
  src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenuNotificationsIndicator.jest.tsx
  src/Components/NavBar/helpers.ts
  src/Components/NavBar/useIndicators.ts
Labels: Jira Synced

#11370 chore(FX-4444): update copy from "Artists I Follow" to "Artists You Follow"
  src/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
  src/Components/ArtworkFilter/Utils/usePrepareFiltersForPills.ts
Labels: Jira Synced, Squash On Green

#11356 fix(GRO-1378): Rename Notable Works Rail
  src/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtistFeaturedWorksRail.tsx
  src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistFeaturedWorksRail.jest.tsx
  src/Apps/Artist/Routes/Overview/__tests__/ArtistOverviewRoute.jest.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/ArtistFeaturedWorksRailQuery.graphql.ts
  src/__generated__/ArtistFeaturedWorksRail_Test_Query.graphql.ts
  src/__generated__/ArtistFeaturedWorksRail_artist.graphql.ts
Labels: Jira Synced

#11376 chore: errors on exhaustive-deps
  .eslintrc.js
Labels: Merge On Green

#11378 Revert "Revert "chore(client): Cleanup client entrypoint""
  src/client.tsx
Labels: Merge On Green

#11353 fix(CX-3151): fix duplication of MyCollection after submission
  src/Apps/Consign/Components/SubmissionStepper.tsx
  src/Apps/Consign/Hooks/useSubmissionFlowSteps.ts
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
Labels: Jira Synced, Squash On Green

#11361 fix(GRO-1372): Update logged out copy
  src/Apps/NewForYou/NewForYouApp.tsx
  src/Apps/NewForYou/__tests__/NewForYouApp.jest.tsx
Labels: Jira Synced

#11380 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11382 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11373 perf(TX-864): place ship to and shipping together on review page
  src/Apps/Order/Components/ShippingArtaSummaryItem.tsx
  src/Apps/Order/Routes/Review/index.tsx
Labels: Jira Synced

#11371 chore(FX-4436): update names for some ways to buy filters
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
  src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
Labels: Jira Synced

#11387 chore(FX-4449): change navigation link copy
  src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
  src/Components/NavBar/menuData.ts
Labels: Jira Synced, Squash On Green

#11396 fix(auction): adds og image
  src/Apps/Auction/Components/AuctionMeta.tsx
  src/__generated__/AuctionAppTestQuery.graphql.ts
  src/__generated__/AuctionMeta_sale.graphql.ts
  src/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/__generated__/useCreateBidderMutation.graphql.ts
Labels: Merge On Green

#11400 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11409 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/SendConversationMessageMutation.graphql.ts
Labels: Squash On Green

#11411 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11389 chore(CX-3066): update My Collection insights tracking events
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/Hooks/__tests__/useAuctionResultsTracking.jest.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/Hooks/useAuctionResultsTracking.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResultItem.jest.tsx
  src/Apps/MyCollection/Routes/Hooks/__tests__/useMyCollectionTracking.jest.tsx
  src/Apps/MyCollection/Routes/Hooks/useMyCollectionTracking.tsx
  src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx
Labels: Jira Synced

#11362 chore: remove upload artwork on small screens
  src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
Labels: Jira Synced, Squash On Green

#11375 refactor: nav bar indicators
  src/Components/NavBar/NavBarLoggedInActions.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuInboxNotificationCount.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotificationsIndicator.tsx
  src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenuInboxNotificationCount.jest.tsx
  src/Components/NavBar/__tests__/NavBar.jest.tsx
  src/Components/NavBar/helpers.ts
  src/__generated__/NavBarMobileMenuInboxNotificationCount_test_Query.graphql.ts
Labels: Jira Synced

#11417 (fix)[GRO-1409] move NFTs from home nav to artwork medium
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
  src/Components/NavBar/menuData.ts
Labels: Jira Synced

#11394 feat(FX-4072): add Keyword filter for other grids
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/Apps/Auction/Components/AuctionArtworkFilter.tsx
  src/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx
  src/Apps/Fair/Routes/FairArtworks.tsx
  src/Apps/Search/Components/SearchResultsArtworksFilters.tsx
  src/Apps/Search/Routes/SearchResultsArtworks.tsx
  src/Components/ArtworkFilter/ArtworkFilters/index.tsx
Labels: Jira Synced

#11424 fix: change copy on the confirmation page
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
Labels: Jira Synced

#11425 fix(CX-3130): Remove "share followed artists..." from Inquiry Flow
  src/Components/Inquiry/Views/InquiryBasicInfo.tsx
  src/Components/Inquiry/__tests__/Views/InquiryBasicInfo.jest.tsx
Labels: Jira Synced

#11413 bugfix(PX-5202): change show cover images to correct dimension to fix blurriness
  src/Apps/Partner/Components/PartnerShows/ShowBanner.tsx
  src/__generated__/ShowBanner_Test_Query.graphql.ts
  src/__generated__/ShowBanner_show.graphql.ts
  src/__generated__/ShowBannersRailRendererQuery.graphql.ts
  src/__generated__/partnerRoutes_ShowsQuery.graphql.ts
Labels: Merge On Green, Jira Synced

#11433 fix: Phone number input in sell form
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/Utils/validation.ts
  src/Apps/MyCollection/Routes/PriceEstimate/__tests__/PriceEstimateContactInformation.jest.tsx
  src/Components/PhoneNumberInputDeprecated/PhoneNumberInput.tsx
  src/Components/PhoneNumberInputDeprecated/__tests__/PhoneNumberInput.jest.tsx
  src/Components/PhoneNumberInputDeprecated/getPhoneNumberInformation.ts
  src/__generated__/getPhoneNumberInformation_Query.graphql.ts
Labels: Squash On Green

#11430 feat: remove cta banner on mweb, add buttons on mweb
  src/Apps/Consign/Routes/MarketingLanding/Components/CtaBanner.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/CtaSection.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/CtaBanner.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/CtaSection.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/index.ts
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
Labels: Jira Synced

#11399 fix(CX-3129): Cleanup Inquiry flow
  src/Components/Inquiry/Views/InquiryArtistsInCollection.tsx
  src/Components/Inquiry/Views/InquiryAuctionHousesYouWorkWith.tsx
  src/Components/Inquiry/Views/InquiryCommercialInterest.tsx
  src/Components/Inquiry/Views/InquiryConfirmation.tsx
  src/Components/Inquiry/Views/InquiryDone.tsx
  src/Components/Inquiry/Views/InquiryFairsYouAttend.tsx
  src/Components/Inquiry/Views/InquiryGalleriesYouWorkWith.tsx
  src/Components/Inquiry/Views/InquiryInstitutionalAffiliations.tsx
  src/Components/Inquiry/__tests__/Views/InquiryCommercialInterest.jest.tsx
  src/Components/Inquiry/__tests__/Views/InquiryInstitutionalAffiliations.jest.tsx
  src/Components/Inquiry/config.ts
  src/__generated__/InquiryArtistsInCollectionQuery.graphql.ts
  src/__generated__/InquiryAuctionHousesYouWorkWithQuery.graphql.ts
  src/__generated__/InquiryFairsYouAttendQuery.graphql.ts
  src/__generated__/InquiryGalleriesYouWorkWithQuery.graphql.ts
Labels: Jira Synced

#11427 feat(CX-3131): Replace Phone number with Other Relative Positions in Inquiry Flow
  src/Components/Inquiry/Views/InquiryBasicInfo.tsx
  src/Components/Inquiry/__tests__/Views/InquiryBasicInfo.jest.tsx
  src/__generated__/InquiryBasicInfoQuery.graphql.ts
  src/__generated__/InquiryBasicInfo_Test_Query.graphql.ts
  src/__generated__/InquiryBasicInfo_me.graphql.ts
Labels: Jira Synced

#11434 feat(CX-3141): update basic information logic in Inquiry flow
  src/Components/Inquiry/Hooks/useInquiryContext.tsx
  src/Components/Inquiry/Views/InquiryLogin.tsx
  src/Components/Inquiry/config.ts
  src/__generated__/useInquiryContextQuery.graphql.ts
  src/__generated__/useInquiryContext_me.graphql.ts
Labels: Jira Synced

#11435 feat(CX-3139): Update confirmation screen in Inquiry Flow
  src/Components/Inquiry/Inquiry.tsx
  src/Components/Inquiry/Views/InquiryConfirmation.tsx
  src/Components/Inquiry/config.ts
Labels: Jira Synced, Squash On Green

#11438 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11437 refactor(auth): removes destination
  src/Apps/Article/ArticleApp.tsx
  src/Apps/Articles/ArticlesApp.tsx
  src/Apps/Articles/NewsApp.tsx
  src/Apps/Authentication/Components/ModalContainer.tsx
  src/Apps/Authentication/Components/__tests__/ModalContainer.jest.tsx
  src/Apps/Authentication/Utils/__tests__/helpers.jest.ts
  src/Apps/Authentication/Utils/__tests__/useAuthForm.jest.ts
  src/Apps/Authentication/Utils/helpers.ts
  src/Apps/Authentication/Utils/useAuthForm.ts
  src/Apps/Authentication/__tests__/authenticationRoutes.jest.tsx
  src/Components/Authentication/Types.ts
  src/Components/Authentication/__tests__/FormSwitcher.jest.tsx
  src/Utils/Hooks/useScrollToOpenArtistAuthModal.ts
Labels: Merge On Green

#11439 fix(auth): correctly triggers onboarding
  src/Apps/Authentication/Utils/__tests__/helpers.jest.ts
  src/Apps/Authentication/Utils/helpers.ts
Labels: Merge On Green

#11423 fix: user can edit address
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/Apps/Order/Utils/shippingUtils.ts
Labels: Jira Synced

#11441 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11445 fix(CX-3162): change email address from sell@artsymail.com to sell@artsy.net
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWAHowItWorksModal.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASectionSubmitted.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSWAHowItWorksModal.jest.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
Labels: Jira Synced

#11444 fix: Update confirmation view design
  src/Components/Inquiry/Views/InquiryConfirmation.tsx
Labels: Jira Synced

#11447 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11449 fix(CX-3139): Update Inquiry flow user experience
  src/Components/Inquiry/Components/InquiryBackdrop.tsx
  src/Components/Inquiry/Inquiry.tsx
Labels: Jira Synced

#11432 refactor(artwork): decouple and defer RelatedWorks query
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/index.tsx
  src/Apps/Artwork/Components/RelatedWorks/index.tsx
  src/Apps/Artwork/Components/__tests__/OtherWorks.jest.tsx
  src/Apps/Artwork/Components/__tests__/RelatedWorks.jest.tsx
  src/__generated__/OtherWorksQuery.graphql.ts
  src/__generated__/OtherWorks_artwork.graphql.ts
  src/__generated__/RelatedWorksQuery.graphql.ts
  src/__generated__/RelatedWorks_Test_Query.graphql.ts
  src/__generated__/RelatedWorks_artwork.graphql.ts
Labels: Jira Synced

#11455 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11451 feat(CX-3172): Add Collector Profile routes
  src/Apps/CollectorProfile/CollectorProfileApp.tsx
  src/Apps/CollectorProfile/Routes/Insights/CollectorProfileInsightsRoute.tsx
  src/Apps/CollectorProfile/Routes/MyCollection/CollectorProfileMyCollectionRoute.tsx
  src/Apps/CollectorProfile/Routes/SavesAndFollows/CollectorProfileSavesAndFollowsRoute.tsx
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/Server/middleware/hardcodedRedirects.ts
  src/__generated__/CollectorProfileApp_me.graphql.ts
  src/__generated__/collectorProfileRoutes_CollectorProfileQuery.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#11457 fix(CX-3192): Update UX on Basic Info view on Inquiry flow
  src/Components/Inquiry/Inquiry.tsx
Labels: Jira Synced

#11463 chore: tune RelatedWorks laziness
  src/Apps/Artwork/Components/RelatedWorks/index.tsx
Labels: Squash On Green
