Repository artsy/force, pull requests merged in 2022-02, with the labels that each got.

#9305 fix: update when the price too low notice shows up
  src/v2/Apps/Order/Components/PriceOptions.tsx
  src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
Labels: Squash On Green

#9300 fix(GRO-725): prevents exposure of token to 3rd parties
  src/v2/Apps/Authentication/Routes/ResetPasswordRoute.tsx
  src/v2/Apps/Authentication/Routes/__tests__/ResetPasswordRoute.jest.tsx
  src/v2/Apps/Authentication/authenticationRoutes.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsPassword.tsx
  src/v2/System/Server/sharifyHelpers.ts
  src/v2/Utils/getENV.tsx
Labels: Merge On Green

#9307 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9298 feat [GRO-737]: redirect how-auctions-work to a support link
  src/desktop/apps/how_auctions_work/bid_increments.coffee
  src/desktop/apps/how_auctions_work/client/index.coffee
  src/desktop/apps/how_auctions_work/index.coffee
  src/desktop/apps/how_auctions_work/routes.coffee
  src/desktop/apps/how_auctions_work/stylesheets/index.styl
  src/desktop/apps/how_auctions_work/stylesheets/mobile_cta.styl
  src/desktop/apps/how_auctions_work/stylesheets/multi_page.styl
  src/desktop/apps/how_auctions_work/stylesheets/sections.styl
  src/desktop/apps/how_auctions_work/templates/index.jade
  src/desktop/apps/how_auctions_work/templates/meta.jade
  src/desktop/apps/how_auctions_work/templates/mobile_cta.jade
  src/desktop/apps/how_auctions_work/templates/section.jade
  src/desktop/apps/how_auctions_work/test/fixture.json
  src/desktop/apps/how_auctions_work/test/template.test.js
  src/desktop/assets/auctions.styl
  src/desktop/assets/auctions.ts
  src/desktop/index.ts
  src/lib/middleware/hardcodedRedirects.ts
  src/mobile/apps/how_auctions_work/bid_increments.coffee
  src/mobile/apps/how_auctions_work/client/index.coffee
  src/mobile/apps/how_auctions_work/fixtures/data.json
  src/mobile/apps/how_auctions_work/index.coffee
  src/mobile/apps/how_auctions_work/routes.coffee
  src/mobile/apps/how_auctions_work/stylesheets/index.styl
  src/mobile/apps/how_auctions_work/templates/index.jade
  src/mobile/apps/how_auctions_work/templates/learn_more.jade
  src/mobile/apps/how_auctions_work/test/template.test.js
  src/mobile/assets/mobile_all.styl
  src/mobile/assets/mobile_all.ts
  src/mobile/index.ts
  src/v2/Apps/_HowAuctionsWork2/HowAuctionsWorkApp.tsx
  src/v2/Apps/_HowAuctionsWork2/howAuctionsWorkRoutes.tsx
  src/v2/routes.tsx
Labels: Jira Synced

#9314 chore(FX-3665): replace deprecated artistID with artistIDs[]
  src/v2/Components/ArtworkFilter/SavedSearch/Utils/__tests__/savedSearchCriteria.jest.ts
  src/v2/Components/ArtworkFilter/SavedSearch/Utils/savedSearchCriteria.tsx
Labels: Jira Synced

#9316 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9318 fix: Corrected logic which led to one event firing multiple times
  src/v2/Apps/Order/Components/PriceOptions.tsx
  src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
Labels: Squash On Green

#9323 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9328 Update metaphysics schema
  src/v2/__generated__/ConversationPageQuery.graphql.ts
  src/v2/__generated__/ConversationPaginationQuery.graphql.ts
  src/v2/__generated__/ConversationPagination_Test_Query.graphql.ts
  src/v2/__generated__/Conversation_conversation.graphql.ts
  src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
Labels: Squash On Green

#9257 feat(FX-3696): Edit saved search alerts flow
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertDeleteModal.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormContainter.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormPlaceholder.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertsEmptyResults.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsList.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsOverviewRoute.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/types.ts
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/useDeleteSavedSearchAlert.ts
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/useEditSavedSearchAlert.ts
  src/v2/Apps/Settings/settingsRoutes.tsx
  src/v2/Components/SavedSearchAlert/Utils/extractPills.ts
  src/v2/__generated__/SavedSearchAlertEditFormQuery.graphql.ts
  src/v2/__generated__/SavedSearchAlertEditForm_Test_Query.graphql.ts
  src/v2/__generated__/SavedSearchAlertEditForm_artist.graphql.ts
  src/v2/__generated__/SavedSearchAlertEditForm_artworksConnection.graphql.ts
  src/v2/__generated__/SavedSearchAlertEditForm_savedSearch.graphql.ts
  src/v2/__generated__/SavedSearchAlertListItem_item.graphql.ts
  src/v2/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
  src/v2/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
  src/v2/__generated__/SavedSearchAlertsApp_me.graphql.ts
  src/v2/__generated__/SavedSearchAlertsOverviewRoute_me.graphql.ts
  src/v2/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts
  src/v2/__generated__/useDeleteSavedSearchAlertMutation.graphql.ts
  src/v2/__generated__/useEditSavedSearchAlertMutation.graphql.ts
Labels: Jira Synced, Squash On Green

#9333 feat(article): implements remaining hero types
  src/v2/Apps/Article/ArticleApp.tsx
  src/v2/Apps/Article/Components/ArticleHeader.tsx
  src/v2/__generated__/ArticleBody_test_Query.graphql.ts
  src/v2/__generated__/ArticleHeader_article.graphql.ts
  src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
Labels: Merge On Green

#9334 [GRO-788] remove links to specialist phone numbers
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Merge On Green

#9336 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9344 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9343 chore: remove new offer submission flag
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
Labels: Jira Synced

#9294 feat(FX-3686): Display alerts for saved search
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
Labels: Jira Synced

#9346 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9347 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9354 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9355 feat: Use article byline on homepage GRO-721
  src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx
  src/v2/__generated__/HomeFeaturedMarketNewsQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedMarketNews_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedMarketNews_articles.graphql.ts
Labels: Merge On Green

#9292 Add a “See details.” text link that opens up the conversation sidebar
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/ConversationMessages.tsx
  src/v2/Apps/Conversation/Components/OrderUpdate.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConversationMessages.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/OrderUpdate.jest.tsx
Labels: Squash On Green

#9359 feat(FX-3727): Open artist's artworks screen with applied filters when "View All" button is clicked
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/v2/__generated__/SavedSearchAlertListItem_item.graphql.ts
  src/v2/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
  src/v2/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
  src/v2/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#9361 chore(FX-3728): Update Apple and Google Play Store Badges in create alert modal
  src/v2/Components/SavedSearchAlert/DownloadAppBanner.tsx
Labels: Jira Synced

#9350 Deploy
  data/schema.graphql
  package.json
  src/v2/Apps/Article/Components/ArticleZoomButton.tsx
  src/v2/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGallery.tsx
  src/v2/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryFigure.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionImageCollection.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionImageSet.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/FAQ.tsx
  src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/FAQ.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/Components/DownloadApps.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
  src/v2/Apps/Conversation/Components/Conversation.tsx
  src/v2/Apps/Conversation/Components/ConversationMessages.tsx
  src/v2/Apps/Conversation/Components/OrderUpdate.tsx
  src/v2/Apps/Conversation/Components/__tests__/ConversationMessages.jest.tsx
  src/v2/Apps/Conversation/Components/__tests__/OrderUpdate.jest.tsx
  src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx
  src/v2/Apps/Order/Components/__tests__/AddressModal.jest.tsx
  src/v2/Apps/Order/Routes/Shipping/index.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/Components/DownloadAppBadges/DownloadAppBadges.tsx
  src/v2/System/Analytics/Schema/Values.ts
  src/v2/__generated__/ArticleZoomGalleryFigure_figure.graphql.ts
  src/v2/__generated__/ArticleZoomGalleryQuery.graphql.ts
  src/v2/__generated__/ArticleZoomGallery_article.graphql.ts
  src/v2/__generated__/HomeFeaturedMarketNewsQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedMarketNews_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedMarketNews_articles.graphql.ts
  src/v2/__generated__/SavedSearchAlertListItem_item.graphql.ts
  src/v2/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
  src/v2/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
  src/v2/__generated__/ShippingTestQuery.graphql.ts
  src/v2/__generated__/Shipping_order.graphql.ts
  src/v2/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/v2/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#9365 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArticleBody_article.graphql.ts
  src/v2/__generated__/ArticleBody_test_Query.graphql.ts
Labels: Squash On Green

#9363 feat(article): implements video embeds
  src/v2/Apps/Article/Components/ArticleBody.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionVideo.tsx
  src/v2/Apps/Article/Components/__tests__/ArticleBody.jest.tsx
  src/v2/__generated__/ArticleBody_article.graphql.ts
  src/v2/__generated__/ArticleBody_test_Query.graphql.ts
  src/v2/__generated__/ArticleSectionVideo_section.graphql.ts
  src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
Labels: Merge On Green

#9366 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9367 feat(article): implements social embeds
  src/v2/Apps/Article/Components/ArticleBody.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionSocialEmbed.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionVideo.tsx
  src/v2/Apps/Article/Components/__tests__/ArticleBody.jest.tsx
  src/v2/__generated__/ArticleBody_article.graphql.ts
  src/v2/__generated__/ArticleBody_test_Query.graphql.ts
  src/v2/__generated__/ArticleSectionSocialEmbed_section.graphql.ts
  src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
Labels: Merge On Green

#9369 chore(FX-3730): update alerts copy
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
  src/v2/Components/ArtworkFilter/SavedSearch/Components/__tests__/CreateAlertButton.jest.tsx
  src/v2/Components/ArtworkFilter/__tests__/ArtworkGridFilterPills.jest.tsx
  src/v2/Components/SavedSearchAlert/DownloadAppBanner.tsx
  src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
Labels: Jira Synced, Squash On Green

#9364 feat(offer): use submitOfferOrderWithConversation mutation
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Order/Routes/Review/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/v2/__generated__/ReviewSubmitOfferOrderWithConversationMutation.graphql.ts
Labels: Jira Synced

#9372 refactor(hook): Update useMutation hook
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/v2/Apps/Settings/Routes/DeleteAccount/DeleteAccountRoute.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsEmailPreferences/SettingsEditSettingsEmailPreferences.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsLinkedAccounts.tsx
  src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethod.tsx
  src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethodForm.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertDeleteModal.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddress.tsx
  src/v2/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddressForm.tsx
  src/v2/Apps/Unsubscribe/Components/UnsubscribeLoggedIn.tsx
  src/v2/Utils/Hooks/useMutation.ts
Labels: Merge On Green

#9375 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9374 feat(article): implements generic embeds
  src/v2/Apps/Article/Components/ArticleBody.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionEmbed.tsx
  src/v2/Apps/Article/Components/__tests__/ArticleBody.jest.tsx
  src/v2/__generated__/ArticleBody_article.graphql.ts
  src/v2/__generated__/ArticleBody_test_Query.graphql.ts
  src/v2/__generated__/ArticleSectionEmbed_section.graphql.ts
  src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
Labels: Merge On Green

#9379 fix(articles): uses thumbnail title
  src/v2/Apps/Articles/Components/ArticlesIndexArticle.tsx
  src/v2/Apps/Articles/Components/__tests__/ArticlesIndexArticles.jest.tsx
  src/v2/__generated__/ArticlesIndexArticle_article.graphql.ts
  src/v2/__generated__/ArticlesIndexArticlesQuery.graphql.ts
  src/v2/__generated__/ArticlesIndexArticles_test_Query.graphql.ts
  src/v2/__generated__/articlesRoutes_ArticlesQuery.graphql.ts
Labels: Merge On Green

#9345 feat(FX-3723): add pagination for edit alerts screen
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/v2/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
  src/v2/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
  src/v2/__generated__/SavedSearchAlertsApp_me.graphql.ts
  src/v2/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#9382 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
  src/v2/__generated__/SavedSearchAlertsApp_me.graphql.ts
  src/v2/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts
Labels: Squash On Green

#9384 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9272 [NX-3057] Remove unneeded conditionals to hide Contact Gallery button
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx
Labels: Jira Synced

#9396 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9401 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9397 Deploy
  .secrets.baseline
  data/schema.graphql
  package.json
  src/config.ts
  src/lib/passport/lib/passport/callbacks.js
  src/lib/passport/test/app/analytics.test.js
  src/lib/passport/test/app/lifecycle.test.js
  src/lib/passport/test/app/locals.test.js
  src/lib/passport/test/app/logout.js
  src/lib/passport/test/app/logout.test.js
  src/lib/passport/test/app/sanitize_redirect.test.js
  src/lib/passport/test/app/token_login.test.js
  src/lib/passport/test/passport/callbacks.test.js
  src/lib/passport/test/passport/serializers.test.js
  src/lib/setup_sharify.js
  src/typings/sharify.d.ts
  src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsLinkedAccounts.tsx
  src/v2/Apps/Settings/Routes/EditSettings/Components/__tests__/SettingsEditSettingsLinkedAccounts.jest.tsx
  src/v2/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
  src/v2/System/Server/sharifyHelpers.ts
  yarn.lock
Labels: Jira Synced

#9400 feat(GRO-807): implements article video layout
  src/v2/Apps/Article/ArticleApp.tsx
  src/v2/Apps/Article/Components/ArticleBody.tsx
  src/v2/Apps/Article/Components/ArticleSeries.tsx
  src/v2/Apps/Article/Components/ArticleSponsor.tsx
  src/v2/Apps/Article/Components/ArticleVideo.tsx
  src/v2/Apps/Article/Components/__tests__/ArticleVideo.jest.tsx
  src/v2/Apps/Articles/Components/ArticlesIndexArticle.tsx
  src/v2/Components/ArticleShare.tsx
  src/v2/__generated__/ArticleApp_article.graphql.ts
  src/v2/__generated__/ArticleSeries_article.graphql.ts
  src/v2/__generated__/ArticleSeries_test_Query.graphql.ts
  src/v2/__generated__/ArticleSponsor_sponsor.graphql.ts
  src/v2/__generated__/ArticleVideo_article.graphql.ts
  src/v2/__generated__/ArticleVideo_test_Query.graphql.ts
  src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
Labels: Merge On Green

#9410 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9406 feat(FX-3738): Full screen modal for edit alert panel
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormDesktop.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormMobile.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/types.ts
Labels: Jira Synced

#9411 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9414 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9393 feat: implement unleash into Force
  package.json
  src/config.ts
  src/lib/__tests__/featureFlagProvider.jest.ts
  src/lib/featureFlags/FeatureFlagProvider.tsx
  src/lib/featureFlags/featureFlagService.ts
  src/lib/featureFlags/unleashService.ts
  src/lib/middleware/featureFlagMiddleware.ts
  src/middleware.ts
  src/typings/sharify.d.ts
  src/v2/Apps/Home/HomeApp.tsx
  src/v2/DevTools/MockBoot.tsx
  src/v2/System/Router/Boot.tsx
  src/v2/System/Router/buildClientApp.tsx
  src/v2/System/Router/buildServerApp.tsx
  src/v2/System/Router/index.ts
  src/v2/System/Server/sharifyHelpers.ts
  src/v2/client.tsx
  src/v2/server.ts
  yarn.lock
Labels: Jira Synced

#9416 feat(router): Add useCurrentRoute
  src/v2/Apps/Artist/ArtistApp.tsx
  src/v2/Apps/Artist/__tests__/ArtistApp.jest.tsx
  src/v2/Apps/Components/AppShell.tsx
  src/v2/Apps/Order/OrderApp.tsx
  src/v2/System/Router/Utils/__tests__/findCurrentRoute.jest.ts
  src/v2/System/Router/Utils/findCurrentRoute.tsx
  src/v2/System/Router/useCurrentRoute.ts
  src/v2/Typings/global.d.ts
Labels: Merge On Green

#9331 [SWA-185]: Display "Processing" label on an image preview if still processing
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/PhotoThumbnail.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/PhotoThumbnail.jest.tsx
  src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
  src/v2/__generated__/UploadPhotos_ImageRefetch_Query.graphql.ts
Labels: Jira Synced

#9423 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9424 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9427 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9429 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArticleBody_test_Query.graphql.ts
  src/v2/__generated__/ArticleByline_article.graphql.ts
Labels: Squash On Green

#9431 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/CreateCreditCardAndUpdatePhoneMutation.graphql.ts
  src/v2/__generated__/useUnsubscribeEmailPreferencesMutation.graphql.ts
  src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
  src/v2/__generated__/useUpdateSettingsEmailPreferencesMutation.graphql.ts
  src/v2/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Squash On Green

#9435 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9433 chore(example-app): Simplify how we demo ArtworkFilter
  src/v2/Apps/Example/ExampleApp.tsx
  src/v2/Apps/Example/Routes/ArtworkFilter/Components/ExampleArtworkFilter.tsx
  src/v2/Apps/Example/Routes/ArtworkFilter/ExampleArtworkFilterRoute.tsx
  src/v2/Apps/Example/exampleRoutes.tsx
  src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/v2/Components/ArtworkFilter/index.tsx
  src/v2/__generated__/ExampleArtworkFilterRoute_tag.graphql.ts
  src/v2/__generated__/ExampleArtworkFilterRoute_viewer.graphql.ts
  src/v2/__generated__/ExampleArtworkFilter_tag.graphql.ts
  src/v2/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/v2/__generated__/exampleRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/exampleRoutes_TagQuery.graphql.ts
Labels: Merge On Green

#9442 Revert "chore: DRY up passport callbacks"
  src/lib/passport/lib/passport/callbacks.js
Labels: Merge On Green

#9446 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9452 chore: Remove artsy-passport example code
  src/lib/passport/README.md
  src/lib/passport/example/client.js
  src/lib/passport/example/error.jade
  src/lib/passport/example/index.js
  src/lib/passport/example/loggedin.jade
  src/lib/passport/example/login.jade
  src/lib/passport/example/newpassword.jade
  src/lib/passport/example/nocsrf.jade
  src/lib/passport/example/personalize.jade
  src/lib/passport/example/public/client.js
Labels: Merge On Green

#9450 fix: palette breaking visual changes
  package.json
  src/v2/Apps/Components/AppShell.tsx
  src/v2/Apps/Components/AppToasts.tsx
  src/v2/Apps/Components/constants.ts
  src/v2/Components/NavBar/Menus/NavBarMenuItem.tsx
  src/v2/Components/NavBar/NavBar.tsx
  src/v2/Components/NavBar/NavBarLoggedInActions.tsx
  src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
  yarn.lock
Labels: Merge On Green

#9451 [GRO-734](feat): small design fixes for /about2
  src/v2/Apps/_About2/AboutApp.tsx
Labels: Merge On Green

#9463 fix(artists): prevents 500s when missing data
  src/v2/Apps/Artists/Components/ArtistsCarouselCell.tsx
  src/v2/Apps/Artists/Routes/ArtistsIndex.tsx
Labels: Merge On Green

#9459 feat(article): implements entity tooltips
  package.json
  src/v2/Apps/Article/Components/ArticleHTML.tsx
  src/v2/Apps/Article/Components/ArticleTooltip.tsx
  src/v2/Components/EntityTooltip/EntityTooltip.tsx
  src/v2/Components/EntityTooltip/EntityTooltipArtist.tsx
  src/v2/Components/EntityTooltip/EntityTooltipGene.tsx
  src/v2/Components/EntityTooltip/EntityTooltipPartner.tsx
  src/v2/Components/EntityTooltip/index.ts
  src/v2/__generated__/EntityTooltipArtistQuery.graphql.ts
  src/v2/__generated__/EntityTooltipArtist_artist.graphql.ts
  src/v2/__generated__/EntityTooltipGeneQuery.graphql.ts
  src/v2/__generated__/EntityTooltipGene_gene.graphql.ts
  src/v2/__generated__/EntityTooltipPartnerQuery.graphql.ts
  src/v2/__generated__/EntityTooltipPartner_partner.graphql.ts
Labels: Merge On Green

#9460 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/ArtistsCarouselCell_featuredLink.graphql.ts
  src/v2/__generated__/ArtistsIndexFragmentContainer_Test_Query.graphql.ts
  src/v2/__generated__/ArtistsIndex_featuredArtists.graphql.ts
  src/v2/__generated__/FairsIndex_Test_Query.graphql.ts
  src/v2/__generated__/FairsIndex_featuredFairs.graphql.ts
  src/v2/__generated__/HomeApp_Test_Query.graphql.ts
  src/v2/__generated__/HomeFeaturedEventsRail_orderedSet.graphql.ts
  src/v2/__generated__/UpdateConsignSubmissionMutation.graphql.ts
  src/v2/__generated__/addAssetToConsignmentMutation.graphql.ts
Labels: Squash On Green

#9472 feat(GRO-750): Article images Q/A
  src/v2/Apps/Article/Components/ArticleHTML.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionImageCollection.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollection.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionCaption.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionImage.tsx
  src/v2/Apps/Article/Components/Sections/ArticleSectionImageCollection/index.ts
  src/v2/__generated__/ArticleBody_test_Query.graphql.ts
  src/v2/__generated__/ArticleSectionImageCollectionCaption_figure.graphql.ts
  src/v2/__generated__/ArticleSectionImageCollectionImage_figure.graphql.ts
  src/v2/__generated__/ArticleSectionImageCollection_section.graphql.ts
  src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
Labels: Merge On Green

#9474 Updated: Changed the phone number on artsy.net/auction sale pages
  src/desktop/apps/auction/components/layout/auction_info/Registration.tsx
  src/v2/Apps/Auction2/Components/AuctionDetails/AuctionInfoSidebar.tsx
Labels: Jira Synced

#9468 GRO-787 & GRO-789: User sees general support CTAs on /meet-the-specialists and updated copy/design on page
  src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Jira Synced

#9476 feat(auction2): Add promoted sale rail
  src/v2/Apps/Auction2/Auction2App.tsx
  src/v2/Apps/Auction2/Components/AuctionActiveBids.tsx
  src/v2/Apps/Auction2/Components/AuctionPromotedSaleRail.tsx
  src/v2/Apps/Auction2/Components/AuctionWorksForYouRail.tsx
  src/v2/Components/Artwork/ShelfArtwork.tsx
  src/v2/__generated__/Auction2App_sale.graphql.ts
  src/v2/__generated__/AuctionPromotedSaleRail_sale.graphql.ts
  src/v2/__generated__/auction2Routes_TopLevelQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
Labels: Merge On Green

#9478 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9480 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9481 fix(article): adds support for video split heroes
  src/v2/Apps/Article/Components/ArticleHeader.tsx
  src/v2/__generated__/ArticleBody_test_Query.graphql.ts
  src/v2/__generated__/ArticleHeader_article.graphql.ts
  src/v2/__generated__/NewsIndexArticlesQuery.graphql.ts
  src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
  src/v2/__generated__/articlesRoutes_NewsQuery.graphql.ts
Labels: Merge On Green

#9482 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9484 qa(auction2): Minor auction2 QA
  src/v2/Apps/Auction2/Auction2App.tsx
  src/v2/Apps/Auction2/Components/AuctionDetails/AuctionDetails.tsx
  src/v2/Apps/Auction2/Components/AuctionDetails/RegisterButton.tsx
  src/v2/Apps/Auction2/Components/Form/IdentityVerificationWarning.tsx
  src/v2/__generated__/Auction2App_me.graphql.ts
  src/v2/__generated__/AuctionDetails_sale.graphql.ts
  src/v2/__generated__/RegisterButton_Test_Query.graphql.ts
  src/v2/__generated__/RegisterButton_sale.graphql.ts
  src/v2/__generated__/auction2Routes_TopLevelQuery.graphql.ts
  src/v2/__generated__/useCreateBidderMutation.graphql.ts
Labels: Merge On Green

#9485 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9489 Update metaphysics schema
  data/schema.graphql
  src/v2/__generated__/FeatureAKGRoute_Test_Query.graphql.ts
  src/v2/__generated__/Feature_viewer.graphql.ts
  src/v2/__generated__/HomeFeaturedMarketNewsQuery.graphql.ts
  src/v2/__generated__/HomeFeaturedMarketNews_Test_Query.graphql.ts
Labels: Squash On Green

#9493 feat: remove high speed bump modal from offer
  src/v2/Apps/Order/Routes/Offer/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/v2/Apps/Order/Routes/__tests__/Offer2.jest.tsx
Labels: Jira Synced, Squash On Green

#9492 feat(FX-3769): Set max width for "Your Alerts" screen
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
Labels: Jira Synced

#9407 feat(NX-3041): Implement new congrats for make offer on eligible artworks
  src/v2/Apps/Artwork/ArtworkApp.tsx
  src/v2/Apps/Artwork/Components/SubmittedOrderModal/SubmittedOrderModal.tsx
  src/v2/Apps/Artwork/Components/SubmittedOrderModal/__tests__/SubmittedOrderModal.jest.tsx
  src/v2/Apps/Artwork/Components/SubmittedOrderModal/index.tsx
  src/v2/Apps/Order/Routes/Review/index.tsx
  src/v2/Apps/Order/Routes/Status/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Status.jest.tsx
  src/v2/Apps/Order/Utils/getStatusCopy.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/__generated__/ArtworkApp_me.graphql.ts
  src/v2/__generated__/StatusQuery.graphql.ts
  src/v2/__generated__/Status_order.graphql.ts
  src/v2/__generated__/SubmittedOrderModal_Test_Query.graphql.ts
  src/v2/__generated__/SubmittedOrderModal_me.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/orderRoutes_StatusQuery.graphql.ts
Labels: Jira Synced

#9487 feat(NX-3082): change CTA copies
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial2.jest.tsx
  src/v2/Apps/Conversation/Components/OpenInquiryModalCTA.tsx
  src/v2/Apps/Conversation/Components/__tests__/OpenInquiryModalCTA.jest.tsx
  src/v2/Components/Artwork/Details.tsx
  src/v2/Components/Artwork/__tests__/Details.jest.tsx
Labels: Jira Synced

#9491 feat(FX-3768): Add additional event tracking
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
Labels: Jira Synced, Squash On Green

#9500 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green

#9494 Deploy
  .circleci/config.yml
  data/schema.graphql
  src/desktop/lib/openAuthModal.ts
  src/v2/Apps/Article/ArticleApp.tsx
  src/v2/Apps/Article/Components/ArticleInfiniteScroll.tsx
  src/v2/Apps/Article/Components/ArticleVisibilityMetadata.tsx
  src/v2/Apps/Artwork/ArtworkApp.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx
  src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial2.jest.tsx
  src/v2/Apps/Artwork/Components/SubmittedOrderModal/SubmittedOrderModal.tsx
  src/v2/Apps/Artwork/Components/SubmittedOrderModal/__tests__/SubmittedOrderModal.jest.tsx
  src/v2/Apps/Artwork/Components/SubmittedOrderModal/index.tsx
  src/v2/Apps/Auction2/Components/AuctionArtworkFilter.tsx
  src/v2/Apps/Auction2/Components/AuctionDetails/AuctionDetails.tsx
  src/v2/Apps/Auction2/Components/Form/ErrorStatus.tsx
  src/v2/Apps/Auction2/Components/RegisterButton.tsx
  src/v2/Apps/Auction2/Components/__tests__/RegisterButton.jest.tsx
  src/v2/Apps/Auction2/Hooks/useAuctionTracking.ts
  src/v2/Apps/Auction2/Routes/Auction2RegistrationRoute.tsx
  src/v2/Apps/Auction2/Routes/Bid/Auction2BidRoute.tsx
  src/v2/Apps/Auction2/Routes/Bid/useSubmitBid.ts
  src/v2/Apps/Auction2/auction2Routes.tsx
  src/v2/Apps/Conversation/Components/OpenInquiryModalCTA.tsx
  src/v2/Apps/Conversation/Components/__tests__/OpenInquiryModalCTA.jest.tsx
  src/v2/Apps/Order/Routes/Review/index.tsx
  src/v2/Apps/Order/Routes/Status/index.tsx
  src/v2/Apps/Order/Routes/__tests__/Status.jest.tsx
  src/v2/Apps/Order/Utils/getStatusCopy.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/v2/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
  src/v2/Apps/_Preferences2/PreferencesApp.tsx
  src/v2/Apps/_Preferences2/__tests__/PreferencesApp.jest.tsx
  src/v2/Apps/_Preferences2/preferencesRoutes.tsx
  src/v2/Apps/_Preferences2/useEditNotificationPreferences.tsx
  src/v2/Apps/__tests__/Fixtures/Order.ts
  src/v2/Components/Artwork/Details.tsx
  src/v2/Components/Artwork/__tests__/Details.jest.tsx
  src/v2/Utils/Hooks/useIntersectionObserver.ts
  src/v2/__generated__/ArticleApp_article.graphql.ts
  src/v2/__generated__/ArticleInfiniteScrollQuery.graphql.ts
  src/v2/__generated__/ArticleInfiniteScroll_viewer.graphql.ts
  src/v2/__generated__/ArticleVisibilityMetadata_article.graphql.ts
  src/v2/__generated__/ArtworkApp_me.graphql.ts
  src/v2/__generated__/PreferencesApp_viewer.graphql.ts
  src/v2/__generated__/StatusQuery.graphql.ts
  src/v2/__generated__/Status_order.graphql.ts
  src/v2/__generated__/SubmittedOrderModal_Test_Query.graphql.ts
  src/v2/__generated__/SubmittedOrderModal_me.graphql.ts
  src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
  src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/v2/__generated__/orderRoutes_StatusQuery.graphql.ts
  src/v2/__generated__/preferencesRoutes_PreferencesQuery.graphql.ts
  src/v2/__generated__/useEditNotificationPreferencesMutation.graphql.ts
Labels: Jira Synced

#9498 mc-jones/fix unleash implementation
  package.json
  src/config.ts
  src/lib/__tests__/featureFlagProvider.jest.ts
  src/lib/featureFlags/FeatureFlagProvider.tsx
  src/lib/featureFlags/featureFlagService.ts
  src/lib/featureFlags/unleashService.ts
  src/lib/middleware/featureFlagMiddleware.ts
  src/middleware.ts
  src/typings/sharify.d.ts
  src/v2/Apps/ViewingRoom/ViewingRoomsApp.tsx
  src/v2/DevTools/MockBoot.tsx
  src/v2/System/Router/Boot.tsx
  src/v2/System/Router/buildClientApp.tsx
  src/v2/System/Router/buildServerApp.tsx
  src/v2/System/Router/index.ts
  src/v2/System/Server/sharifyHelpers.ts
  src/v2/client.tsx
  src/v2/server.ts
  yarn.lock
Labels: Jira Synced

#9510 Update metaphysics schema
  data/schema.graphql
Labels: Squash On Green
