Repository artsy/force, pull requests merged in 2023-03, with the labels that each got.

#12010 chore(collector profile): change follow profiles copy
  src/Apps/Settings/Routes/Saves/Components/SettingsSavesProfiles.tsx
  src/Apps/Settings/Routes/Saves/Components/__tests__/SettingsSavesProfiles.jest.tsx
Labels: Jira Synced

#12012 fix(CX-3360): change specialty for one specialist
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
Labels: Jira Synced, Squash On Green

#12014 feat(error): improves messages for client-side errors
  src/Components/ErrorPage.tsx
  src/System/Router/ErrorBoundary.tsx
Labels: Merge On Green

#12015 feat(progressive-onboarding): adds tracking; updates dismissal logic
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFindFollows.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSaves.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowsHighlight.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingHighlight.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingPopover.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSavesHighlight.tsx
  src/Components/ProgressiveOnboarding/useProgressiveOnboardingTracking.tsx
Labels: Jira Synced

#12016 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12009 feat(TX-1073): Select list price as default offer option
  src/Apps/Order/Components/PriceOptions.tsx
  src/Apps/Order/Routes/__tests__/Offer.jest.tsx
Labels: Jira Synced

#12027 chore(deps): upgrades palette
  package.json
  yarn.lock
Labels: Merge On Green

#12030 chore(deps): bumps palette
  package.json
  yarn.lock
Labels: Merge On Green

#12020 feat(artwork lists): add the edit action
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/DeleteSavesModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/EditSavesModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/Mutations/useUpdateCollection.ts
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/SavesContextualMenu.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/DeleteSavesModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/EditSavesModal.jest.tsx
  src/Components/ContextualMenu/ContextualMenu.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/useUpdateCollectionMutation.graphql.ts
Labels: Jira Synced, Squash On Green

#12031 Fix(CX-3360): design and tracking adjustments
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FooterBanner.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpeakToTheTeam.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Footer.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HeaderSWA.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HowItWorksSteps.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/MeetTheSpecialists.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SpeakToTheTeam.jest.tsx
  yarn.lock
Labels: Jira Synced

#12042 chore: remove unneeded integrity test
  cypress/e2e/myCollection.cy.ts
Labels: Jira Synced, Squash On Green

#12037 feat: add analytics on search artist quickaction btns
  src/Components/Search/Suggestions/SuggestionItem.tsx
Labels: Jira Synced

#12036 feat(CX-3467): Add edition number to MyC artwork details
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MyCollectionArtworkSidebar.jest.tsx
  src/__generated__/MyCollectionArtworkSidebarMetadata_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkSidebarTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#12038 feat(devx): add package script to pretty-print i18n translations
  docs/i18n.md
  package.json
  scripts/list-translations.js
Labels: Squash On Green

#12044 fix(GRO-1588): re-check auth on tab focus
  src/Utils/Hooks/useAuthValidation.ts
Labels: Jira Synced

#12048 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12047 build(deps): updated testing deps
  package.json
  yarn.lock
Labels: Jira Synced

#12045 fix(TX-1071): improve checkout flow tab accessibility
  src/Apps/Order/Components/CreditCardPicker.tsx
  src/Apps/Order/Components/PhoneNumberForm.tsx
  src/Apps/Order/Components/SaveAndContinueButton.tsx
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Components/AddressForm.tsx
  src/Components/CountrySelect.tsx
Labels: Jira Synced

#12051 chore: remove released collector profile and separate saves and follows ff
  .secrets.baseline
  src/Apps/Artist/Components/BackLink.tsx
  src/Apps/Artist/Components/__tests__/BackLink.jest.tsx
  src/Apps/CollectorProfile/CollectorProfileApp.tsx
  src/Apps/CollectorProfile/Routes/Follows/CollectorProfileFollowsRoute.tsx
  src/Apps/CollectorProfile/Routes/SavesAndFollows/CollectorProfileSavesAndFollowsRoute.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYouWhenFromMyCollection.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormHeader.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormMain.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionEditArtwork.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkBackButton.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkImageBrowser/MyCollectionArtworkNoImageComponent.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkImageBrowser/__tests__/MyCollectionArtworkImageBrowser.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkRequestPriceEstimateSection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/__tests__/MyCollectionArtwork.jest.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateConfirmation.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/__tests__/PriceEstimateContactInformation.jest.tsx
  src/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
  src/Apps/Settings/Routes/EditSettings/Components/__tests__/SettingsEditSettingsInformation.jest.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Components/CareerHighlightModalPromoStep.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightPromoCard.tsx
  src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx
  src/Apps/Settings/Routes/Insights/Components/InsightsLandingPage.tsx
  src/Apps/Settings/Routes/Insights/Components/InsightsMedianSalePrice.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
  src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsMedianSalePrice.jest.tsx
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
  src/Apps/Settings/Routes/MyCollection/Components/MyCollectionEmptyState.tsx
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
  src/Apps/Settings/SettingsApp.tsx
  src/Components/Artwork/__tests__/Metadata.jest.tsx
  src/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/Components/NavBar/Menus/__tests__/NavBarUserMenu.jest.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotifications.tsx
  src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
  src/Components/NavBar/__tests__/NavBar.jest.tsx
  src/Components/NavBar/__tests__/NavBarTracking.jest.tsx
Labels: Jira Synced

#12024 feat(FX-4637): User adds artworks to new list — initial artwork grid and selection
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/AddArtworksModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/ArtworkItem.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/ArtworksList.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModalWizard.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/SelectArtworkItem.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesHeader.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/CreateNewListModalMutation.graphql.ts
Labels: Jira Synced

#12059 chore: remove cx released ffs
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASectionSubmitted.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/__tests__/MyCollectionArtwork.jest.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightCard.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightPromoCard.tsx
  src/Apps/Settings/Routes/MyCollection/Components/EmptyMyCollectionPage.tsx
Labels: Jira Synced

#12013 feat(FX-4592): display toasts for Saves
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkModal.tsx
  src/Components/Artwork/ManageArtworkForSaves.tsx
  src/Components/Artwork/SaveButton/SaveArtworkToListsButton.tsx
  src/Components/Artwork/SaveButton/__tests__/SaveArtworkToListsButton.jest.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/SelectListsForArtworkModalQuery.graphql.ts
  src/__generated__/SelectListsForArtworkModal_Test_Query.graphql.ts
  src/__generated__/SelectListsForArtworkModal_me.graphql.ts
Labels: Jira Synced

#12062 chore: remove more cx ffs
  .secrets.baseline
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx
  src/Components/Artwork/Details.tsx
  src/Components/Artwork/__tests__/Details.jest.tsx
Labels: Jira Synced

#12065 fix: compacts artworks displayed in shelf
  src/Components/RecentlyViewed/RecentlyViewed.tsx
Labels: Merge On Green

#12008 feat: use order displayState instead of state
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/Routes/__tests__/Status.jest.tsx
  src/Apps/Order/__tests__/OrderApp.jest.tsx
  src/Apps/Order/redirects.tsx
  src/__generated__/orderRoutes_OrderQuery.graphql.ts
  src/__generated__/redirects_order.graphql.ts
Labels: Jira Synced, Squash On Green

#12069 refactor: add comment to clarify usage of inputs in verifyID helper
  src/Apps/Settings/Routes/EditProfile/helpers/verifyID.ts
Labels: Jira Synced

#12063 chore: show only past auction results inside insights
  src/Apps/Settings/Routes/Insights/Components/InsightsAuctionResults.tsx
Labels: Jira Synced

#12071 fix(CX-3526): add new copies, adjust images in carousels
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/CollectorsOverview.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Highlights.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Footer.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HowItWorksSteps.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/__generated__/InsightsAuctionResults_me.graphql.ts
  src/__generated__/collectorProfileRoutes_InsightsRouteQuery.graphql.ts
  src/__generated__/settingsRoutes_InsightsRouteQuery.graphql.ts
Labels: Jira Synced

#12057 chore:slight style refactor of conditional link
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
  src/Components/Artwork/Details.tsx
Labels: Jira Synced

#12074 chore: improvements for edit list and create new list modals
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/EditSavesModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/EditSavesModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModal.tsx
Labels: Jira Synced

#12077 chore: new link styles integration
  package.json
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
  src/Apps/Conversation/Components/ConversationSnippet.tsx
  src/Apps/Conversation/Components/Item.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#12085 chore(CX-3530): hide parts of the page
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
Labels: Jira Synced

#12058 feat(CX-3413): Add confidentialNotes field to My Collection artwork form
  .secrets.baseline
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormMain.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionEditArtwork.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkFormHelpers.ts
  src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkModel.ts
  src/Apps/MyCollection/Routes/EditArtwork/Utils/useCreateOrUpdateArtwork.ts
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx
  src/__generated__/MyCollectionEditArtworkTest_Query.graphql.ts
  src/__generated__/MyCollectionEditArtwork_artwork.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionArtworkFormQuery.graphql.ts
  src/__generated__/myCollectionRoutes_MyCollectionArtworkFormQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#12076 feat: add delete collection updater and redirect
  src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/DeleteSavesModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/Mutations/useCreateCollection.ts
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/Mutations/useDeleteCollection.ts
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModal.tsx
  src/__generated__/CollectorProfileSaves2Route_Test_Query.graphql.ts
  src/__generated__/CollectorProfileSaves2Route_me.graphql.ts
  src/__generated__/collectorProfileRoutes_Saves2Query.graphql.ts
  src/__generated__/useCreateCollectionMutation.graphql.ts
  src/__generated__/useDeleteCollectionMutation.graphql.ts
Labels: Jira Synced

#12083 style: move the see full results to the bottom
  src/Components/Search/SearchBar.tsx
  src/Components/Search/Suggestions/SuggestionItem.tsx
  src/Components/Search/__tests__/SearchBar.jest.tsx
Labels: Jira Synced

#12084 refactor: clean up new-price-list feature flag
  src/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
  src/Apps/ArtistSeries/artistSeriesRoutes.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
  src/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilterNew.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilterNew.jest.tsx
Labels: Jira Synced

#12082 CX-3493: Sort "Curator's Picks: Emerging" home rail by decayed merch
  scripts/setup.sh
  src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx
  src/__generated__/HomeEmergingPicksArtworksRailQuery.graphql.ts
  src/__generated__/HomeEmergingPicksArtworksRail_Test_Query.graphql.ts
  src/__generated__/HomeEmergingPicksArtworksRail_viewer.graphql.ts
Labels: Jira Synced, Squash On Green

#12091 docs: update create review app.md
  docs/creating_review_app.md
Labels: Jira Synced

#12090 refactor(cleanup): remove artist-artwork-grid-keyword-search
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
  src/Apps/ArtistSeries/__tests__/ArtistSeriesArtworksFilter.jest.tsx
  src/Apps/Auction/Components/AuctionArtworkFilter.tsx
  src/Apps/Fair/Routes/FairArtworks.tsx
  src/Apps/Gene/Components/__tests__/GeneArtworkFilter.jest.tsx
  src/Apps/Partner/Routes/__tests__/Works.jest.tsx
  src/Apps/Show/__tests__/ShowArtworks.jest.tsx
  src/Apps/Tag/Components/__tests__/TagArtworkFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/index.tsx
Labels: Jira Synced, Squash On Green

#12098 chore(CX-3538): change icons, comment out testimonials
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/DollarCircleIcon.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/GlobeNetworkCircleIcon.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Highlights.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PlanetCircleIcon.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/StarCircleIcon.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
Labels: Jira Synced

#12061 feat(FX-4637): User adds artworks to new list — connect backend
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/AddArtworksModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/AddArtworksModalContent.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/ArtworkItem.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/ArtworksList.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModalWizard.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/__tests__/CreateNewListModalWizard.jest.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/AddArtworksModalContentQuery.graphql.ts
  src/__generated__/AddArtworksModalContentRefetchQuery.graphql.ts
  src/__generated__/AddArtworksModalContent_me.graphql.ts
  src/__generated__/ArtworksList_artworks.graphql.ts
Labels: Jira Synced

#12102 chore: Bring back brew section from setup script
  scripts/setup.sh
Labels: Squash On Green

#12103 fix: replace the image
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
Labels: Jira Synced, Squash On Green

#12099 chore: cleanup trending-sort-for-artist-artwork-grids feature flag
  src/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilter.jest.tsx
Labels: Jira Synced

#12101 feat(FX-4639): User adds artworks to new list — mutation and toast
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/AddArtworksModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/ArtworksList.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModalForManageArtwork.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModalWizard.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/__tests__/AddArtworksModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/useAddArtworksToCollection.ts
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesHeader.tsx
  src/Components/Artwork/ManageArtworkForSaves.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/useAddArtworksToCollectionMutation.graphql.ts
Labels: Jira Synced

#12108 chore: specify `sort` arg for other collections
  src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
  src/__generated__/CollectorProfileSaves2Route_Test_Query.graphql.ts
  src/__generated__/CollectorProfileSaves2Route_me.graphql.ts
  src/__generated__/collectorProfileRoutes_Saves2Query.graphql.ts
Labels: Jira Synced

#12110 fix(home): fixes image stretching; clean up
  cypress/e2e/home.cy.ts
  src/Apps/Home/Components/HomeContentCards/BrazeCards.tsx
  src/Apps/Home/Components/HomeContentCards/FallbackCards.tsx
  src/Apps/Home/Components/HomeContentCards/HomeContentCard.tsx
  src/Apps/Home/Components/HomeContentCards/PlaceholderCards.tsx
  src/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
  src/Apps/Home/Components/HomeHeroUnits/__tests__/HomeHeroUnit.jest.tsx
  src/Apps/Home/HomeApp.tsx
  src/Apps/Home/__tests__/HomeApp.jest.tsx
  src/Apps/Home/homeRoutes.tsx
  src/__generated__/HomeApp_Test_Query.graphql.ts
  src/__generated__/HomeApp_homePage.graphql.ts
  src/__generated__/HomeHeroUnit_Test_Query.graphql.ts
  src/__generated__/HomeHeroUnit_heroUnit.graphql.ts
  src/__generated__/homeRoutes_HomeQuery.graphql.ts
Labels: Merge On Green

#12112 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12113 fix(CX-3360): address design issues
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FAQSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FooterBanner.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/FAQSWA.jest.tsx
Labels: Jira Synced

#12117 fix(artist): uses status field to determine auction lots rendering
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Routes/Overview/Utils/renderOrRedirect.tsx
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistApp_artist.graphql.ts
  src/__generated__/ArtistApp_sharedMetadata.graphql.ts
  src/__generated__/artistRoutes_TopLevelQuery.graphql.ts
Labels: Jira Synced

#12095 feat(TX-1079): update order app layout
  src/Apps/Order/OrderApp.tsx
  src/Apps/Order/__tests__/OrderApp.jest.tsx
  src/Apps/Order/orderRoutes.tsx
  src/Components/NavBar/MinimalNavBar.tsx
  src/Components/NavBar/__tests__/MinimalNavBar.jest.tsx
Labels: Jira Synced, Squash On Green

#12081 feat(TX-1015): order creation after auth
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercialButtons.jest.tsx
  src/Utils/Hooks/useAuthIntent/index.tsx
  src/Utils/Hooks/useAuthIntent/mutations/AuthIntentCreateOfferOrderMutation.ts
  src/Utils/Hooks/useAuthIntent/mutations/AuthIntentCreateOrderMutation.ts
  src/__generated__/AuthIntentCreateOfferOrderMutation.graphql.ts
  src/__generated__/AuthIntentCreateOrderMutation.graphql.ts
Labels: Jira Synced

#12121 fix(CX-3493): Increase number of artworks in Curator's picks rail to 20
  src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx
  src/__generated__/HomeEmergingPicksArtworksRailQuery.graphql.ts
  src/__generated__/HomeEmergingPicksArtworksRail_Test_Query.graphql.ts
  src/__generated__/HomeEmergingPicksArtworksRail_viewer.graphql.ts
Labels: Jira Synced

#12097 refactor(cleanup): remove force-fetch-alert-labels-from-metaphysics ff
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertContext.tsx
  src/Components/SavedSearchAlert/Utils/__tests__/convertLabelsToPills.jest.ts
  src/Components/SavedSearchAlert/Utils/convertLabelsToPills.ts
  src/__generated__/SavedSearchAlertEditFormQuery.graphql.ts
  src/__generated__/SavedSearchAlertEditForm_Test_Query.graphql.ts
  src/__generated__/SavedSearchAlertEditForm_me.graphql.ts
Labels: Jira Synced

#12115 feat: Image icon in search result
  src/Components/Search/SearchBar.tsx
  src/Components/Search/Suggestions/SuggestionItem.tsx
  src/Components/Search/Suggestions/SuggestionItemPreview.tsx
  src/Components/Search/__tests__/SearchBar.jest.tsx
  src/__generated__/SearchBarRefetchQuery.graphql.ts
  src/__generated__/SearchBarSuggestQuery.graphql.ts
  src/__generated__/SearchBarTestQuery.graphql.ts
  src/__generated__/SearchBar_viewer.graphql.ts
Labels: Jira Synced

#12049 feat(TX-1061): Provenance and artwork condition for PS orders
  .secrets.baseline
  src/Apps/Order/Components/AdditionalArtworkDetails.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__tests__/Payment.jest.tsx
  src/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/AdditionalArtworkDetails_order.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/Payment_order.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/Review_order.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#12125 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12116 feat(FX-4689): Change the behavior of the 💙 button when the user is NOT logged in to the account
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveToListsButton.tsx
  src/Components/Artwork/SaveButton/SaveArtworkToListsButton.tsx
  src/Components/Artwork/SaveButton/__tests__/SaveArtworkToListsButton.jest.tsx
  src/Components/Artwork/SaveButton/useSaveArtworkToLists.ts
  src/Components/Artwork/SaveButton/useSaveArtworkToLists.tsx
  src/Components/Artwork/useArtworkLists.ts
  src/System/i18n/locales/en-US/translation.json
  src/Utils/Hooks/useAuthIntent/index.tsx
  src/__generated__/ArtworkActionsSaveToListsButton_artwork.graphql.ts
  src/__generated__/ArtworkActions_Test_Query.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#12130 feat: update bidding starts copy
  src/Utils/__tests__/getSaleOrLotTimerInfo.jest.ts
  src/Utils/getSaleOrLotTimerInfo.ts
Labels: Jira Synced

#12127 feat: empty states for artwork lists
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/DeleteSavesModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/EditSavesModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/SavesContextualMenu.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/DeleteSavesModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/EditSavesModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/SavesContextualMenu.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesArtworks.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesArtworksGrid.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesEmptyState.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/SavesArtworks.jest.tsx
  src/__generated__/SavesArtworksGrid_artworks.graphql.ts
  src/__generated__/SavesArtworksGrid_collection.graphql.ts
  src/__generated__/SavesArtworksGrid_me.graphql.ts
  src/__generated__/SavesArtworksQuery.graphql.ts
  src/__generated__/SavesArtworks_Test_Query.graphql.ts
  src/__generated__/SavesArtworks_collection.graphql.ts
  src/__generated__/SavesArtworks_me.graphql.ts
  src/__generated__/SavesEmptyState_collection.graphql.ts
  src/__generated__/SavesEmptyState_me.graphql.ts
Labels: Jira Synced, Squash On Green

#12135 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12138 fix: remove second popup appearing on artwork page after leaving checkout
  src/Apps/Order/OrderApp.tsx
Labels: Jira Synced

#12134 feat: add ff on saves - nav - dropdown
  src/Apps/CollectorProfile/CollectorProfileApp.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Utils/useLinksToSaves.ts
  src/Components/NavBar/Menus/NavBarUserMenu.tsx
Labels: Jira Synced, Squash On Green

#12144 chore: update swa landing page images
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
Labels: Jira Synced, Squash On Green

#12147 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12149 chore(feature-flags): removes art-quiz flag
  src/Apps/ArtQuiz/artQuizRoutes.tsx
Labels: Merge On Green

#12151 chore: Update a headshot GRO-1633
  src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Merge On Green

#12157 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
Labels: Squash On Green

#12153 refactor: Verify Your ID and Verify Your Email mutations
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
  src/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileFields.jest.tsx
  src/Apps/Settings/Routes/EditProfile/Mutations/useVerifyEmail.ts
  src/Apps/Settings/Routes/EditProfile/Mutations/useVerifyID.ts
  src/Apps/Settings/Routes/EditProfile/helpers/useHandleVerification.tsx
  src/Apps/Settings/Routes/EditProfile/helpers/verifyEmail.ts
  src/Apps/Settings/Routes/EditProfile/helpers/verifyID.ts
  src/__generated__/useVerifyEmailMutation.graphql.ts
  src/__generated__/useVerifyIDMutation.graphql.ts
Labels: Jira Synced, Squash On Green

#12168 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12154 chore: update copy on SWA confirmation pages
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYouWhenFromMyCollection.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYouWhenFromMyCollection.jest.tsx
Labels: Jira Synced, Squash On Green

#12160 fix(CX-3581): swa adjust alignment
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
Labels: Jira Synced

#12169 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12171 refactor(phase 2): standardise and use ArtworkList terminology
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/DeleteArtworkListModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/EditArtworkListModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/Mutations/useDeleteArtworkList.ts
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/Mutations/useUpdateArtworkList.ts
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/SavesContextualMenu.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/DeleteArtworkListModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/EditArtworkListModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/SavesContextualMenu.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesArtworks.tsx
  src/__generated__/useDeleteArtworkListMutation.graphql.ts
  src/__generated__/useUpdateArtworkListMutation.graphql.ts
Labels: Jira Synced

#12175 refactor(phase 3): standardise and use `ArtworkList` terminology
  src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/ArtworkListContextualMenu.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/ArtworkListContextualMenu.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListArtworksGrid.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListArtworksGridHeader.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListContent.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListEmptyState.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListPlaceholders.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/ArtworkListContent.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/ArtworkListEmptyState.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/SavesArtworks.jest.tsx
  src/__generated__/ArtworkListArtworksGrid_me.graphql.ts
  src/__generated__/ArtworkListContentQuery.graphql.ts
  src/__generated__/ArtworkListContent_Test_Query.graphql.ts
  src/__generated__/ArtworkListContent_me.graphql.ts
  src/__generated__/ArtworkListEmptyState_Test_Query.graphql.ts
  src/__generated__/ArtworkListEmptyState_me.graphql.ts
Labels: Jira Synced, Squash On Green

#12176 refactor(phase 4): standardise and use `ArtworkList` terminology
  src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListItem.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListsHeader.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Images/ArtworkListNoImage.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Images/FourUpImageLayout.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Images/StackedImageLayout.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Images/__tests__/FourUpImageLayout.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Images/__tests__/StackedImageLayout.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesEntityImage.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/ArtworkListsHeader.jest.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#12177 refactor(phase 5): standardise and use `ArtworkList` terminology
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectArtworkListItem.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectArtworkListsContent.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectArtworkListsFooter.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectArtworkListsHeader.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectArtworkListsPlaceholders.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkContent.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/useSelectArtworkLists.ts
  src/Components/Artwork/__tests__/ManageArtworkForSaves.jest.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/SelectArtworkListItem_item.graphql.ts
  src/__generated__/SelectListsForArtworkModalQuery.graphql.ts
  src/__generated__/SelectListsForArtworkModal_Test_Query.graphql.ts
  src/__generated__/SelectListsForArtworkModal_me.graphql.ts
  src/__generated__/useSelectArtworkListsMutation.graphql.ts
Labels: Jira Synced, Squash On Green

#12184 feat(FX-4707): Track `editedArtworkList` event when a user edits an artwork list
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/EditArtworkListModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/EditArtworkListModal.jest.tsx
Labels: Jira Synced, Squash On Green
