Repository artsy/force, pull requests merged in 2023-11, with the labels that each got.

#13093 fix(artist): corrects spacing in safari
  src/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx
Labels: Jira Synced

#13096 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13092 feat: new artwork alert (create alert) modal
  src/Apps/Alert/AlertApp.tsx
  src/Apps/Alert/alertRoutes.tsx
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistWorksForSaleEmpty.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBiddingClosedMessage.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlert.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkSidebarCreateAlert.jest.tsx
  src/Components/Alert/Components/CriteriaPills.tsx
  src/Components/Alert/Components/Debug.tsx
  src/Components/Alert/Components/Filters/Rarity.tsx
  src/Components/Alert/Components/Form/AlertNameInput.tsx
  src/Components/Alert/Components/Form/PriceRange.tsx
  src/Components/Alert/Components/Modal.tsx
  src/Components/Alert/Components/Steps.tsx
  src/Components/Alert/Components/Steps/Confirmation.tsx
  src/Components/Alert/Components/Steps/Details.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
  src/Components/Alert/Hooks/useAlert.tsx
  src/Components/Alert/Hooks/useAlertContext.tsx
  src/Components/Alert/Hooks/useCreateAlert.tsx
  src/Components/Alert/index.ts
  src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx
  src/Components/SavedSearchAlert/Utils/savedSearchCriteria.tsx
  src/__generated__/AlertNameInputQuery.graphql.ts
  src/__generated__/AlertNameInput_previewSavedSearch.graphql.ts
  src/__generated__/ArtworkSidebarAuctionInfoPollingQuery.graphql.ts
  src/__generated__/ArtworkSidebarBiddingClosedMessage_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCreateAlert_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCreateAlert_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCurrentBidInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/__generated__/CriteriaPillsQuery.graphql.ts
  src/__generated__/CriteriaPills_previewSavedSearch.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/useCreateAlertMutation.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#13099 fix(ONYX-386): remove new artwork alert modal from auctions header
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
Labels: Jira Synced

#13100 fix(pricerange): respond to external value changes; adds debounced callback
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/PriceRangeFilter.tsx
  src/Components/Alert/Components/Form/PriceRange.tsx
  src/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/PriceRangeFilterQuick.tsx
  src/Components/PriceRange/PriceRange.tsx
  src/Components/SavedSearchAlert/Components/PriceRangeFilter.tsx
Labels: Jira Synced

#13103 fix(artist): corrects empty condition; guards on extraneous fetches of subcomponents
  src/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx
  src/Apps/Artist/Routes/Overview/__tests__/ArtistOverviewRoute.jest.tsx
  src/__generated__/ArtistOverviewRoute_Test_Query.graphql.ts
  src/__generated__/ArtistOverviewRoute_artist.graphql.ts
  src/__generated__/artistRoutes_OverviewQuery.graphql.ts
Labels: Jira Synced

#13101 chore(DIA-204): Display save tooltip regardless of logged in status
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.jest.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingSaves.jest.tsx
Labels: Jira Synced

#13098 chore: update list of specialists
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/MeetTheSpecialists.jest.tsx
Labels: Squash On Green

#13105 fix(DIA-308): implements less confusing "artists you follow" filter behavior
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
  src/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/ShowMore.tsx
  src/Components/ArtworkFilter/ArtworkFilters/index.tsx
  src/Components/ArtworkFilter/index.tsx
  src/Components/SavedSearchAlert/Utils/extractPills.ts
  src/Components/SavedSearchAlert/constants.ts
  src/Components/SavedSearchAlert/useActiveFilterPills.ts
Labels: Jira Synced

#13110 fix(article): uses channel name; falls back to byline
  src/Apps/Article/Components/ArticleChannelRelatedArticles.tsx
  src/__generated__/ArticleChannelRelatedArticlesQuery.graphql.ts
  src/__generated__/ArticleChannelRelatedArticles_article.graphql.ts
Labels: Jira Synced

#13107 Deploy
  src/Apps/Article/Components/ArticleChannelRelatedArticles.tsx
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
  src/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
  src/Components/Alert/Components/Steps/Details.tsx
  src/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/ShowMore.tsx
  src/Components/ArtworkFilter/ArtworkFilters/index.tsx
  src/Components/ArtworkFilter/index.tsx
  src/Components/SavedSearchAlert/Utils/extractPills.ts
  src/Components/SavedSearchAlert/constants.ts
  src/Components/SavedSearchAlert/useActiveFilterPills.ts
  src/__generated__/ArticleChannelRelatedArticlesQuery.graphql.ts
  src/__generated__/ArticleChannelRelatedArticles_article.graphql.ts
Labels: Jira Synced

#13106 feat: Add Medium Alert Filter
  src/Components/Alert/Components/Filters/Medium.tsx
  src/Components/Alert/Components/Filters/QuickMultipleSelectAlertFilter.tsx
  src/Components/Alert/Components/Filters/Rarity.tsx
  src/Components/Alert/Components/Filters/ShowMore.tsx
  src/Components/Alert/Components/Filters/__tests__/Medium.jest.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
Labels: Jira Synced

#13112 chore: Remove filter context from alert medium filter test
  src/Components/Alert/Components/Filters/__tests__/Medium.jest.tsx
Labels: Squash On Green

#13119 feat(ONYX-387, ONYX-513): add price range filter, move min/max inputs of Price Range filter below the slider
  src/Components/Alert/Components/Filters/Price.tsx
  src/Components/Alert/Components/Filters/__tests__/Price.jest.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
  src/Components/Alert/Hooks/useAlertContext.tsx
  src/Components/PriceRange/PriceRange.tsx
Labels: Jira Synced, Squash On Green

#13122 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12415 feat: New Palette inputs [Review-app]
  package.json
  src/Apps/Artist/Routes/AuctionResults/Components/SortSelect.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Auction/Components/Form/Utils/errorMessages.ts
  src/Apps/Auction/Hooks/useCreateTokenAndSubmit.ts
  src/Apps/Auction/Routes/__tests__/AuctionConfirmRegistrationRoute.jest.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/Components/ConsignmentInquiryForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/acceptableCategoriesForSubmission.ts
  src/Apps/Fair/Components/__tests__/FairBooths.jest.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Utils/rarityOptions.ts
  src/Apps/Order/Components/AddressModal.tsx
  src/Apps/Order/Components/CreditCardPicker.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/Shipping2.jest.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/Apps/PriceDatabase/Components/PriceDatabaseSearch.tsx
  src/Apps/Search/Routes/__tests__/SearchResultsArtworks.jest.tsx
  src/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethodForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx
  src/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddressForm.tsx
  src/Components/Address/AddressForm.tsx
  src/Components/Address/AddressModalFields.tsx
  src/Components/BankDebitForm/BankDebitProvider.tsx
  src/Components/CreditCardInput/CreditCardInput.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/PriceRange/PriceRange.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/Components/Search/Mobile/Overlay.tsx
  src/Components/Search/NavBarSearchInputContainer.tsx
  src/Components/Search/SearchBarInput.tsx
  src/Components/SortFilter.tsx
  src/Components/__tests__/SortFilter.jest.tsx
  src/Utils/countries.ts
  yarn.lock
Labels: Jira Synced, Squash On Green

#13121 Deploy
  data/schema.graphql
  package.json
  scripts/setup.sh
  src/Apps/Artist/Routes/AuctionResults/Components/SortSelect.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Auction/Components/Form/Utils/errorMessages.ts
  src/Apps/Auction/Hooks/useCreateTokenAndSubmit.ts
  src/Apps/Auction/Routes/__tests__/AuctionConfirmRegistrationRoute.jest.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/Components/ConsignmentInquiryForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/acceptableCategoriesForSubmission.ts
  src/Apps/Fair/Components/__tests__/FairBooths.jest.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Utils/rarityOptions.ts
  src/Apps/Order/Components/AddressModal.tsx
  src/Apps/Order/Components/CreditCardPicker.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/Shipping2.jest.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/Apps/PriceDatabase/Components/PriceDatabaseSearch.tsx
  src/Apps/Search/Routes/__tests__/SearchResultsArtworks.jest.tsx
  src/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethodForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx
  src/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddressForm.tsx
  src/Components/Address/AddressForm.tsx
  src/Components/Address/AddressModalFields.tsx
  src/Components/Alert/Components/Filters/Price.tsx
  src/Components/Alert/Components/Filters/__tests__/Price.jest.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
  src/Components/Alert/Hooks/useAlertContext.tsx
  src/Components/BankDebitForm/BankDebitProvider.tsx
  src/Components/CreditCardInput/CreditCardInput.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/PriceRange/PriceRange.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/Components/Search/Mobile/Overlay.tsx
  src/Components/Search/NavBarSearchInputContainer.tsx
  src/Components/Search/SearchBarInput.tsx
  src/Components/SortFilter.tsx
  src/Components/__tests__/SortFilter.jest.tsx
  src/Utils/countries.ts
  yarn.lock
Labels: Jira Synced

#13124 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/createSavedSearchAlertMutation.graphql.ts
  src/__generated__/useCreateAlertMutation.graphql.ts
  src/__generated__/useEditSavedSearchAlertMutation.graphql.ts
Labels: Squash On Green

#13126 test: add new selectors for Integrity to fix CC issue
  src/Components/CreditCardInput/CreditCardInput.tsx
Labels: Jira Synced, Squash On Green

#13123 feat(ONYX-479): add color and ways to buy filters
  src/Components/Alert/Components/Filters/Color.tsx
  src/Components/Alert/Components/Filters/WaysToBuy.tsx
  src/Components/Alert/Components/Filters/__tests__/Color.jest.tsx
  src/Components/Alert/Components/Filters/__tests__/WaysToBuy.jest.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
Labels: Jira Synced

#13128 feat(nav): updates nav items
  src/Components/NavBar/Menus/NavBarSubMenu.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileSubMenu.tsx
  src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
  src/Components/NavBar/menuData.ts
Labels: Jira Synced

#13125 Deploy
  data/schema.graphql
  src/Apps/Example/Mutations/.gitkeep
  src/Apps/Example/Utils/.gitkeep
  src/Components/Alert/Components/Filters/Color.tsx
  src/Components/Alert/Components/Filters/WaysToBuy.tsx
  src/Components/Alert/Components/Filters/__tests__/Color.jest.tsx
  src/Components/Alert/Components/Filters/__tests__/WaysToBuy.jest.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
  src/Components/CreditCardInput/CreditCardInput.tsx
  src/Components/NavBar/Menus/NavBarSubMenu.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileSubMenu.tsx
  src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
  src/Components/NavBar/menuData.ts
  src/__generated__/createSavedSearchAlertMutation.graphql.ts
  src/__generated__/useCreateAlertMutation.graphql.ts
  src/__generated__/useEditSavedSearchAlertMutation.graphql.ts
Labels: Jira Synced

#13132 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/SavedSearchAlertNameInputQuery.graphql.ts
  src/__generated__/SavedSearchAlertNameInput_Test_Query.graphql.ts
  src/__generated__/useAlertContextPreviewQuery.graphql.ts
Labels: Squash On Green

#13131 feat(alerts): reorder filters in new create alert modal
  src/Components/Alert/Components/Steps/Filters.tsx
Labels: Jira Synced

#13133 chore(alerts): remove passing of authDialogOptions options to useAlert
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistWorksForSaleEmpty.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlert.tsx
  src/Components/Alert/Hooks/useAlert.tsx
  src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx
  src/Utils/Hooks/useAuthIntent/index.tsx
Labels: Jira Synced

#13136 feat(alerts): small style updates to the new create alert modal
  src/Components/Alert/Components/Modal.tsx
  src/Components/Alert/Components/Steps/Details.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
Labels: Jira Synced

#13130 chore(analytics): add analytics events to new create alert modal
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistWorksForSaleEmpty.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBiddingClosedMessage.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlert.tsx
  src/Components/Alert/Components/CreateAlertButton.tsx
  src/Components/Alert/Hooks/useAlertContext.tsx
  src/Components/Alert/Hooks/useAlertTracking.ts
  src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx
Labels: Jira Synced

#13137 feat(alerts): copy update for details screen
  src/Components/Alert/Components/Steps/Details.tsx
Labels: Jira Synced

#13138 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13139 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13129 feat: Create alert logged-out experience
  src/Components/Alert/Hooks/useAlert.tsx
  src/Utils/Hooks/useAuthIntent/index.tsx
Labels: Jira Synced, Squash On Green

#13135 feat: mark App Authenticator as preferred 2fa method
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
  src/Utils/__tests__/isArtsyEmail.jest.ts
  src/Utils/isArtsyEmail.ts
Labels: Jira Synced

#13142 chore(webpack): Remove fork-ts-checker webpack plugin
  package.json
  webpack/envs/clientDevelopmentConfig.js
  yarn.lock
Labels: Merge On Green

#13143 refactor: use recommended instead of preferred for App Auth 2fa
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
Labels: Jira Synced

#13146 feat(dia-194): sticky article sidebar
  src/Apps/Article/Components/ArticleBody.tsx
  src/Components/Sticky/Sticky.tsx
Labels: Jira Synced

#13149 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13150 fix(alerts): ensure artist series in previews/pills when managing alerts
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/__generated__/SavedSearchAlertListItem_item.graphql.ts
  src/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
  src/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
  src/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts
  src/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts
Labels: Jira Synced

#13151 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13154 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13152 fix(search): uses cover artworks for avatar images on artists
  src/Components/Search/Mobile/SearchResultsList.tsx
  src/Components/Search/SearchBarInput.tsx
  src/__generated__/MobileSearchBarSuggestQuery.graphql.ts
  src/__generated__/OverlayRefetchQuery.graphql.ts
  src/__generated__/SearchBarInputRefetchQuery.graphql.ts
  src/__generated__/SearchBarInputSuggestQuery.graphql.ts
  src/__generated__/SearchBarInput_viewer.graphql.ts
  src/__generated__/SearchResultsListPaginationQuery.graphql.ts
  src/__generated__/SearchResultsList_viewer.graphql.ts
Labels: Jira Synced

#13156 feat(ONYX-529): alert modal UI updates
  src/Components/Alert/Components/CriteriaPills.tsx
  src/Components/Alert/Components/Filters/Medium.tsx
  src/Components/Alert/Components/Filters/QuickMultipleSelectAlertFilter.tsx
  src/Components/Alert/Components/Modal.tsx
  src/Components/Alert/Components/Steps.tsx
  src/Components/Alert/Components/Steps/Details.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
Labels: Jira Synced

#13120 chore: EMI-1552 Shipping with no saved addresses
  src/Apps/Order/Routes/Shipping2/AddressModal.jest.tsx
  src/Apps/Order/Routes/Shipping2/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/Hooks/useParseOrderData.ts
  src/Apps/Order/Routes/Shipping2/Hooks/useShippingContext.ts
  src/Apps/Order/Routes/Shipping2/Mutations/useCreateSavedAddress.ts
  src/Apps/Order/Routes/Shipping2/Mutations/useDeleteSavedAddress.ts
  src/Apps/Order/Routes/Shipping2/Mutations/useSaveFulfillmentDetails.ts
  src/Apps/Order/Routes/Shipping2/Mutations/useSelectShippingQuote.ts
  src/Apps/Order/Routes/Shipping2/Mutations/useUpdateSavedAddress.ts
  src/Apps/Order/Routes/Shipping2/Mutations/useUpdateUserDefaultAddress.ts
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/ShippingContext.ts
  src/Apps/Order/Routes/Shipping2/Utils/ShippingContext.ts
  src/Apps/Order/Routes/Shipping2/Utils/shippingUtils.ts
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/setOrderShipping.ts
  src/Apps/Order/Utils/useOrderTracking.tsx
  src/__generated__/AddressModal2TestQuery.graphql.ts
  src/__generated__/Shipping2TestQuery.graphql.ts
  src/__generated__/Shipping2_order.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/useCreateSavedAddressMutation.graphql.ts
  src/__generated__/useDeleteSavedAddressMutation.graphql.ts
  src/__generated__/useSaveFulfillmentDetailsMutation.graphql.ts
  src/__generated__/useSelectShippingQuoteMutation.graphql.ts
  src/__generated__/useUpdateSavedAddressMutation.graphql.ts
  src/__generated__/useUpdateUserDefaultAddressMutation.graphql.ts
Labels: Jira Synced

#13161 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13163 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13169 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13158 feat: Alert filter price histogram
  src/Components/Alert/Components/Filters/Price.tsx
  src/Components/Alert/Components/Filters/__tests__/Price.jest.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
  src/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/__generated__/PriceAggregationsQuery.graphql.ts
  src/__generated__/Price_artworksConnection.graphql.ts
Labels: Jira Synced

#13160 fix: Alert filter modal overflow background
  src/Components/Alert/Components/Modal.tsx
Labels: Jira Synced

#13173 feat(progressive-onboarding): sync saving artwork logged out
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx
  src/Utils/Hooks/useAuthIntent/index.tsx
Labels: Jira Synced

#13175 chore: guard after auth behavior behind same feature flag
  src/Components/Alert/AlertProvider.tsx
Labels: Jira Synced

#13178 docs: mark deprecated testing utilities and point to updated docs
  src/DevTools/README.md
  src/DevTools/renderRelayTree.tsx
  src/DevTools/setupTestWrapper.tsx
Labels: Merge On Green, Jira Synced

#13182 chore(eslint): Add rule guarding against relay-runtime `graphql` import
  .eslintrc.js
Labels: Merge On Green

#13187 feat: Sort artwork lists by updated at desc
  src/Apps/CollectorProfile/Routes/Saves/Components/SelectArtworkListsModal/SelectArtworkListsModal.tsx
  src/__generated__/SelectArtworkListsModalQuery.graphql.ts
  src/__generated__/SelectArtworkListsModal_Test_Query.graphql.ts
  src/__generated__/SelectArtworkListsModal_me.graphql.ts
Labels: Jira Synced

#13159 feat(onyx-472): add size filter to alert filters
  src/Components/Alert/AlertContext.ts
  src/Components/Alert/AlertProvider.tsx
  src/Components/Alert/Components/Filters/Size.tsx
  src/Components/Alert/Components/Filters/__tests__/Size.jest.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
  src/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter.jest.tsx
  src/Components/SavedSearchAlert/Utils/extractPills.ts
  src/Utils/__tests__/customSizeUtils.jest.ts
  src/Utils/customRangeUtils.ts
  src/Utils/customSizeUtils.ts
Labels: Jira Synced

#13195 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13197 Revert "feat(filters): jump to top on filter apply"
  src/Components/ArtworkFilter/index.tsx
Labels: Merge On Green

#13203 fix: adjust sellers bio and photo
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
Labels: Squash On Green

#13205 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useAddCreditCardAndUpdateProfileMutation.graphql.ts
  src/__generated__/useUpdateMyUserProfileMutation.graphql.ts
  src/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Squash On Green

#13207 chore(convos): Update copy
  src/Apps/Conversations/components/ConversationCTA/ConversationReviewOfferCTA.tsx
  src/Apps/Conversations/components/Details/OrderInformation/__tests__/OrderState.jest.tsx
  src/Apps/Conversations/components/Details/OrderState/ConversationStatusWithCounter.tsx
Labels: Merge On Green

#13208 feat(convos): Add ZeroState
  src/Apps/Conversations/ConversationApp.tsx
  src/Apps/Conversations/components/ConversationZeroState.tsx
  src/Apps/Conversations/conversationsRoutes.tsx
  src/__generated__/conversationsRoutes_DetailQuery.graphql.ts
Labels: Merge On Green

#13189 Feat: Address autocomplete input for new shipping route
  src/Apps/Order/Routes/Shipping2/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Components/Address/AddressAutocompleteInput.tsx
  src/Components/Address/__tests__/AddressAutocompleteInput.jest.tsx
  src/Components/Address/useAddressAutocomplete.ts
Labels: Jira Synced

#13211 fix(system): Dont clear relay cache after mutations -> speed up logged in experience
  src/Apps/Auction/auctionRoutes.tsx
  src/Apps/Settings/settingsRoutes.tsx
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Components/FollowButton/FollowGeneButton.tsx
  src/Components/FollowButton/FollowProfileButton.tsx
  src/System/Relay/createRelaySSREnvironment.ts
Labels: Merge On Green

#13212 Revert "fix(system): Dont clear relay cache after mutations -> speed up logged in experience"
  src/Apps/Auction/auctionRoutes.tsx
  src/Apps/Settings/settingsRoutes.tsx
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Components/FollowButton/FollowGeneButton.tsx
  src/Components/FollowButton/FollowProfileButton.tsx
  src/System/Relay/createRelaySSREnvironment.ts
Labels: Merge On Green

#13202 test: migrate alert provider specs to React Testing Library
  src/Components/Alert/Hooks/__tests__/AlertProvider.jest.tsx
  src/Components/Alert/Hooks/__tests__/Utils/AlertProviderTestPage.tsx
Labels: Jira Synced

#13170 feat: Allow multiple artist IDs for Alert price histogram
  src/Components/Alert/Components/Filters/Price.tsx
  src/__generated__/PriceAggregationsQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#13215 feat: allow routing to edit panel of alerts app
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormDesktop.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
  src/Apps/Settings/settingsRoutes.tsx
  src/__generated__/SavedSearchAlertsApp_Alert_Query.graphql.ts
  src/__generated__/settingsRoutes_SavedSearchAlertsAppEditQuery.graphql.ts
Labels: Jira Synced

#13183 feat(ONYX-529): create new alert modal, add sticky modal headers and refactor
  src/Components/Alert/AlertProvider.tsx
  src/Components/Alert/Components/CreateAlertButton.tsx
  src/Components/Alert/Components/Filters/QuickMultipleSelectAlertFilter.tsx
  src/Components/Alert/Components/Modal.tsx
  src/Components/Alert/Components/Modal/Modal.tsx
  src/Components/Alert/Components/Modal/ModalContent.tsx
  src/Components/Alert/Components/Modal/ModalHeader.tsx
  src/Components/Alert/Components/Steps/Confirmation.tsx
  src/Components/Alert/Components/Steps/Details.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
  src/Components/Alert/Components/Steps/StepsFooter/FiltersFooter.tsx
  src/Components/Alert/Components/Steps/StepsHeader/ConfirmationHeader.tsx
  src/Components/Alert/Components/Steps/StepsHeader/FiltersHeader.tsx
Labels: Jira Synced

#13218 feat: add artist series horizontal filter
  src/Components/ArtworkFilter/ArtworkFiltersQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/ArtistSeriesFilterQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/__tests__/ArtistSeriesFilterQuick.jest.tsx
Labels: Jira Synced
