Repository artsy/force, pull requests merged in 2023-08, with the labels that each got.

#12673 fix: do not proceed automatically after choosing a verified address
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Components/AddressForm.tsx
Labels: Jira Synced

#12679 fix(artist): specifically links to artist auction results index and labels link
  src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResult.tsx
Labels: Jira Synced

#12677 feat: add verified representatives to Artist header
  src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistHeader2_artist.graphql.ts
  src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts
Labels: Jira Synced

#12685 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
  src/__generated__/ArtistCareerHighlights_artist.graphql.ts
  src/__generated__/ArtistHeader2_artist.graphql.ts
  src/__generated__/ArtistInsightBadges_Test_Query.graphql.ts
  src/__generated__/ArtistInsightBadges_artist.graphql.ts
Labels: Squash On Green

#12690 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
  src/__generated__/ArtistCareerHighlights_artist.graphql.ts
  src/__generated__/ArtistHeader2_artist.graphql.ts
  src/__generated__/ArtistInsightBadges_Test_Query.graphql.ts
  src/__generated__/ArtistInsightBadges_artist.graphql.ts
Labels: Squash On Green

#12692 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12676 fix(onyx-158): Hide See all matching works button on alerts confirmation step when <= 10 artworks match criteria
  src/Components/SavedSearchAlert/Components/ConfirmationStepFooter.tsx
  src/Components/SavedSearchAlert/Components/__tests__/ConfirmationStepFooter.jest.tsx
  src/Components/SavedSearchAlert/ConfirmationArtworksGrid.tsx
  src/Components/SavedSearchAlert/ConfirmationStepModal.tsx
Labels: Jira Synced

#12693 fix(ONYX-128): update Create Alert button with icon and add grid layout
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlertButton.tsx
Labels: Jira Synced

#12694 chore(hot-reloading): Bump related libs to latest
  package.json
  yarn.lock
Labels: Squash On Green

#12697 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12699 feat(artist): adds dedicated empty state
  src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistWorksForSaleEmpty.tsx
  src/__generated__/ArtistWorksForSaleEmpty_artist.graphql.ts
  src/__generated__/ArtistWorksForSaleRoute_artist.graphql.ts
  src/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
Labels: Jira Synced

#12704 fix: display the price filter for all users
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
Labels: Merge On Green, Jira Synced

#12712 chore(deps): bumps palette
  package.json
  src/Apps/Conversation/Components/OrderModal.tsx
  src/Apps/Order/Components/AddressModal.tsx
  yarn.lock
Labels: Merge On Green

#12717 feat(ONYX-129): add available works copy and tooltip
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertTooltip.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/ArtworkAuctionCreateAlertHeader.jest.tsx
  src/__generated__/ArtworkAuctionCreateAlertHeader_Test_Query.graphql.ts
  src/__generated__/ArtworkAuctionCreateAlertHeader_artwork.graphql.ts
  src/__generated__/ArtworkAuctionCreateAlertTooltip_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#12724 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistAuctionResultsRoute_artist.graphql.ts
  src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
Labels: Squash On Green

#12695 feat(onyx-131): Suggested artworks modal
  docs/best_practices.md
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertTooltip.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksButton.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksModal.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksModalFooter.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksModalGrid.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksModalHeader.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/ArtworkAuctionCreateAlertHeader.jest.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/ArtworkAuctionCreateAlertTooltip.jest.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksModal.jest.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksModalGrid.jest.tsx
  src/Components/SavedSearchAlert/ConfirmationArtworksGrid.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertContext.tsx
  src/Components/SavedSearchAlert/Utils/savedSearchCriteria.tsx
  src/DevTools/setupTestWrapper.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/ArtworkAuctionCreateAlertHeader_Test_Query.graphql.ts
  src/__generated__/ArtworkAuctionCreateAlertHeader_artwork.graphql.ts
  src/__generated__/ArtworkAuctionCreateAlertTooltip_artwork.graphql.ts
  src/__generated__/SuggestedArtworksModalGridQuery.graphql.ts
  src/__generated__/SuggestedArtworksModalGrid_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#12723 feat: handle gravity errors in metaphysics verify address query resolver
  data/schema.graphql
  src/Apps/Order/Components/AddressVerificationFlow.tsx
  src/Apps/Order/Components/__tests__/AddressVerificationFlow.jest.tsx
  src/__generated__/AddressVerificationFlowQuery.graphql.ts
  src/__generated__/AddressVerificationFlow_Test_Query.graphql.ts
  src/__generated__/AddressVerificationFlow_verifyAddress.graphql.ts
Labels: Jira Synced, Do not merge

#12726 chore(ONYX-137): Remove "Recommended" artwork grid sort on show/booth pages
  src/Apps/Show/Components/ShowArtworks.tsx
Labels: Jira Synced

#12721 feat(artist): feature flags new artwork filter layout
  src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx
  src/Components/ArtworkFilter/ArtworkFilterDrawer.tsx
  src/Components/ArtworkFilter/ArtworkFilters/ArtworkSortFilter2.tsx
  src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/Components/ArtworkFilter/index.tsx
Labels: Jira Synced

#12728 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12720 fix(EMI-1392): address verification flow tracking spec audit
  src/Apps/Order/Components/AddressVerificationFlow.tsx
  src/Apps/Order/Components/__tests__/AddressVerificationFlow.jest.tsx
Labels: Jira Synced

#12727 Deploy
  data/schema.graphql
  src/Apps/Order/Components/AddressVerificationFlow.tsx
  src/Apps/Order/Components/__tests__/AddressVerificationFlow.jest.tsx
  src/Apps/Search/Routes/SearchResultsArtworks.tsx
  src/Apps/Show/Components/ShowArtworks.tsx
  src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx
  src/Components/ArtworkFilter/ArtworkFilterDrawer.tsx
  src/Components/ArtworkFilter/ArtworkFilters/ArtworkSortFilter2.tsx
  src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/Components/ArtworkFilter/index.tsx
  src/__generated__/AddressVerificationFlowQuery.graphql.ts
  src/__generated__/AddressVerificationFlow_Test_Query.graphql.ts
  src/__generated__/AddressVerificationFlow_verifyAddress.graphql.ts
Labels: Jira Synced

#12730 chore: bump loader-utils
  yarn.lock
Labels: Jira Synced

#12729 fix(EMI-1383): style error modal background color
  src/Apps/Order/Components/AddressVerificationFlow.tsx
Labels: Jira Synced

#12732 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12733 fix: preserve suggested address after editing
  src/Components/AddressForm.tsx
  src/Components/__tests__/AddressForm.jest.tsx
Labels: Jira Synced

#12725 feat: add currency filter for PriceDB
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultsRoute.tsx
  src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/CurrencyFilter.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/PriceRangeFilter.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/Apps/Artist/Utils/allowedAuctionResultFilters.ts
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResultsRoute_artist.graphql.ts
  src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
Labels: Jira Synced

#12737 feat(filters): mobile filter updates
  src/Apps/Artist/ArtistApp.tsx
  src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx
  src/Components/ArtworkFilter/ArtworkFilterDrawer.tsx
  src/Components/ArtworkFilter/ArtworkFilterMobileOverlay.tsx
  src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/Components/ArtworkFilter/__tests__/ArtworkFilterMobileOverlay.jest.tsx
  src/Components/ArtworkFilter/index.tsx
Labels: Jira Synced

#12680 feat(progressive-onboarding): adds popover for create alert artwork sidebar
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlertButton.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertCreateSimple.tsx
Labels: Jira Synced

#12702 docs: update readme
  README.md
Labels: Jira Synced

#12734 feat: move keyword search to filters area
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/KeywordFilter.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionResultsControls.tsx
Labels: Jira Synced

#12739 fix(artist): triggers 2x2 layout at a wider breakpoint
  src/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx
Labels: Jira Synced

#12735 feat(EMI-1282): update PaymentContent copy
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/__tests__/Payment.jest.tsx
Labels: Jira Synced

#12742 chore: bump body-parser
  package.json
  yarn.lock
Labels: Jira Synced

#12746 fix: add spacing for Market Stats for mobile view
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx
Labels: Jira Synced

#12752 fix: prevents malicious hrefs
  src/System/Router/RouterLink.tsx
  src/System/Router/__tests__/RouterLink.jest.tsx
  src/Utils/__tests__/sanitizeURL.jest.ts
  src/Utils/sanitizeURL.ts
Labels: Merge On Green, Jira Synced

#12754 Revert "fix: prevents malicious hrefs"
  src/System/Router/RouterLink.tsx
  src/System/Router/__tests__/RouterLink.jest.tsx
  src/Utils/__tests__/sanitizeURL.jest.ts
  src/Utils/sanitizeURL.ts
Labels: Merge On Green

#12750 chore(DIA-64): Update curated collections in nav
  src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
  src/Components/NavBar/menuData.ts
Labels: Jira Synced

#12748 feat(ONYX-130): add shelf for suggested artworks
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksShelf.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksShelf.jest.tsx
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelf_Test_Query.graphql.ts
Labels: Jira Synced

#12757 fix(DIA-64): Incorrect copy
  src/Components/NavBar/menuData.ts
Labels: Jira Synced

#12745 fix: Extra save & continue click investigation fix
  src/Apps/Order/Components/AddressVerificationFlow.tsx
  src/Apps/Order/Components/__tests__/AddressVerificationFlow.jest.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
Labels: Jira Synced

#12758 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12688 feat: show error message when setting payment by setup intent fails (EMI-1284)
  src/Apps/Order/Dialogs.tsx
  src/Apps/Order/Hooks/__tests__/useStripePaymentBySetupIntentId.jest.tsx
  src/Apps/Order/Hooks/useStripePaymentBySetupIntentId.tsx
  src/Apps/Order/Routes/Payment/index.tsx
Labels: Jira Synced

#12756 Deploy
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksShelf.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksShelf.jest.tsx
  src/Apps/Order/Components/AddressVerificationFlow.tsx
  src/Apps/Order/Components/__tests__/AddressVerificationFlow.jest.tsx
  src/Apps/Order/Dialogs.tsx
  src/Apps/Order/Hooks/__tests__/useStripePaymentBySetupIntentId.jest.tsx
  src/Apps/Order/Hooks/useStripePaymentBySetupIntentId.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
  src/Components/NavBar/menuData.ts
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelf_Test_Query.graphql.ts
Labels: Jira Synced

#12759 fix(DIA-117): fixes 'quick navigation' links in safari; search clean up
  .eslintrc.js
  package.json
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/__tests__/NavBar.jest.tsx
  src/Components/Search/NewSearch/Mobile/Overlay.tsx
  src/Components/Search/NewSearch/Mobile/SearchResultsList.tsx
  src/Components/Search/NewSearch/SearchBar.tsx
  src/Components/Search/NewSearch/SearchBarFooter.tsx
  src/Components/Search/NewSearch/SearchBarInput.tsx
  src/Components/Search/NewSearch/SearchInputPills.tsx
  src/Components/Search/NewSearch/SuggestionItem/DefaultSuggestion.tsx
  src/Components/Search/NewSearch/SuggestionItem/NewSearchBarSuggestion.tsx
  src/Components/Search/NewSearch/SuggestionItem/NewSuggestionItem.tsx
  src/Components/Search/NewSearch/SuggestionItem/QuickNavigation.tsx
  src/Components/Search/NewSearch/SuggestionItem/QuickNavigationItem.tsx
  src/Components/Search/NewSearch/SuggestionItem/SuggestionItem.tsx
  src/Components/Search/NewSearch/utils/formatOptions.ts
  src/Components/Search/SearchBar.tsx
  src/Components/Search/Suggestions/SuggestionItem.tsx
  src/Components/Search/__tests__/SearchBar.jest.tsx
  src/__generated__/MobileSearchBarSuggestQuery.graphql.ts
  src/__generated__/NewSearchBarInputRefetchQuery.graphql.ts
  src/__generated__/NewSearchBarInputSuggestQuery.graphql.ts
  src/__generated__/NewSearchBarInput_viewer.graphql.ts
  src/__generated__/OverlayRefetchQuery.graphql.ts
  src/__generated__/Overlay_viewer.graphql.ts
  src/__generated__/SearchBarInputRefetchQuery.graphql.ts
  src/__generated__/SearchBarInputSuggestQuery.graphql.ts
  src/__generated__/SearchBarInput_viewer.graphql.ts
  src/__generated__/SearchBarRefetchQuery.graphql.ts
  src/__generated__/SearchInputPills_viewer.graphql.ts
  yarn.lock
Labels: Jira Synced

#12761 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistAuctionResultsRoute_artist.graphql.ts
  src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
Labels: Squash On Green

#12763 fix(onyx): update copy and placeholder for Auction create alert header
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertTooltip.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksShelf.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/ArtworkAuctionCreateAlertTooltip.jest.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#12765 fix(DIA-102): sanitize back hrefs
  src/Apps/Auction/Components/RegisterButton.tsx
  src/System/Router/RouterLink.tsx
  src/System/Router/__tests__/RouterLink.jest.tsx
  src/Utils/__tests__/sanitizeURL.jest.ts
  src/Utils/sanitizeURL.ts
Labels: Jira Synced

#12766 Revert "fix(DIA-102): sanitize back hrefs"
  src/Apps/Auction/Components/RegisterButton.tsx
  src/System/Router/RouterLink.tsx
  src/System/Router/__tests__/RouterLink.jest.tsx
  src/Utils/__tests__/sanitizeURL.jest.ts
  src/Utils/sanitizeURL.ts
Labels: Merge On Green, Jira Synced

#12767 fix: prevents non url back links
  src/Apps/Artist/Components/ArtistBackLink.tsx
  src/Apps/Show/Components/BackToFairBanner.tsx
  src/Utils/__tests__/sanitizeURL.jest.ts
  src/Utils/sanitizeURL.ts
Labels: Merge On Green, Jira Synced

#12768 Update artist header with verified rep change
  data/schema.graphql
  src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistHeader2_artist.graphql.ts
  src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts
Labels: Merge On Green

#12770 fix(artist): removes verified reps for time being
  src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistHeader2_artist.graphql.ts
  src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts
Labels: Merge On Green

#12772 fix(DIA-64): Fixes incorrect nav route
  src/Components/NavBar/menuData.ts
Labels: Jira Synced, Squash On Green

#12771 Deploy
  src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx
  src/Components/NavBar/menuData.ts
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistHeader2_artist.graphql.ts
  src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts
Labels: Jira Synced

#12773 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12780 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12781 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12782 fix(ONYX-270): update responsive spacing and fontsize
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksShelf.tsx
Labels: Jira Synced

#12783 feat(onyx-267): Hide suggested artworks section if there are no suggested artworks
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/ArtworkAuctionCreateAlertHeader.jest.tsx
  src/__generated__/ArtworkAuctionCreateAlertHeader_Test_Query.graphql.ts
  src/__generated__/ArtworkAuctionCreateAlertHeader_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#12784 fix(ONYX-270): update skeleton with height and overflow
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksShelf.tsx
Labels: Jira Synced

#12792 fix: Update Partners filter correctly on route change
  src/Components/ArtworkFilter/index.tsx
Labels: Jira Synced

#12778 chore: Tracking corrections, refactor address verification flow
  src/Apps/Order/Components/AddressVerificationFlow.tsx
  src/Apps/Order/Components/__tests__/AddressVerificationFlow.jest.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
Labels: Jira Synced

#12793 fix(auth): threads through analytics options after social login/sign up
  src/Components/AuthDialog/AuthDialogContext.tsx
  src/Components/AuthDialog/Components/AuthDialogSocial.tsx
  src/Components/AuthDialog/Hooks/__tests__/useSocialAuthTracking.jest.ts
  src/Components/AuthDialog/Hooks/useAuthDialogTracking.ts
  src/Components/AuthDialog/Hooks/useSocialAuthTracking.ts
Labels: Jira Synced

#12762 feat: add sale end year filter
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultsRoute.tsx
  src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/SaleEndYearFilter.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/Apps/Artist/Utils/allowedAuctionResultFilters.ts
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResultsRoute_artist.graphql.ts
  src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
Labels: Jira Synced

#12751 feat(alerts): use generated displayName in create and edit forms
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCreateArtworkAlert.jest.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/CreateArtworkAlertSection.jest.tsx
  src/Components/SavedSearchAlert/Components/SavedSearchAlertNameInput.tsx
  src/Components/SavedSearchAlert/Components/__tests__/SavedSearchAlertNameInput.jest.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
  src/__generated__/SavedSearchAlertNameInputQuery.graphql.ts
  src/__generated__/SavedSearchAlertNameInput_Test_Query.graphql.ts
  src/__generated__/SavedSearchAlertNameInput_previewSavedSearch.graphql.ts
Labels: Jira Synced

#12797 Revert "chore(deps): update dep typescript from 4.7.4 to v4.9.5"
  package.json
  yarn.lock
Labels: Merge On Green

#12798 fix(dia-10): uses auction lots status instead of count for rendering empty state
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistWorksForSaleEmpty.tsx
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
Labels: Merge On Green, Jira Synced

#12800 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12804 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12801 Fix broken help article link
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
Labels: Jira Synced

#12806 fix: Use new generated default name in alert edit form
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx
Labels: Jira Synced

#12803 feat: report currency not supported (EMI-1328)
  src/Apps/Order/Dialogs.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitOrder.ts
  src/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/Apps/Order/Utils/__tests__/getErrorDialogCopy.jest.tsx
  src/Apps/Order/Utils/getErrorDialogCopy.tsx
Labels: Jira Synced

#12807 fix(dia-103): ensures top context bar only links to internal routes
  src/Apps/Consign/Routes/ConsignmentInquiry/ConsignmentInquiry.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/__tests__/ConsignmentInquiry.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Components/TopContextBar.tsx
  src/Utils/__tests__/sanitizeURL.jest.ts
  src/Utils/sanitizeURL.ts
Labels: Jira Synced

#12809 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12810 feat: report destination_could_not_be_geocoded error (EMI-1332)
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/setOrderShipping.ts
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/Apps/Order/Utils/getErrorDialogCopy.tsx
Labels: Jira Synced

#12812 fix(ONYX-274): update copy for title and sugested artworks modal
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksModal.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksModalHeader.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksModal.jest.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#12808 Deploy
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksModal.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksModalHeader.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksModal.jest.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/ConsignmentInquiry.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/__tests__/ConsignmentInquiry.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/Order/Dialogs.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/setOrderShipping.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitOrder.ts
  src/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/Apps/Order/Utils/__tests__/getErrorDialogCopy.jest.tsx
  src/Apps/Order/Utils/getErrorDialogCopy.tsx
  src/Components/TopContextBar.tsx
  src/System/i18n/locales/en-US/translation.json
  src/Utils/__tests__/sanitizeURL.jest.ts
  src/Utils/sanitizeURL.ts
Labels: Jira Synced

#12813 fix: Alert edit form scroll bug
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
Labels: Jira Synced

#12815 Deploy
  package.json
  src/Apps/Artist/Utils/allowedAuctionResultFilters.ts
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkCreateAlertButton.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBiddingClosedMessage.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/__generated__/ArtworkAuctionCreateAlertHeader_Test_Query.graphql.ts
  src/__generated__/ArtworkAuctionCreateAlertHeader_artwork.graphql.ts
  src/__generated__/ArtworkCreateAlertButton_artwork.graphql.ts
  src/__generated__/ArtworkSidebarAuctionInfoPollingQuery.graphql.ts
  src/__generated__/ArtworkSidebarBiddingClosedMessage_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCurrentBidInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#12820 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12822 chore(analytics): add contextModule to ShelfArtwork used in closed lot header
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksShelf.tsx
Labels: Jira Synced
