Repository artsy/force, pull requests merged in 2023-02, with the labels that each got.

#11859 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11860 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11861 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11863 fix: make short description optional
  src/Apps/Order/Components/ItemReview.tsx
Labels: Jira Synced, Squash On Green

#11867 refactor: item review component for checkout review step
  src/Apps/Order/Components/ItemReview.tsx
  src/__generated__/ItemReview_lineItem.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#11862 Deploy
  data/schema.graphql
  package.json
  src/Apps/Order/Components/ItemReview.tsx
  src/Components/NavBar/NavBarLoggedInActions.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotifications.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotificationsIndicator.tsx
  src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenuNotificationsIndicator.jest.tsx
  src/Components/Notifications/Mutations/markNotificationsAsSeen.ts
  src/Components/Notifications/Notifications.tsx
  src/__generated__/ItemReview_lineItem.graphql.ts
  src/__generated__/NavBarLoggedInActionsQuery.graphql.ts
  src/__generated__/NavBarMobileMenuNotificationsIndicatorQuery.graphql.ts
  src/__generated__/NavBarMobileMenuNotificationsIndicator_me.graphql.ts
  src/__generated__/NavBarMobileMenuNotificationsIndicator_test_Query.graphql.ts
  src/__generated__/NavBarMobileMenuNotificationsQuery.graphql.ts
  src/__generated__/NavBarMobileMenuNotifications_me.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/markNotificationsAsSeenMutation.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#11866 feat(auth): tracks social logins
  scripts/smoke_test.sh
  src/Apps/Authentication/__tests__/authenticationRoutes.jest.tsx
  src/Apps/Components/AppShell.tsx
  src/Apps/Components/__tests__/AppShell.jest.tsx
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsLinkedAccounts.tsx
  src/Components/AuthDialog/Components/AuthDialogSocial.tsx
  src/Components/AuthDialog/Hooks/__tests__/useSocialAuthTracking.jest.ts
  src/Components/AuthDialog/Hooks/useAfterAuthenticationRedirectUrl.ts
  src/Components/AuthDialog/Hooks/useAuthDialogTracking.ts
  src/Components/AuthDialog/Hooks/useSocialAuthTracking.ts
  src/Components/AuthDialog/Views/__tests__/AuthDialogForgotPassword.jest.tsx
  src/System/Router/__tests__/buildServerApp.jest.tsx
  src/Utils/Hooks/useAuthIntent/__tests__/useAuthIntent.jest.ts
  src/Utils/Hooks/useAuthIntent/index.tsx
Labels: Merge On Green, Jira Synced

#11871 fix(auth): adds data-attrs for integrity
  src/Components/AuthDialog/Views/AuthDialogForgotPassword.tsx
  src/Components/AuthDialog/Views/AuthDialogLogin.tsx
Labels: Merge On Green

#11872 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11868 fix: Clear local images when navigating back in artwork form
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormContext.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
  src/Utils/localImageHelpers.ts
Labels: Jira Synced

#11877 fix: Add index to local images
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormContext.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormImages.tsx
Labels: Jira Synced, Squash On Green

#11880 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11881 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11846 feat(FX-4526): Create component for Saves and Wishlist rail
  src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/FourUpImageLayout.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesItem.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/StackedImageLayout.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/FourUpImageLayout.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/SavesItem.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/StackedImageLayout.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Utils/__tests__/prepareImageURLs.jest.ts
  src/Apps/CollectorProfile/Routes/Saves2/Utils/prepareImageURLs.ts
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/__generated__/CollectorProfileSaves2Route_me.graphql.ts
  src/__generated__/SavesItem_item.graphql.ts
  src/__generated__/SavesItem_test_Query.graphql.ts
  src/__generated__/collectorProfileRoutes_Saves2Query.graphql.ts
Labels: Jira Synced

#11884 Feat(CX-3361): redesign the swa landing page part 1
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/DollarCircleIcon.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Highlights.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PlanetCircleIcon.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/StarCircleIcon.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HeaderSWA.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
Labels: Jira Synced

#11885 Feat(CX-3366): redesign the swa landing page part 2
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HowItWorksSteps.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
Labels: Jira Synced

#11883 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11895 chore: correctly display image placeholders for saves/wishlist
  src/Apps/CollectorProfile/Routes/Saves2/Components/FourUpImageLayout.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/StackedImageLayout.tsx
Labels: Jira Synced, Squash On Green

#11889 feat(CX-3363): remove the Talk to Specialists page link from the footer
  src/Components/Footer/Footer.tsx
Labels: Jira Synced, Squash On Green

#11886 Feat(CX-3373): Collector Profile breadcrumb in Settings
  src/Apps/Settings/SettingsApp.tsx
Labels: Jira Synced

#11892 feat(TX-1038): Additional artwork details for private sales
  src/Apps/Order/Components/AdditionalArtworkDetails.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__tests__/Payment.jest.tsx
  src/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/AdditionalArtworkDetails_order.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/Payment_order.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/Review_order.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#11899 Deploy
  cypress/e2e/alerts.cy.ts
  cypress/e2e/consign.cy.ts
  cypress/e2e/notifications.cy.ts
  cypress/e2e/partnerProfile.cy.js
  cypress/e2e/userPayments.cy.js
  cypress/e2e/userShipping.cy.js
  data/schema.graphql
  src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/FourUpImageLayout.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesItem.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/StackedImageLayout.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/FourUpImageLayout.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/SavesItem.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/StackedImageLayout.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Utils/__tests__/prepareImageURLs.jest.ts
  src/Apps/CollectorProfile/Routes/Saves2/Utils/prepareImageURLs.ts
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/DollarCircleIcon.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Highlights.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PlanetCircleIcon.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/StarCircleIcon.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HeaderSWA.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HowItWorksSteps.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/Apps/Order/Components/AdditionalArtworkDetails.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__tests__/Payment.jest.tsx
  src/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/Apps/Settings/SettingsApp.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/Components/Footer/Footer.tsx
  src/__generated__/AdditionalArtworkDetails_order.graphql.ts
  src/__generated__/CollectorProfileSaves2Route_me.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/Payment_order.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/Review_order.graphql.ts
  src/__generated__/SavesItem_item.graphql.ts
  src/__generated__/SavesItem_test_Query.graphql.ts
  src/__generated__/collectorProfileRoutes_Saves2Query.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
Labels: Jira Synced

#11882 feat(TX-1033): add conditional title for wire transfer
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/__tests__/Payment.jest.tsx
Labels: Jira Synced, Squash On Green

#11890 fix(FX-4601): Do not display +n text in activity panel for non-artwork-based notifications
  src/Components/Notifications/NotificationItem.tsx
  src/Components/Notifications/__tests__/NotificationItem.jest.tsx
  src/Components/Notifications/util.ts
Labels: Jira Synced

#11894 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11897 fix(GRO-1535): removes column headers hack
  src/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtistList.tsx
Labels: Merge On Green, Jira Synced

#11903 fix(jobs): removes redundant location for leadgen category
  src/Apps/Jobs/Components/JobLink.tsx
  src/Apps/Jobs/Components/JobsFilter.tsx
Labels: Merge On Green

#11904 chore: restore smoke scripts
  scripts/smoke_test.sh
Labels: Merge On Green

#11896 fix(GRO-1301): Fixes redirect for social sign ups
  src/Apps/Authentication/Legacy/Server/__tests__/checkForRedirect.jest.ts
  src/Apps/Authentication/Legacy/Server/checkForRedirect.ts
  src/Components/AuthDialog/Components/AuthDialogSocial.tsx
  src/Utils/__tests__/sanitizeRedirect.jest.ts
Labels: Merge On Green, Jira Synced

#11853 feat: add art quiz as an onboarding reward screen
  src/Components/Onboarding/Components/OnboardingDebug.tsx
  src/Components/Onboarding/Components/OnboardingSteps.tsx
  src/Components/Onboarding/Hooks/useOnboardingContext.tsx
  src/Components/Onboarding/Views/OnboardingQuestionOne.tsx
  src/Components/Onboarding/Views/OnboardingQuestionThree.tsx
  src/Components/Onboarding/Views/OnboardingThankYou.tsx
  src/Components/Onboarding/config.ts
Labels: Jira Synced

#11907 fix(art-quiz): prevents squashed buttons and short screen overflows
  src/Apps/ArtQuiz/Components/ArtQuizFullscreen.tsx
  src/Apps/ArtQuiz/Routes/ArtQuizWelcome.tsx
Labels: Merge On Green

#11908 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11909 fix: Adjust cleanLocalImages logic
  src/Utils/localImageHelpers.ts
Labels: Squash On Green

#11911 fix: Hide size for automatically added photos in MyC form
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Components/PhotoUpload/Components/PhotoThumbnail.tsx
  src/Components/PhotoUpload/Utils/fileUtils.ts
Labels: Jira Synced

#11916 feat(CX-3373): Rm extra spacing
  src/Apps/Settings/SettingsApp.tsx
Labels: Jira Synced

#11913 Feat(CX-3370): redesign the swa landing page part 6
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FAQSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Reviews.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/FAQSWA.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Footer.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/Components/HeroCarousel/HeroCarousel.story.tsx
  src/Components/HeroCarousel/HeroCarousel.tsx
  src/Components/HeroCarousel/HeroCarouselLarge.tsx
  src/Components/HeroCarousel/HeroCarouselSmall.tsx
Labels: Jira Synced

#11917 feat(TX-1042): use artwork version date and dimensions in checkout
  .secrets.baseline
  src/Apps/Order/Components/ArtworkSummaryItem.tsx
  src/Apps/Order/Components/ItemReview.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/ArtworkSummaryItem_order.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/ItemReview_lineItem.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/RejectTestQuery.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/__generated__/orderRoutes_RejectQuery.graphql.ts
  src/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/orderRoutes_StatusQuery.graphql.ts
Labels: Jira Synced

#11918 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11912 Deploy
  .secrets.baseline
  README.md
  data/schema.graphql
  src/Apps/ArtQuiz/Components/ArtQuizResultsRecommendedArtworks.tsx
  src/Apps/Components/AppShell.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FAQSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Reviews.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/FAQSWA.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Footer.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Apps/Order/Components/ArtworkSummaryItem.tsx
  src/Apps/Order/Components/ItemReview.tsx
  src/Apps/Settings/SettingsApp.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/Components/AuthDialog/AuthDialog.tsx
  src/Components/AuthDialog/Hooks/useCountryCode.ts
  src/Components/AuthDialog/Views/AuthDialogSignUp.tsx
  src/Components/HeroCarousel/HeroCarousel.story.tsx
  src/Components/HeroCarousel/HeroCarousel.tsx
  src/Components/HeroCarousel/HeroCarouselLarge.tsx
  src/Components/HeroCarousel/HeroCarouselSmall.tsx
  src/Components/PhotoUpload/Components/PhotoThumbnail.tsx
  src/Components/PhotoUpload/Utils/fileUtils.ts
  src/Utils/Hooks/__tests__/useClientQuery.jest.ts
  src/Utils/Hooks/useClientQuery.ts
  src/Utils/Hooks/useSetupAuth.ts
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/ArtworkSummaryItem_order.graphql.ts
  src/__generated__/AuthDialogSignUp_requestLocation.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/ItemReview_lineItem.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/RejectTestQuery.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/__generated__/orderRoutes_RejectQuery.graphql.ts
  src/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/orderRoutes_StatusQuery.graphql.ts
  src/__generated__/useClientQueryTestQuery.graphql.ts
  src/__generated__/useCountryCodeQuery.graphql.ts
Labels: Jira Synced

#11921 feat(TX-1053): Get versioned artwork image
  src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
  src/Apps/Settings/Routes/Purchases/Components/__tests__/SettingsPurchases.jest.tsx
  src/__generated__/SettingsPurchasesQuery.graphql.ts
  src/__generated__/SettingsPurchasesRow_order.graphql.ts
  src/__generated__/SettingsPurchases_Test_Query.graphql.ts
  src/__generated__/settingsRoutes_PurchasesRouteQuery.graphql.ts
Labels: Jira Synced

#11919 fix(FX-4572): contact gallery button artwork page
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarPartnerInfo.jest.tsx
  src/__generated__/ArtworkSidebarPartnerInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarPartnerInfo_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#11924 fix(onboarding): fixes responsive styling
  src/Apps/ArtQuiz/Components/ArtQuizResultsLoader.tsx
  src/Apps/ArtQuiz/Routes/ArtQuizWelcome.tsx
  src/Components/Onboarding/Components/OnboardingModal.tsx
  src/Components/Onboarding/Hooks/useOnboarding.tsx
  src/Components/Onboarding/Views/OnboardingWelcome.tsx
  src/Components/SplitLayout.tsx
Labels: Merge On Green, Jira Synced

#11923 Feat(CX-3368): redesign the swa landing page part 4
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/CollectorsOverview.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
Labels: Jira Synced

#11922 Deploy
  src/Apps/ArtQuiz/Components/ArtQuizResultsLoader.tsx
  src/Apps/ArtQuiz/Routes/ArtQuizWelcome.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarPartnerInfo.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/CollectorsOverview.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
  src/Apps/Settings/Routes/Purchases/Components/__tests__/SettingsPurchases.jest.tsx
  src/Components/Onboarding/Components/OnboardingModal.tsx
  src/Components/Onboarding/Hooks/useOnboarding.tsx
  src/Components/Onboarding/Views/OnboardingWelcome.tsx
  src/Components/SplitLayout.tsx
  src/__generated__/ArtworkSidebarPartnerInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarPartnerInfo_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/SettingsPurchasesQuery.graphql.ts
  src/__generated__/SettingsPurchasesRow_order.graphql.ts
  src/__generated__/SettingsPurchases_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/settingsRoutes_PurchasesRouteQuery.graphql.ts
Labels: Jira Synced

#11925 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11927 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11928 feat(TX-1058): order app logo redirects to home page
  src/Apps/Order/OrderApp.tsx
  src/Apps/Order/__tests__/OrderApp.jest.tsx
Labels: Jira Synced

#11933 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useCreateArtworkMutation.graphql.ts
  src/__generated__/useUpdateArtworkMutation.graphql.ts
Labels: Squash On Green

#11930 feat(TX-1067): Wire instructions update
  src/Apps/Order/Routes/__tests__/Status.jest.tsx
  src/Apps/Order/Utils/getStatusCopy.tsx
Labels: Jira Synced

#11914 feat(PRO-57): update routing logic for offers
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarPartnerInfo.jest.tsx
  src/Apps/Conversation/Components/Conversation.tsx
  src/Apps/Conversation/Components/ConversationCTA.tsx
  src/Apps/Conversation/Components/EditionSelectBox.tsx
  src/Apps/Conversation/Components/MakeOfferOnInquiryButton.tsx
  src/Apps/Conversation/Components/__tests__/ConfirmArtwork.jest.tsx
  src/Apps/Conversation/Components/__tests__/ConversationCTA.jest.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitOfferOrder.ts
  src/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/Review_order.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
Labels: Jira Synced

#11940 fix: capitalize K on sale price
  src/Apps/Artist/Routes/AuctionResults/Components/MarketStatsPlaceholder.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/MarketStats.jest.tsx
  src/Utils/__tests__/formatLargeNumber.jest.ts
  src/Utils/formatLargeNumber.ts
Labels: Jira Synced

#11937 chore:add artist link to viewing room
  .secrets.baseline
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
  src/Apps/ViewingRoom/Routes/Works/__tests__/ViewingRoomWorksRoute.jest.tsx
  src/__generated__/ViewingRoomArtworkDetails_artwork.graphql.ts
  src/__generated__/ViewingRoomWorksRoute_Test_Query.graphql.ts
  src/__generated__/viewingRoomRoutes_ViewingRoomWorksRouteQuery.graphql.ts
Labels: Jira Synced

#11935 Deploy
  .secrets.baseline
  package.json
  src/Apps/Artist/Routes/AuctionResults/Components/MarketStatsPlaceholder.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/MarketStats.jest.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarPartnerInfo.jest.tsx
  src/Apps/Conversation/Components/Conversation.tsx
  src/Apps/Conversation/Components/ConversationCTA.tsx
  src/Apps/Conversation/Components/EditionSelectBox.tsx
  src/Apps/Conversation/Components/MakeOfferOnInquiryButton.tsx
  src/Apps/Conversation/Components/__tests__/ConfirmArtwork.jest.tsx
  src/Apps/Conversation/Components/__tests__/ConversationCTA.jest.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitOfferOrder.ts
  src/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/Apps/Order/Routes/__tests__/Status.jest.tsx
  src/Apps/Order/Utils/getStatusCopy.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
  src/Apps/ViewingRoom/Routes/Works/__tests__/ViewingRoomWorksRoute.jest.tsx
  src/Utils/__tests__/formatLargeNumber.jest.ts
  src/Utils/formatLargeNumber.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/Review_order.graphql.ts
  src/__generated__/ViewingRoomArtworkDetails_artwork.graphql.ts
  src/__generated__/ViewingRoomWorksRoute_Test_Query.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/__generated__/viewingRoomRoutes_ViewingRoomWorksRouteQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#11942 Updating staffing title changes + profile pic
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
  src/Apps/Contact/ContactApp.tsx
  src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Jira Synced

#11955 fix(artists): guards against potentially null data
  src/Apps/Artists/Routes/ArtistsIndex.tsx
Labels: Merge On Green

#11944 Feat(CX-3420): MyC Artwork Page - display new field Notes
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MetadataField.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MyCollectionArtworkSidebar.jest.tsx
  src/__generated__/MyCollectionArtworkSidebarMetadata_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkSidebarTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/ViewingRoomWorksRoute_Test_Query.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
  src/__generated__/viewingRoomRoutes_ViewingRoomWorksRouteQuery.graphql.ts
Labels: Jira Synced

#11941 Feat(CX-3369): redesign the swa landing page part 5
  data/schema.graphql
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviouslySoldOnArtsyRail.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SoldArtwork.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SoldArtworkDetails.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/PreviouslySoldOnArtsyRail.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/__generated__/PreviouslySoldOnArtsyRailQuery.graphql.ts
  src/__generated__/PreviouslySoldOnArtsyRail_recentlySoldArtworks.graphql.ts
  src/__generated__/PreviouslySoldOnArtsyRail_tests_Query.graphql.ts
  src/__generated__/SoldArtworkDetails_artwork.graphql.ts
  src/__generated__/SoldArtwork_artwork.graphql.ts
Labels: Jira Synced

#11946 feat(TX-1059): Checkout flow tab navigation
  src/Apps/Order/Components/OrderRouteContainer.tsx
  src/Apps/Order/Components/OrderStepper.tsx
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/Counter/index.tsx
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Reject/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/Accept_order.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/Counter_order.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/NewPayment_order.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/Offer_order.graphql.ts
  src/__generated__/OrderStepper_order.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/Payment_order.graphql.ts
  src/__generated__/RejectTestQuery.graphql.ts
  src/__generated__/Reject_order.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/Respond_order.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/Review_order.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/Shipping_order.graphql.ts
  src/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/__generated__/orderRoutes_RejectQuery.graphql.ts
  src/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
Labels: Jira Synced

#11958 Fix(CX-3428): web mweb address latest design changes and qa comments
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/CollectorsOverview.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FAQSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FooterBanner.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Highlights.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Reviews.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpeakToTheTeam.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/TextAndImageLayout.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SpeakToTheTeam.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
Labels: Jira Synced

#11962 fix(CX-3390):hide upcoming auctions when there are no upcoming auctions in auction results
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/TableSidebar.tsx
Labels: Jira Synced

#11945 feat(FX-4551): User creates an artworks list
  src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesHeader.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/CreateNewListModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/SavesHeader.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/__tests__/CollectorProfileSaves2Route.jest.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/CreateNewListModalMutation.graphql.ts
Labels: Jira Synced

#11968 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11965 feat(TX-1016): Primitive phone number validation
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Utils/formValidators.tsx
Labels: Jira Synced

#11943 feat(artwork lists): contextual action menu + delete action
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/DeleteSavesModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/SavesContextualMenu.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/DeleteSavesModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/SavesContextualMenu.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesArtworks.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/SavesArtworks.jest.tsx
  src/Components/ContextualMenu/ContextualMenu.tsx
  src/Components/ContextualMenu/ContextualMenuItem.tsx
  src/Components/ContextualMenu/__stories__/ContextualMenu.story.tsx
  src/Components/ContextualMenu/__tests__/ContextualMenu.jest.tsx
  src/Components/ContextualMenu/index.ts
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/DeleteSavesModalMutation.graphql.ts
  src/__generated__/SavesArtworksQuery.graphql.ts
  src/__generated__/SavesArtworks_Test_Query.graphql.ts
  src/__generated__/SavesArtworks_collection.graphql.ts
Labels: Merge On Green, Jira Synced

#11974 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
  src/__generated__/ArtistHeader_Test_Query.graphql.ts
  src/__generated__/ArtistInsightBadges_Test_Query.graphql.ts
  src/__generated__/ArtistInsightBadges_artist.graphql.ts
  src/__generated__/ArtistInsightPills_Test_Query.graphql.ts
  src/__generated__/ArtistInsightPills_artist.graphql.ts
Labels: Squash On Green

#11975 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11977 fix(CX-3360): swa final adjustments
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FAQSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FooterBanner.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviouslySoldOnArtsyRail.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpeakToTheTeam.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/TextAndImageLayout.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
Labels: Jira Synced

#11979 Small refactoring of create collection modal
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal.tsx
Labels: Jira Synced

#11973 Deploy
  data/schema.graphql
  package.json
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/DeleteSavesModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/SavesContextualMenu.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/DeleteSavesModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/SavesContextualMenu.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesArtworks.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/SavesArtworks.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FAQSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FooterBanner.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviouslySoldOnArtsyRail.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpeakToTheTeam.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/TextAndImageLayout.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Utils/formValidators.tsx
  src/Components/ContextualMenu/ContextualMenu.tsx
  src/Components/ContextualMenu/ContextualMenuItem.tsx
  src/Components/ContextualMenu/__stories__/ContextualMenu.story.tsx
  src/Components/ContextualMenu/__tests__/ContextualMenu.jest.tsx
  src/Components/ContextualMenu/index.ts
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
  src/__generated__/ArtistHeader_Test_Query.graphql.ts
  src/__generated__/ArtistInsightBadges_Test_Query.graphql.ts
  src/__generated__/ArtistInsightBadges_artist.graphql.ts
  src/__generated__/ArtistInsightPills_Test_Query.graphql.ts
  src/__generated__/ArtistInsightPills_artist.graphql.ts
  src/__generated__/DeleteSavesModalMutation.graphql.ts
  src/__generated__/SavesArtworksQuery.graphql.ts
  src/__generated__/SavesArtworks_Test_Query.graphql.ts
  src/__generated__/SavesArtworks_collection.graphql.ts
  yarn.lock
Labels: Jira Synced

#11984 feat(script): Add `yarn dead-code` script
  package.json
  scripts/better.js
  scripts/check-dead-code.sh
Labels: Merge On Green

#11989 chore: update the copy of Additional Conditions of Sale for the private sales
  src/Apps/Order/Components/BuyerGuarantee.tsx
  src/Apps/Order/Components/ConditionsOfSaleDisclaimer.tsx
  src/Apps/Order/Components/__tests__/BuyerGuarantee.jest.tsx
  src/Apps/Order/Routes/__tests__/Review.jest.tsx
Labels: Jira Synced

#11954 feat(FX-4590): Select lists for this artwork modal - connect backend
  src/Apps/CollectorProfile/Routes/Saves2/Components/FourUpImageLayout.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesArtworkSaveButton.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SavesNoImage.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListItem.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkFooter.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkHeader.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkImage.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkPlaceholders.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/__tests__/SelectListsForArtworkModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/StackedImageLayout.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Utils/__tests__/getSelectedCollectionIds.jest.ts
  src/Apps/CollectorProfile/Routes/Saves2/Utils/getSelectedCollectionIds.ts
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/SelectListItem_item.graphql.ts
  src/__generated__/SelectListsForArtworkHeader_artwork.graphql.ts
  src/__generated__/SelectListsForArtworkModalQuery.graphql.ts
  src/__generated__/SelectListsForArtworkModal_Test_Query.graphql.ts
  src/__generated__/SelectListsForArtworkModal_artwork.graphql.ts
  src/__generated__/SelectListsForArtworkModal_me.graphql.ts
Labels: Jira Synced

#11990 chore: update metaphysics graphql schema
  src/__generated__/ArtworkGridExampleQuery.graphql.ts
Labels: Squash On Green

#11991 fix(CX-3360): swa final adjustments
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviouslySoldOnArtsyRail.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/MeetTheSpecialists.jest.tsx
Labels: Jira Synced

#11982 feat(GRO-1558): progressive onboarding for artist follows
  src/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Components/FollowButton/__tests__/FollowArtistButton.jest.tsx
  src/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/Components/NavBar/NavBarLoggedInActions.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFindFollows.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowsHighlight.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingPopover.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingContext.jest.tsx
  src/System/Router/Boot.tsx
  src/__generated__/FollowArtistButtonMutation.graphql.ts
  src/__generated__/FollowArtistButtonQuery.graphql.ts
  src/__generated__/FollowArtistButton_Test_Query.graphql.ts
  src/__generated__/FollowArtistButton_me.graphql.ts
  src/__generated__/ProgressiveOnboardingFollowArtistQuery.graphql.ts
  src/__generated__/ProgressiveOnboardingFollowArtist_me.graphql.ts
Labels: Merge On Green, Jira Synced

#11993 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11995 fix(errors): uses logo only layout on error pages
  src/Server/middleware/errorHandler.tsx
Labels: Merge On Green

#11994 perf: temporarily disable RelatedWorks rail
  src/Apps/Artwork/ArtworkApp.tsx
Labels: Jira Synced, Squash On Green

#11997 fix(art-quiz): adds footer space to help visually and fix double scroll
  src/Apps/ArtQuiz/Components/ArtQuizResultsEmpty.tsx
  src/Apps/ArtQuiz/Components/ArtQuizResultsTabs.tsx
Labels: Merge On Green

#11998 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#11996 chore(quiz): add data test id for integration testing
  src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
Labels: Jira Synced

#12001 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
