Repository artsy/force, pull requests merged in 2023-12, with the labels that each got.

#13219 feat: move artist series filter into correct position
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
Labels: Squash On Green

#13214 feat: Reload artist page correctly when navigating from same artist page
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/Components/Alert/Components/Steps/Confirmation.tsx
Labels: Jira Synced

#13192 feat: Update notification preference defaults in alert modal
  src/Components/Alert/Components/Filters/EmailPreferenceWarningMessage.tsx
  src/Components/Alert/Components/Filters/__tests__/NotificationPreferences.jest.tsx
  src/Components/Alert/Components/NotificationPreferences.tsx
  src/Components/Alert/Components/Steps/Details.tsx
  src/Components/Alert/Hooks/__tests__/AlertProvider.jest.tsx
  src/__generated__/NotificationPreferencesQuery.graphql.ts
  src/__generated__/NotificationPreferences_viewer.graphql.ts
Labels: Jira Synced, Squash On Green

#13223 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13225 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13228 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13204 feat(EMI-1572): partner offer checkout route redirect
  src/Apps/PartnerOffer/Routes/Mutations/UsePartnerOfferCheckoutMutation.tsx
  src/Apps/PartnerOffer/Routes/PartnerOfferCheckout.tsx
  src/Apps/PartnerOffer/Routes/__tests__/PartnerOfferCheckout.jest.tsx
  src/Apps/PartnerOffer/partnerOfferRoutes.tsx
  src/__generated__/UsePartnerOfferCheckoutMutation.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#13231 Chore: [EMI-1523] artsy shipping with no saved addresses
  src/Apps/Order/Routes/Shipping2/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Hooks/useParseOrderData.ts
  src/Apps/Order/Routes/Shipping2/Hooks/useShippingContext.ts
  src/Apps/Order/Routes/Shipping2/Mutations/useCreateSavedAddress.ts
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/Utils/ShippingContext.ts
  src/Apps/Order/Routes/Shipping2/Utils/shippingUtils.ts
  src/Apps/Order/Routes/Shipping2/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/saveAddress.ts
  src/Components/__tests__/Utils/addressForm2.ts
Labels: Jira Synced

#13232 fix: generate and fix types
  src/Apps/Order/Routes/Shipping2/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/Mutations/useDeleteSavedAddress.ts
  src/Apps/Order/Routes/Shipping2/Mutations/useSelectShippingQuote.ts
  src/Apps/Order/Routes/Shipping2/Mutations/useUpdateSavedAddress.ts
  src/Apps/Order/Routes/Shipping2/Mutations/useUpdateUserDefaultAddress.ts
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/__generated__/useCreateSavedAddressMutation.graphql.ts
  src/__generated__/useDeleteSavedAddressMutation.graphql.ts
  src/__generated__/useSelectShippingQuoteMutation.graphql.ts
  src/__generated__/useUpdateSavedAddressMutation.graphql.ts
  src/__generated__/useUpdateUserDefaultAddressMutation.graphql.ts
Labels: Squash On Green

#13174 feat(ONYX-385): Saved searches suggested filters
  src/Components/Alert/Components/Filters/QuickMultipleSelectAlertFilter.tsx
  src/Components/Alert/Components/Form/SuggestedFilters.tsx
  src/Components/Alert/Components/Form/__tests__/SuggestedFilters.jest.tsx
  src/Components/Alert/Components/Steps/Details.tsx
  src/Components/Alert/Helpers/handleFieldsWithMultipleValues.ts
  src/Components/Alert/Helpers/isValueSelected.tsx
  src/Components/Alert/Hooks/__tests__/AlertProvider.jest.tsx
  src/DevTools/setupTestWrapper.tsx
  src/__generated__/SuggestedFiltersFetchQuery.graphql.ts
Labels: Jira Synced

#13227 feat(EMI-1587): update the price for a partner offer
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Components/__tests__/TransactionDetailsSummary.jest.tsx
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/Shipping2TestQuery.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/TransactionDetailsSummaryItemTestQuery.graphql.ts
  src/__generated__/TransactionDetailsSummaryItem_order.graphql.ts
  src/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/orderRoutes_StatusQuery.graphql.ts
  src/__generated__/useSaveFulfillmentDetailsMutation.graphql.ts
  src/__generated__/useSelectShippingQuoteMutation.graphql.ts
Labels: Jira Synced

#13239 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13237 Deploy
  data/schema.graphql
  jest.config.js
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Preferences/PreferencesApp.tsx
  src/Components/Artwork/__tests__/GridItem.jest.js
  src/Server/passport-local-with-otp/test/strategy.error.jest.js
  src/Server/passport-local-with-otp/test/strategy.fail.jest.js
  src/Server/passport-local-with-otp/test/strategy.fields.jest.js
  src/Server/passport-local-with-otp/test/strategy.normal.jest.js
  src/Server/passport-local-with-otp/test/strategy.options.jest.js
  src/Server/passport-local-with-otp/test/strategy.passreq.jest.js
  src/Server/passport/test/app/analytics.jest.js
  src/Server/passport/test/app/sanitize_redirect.jest.js
Labels: Jira Synced

#13240 fix: update more filters button color
  src/Components/Alert/Components/Form/SuggestedFilters.tsx
Labels: Squash On Green

#13238 feat(ONYX-580): update create alert copy
  src/Components/Alert/Components/Form/SuggestedFilters.tsx
  src/Components/Alert/Components/Form/__tests__/SuggestedFilters.jest.tsx
  src/Components/Alert/Components/Steps/Details.tsx
Labels: Jira Synced

#13252 feat(ONYX-569): remove Alert Name input in Modal and Edit alert
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
  src/Components/Alert/AlertProvider.tsx
  src/Components/Alert/Components/Form/AlertNameInput.tsx
  src/Components/Alert/Components/Steps/Details.tsx
  src/Components/Alert/Hooks/__tests__/AlertProvider.jest.tsx
  src/__generated__/AlertProviderPreviewQuery.graphql.ts
Labels: Jira Synced

#13251 fix(dia-333): prevent insertion of arbitrary error messages
  src/Apps/Authentication/Components/AuthenticationInlineDialog.tsx
  src/Server/passport/lib/app/lifecycle.ts
  src/Server/passport/test/app/lifecycle.jest.js
Labels: Jira Synced

#13245 Feat: [EMI-1601] update new address w artsy shipping
  src/Apps/Order/Components/Collapse.tsx
  src/Apps/Order/Components/SavedAddresses.tsx
  src/Apps/Order/Routes/Shipping2/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Hooks/useParseOrderData.ts
  src/Apps/Order/Routes/Shipping2/Hooks/useShippingContext.ts
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/Utils/ShippingContext.ts
  src/Apps/Order/Routes/Shipping2/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/saveAddress.ts
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
Labels: Jira Synced

#13256 feat(EMI-1592): show the list price for a partner offer
  src/Apps/Order/Components/ArtworkSummaryItem.tsx
Labels: Jira Synced

#13248 feat: remove sections for churned profiles
  src/Apps/Partner/Routes/Overview/index.tsx
  src/__generated__/Overview_partner.graphql.ts
  src/__generated__/partnerRoutes_OverviewQuery.graphql.ts
Labels: Jira Synced

#13254 Deploy
  package.json
  src/Apps/Authentication/Components/AuthenticationInlineDialog.tsx
  src/Apps/Order/Components/ArtworkSummaryItem.tsx
  src/Apps/Order/Components/Collapse.tsx
  src/Apps/Order/Components/SavedAddresses.tsx
  src/Apps/Order/Routes/Shipping2/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Hooks/useParseOrderData.ts
  src/Apps/Order/Routes/Shipping2/Hooks/useShippingContext.ts
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/Utils/ShippingContext.ts
  src/Apps/Order/Routes/Shipping2/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/saveAddress.ts
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/Apps/Partner/Routes/Overview/index.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
  src/Components/Alert/AlertProvider.tsx
  src/Components/Alert/Components/Form/AlertNameInput.tsx
  src/Components/Alert/Components/Steps/Details.tsx
  src/Components/Alert/Hooks/__tests__/AlertProvider.jest.tsx
  src/Server/passport/lib/app/lifecycle.ts
  src/Server/passport/lib/passport/callbacks.js
  src/Server/passport/test/app/lifecycle.jest.js
  src/Server/passport/test/passport/callbacks.jest.js
  src/__generated__/AlertProviderPreviewQuery.graphql.ts
  src/__generated__/Overview_partner.graphql.ts
  src/__generated__/partnerRoutes_OverviewQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#13261 feat(onyx-554): Include new modal design to closed lot alert header via feature flag
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
Labels: Jira Synced

#13263 fix(ONYX-591): update copy for criteria pills in edit alert form
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
Labels: Jira Synced

#13264 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13262 Deploy
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
Labels: Jira Synced

#13266 fix: get alerts list to update properly
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
Labels: Jira Synced

#13268 fix(alerts): ensure artist series is editable in new form
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
  src/__generated__/NewSavedSearchAlertEditFormQuery.graphql.ts
  src/__generated__/NewSavedSearchAlertEditForm_searchCriteria.graphql.ts
Labels: Jira Synced

#13246 feat: [EMI-1534] Reload shipping quotes on page refresh
  src/Apps/Order/Routes/Shipping2/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Hooks/useShippingContext.ts
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/Utils/ShippingContext.ts
  src/Apps/Order/Routes/Shipping2/Utils/ShippingContext/ShippingContext.tsx
  src/Apps/Order/Routes/Shipping2/Utils/ShippingContext/parseOrderData.ts
  src/Apps/Order/Routes/Shipping2/Utils/shippingUtils.ts
  src/Apps/Order/Routes/Shipping2/__tests__/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Order/Utils/getErrorDialogCopy.tsx
Labels: Jira Synced

#13269 fix(ONYX-598): fix resizing of the edit alert form and filters
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
Labels: Jira Synced, Squash On Green

#13267 Deploy
  package.json
  src/Apps/Order/Routes/Shipping2/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Hooks/useShippingContext.ts
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/Utils/ShippingContext.ts
  src/Apps/Order/Routes/Shipping2/Utils/ShippingContext/ShippingContext.tsx
  src/Apps/Order/Routes/Shipping2/Utils/ShippingContext/parseOrderData.ts
  src/Apps/Order/Routes/Shipping2/Utils/shippingUtils.ts
  src/Apps/Order/Routes/Shipping2/__tests__/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Order/Utils/getErrorDialogCopy.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
  src/__generated__/NewSavedSearchAlertEditFormQuery.graphql.ts
  src/__generated__/NewSavedSearchAlertEditForm_searchCriteria.graphql.ts
  yarn.lock
Labels: Jira Synced

#13273 fix(ONYX-601): fix placeholder on the edit alert form
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormPlaceholder.tsx
  src/Components/Alert/Components/CriteriaPills.tsx
  src/Components/Alert/Components/Form/SuggestedFilters.tsx
Labels: Jira Synced, Squash On Green

#13275 feat(EMI-1593): update saves tooltip content for PartnerOffer
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
Labels: Jira Synced

#13280 fix(ONYX-591): remove separators and update spacing
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
Labels: Jira Synced

#13282 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/ArtworkMeta_artwork.graphql.ts
Labels: Squash On Green

#13283 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13270 Chore: Shipping2 loading state
  src/Apps/Order/Routes/Shipping2/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Utils/ShippingContext/ShippingContext.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
Labels: Jira Synced

#13277 fix(onyx-560): Searching for a number results in errors that break pagination
  src/Apps/Search/Routes/SearchResultsEntity.tsx
  src/Components/ArtworkFilter/index.tsx
Labels: Jira Synced

#13278 feat(EMI-1594): Update Save Artwork toast
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActionsSaveButton.jest.tsx
  src/Components/Artwork/SaveButton/__tests__/SaveArtworkToListsButton.jest.tsx
  src/Components/Artwork/useArtworkLists.ts
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#13281 fix(ONYX-596): add animation to Details in Edit Alert form
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
Labels: Jira Synced

#13284 feat: display nearby galleries rail and about section for churned profiles
  src/Apps/Partner/Routes/Overview/index.tsx
  src/__generated__/Overview_partner.graphql.ts
  src/__generated__/partnerRoutes_OverviewQuery.graphql.ts
Labels: Jira Synced

#13276 Deploy
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActionsSaveButton.jest.tsx
  src/Apps/Order/Routes/Shipping2/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Utils/ShippingContext/ShippingContext.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Partner/Routes/Overview/index.tsx
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/Components/__tests__/NavigationTabs.jest.tsx
  src/Apps/Search/Routes/SearchResultsEntity.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/Search/__tests__/SearchApp.jest.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormPlaceholder.tsx
  src/Components/Alert/Components/CriteriaPills.tsx
  src/Components/Alert/Components/Form/SuggestedFilters.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
  src/Components/Artwork/SaveButton/__tests__/SaveArtworkToListsButton.jest.tsx
  src/Components/Artwork/useArtworkLists.ts
  src/Components/ArtworkFilter/index.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/ArtworkMeta_artwork.graphql.ts
  src/__generated__/Overview_partner.graphql.ts
  src/__generated__/partnerRoutes_OverviewQuery.graphql.ts
Labels: Jira Synced

#13286 feat(alerts): allow artist series suggestion to be accepted
  src/Components/Alert/Components/Form/SuggestedFilters.tsx
  src/Components/Alert/Components/Form/__tests__/SuggestedFilters.jest.tsx
Labels: Squash On Green

#13288 chore: add testid to the delete alert button
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertDeleteModal.tsx
Labels: Jira Synced, Squash On Green

#13290 fix(ONYX-606): add underline to showmore on filter pills
  src/Components/Alert/Components/CriteriaPills.tsx
Labels: Jira Synced

#13292 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13291 Deploy
  data/schema.graphql
  src/Components/Alert/Components/CriteriaPills.tsx
Labels: Jira Synced

#13289 feat: Always enable email notifications when creating alerts
  src/Components/Alert/Components/Filters/__tests__/NotificationPreferences.jest.tsx
  src/Components/Alert/Components/NotificationPreferences.tsx
Labels: Jira Synced, Squash On Green

#13293 chore: port fulfillment-details-specific tests from route to form component
  src/Apps/Order/Routes/Shipping2/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Components/Address/utils.ts
Labels: Jira Synced

#13299 fix(onyx-560): fixes broken search page when searching by a number
  src/Components/Search/SearchBarInput.tsx
Labels: Jira Synced

#13302 feat(alerts): source artist series suggestions from artwork
  src/Apps/Artwork/ArtworkApp.tsx
  src/Components/Alert/Components/Form/SuggestedFilters.tsx
  src/__generated__/SuggestedFiltersFetchQuery.graphql.ts
Labels: Jira Synced

#13303 chore: update copy for subscribe banner
  src/Apps/Partner/Components/Overview/SubscriberBanner.tsx
  src/__generated__/SubscriberBanner_partner.graphql.ts
  src/__generated__/partnerRoutes_OverviewQuery.graphql.ts
Labels: Jira Synced

#13312 chore: rename Saved Alerts to Alerts in settings
  src/Apps/Settings/SettingsApp.tsx
  src/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
Labels: Jira Synced

#13310 refactor(progressive-onboarding): Swap in new @artsy/dismissible and refactor code
  package.json
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertCreate.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertCreateSimple.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFind.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertHighlight.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertReady.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertSelectFilter.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowFind.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowHighlight.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveFind.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveHighlight.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingAlerts.jest.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingContext.jest.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingFollows.jest.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingSaves.jest.tsx
  src/Components/ProgressiveOnboarding/progressiveOnboardingAlerts.tsx
  src/System/Router/Boot.tsx
  src/Utils/Hooks/useAuthIntent/index.tsx
  yarn.lock
Labels: Jira Synced

#13305 chore: change Viewing Room button copy
  src/Apps/ViewingRoom/Components/ViewingRoomContentNotAccessible.tsx
Labels: Jira Synced
