Repository artsy/force, pull requests merged in 2023-04, with the labels that each got.

#12193 fix: Update Insights's Auction Result title
  src/Apps/Settings/Routes/Insights/Components/InsightsAuctionResults.tsx
Labels: Jira Synced

#12195 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12196 refactor: pass context owner in the parent component
  src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListArtworksGrid.tsx
Labels: Jira Synced

#12197 refactor(phase 6): standardise and use `ArtworkList` terminology
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectArtworkListsModal/SelectArtworkListItem.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectArtworkListsModal/SelectArtworkListsContent.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectArtworkListsModal/SelectArtworkListsFooter.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectArtworkListsModal/SelectArtworkListsHeader.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectArtworkListsModal/SelectArtworkListsModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectArtworkListsModal/SelectArtworkListsPlaceholders.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectArtworkListsModal/__tests__/SelectArtworkListsModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectArtworkListsModal/useSelectArtworkLists.ts
  src/Apps/CollectorProfile/Routes/Saves2/Utils/__tests__/getSelectedArtworkListIds.jest.ts
  src/Apps/CollectorProfile/Routes/Saves2/Utils/__tests__/getSelectedCollectionIds.jest.ts
  src/Apps/CollectorProfile/Routes/Saves2/Utils/getSelectedArtworkListIds.ts
  src/Apps/CollectorProfile/Routes/Saves2/Utils/getSelectedCollectionIds.ts
  src/Components/Artwork/ManageArtworkForSaves.tsx
  src/__generated__/SelectArtworkListsModalQuery.graphql.ts
  src/__generated__/SelectArtworkListsModal_Test_Query.graphql.ts
  src/__generated__/SelectArtworkListsModal_me.graphql.ts
Labels: Jira Synced, Squash On Green

#12158 feat(FX-4638): User adds artworks to new list — pagination
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/AddArtworksModalContent.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/ArtworksInfiniteScrollSentinel.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/ArtworksList.tsx
  src/__generated__/AddArtworksModalContentPaginationQuery.graphql.ts
  src/__generated__/AddArtworksModalContentQuery.graphql.ts
  src/__generated__/AddArtworksModalContent_me.graphql.ts
Labels: Jira Synced

#12203 feat(GRO-1637): roughs in brand campaign routes
  src/Apps/Marketing/Components/MarketingAlternatingStack.tsx
  src/Apps/Marketing/Components/MarketingCollectionCell.tsx
  src/Apps/Marketing/Components/MarketingFeaturedArtworksRail.tsx
  src/Apps/Marketing/Components/MarketingHeader.tsx
  src/Apps/Marketing/Components/MarketingQuizCTA.tsx
  src/Apps/Marketing/Components/MarketingTrendingArtistsRail.tsx
  src/Apps/Marketing/Routes/MarketingFindArtYouWantRoute.tsx
  src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx
  src/Apps/Marketing/marketingRoutes.tsx
  src/__generated__/MarketingFeaturedArtworksRailQuery.graphql.ts
  src/__generated__/MarketingFeaturedArtworksRail_viewer.graphql.ts
  src/__generated__/MarketingTrendingArtistsRailQuery.graphql.ts
  src/__generated__/MarketingTrendingArtistsRail_viewer.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#12088 refactor: move AppToasts to bottom
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActionsSaveButtonV2.jest.tsx
  src/Apps/Components/AppToasts.tsx
  src/Apps/Components/Layouts/LayoutBlank.tsx
  src/Apps/Components/Layouts/LayoutContainerOnly.tsx
  src/Apps/Components/Layouts/LayoutDefault.tsx
  src/Apps/Components/Layouts/LayoutLogoOnly.tsx
  src/Apps/Components/Layouts/LayoutNavOnly.tsx
  src/Components/Artwork/SaveButton/__tests__/SaveArtworkToListsButton.jest.tsx
Labels: Jira Synced

#12201 fix(FX-4698): search feedback
  src/Apps/Search/Components/SendFeedback.tsx
  src/Apps/Search/Components/__tests__/SendFeedback.jest.tsx
Labels: Jira Synced

#12202 feat(FX-4713): display border for all artwork images in artwork lists rail
  src/Apps/CollectorProfile/Routes/Saves2/Components/Images/ArtworkListImageBorder.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Images/ArtworkListNoImage.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Images/FourUpImageLayout.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Images/StackedImageLayout.tsx
Labels: Jira Synced

#12204 fix(FX-4713): specify size for image containers, specify size for images
  src/Apps/CollectorProfile/Routes/Saves2/Components/Images/FourUpImageLayout.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Images/StackedImageLayout.tsx
Labels: Jira Synced, Squash On Green

#12205 fix(FX-4716): update empty-state to match designs
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListEmptyState.tsx
Labels: Jira Synced

#12211 feat(GRO-1637): refines brand campaign routes
  src/Apps/Marketing/Components/MarketingAlternatingStack.tsx
  src/Apps/Marketing/Components/MarketingHeader.tsx
  src/Apps/Marketing/Components/MarketingQuizCTA.tsx
  src/Apps/Marketing/Routes/MarketingFindArtYouWantRoute.tsx
  src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx
  src/Apps/Marketing/Utils/brandPalette.ts
Labels: Jira Synced

#12207 feat(FX-4717): Respond with a 404 when navigating to a non-existent list
  src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
  src/Apps/CollectorProfile/Routes/Saves2/__tests__/CollectorProfileSaves2Route.jest.tsx
Labels: Jira Synced

#12213 refactor(artwork lists): use a common ArtworkListForm in create and edit flows
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/EditArtworkListModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListForm/ArtworkListForm.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModal.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#12215 chore: update copy to follow new designs
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
Labels: Squash On Green

#12208 chore(FX-4719): set correct page title for the new "Saves" tab
  src/Apps/CollectorProfile/Routes/Follows/CollectorProfileFollowsRoute.tsx
  src/Apps/CollectorProfile/Routes/Saves/CollectorProfileSavesRoute.tsx
  src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
  src/Apps/CollectorProfile/Routes/Saves2/__tests__/CollectorProfileSaves2Route.jest.tsx
  src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
Labels: Jira Synced, Squash On Green

#12217 chore(FX-4721): rename sort options
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListContent.tsx
Labels: Jira Synced, Squash On Green

#12216 feat(GRO-1638): New footer
  src/Components/DownloadAppBadges/DownloadAppBadge.tsx
  src/Components/DownloadAppBadges/DownloadAppBadges.tsx
  src/Components/Footer/Footer.tsx
  src/Components/Footer/FooterDownloadAppBanner.tsx
  src/Components/Footer/FooterDownloadAppBanner2.tsx
Labels: Jira Synced

#12218 feat(GRO-1639,GRO-1640): Minor tweaks
  src/Apps/Marketing/Components/MarketingQuizCTA.tsx
  src/Components/Footer/FooterDownloadAppBanner.tsx
  src/Components/Footer/__tests__/Footer.jest.tsx
Labels: Jira Synced

#12209 chore(TX-1114): update wire transfer bank details
  src/Apps/Order/Routes/__tests__/Status.jest.tsx
  src/Apps/Order/Utils/getStatusCopy.tsx
Labels: Jira Synced

#12221 Fix typo in wire instructions
  src/Apps/Order/Routes/__tests__/Status.jest.tsx
  src/Apps/Order/Utils/getStatusCopy.tsx
Labels: Jira Synced

#12223 fix(GRO-1649): cleans up session only when executing redirect
  src/Apps/Authentication/Middleware/checkForRedirect.ts
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/helpers.ts
  src/Server/passport/lib/app/__tests__/redirectBack.jest.ts
  src/Server/passport/lib/app/lifecycle.js
  src/Server/passport/lib/app/logout.js
  src/Server/passport/lib/app/redirectBack.ts
  src/Server/passport/lib/app/redirectback.js
  src/Server/passport/lib/app/sanitize_redirect.js
  src/Server/passport/sanitize-redirect.js
Labels: Jira Synced

#12224 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12072 feat(FX-4667): Align modal width across different artwork list-related modals
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/DeleteArtworkListModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/AddArtworksModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectArtworkListsModal/SelectArtworkListsModal.tsx
Labels: Jira Synced, Squash On Green

#12229 fix: bring back the link
  src/Components/Footer/Footer.tsx
Labels: Jira Synced

#12230 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12119 feat(CX-3402): Single Auction Result page
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResult.tsx
  src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResultBackLink.tsx
  src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResultImage.tsx
  src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResultMetaData.tsx
  src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResultPrice.tsx
  src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResultTitleInfo.tsx
  src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/__tests__/AuctionResult.jest.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResultItem.jest.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/Apps/Artist/artistRoutes.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx
  src/Apps/Settings/SettingsApp.tsx
  src/__generated__/ArtistAuctionResultItemTestQuery.graphql.ts
  src/__generated__/ArtistAuctionResultItem_auctionResult.graphql.ts
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
  src/__generated__/AuctionResultImage_auctionResult.graphql.ts
  src/__generated__/AuctionResultMetaData_auctionResult.graphql.ts
  src/__generated__/AuctionResultPrice_auctionResult.graphql.ts
  src/__generated__/AuctionResultTestQuery.graphql.ts
  src/__generated__/AuctionResultTitleInfo_auctionResult.graphql.ts
  src/__generated__/AuctionResult_auctionResult.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/artistRoutes_AuctionResultQuery.graphql.ts
  src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_InsightsRouteQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
  src/__generated__/settingsRoutes_InsightsRouteQuery.graphql.ts
Labels: Jira Synced

#12234 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12235 chore: update copies
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Footer.jest.tsx
  src/Apps/Settings/Routes/MyCollection/Components/MyCollectionEmptyState.tsx
Labels: Jira Synced

#12237 feat: update auction results pagination
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultsRoute.tsx
  src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.jest.tsx
  src/Apps/Artist/Utils/allowedAuctionResultFilters.ts
  src/Apps/Artist/artistRoutes.tsx
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResultsRoute_artist.graphql.ts
  src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
Labels: Jira Synced

#12238 fix(TX-1019): Error display for invalid phone number submission via Add Address modal
  src/Apps/Order/Components/AddressModal.tsx
  src/Apps/Order/Components/__tests__/AddressModal.jest.tsx
  src/Apps/Order/Mutations/CreateUserAddress.ts
Labels: Jira Synced

#12244 fix(CX-3619): change tabs text size
  src/Apps/CollectorProfile/CollectorProfileApp.tsx
Labels: Jira Synced

#12245 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12249 feat(CX-3620): change the design of the auction lots rail
  src/Apps/Auctions/Components/WorksByArtistsYouFollowRail.tsx
  src/Apps/Auctions/Components/__tests__/WorksByArtistsYouFollowRail.jest.tsx
  src/Components/Artwork/ShelfArtwork.tsx
Labels: Jira Synced, Squash On Green

#12246 fix: correctly display artworks count for recently created artwork list
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/Mutations/useCreateCollection.ts
  src/__generated__/useCreateCollectionMutation.graphql.ts
Labels: Jira Synced

#12256 fix(GRO-1668): Prevent multiple secondary tips from appearing simultaneously
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertCreate.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFind.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertReady.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertSelectFilter.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowFind.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowHighlight.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveFind.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveHighlight.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingContext.jest.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingFollows.jest.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingSaves.jest.tsx
Labels: Jira Synced

#12257 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12258 Revert "feat(CX-3620): change the design of the auction lots rail"
  src/Apps/Auctions/Components/WorksByArtistsYouFollowRail.tsx
  src/Apps/Auctions/Components/__tests__/WorksByArtistsYouFollowRail.jest.tsx
  src/Components/Artwork/ShelfArtwork.tsx
Labels: Jira Synced, Squash On Green

#12254 chore(FX-4737, FX-4738): artwork list copy changes (phase 2)
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButtonV2.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsWatchLotButton.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/UtilButton.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActionsSaveButtonV2.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/ArtworkListsHeader.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/__tests__/CollectorProfileSaves2Route.jest.tsx
  src/Components/Artwork/SaveButton/useSaveArtworkToLists.ts
  src/Components/Artwork/useArtworkLists.ts
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced, Squash On Green

#12255 refactor(FX-4736): Use `collector-profile/saves` instead of `collector-profile/saves2` for artwork lists
  src/Apps/CollectorProfile/CollectorProfileApp.tsx
  src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/DeleteArtworkListModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListItem.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/ArtworkListItem.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Utils/useLinksToSaves.ts
  src/Apps/CollectorProfile/Routes/SavesAndFollows/CollectorProfileSavesAndFollowsRoute.tsx
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/Apps/CollectorProfile/constants.ts
  src/Components/Artwork/ManageArtworkForSaves.tsx
  src/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/Server/middleware/userRequiredMiddleware.ts
  src/__generated__/CollectorProfileSavesAndFollowsRoute_me.graphql.ts
  src/__generated__/collectorProfileRoutes_Saves2Query.graphql.ts
  src/__generated__/collectorProfileRoutes_SavesAndFollowsRouteQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#12259 feat(CX-3620): auction lots for you ending soon rail ux chanes
  src/Apps/Auctions/Components/WorksByArtistsYouFollowRail.tsx
  src/Apps/Auctions/Components/__tests__/WorksByArtistsYouFollowRail.jest.tsx
Labels: Jira Synced

#12250 Add more braze logging
  src/Apps/Home/Components/HomeContentCards/HomeContentCards.tsx
Labels: Merge On Green

#12265 fix(GRO-1659): Brand campaign Q/A
  src/Apps/ArtQuiz/artQuizRoutes.tsx
  src/Apps/Marketing/Components/MarketingFeaturedArtworksRail.tsx
  src/Apps/Marketing/Components/MarketingHeader.tsx
  src/Apps/Marketing/Components/MarketingQuizCTA.tsx
  src/Apps/Marketing/Routes/MarketingFindArtYouLoveRoute.tsx
  src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx
  src/Apps/Marketing/marketingRoutes.tsx
  src/Components/DownloadAppBadges/DownloadAppBadge.tsx
  src/Components/Footer/FooterDownloadAppBanner2.tsx
Labels: Jira Synced

#12263 chore(FX-4732): Change message when creating a list
  src/Components/Artwork/__tests__/ManageArtworkForSaves.jest.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#12267 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12272 fix(marketing): updates assets
  src/Apps/Marketing/Components/MarketingQuizCTA.tsx
  src/Apps/Marketing/Routes/MarketingFindArtYouLoveRoute.tsx
  src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx
Labels: Merge On Green

#12269 chore: Add isP1Artist to saveCollectedArtwork tracking event
  .secrets.baseline
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionEditArtwork.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkModel.ts
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx
  src/Apps/MyCollection/Routes/Hooks/__tests__/useMyCollectionTracking.jest.tsx
  src/Apps/MyCollection/Routes/Hooks/useMyCollectionTracking.tsx
  src/__generated__/ArtistAutocomplete_SearchConnection_Query.graphql.ts
  src/__generated__/MyCollectionArtworkFormArtistStep_me.graphql.ts
  src/__generated__/MyCollectionCreateArtworkTest_Query.graphql.ts
  src/__generated__/MyCollectionEditArtworkTest_Query.graphql.ts
  src/__generated__/MyCollectionEditArtwork_artwork.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionArtworkFormQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts
  src/__generated__/myCollectionRoutes_MyCollectionArtworkFormQuery.graphql.ts
  src/__generated__/myCollectionRoutes_MyCollectionArtworkUploadQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#12261 feat(NX-3487): implement salesforce chat bubble
  src/Apps/Artwork/Components/ArtworkZendesk.tsx
  src/Apps/Auction/AuctionApp.tsx
  src/Apps/Auction/__tests__/AuctionApp.jest.tsx
  src/Apps/Order/OrderApp.tsx
  src/Apps/Order/__tests__/OrderApp.jest.tsx
  src/Components/SalesforceWrapper.tsx
  src/Server/config.ts
  src/Server/setup_sharify.ts
  src/Typings/global.d.ts
  src/Typings/sharify.d.ts
  src/Utils/exceedsChatSupportThreshold.ts
Labels: Jira Synced

#12268 feat: new search boilerplate with feature flag enabled.
  src/Components/NavBar/NavBar.tsx
  src/Components/Search/NewSearch/NewSearchBar.tsx
  src/Components/Search/NewSearch/NewSearchBarInputContainer.tsx
  src/Components/Search/NewSearch/NewSearchBarSuggestion.tsx
Labels: Jira Synced, Squash On Green

#12156 chore: use version C for new works for you rail
  src/Apps/Home/Components/HomeNewWorksForYouRail.tsx
  src/Apps/NewForYou/newForYouRoutes.tsx
  src/__generated__/HomeNewWorksForYouRailQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#12274 chore(NX-3492): change support links from ZD to Salesforce
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuthenticityCertificate.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarShippingInformation.tsx
  src/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
  src/Apps/Auctions/AuctionsApp.tsx
  src/Apps/Auctions/__tests__/AuctionsApp.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FAQSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/FAQSWA.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Conversation/Components/DetailsSidebar.tsx
  src/Apps/IdentityVerification/IdentityVerificationApp/index.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWAHowItWorksModal.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASectionSubmitted.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSWAHowItWorksModal.jest.tsx
  src/Apps/Order/Components/BuyerGuarantee.tsx
  src/Apps/Order/Components/StickyFooter.tsx
  src/Apps/Order/Components/__tests__/StickyFooter.jest.tsx
  src/Components/Footer/Footer.tsx
  src/Server/middleware/hardcodedRedirects.ts
Labels: Jira Synced, Do not merge, help links migration

#12281 fix(settings): clean up
  src/Apps/Components/Layouts/LayoutLogoOnly.tsx
  src/Apps/Settings/SettingsApp.tsx
  src/Apps/Settings/settingsRoutes.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavBarLoggedInActions.tsx
  src/Components/NavBar/__tests__/NavBar.jest.tsx
  src/Server/middleware/hardcodedRedirects.ts
  src/__generated__/settingsRoutes_MyCollectionRouteQuery.graphql.ts
Labels: Merge On Green

#12283 feat: alerts option in user dropdown
  src/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/Components/NavBar/Menus/__tests__/NavBarUserMenu.jest.tsx
Labels: Merge On Green

#12284 feat: reduce memory request/limit to reflect actual usage
  Dockerfile
  hokusai/production.yml
  hokusai/staging.yml
Labels: Jira Synced

#12271 feat(TX-1134): add title when bank transfer is the only payment method
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/__tests__/Payment.jest.tsx
Labels: Jira Synced

#12287 fix(article): disables lazyloading on ads
  src/Apps/Article/Components/ArticleAd/ArticleAd.tsx
Labels: Merge On Green

#12290 feat(alerts): completes alerts onboarding tips
  src/Apps/Settings/SettingsApp.tsx
  src/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertCreate.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertHighlight.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingAlerts.jest.tsx
  src/Components/SavedSearchAlert/Components/ActiveFilterPillsAndCreateAlert.tsx
  src/Components/SavedSearchAlert/Components/__tests__/ActiveFilterPillsAndCreateAlert.jest.tsx
Labels: Merge On Green, Jira Synced

#12264 feat(CX-3618): create the view all artwork grid page for auctions works for you
  src/Apps/Auctions/Components/WorksByArtistsYouFollowRail.tsx
  src/Apps/Auctions/Components/__tests__/WorksByArtistsYouFollowRail.jest.tsx
  src/Apps/Auctions/EndingSoonAuctions/EndingSoonAuctions.tsx
  src/Apps/Auctions/EndingSoonAuctions/__tests__/EndingSoonAuctions.jest.tsx
  src/Apps/Auctions/EndingSoonAuctions/endingSoonAuctionsRoutes.tsx
  src/Apps/Auctions/Routes/EndingSoonAuctionsGrid.tsx
  src/Apps/Auctions/auctionsRoutes.tsx
  src/Apps/Components/LogInPrompt.tsx
  src/Apps/Components/__tests__/LogInPrompt.jest.tsx
  src/Apps/NewForYou/NewForYouApp.tsx
  src/__generated__/AuctionsApp_Test_Query.graphql.ts
  src/__generated__/CuritorialRailsTabBar_Test_Query.graphql.ts
  src/__generated__/EndingSoonAuctionsGridQuery.graphql.ts
  src/__generated__/EndingSoonAuctionsGrid_viewer.graphql.ts
  src/__generated__/EndingSoonAuctions_test_Query.graphql.ts
  src/__generated__/EndingSoonAuctions_viewer.graphql.ts
  src/__generated__/WorksByArtistsYouFollowRail_Test_Query.graphql.ts
  src/__generated__/WorksByArtistsYouFollowRail_viewer.graphql.ts
  src/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
  src/__generated__/endingSoonAuctionsRoutes_TopLevelQuery.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#12276 feat: add search pills
  src/Components/Search/NewSearch/NewSearchBarInputContainer.tsx
  src/Components/Search/NewSearch/NewSearchInputPillsContainer.tsx
Labels: Jira Synced, Squash On Green

#12300 test: skip cypress settings redirect
  cypress/e2e/settings.cy.ts
Labels: Jira Synced

#12301 chore(icons): replaces icons
  src/Apps/ArtQuiz/Components/ArtQuizButton.tsx
  src/Apps/ArtQuiz/Components/ArtQuizResultsLoader.tsx
  src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
  src/Apps/ArtQuiz/Routes/ArtQuizWelcome.tsx
  src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGallery.tsx
  src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryFigure.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtsyGuarantee.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/__tests__/ArtworkTopContextBar.jest.tsx
  src/Apps/Auctions/Components/MyBids/MyBidsBidItem.tsx
  src/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileHeader/Components/CollectorProfileHeaderAvatar.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileHeader/Components/__tests__/CollectorProfileHeaderAvatar.jest.tsx
  src/Apps/Conversation/Components/DetailsHeader.tsx
  src/Apps/FairOrginizer/Components/__tests__/DedicatedArticlesBreadcrumbs.jest.tsx
  src/Apps/Order/Routes/__tests__/Accept.jest.tsx
  src/Apps/Order/Routes/__tests__/Counter.jest.tsx
  src/Apps/Order/Routes/__tests__/Respond.jest.tsx
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/SettingsEditProfileArtistsYouCollectRemoveButton.tsx
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
  src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Components/CareerHighlightsModal.tsx
  src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormDesktop.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/Components/Artwork/GridItem.tsx
  src/Components/Artwork/SaveButton/DeprecatedSaveButton.tsx
  src/Components/Artwork/SaveButton/SaveButton.tsx
  src/Components/Artwork/SaveButton/__tests__/SaveArtworkToListsButton.jest.tsx
  src/Components/Artwork/SidebarExpandable.tsx
  src/Components/ArtworkFilter/ArtworkFilters/KeywordFilter.tsx
  src/Components/ArtworkFilter/index.tsx
  src/Components/AuctionBuyersPremiumDialog.tsx
  src/Components/AuctionFAQsDialog.tsx
  src/Components/AuthDialog/Components/AuthDialogSocial.tsx
  src/Components/DeepZoom/DeepZoomCloseButton.tsx
  src/Components/Footer/Footer.tsx
  src/Components/Inquiry/Inquiry.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/Components/NavBar/NavBarPrimaryLogo.tsx
  src/Components/NavBar/__tests__/NavBar.jest.tsx
  src/Components/NavBar/__tests__/NavBarTracking.jest.tsx
  src/Components/Notifications/NotificationsTabs.tsx
  src/Components/Onboarding/Components/OnboardingFollows.tsx
  src/Components/Onboarding/Components/OnboardingModal.tsx
  src/Components/PhotoUpload/Components/PhotoThumbnail.tsx
  src/Components/Search/SearchInputContainer.tsx
  src/Components/SplitLayout.tsx
  src/Components/StepSummaryItem.tsx
  src/Components/TopContextBar.tsx
  src/Components/ViewInRoom/ViewInRoomCloseButton.tsx
Labels: Merge On Green

#12305 fix(artwork): removes custom expandables
  package.json
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Components/Artwork/SidebarExpandable.tsx
  yarn.lock
Labels: Merge On Green

#12306 fix(GRO-1673): remaining q/a items
  src/Apps/Marketing/Routes/MarketingFindArtYouLoveRoute.tsx
  src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx
  src/Components/Footer/FooterDownloadAppBanner2.tsx
Labels: Merge On Green, Jira Synced

#12307 chore: Add missing SF env vars to Server/config.ts
  src/Server/config.ts
Labels: Jira Synced

#12292 feat: search pills backend data wire up
  src/Components/Search/NewSearch/NewSearchBar.tsx
  src/Components/Search/NewSearch/NewSearchBarFooter.tsx
  src/Components/Search/NewSearch/NewSearchBarInput.tsx
  src/Components/Search/NewSearch/NewSearchBarInputContainer.tsx
  src/Components/Search/NewSearch/NewSearchInputPills.tsx
  src/Components/Search/NewSearch/NewSearchInputPillsContainer.tsx
  src/Components/Search/NewSearch/constants.ts
  src/Components/Search/NewSearch/utils/getLabel.ts
  src/__generated__/NewSearchBarInputRefetchQuery.graphql.ts
  src/__generated__/NewSearchBarInputSuggestQuery.graphql.ts
  src/__generated__/NewSearchBarInput_viewer.graphql.ts
  src/__generated__/NewSearchInputPills_viewer.graphql.ts
Labels: Jira Synced

#12317 fix: disable exit on error during cypress install
  scripts/smoke_test.sh
Labels: Jira Synced

#12310 fix: make auction result main query principal
  src/Apps/Artist/artistRoutes.tsx
  src/__generated__/artistRoutes_AuctionResultQuery.graphql.ts
Labels: Jira Synced

#12320 refactor: increase cypress install timeout to 60s, add retry
  scripts/smoke_test.sh
Labels: Jira Synced

#12324 fix: Use an emdash like a gentleman GRO-1648
  src/Apps/Home/Components/HomeContentCards/FallbackCards.tsx
Labels: Merge On Green

#12326 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useEditNotificationPreferencesMutation.graphql.ts
Labels: Squash On Green

#12328 chore: dd-trace upgrade to v1
  hokusai/development.yml
  package.json
  yarn.lock
Labels: Jira Synced

#12330 fix(NX-3530): hide SF chat after unmounting. Same as the zendesk component
  src/Components/SalesforceWrapper.tsx
Labels: Jira Synced

#12332 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12333 fix(NX-3530): window is undefined on ssr
  src/Components/SalesforceWrapper.tsx
Labels: Jira Synced

#12318 fix: set auction artwork initial sort from querystring
  src/Apps/Auction/Components/AuctionArtworkFilter.tsx
  src/Apps/Auction/Components/__tests__/AuctionArtworkFilter.jest.tsx
  src/Apps/Auction/auctionRoutes.tsx
Labels: Jira Synced

#12334 fix: move usage of window to the useEffect
  src/Components/SalesforceWrapper.tsx
Labels: Jira Synced, Squash On Green
