Repository artsy/force, pull requests merged in 2023-06, with the labels that each got.

#12473 feat: enable artwork lists for artsy employee
  .secrets.baseline
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
  src/Apps/CollectorProfile/Routes/Saves2/useCheckIfArtworkListsEnabled.ts
  src/Apps/CollectorProfile/Routes/SavesAndFollows/CollectorProfileSavesAndFollowsRoute.tsx
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
  src/Components/Artwork/Details.tsx
  src/Utils/__tests__/isArtsyEmail.jest.ts
  src/Utils/isArtsyEmail.ts
Labels: Jira Synced

#12478 feat: disable experimental fetch
  Dockerfile
  scripts/jest.sh
  scripts/start.sh
Labels: Jira Synced

#12467 feat(FX-4772): Inline price control with Create alert modal
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx
  src/Components/NumericInput.tsx
  src/Components/PriceRange/Histogram.tsx
  src/Components/PriceRange/PriceRange.tsx
  src/Components/PriceRange/Utils/__tests__/convertToFilterFormatRange.jest.ts
  src/Components/PriceRange/Utils/__tests__/getPriceValue.jest.ts
  src/Components/PriceRange/Utils/__tests__/parsePriceRange.jest.ts
  src/Components/PriceRange/Utils/convertToFilterFormatRange.ts
  src/Components/PriceRange/Utils/getPriceValue.ts
  src/Components/PriceRange/Utils/parsePriceRange.ts
  src/Components/PriceRange/Utils/parseSliderPriceRange.ts
  src/Components/PriceRange/constants.ts
  src/Components/SavedSearchAlert/Components/PriceRangeFilter.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertContext.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#12482 fix: use lowercase o in only
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Components/__tests__/TransactionDetailsSummary.jest.tsx
Labels: Jira Synced

#12485 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12489 fix(usesizeandposition): ensures that if node is added after hook is set up; we still get geometry
  src/Utils/Hooks/useSizeAndPosition.ts
Labels: Merge On Green

#12496 chore: replace zendesk link in buyer guarantee page with SF one
  src/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
Labels: Jira Synced, help links migration

#12491 fix: separate CVC and Expiration from Credit Card Number on small devices
  src/Components/CreditCardInput/CreditCardInput.tsx
Labels: Jira Synced

#12495 test(artwork lists): enable Integrity testing
  src/Apps/Artwork/Components/ArtworkImageBrowser/SaveUtilButton.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/AddArtworksModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/ArtworkItem.tsx
  src/Apps/CollectorProfile/Routes/Saves2/useCheckIfArtworkListsEnabled.ts
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
Labels: Jira Synced, Squash On Green

#12501 Revert "feat: Segment Cookie Consent Manager"
  package.json
  src/Apps/Article/Components/ArticleAd/ArticleAd.tsx
  src/Apps/Article/Components/ArticleAd/ArticleAdBanner.tsx
  src/Apps/Article/Components/Sections/ArticleSectionVideo.tsx
  src/Components/CookieConsentManager/CookieConsentBanner.tsx
  src/Components/CookieConsentManager/CookieConsentManager.tsx
  src/Components/CookieConsentManager/CookieConsentManagerContext.tsx
  src/Components/CookieConsentManager/CookieConsentManagerDialog.tsx
  src/Components/CookieConsentManager/CookieConsentManagerSetter.tsx
  src/Components/CookieConsentManager/README.md
  src/Components/CookieConsentManager/__tests__/categories.jest.ts
  src/Components/CookieConsentManager/categories.ts
  src/Components/CookieConsentManager/cookieConsentManagerServerRoutes.ts
  src/Components/CookieConsentManager/useConsentRequired.ts
  src/Components/CookieConsentManager/utils.ts
  src/Server/analytics/segmentOneTrustIntegration/__tests__/conditionallyLoadAnalytics.jest.ts
  src/Server/analytics/segmentOneTrustIntegration/__tests__/fetchDestinationForWriteKey.jest.ts
  src/Server/analytics/segmentOneTrustIntegration/__tests__/fetchDestinations.jest.ts
  src/Server/analytics/segmentOneTrustIntegration/__tests__/getConsent.jest.ts
  src/Server/analytics/segmentOneTrustIntegration/__tests__/getConsentAndLoad.jest.ts
  src/Server/analytics/segmentOneTrustIntegration/__tests__/getOneTrustConsent.jest.ts
  src/Server/analytics/segmentOneTrustIntegration/__tests__/oneTrustReady.jest.ts
  src/Server/analytics/segmentOneTrustIntegration/__tests__/setSegmentDestinationPref.jest.ts
  src/Server/analytics/segmentOneTrustIntegration/__tests__/validateSegmentResponse.jest.ts
  src/Server/analytics/segmentOneTrustIntegration/conditionallyLoadAnalytics.ts
  src/Server/analytics/segmentOneTrustIntegration/delay.ts
  src/Server/analytics/segmentOneTrustIntegration/fetchDestinationForWriteKey.ts
  src/Server/analytics/segmentOneTrustIntegration/fetchDestinations.ts
  src/Server/analytics/segmentOneTrustIntegration/getConsent.ts
  src/Server/analytics/segmentOneTrustIntegration/getConsentAndLoad.ts
  src/Server/analytics/segmentOneTrustIntegration/getOneTrustConsent.ts
  src/Server/analytics/segmentOneTrustIntegration/oneTrustReady.ts
  src/Server/analytics/segmentOneTrustIntegration/segmentOneTrustIntegration.ts
  src/Server/analytics/segmentOneTrustIntegration/setSegmentDestinationPref.ts
  src/Server/analytics/segmentOneTrustIntegration/setServerSideCookie.ts
  src/Server/analytics/segmentOneTrustIntegration/setTrackingPreferences.ts
  src/Server/analytics/segmentOneTrustIntegration/validateSegmentResponse.ts
  src/System/Router/Boot.tsx
  src/System/Router/renderServerApp.tsx
  src/client.tsx
  src/html.ejs
  src/server.ts
  src/tests.ts
  yarn.lock
Labels: Merge On Green

#12510 feat(cookie-consent): implements cookie consent manager
  package.json
  src/Components/CookieConsentManager/CookieConsentBanner.tsx
  src/Components/CookieConsentManager/CookieConsentManager.tsx
  src/Components/CookieConsentManager/CookieConsentManagerContext.tsx
  src/Components/CookieConsentManager/CookieConsentManagerDialog.tsx
  src/Components/CookieConsentManager/CookieConsentManagerSetter.tsx
  src/Components/CookieConsentManager/README.md
  src/Components/CookieConsentManager/__tests__/categories.jest.ts
  src/Components/CookieConsentManager/categories.ts
  src/Components/CookieConsentManager/cookieConsentManagerServerRoutes.ts
  src/Components/CookieConsentManager/useConsentRequired.ts
  src/Components/CookieConsentManager/utils.ts
  yarn.lock
Labels: Merge On Green

#12507 chore(TX-1229): add error message tracking for review route
  src/Apps/Order/Routes/Review/index.tsx
Labels: Jira Synced

#12514 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12508 feat(TX-1213): update SEPA copy
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/__tests__/Payment.jest.tsx
Labels: Jira Synced

#12512 feat(TX-1154): update price options and offer note
  src/Apps/Order/Components/OfferNote.tsx
  src/Apps/Order/Components/PriceOptions.tsx
  src/Apps/Order/Components/__tests__/OfferNote.jest.tsx
  src/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
Labels: Jira Synced

#12502 feat(artwork lists): improve visibility of artwork list content on smaller screens
  src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListArtworksGrid.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListContent.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListItem.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Utils/useArtworkListVisibility.tsx
Labels: Jira Synced

#12517 chore(artwork lists): make artwork list scrolling less strict
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListContent.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Utils/useArtworkListVisibility.tsx
Labels: Squash On Green

#12518 chore: Update editorial contact section GRO-1627
  src/Apps/Contact/ContactApp.tsx
Labels: Merge On Green

#12519 chore: Update specialist info GRO-1757
  src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Merge On Green

#12520 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12521 fix(artwork lists): small typo
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListArtworksGrid.tsx
Labels: Squash On Green

#12515 chore(FX-4718): it's hard to click on the buttons if the toast message is displayed
  src/Apps/Components/AppToasts.tsx
Labels: Jira Synced

#12524 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12526 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12522 fix(CX-3780): show artwork image inside my collection when gemini processing fails
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtworkStep.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArworkSearch.tsx
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
Labels: Jira Synced

#12532 chore(e2e): adding timeout to artist cypress run
  cypress/e2e/artist.cy.js
Labels: Merge On Green

#12533 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12530 fix(FX-4730): fixes incorrect validation message when creating / updating artwork lists
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/EditArtworkListModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/Mutations/useCreateCollection.ts
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/Mutations/useUpdateArtworkList.ts
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModal.tsx
  src/__generated__/useCreateCollectionMutation.graphql.ts
  src/__generated__/useUpdateArtworkListMutation.graphql.ts
Labels: Jira Synced

#12548 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12549 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12551 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useVerifyIDMutation.graphql.ts
Labels: Squash On Green

#12555 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12557 fix: sort past shows by end date
  src/Apps/Shows/Routes/ShowsCity.tsx
  src/__generated__/ShowsCityQuery.graphql.ts
  src/__generated__/ShowsCity_Test_Query.graphql.ts
  src/__generated__/ShowsCity_city.graphql.ts
  src/__generated__/showsRoutes_ShowsCityQuery.graphql.ts
Labels: Jira Synced

#12560 feat(PRO-158): store user ID on self-initiated IDV
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
  src/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileFields.jest.tsx
  src/__generated__/SettingsEditProfileFields_Test_Query.graphql.ts
  src/__generated__/SettingsEditProfileFields_me.graphql.ts
  src/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts
Labels: Jira Synced

#12563 chore: Update list of people on meet the specialist page
  src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Labels: Merge On Green

#12564 feat: update activity panel empty state copy
  src/Components/Notifications/NotificationsEmptyStateByType.tsx
  src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx
Labels: Jira Synced

#12558 chore(NX-3560): Setup Auction Support Chat (Salesforce)
  src/Apps/Artwork/Components/ArtworkZendesk.tsx
  src/Apps/Auction/AuctionApp.tsx
  src/Components/SalesforceWrapper.tsx
  src/Server/config.ts
  src/Server/setup_sharify.ts
  src/Typings/sharify.d.ts
Labels: Jira Synced

#12568 chore: update list of specialists
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
Labels: Squash On Green

#12569 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12572 fix: Make SalesforceWrapper safer
  src/Apps/Order/OrderApp.tsx
  src/Apps/Order/__tests__/OrderApp.jest.tsx
  src/Components/SalesforceWrapper.tsx
Labels: Jira Synced, Squash On Green

#12575 fix(NX-3562): Remove duplicated component
  src/Apps/Artwork/Components/ArtworkChatBubble.tsx
Labels: Jira Synced

#12543 feat(FX-4804): Confirmation step in Create Alert modal flow
  src/Components/Artwork/Details.tsx
  src/Components/ArtworkGrid/ArtworkGridContext.tsx
  src/Components/SavedSearchAlert/Components/ConfirmationModalHeader.tsx
  src/Components/SavedSearchAlert/Components/ConfirmationStepFooter.tsx
  src/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButtonContainer.tsx
  src/Components/SavedSearchAlert/Components/__tests__/ConfirmationModalHeader.jest.tsx
  src/Components/SavedSearchAlert/Components/__tests__/ConfirmationStepFooter.jest.tsx
  src/Components/SavedSearchAlert/ConfirmationArtworksGrid.tsx
  src/Components/SavedSearchAlert/ConfirmationStepModal.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/Components/SavedSearchAlert/__tests__/ConfirmationArtworksGrid.jest.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/ConfirmationArtworksGridQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGrid_Test_Query.graphql.ts
  src/__generated__/ConfirmationStepFooterQuery.graphql.ts
  src/__generated__/ConfirmationStepFooter_Test_Query.graphql.ts
Labels: Jira Synced

#12577 chore: More updates to meet the specialist page GRO-1771
  src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Merge On Green
