Repository artsy/force, pull requests merged in 2023-05, with the labels that each got.

#12336 feat(PRO-85): use order state when routing after offer
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitOfferOrder.ts
  src/Apps/Order/Routes/__tests__/Review.jest.tsx
Labels: Jira Synced

#12335 chore: upgrade dd-trace to maintenance version
  package.json
  src/Server/datadog.ts
  yarn.lock
Labels: Jira Synced

#12342 fix: use correct param for redirect from `/collection/id:` to `/artist-series/:id`
  src/Apps/Collect/Server/__tests__/redirectCollectionToArtistSeries.jest.ts
  src/Apps/Collect/Server/redirectCollectionToArtistSeries.ts
Labels: Jira Synced, Squash On Green

#12343 Revert "feat(PRO-107): add tracking to settings IDV clicks"
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
  src/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileFields.jest.tsx
Labels: Merge On Green

#12344 Revert "Revert "feat(PRO-107): add tracking to settings IDV clicks""
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
  src/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileFields.jest.tsx
Labels: Jira Synced

#12347 fix(buyer-guarantee): fixes icon alignment
  src/Apps/BuyerGuarantee/Components/BuyerGuaranteeIcons.tsx
  src/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
Labels: Merge On Green

#12349 chore: Remove stale fallback card GRO-1690
  src/Apps/Home/Components/HomeContentCards/FallbackCards.tsx
Labels: Merge On Green

#12337 Fix(CX-3670): display artworks in 2/3/4 columns
  src/Apps/Auctions/Routes/EndingSoonAuctionsGrid.tsx
  src/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx
Labels: Jira Synced

#12309 chore(CX-3649): add redirect, href
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResult.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResultItem.jest.tsx
  src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistCareerHighlights.jest.tsx
  src/Apps/Auctions/EndingSoonAuctions/EndingSoonAuctions.tsx
  src/Apps/Components/LogInPrompt.tsx
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
  src/Server/middleware/userRequiredMiddleware.ts
  src/__generated__/AuctionResultTestQuery.graphql.ts
  src/__generated__/AuctionResult_auctionResult.graphql.ts
  src/__generated__/artistRoutes_AuctionResultQuery.graphql.ts
Labels: Jira Synced

#12350 fix: 301 redirect invalid artist urls from trending score a/b
  src/Apps/Artist/Server/__tests__/redirect.jest.ts
  src/Apps/Artist/Server/redirect.ts
  src/Apps/Artist/artistRoutes.tsx
Labels: Jira Synced, Squash On Green

#12355 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12361 fix: Hide install app on meet your new art advisor LP campaign
  src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx
Labels: Jira Synced, Squash On Green

#12364 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12360 feat: Add meet the specialists bios
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
Labels: Jira Synced

#12353 chore(CX-3652): Single Auction Result page - address late PR comments
  src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResult.tsx
  src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResultBackLink.tsx
  src/__generated__/AuctionResultTestQuery.graphql.ts
  src/__generated__/AuctionResult_auctionResult.graphql.ts
  src/__generated__/artistRoutes_AuctionResultQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#12365 fix: Adjust pill styling in SWA "Meet the Specialist" section
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
Labels: Squash On Green

#12366 chore(icons): replaces remaining icons
  package.json
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuthenticityCertificate.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCurrentBidInfo.jest.tsx
  src/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
  src/Apps/Artwork/Components/TrustSignals/BuyerGuarantee.tsx
  src/Apps/Artwork/Components/TrustSignals/SecurePayment.tsx
  src/Apps/Artwork/Components/TrustSignals/VerifiedSeller.tsx
  src/Apps/Auction/Components/AuctionActiveBids.tsx
  src/Apps/BuyerGuarantee/Components/BuyerGuaranteeIcons.tsx
  src/Apps/BuyerGuarantee/Components/BuyerGuaranteeTables.tsx
  src/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/SelectArtworkListsModal/SelectArtworkListItem.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/DollarCircleIcon.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/GlobeNetworkCircleIcon.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Highlights.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/StarCircleIcon.tsx
  src/Apps/Conversation/Components/ConversationCTA.tsx
  src/Apps/Conversation/Components/ConversationHeader.tsx
  src/Apps/Conversation/Components/OrderUpdate.tsx
  src/Apps/Conversation/Components/ReviewOfferCTA.tsx
  src/Apps/Order/Components/CreditCardDetails.tsx
  src/Apps/Order/Components/__tests__/CreditCardPicker.jest.tsx
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/__tests__/Accept.jest.tsx
  src/Apps/Order/Routes/__tests__/Counter.jest.tsx
  src/Apps/Order/Routes/__tests__/Respond.jest.tsx
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsLinkedAccounts.tsx
  src/Apps/Settings/Routes/Payments/Components/SettingsCreditCard.tsx
  src/Apps/Shows/Routes/ShowsAllCities.tsx
  src/Components/AuthDialog/Components/AuthDialogSocial.tsx
  src/Components/BrandCreditCardIcon.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileSubMenu.tsx
  src/Components/__stories__/BrandCreditCard.story.tsx
  yarn.lock
Labels: Merge On Green

#12370 chore: removes follow/saves flag
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
Labels: Jira Synced

#12369 chore(footer): removes footer feature flag
  src/Apps/Components/__tests__/AppShell.jest.tsx
  src/Components/Footer/FooterDownloadAppBanner.tsx
  src/Components/Footer/FooterDownloadAppBanner2.tsx
  src/Components/Footer/__tests__/Footer.jest.tsx
Labels: Merge On Green, Jira Synced

#12372 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/CareerHighlightModalStepTestQuery.graphql.ts
  src/__generated__/CareerHighlightsStepsQuery.graphql.ts
  src/__generated__/InsightsCareerHighlightRailTestQuery.graphql.ts
  src/__generated__/InsightsMedianSalePriceTestQuery.graphql.ts
  src/__generated__/InsightsOverviewTestQuery.graphql.ts
  src/__generated__/MyCollectionCreateArtworkTest_Query.graphql.ts
  src/__generated__/MyCollectionRouteQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_InsightsRouteQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionRouteQuery.graphql.ts
  src/__generated__/myCollectionRoutes_MyCollectionArtworkUploadQuery.graphql.ts
  src/__generated__/settingsRoutes_InsightsRouteQuery.graphql.ts
Labels: Squash On Green

#12377 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/CareerHighlightModalStepTestQuery.graphql.ts
  src/__generated__/CareerHighlightsStepsQuery.graphql.ts
  src/__generated__/InsightsCareerHighlightRailTestQuery.graphql.ts
  src/__generated__/InsightsMedianSalePriceTestQuery.graphql.ts
  src/__generated__/InsightsOverviewTestQuery.graphql.ts
  src/__generated__/MyCollectionCreateArtworkTest_Query.graphql.ts
  src/__generated__/MyCollectionRouteQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_InsightsRouteQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionRouteQuery.graphql.ts
  src/__generated__/myCollectionRoutes_MyCollectionArtworkUploadQuery.graphql.ts
  src/__generated__/settingsRoutes_InsightsRouteQuery.graphql.ts
Labels: Squash On Green

#12375 feat(FX-4657): mobile web search overlay
  src/Components/NavBar/NavBar.tsx
  src/Components/Search/NewSearch/Mobile/Overlay.tsx
  src/Components/Search/NewSearch/Mobile/OverlayBase.tsx
  src/Components/Search/NewSearch/Mobile/SearchBar.tsx
  src/Components/Search/NewSearch/NewSearchBar.tsx
  src/Components/Search/NewSearch/NewSearchBarInput.tsx
Labels: Jira Synced

#12379 chore: removes v2 types
  .storybook/preview.js
  package.json
  src/Apps/Article/Components/ArticleHTML.tsx
  src/Apps/Auction/Routes/AuctionFAQRoute.tsx
  src/Apps/Components/AppContainer.tsx
  src/Apps/Consign/Hooks/useSubmissionFlowSteps.ts
  src/Apps/Conversation/Components/DetailsSidebar.tsx
  src/Apps/Conversation/Components/OrderUpdate.tsx
  src/Apps/Conversation/Components/Reply.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx
  src/Apps/Page/Components/PageHTML.tsx
  src/Apps/Partner/Routes/Artists/ArtistsRoute.tsx
  src/Components/ArtworkFilter/Utils/useFilterLabelCountByKey.ts
  src/Components/CreditCardInput/CreditCardInput.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/OneTrustConsentStyles.ts
  src/Components/Sticky/Sticky.tsx
  src/Components/__tests__/ArtistBio.jest.tsx
  src/Components/__tests__/SelectedExhibitions.jest.tsx
  src/DevTools/MockBoot.tsx
  src/Server/middleware/errorHandler.tsx
  src/System/Router/Boot.tsx
  src/Utils/Hooks/useJump.tsx
  src/Utils/Hooks/useMatchMedia.ts
  src/Utils/Responsive/DeprecatedResponsive.tsx
  tsconfig.json
  yarn.lock
Labels: Merge On Green

#12384 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12378 fix(PRO-130): correct routing after in_review offer
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__tests__/Review.jest.tsx
Labels: Jira Synced

#12374 [CX-3647] feat: Release SWA landing page redesign
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
Labels: Jira Synced

#12387 fix(GRO-1713): Remove download link
  src/Apps/About/AboutApp.tsx
  src/Apps/About/AboutArtworksRail.tsx
  src/Components/NavBar/NavBar.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/AboutArtworksRailQuery.graphql.ts
  src/__generated__/AboutArtworksRail_marketingCollection.graphql.ts
Labels: Merge On Green, Jira Synced

#12394 fix(FX-4655): fixes new search bar quicklink navigation
  src/Components/Search/NewSearch/SuggestionItem/QuickNavigation.tsx
  src/Components/Search/NewSearch/SuggestionItem/QuickNavigationItem.tsx
Labels: Jira Synced

#12400 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12401 fix(artist): preserves query string
  src/Apps/Artist/artistRoutes.tsx
Labels: Jira Synced

#12402 fix: hide testimonials in SWA LP
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
Labels: Jira Synced

#12408 fix: cascading bids banner link has :visited state making it invisible
  src/Components/CascadingEndTimesBanner.tsx
Labels: Jira Synced

#12404 feat(FX-4659): mWeb search overlay - add search pills
  src/Components/NavBar/NavBar.tsx
  src/Components/Search/NewSearch/Mobile/MobileSearchBar.tsx
  src/Components/Search/NewSearch/Mobile/Overlay.tsx
  src/Components/Search/NewSearch/Mobile/OverlayBase.tsx
  src/Components/Search/NewSearch/Mobile/SearchBar.tsx
  src/Components/Search/NewSearch/NewSearchBar.tsx
  src/Components/Search/NewSearch/NewSearchBarInput.tsx
  src/Components/Search/NewSearch/NewSearchInputPills.tsx
  src/Components/Search/NewSearch/SearchInputContainer.tsx
  src/Components/Search/NewSearch/constants.ts
  src/Components/Search/NewSearch/utils/reportPerformanceMeasurement.ts
  src/Components/Search/NewSearch/utils/shouldStartSearching.ts
  src/__generated__/MobileSearchBarRefetchQuery.graphql.ts
  src/__generated__/MobileSearchBarSuggestQuery.graphql.ts
  src/__generated__/MobileSearchBar_viewer.graphql.ts
Labels: Jira Synced

#12406 fix(alerts): fixes children type
  src/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButtonV2.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.jest.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavBarLoggedInActions.tsx
  src/Components/NavBar/__tests__/NavBar.jest.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertCreate.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFind.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingCounts.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowFind.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveFind.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingAlerts.jest.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingFollows.jest.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingSaves.jest.tsx
  src/Components/ProgressiveOnboarding/withProgressiveOnboardingCounts.tsx
  src/Components/SavedSearchAlert/Components/ActiveFilterPillsAndCreateAlert.tsx
  src/Components/SavedSearchAlert/Components/__tests__/ActiveFilterPillsAndCreateAlert.jest.tsx
  src/__generated__/ProgressiveOnboardingCountsQuery.graphql.ts
  src/__generated__/ProgressiveOnboardingCounts_me.graphql.ts
  src/__generated__/withProgressiveOnboardingCountsQuery.graphql.ts
Labels: Merge On Green, Jira Synced

#12407 feat(TX-1168): update add new address button + collector profile cleanup
  src/Apps/Order/Components/SavedAddresses.tsx
  src/Apps/Order/Components/__tests__/SavedAddresses.jest.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
Labels: Jira Synced

#12412 refactor: clean up legacy empty auction handling
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
Labels: Jira Synced

#12413 fix: dropdown closes clicking on footer
  src/Components/Search/NewSearch/NewSearchBarFooter.tsx
  src/Components/Search/NewSearch/NewSearchBarInput.tsx
Labels: Jira Synced, Squash On Green

#12397 feat(TX-1151): Update address form layouts in the checkout flow
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/Components/Address/AddressModalFields.tsx
  src/Components/AddressForm.tsx
Labels: Jira Synced

#12433 fix(artist): fixes content shift for market signals component
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/MarketStatsPlaceholder.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/MarketStats.jest.tsx
  src/__generated__/MarketStatsQuery.graphql.ts
Labels: Merge On Green

#12431 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12383 feat(TX-1149): Address form with verification
  src/Apps/Order/Components/CheckoutAddress.tsx
  src/Apps/Order/Components/PhoneNumberForm.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/Components/CountrySelect.tsx
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/Shipping_me.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
Labels: Jira Synced

#12432 fix(artist): fixes empty state for filters on auction-results
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/ArtistAuctionResultsEmptyState.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
Labels: Jira Synced

#12439 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12435 feat(artwork lists): improve name handling
  src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/EditArtworkListModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListForm/ArtworkListForm.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModal.tsx
  src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/__tests__/CreateNewListModal.jest.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced, Squash On Green

#12443 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12437 fix: keyboard arrow navigation
  src/Components/Search/NewSearch/NewSearchBarFooter.tsx
  src/Components/Search/NewSearch/NewSearchBarInput.tsx
  src/Components/Search/NewSearch/SuggestionItem/SuggestionItemLink.ts
Labels: Jira Synced

#12447 chore: add error message event tracking for payment step
  package.json
  src/Apps/Order/Routes/Payment/index.tsx
  yarn.lock
Labels: Jira Synced

#12444 feat(NX-3543): automated inquiry messages for contact gallery modal
  src/Components/Inquiry/Hooks/useInquiryContext.tsx
  src/Components/Inquiry/Views/InquiryInquiry.tsx
  src/Components/Inquiry/__tests__/Views/InquirySpecialist.jest.tsx
Labels: Jira Synced

#12436 feat(TX-1200): Address verification modals
  src/Apps/Order/Components/CheckoutAddress.tsx
  src/Apps/Order/Components/__tests__/CheckoutAddress.jest.tsx
Labels: Jira Synced, Draft

#12460 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12346 Chore (PX-5561) - Add shipping disclaimer copy for Artsy Shipping Offers (web)
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Components/__tests__/TransactionDetailsSummary.jest.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/ConversationPageQuery.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/DetailsSidebar_Test_Query.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/TransactionDetailsSummaryItemTestQuery.graphql.ts
  src/__generated__/TransactionDetailsSummaryItem_order.graphql.ts
  src/__generated__/conversationRoutes_DetailQuery.graphql.ts
  src/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/orderRoutes_StatusQuery.graphql.ts
Labels: Jira Synced

#12463 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12446 chore(deps): removes unused dependencies
  package.json
  yarn.lock
Labels: Merge On Green

#12440 fix(artwork lists): improve a11y by making focus visible
  src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListItem.tsx
Labels: Jira Synced

#12465 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12466 fix(artist): update smoke test to match latest meta description format
  cypress/e2e/artist.cy.js
Labels: Squash On Green

#12468 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12469 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12456 feat: analytic events for new search bar container
  src/Components/Search/NewSearch/Mobile/Overlay.tsx
  src/Components/Search/NewSearch/NewSearchBarFooter.tsx
  src/Components/Search/NewSearch/NewSearchBarInput.tsx
  src/Components/Search/NewSearch/constants.ts
Labels: Jira Synced, Squash On Green

#12476 chore(GRO-1671): update meta tags based on the selected tab on the Artist page
  cypress/e2e/artist.cy.js
  src/Apps/Artist/Components/ArtistMeta/ArtistMeta.tsx
  src/Apps/Artist/Components/ArtistMeta/__tests__/helpers.jest.ts
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx
  src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
  src/Apps/Artist/Utils/__tests__/computeTitle.jest.tsx
  src/Apps/Artist/Utils/computeTitle.ts
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/__generated__/ArtistMeta_Test_Query.graphql.ts
  src/__generated__/ArtistMeta_artist.graphql.ts
  src/__generated__/ArtistOverviewRoute_Test_Query.graphql.ts
  src/__generated__/ArtistOverviewRoute_artist.graphql.ts
  src/__generated__/ArtistWorksForSaleRoute_artist.graphql.ts
  src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts
  src/__generated__/artistRoutes_ArtistSubAppQuery.graphql.ts
  src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
  src/__generated__/artistRoutes_OverviewQuery.graphql.ts
  src/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
Labels: Jira Synced
