Repository artsy/force, pull requests merged in 2023-10, with the labels that each got.

#12970 Deploy
  src/Components/Address/AddressForm.tsx
  src/Components/Address/__tests__/AddressForm.jest.tsx
  src/Components/Address/__tests__/useAddressAutocomplete.jest.ts
  src/Components/Address/useAddressAutocomplete.ts
Labels: Jira Synced

#12974 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12977 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12978 chore [EMI-1494]: disable autocomplete on billing page
  src/Components/Address/AddressForm.tsx
Labels: Jira Synced

#12979 refactor(filter): simplifies filter components
  src/Components/ArtworkFilter/ArtworkFilters/FilterExpandable.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/FilterExpandable.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/useScrollContext.tsx
  src/Components/ArtworkFilter/Utils/getElementParams.ts
  src/Components/ArtworkFilter/index.tsx
Labels: Merge On Green

#12973 fix(alerts): don't include current artwork in suggested inventory
  src/Apps/Artwork/Components/ArtworkCreateAlertButton.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateArtworkAlert.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/CreateArtworkAlertSection.jest.tsx
  src/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButtonContainer.tsx
  src/Components/SavedSearchAlert/ConfirmationArtworksGrid.tsx
  src/Components/SavedSearchAlert/ConfirmationStepModal.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertContext.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/__generated__/CreateArtworkAlertSection_Test_Query.graphql.ts
  src/__generated__/CreateArtworkAlertSection_artwork.graphql.ts
Labels: Jira Synced

#12972 tracks clicks to read more link
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetailsAdditionalInfo.jest.tsx
Labels: Jira Synced

#12986 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useAddCreditCardAndUpdateProfileMutation.graphql.ts
  src/__generated__/useUpdateMyUserProfileMutation.graphql.ts
  src/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Squash On Green

#12989 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12983 Deploy
  .env.example
  data/schema.graphql
  package.json
  src/Apps/Artwork/Components/ArtworkCreateAlertButton.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetailsAdditionalInfo.jest.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateArtworkAlert.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/CreateArtworkAlertSection.jest.tsx
  src/Components/Address/AddressForm.tsx
  src/Components/Address/__tests__/useAddressAutocomplete.jest.ts
  src/Components/Address/useAddressAutocomplete.ts
  src/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButtonContainer.tsx
  src/Components/SavedSearchAlert/ConfirmationArtworksGrid.tsx
  src/Components/SavedSearchAlert/ConfirmationStepModal.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertContext.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/Components/SavedSearchAlert/useUserPhoneNumber.tsx
  src/__generated__/CreateArtworkAlertSection_Test_Query.graphql.ts
  src/__generated__/CreateArtworkAlertSection_artwork.graphql.ts
  src/__generated__/useAddCreditCardAndUpdateProfileMutation.graphql.ts
  src/__generated__/useUpdateMyUserProfileMutation.graphql.ts
  src/__generated__/useUpdateSettingsInformationMutation.graphql.ts
  src/__generated__/useUserPhoneNumberQuery.graphql.ts
  src/tests.ts
  yarn.lock
Labels: Jira Synced

#12993 feat(EMI-1335): add error msg for credit_card_deactivated
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__tests__/Review.jest.tsx
Labels: Jira Synced

#12995 fix: Disable autocomplete on billing page.
  src/Components/Address/AddressForm.tsx
Labels: Jira Synced

#12997 fix(filter): includes selected prop
  src/Components/SavedSearchAlert/Components/SavedSearchAlertPills.tsx
Labels: Merge On Green

#13004 fix: updates `Artist#image` to `Artist#coverArtwork`
  src/Components/Cells/CellArtist.tsx
  src/Components/Cells/__tests__/CellArtist.jest.tsx
  src/Components/EntityHeaders/EntityHeaderArtist.tsx
  src/__generated__/ArtistInfoQuery.graphql.ts
  src/__generated__/ArtistInfo_Test_Query.graphql.ts
  src/__generated__/ArtistRelatedArtistsRailQuery.graphql.ts
  src/__generated__/ArtistRelatedArtistsRail_Test_Query.graphql.ts
  src/__generated__/ArtistsIndexFragmentContainer_Test_Query.graphql.ts
  src/__generated__/ArtworkRelatedArtistsPaginationQuery.graphql.ts
  src/__generated__/ArtworkRelatedArtistsQuery.graphql.ts
  src/__generated__/CareerHighlightModalStepTestQuery.graphql.ts
  src/__generated__/CareerHighlightsStepsQuery.graphql.ts
  src/__generated__/CellArtistFragmentContainer_Test_Query.graphql.ts
  src/__generated__/CellArtistStoryQuery.graphql.ts
  src/__generated__/CellArtist_artist.graphql.ts
  src/__generated__/CellPartnerArtistFragmentContainer_Test_Query.graphql.ts
  src/__generated__/EntityHeaderArtistFragmentContainer_Test_Query.graphql.ts
  src/__generated__/EntityHeaderArtistStoryQuery.graphql.ts
  src/__generated__/EntityHeaderArtist_artist.graphql.ts
  src/__generated__/EntityTooltipArtistQuery.graphql.ts
  src/__generated__/FollowArtistPopoverQuery.graphql.ts
  src/__generated__/FollowArtistPopoverRowMutation.graphql.ts
  src/__generated__/HomeTrendingArtistsRailQuery.graphql.ts
  src/__generated__/HomeTrendingArtistsRail_Test_Query.graphql.ts
  src/__generated__/InsightsMedianSalePriceTestQuery.graphql.ts
  src/__generated__/MarketingTrendingArtistsRailQuery.graphql.ts
  src/__generated__/MyCollectionCreateArtworkTest_Query.graphql.ts
  src/__generated__/OnboardingOrderedSetQuery.graphql.ts
  src/__generated__/OnboardingOrderedSet_Test_Query.graphql.ts
  src/__generated__/OnboardingSearchResultsQuery.graphql.ts
  src/__generated__/OnboardingSearchResults_Test_Query.graphql.ts
  src/__generated__/PartnerArtistsCarouselRendererQuery.graphql.ts
  src/__generated__/SettingsSavesArtistsQuery.graphql.ts
  src/__generated__/SettingsSavesArtists_test_Query.graphql.ts
  src/__generated__/artistsRoutes_ArtistsQuery.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/collectRoutes_CollectionQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_InsightsRouteQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts
  src/__generated__/exampleRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionInsightsCollectorProfileRoutesQuery.graphql.ts
  src/__generated__/myCollectionInsightsRoutesQuery.graphql.ts
  src/__generated__/myCollectionRoutes_MyCollectionArtworkUploadQuery.graphql.ts
  src/__generated__/settingsRoutes_InsightsRouteQuery.graphql.ts
Labels: Merge On Green, Jira Synced

#13016 chore: update the text
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
Labels: Jira Synced

#13012 Deploy
  src/Apps/Order/Components/OfferInput.tsx
  src/Apps/Order/Components/OfferNote.tsx
  src/Apps/Order/Components/__tests__/OfferInput.jest.tsx
  src/Apps/Order/Components/__tests__/OfferNote.jest.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/Respond/index.tsx
Labels: Jira Synced

#13023 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13019 chore(onyx-139): Remove New prefix from search component names
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/__tests__/NavBar.jest.tsx
  src/Components/Search/Mobile/MobileSearchBar.tsx
  src/Components/Search/Mobile/Overlay.tsx
  src/Components/Search/Mobile/OverlayBase.tsx
  src/Components/Search/Mobile/SearchResultsList.tsx
  src/Components/Search/Mobile/SearchResultsList/ContentPlaceholder.tsx
  src/Components/Search/Mobile/SearchResultsList/NoResults.tsx
  src/Components/Search/NavBarSearchInputContainer.tsx
  src/Components/Search/SearchBar.tsx
  src/Components/Search/SearchBarFooter.tsx
  src/Components/Search/SearchBarInput.tsx
  src/Components/Search/SearchInputPills.tsx
  src/Components/Search/StaticSearchContainer.tsx
  src/Components/Search/SuggestionItem/DefaultSuggestion.tsx
  src/Components/Search/SuggestionItem/Highlight.ts
  src/Components/Search/SuggestionItem/QuickNavigationItem.tsx
  src/Components/Search/SuggestionItem/SuggestionItem.tsx
  src/Components/Search/SuggestionItem/SuggestionItemLink.ts
  src/Components/Search/SuggestionItem/SuggestionItemPreview.tsx
  src/Components/Search/constants.ts
  src/Components/Search/utils/formatOptions.ts
  src/Components/Search/utils/getLabel.ts
  src/Components/Search/utils/getSearchTerm.ts
  src/Components/Search/utils/reportPerformanceMeasurement.ts
  src/Components/Search/utils/shouldStartSearching.ts
Labels: Jira Synced

#13028 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesApp_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/__generated__/ArtistWorksForSaleRoute_artist.graphql.ts
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/AuctionAppTestQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterTestQuery.graphql.ts
  src/__generated__/AuctionArtworkFilter_viewer.graphql.ts
  src/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
  src/__generated__/ConfirmationArtworksGridQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGrid_Test_Query.graphql.ts
  src/__generated__/FairArtworksQuery.graphql.ts
  src/__generated__/FairArtworks_Query.graphql.ts
  src/__generated__/FairArtworks_fair.graphql.ts
  src/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/__generated__/GeneArtworkFilter_Query.graphql.ts
  src/__generated__/GeneArtworkFilter_gene.graphql.ts
  src/__generated__/GeneShow_Test_Query.graphql.ts
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
  src/__generated__/SavedSearchAlertEditForm_Test_Query.graphql.ts
  src/__generated__/SavedSearchAlertEditForm_artworksConnection.graphql.ts
  src/__generated__/SearchResultsArtworks_Query.graphql.ts
  src/__generated__/SearchResultsArtworks_viewer.graphql.ts
  src/__generated__/ShowApp_Test_Query.graphql.ts
  src/__generated__/ShowApp_show.graphql.ts
  src/__generated__/ShowArtworksQuery.graphql.ts
  src/__generated__/SuggestedArtworksModalGridQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/TagApp_Test_Query.graphql.ts
  src/__generated__/TagArtworkFilterQuery.graphql.ts
  src/__generated__/TagArtworkFilter_Query.graphql.ts
  src/__generated__/TagArtworkFilter_tag.graphql.ts
  src/__generated__/WorksQuery.graphql.ts
  src/__generated__/WorksTL_Query.graphql.ts
  src/__generated__/Works_Query.graphql.ts
  src/__generated__/Works_partner.graphql.ts
  src/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
  src/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
  src/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/collectRoutes_CollectionQuery.graphql.ts
  src/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/fairRoutes_FairArtworksQuery.graphql.ts
  src/__generated__/geneRoutes_GeneShowQuery.graphql.ts
  src/__generated__/partnerRoutes_WorksQuery.graphql.ts
  src/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
  src/__generated__/showRoutes_ShowQuery.graphql.ts
  src/__generated__/tagRoutes_TagQuery.graphql.ts
Labels: Squash On Green

#13026 feat(DIA-184): inline follow counts on mobile
  src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx
  src/Apps/Partner/Components/PartnerHeader/index.tsx
  src/Components/FollowButton/Button.tsx
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Components/FollowButton/FollowGeneButton.tsx
  src/Components/FollowButton/FollowProfileButton.tsx
Labels: Jira Synced

#13031 feat(DIA-216,DIA-223): Re-structure existing layout; adds clear all button
  src/Components/ArtworkFilter/ArtworkFilterActiveFilters.tsx
  src/Components/ArtworkFilter/index.tsx
Labels: Merge On Green, Jira Synced

#13037 fix(filters): fixes issue with range + labeled input interaction
  src/Components/NumericInput.tsx
Labels: Jira Synced

#13025 Refactor: Checkout flow shipping step
  .secrets.baseline
  src/Apps/Order/Mutations/CreateUserAddress.ts
  src/Apps/Order/Mutations/SetShipping.ts
  src/Apps/Order/Routes/Shipping2/AddressModal.jest.tsx
  src/Apps/Order/Routes/Shipping2/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/SavedAddressItem2.tsx
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/ShippingContext.ts
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Order/Routes/Shipping2/shippingUtils.ts
  src/Apps/Order/orderRoutes.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/Components/Address/utils.ts
  src/Components/CountrySelect.tsx
  src/__generated__/FulfillmentDetailsForm_me.graphql.ts
  src/__generated__/FulfillmentDetailsForm_order.graphql.ts
  src/__generated__/SavedAddresses2Mutation_Test_Query.graphql.ts
  src/__generated__/SavedAddresses2RefetchQuery.graphql.ts
  src/__generated__/SavedAddresses2_me.graphql.ts
  src/__generated__/Shipping2TestQuery.graphql.ts
  src/__generated__/Shipping2_me.graphql.ts
  src/__generated__/Shipping2_order.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
Labels: Jira Synced

#13043 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13044 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/createSavedSearchAlertMutation.graphql.ts
  src/__generated__/useEditSavedSearchAlertMutation.graphql.ts
Labels: Squash On Green

#13046 fix(progressive-onboarding): removes lazyload to prevent layout shift
  src/Components/ProgressiveOnboarding/withProgressiveOnboardingCounts.tsx
Labels: Jira Synced

#13050 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13041 feat(artist series filter): add to artist page's artwork grid
  .eslintrc.js
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
  src/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilters.jest.tsx
  src/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
  src/Apps/Artist/artistRoutes.tsx
  src/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/ArtworkFilter/ArtworkFilters/ArtistSeriesFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/ArtistSeriesFilter.jest.tsx
  src/Components/ArtworkFilter/Utils/__tests__/countChangedFilters.jest.ts
  src/Components/ArtworkFilter/Utils/__tests__/getSelectedFiltersCounts.jest.ts
  src/Components/ArtworkFilter/Utils/__tests__/urlBuilder.jest.tsx
  src/Components/ArtworkFilter/Utils/allowedFilters.ts
  src/Components/ArtworkFilter/Utils/isDefaultFilter.tsx
  src/Components/SavedSearchAlert/constants.ts
Labels: Jira Synced, Squash On Green

#13053 fix: feedback mutation
  src/Apps/Search/Components/SendFeedback.tsx
  src/__generated__/SendFeedbackSearchResultsMutation.graphql.ts
Labels: Jira Synced

#13051 feat(filters): adds rarity and medium quick filters
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Components/ArtworkFilter/ArtworkFilters/AttributionClassFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/FilterQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/__tests__/FilterQuick.jest.tsx
  src/Components/ArtworkFilter/index.tsx
  src/Components/SavedSearchAlert/Utils/extractPills.ts
Labels: Merge On Green, Jira Synced

#13058 feat(dia-220): implements price range quick filter
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/PriceRangeFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilterSort.tsx
  src/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/FilterQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/PriceRangeFilterQuick.tsx
  src/Components/ArtworkFilter/index.tsx
Labels: Jira Synced

#13060 fix(EMI-1336): don't show cookie banner for Eigen
  src/Components/CookieConsentManager/CookieConsentManager.tsx
Labels: Jira Synced

#13059 chore(ONYX-271): cleanup ff related code
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormDesktop.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormMobile.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
Labels: Jira Synced

#13062 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13064 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
Labels: Squash On Green

#13066 fix(artist): properly tearsdown auth dialog setup
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/ArtistSubApp.tsx
  src/Utils/Hooks/__tests__/useScrollToOpenArtistAuthModal.jest.ts
  src/Utils/Hooks/useScrollToOpenArtistAuthModal.ts
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistApp_artist.graphql.ts
  src/__generated__/ArtistSubApp_artist.graphql.ts
  src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts
  src/__generated__/artistRoutes_ArtistSubAppQuery.graphql.ts
  src/__generated__/useScrollToOpenArtistAuthModalQuery.graphql.ts
Labels: Jira Synced

#13057 Deploy
  data/schema.graphql
  package.json
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/ArtistSubApp.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/PriceRangeFilter.tsx
  src/Apps/Collect/collectRoutes.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormDesktop.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormMobile.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilterSort.tsx
  src/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/FilterQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/PriceRangeFilterQuick.tsx
  src/Components/ArtworkFilter/index.tsx
  src/Components/CookieConsentManager/CookieConsentManager.tsx
  src/Components/SavedSearchAlert/Components/DetailsInput.tsx
  src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
  src/Utils/Hooks/__tests__/useScrollToOpenArtistAuthModal.jest.ts
  src/Utils/Hooks/useScrollToOpenArtistAuthModal.ts
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistApp_artist.graphql.ts
  src/__generated__/ArtistSubApp_artist.graphql.ts
  src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts
  src/__generated__/artistRoutes_ArtistSubAppQuery.graphql.ts
  src/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/useScrollToOpenArtistAuthModalQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#13068 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13070 chore(lib): Update jest swc libs to latst
  package.json
  yarn.lock
Labels: Merge On Green

#13069 Deploy
  data/schema.graphql
  package.json
  src/Apps/Order/Components/AddressVerificationFlow.tsx
  src/Apps/Order/Components/PriceOptions.tsx
  src/Apps/Order/Components/ShippingQuotes.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Shipping2/AddressModal.jest.tsx
  src/Apps/Order/Routes/Shipping2/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/ShippingContext.ts
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Order/Routes/__tests__/Offer.jest.tsx
  src/Components/CountrySelect.tsx
  yarn.lock
Labels: Jira Synced

#13073 chore: cleanup unused default alert placeholder value
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistWorksForSaleEmpty.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/ArtworkAuctionCreateAlertTooltip.jest.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksModal.jest.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksModalGrid.jest.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksShelf.jest.tsx
  src/Apps/Artwork/Components/ArtworkCreateAlertButton.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateArtworkAlert.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Components/SavedSearchAlert/Components/__tests__/ConfirmationModalHeader.jest.tsx
  src/Components/SavedSearchAlert/Components/__tests__/SavedSearchCreateAlertButtonContainer.jest.tsx
  src/Components/SavedSearchAlert/Utils/__tests__/savedSearchCriteria.jest.ts
  src/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
  src/Components/SavedSearchAlert/types.ts
Labels: Jira Synced

#13076 feat(dia-226): filter experiment set up
  src/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx
  src/Components/ArtworkFilter/index.tsx
  src/Components/ArtworkFilter/useRevisedArtworkFilters.ts
  src/System/useFeatureFlag.tsx
Labels: Merge On Green, Jira Synced

#13082 fix(my-collection): Remove non-null assertion crasher
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarTitleInfo.tsx
Labels: Merge On Green

#13084 chore(eslint): relax non-null assertions in tests
  .eslintrc.js
Labels: Squash On Green

#13085 feat(dia-295): filter q/a
  src/Components/ArtworkFilter/ArtworkFilterDrawer.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/FilterQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/PriceRangeFilterQuick.tsx
  src/Components/ArtworkFilter/index.tsx
Labels: Merge On Green, Jira Synced

#13078 feat(EMI-1512): add order tracking helper for new shipping route
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Order/Utils/useOrderTracking.tsx
Labels: Jira Synced

#13090 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13091 feat: Include news in artist articles section DIA-291
  src/Apps/Artist/Routes/Articles/ArtistArticlesRoute.tsx
  src/__generated__/ArtistArticlesRouteQuery.graphql.ts
  src/__generated__/ArtistArticlesRoute_Test_Query.graphql.ts
  src/__generated__/ArtistArticlesRoute_artist.graphql.ts
  src/__generated__/artistRoutes_ArticlesQuery.graphql.ts
Labels: Merge On Green

#13086 Deploy
  .eslintrc.js
  data/schema.graphql
  src/Apps/Artist/Routes/Articles/ArtistArticlesRoute.tsx
  src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Order/Utils/useOrderTracking.tsx
  src/Components/ArtworkFilter/ArtworkFilterDrawer.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/FilterQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/PriceRangeFilterQuick.tsx
  src/Components/ArtworkFilter/index.tsx
  src/__generated__/ArtistArticlesRouteQuery.graphql.ts
  src/__generated__/ArtistArticlesRoute_Test_Query.graphql.ts
  src/__generated__/ArtistArticlesRoute_artist.graphql.ts
  src/__generated__/artistRoutes_ArticlesQuery.graphql.ts
Labels: Jira Synced
