Repository artsy/force, pull requests merged in 2023-07, with the labels that each got.

#12585 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useAddArtistYouCollectMutation.graphql.ts
Labels: Squash On Green

#12576 fix(FX-4827): fixes new search bar for small screens
  src/Components/Search/NewSearch/NewSearchBarFooter.tsx
  src/Components/Search/NewSearch/NewSearchBarInput.tsx
Labels: Jira Synced

#12567 feat(FX-4648): add missing analytic tracking for new search behaviour
  src/Components/Search/NewSearch/Mobile/Overlay.tsx
  src/Components/Search/NewSearch/Mobile/SearchResultsList.tsx
  src/Components/Search/NewSearch/NewSearchBarFooter.tsx
  src/Components/Search/NewSearch/NewSearchBarInput.tsx
  src/Components/Search/NewSearch/SuggestionItem/NewSuggestionItem.tsx
  src/Components/Search/NewSearch/SuggestionItem/QuickNavigation.tsx
Labels: Jira Synced

#12590 [#FF] refactor: bank account auto-selection hook
  src/Apps/Order/Components/BankAccountPicker.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Utils/orderUtils.ts
Labels: Draft

#12601 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12604 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12607 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12605 feat(onyx-114): Do not dispatch new artwork lists behavior when clicking on 'Watch lot' on artwork page
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButtonV2.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActionsSaveButtonV2.jest.tsx
Labels: Jira Synced

#12612 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12617 feat: do not use spot in staging
  hokusai/staging.yml
Labels: Jira Synced

#12602 feat: make address verification query (EMI-1242)
  src/Apps/Order/Components/AddressVerificationFlow.tsx
  src/Apps/Order/Components/CheckoutAddress.tsx
  src/Apps/Order/Components/__tests__/CheckoutAddress.jest.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/Components/AddressForm.tsx
  src/__generated__/AddressVerificationFlowQuery.graphql.ts
  src/__generated__/AddressVerificationFlow_verifiedAddressResult.graphql.ts
Labels: Jira Synced, Draft

#12626 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12628 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12625 feat(alerts): update confirmation messages for various cases
  src/Components/SavedSearchAlert/Components/__tests__/ConfirmationModalHeader.jest.tsx
  src/Components/SavedSearchAlert/ConfirmationArtworksGrid.tsx
  src/Components/SavedSearchAlert/__tests__/ConfirmationArtworksGrid.jest.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#12629 fix: only perform address verification once
  src/Apps/Order/Routes/Shipping/index.tsx
Labels: Jira Synced

#12622 feat: use two k8s deployments
  hokusai/production.yml
  hokusai/staging.yml
Labels: Jira Synced

#12638 fix(toasts): adjust position when cookie consent banner is displayed
  src/Apps/Components/constants.ts
Labels: Jira Synced, Squash On Green

#12639 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12627 fix(onyx-147): fix impossible to navigate to a See full results option using keyboard arrows
  src/Components/Search/NewSearch/NewSearchBarFooter.tsx
  src/Components/Search/NewSearch/NewSearchBarInput.tsx
Labels: Jira Synced

#12640 fix(onyx-145): update the search input field when scrolling through options using keyboard arrows
  src/Apps/Search/SearchApp.tsx
  src/Components/Search/NewSearch/NewSearchBar.tsx
  src/Components/Search/NewSearch/NewSearchBarInput.tsx
Labels: Jira Synced

#12642 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12643 fix(ONYX-117): SWA LP copy update
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/CollectorsOverview.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Footer.jest.tsx
Labels: Jira Synced

#12644 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12645 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12646 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12649 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#12647 fix(onyx-162): Fix pill navigation when it doesn’t remove the arrow button when scrolled all the way over to the right
  src/Components/Search/NewSearch/NewSearchInputPills.tsx
Labels: Jira Synced

#12655 feat(progressive-onboarding): displays follow tip to logged out users
  src/Apps/Artist/Components/ArtistHeader/__tests__/ArtistHeader.jest.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingContext.jest.tsx
  src/Components/ProgressiveOnboarding/withProgressiveOnboardingCounts.tsx
  src/Utils/Hooks/useAuthIntent/index.tsx
Labels: Jira Synced

#12654 Use different feature flags for US and international address verification
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
Labels: Jira Synced

#12523 feat: remove user checks from artwork lists feature toggle
  src/Apps/CollectorProfile/Routes/Saves2/useCheckIfArtworkListsEnabled.ts
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
Labels: Jira Synced, Do not merge

#12660 fix: avoid double triggering address verification modal
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
Labels: Jira Synced

#12663 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
  src/__generated__/ArtistCareerHighlights_artist.graphql.ts
  src/__generated__/ArtistHeader2_artist.graphql.ts
  src/__generated__/ArtistInsightBadges_Test_Query.graphql.ts
  src/__generated__/ArtistInsightBadges_artist.graphql.ts
Labels: Squash On Green

#12666 fix: perform basic form validation before address verification
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
Labels: Jira Synced

#12624 feat(EMI-1285): add tracking to address validation on checkout
  src/Apps/Order/Components/AddressVerificationFlow.tsx
Labels: Jira Synced

#12669 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
