Repository artsy/force, pull requests merged in 2024-02, with the labels that each got.

#13451 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13452 fix(consign): fixes inverted contrast; image placeholders
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/TextAndImageLayout.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
Labels: Jira Synced

#13324 chore: fix remaining shipping2 tests, complete initial refactor
  .secrets.baseline
  src/Apps/Order/Routes/Shipping2/Components/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Components/SaveAndContinueButton.tsx
  src/Apps/Order/Routes/Shipping2/Components/SavedAddressItem2.tsx
  src/Apps/Order/Routes/Shipping2/Components/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/Components/ShippingQuotes2.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/Hooks/__tests__/useUserAddressUpdates.jest.ts
  src/Apps/Order/Routes/Shipping2/Hooks/useBackToFulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/Hooks/useHandleExchangeError.tsx
  src/Apps/Order/Routes/Shipping2/Hooks/useHandleSaveFulfillmentDetails.ts
  src/Apps/Order/Routes/Shipping2/Hooks/useHandleUserAddressUpdates.ts
  src/Apps/Order/Routes/Shipping2/Hooks/useSaveSelectedShippingQuote.tsx
  src/Apps/Order/Routes/Shipping2/Hooks/useSelectFirstShippingQuote.tsx
  src/Apps/Order/Routes/Shipping2/Hooks/useUserAddressUpdates.ts
  src/Apps/Order/Routes/Shipping2/Mutations/useSaveFulfillmentDetails.ts
  src/Apps/Order/Routes/Shipping2/ShippingContext.tsx
  src/Apps/Order/Routes/Shipping2/Utils/computeOrderData.ts
  src/Apps/Order/Routes/Shipping2/Utils/shippingUtils.ts
  src/Apps/Order/Routes/Shipping2/__tests__/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Order/Utils/getErrorDialogCopy.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/Components/__tests__/Utils/addressForm2.ts
  src/System/useFeatureFlag.tsx
  src/__generated__/SavedAddresses2Mutation_Test_Query.graphql.ts
  src/__generated__/SavedAddresses2TestQuery.graphql.ts
  src/__generated__/SavedAddresses2_me.graphql.ts
  src/__generated__/Shipping2TestQuery.graphql.ts
  src/__generated__/Shipping2_me.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/useCreateSavedAddressMutation.graphql.ts
  src/__generated__/useDeleteSavedAddressMutation.graphql.ts
  src/__generated__/useSaveFulfillmentDetailsMutation.graphql.ts
  src/__generated__/useUpdateSavedAddressMutation.graphql.ts
  src/__generated__/useUpdateUserDefaultAddressMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#13391 feat: adds an availability filter for use on artwork grids
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
  src/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilters.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/AvailabilityFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/AvailabilityFilter.jest.tsx
Labels: Jira Synced, Squash On Green, hackathon

#13450 feat(onyx-705): viewing rooms notification page
  src/Components/Notifications/Notification.tsx
  src/Components/Notifications/NotificationViewingRoom.tsx
  src/Components/Notifications/NotificationViewingRoomsList.tsx
  src/Components/Notifications/ViewingRoomPublishedNotification.tsx
  src/Components/Notifications/__tests__/ViewingRoomPublishedNotification.jest.tsx
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/NotificationViewingRoom_viewingRoom.graphql.ts
  src/__generated__/NotificationViewingRoomsList_viewingRoomsConnection.graphql.ts
  src/__generated__/ViewingRoomPublishedNotification_notification.graphql.ts
  src/__generated__/ViewingRoomPublishedNotification_test_Query.graphql.ts
Labels: Jira Synced

#13461 fix: remove followers count on mobile view
  src/Apps/Partner/Components/PartnerHeader/index.tsx
Labels: Jira Synced

#13465 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13426 chore(alerts): clean up `onyx_artwork_alert_modal_v2` flag and dead code
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistWorksForSaleEmpty.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkCreateAlertButton.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBiddingClosedMessage.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlert.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkSidebarCreateAlert.jest.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormDesktop.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormMobile.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.ts
  src/Components/Alert/AlertProvider.tsx
  src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx
  src/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButton.tsx
  src/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButtonContainer.tsx
  src/Components/SavedSearchAlert/Components/__tests__/SavedSearchCreateAlertButtonContainer.jest.tsx
  src/__generated__/ArtworkAuctionCreateAlertHeader_Test_Query.graphql.ts
  src/__generated__/ArtworkAuctionCreateAlertHeader_artwork.graphql.ts
  src/__generated__/ArtworkCreateAlertButton_artwork.graphql.ts
  src/__generated__/ArtworkSidebarAuctionInfoPollingQuery.graphql.ts
  src/__generated__/ArtworkSidebarBiddingClosedMessage_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCurrentBidInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#13471 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13476 Chore(copy): Fairs -> Fairs & Events
  src/Apps/Fairs/Routes/FairsIndex.tsx
  src/Apps/Fairs/Routes/__tests__/FairsIndex.jest.tsx
  src/Apps/Home/Components/HomeCurrentFairs.tsx
  src/Apps/Home/__tests__/HomeCurrentFairs.jest.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
  src/Components/NavBar/__tests__/NavBarTracking.jest.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#13477 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13480 fix: Editorial notification artist line breaks
  src/Components/Notifications/ArticleFeaturedArtistNotification.tsx
Labels: Jira Synced

#13481 fix: Remove notification list Show More button and design fixes
  src/Components/Notifications/NotificationsList.tsx
  src/Components/Notifications/NotificationsWrapper.tsx
Labels: Jira Synced, Squash On Green

#13484 Chore(copy): Change trending artists in nav bar
  src/Components/NavBar/menuData.ts
Labels: Jira Synced

#13486 chore(EMI-1700): offer expired banner copy change
  src/Apps/Artwork/ArtworkApp.tsx
Labels: Jira Synced

#13485 feat(ONYX-695): add offers filter
  src/Apps/Notifications/NotificationsApp.tsx
  src/Components/Notifications/Notifications.tsx
  src/Components/Notifications/NotificationsEmptyStateByType.tsx
  src/Components/Notifications/NotificationsList.tsx
  src/Components/Notifications/NotificationsPills.tsx
  src/Components/Notifications/__tests__/Notifications.jest.tsx
  src/Components/Notifications/__tests__/NotificationsList.jest.tsx
  src/Components/Notifications/types.ts
  src/__generated__/NotificationsListPaginationQuery.graphql.ts
  src/__generated__/NotificationsList_viewer.graphql.ts
  src/__generated__/NotificationsPillsQuery.graphql.ts
Labels: Jira Synced

#13487 feat(ONYX-742): notifications empty state redesign
  src/Components/Notifications/NotificationsContextualMenu.tsx
  src/Components/Notifications/NotificationsEmptyStateByType.tsx
  src/Components/Notifications/NotificationsPills.tsx
  src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx
Labels: Jira Synced

#13482 Deploy
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Notifications/NotificationsApp.tsx
  src/Apps/Order/Components/PartnerOfferTimerItem.tsx
  src/Components/NavBar/menuData.ts
  src/Components/Notifications/ArticleFeaturedArtistNotification.tsx
  src/Components/Notifications/Notifications.tsx
  src/Components/Notifications/NotificationsContextualMenu.tsx
  src/Components/Notifications/NotificationsEmptyStateByType.tsx
  src/Components/Notifications/NotificationsList.tsx
  src/Components/Notifications/NotificationsPills.tsx
  src/Components/Notifications/NotificationsWrapper.tsx
  src/Components/Notifications/__tests__/Notifications.jest.tsx
  src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx
  src/Components/Notifications/__tests__/NotificationsList.jest.tsx
  src/Components/Notifications/types.ts
  src/__generated__/NotificationsListPaginationQuery.graphql.ts
  src/__generated__/NotificationsList_viewer.graphql.ts
  src/__generated__/NotificationsPillsQuery.graphql.ts
Labels: Jira Synced

#13493 fix: Adjust Alerts notification page header on mWeb
  src/Components/Notifications/AlertNotification.tsx
Labels: Jira Synced

#13479 fix(onyx-751): hide unpublished viewing room / activity panel notifications from activity panel
  src/Components/Notifications/NotificationsList.tsx
  src/Components/Notifications/__tests__/NotificationsList.jest.tsx
  src/Components/Notifications/__tests__/util.jest.ts
  src/Components/Notifications/util.ts
  src/__generated__/NotificationsListPaginationQuery.graphql.ts
  src/__generated__/NotificationsListQuery.graphql.ts
  src/__generated__/NotificationsList_test_Query.graphql.ts
  src/__generated__/NotificationsList_viewer.graphql.ts
Labels: Jira Synced

#13495 fix: Mark notification as read when opening notification page
  src/Components/Notifications/Notification.tsx
  src/Components/Notifications/NotificationItem.tsx
  src/__generated__/NotificationQuery.graphql.ts
Labels: Squash On Green

#13489 chore(alerts): clean up remaining v2 feature flags and dead code
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormPlaceholder.tsx
  src/Components/Alert/Components/Filters/__tests__/NotificationPreferences.jest.tsx
  src/Components/Alert/Components/Filters/__tests__/Price.jest.tsx
  src/Components/Alert/Components/Form/PriceRange.tsx
  src/Components/Alert/Components/Form/SuggestedFilters.tsx
  src/Components/Alert/Components/Steps/Details.tsx
  src/Components/Alert/Hooks/__tests__/AlertProvider.jest.tsx
  src/DevTools/setupTestWrapper.tsx
Labels: Jira Synced

#13494 fix: Clean up notification pills query
  src/Components/Notifications/NotificationsPills.tsx
  src/__generated__/NotificationsPillsQuery.graphql.ts
Labels: Squash On Green

#13509 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13513 fix: Partner offer notification item design
  src/Components/Notifications/NotificationItem.tsx
  src/Components/Notifications/NotificationTypeLabel.tsx
Labels: Jira Synced, Squash On Green

#13514 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13515 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/AlertNotification_notification.graphql.ts
Labels: Squash On Green

#13518 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13519 fix: Correctly update unreadNotificationsCount when reading notification
  src/Components/Notifications/Mutations/markAllNotificationsAsRead.ts
  src/Components/Notifications/Mutations/markNotificationAsRead.ts
  src/Components/Notifications/Mutations/markNotificationsAsSeen.ts
  src/__generated__/markAllNotificationsAsReadMutation.graphql.ts
  src/__generated__/markNotificationAsReadMutation.graphql.ts
  src/__generated__/markNotificationsAsSeenMutation.graphql.ts
Labels: Jira Synced, Squash On Green

#13521 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13520 fix: Adjust notification page Edit Alert font size
  src/Components/Notifications/AlertNotification.tsx
Labels: Jira Synced, Squash On Green

#13523 fix(shows): Fix display of address
  src/Apps/Show/Components/ShowInfoLocation.tsx
Labels: Merge On Green

#13529 fix: Adjust Activity panel max height and placeholder image width for mWeb
  src/Components/Notifications/Notification.tsx
  src/Components/Notifications/NotificationsWrapper.tsx
Labels: Squash On Green

#13532 fix: Rename Follows notification filter pill
  src/Components/Notifications/NotificationsPills.tsx
Labels: Squash On Green

#13537 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13540 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13531 feat(ONYX-727): top alert should be active when user visits settings alerts page
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
  src/Components/Notifications/NotificationsList.tsx
  src/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
  src/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
  src/__generated__/SavedSearchAlertsApp_me.graphql.ts
  src/__generated__/settingsRoutes_SavedSearchAlertsAppEditQuery.graphql.ts
  src/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#13545 Deploy
  package.json
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
  src/Components/Notifications/Notification.tsx
  src/Components/Notifications/NotificationsList.tsx
  src/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
  src/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
  src/__generated__/SavedSearchAlertsApp_me.graphql.ts
  src/__generated__/settingsRoutes_SavedSearchAlertsAppEditQuery.graphql.ts
  src/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#13552 fix: artist cover image meta
  src/Apps/Artist/Components/ArtistMeta/ArtistMeta.tsx
  src/Apps/Artist/Components/ArtistMeta/__tests__/ArtistMeta.jest.tsx
  src/Apps/Artist/Components/ArtistMeta/__tests__/helpers.jest.ts
  src/Apps/Artist/Components/ArtistMeta/helpers.ts
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistMeta_Test_Query.graphql.ts
  src/__generated__/ArtistMeta_artist.graphql.ts
  src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts
  src/__generated__/artistRoutes_ArtistSubAppQuery.graphql.ts
Labels: Jira Synced, Squash On Green
