Repository artsy/force, pull requests merged in 2024-08, with the labels that each got.

#14270 fix: Sell flow Condition step link styling
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Routes/AdditionalRoutes/ConditionRoute.tsx
Labels: Jira Synced

#14272 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14275 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/MyCollectionArtworkGrid_artworks.graphql.ts
  src/__generated__/MyCollectionArtworkInsights_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkSWASectionSubmitted_submissionState.graphql.ts
  src/__generated__/MyCollectionArtworkSWASubmissionStatus_Test_Query.graphql.ts
  src/__generated__/MyCollectionArtworkSWASubmissionStatus_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/MyCollectionArtwork_artwork.graphql.ts
Labels: Squash On Green

#14276 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14280 fix: Make additional documents optional in Sell flow
  src/Apps/Sell/Routes/AdditionalRoutes/AdditionalDocumentsRoute.tsx
  src/Apps/Sell/Routes/__tests__/AdditionalDocumentsRoute.jest.tsx
Labels: Squash On Green

#14279 chore: Post approval Sell flow tracking events
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSubmitForSale.tsx
  src/Apps/Sell/Hooks/useSubmissionTracking.ts
  src/Apps/Sell/Routes/ThankYouRoute.tsx
  src/Apps/Sell/Routes/__tests__/ConditionRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ThankYouRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/__generated__/MyCollectionArtworkSWASubmissionStatus_Test_Query.graphql.ts
  src/__generated__/MyCollectionArtworkSWASubmissionStatus_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#14284 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14278 chore(cache): Update TTLs / docs
  docs/caching.md
  src/Apps/Artist/artistRoutes.tsx
  src/Apps/ArtistSeries/artistSeriesRoutes.tsx
  src/Apps/Artists/artistsRoutes.tsx
  src/Apps/Auction/auctionRoutes.tsx
  src/Apps/Categories/categoriesRoutes.tsx
  src/Apps/Collect/collectRoutes.tsx
  src/Apps/Gene/geneRoutes.tsx
  src/Apps/Sale/saleRoutes.tsx
  src/Apps/serverCacheTTLs.tsx
Labels: Merge On Green

#14277 feat: expand auction artworks filter options
  src/Apps/Auction/Components/AuctionArtworkFilter.tsx
  src/Apps/Auction/Components/__tests__/AuctionArtworkFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/Utils/useFilterSelectResults.ts
Labels: Jira Synced, hackathon

#14274 feat: offer quick filters for featured keywords on fairs (WIP)
  src/Apps/Fair/Routes/FairArtworks.tsx
  src/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/KeywordFilter.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/FeaturedKeywordsFilterQuick.tsx
  src/Components/ArtworkFilter/index.tsx
  src/__generated__/FairArtworksQuery.graphql.ts
  src/__generated__/FairArtworks_Query.graphql.ts
  src/__generated__/FairArtworks_fair.graphql.ts
  src/__generated__/fairRoutes_FairArtworksQuery.graphql.ts
Labels: hackathon

#14268 chore(graphql-proxy): Update default ENABLE_GRAPHQL_PROXY=true
  .env.example
  .env.oss
  .secrets.baseline
  cypress.config.ts
  scripts/smoke_test.sh
  src/Server/config.ts
Labels: Merge On Green

#14285 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14287 feat(cache): Add cache logger middleware
  src/Server/middleware/__tests__/graphqlProxyMiddleware.jest.ts
  src/Server/middleware/graphqlProxyMiddleware.ts
  src/System/Relay/createRelaySSREnvironment.ts
  src/System/Relay/middleware/cacheLoggerMiddleware.ts
Labels: Merge On Green

#14295 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14300 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14301 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14302 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14297 fix: Link to previous submision step when completing submission from MyC
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/__generated__/MyCollectionArtworkSWASubmissionStatus_Test_Query.graphql.ts
  src/__generated__/MyCollectionArtworkSWASubmissionStatus_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Squash On Green

#14307 fix: Add missing My Collection submission status tracking
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx
Labels: Squash On Green

#14313 fix(proxy): Use X-Access-Token for checking logged-in
  src/Server/middleware/__tests__/graphqlProxyMiddleware.jest.ts
  src/Server/middleware/graphqlProxyMiddleware.ts
Labels: Merge On Green

#14311 fix: hide edit button if submission
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkHeader.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkHeader.jest.tsx
  src/__generated__/MyCollectionArtworkHeaderTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkHeader_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#14326 fix: broken partner shows
  src/Apps/Show/Components/ShowContextCard.tsx
Labels: Merge On Green

#14316 Deploy
  src/Apps/Auction/Components/Form/AddressForm.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkHeader.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkHeader.jest.tsx
  src/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetails.tsx
  src/Apps/Partner/Components/PartnerArtists/PartnerArtistDetailsList/PartnerArtistDetailsList.tsx
  src/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtists.tsx
  src/Apps/Sell/Routes/AdditionalRoutes/ShippingLocationRoute.tsx
  src/Apps/Sell/Routes/__tests__/ShippingLocationRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Apps/Show/Components/ShowContextCard.tsx
  src/Components/Artwork/Details.tsx
  src/Components/Artwork/__tests__/Details.jest.tsx
  src/Components/CountrySelect.tsx
  src/Server/middleware/__tests__/graphqlProxyMiddleware.jest.ts
  src/Server/middleware/graphqlProxyMiddleware.ts
  src/__generated__/MyCollectionArtworkHeaderTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkHeader_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/PartnerArtistDetailsListRendererQuery.graphql.ts
  src/__generated__/PartnerArtistDetailsList_partner.graphql.ts
  src/__generated__/ShippingLocationRoute_Test_Query.graphql.ts
  src/__generated__/ShippingLocationRoute_submission.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
  src/__generated__/sellRoutes_ShippingLocationRouteQuery.graphql.ts
Labels: Jira Synced

#14329 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14331 feat: sales offer featured keywords for curated browsing (whether auctions or not)
  src/Apps/Auction/AuctionApp.tsx
  src/Apps/Auction/Components/AuctionArtworkFilter.tsx
  src/Apps/Auction/Components/__tests__/AuctionArtworkFilter.jest.tsx
  src/Apps/Fair/Routes/FairArtworks.tsx
  src/Apps/Partner/Routes/Works/index.tsx
  src/Apps/Sale/Components/SaleArtworks.tsx
  src/Apps/Sale/SaleApp.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/FeaturedKeywordsFilterQuick.tsx
  src/Components/ArtworkFilter/index.tsx
  src/__generated__/AuctionAppTestQuery.graphql.ts
  src/__generated__/AuctionApp_viewer.graphql.ts
  src/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterTestQuery.graphql.ts
  src/__generated__/AuctionArtworkFilter_viewer.graphql.ts
  src/__generated__/SaleApp_Test_Query.graphql.ts
  src/__generated__/SaleApp_sale.graphql.ts
  src/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/__generated__/saleRoutes_SaleQuery.graphql.ts
Labels: hackathon

#14328 chore(DIA-779): monthly artists name update in navbar
  src/Components/NavBar/menuData.ts
Labels: Jira Synced

#14333 fix: Display previous submission on Sell page when in APPROVED state
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviousSubmission.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx
  src/Apps/Sell/SellFlowContext.tsx
Labels: Jira Synced

#14321 feat(saves): Rebuilds saves; adds price filtering
  package.json
  src/Apps/CollectorProfile/Routes/Saves/CollectorProfileSavesRoute.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/Actions/ArtworkListContextualMenu.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListContent.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/SavesArtworks.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/SavesArtworksGrid.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/SavesArtworksHeader.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/__tests__/ArtworkListContent.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves/__tests__/CollectorProfileSavesRoute.jest.tsx
  src/Components/Alert/Components/Filters/__tests__/Price.jest.tsx
  src/Components/ArtworkGrid/ArtworkGridEmptyState.tsx
  src/Components/ClientSuspense.tsx
  src/Components/PriceRange/PriceRange.tsx
  src/Components/PriceRange/Utils/__tests__/parsePriceRange.jest.ts
  src/Components/PriceRange/Utils/__tests__/priceRangeToLabel.jest.ts
  src/Components/PriceRange/Utils/parsePriceRange.ts
  src/Components/PriceRange/Utils/priceRangeToLabel.ts
  src/Components/PriceRange/constants.ts
  src/Components/SavedSearchAlert/Utils/extractPills.ts
  src/System/Components/FallbackErrorBoundary.tsx
  src/Utils/Hooks/useDebounce.ts
  src/__generated__/ArtworkListContentQuery.graphql.ts
  src/__generated__/ArtworkListContent_Test_Query.graphql.ts
  src/__generated__/ArtworkListContent_me.graphql.ts
  src/__generated__/SavesArtworksGridQuery.graphql.ts
  src/__generated__/SavesArtworksHeaderQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#14332 fix: Hide back button on Sell flow title step to not allow editing artist
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Routes/__tests__/TitleRoute.jest.tsx
Labels: Squash On Green

#14339 fix: allow all accounts to add cards (reverts #14046)
  src/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethods.tsx
  src/Apps/Settings/Routes/__tests__/SettingsPaymentsRoute.jest.tsx
Labels: Squash On Green

#14338 fix(EMI-2019): check if offer available
  src/Apps/Artwork/Components/ArtworkPageBanner.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkPageBanner.jest.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkPageBanner_Test_Query.graphql.ts
  src/__generated__/ArtworkPageBanner_me.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#14342 chore: Simplify submission tracking getOwnerType function
  src/Apps/Sell/Hooks/useSubmissionTracking.ts
Labels: Jira Synced

#14345 fix: use correct property to determine partner offer availability
  src/Apps/Artwork/Components/ArtworkPageBanner.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkPageBanner.jest.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkPageBanner_Test_Query.graphql.ts
  src/__generated__/ArtworkPageBanner_me.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#14350 feat: Make Sell flow bottom navigation transparent
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Components/SubmissionLayout.tsx
Labels: Jira Synced

#14341 feat: adds relative-ci agent
  .circleci/config.yml
  .gitignore
  Dockerfile
  package.json
  relativeci.config.js
  webpack/envs/clientProductionConfig.js
  yarn.lock
Labels: Jira Synced

#14346 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14356 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useUpdateCollectorProfileMutation.graphql.ts
Labels: Squash On Green

#14357 refactor: separates out and lazy loads onboarding code
  src/Components/Onboarding/Components/OnboardingDialog.tsx
  src/Components/Onboarding/Hooks/useOnboarding.tsx
Labels: Jira Synced

#14358 feat: allows for disabling 3rd party code via query string
  src/Server/middleware/__tests__/bootstrapSharifyAndContextLocalsMiddleware.jest.ts
  src/Server/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts
Labels: Jira Synced

#14361 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14362 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14363 fix(ONYX-1197): Make sure Sell flow intro page CTAs are visible on all window sizes
  src/Apps/Conversations/components/ConversationLayout.tsx
  src/Apps/Sell/Routes/IntroRoute.tsx
Labels: Jira Synced

#14364 feat: Decrease Sell flow bottom navigation transparency
  src/Apps/Sell/Components/BottomFormNavigation.tsx
Labels: Squash On Green

#14367 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14368 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14370 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14371 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14373 fix: details artist line overflow
  src/Components/Artwork/Details.tsx
Labels: Merge On Green, Jira Synced

#14369 chore: if form ends up on the shipping step with details saved the address should save by default
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetails.tsx
Labels: Jira Synced

#14374 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14376 fix(notifications): Fix notifications menu pills
  src/Components/Notifications/Notifications.tsx
Labels: Jira Synced

#14377 fix(search): Use coverImage first, then fallback
  src/Apps/Search/Routes/SearchResultsArtists.tsx
  src/__generated__/SearchResultsArtistsQuery.graphql.ts
  src/__generated__/SearchResultsArtists_viewer.graphql.ts
  src/__generated__/searchRoutes_SearchResultsArtistsQuery.graphql.ts
Labels: Squash On Green

#14378 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14379 fix: revert artwork details overflow fix
  src/Components/Artwork/Details.tsx
Labels: Jira Synced, Squash On Green

#14386 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14389 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14394 fix: removes focus-visible polyfill
  package.json
  src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGallery.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowserLarge.tsx
  src/Apps/Show/Components/ShowInstallShots.tsx
  src/Components/FocusVisible.tsx
  src/Components/NavBar/NavBarPrimaryLogo.tsx
  src/Components/Search/Mobile/OverlayBase.tsx
  src/System/Boot.tsx
  yarn.lock
Labels: Jira Synced

#14395 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14390 chore: Remove old Sell flow (part 1)
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HeaderSWA.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HowItWorksSteps.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SWAFooter.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Utils/marketingLandingTracking.ts
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSubmitForSale.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSubmitForSale.jest.tsx
Labels: Jira Synced

#14400 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
  src/__generated__/ArtistCareerHighlights_artist.graphql.ts
  src/__generated__/ArtistHeader_artist.graphql.ts
  src/__generated__/ArtistInsightBadges_Test_Query.graphql.ts
  src/__generated__/ArtistInsightBadges_artist.graphql.ts
Labels: Squash On Green

#14402 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14403 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14396 Chore: add sell flow test submission state query param for Integrity tests
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx
  src/Apps/Sell/SellFlowContext.tsx
Labels: Jira Synced

#14406 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14408 fix: Uppercase test submission state
  src/Apps/Sell/SellFlowContext.tsx
Labels: Squash On Green

#14407 chore: Remove old Sell flow (part 2)
  src/Apps/Consign/Components/SubmissionStepper.tsx
  src/Apps/Consign/Hooks/useSubmissionFlowSteps.ts
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/Components/DownloadApp.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYouWhenFromMyCollection.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYouWhenFromMyCollection.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/UploadPhotosForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
  src/Apps/Consign/Routes/SubmissionFlow/Utils/formHelpers.ts
  src/Apps/Consign/Routes/SubmissionFlow/Utils/redirects.ts
  src/Apps/Consign/Routes/SubmissionFlow/Utils/types.ts
  src/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
  src/Apps/Consign/consignRoutes.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSubmitForSale.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSWASubmissionStatus.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSubmitForSale.jest.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
  src/Apps/Sell/Components/ArtistAutocomplete.tsx
  src/Apps/Sell/Components/__tests__/ArtistAutocomplete.jest.tsx
  src/Apps/Sell/Routes/ArtistRoute.tsx
  src/Apps/Sell/Utils/createOrUpdateConsignSubmission.ts
  src/__generated__/ArtworkDetails_SubmissionFlowPrepopulatedTest_Query.graphql.ts
  src/__generated__/ArtworkDetails_SubmissionFlowTest_Query.graphql.ts
  src/__generated__/ArtworkDetails_me.graphql.ts
  src/__generated__/ArtworkDetails_myCollectionArtwork.graphql.ts
  src/__generated__/ArtworkDetails_submission.graphql.ts
  src/__generated__/UploadPhotos_ImageRefetch_Query.graphql.ts
  src/__generated__/UploadPhotos_SubmissionFlowTest_Query.graphql.ts
  src/__generated__/UploadPhotos_SubmissionMyCollectionFlowTest_Query.graphql.ts
  src/__generated__/UploadPhotos_myCollectionArtwork.graphql.ts
  src/__generated__/UploadPhotos_submission.graphql.ts
  src/__generated__/consignRoutes_artworkDetailsQuery.graphql.ts
  src/__generated__/consignRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignRoutes_artworkEditDetailsQuery.graphql.ts
  src/__generated__/consignRoutes_myCollectionArtworkQuery.graphql.ts
  src/__generated__/consignRoutes_uploadArtworkPhotosQuery.graphql.ts
  src/__generated__/consignRoutes_uploadPhotosQuery.graphql.ts
  src/__generated__/redirects_submission.graphql.ts
Labels: Jira Synced

#14404 fix(EMI-1944): clear address on delete
  src/Apps/Order/Routes/Shipping2/Components/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
Labels: Jira Synced

#14412 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtQuizTrendingCollections_viewer.graphql.ts
  src/__generated__/MarketingFeaturedArtworksRail_viewer.graphql.ts
  src/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
Labels: Squash On Green

#14410 Deploy
  data/schema.graphql
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSWASubmissionStatus.jest.tsx
  src/Apps/Order/Routes/Shipping2/Components/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Apps/Partner/Components/Overview/AboutPartner.tsx
  src/Apps/Partner/Components/__tests__/Overview/AboutPartner.jest.tsx
  src/Components/Artwork/ConsignmentSubmissionStatus.tsx
  src/Components/Artwork/__tests__/ConsignmentSubmissionStatus.jest.tsx
  src/__generated__/AboutPartner_Test_Query.graphql.ts
  src/__generated__/AboutPartner_partner.graphql.ts
  src/__generated__/ArtQuizTrendingCollections_viewer.graphql.ts
  src/__generated__/MarketingFeaturedArtworksRail_viewer.graphql.ts
  src/__generated__/MyCollectionArtworkSWASubmissionStatus_Test_Query.graphql.ts
  src/__generated__/MyCollectionArtworkSWASubmissionStatus_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
  src/__generated__/partnerRoutes_OverviewQuery.graphql.ts
Labels: Jira Synced

#14419 chore: Move Inquiry routes to Sell app
  src/Apps/Consign/consignRoutes.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/utils/contactInformationValidationSchema.ts
  src/Apps/Sell/Routes/ConsignmentInquiry/Components/ConsignmentInquiryForm.tsx
  src/Apps/Sell/Routes/ConsignmentInquiry/Components/ConsignmentInquiryFormAbandonEdit.tsx
  src/Apps/Sell/Routes/ConsignmentInquiry/ConsignmentInquiry.tsx
  src/Apps/Sell/Routes/ConsignmentInquiry/ConsignmentInquiryConfirmation.tsx
  src/Apps/Sell/Routes/ConsignmentInquiry/ConsignmentInquiryContainer.tsx
  src/Apps/Sell/Routes/ConsignmentInquiry/__tests__/ConsignmentInquiry.jest.tsx
  src/Apps/Sell/Routes/ConsignmentInquiry/utils/useCreateConsignmentInquiry.ts
  src/Apps/Sell/Routes/ConsignmentInquiry/utils/validation.ts
  src/Apps/Sell/sellRoutes.tsx
  src/__generated__/sellRoutes_ConsignmentInquiryAppQuery.graphql.ts
  src/__generated__/sellRoutes_ConsignmentInquiryWithRecipientEmailAppQuery.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#14418 fix(EMI-1935): Prefill address modal country and make sure it is visible
  src/Apps/Order/Routes/Shipping2/Components/AddressModal2.tsx
  src/Apps/Order/Routes/Shipping2/Components/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/AddressModal2.jest.tsx
Labels: Jira Synced

#14416 chore: update metaphysics graphql schema
  data/schema.graphql
  src/Apps/ArtistSeries/__tests__/ArtistSeriesMeta.jest.tsx
  src/__generated__/ArtistSeriesApp_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilter_Query.graphql.ts
  src/__generated__/ArtistSeriesHeader_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesMeta_TestQuery.graphql.ts
  src/__generated__/ArtistSeriesMeta_artistSeries.graphql.ts
  src/__generated__/ArtistSeriesRailQuery.graphql.ts
  src/__generated__/ArtworkArtistSeriesQuery.graphql.ts
  src/__generated__/ArtworkArtistSeries_Query.graphql.ts
  src/__generated__/CellArtistSeriesFragmentContainer_Test_Query.graphql.ts
  src/__generated__/CellArtistSeriesStoryQuery.graphql.ts
  src/__generated__/artistRoutes_ArtistSeriesQuery.graphql.ts
  src/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
Labels: Squash On Green
