Repository artsy/force, pull requests merged in 2024-10, with the labels that each got.

#14597 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14598 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14600 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14601 fix(EMI-2123): dont redirect for displayState != submitted on payment failed route
  src/Apps/Order/__tests__/OrderApp.jest.tsx
  src/Apps/Order/redirects.tsx
Labels: Jira Synced

#14596 Deploy
  data/schema.graphql
  src/Apps/Collect/Routes/Collection/Components/Header/index.tsx
  src/Apps/Collect/Routes/Collection/index.tsx
  src/Apps/Order/__tests__/OrderApp.jest.tsx
  src/Apps/Order/redirects.tsx
  src/__generated__/Collection_collection.graphql.ts
  src/__generated__/Header_collection.graphql.ts
  src/__generated__/collectRoutes_CollectionQuery.graphql.ts
Labels: Jira Synced

#14604 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14607 feat(sentry): Add route-level span tracing
  .vscode/settings.json
  src/Server/setupSentryClient.ts
  src/System/Boot.tsx
  src/System/Router/RenderStates.tsx
  src/System/Utils/setupSentryClient.ts
  src/client.tsx
Labels: Merge On Green, performance

#14608 Deploy
  .vscode/settings.json
  src/Server/setupSentryClient.ts
  src/System/Boot.tsx
  src/System/Router/RenderStates.tsx
  src/System/Utils/setupSentryClient.ts
  src/client.tsx
Labels: Merge On Green

#14610 fix: en dash in date range for collector signals
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCollectorSignal.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarDetails.jest.tsx
Labels: Jira Synced

#14614 fix: show seconds left to bid in auction signals
  src/Components/Artwork/Details/BidTimerLine.tsx
  src/Components/Artwork/Details/__tests__/BidTimerLine.jest.tsx
Labels: Jira Synced

#14618 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14620 chore(sentry): Drop our sample rate down
  src/System/Utils/setupSentryClient.ts
  src/instrument.ts
Labels: Merge On Green

#14621 chore(sentry): drop our sample rate down further
  src/System/Utils/setupSentryClient.ts
  src/instrument.ts
Labels: Squash On Green

#14627 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14628 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14632 feat(prefetch): Add feature-flag support for prefetch-on-enter for logged out
  src/System/Components/RouterLink.tsx
Labels: performance

#14634 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14636 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14637 fix: Make artist name clickable on Private artworks pages
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
Labels: Jira Synced

#14612 feat: pods to load vars from vault [Do-Not-Merge]
  Dockerfile
  hokusai/production.yml
  hokusai/staging.yml
  scripts/load_secrets_and_run.sh
Labels: Jira Synced

#14638 fix: path in entrypoint
  Dockerfile
Labels: Merge On Green

#14642 refactor(searchbar): Remove unnecessary empty query
  src/Components/Search/SearchBar.tsx
  src/Components/Search/SearchBarInput.tsx
  src/Components/Search/SuggestionItem/SuggestionItemPreview.tsx
  src/Components/Search/utils/shouldStartSearching.ts
  src/Utils/Hooks/useClientQuery.ts
  src/__generated__/SearchBarInputRefetchQuery.graphql.ts
  src/__generated__/SearchBarInputSuggestQuery.graphql.ts
  src/__generated__/SearchBarInput_viewer.graphql.ts
Labels: Jira Synced, performance

#14643 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14648 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14641 feat: show co-badged card language when there is a saved card
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/__tests__/Payment.jest.tsx
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/Payment_me.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
Labels: Jira Synced

#14651 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14653 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14655 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14658 chore: add line break after payment amount in InvoicePaymentRoute
  src/Apps/Invoice/Routes/InvoicePaymentRoute.tsx
Labels: Merge On Green

#14659 test: add tests for InvoiceApp
  src/Apps/Invoice/Hooks/__tests__/useCreateTokenAndSubmit.jest.ts
  src/Apps/Invoice/InvoiceApp.tsx
  src/Apps/Invoice/Routes/InvoiceDetailRoute.tsx
  src/Apps/Invoice/Routes/InvoicePaymentRoute.tsx
  src/Apps/Invoice/Routes/__tests__/InvoiceDetailRoute.jest.tsx
  src/Apps/Invoice/Routes/__tests__/InvoicePaymentRoute.jest.tsx
  src/Apps/Invoice/__tests__/InvoiceApp.jest.tsx
  src/Apps/Invoice/invoiceRoutes.tsx
  src/__generated__/InvoiceApp_Test_Query.graphql.ts
  src/__generated__/InvoiceDetailRoute_Test_Query.graphql.ts
  src/__generated__/InvoicePaymentRoute_Test_Query.graphql.ts
Labels: Merge On Green

#14666 feat: downgrade @artsy/icons
  package.json
  yarn.lock
Labels: Merge On Green, Jira Synced

#14669 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14674 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14680 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14686 fix: pass through data-test* properties
  src/System/Components/RouterLink.tsx
Labels: Merge On Green

#14685 fix: add safeguards for rendering the insights
  src/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlight.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlights.tsx
  src/__generated__/ArtistCareerHighlightsQuery.graphql.ts
  src/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
  src/__generated__/ArtistCareerHighlights_artist.graphql.ts
Labels: Merge On Green, Jira Synced

#14690 fix(router link): allow onclick prop explicitly
  src/System/Components/RouterLink.tsx
Labels: Merge On Green

#14694 chore(palette): Bump to latest
  package.json
  yarn.lock
Labels: Merge On Green

#14696 chore: remove http-proxy-middleware
  package.json
  yarn.lock
Labels: Merge On Green, performance

#14702 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14704 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14708 chore(performance): Experiment with improving LCP and CLS by guarding against bots
  src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
  src/Apps/Artwork/Components/ArtworkLightbox.tsx
  src/Apps/Artwork/Components/ArtworkLightboxPlaceholder.tsx
  src/Components/CookieConsentManager/CookieConsentManager.tsx
Labels: performance

#14705 chore: AMBER-911 - show shipping prices for Artsy Auction artworks
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebar.jest.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#14718 fix(artwork-grids): Ensure we dont rerender on route changes
  src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
  src/Apps/ArtistSeries/ArtistSeriesApp.tsx
  src/Apps/ArtistSeries/Components/ArtistSeriesArtworksFilter.tsx
  src/Apps/Artwork/Components/ArtworkLightbox.tsx
  src/Apps/Auction/Components/AuctionArtworkFilter.tsx
  src/Apps/Collect/Routes/Collect/index.tsx
  src/Apps/Collect/Routes/Collection/Components/Header/CollectionFeaturedArtists.tsx
  src/Apps/Collect/Routes/Collection/index.tsx
  src/Apps/Gene/Components/GeneArtworkFilter.tsx
  src/Apps/Show/Components/ShowArtworks.tsx
  src/Apps/Tag/Components/TagArtworkFilter.tsx
  src/Components/ArtworkGrid/LazyArtworkGrid.tsx
Labels: performance

#14722 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14700 feat: display new credit card brand icons
  src/Apps/Order/Components/CreditCardDetails.tsx
  src/Components/BrandCreditCardIcon.tsx
Labels: Jira Synced

#14726 feat: defer artworks grid on Fair artworks route
  src/Apps/Fair/Routes/FairArtworks.tsx
  src/Apps/Fair/fairRoutes.tsx
  src/__generated__/FairArtworksFilterQuery.graphql.ts
  src/__generated__/FairArtworksFilterRefetchQuery.graphql.ts
Labels: performance

#14709 fix: use backend field to determine if an order is already with payment method set
  src/Apps/Order/Components/OrderStepper.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Utils/__tests__/orderUtils.jest.ts
  src/Apps/Order/Utils/orderUtils.ts
  src/Apps/Order/__tests__/OrderApp.jest.tsx
  src/Apps/Order/redirects.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/OrderStepper_order.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/Payment_order.graphql.ts
  src/__generated__/RejectTestQuery.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/Shipping2TestQuery.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/__generated__/orderRoutes_OrderQuery.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/__generated__/orderRoutes_RejectQuery.graphql.ts
  src/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/redirects_order.graphql.ts
  src/__generated__/useSaveFulfillmentDetailsMutation.graphql.ts
  src/__generated__/useSelectShippingQuoteMutation.graphql.ts
Labels: Jira Synced

#14728 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14729 fix: revert using backend field to determine if an order is already with payment method set
  src/Apps/Order/Components/OrderStepper.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Utils/__tests__/orderUtils.jest.ts
  src/Apps/Order/Utils/orderUtils.ts
  src/Apps/Order/__tests__/OrderApp.jest.tsx
  src/Apps/Order/redirects.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/OrderStepper_order.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/Payment_order.graphql.ts
  src/__generated__/RejectTestQuery.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/Shipping2TestQuery.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/__generated__/orderRoutes_OrderQuery.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/__generated__/orderRoutes_RejectQuery.graphql.ts
  src/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/redirects_order.graphql.ts
  src/__generated__/useSaveFulfillmentDetailsMutation.graphql.ts
  src/__generated__/useSelectShippingQuoteMutation.graphql.ts
Labels: Merge On Green

#14732 chore(invoice): Clean up layout
  src/Apps/Invoice/Components/AddressForm.tsx
  src/Apps/Invoice/Components/InvoiceLineItems.tsx
  src/Apps/Invoice/Components/InvoicePaymentForm.tsx
  src/Apps/Invoice/InvoiceApp.tsx
  src/Apps/Invoice/Routes/InvoiceDetailRoute.tsx
  src/Apps/Invoice/Routes/InvoicePaymentRoute.tsx
  src/Apps/Invoice/Routes/__tests__/InvoiceDetailRoute.jest.tsx
  src/Apps/Invoice/Routes/__tests__/InvoicePaymentRoute.jest.tsx
  src/Apps/Invoice/__tests__/InvoiceApp.jest.tsx
  src/Apps/Invoice/invoiceRoutes.tsx
Labels: Merge On Green

#14713 feat(performance): Add support for SSR streaming
  src/Apps/Fair/Routes/FairArticles.tsx
  src/Apps/Shows/Components/ShowsHeader.tsx
  src/Server/config.ts
  src/Server/setup_sharify.ts
  src/System/Router/Utils/collectAssets.tsx
  src/System/Router/__tests__/serverRouter.jest.tsx
  src/System/Router/renderServerApp.tsx
  src/System/Router/serverRouter.tsx
  src/Typings/sharify.d.ts
  src/html.ejs
  src/server.ts
Labels: Jira Synced, performance

#14682 fix: Allow logged out users to exit Sell flow by clicking on Artsy logo
  src/Apps/MyCollection/Routes/EditArtwork/Components/ArtworkFormExitConfirmationDialog.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormHeader.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormMain.tsx
  src/Apps/Sell/Components/SubmissionHeader.tsx
  src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
Labels: Jira Synced

#14737 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14738 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14739 chore: add tracking to update payment method
  src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
Labels: Jira Synced

#14735 fix: use backend field to determine if payment is set on an order
  src/Apps/Order/Components/OrderStepper.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Utils/__tests__/orderUtils.jest.ts
  src/Apps/Order/Utils/orderUtils.ts
  src/Apps/Order/__tests__/OrderApp.jest.tsx
  src/Apps/Order/redirects.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/OrderStepper_order.graphql.ts
  src/__generated__/PaymentRouteSetOrderPaymentMutation.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/Payment_order.graphql.ts
  src/__generated__/Payment_validation.graphql.ts
  src/__generated__/RejectTestQuery.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
  src/__generated__/orderRoutes_OfferQuery.graphql.ts
  src/__generated__/orderRoutes_OrderQuery.graphql.ts
  src/__generated__/orderRoutes_PaymentQuery.graphql.ts
  src/__generated__/orderRoutes_RejectQuery.graphql.ts
  src/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/redirects_order.graphql.ts
  src/__generated__/useSaveFulfillmentDetailsMutation.graphql.ts
  src/__generated__/useSelectShippingQuoteMutation.graphql.ts
  src/__generated__/useSetPaymentByStripeIntentMutation.graphql.ts
  src/__generated__/useSetPaymentMutation.graphql.ts
Labels: Jira Synced

#14743 chore(performance): Attempt to improve LCP by disabling lazyload on Artwork/Artist
  src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
  src/Apps/Artwork/Components/ArtworkLightbox.tsx
  src/Apps/Artwork/Components/ArtworkLightboxPlaceholder.tsx
  src/Components/CookieConsentManager/CookieConsentManager.tsx
Labels: performance

#14746 chore: adding comment to give context on hard coded values
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
Labels: Squash On Green

#14748 chore: revert - show shipping prices when present for Artsy Auction ar…
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebar.jest.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#14749 fix(AMBER-1099): [Viewing Room] Jillian Ross Viewing Room Bug/Formatting
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
Labels: Jira Synced

#14744 chore(EMI-2094): Dont show the end times banner if the sale is ended
  src/Apps/Artwork/Components/__tests__/ArtworkPageBanner.jest.tsx
  src/Apps/Auction/__tests__/AuctionApp.jest.tsx
  src/Components/CascadingEndTimesBanner.tsx
  src/Components/__tests__/CascadingEndTimesBanner.jest.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkPageBanner_Test_Query.graphql.ts
  src/__generated__/AuctionAppTestQuery.graphql.ts
  src/__generated__/CascadingEndTimesBanner_Test_Query.graphql.ts
  src/__generated__/CascadingEndTimesBanner_sale.graphql.ts
  src/__generated__/ViewingRoomArtworkDetails_artwork.graphql.ts
  src/__generated__/ViewingRoomWorksRoute_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/__generated__/useCreateBidderMutation.graphql.ts
  src/__generated__/viewingRoomRoutes_ViewingRoomWorksRouteQuery.graphql.ts
Labels: Jira Synced

#14752 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14753 fix: Add space to COA message AMBER-1108
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuthenticityCertificate.tsx
  src/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
  src/Apps/Artwork/Components/TrustSignals/__tests__/AuthenticityCertificate.jest.tsx
  src/__generated__/AuthenticityCertificateTestQuery.graphql.ts
  src/__generated__/AuthenticityCertificate_artwork.graphql.ts
Labels: Merge On Green

#14759 chore(tests): Split react versions for enzyme tests
  jest.legacy.config.js
  package.json
  scripts/migrate-enzyme-tests.js
  src/Apps/Order/Routes/Shipping/Hooks/__tests__/useUserAddressUpdates.jest.ts
  src/Components/Address/__tests__/useAddressAutocomplete.jest.ts
  src/Utils/Hooks/__tests__/useClientQuery.jest.ts
  yarn.lock
Labels: Jira Synced, React 18 Upgrade

#14761 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
