Repository artsy/force, pull requests merged in 2024-06, with the labels that each got.

#13948 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useCreateArtworkMutation.graphql.ts
  src/__generated__/useUpdateArtworkMutation.graphql.ts
Labels: Squash On Green

#13949 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useCreateArtworkMutation.graphql.ts
  src/__generated__/useUpdateArtworkMutation.graphql.ts
Labels: Squash On Green

#13950 fix(DIA-664): Dark mode Q/A - Part 1
  src/Apps/Conversations/components/Message/ConversationTimeSince.tsx
  src/Apps/Conversations/components/Sidebar/ConversationsSidebarItem.tsx
  src/Apps/Order/Components/BuyerGuarantee.tsx
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Routes/__tests__/Status.jest.tsx
  src/Apps/Settings/Routes/MyCollection/Components/MyCollectionAppDownload.tsx
  src/Components/DownloadAppBadges/DownloadAppBadge.tsx
  src/Components/DownloadAppBadges/DownloadAppBadges.tsx
  src/Components/Footer/Footer.tsx
Labels: Jira Synced

#13946 chore: Remove references to amber_artwork_visibility_unlisted as this is liv…
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPrivateArtwork.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/ArtworkSidebarPrivateArtworkQuery.graphql.ts
  src/__generated__/ArtworkSidebarPrivateArtwork_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13954 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13951 Deploy
  data/schema.graphql
  package.json
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkPageBanner.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPrivateArtwork.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/Apps/Conversations/components/Message/ConversationTimeSince.tsx
  src/Apps/Conversations/components/Sidebar/ConversationsSidebarItem.tsx
  src/Apps/Order/Components/BuyerGuarantee.tsx
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Routes/__tests__/Status.jest.tsx
  src/Apps/Settings/Routes/MyCollection/Components/MyCollectionAppDownload.tsx
  src/Components/DownloadAppBadges/DownloadAppBadge.tsx
  src/Components/DownloadAppBadges/DownloadAppBadges.tsx
  src/Components/Footer/Footer.tsx
  src/Components/Notifications/NotificationItem.tsx
  src/Components/Notifications/PartnerOfferArtwork.tsx
  src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/ArtworkSidebarPrivateArtworkQuery.graphql.ts
  src/__generated__/ArtworkSidebarPrivateArtwork_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#13952 feat(Conversation): shows a toast error when convo's cta fails
  src/Apps/Conversations/components/ConversationCTA/ConversationCTA.tsx
  src/Apps/Conversations/components/ConversationCTA/ConversationMakeOfferButton.tsx
  src/Apps/Conversations/components/ConversationCTA/ConversationPurchaseButton.tsx
  src/Apps/Conversations/components/ConversationCTA/__tests__/ConversationCTA.jest.tsx
  src/__generated__/ConversationCTA_Test_Query.graphql.ts
  src/__generated__/ConversationCTA_conversation.graphql.ts
  src/__generated__/ConversationReplyTestQuery.graphql.ts
  src/__generated__/conversationsRoutes_DetailQuery.graphql.ts
Labels: Jira Synced

#13927 feat: add initial scaffold for new Sell with Artsy flow
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Components/DevDebug.tsx
  src/Apps/Sell/Components/StepsNavigation.tsx
  src/Apps/Sell/Components/SubmissionHeader.tsx
  src/Apps/Sell/Components/SubmissionLayout.tsx
  src/Apps/Sell/Mutations/useCreateSubmission.tsx
  src/Apps/Sell/Mutations/useUpdateSubmission.tsx
  src/Apps/Sell/Routes/DetailsRoute.tsx
  src/Apps/Sell/Routes/DimensionsRoute.tsx
  src/Apps/Sell/Routes/IntroRoute.tsx
  src/Apps/Sell/Routes/NewFromMyCollectionRoute.tsx
  src/Apps/Sell/Routes/NewRoute.tsx
  src/Apps/Sell/Routes/PhotosRoute.tsx
  src/Apps/Sell/Routes/PurchaseHistoryRoute.tsx
  src/Apps/Sell/Routes/SubmissionRoute.tsx
  src/Apps/Sell/Routes/ThankYouRoute.tsx
  src/Apps/Sell/Routes/TitleRoute.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Apps/Sell/sellRoutes.tsx
  src/__generated__/ArtistAutocomplete_SearchConnection_Query.graphql.ts
  src/__generated__/DetailsRoute_submission.graphql.ts
  src/__generated__/DimensionsRoute_submission.graphql.ts
  src/__generated__/MyCollectionArtworkFormArtistStep_me.graphql.ts
  src/__generated__/MyCollectionCreateArtworkTest_Query.graphql.ts
  src/__generated__/PhotosRoute_submission.graphql.ts
  src/__generated__/PurchaseHistoryRoute_submission.graphql.ts
  src/__generated__/SubmissionRoute_submission.graphql.ts
  src/__generated__/ThankYouRoute_submission.graphql.ts
  src/__generated__/TitleRoute_submission.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts
  src/__generated__/myCollectionRoutes_MyCollectionArtworkUploadQuery.graphql.ts
  src/__generated__/sellRoutes_DetailsRouteQuery.graphql.ts
  src/__generated__/sellRoutes_DimensionsRouteQuery.graphql.ts
  src/__generated__/sellRoutes_PhotosRouteQuery.graphql.ts
  src/__generated__/sellRoutes_PurchaseHistoryRouteQuery.graphql.ts
  src/__generated__/sellRoutes_SubmissionRouteQuery.graphql.ts
  src/__generated__/sellRoutes_ThankYouRouteQuery.graphql.ts
  src/__generated__/sellRoutes_TitleRouteQuery.graphql.ts
  src/__generated__/useCreateSubmissionMutation.graphql.ts
  src/__generated__/useUpdateSubmissionMutation.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#13962 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useCreateArtworkMutation.graphql.ts
  src/__generated__/useUpdateArtworkMutation.graphql.ts
Labels: Squash On Green

#13960 Deploy
  data/schema.graphql
  src/Apps/About/AboutApp.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
  src/Apps/Conversations/components/ConversationCTA/ConversationCTA.tsx
  src/Apps/Conversations/components/ConversationCTA/ConversationMakeOfferButton.tsx
  src/Apps/Conversations/components/ConversationCTA/ConversationPurchaseButton.tsx
  src/Apps/Conversations/components/ConversationCTA/__tests__/ConversationCTA.jest.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Components/DevDebug.tsx
  src/Apps/Sell/Components/StepsNavigation.tsx
  src/Apps/Sell/Components/SubmissionHeader.tsx
  src/Apps/Sell/Components/SubmissionLayout.tsx
  src/Apps/Sell/Mutations/useCreateSubmission.tsx
  src/Apps/Sell/Mutations/useUpdateSubmission.tsx
  src/Apps/Sell/Routes/DetailsRoute.tsx
  src/Apps/Sell/Routes/DimensionsRoute.tsx
  src/Apps/Sell/Routes/IntroRoute.tsx
  src/Apps/Sell/Routes/NewFromMyCollectionRoute.tsx
  src/Apps/Sell/Routes/NewRoute.tsx
  src/Apps/Sell/Routes/PhotosRoute.tsx
  src/Apps/Sell/Routes/PurchaseHistoryRoute.tsx
  src/Apps/Sell/Routes/SubmissionRoute.tsx
  src/Apps/Sell/Routes/ThankYouRoute.tsx
  src/Apps/Sell/Routes/TitleRoute.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Apps/Sell/sellRoutes.tsx
  src/Components/Footer/FooterDownloadAppBanner.tsx
  src/__generated__/ArtistAutocomplete_SearchConnection_Query.graphql.ts
  src/__generated__/ConversationCTA_Test_Query.graphql.ts
  src/__generated__/ConversationCTA_conversation.graphql.ts
  src/__generated__/ConversationReplyTestQuery.graphql.ts
  src/__generated__/DetailsRoute_submission.graphql.ts
  src/__generated__/DimensionsRoute_submission.graphql.ts
  src/__generated__/MyCollectionArtworkFormArtistStep_me.graphql.ts
  src/__generated__/MyCollectionCreateArtworkTest_Query.graphql.ts
  src/__generated__/PhotosRoute_submission.graphql.ts
  src/__generated__/PurchaseHistoryRoute_submission.graphql.ts
  src/__generated__/SubmissionRoute_submission.graphql.ts
  src/__generated__/ThankYouRoute_submission.graphql.ts
  src/__generated__/TitleRoute_submission.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts
  src/__generated__/conversationsRoutes_DetailQuery.graphql.ts
  src/__generated__/myCollectionRoutes_MyCollectionArtworkUploadQuery.graphql.ts
  src/__generated__/sellRoutes_DetailsRouteQuery.graphql.ts
  src/__generated__/sellRoutes_DimensionsRouteQuery.graphql.ts
  src/__generated__/sellRoutes_PhotosRouteQuery.graphql.ts
  src/__generated__/sellRoutes_PurchaseHistoryRouteQuery.graphql.ts
  src/__generated__/sellRoutes_SubmissionRouteQuery.graphql.ts
  src/__generated__/sellRoutes_ThankYouRouteQuery.graphql.ts
  src/__generated__/sellRoutes_TitleRouteQuery.graphql.ts
  src/__generated__/useCreateArtworkMutation.graphql.ts
  src/__generated__/useCreateSubmissionMutation.graphql.ts
  src/__generated__/useUpdateArtworkMutation.graphql.ts
  src/__generated__/useUpdateSubmissionMutation.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#13963 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13933 feat(AMBER-700): Move Artwork Details to top of page/sidebar for private works
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuthenticityCertificate.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarClassification.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarDetails.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/PrivateArtworkAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/PrivateArtworkDefinitionList.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarDetails.jest.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/PrivateArtworkAdditionalInfo.jest.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkMetadata.tsx
  src/Apps/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkMetadata.jest.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebarDetails_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarDetails_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/__generated__/PrivateArtworkAdditionalInfo_Test_Query.graphql.ts
  src/__generated__/PrivateArtworkAdditionalInfo_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13964 Deploy
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuthenticityCertificate.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarClassification.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarDetails.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/PrivateArtworkAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/PrivateArtworkDefinitionList.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarDetails.jest.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/PrivateArtworkAdditionalInfo.jest.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkMetadata.tsx
  src/Apps/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkMetadata.jest.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebarDetails_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarDetails_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/__generated__/PrivateArtworkAdditionalInfo_Test_Query.graphql.ts
  src/__generated__/PrivateArtworkAdditionalInfo_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13968 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13969 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13966 fix(EMI-1691): Refactor Preference App tests
  src/Apps/Preferences/__tests__/PreferencesApp.jest.tsx
  src/__generated__/PreferencesAppTestQuery.graphql.ts
Labels: Jira Synced

#13972 fix(DIA-664): Cleans up theme selection
  src/Apps/AppPreferences/useAppPreferences.tsx
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsThemeSelect.tsx
  src/Components/Footer/Footer.tsx
  src/Utils/Hooks/useDarkModeToggle.ts
  src/__generated__/PreferencesAppTestQuery.graphql.ts
Labels: Jira Synced

#13967 Chore(EMI-1671): remove name from pickup form
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
Labels: Jira Synced

#13970 Deploy
  data/schema.graphql
  src/Apps/AppPreferences/useAppPreferences.tsx
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Apps/Preferences/__tests__/PreferencesApp.jest.tsx
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Components/DevDebug.tsx
  src/Apps/Sell/Components/SubmissionHeader.tsx
  src/Apps/Sell/Components/SubmissionLayout.tsx
  src/Apps/Sell/Routes/NewRoute.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsThemeSelect.tsx
  src/Components/Footer/Footer.tsx
  src/Utils/Hooks/useDarkModeToggle.ts
  src/__generated__/PreferencesAppTestQuery.graphql.ts
Labels: Jira Synced

#13973 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13975 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13976 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13979 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13981 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13984 refactor(loading-bar): Polish top-bar loading states
  src/System/Router/PageLoader.tsx
  src/System/Router/PageLoadingBar.tsx
  src/System/Router/RenderStatus.tsx
Labels: Merge On Green

#13980 Deploy
  data/schema.graphql
  src/System/Router/PageLoader.tsx
  src/System/Router/PageLoadingBar.tsx
  src/System/Router/RenderStatus.tsx
Labels: Merge On Green

#13978 feat: New submission flow artist step
  src/Apps/Artwork/Components/__tests__/ArtworkPageBanner.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Routes/ArtistRoute.tsx
  src/Apps/Sell/Routes/NewRoute.tsx
  src/Apps/Sell/Routes/__tests__/ArtistRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/NewRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Apps/Sell/sellRoutes.tsx
  src/__generated__/ArtistRoute_Test_Query.graphql.ts
  src/__generated__/ArtistRoute_submission.graphql.ts
  src/__generated__/sellRoutes_ArtistRouteQuery.graphql.ts
Labels: Jira Synced

#13965 feat: update text for the inquiry flow
  src/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
  src/Components/Inquiry/Views/InquiryInquiry.tsx
Labels: Merge On Green, Jira Synced

#13989 feat: New submission flow details step
  src/Apps/Sell/Routes/DetailsRoute.tsx
  src/Apps/Sell/Routes/__tests__/ArtistRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/DetailsRoute.jest.tsx
  src/__generated__/ArtistRoute_Test_Query.graphql.ts
  src/__generated__/DetailsRoute_Test_Query.graphql.ts
Labels: Jira Synced, Squash On Green

#13996 fix: add missing info icon to inquiry modal copy
  src/Components/Inquiry/Views/InquiryInquiry.tsx
Labels: Jira Synced, Squash On Green

#13988 feat: Carry over auto-completed location when submitting a MyC artwork
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/__generated__/ArtworkDetails_SubmissionFlowPrepopulatedTest_Query.graphql.ts
  src/__generated__/ArtworkDetails_myCollectionArtwork.graphql.ts
  src/__generated__/consignRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignRoutes_myCollectionArtworkQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#13995 feat(ONYX-1019): add artwork dimensions step
  src/Apps/Sell/Routes/DimensionsRoute.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/__generated__/DimensionsRoute_Test_Query.graphql.ts
Labels: Jira Synced

#13993 feat(nav): updates menus
  package.json
  src/Components/NavBar/Menus/NavBarSubMenu.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
  src/Components/NavBar/menuData.ts
  yarn.lock
Labels: Jira Synced

#14001 chore: removes dark mode feature flag
  src/Apps/Components/__tests__/AppShell.jest.tsx
  src/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
  src/Components/Footer/Footer.tsx
  src/Components/Footer/__tests__/Footer.jest.tsx
Labels: Jira Synced

#13999 Deploy
  package.json
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Sell/Routes/DimensionsRoute.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Components/NavBar/Menus/NavBarSubMenu.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
  src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
  src/Components/NavBar/menuData.ts
  src/__generated__/ArtworkDetails_SubmissionFlowPrepopulatedTest_Query.graphql.ts
  src/__generated__/ArtworkDetails_myCollectionArtwork.graphql.ts
  src/__generated__/DimensionsRoute_Test_Query.graphql.ts
  src/__generated__/consignRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignRoutes_myCollectionArtworkQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#14003 fix: update the settings link color
  src/Components/Inquiry/Views/InquiryInquiry.tsx
Labels: Jira Synced, Squash On Green

#13639 chore(ONYX-661): display error message on alert edit/add
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Components/Alert/AlertContext.ts
  src/Components/Alert/AlertProvider.tsx
  src/Components/Alert/Components/Steps/Details.tsx
Labels: Jira Synced

#14013 chore(storybooks): Remove CI deploys
  .circleci/config.yml
Labels: Merge On Green

#14012 fix: Update Sell flow `ArtistAutocomplete` `Artist#image` to `Artist#coverArtwork`
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx
  src/__generated__/ArtistAutocomplete_SearchConnection_Query.graphql.ts
Labels: Squash On Green

#14016 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/AlertNotification_notification.graphql.ts
  src/__generated__/ArticleFeaturedArtistNotification_notification.graphql.ts
  src/__generated__/ArtworkPublishedNotification_notification.graphql.ts
  src/__generated__/NotificationItem_item.graphql.ts
  src/__generated__/NotificationItem_test_Query.graphql.ts
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/NotificationTypeLabel_notification.graphql.ts
  src/__generated__/NotificationsListNextQuery.graphql.ts
  src/__generated__/NotificationsListQuery.graphql.ts
  src/__generated__/NotificationsList_test_Query.graphql.ts
  src/__generated__/NotificationsList_viewer.graphql.ts
  src/__generated__/PartnerShowOpenedNotification_test_Query.graphql.ts
  src/__generated__/ViewingRoomPublishedNotification_notification.graphql.ts
  src/__generated__/ViewingRoomPublishedNotification_test_Query.graphql.ts
Labels: Squash On Green

#14002 chore: AMBER-724 - hide inquire on artworks grid
  src/Components/Artwork/Details.tsx
  src/Components/Artwork/__tests__/Details.jest.tsx
Labels: Jira Synced

#14018 fix(partner): corrects follow button alignment
  src/Apps/Partner/Components/PartnerHeader/index.tsx
Labels: Jira Synced

#14009 feat: Improve new Sell flow bottom navigation
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Routes/ArtistRoute.tsx
  src/Apps/Sell/Routes/__tests__/DetailsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
Labels: Jira Synced

#14024 chore(loading-bar): fade in top bar
  src/System/Components/PageLoadingBar.tsx
Labels: Merge On Green

#14023 Deploy
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Routes/ArtistRoute.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/System/Components/PageLoadingBar.tsx
Labels: Merge On Green

#14029 chore(loading-bar): Less fade
  src/System/Components/PageLoadingBar.tsx
Labels: Merge On Green

#14028 Deploy
  package.json
  src/System/Components/PageLoadingBar.tsx
  yarn.lock
Labels: Merge On Green

#14031 chore: copy changes for auction pages
  src/Apps/Auction/Components/AuctionDetails/AuctionInfoSidebar.tsx
  src/Apps/Auction/Components/AuctionDetails/__tests__/AuctionInfoSidebar.jest.tsx
Labels: Merge On Green, Jira Synced

#14033 chore(DIA-718): add elements to auction sidebar
  src/Apps/Auction/Components/AuctionDetails/AuctionInfoSidebar.tsx
Labels: Merge On Green, Jira Synced

#14034 Deploy
  src/Apps/Auction/Components/AuctionDetails/AuctionInfoSidebar.tsx
Labels: Jira Synced

#14030 feat(ONYX-1018): add purchase history step
  package.json
  src/Apps/Home/__tests__/HomeWorksForYouTabBar.jest.tsx
  src/Apps/Order/Components/SavedAddressItem.tsx
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/Shipping2/Components/SavedAddressItem2.tsx
  src/Apps/Sell/Routes/PurchaseHistoryRoute.tsx
  src/Apps/Sell/Routes/__tests__/PurchaseHistoryRoute.jest.tsx
  src/Apps/Sell/Utils/formUtils.ts
  src/__generated__/PurchaseHistoryRoute_Test_Query.graphql.ts
  src/__generated__/PurchaseHistoryRoute_submission.graphql.ts
  src/__generated__/sellRoutes_PurchaseHistoryRouteQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#13983 feat(ONYX-928): add new specialists
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
Labels: Jira Synced

#14037 Deploy
  package.json
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
  src/Apps/Home/__tests__/HomeWorksForYouTabBar.jest.tsx
  src/Apps/Order/Components/SavedAddressItem.tsx
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/Shipping2/Components/SavedAddressItem2.tsx
  src/Apps/Sell/Routes/PurchaseHistoryRoute.tsx
  src/Apps/Sell/Routes/__tests__/PurchaseHistoryRoute.jest.tsx
  src/Apps/Sell/Utils/formUtils.ts
  src/__generated__/PurchaseHistoryRoute_Test_Query.graphql.ts
  src/__generated__/PurchaseHistoryRoute_submission.graphql.ts
  src/__generated__/sellRoutes_PurchaseHistoryRouteQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#14039 feat: New sell flow "artist not eligible" experience
  src/Apps/Sell/Components/ArtistNotEligibleText.tsx
  src/Apps/Sell/Routes/ArtistNotEligibleRoute.tsx
  src/Apps/Sell/Routes/ArtistRoute.tsx
  src/Apps/Sell/Routes/__tests__/ArtistNotEligibleRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ArtistRoute.jest.tsx
  src/Apps/Sell/sellRoutes.tsx
  src/__generated__/ArtistNotEligibleRoute_Test_Query.graphql.ts
  src/__generated__/ArtistNotEligibleRoute_artist.graphql.ts
  src/__generated__/sellRoutes_ArtistNotEligibleRouteQuery.graphql.ts
Labels: Jira Synced

#14038 chore(AMBER-760): Add saleMessage as price_display to artwork pageview
  src/Apps/Artwork/ArtworkApp.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#14042 feat(completeprofile): adds profile information dialog
  src/Components/CompleteProfile/CompleteProfileInformationDialog.tsx
  src/__generated__/CompleteProfileInformationDialogQuery.graphql.ts
Labels: Jira Synced

#14025 feat(ONYX-1013): add start submission page
  src/Apps/Sell/Routes/IntroRoute.tsx
  src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx
Labels: Jira Synced, Squash On Green

#14041 feat: New Sell flow progress bar
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Components/SubmissionLayout.tsx
  src/Apps/Sell/Components/SubmissionProgressBar.tsx
  src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
  src/Apps/Sell/Routes/ArtistNotEligibleRoute.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Apps/Sell/sellRoutes.tsx
Labels: Jira Synced

#14040 Deploy
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Sell/Components/ArtistNotEligibleText.tsx
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Components/SubmissionLayout.tsx
  src/Apps/Sell/Components/SubmissionProgressBar.tsx
  src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
  src/Apps/Sell/Routes/ArtistNotEligibleRoute.tsx
  src/Apps/Sell/Routes/ArtistRoute.tsx
  src/Apps/Sell/Routes/IntroRoute.tsx
  src/Apps/Sell/Routes/__tests__/ArtistNotEligibleRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ArtistRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Apps/Sell/sellRoutes.tsx
  src/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethods.tsx
  src/Apps/Settings/Routes/__tests__/SettingsPaymentsRoute.jest.tsx
  src/Components/CompleteProfile/CompleteProfileInformationDialog.tsx
  src/__generated__/ArtistNotEligibleRoute_Test_Query.graphql.ts
  src/__generated__/ArtistNotEligibleRoute_artist.graphql.ts
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/CompleteProfileInformationDialogQuery.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/sellRoutes_ArtistNotEligibleRouteQuery.graphql.ts
Labels: Jira Synced

#14047 fix: adjust title sizes on the submission screens
  src/Apps/Sell/Components/SubmissionStepTitle.tsx
  src/Apps/Sell/Routes/ArtistNotEligibleRoute.tsx
  src/Apps/Sell/Routes/ArtistRoute.tsx
  src/Apps/Sell/Routes/DetailsRoute.tsx
  src/Apps/Sell/Routes/DimensionsRoute.tsx
  src/Apps/Sell/Routes/PhotosRoute.tsx
  src/Apps/Sell/Routes/PurchaseHistoryRoute.tsx
  src/Apps/Sell/Routes/TitleRoute.tsx
Labels: Jira Synced

#14035 fix: address form validation inconsistencies
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/Utils/shippingUtils.ts
Labels: Jira Synced

#14055 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13998 feat: New MyC Submit for Sale flow
  src/Apps/Consign/Routes/SubmissionFlow/Mutations/CreateConsignSubmissionMutation.ts
  src/Apps/Consign/Routes/SubmissionFlow/Utils/createOrUpdateConsignSubmission.ts
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSWASection.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtworkAboutTab.tsx
  src/__generated__/MyCollectionArtworkInsights_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkSWASection_Test_Query.graphql.ts
  src/__generated__/MyCollectionArtworkSWASection_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/MyCollectionArtwork_artwork.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#14061 fix(EMI-1924): user logged in to show expired banner
  src/Apps/Artwork/Components/ArtworkPageBanner.tsx
Labels: Jira Synced

#13977 feat(fadeinbox): animation standardization fadein isMounted
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Components/Alert/Components/Steps/Details.tsx
  src/Components/Alert/Components/Steps/Filters.tsx
  src/Components/FadeInBox.tsx
Labels: Jira Synced

#14060 feat(ONYX-1077): add mWeb navigation
  src/Apps/Sell/Components/SubmissionHeader.tsx
  src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
Labels: Jira Synced

#14066 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14065 Fix: return if artist associated with saved alert cannot be found
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
Labels: Jira Synced

#14057 chore: Make "Start Selling" button ready for new sell flow
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
Labels: Jira Synced

#14071 chore: Do not set SOURCE when submitting an artwork from My Collection
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx
Labels: Jira Synced, Squash On Green

#14074 fix: Use dvh for Sell flow layout to correctly set height on mobile
  src/Apps/Sell/Components/SubmissionLayout.tsx
Labels: Squash On Green

#14062 feat: require login in new Sell flow
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Routes/ArtistRoute.tsx
  src/Apps/Sell/Routes/__tests__/ArtistNotEligibleRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ArtistRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/DetailsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/NewRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/PurchaseHistoryRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ThankYouRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/TitleRoute.jest.tsx
Labels: Jira Synced

#14064 feat: add 07 curated discovery articles rail
  .vscode/settings.json
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Article.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArticlesRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollectionsRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
  src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts
Labels: Merge On Green

#14077 fix(ONYX-1013): update images and styling
  src/Apps/Sell/Components/SubmissionLayout.tsx
  src/Apps/Sell/Routes/IntroRoute.tsx
Labels: Jira Synced

#14076 fix: New Sell flow design adjustments
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Components/SubmissionHeader.tsx
  src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
Labels: Squash On Green

#14078 feat: add rudimentary 07 artworks rail
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
  src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts
Labels: Squash On Green

#14084 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14068 Deploy
  data/schema.graphql
  hokusai/production.yml
  hokusai/staging.yml
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Components/SubmissionHeader.tsx
  src/Apps/Sell/Components/SubmissionLayout.tsx
  src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
  src/Apps/Sell/Routes/ArtistRoute.tsx
  src/Apps/Sell/Routes/IntroRoute.tsx
  src/Apps/Sell/Routes/__tests__/ArtistNotEligibleRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ArtistRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/DetailsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/NewRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/PurchaseHistoryRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ThankYouRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/TitleRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Components/Inquiry/Views/InquiryInquiry.tsx
  src/__generated__/useUpdateCollectorProfileMutation.graphql.ts
Labels: Jira Synced

#14052 fix: Go back to fulfillment details step (hide shipping quotes) when interacting with pickup/autocomplete
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Routes/Shipping2/ShippingContext.tsx
Labels: Jira Synced

#14083 feat: get or create weaviate user for curated discovery
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Form.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
  src/Apps/ArtAdvisor/07-Curated-Discovery/types.ts
  src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts
Labels: Jira Synced

#14086 feat: add price filtering to 07 artworks rail
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/StatePreview.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
  src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts
Labels: Squash On Green

#14069 feat(onyx-944): activity panel navigates directly to entity page whenonly one entity in notification row
  src/Components/Notifications/NotificationItem.tsx
  src/Components/Notifications/NotificationsList.tsx
  src/Components/Notifications/__tests__/NotificationItem.jest.tsx
Labels: Jira Synced

#14059 chore: New sell flow tracking
  src/Apps/Sell/Components/ArtistNotEligibleText.tsx
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Components/SubmissionHeader.tsx
  src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
  src/Apps/Sell/Hooks/useSubmissionTracking.ts
  src/Apps/Sell/Routes/ArtistRoute.tsx
  src/Apps/Sell/Routes/IntroRoute.tsx
  src/Apps/Sell/Routes/NewFromMyCollectionRoute.tsx
  src/Apps/Sell/Routes/ThankYouRoute.tsx
  src/Apps/Sell/Routes/__tests__/ArtistNotEligibleRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ThankYouRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/__generated__/ThankYouRoute_Test_Query.graphql.ts
  src/__generated__/ThankYouRoute_submission.graphql.ts
Labels: Jira Synced, Squash On Green

#14091 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14092 fix: Open Sell flow advisor and faq links in new tab
  src/Apps/Sell/Components/ArtistNotEligibleText.tsx
Labels: Squash On Green

#14088 feat(ONYX-1020): add phone number step
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Hooks/useSubmissionTracking.ts
  src/Apps/Sell/Routes/PhoneNumberRoute.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/PhoneNumberRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Apps/Sell/sellRoutes.tsx
  src/__generated__/PhoneNumberRoute_Test_Query.graphql.ts
  src/__generated__/PhoneNumberRoute_me.graphql.ts
  src/__generated__/PhoneNumberRoute_submission.graphql.ts
  src/__generated__/sellRoutes_PhoneNumberRouteQuery.graphql.ts
Labels: Jira Synced

#14096 chore: update curated discovery description with user requirement
  src/Apps/ArtAdvisor/ArtAdvisorApp.tsx
Labels: Squash On Green

#14093 Deploy
  src/Apps/Collect/Components/SeoProductsForCollections.tsx
  src/Apps/Collect/Components/__tests__/SeoProductsForCollections.jest.tsx
  src/Apps/Collect/Routes/Collection/index.tsx
  src/Apps/Home/Components/__tests__/HomeAuctionLotsForYouRail.jest.tsx
  src/Apps/Home/Components/__tests__/HomeAuctionLotsRail.jest.tsx
  src/Apps/Home/Components/__tests__/HomeCurrentFairs.jest.tsx
  src/Apps/Home/Components/__tests__/HomeEmergingPicksArtworksRail.jest.tsx
  src/Apps/Home/Components/__tests__/HomeFeaturedGalleriesRail.jest.tsx
  src/Apps/Home/Components/__tests__/HomeFeaturedMarketNews.jest.tsx
  src/Apps/Home/Components/__tests__/HomeFeaturedShowsRail.jest.tsx
  src/Apps/Home/Components/__tests__/HomeNewWorksForYouRail.jest.tsx
  src/Apps/Home/Components/__tests__/HomeNewWorksFromGalleriesYouFollowRail.jest.tsx
  src/Apps/Home/Components/__tests__/HomeRecentlyViewedRail.jest.tsx
  src/Apps/Home/Components/__tests__/HomeTrendingArtistsRail.jest.tsx
  src/Apps/Home/Components/__tests__/HomeWorksByArtistsYouFollowRail.jest.tsx
  src/Apps/Home/Components/__tests__/HomeWorksForYouTabBar.jest.tsx
  src/Apps/Home/__tests__/HomeApp.jest.tsx
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Hooks/useSubmissionTracking.ts
  src/Apps/Sell/Routes/PhoneNumberRoute.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/PhoneNumberRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Apps/Sell/sellRoutes.tsx
  src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
  src/__generated__/Collection_collection.graphql.ts
  src/__generated__/PhoneNumberRoute_Test_Query.graphql.ts
  src/__generated__/PhoneNumberRoute_me.graphql.ts
  src/__generated__/PhoneNumberRoute_submission.graphql.ts
  src/__generated__/RelatedCollectionsRailQuery.graphql.ts
  src/__generated__/SeoProductsForCollections_ascending_artworks.graphql.ts
  src/__generated__/SeoProductsForCollections_descending_artworks.graphql.ts
  src/__generated__/collectRoutes_CollectionQuery.graphql.ts
  src/__generated__/sellRoutes_PhoneNumberRouteQuery.graphql.ts
Labels: Jira Synced

#14099 fix: ai-squad review app
  hokusai/production.yml
  hokusai/staging.yml
Labels: Merge On Green

#14090 chore(EMI-1936): remove extra space in the shipping form
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
Labels: Jira Synced

#14101 chore: update metaphysics graphql schema
  src/__generated__/HomeApp_Test_Query.graphql.ts
Labels: Squash On Green

#14103 chore(AMBER-769): Do not hide the sale message on the grid
  src/Components/Artwork/Details.tsx
  src/Components/Artwork/__tests__/Details.jest.tsx
Labels: Jira Synced

#14097 feat: add artwork like and dislike functionality
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
  src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts
Labels: Jira Synced

#14112 refactor: 07 components and types
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Form.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Article.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArticlesRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Header.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollection.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollectionsRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/types.ts
  src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts
Labels: Squash On Green

#14113 chore(ai): deploy review app
  src/Apps/ArtAdvisor/07-Curated-Discovery/App.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Form.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Interests.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Article.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArticlesRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Header.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollection.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollectionsRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/llm/extractInterestsIntent.ts
  src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
  src/Apps/ArtAdvisor/07-Curated-Discovery/types.ts
  src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts
Labels: Jira Synced

#14114 feat: minor styling changes to 07
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Article.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArticlesRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollection.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollectionsRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/types.ts
  src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts
Labels: Squash On Green

#14115 chore(ai): deploy review app
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Article.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArticlesRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollection.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollectionsRail.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/types.ts
  src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts
Labels: Merge On Green
