Repository artsy/force, pull requests merged in 2024-11, with the labels that each got.

#14764 feat: don't lazy-load main artist image (LCP)
  src/Components/FullBleedHeader/FullBleedHeaderPicture.tsx
Labels: Merge On Green, performance

#14763 fix(artwork): Fix cutoff on closed auction artworks
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksShelf.tsx
Labels: Merge On Green

#14768 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14774 feat(web-vitals): Better DX around web-vitals debugging
  package.json
  src/Server/config.ts
  src/Server/setup_sharify.ts
  src/System/Utils/setupWebVitals.ts
  src/Typings/sharify.d.ts
  src/client.tsx
  yarn.lock
Labels: performance

#14775 fix(lcp): Improve LCP on /collect
  src/Components/CollectionsHubsNav.tsx
Labels: Merge On Green, performance

#14777 fix(lcp): Improve LCP on /articles
  src/Apps/Articles/Components/ArticlesIndexArticle.tsx
  src/Apps/Articles/Components/ArticlesIndexArticles.tsx
Labels: Merge On Green, performance

#14778 fix(lcp): Improve LCP on mobile fair page
  src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
  src/Apps/Fair/Components/FairHeader/FairHeaderImage.tsx
Labels: Merge On Green, performance

#14779 fix(lcp): Improve LCP on /artist-series
  src/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
  src/__generated__/ArtistSeriesHeader_artistSeries.graphql.ts
  src/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
Labels: Merge On Green, performance

#14781 chore(lcp): Add fetchPriority=high to main images
  src/Apps/Articles/Components/ArticlesIndexArticle.tsx
  src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
  src/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
  src/Apps/Artists/Components/ArtistsCarouselCell.tsx
  src/Apps/Fair/Components/FairHeader/FairHeaderImage.tsx
  src/Apps/Fairs/Components/FairsFairBanner.tsx
  src/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
  src/Apps/Partners/Components/PartnersFeaturedCarouselCell.tsx
  src/Apps/Sell/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Components/Cells/CellArtist.tsx
  src/Components/CollectionsHubsNav.tsx
  src/Components/FullBleedHeader/FullBleedHeaderPicture.tsx
Labels: Merge On Green, performance

#14784 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14770 feat: refactor saves/list inclusion properties to defer until needed; replace with `isSavedToAnyList`
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActionsSaveButton.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/SelectArtworkListsModal/useSelectArtworkLists.ts
  src/Components/Artwork/SaveButton/DeprecatedSaveButton.tsx
  src/Components/Artwork/SaveButton/SaveArtworkMutation.ts
  src/Components/Artwork/SaveButton/SaveArtworkToListsButton.tsx
  src/Components/Artwork/SaveButton/__tests__/DeprecatedSaveButton.jest.tsx
  src/Components/Artwork/SaveButton/__tests__/SaveArtworkToListsButton.jest.tsx
  src/Components/Artwork/SaveButton/useSaveArtwork.ts
  src/Components/Artwork/SaveButton/useSaveArtworkToLists.ts
  src/Components/Artwork/useArtworkLists.ts
  src/__generated__/ArtworkActionsSaveButton_Test_Query.graphql.ts
  src/__generated__/ArtworkActionsSaveButton_artwork.graphql.ts
  src/__generated__/ArtworkActions_Test_Query.graphql.ts
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/DeprecatedSaveButtonQuery.graphql.ts
  src/__generated__/DeprecatedSaveButtonTestQuery.graphql.ts
  src/__generated__/DeprecatedSaveButton_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/SaveArtworkMutation.graphql.ts
  src/__generated__/SaveArtworkToListsButtonQuery.graphql.ts
  src/__generated__/SaveArtworkToListsButton_Test_Query.graphql.ts
  src/__generated__/SaveArtworkToListsButton_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
  src/__generated__/useArtworkListsArtworkSaveStatesQuery.graphql.ts
  src/__generated__/useSaveArtworkToListsArtworkListInclusionQuery.graphql.ts
  src/__generated__/useSelectArtworkListsMutation.graphql.ts
Labels: Merge On Green

#14787 feat(performance): Add PreloadWebpackPlugin for preloading initial JS chunks and simplify html pipeline
  package.json
  src/html.ejs
  webpack/envs/clientDevelopmentConfig.js
  webpack/envs/clientProductionConfig.js
  webpack/sharedPlugins.js
  yarn.lock
Labels: Jira Synced, performance

#14794 feat: add Link headers corresponding to preconnect and preload instructions (DIA-967)
  package.json
  src/Apps/Authentication/Middleware/redirectPostAuth.ts
  src/Server/middleware/__tests__/hardcodedRedirects.jest.ts
  src/Server/middleware/linkHeadersMiddleware.ts
  src/middleware.ts
  yarn.lock
Labels: Merge On Green, performance

#14795 fix(html): Re-enable html minification
  webpack/envs/clientProductionConfig.js
Labels: Merge On Green

#14788 Deploy
  package.json
  src/Apps/Authentication/Middleware/redirectPostAuth.ts
  src/Server/middleware/__tests__/hardcodedRedirects.jest.ts
  src/Server/middleware/linkHeadersMiddleware.ts
  src/html.ejs
  src/middleware.ts
  webpack/envs/clientDevelopmentConfig.js
  webpack/envs/clientProductionConfig.js
  webpack/sharedPlugins.js
  yarn.lock
Labels: Jira Synced

#14783 chore: AMBER-1102 - salesforce message widget
  src/Components/SalesforceWrapper.tsx
  src/Server/config.ts
  src/Server/setup_sharify.ts
  src/Typings/global.d.ts
  src/Typings/sharify.d.ts
Labels: Jira Synced

#14796 feat(early-hints): Add support for emitting webpack .js early hint headers and passing via linkHeadersMiddleware
  package.json
  src/Server/__tests__/getWebpackEarlyHints.jest.ts
  src/Server/getWebpackEarlyHints.ts
  src/Server/middleware/linkHeadersMiddleware.ts
  src/System/Router/renderServerApp.tsx
  src/dev.js
  src/html.ejs
  webpack/plugins/EarlyHintsPlugin.js
  webpack/sharedPlugins.js
  yarn.lock
Labels: Jira Synced, performance

#14808 fix(early-hints): Fix cors configuration around preloading js assets
  src/Server/__tests__/getWebpackEarlyHints.jest.ts
  src/Server/getWebpackEarlyHints.ts
Labels: performance

#14806 Deploy
  package.json
  src/Apps/Conversations/components/Sidebar/ConversationsSidebarItem.tsx
  src/Apps/Fair/Routes/FairOverview.tsx
  src/Server/__tests__/getWebpackEarlyHints.jest.ts
  src/Server/getWebpackEarlyHints.ts
  src/Server/middleware/linkHeadersMiddleware.ts
  src/System/Router/renderServerApp.tsx
  src/__generated__/ConversationsSidebar2PaginationQuery.graphql.ts
  src/__generated__/ConversationsSidebarItemTestQuery.graphql.ts
  src/__generated__/ConversationsSidebarItem_conversation.graphql.ts
  src/__generated__/ConversationsSidebarPaginationQuery.graphql.ts
  src/__generated__/ConversationsSidebarTestQuery.graphql.ts
  src/__generated__/FairOverview_Test_Query.graphql.ts
  src/__generated__/FairOverview_fair.graphql.ts
  src/__generated__/conversationsRoutes_DetailQuery.graphql.ts
  src/__generated__/fairRoutes_FairOverviewQuery.graphql.ts
  src/dev.js
  src/html.ejs
  webpack/plugins/EarlyHintsPlugin.js
  webpack/sharedPlugins.js
  yarn.lock
Labels: Merge On Green

#14803 fix: Require logged in user for all`/favorites/alerts/` sub route
  src/Apps/Favorites/favoritesRoutes.tsx
  src/Server/middleware/userRequiredMiddleware.ts
Labels: Jira Synced

#14799 fix: Avoid remount on Search page
  src/Apps/Search/Routes/SearchResultsArtworks.tsx
Labels: Jira Synced

#14818 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14820 fix(EMI-2157): Checkout dead ends due to invisible saved address errors
  src/Apps/Order/Routes/Shipping/Components/AddressModal.tsx
  src/Apps/Order/Routes/Shipping/Components/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping/Utils/shippingUtils.ts
Labels: Jira Synced

#14823 Deploy
  data/schema.graphql
  package.json
  src/Apps/Article/Components/ArticleHero.tsx
  src/Apps/Collect/Routes/Collection/index.tsx
  src/Apps/Order/Routes/Shipping/Components/AddressModal.tsx
  src/Apps/Order/Routes/Shipping/Components/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping/Utils/shippingUtils.ts
  src/Components/Notifications/NotificationArtwork.tsx
  src/Components/Notifications/NotificationArtworkList.tsx
  src/Components/Notifications/NotificationItem.tsx
  yarn.lock
Labels: Merge On Green, Jira Synced

#14824 docs(caching): Add link to overview of Relay normalization issue
  docs/caching.md
  docs/caching2.md
Labels: Merge On Green

#14816 fix: Correctly unset availability filter
  src/Components/ArtworkFilter/ArtworkFilters/AvailabilityFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/AvailabilityFilter.jest.tsx
Labels: Jira Synced

#14817 fix: Remove filters with `null` values from the URL
  src/Components/ArtworkFilter/Utils/urlBuilder.tsx
Labels: Jira Synced

#14831 fix: properly tracks completion, and avoids early closure
  src/Components/Onboarding/Components/OnboardingFollows.tsx
  src/Components/Onboarding/Components/OnboardingMarketingCollection.tsx
  src/Components/Onboarding/Components/OnboardingSteps.tsx
  src/Components/Onboarding/config.ts
Labels: Jira Synced

#14834 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14836 fix: ensures social title is correct
  src/Apps/Article/Components/ArticleMetaTags.tsx
  src/Components/MetaTags.tsx
Labels: Jira Synced

#14838 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14837 fix(DIA-982): allow recovery codes to be entered on mobile
  src/Components/AuthDialog/Views/AuthDialogLogin.tsx
  src/Components/Inquiry/Views/InquiryLogin.tsx
Labels: Jira Synced

#14842 chore: avoid loading extensive @artsy libraries until necessary
  package.json
  webpack/bundleSplitting.js
  yarn.lock
Labels: performance

#14800 fix: Update the term on the search page correctly
  src/Apps/Search/SearchApp.tsx
Labels: Jira Synced

#14835 Deploy
  .circleci/config.yml
  data/schema.graphql
  package.json
  src/Apps/Article/Components/ArticleMetaTags.tsx
  src/Apps/Articles/Components/ArticlesIndexArticle.tsx
  src/Apps/Search/SearchApp.tsx
  src/Components/AuthDialog/Views/AuthDialogLogin.tsx
  src/Components/Inquiry/Views/InquiryLogin.tsx
  src/Components/MetaTags.tsx
  webpack/bundleSplitting.js
  yarn.lock
Labels: Jira Synced

#14845 feat: switch initContainer to Fortress repo
  hokusai/production.yml
  hokusai/staging.yml
Labels: Jira Synced

#14856 chore: update note for counteroffer step
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Components/__stories__/CountdownTimer.story.tsx
Labels: Jira Synced

#14859 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14865 feat: use a query renderer for artwork page sidebar on mobile
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/__tests__/ArtworkApp.jest.tsx
  src/Apps/Artwork/artworkRoutes.tsx
  src/System/Router/Utils/serverAppContext.ts
  src/System/Router/__tests__/serverRouter.jest.enzyme.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/ArtworkApp_artworkResult.graphql.ts
  src/__generated__/ArtworkApp_me.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Merge On Green

#14869 chore: add placeholder for artwork sidebar query renderer
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
Labels: Merge On Green

#14858 chore(perf): avoid loading associated artists unnecessarily
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkDownloadButton.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBiddingClosedMessage.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
  src/__generated__/ArtworkActions_Test_Query.graphql.ts
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/ArtworkAuctionCreateAlertHeader_Test_Query.graphql.ts
  src/__generated__/ArtworkAuctionCreateAlertHeader_artwork.graphql.ts
  src/__generated__/ArtworkDownloadButton_artwork.graphql.ts
  src/__generated__/ArtworkSidebarArtists_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarArtists_artwork.graphql.ts
  src/__generated__/ArtworkSidebarAuctionInfoPollingQuery.graphql.ts
  src/__generated__/ArtworkSidebarBiddingClosedMessage_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCurrentBidInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/PricingContextQuery.graphql.ts
  src/__generated__/PricingContextTestQuery.graphql.ts
  src/__generated__/PricingContext_artwork.graphql.ts
  src/__generated__/PrivateArtworkAboutArtistQuery.graphql.ts
  src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: performance

#14871 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14875 feat: removes cookie consent banner for googlebot
  src/Components/CookieConsentManager/__tests__/useConsentRequired.jest.ts
  src/Components/CookieConsentManager/useConsentRequired.ts
Labels: performance

#14864 fix(consignment inquiry): correct routing for email form
  src/Apps/Sell/Routes/ConsignmentInquiry/ConsignmentInquiryConfirmation.tsx
  src/Apps/Sell/sellRoutes.tsx
Labels: Jira Synced

#14878 fix: use getENV instead of server side context to check IS_MOBILE
  src/Apps/Artwork/artworkRoutes.tsx
  src/System/Router/Utils/serverAppContext.ts
  src/System/Router/__tests__/serverRouter.jest.enzyme.tsx
Labels: Merge On Green

#14873 fix: Retain useClientQuery queries
  src/Utils/Hooks/useClientQuery.ts
Labels: Squash On Green

#14888 fix(artwork): Fix deepzoom
  src/Components/DeepZoom/DeepZoom.tsx
Labels: Merge On Green

#14891 chore: Sync schema
  data/schema.graphql
Labels: Merge On Green

#14893 fix(artwork-brick): Fix artwork hover zoom performance
  src/Components/MagnifyImage.tsx
Labels: performance

#14885 chore(perf): avoid unnecessary partner loads (DIA-989)
  src/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx
  src/Apps/Artwork/Components/TrustSignals/BuyerGuarantee.tsx
  src/Apps/Artwork/Components/TrustSignals/SecurePayment.tsx
  src/Apps/Artwork/Components/TrustSignals/VerifiedSeller.tsx
  src/Apps/Artwork/Components/TrustSignals/__tests__/BuyerGuarantee.jest.enzyme.tsx
  src/Apps/Artwork/Components/TrustSignals/__tests__/SecurePayment.jest.enzyme.tsx
  src/Apps/Artwork/Components/TrustSignals/__tests__/VerifiedSeller.jest.enzyme.tsx
  src/Apps/Artwork/Utils/badges.ts
  src/__generated__/BuyerGuaranteeTestQuery.graphql.ts
  src/__generated__/BuyerGuarantee_artwork.graphql.ts
  src/__generated__/SecurePaymentTestQuery.graphql.ts
  src/__generated__/SecurePayment_artwork.graphql.ts
  src/__generated__/VerifiedSellerTestQuery.graphql.ts
  src/__generated__/VerifiedSeller_artwork.graphql.ts
Labels: Merge On Green, performance

#14899 Deploy
  src/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx
  src/Apps/Artwork/Components/TrustSignals/BuyerGuarantee.tsx
  src/Apps/Artwork/Components/TrustSignals/SecurePayment.tsx
  src/Apps/Artwork/Components/TrustSignals/VerifiedSeller.tsx
  src/Apps/Artwork/Components/TrustSignals/__tests__/BuyerGuarantee.jest.enzyme.tsx
  src/Apps/Artwork/Components/TrustSignals/__tests__/SecurePayment.jest.enzyme.tsx
  src/Apps/Artwork/Components/TrustSignals/__tests__/VerifiedSeller.jest.enzyme.tsx
  src/Apps/Artwork/Utils/badges.ts
  src/__generated__/BuyerGuaranteeTestQuery.graphql.ts
  src/__generated__/BuyerGuarantee_artwork.graphql.ts
  src/__generated__/SecurePaymentTestQuery.graphql.ts
  src/__generated__/SecurePayment_artwork.graphql.ts
  src/__generated__/VerifiedSellerTestQuery.graphql.ts
  src/__generated__/VerifiedSeller_artwork.graphql.ts
Labels: Jira Synced

#14906 feat(react-18): Add streaming via react-streaming
  .storybook/preview.js
  jest.legacy.config.js
  package.json
  src/Components/AuthDialog/AuthDialogContext.tsx
  src/Components/FlashBanner/index.tsx
  src/Components/NavBar/NavBarLoggedInActions.tsx
  src/Server/config.ts
  src/Server/setup_sharify.ts
  src/System/Boot.tsx
  src/System/Relay/__tests__/createRelaySSREnvironment.jest.ts
  src/System/Relay/createRelaySSREnvironment.ts
  src/System/Router/Utils/__tests__/serializeRelayHydrationData.jest.ts
  src/System/Router/Utils/collectAssets.tsx
  src/System/Router/Utils/renderToStream.tsx
  src/System/Router/Utils/serializeRelayHydrationData.tsx
  src/System/Router/__tests__/clientRouter.jest.tsx
  src/System/Router/__tests__/serverRouter.jest.enzyme.tsx
  src/System/Router/clientRouter.tsx
  src/System/Router/renderServerApp.tsx
  src/System/Router/serverRouter.tsx
  src/Typings/global.d.ts
  src/Typings/sharify.d.ts
  src/server.ts
  webpack/bundleSplitting.js
  yarn.lock
Labels: performance

#14886 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14904 Deploy
  src/Apps/Auction/Components/Form/AddressFormWithCreditCard.tsx
  src/Apps/Auction/Components/Form/ConditionsOfSaleCheckbox.tsx
  src/Apps/Auction/Components/Form/ErrorStatus.tsx
  src/Apps/Auction/Components/Form/Utils/initialValues.ts
  src/Apps/Auction/Components/Form/__tests__/AddressForm.jest.enzyme.tsx
  src/Apps/Auction/Components/Form/__tests__/AddressFormWithCreditCard.jest.enzyme.tsx
  src/Apps/Auction/Components/Form/__tests__/ConditionsOfSaleCheckbox.jest.enzyme.tsx
  src/Apps/Auction/Components/Form/__tests__/ErrorStatus.jest.enzyme.tsx
  src/Apps/Auction/Hooks/__tests__/useCreateTokenAndSubmit.jest.tsx
  src/Apps/Auction/Hooks/useAuctionFormContext.ts
  src/Apps/Auction/Hooks/useCreateTokenAndSubmit.ts
  src/Apps/Auction/Routes/Bid/Components/PricingTransparency.tsx
  src/Apps/Invoice/Components/AddressForm.tsx
  src/Apps/Invoice/Components/AddressFormWithCreditCard.tsx
  src/Apps/Invoice/Components/InvoicePaymentForm.tsx
  src/Apps/Invoice/Hooks/__tests__/useCreateTokenAndSubmit.jest.ts
  src/Apps/Invoice/Hooks/useCreateTokenAndSubmit.ts
  src/Apps/Invoice/Hooks/useFormContext.ts
  src/Apps/Order/Components/CreditCardPicker.tsx
  src/Apps/Order/Components/__tests__/CreditCardPicker.jest.enzyme.enzyme.tsx
  src/Apps/Order/Utils/__tests__/formValidators.jest.tsx
  src/Apps/Order/Utils/formValidators.tsx
  src/Components/Address/AddressAutocompleteInput.tsx
  src/Components/Address/AddressForm.tsx
  src/Components/Address/AddressFormFields.tsx
  src/Components/Address/__tests__/AddressFormFields.jest.tsx
  src/Components/Address/__tests__/utils.ts
  src/Components/Address/useAddressAutocomplete.ts
  src/Components/Address/utils.ts
  src/Components/AppDownloadFooter.tsx
  src/Components/__tests__/Utils/addressForm.ts
  src/Components/__tests__/Utils/addressForm2.ts
Labels: Jira Synced

#14908 chore: consolidating messaging endpoints
  src/Components/SalesforceWrapper.tsx
  src/Server/config.ts
  src/Server/setup_sharify.ts
  src/Typings/sharify.d.ts
Labels: Jira Synced

#14905 chore(perf): avoid loading artworks' associated artists unnecessarily
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/PrivateArtworkAboutArtistQuery.graphql.ts
  src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: performance

#14914 chore(webpack): Removes SWC compilation pipeline in prep for RSPack, take 2
  .gitignore
  .swcrc.js
  HACKS.md
  __mocks__/@loadable/component.tsx
  coffeelint.json
  jest.config.js
  jest.legacy.config.js
  package.json
  scripts/clean.sh
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/__tests__/SettingsEditSettingsTwoFactorBackupCodesActions.jest.enzyme.tsx
  webpack/envs/clientDevelopmentConfig.js
  webpack/sharedLoaders.js
  webpack/webpackEnv.js
  yarn.lock
Labels: Merge On Green

#14918 feat(prefetching): Prefetch JS alongside network responses
  src/Apps/Alert/alertRoutes.tsx
  src/Apps/ArtQuiz/artQuizRoutes.tsx
  src/Apps/Article/articleRoutes.tsx
  src/Apps/Articles/articlesRoutes.tsx
  src/Apps/Artist/artistRoutes.tsx
  src/Apps/ArtistSeries/artistSeriesRoutes.tsx
  src/Apps/Artists/artistsRoutes.tsx
  src/Apps/Artwork/artworkRoutes.tsx
  src/Apps/Auction/auctionRoutes.tsx
  src/Apps/Auctions/EndingSoonAuctions/endingSoonAuctionsRoutes.tsx
  src/Apps/Auctions/auctionsRoutes.tsx
  src/Apps/Authentication/authenticationRoutes.tsx
  src/Apps/BuyerGuarantee/buyerGuaranteeRoutes.tsx
  src/Apps/Categories/categoriesRoutes.tsx
  src/Apps/Collect/collectRoutes.tsx
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/Apps/Components/AppShell.tsx
  src/Apps/Components/__tests__/AppShell.jest.tsx
  src/Apps/Example/exampleRoutes.tsx
  src/Apps/Fair/fairRoutes.tsx
  src/Apps/FairOrginizer/fairOrganizerRoutes.tsx
  src/Apps/Fairs/fairsRoutes.tsx
  src/Apps/Favorites/favoritesRoutes.tsx
  src/Apps/Feature/featureRoutes.tsx
  src/Apps/Gene/geneRoutes.tsx
  src/Apps/Home/homeRoutes.tsx
  src/Apps/IdentityVerification/identityVerificationRoutes.tsx
  src/Apps/Invoice/invoiceRoutes.tsx
  src/Apps/Jobs/jobsRoutes.tsx
  src/Apps/Marketing/marketingRoutes.tsx
  src/Apps/MyCollection/myCollectionRoutes.tsx
  src/Apps/MyCollectionInsights/myCollectionInsightsCollectorProfileRoutes.tsx
  src/Apps/MyCollectionInsights/myCollectionInsightsRoutes.tsx
  src/Apps/NewForYou/newForYouRoutes.tsx
  src/Apps/NewWorksFromGalleriesYouFollow/newWorksFromGalleriesYouFollowRoutes.tsx
  src/Apps/Notifications/notificationsRoutes.ts
  src/Apps/Onboarding/onboardingRoutes.tsx
  src/Apps/Order/orderRoutes.tsx
  src/Apps/Page/pageRoutes.tsx
  src/Apps/Partner/partnerRoutes.tsx
  src/Apps/PartnerOffer/partnerOfferRoutes.tsx
  src/Apps/Partners/partnersRoutes.ts
  src/Apps/Preferences/preferencesRoutes.tsx
  src/Apps/Press/pressRoutes.tsx
  src/Apps/PriceDatabase/priceDatabaseRoutes.tsx
  src/Apps/Sale/saleRoutes.tsx
  src/Apps/SaleAgreements/saleAgreementsRoutes.tsx
  src/Apps/Search/searchRoutes.tsx
  src/Apps/Sell/sellRoutes.tsx
  src/Apps/Settings/settingsRoutes.tsx
  src/Apps/Show/showRoutes.tsx
  src/Apps/Shows/showsRoutes.tsx
  src/Apps/Tag/tagRoutes.tsx
  src/System/Hooks/usePrefetchRoute.tsx
  src/System/Router/Route.tsx
Labels: performance

#14919 chore(preloading): add a couple missing routes
  src/Apps/ViewingRoom/viewingRoomRoutes.tsx
  src/Apps/WorksForYou/worksForYouRoutes.tsx
Labels: Merge On Green

#14922 fix(artwork): Bump fetch priority on main image preloader
  cypress/e2e/artwork.cy.js
  src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
  src/Apps/Artwork/Components/ArtworkLightbox.tsx
  src/Apps/Artwork/Components/ArtworkLightboxPlaceholder.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkImageBrowserLarge_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowserSmall_Test_Query.graphql.ts
  src/__generated__/ArtworkLightboxTestQuery.graphql.ts
  src/__generated__/ArtworkLightbox_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Merge On Green

#14813 chore: Add tracking to Alert list actions
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
Labels: Jira Synced
