Repository artsy/force, pull requests merged in 2024-07, with the labels that each got.

#14118 fix: Adjust Sell flow thank you step font size
  src/Apps/Sell/Routes/PhoneNumberRoute.tsx
  src/Apps/Sell/Routes/ThankYouRoute.tsx
Labels: Squash On Green

#14102 feat: New Sell flow meta tags
  src/Apps/Consign/Routes/MarketingLanding/Components/SellMeta.tsx
  src/Apps/Sell/Routes/IntroRoute.tsx
  src/Apps/Sell/Routes/NewRoute.tsx
  src/Apps/Sell/Routes/SubmissionRoute.tsx
  src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/NewRoute.jest.tsx
Labels: Jira Synced

#14124 fix: New Sell flow design adjustments and fixes
  src/Apps/Sell/Components/SubmissionLayout.tsx
  src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
  src/Apps/Sell/Routes/ArtistRoute.tsx
  src/Apps/Sell/Routes/DimensionsRoute.tsx
  src/Apps/Sell/Routes/PhotosRoute.tsx
  src/Apps/Sell/Routes/__tests__/PhotosRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/TitleRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
Labels: Squash On Green

#14123 fix(ONYX-1037): change isMobile efinition
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
Labels: Jira Synced

#14049 feat: defer forced login / sign up to end of SWA submission flow
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HeaderSWA.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
Labels: Jira Synced

#14130 chore: deploy ai review app
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Article.tsx
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollection.tsx
Labels: Merge On Green

#14131 fix: remove validation redirects in existing submission flow
  src/Apps/Consign/Routes/SubmissionFlow/Utils/redirects.ts
Labels: Jira Synced

#14121 chore: Add invisible ReCaptcha to new Sell flow
  src/Apps/Sell/Routes/NewRoute.tsx
Labels: Squash On Green

#14138 fix: Update Sell flow photo step copy
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
  src/Apps/Sell/Routes/__tests__/PhotosRoute.jest.tsx
  src/Components/PhotoUpload/Utils/fileUtils.ts
Labels: Squash On Green

#14139 fix: Bring Back button back to Sell flow title step
  src/Apps/Sell/Routes/__tests__/TitleRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
Labels: Jira Synced, Squash On Green

#14140 fix: Adjust Tips for taking photos font size
  src/Apps/Sell/Routes/PhotosRoute.tsx
Labels: Squash On Green

#14135 chore(AMBER-769): Remove logic to display hardcoded message for "Bidding closed"
  src/Components/Artwork/Details.tsx
  src/Components/Artwork/__tests__/Details.jest.tsx
Labels: Jira Synced

#14142 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14141 fix: allow scrolling from any part of the add photos page
  src/Apps/Sell/Components/SubmissionLayout.tsx
Labels: Jira Synced, Squash On Green

#14145 fix: align check icon
  src/Apps/Sell/Components/SubmissionProgressBar.tsx
Labels: Jira Synced

#14143 chore: add border to bottom form navigation
  src/Apps/Sell/Components/BottomFormNavigation.tsx
Labels: Jira Synced

#14147 fix: Adjust Sell flow bottom navigation
  src/Apps/Sell/Components/BottomFormNavigation.tsx
Labels: Squash On Green

#14149 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14108 feat: Finish previous submission experience
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviousSubmission.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HeaderSWA.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/Apps/Sell/Components/SubmissionHeader.tsx
  src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Apps/Sell/Utils/previousSubmissionUtils.ts
  src/Components/EntityHeaders/EntityHeaderSubmission.tsx
  src/__generated__/EntityHeaderSubmission_submission.graphql.ts
  src/__generated__/PreviousSubmissionQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#14150 fix: Finish previous submission adjustments
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviousSubmission.tsx
  src/Apps/Sell/Components/SubmissionHeader.tsx
  src/__generated__/PreviousSubmissionQuery.graphql.ts
Labels: Squash On Green

#14144 feat: defer SWA login/signup prompt in SWAFooter/SWAStickyFooter
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SWAFooter.jest.tsx
Labels: Jira Synced

#14153 fix: Add Yup validation to Previous submission localStorage data
  src/Apps/Sell/Utils/previousSubmissionUtils.ts
Labels: Jira Synced, Squash On Green

#14154 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useCreateArtworkMutation.graphql.ts
  src/__generated__/useUpdateArtworkMutation.graphql.ts
Labels: Squash On Green

#14162 chore(DIA-747): updates artists in navbar
  src/Components/NavBar/menuData.ts
Labels: Merge On Green, Jira Synced

#14157 fix: adjust add photos page
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormImages.tsx
  src/Apps/Sell/Components/UploadMoreMessage.tsx
  src/Components/PhotoUpload/Components/PhotoDropzone.tsx
  src/Components/PhotoUpload/__tests__/PhotoDropzone.jest.tsx
Labels: Jira Synced

#14164 fix: add Select option to the Select component values
  src/Apps/Sell/Routes/PurchaseHistoryRoute.tsx
  src/Apps/Sell/Routes/__tests__/PurchaseHistoryRoute.jest.tsx
  src/Apps/Sell/Utils/formUtils.ts
Labels: Jira Synced, Squash On Green

#14160 feat: add availability filter to other artwork grids
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
  src/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilters.jest.tsx
  src/Apps/ArtistSeries/__tests__/ArtistSeriesArtworksFilter.jest.tsx
  src/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx
  src/Apps/Collect/Routes/Collection/Components/__tests__/CollectionArtworksFilter.jest.tsx
  src/Apps/Fair/Routes/FairArtworks.tsx
  src/Apps/Gene/Components/__tests__/GeneArtworkFilter.jest.tsx
  src/Apps/Partner/Routes/__tests__/Works.jest.tsx
  src/Apps/Search/Components/SearchResultsArtworksFilters.tsx
  src/Apps/Show/__tests__/ShowArtworks.jest.tsx
  src/Apps/Tag/Components/__tests__/TagArtworkFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/AvailabilityFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/AvailabilityFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/index.tsx
Labels: Jira Synced

#14161 Deploy
  src/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormImages.tsx
  src/Apps/Order/Routes/Shipping2/Components/ShippingQuotes2.tsx
  src/Apps/Order/Routes/Shipping2/Hooks/useSelectFirstShippingQuote.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Sell/Components/ImagePreviewItem.tsx
  src/Apps/Sell/Components/ImagePreviewsGrid.tsx
  src/Apps/Sell/Components/SubmissionLayout.tsx
  src/Apps/Sell/Components/UploadMoreMessage.tsx
  src/Apps/Sell/Routes/PurchaseHistoryRoute.tsx
  src/Apps/Sell/Routes/__tests__/PurchaseHistoryRoute.jest.tsx
  src/Apps/Sell/Utils/formUtils.ts
  src/Components/NavBar/menuData.ts
  src/Components/PhotoUpload/Components/PhotoDropzone.tsx
  src/Components/PhotoUpload/__tests__/PhotoDropzone.jest.tsx
Labels: Jira Synced

#14169 Deploy
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
  src/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilters.jest.tsx
  src/Apps/ArtistSeries/__tests__/ArtistSeriesArtworksFilter.jest.tsx
  src/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx
  src/Apps/Collect/Routes/Collection/Components/__tests__/CollectionArtworksFilter.jest.tsx
  src/Apps/Fair/Routes/FairArtworks.tsx
  src/Apps/Gene/Components/__tests__/GeneArtworkFilter.jest.tsx
  src/Apps/Partner/Routes/__tests__/Works.jest.tsx
  src/Apps/Search/Components/SearchResultsArtworksFilters.tsx
  src/Apps/Show/__tests__/ShowArtworks.jest.tsx
  src/Apps/Tag/Components/__tests__/TagArtworkFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/AvailabilityFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/AvailabilityFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/index.tsx
Labels: Jira Synced

#14170 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14173 fix: Align Sell flow exit button on mobile
  src/Apps/Sell/Components/SubmissionHeader.tsx
Labels: Jira Synced

#14175 chore: Replace new Sell flow routes: `/sell2` - `/sell`
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviousSubmission.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HeaderSWA.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSWASection.jest.tsx
  src/Apps/Sell/Components/StepsNavigation.tsx
  src/Apps/Sell/Routes/ArtistNotEligibleRoute.tsx
  src/Apps/Sell/Routes/ArtistRoute.tsx
  src/Apps/Sell/Routes/IntroRoute.tsx
  src/Apps/Sell/Routes/ThankYouRoute.tsx
  src/Apps/Sell/Routes/__tests__/ArtistNotEligibleRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/DetailsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/PhoneNumberRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/PhotosRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/PurchaseHistoryRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ThankYouRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Apps/Sell/sellRoutes.tsx
Labels: Jira Synced

#14179 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/SettingsEditProfileImageMutation.graphql.ts
  src/__generated__/useAddCreditCardAndUpdateProfileMutation.graphql.ts
  src/__generated__/useUpdateMyUserProfileMutation.graphql.ts
  src/__generated__/useUpdateSettingsInformationMutation.graphql.ts
Labels: Squash On Green

#14133 fix(ONYX-1097): adjust component structure
  src/Apps/Notifications/NotificationsApp.tsx
  src/Apps/Notifications/notificationsutils.ts
  src/Components/Notifications/AlertNotification.tsx
  src/Components/Notifications/ArticleFeaturedArtistNotification.tsx
  src/Components/Notifications/ArtworkPublishedNotification.tsx
  src/Components/Notifications/Notification.tsx
  src/Components/Notifications/NotificationItem.tsx
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/PartnerShowOpenedNotification.tsx
  src/Components/Notifications/ViewingRoomPublishedNotification.tsx
Labels: Jira Synced

#14186 chore: deploy AI review app
  src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Interests.tsx
Labels: Merge On Green

#14190 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14132 feat(EMI-1957): basic useCollectorSignals hooks for list and single artworks
  src/Components/ArtworkGrid/ArtworkGridContext.tsx
  src/Utils/Hooks/useCollectorSignals.tsx
  src/Utils/__tests__/useCollectorSignals.jest.tsx
  src/__generated__/ArtworkGridContext_artworksConnection.graphql.ts
  src/__generated__/ArtworkGridContext_me.graphql.ts
  src/__generated__/useCollectorSignalsArtworksConnectionTestQuery.graphql.ts
  src/__generated__/useCollectorSignalsSingleArtworkTestQuery.graphql.ts
  src/__generated__/useCollectorSignals_artwork.graphql.ts
  src/__generated__/useCollectorSignals_artworksConnection.graphql.ts
  src/__generated__/useCollectorSignals_me.graphql.ts
Labels: Jira Synced, Squash On Green

#14168 chore(ONYX-1107): retrieve swa specialists data from MP
  src/Apps/Consign/Routes/ConsignmentInquiry/ConsignmentInquiry.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/__tests__/ConsignmentInquiry.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviouslySoldOnArtsyRail.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/MeetTheSpecialists.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/Apps/Consign/consignRoutes.tsx
  src/__generated__/ConsignmentInquiry_Test_Query.graphql.ts
  src/__generated__/ConsignmentInquiry_viewer.graphql.ts
  src/__generated__/MeetTheSpecialistsQuery.graphql.ts
  src/__generated__/MeetTheSpecialists_staticContent.graphql.ts
  src/__generated__/MeetTheSpecialists_test_Query.graphql.ts
  src/__generated__/consignRoutes_ConsignmentInquiryAppQuery.graphql.ts
  src/__generated__/consignRoutes_ConsignmentInquiryWithRecipientEmailAppQuery.graphql.ts
Labels: Jira Synced

#14188 chore: Use submission's `internalID` for Sell flow tracking
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Components/StepsNavigation.tsx
  src/Apps/Sell/Components/SubmissionHeader.tsx
  src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
  src/Apps/Sell/Routes/SubmissionRoute.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/PhoneNumberRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
Labels: Squash On Green

#14193 chore(copy): update checkout - to check out
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebar.jest.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#14192 Deploy
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebar.jest.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/ConsignmentInquiry.tsx
  src/Apps/Consign/Routes/ConsignmentInquiry/__tests__/ConsignmentInquiry.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviouslySoldOnArtsyRail.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/MeetTheSpecialists.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/Apps/Consign/consignRoutes.tsx
  src/Apps/Sell/Components/BottomFormNavigation.tsx
  src/Apps/Sell/Components/StepsNavigation.tsx
  src/Apps/Sell/Components/SubmissionHeader.tsx
  src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
  src/Apps/Sell/Routes/SubmissionRoute.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/PhoneNumberRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Components/ArtworkGrid/ArtworkGridContext.tsx
  src/System/i18n/locales/en-US/translation.json
  src/Utils/Hooks/useCollectorSignals.tsx
  src/Utils/__tests__/useCollectorSignals.jest.tsx
  src/__generated__/ArtworkGridContext_artworksConnection.graphql.ts
  src/__generated__/ArtworkGridContext_me.graphql.ts
  src/__generated__/ConsignmentInquiry_Test_Query.graphql.ts
  src/__generated__/ConsignmentInquiry_viewer.graphql.ts
  src/__generated__/MeetTheSpecialistsQuery.graphql.ts
  src/__generated__/MeetTheSpecialists_staticContent.graphql.ts
  src/__generated__/MeetTheSpecialists_test_Query.graphql.ts
  src/__generated__/consignRoutes_ConsignmentInquiryAppQuery.graphql.ts
  src/__generated__/consignRoutes_ConsignmentInquiryWithRecipientEmailAppQuery.graphql.ts
  src/__generated__/useCollectorSignalsArtworksConnectionTestQuery.graphql.ts
  src/__generated__/useCollectorSignalsSingleArtworkTestQuery.graphql.ts
  src/__generated__/useCollectorSignals_artwork.graphql.ts
  src/__generated__/useCollectorSignals_artworksConnection.graphql.ts
  src/__generated__/useCollectorSignals_me.graphql.ts
Labels: Jira Synced

#14194 feat: real-time art quiz recs
  src/Apps/ArtAdvisor/08-Art-Quiz/server.ts
  src/Apps/ArtAdvisor/08-Art-Quiz/types.ts
  src/Apps/ArtAdvisor/08-Art-Quiz/weaviate-db.ts
  src/Apps/ArtAdvisor/ArtAdvisorServerRoutes.ts
  src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
  src/Apps/ArtQuiz/__tests__/ArtQuizArtworks.jest.tsx
  src/__generated__/ArtQuizArtworks_Test_Query.graphql.ts
  src/__generated__/ArtQuizArtworks_me.graphql.ts
  src/__generated__/artQuizRoutes_ArtworksQuery.graphql.ts
Labels: Squash On Green

#14196 Deploy
  src/Apps/ArtAdvisor/08-Art-Quiz/server.ts
  src/Apps/ArtAdvisor/08-Art-Quiz/types.ts
  src/Apps/ArtAdvisor/08-Art-Quiz/weaviate-db.ts
  src/Apps/ArtAdvisor/ArtAdvisorServerRoutes.ts
  src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
  src/Apps/ArtQuiz/__tests__/ArtQuizArtworks.jest.tsx
  src/__generated__/ArtQuizArtworks_Test_Query.graphql.ts
  src/__generated__/ArtQuizArtworks_me.graphql.ts
  src/__generated__/artQuizRoutes_ArtworksQuery.graphql.ts
Labels: Merge On Green

#14197 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14199 feat: Navigate to MyC artwork page on Sell flow thank you step
  src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
  src/Apps/Sell/Routes/ThankYouRoute.tsx
  src/Apps/Sell/Routes/__tests__/AdditionalDocumentsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ArtistRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ConditionRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/DetailsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/FrameRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/NewRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/PhoneNumberRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/PhotosRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/PurchaseHistoryRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ShippingLocationRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ThankYouRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/TitleRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/__generated__/ThankYouRoute_Test_Query.graphql.ts
  src/__generated__/ThankYouRoute_submission.graphql.ts
  src/__generated__/sellRoutes_ThankYouRouteQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#14195 fix: make manual prepending of US account for possibility of 'under' in price
  src/Apps/Order/Components/ArtworkSummaryItem.tsx
  src/Apps/Order/Utils/currencyUtils.ts
Labels: Jira Synced

#14203 fix(artist): Ensure subroutes 404 by adding @principleField directive
  src/Apps/Artist/Routes/CV/ArtistCVRoute.tsx
  src/Apps/Artist/Routes/Shows/ArtistShowsRoute.tsx
  src/Apps/Artist/artistRoutes.tsx
  src/Components/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/Components/ArtworkFilter/Utils/getInitialFilterState.ts
  src/__generated__/ArtistCVRoute_Test_Query.graphql.ts
  src/__generated__/ArtistCVRoute_viewer.graphql.ts
  src/__generated__/ArtistShowsRoute_viewer.graphql.ts
  src/__generated__/artistRoutes_ArticlesQuery.graphql.ts
  src/__generated__/artistRoutes_ArtistConsignQuery.graphql.ts
  src/__generated__/artistRoutes_ArtistSeriesQuery.graphql.ts
  src/__generated__/artistRoutes_ArtistSubAppQuery.graphql.ts
  src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
  src/__generated__/artistRoutes_CVQuery.graphql.ts
  src/__generated__/artistRoutes_OverviewQuery.graphql.ts
  src/__generated__/artistRoutes_ShowsQuery.graphql.ts
  src/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
Labels: Merge On Green, Jira Synced

#14125 feat: includes artists in collection during inquiry
  package.json
  src/Components/CollectorProfile/CollectorProfileArtistsAdd.tsx
  src/Components/CollectorProfile/CollectorProfileArtistsAddDialog.tsx
  src/Components/CompleteProfile/CompleteProfileCollectionDialog.tsx
  src/Components/Inquiry/Hooks/useArtworkInquiryRequest.ts
  src/Components/Inquiry/Hooks/useInquiryContext.tsx
  src/Components/Inquiry/Inquiry.tsx
  src/Components/Inquiry/Views/InquiryArtistsInCollection.tsx
  src/Components/Inquiry/Views/InquiryBasicInfo.tsx
  src/Components/Inquiry/Views/InquiryInquiry.tsx
  src/Components/Inquiry/Views/InquiryLogin.tsx
  src/Components/Inquiry/__tests__/Views/InquiryBasicInfo.jest.tsx
  src/Components/Inquiry/config.ts
  src/Utils/Hooks/useMutation.ts
  src/Utils/Hooks/useOnce.ts
  src/__generated__/CollectorProfileArtistsAddCreateUserInterestsMutation.graphql.ts
  src/__generated__/CollectorProfileArtistsAddQuery.graphql.ts
  src/__generated__/InquiryBasicInfoQuery.graphql.ts
  src/__generated__/InquiryBasicInfo_Test_Query.graphql.ts
  src/__generated__/InquiryBasicInfo_me.graphql.ts
  src/__generated__/useInquiryContextQuery.graphql.ts
  src/__generated__/useInquiryContext_me.graphql.ts
  yarn.lock
Labels: Jira Synced

#14205 fix: Filter out null notifications in Activity panel
  src/Components/Notifications/__tests__/NotificationsList.jest.tsx
  src/Components/Notifications/__tests__/util.jest.ts
  src/Components/Notifications/util.ts
Labels: Jira Synced

#14209 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/addAssetToConsignmentMutation.graphql.ts
Labels: Squash On Green

#14214 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14217 chore(loading-bar): Less fade
  src/System/Components/PageLoadingBar.tsx
Labels: Merge On Green

#14221 feat(onyx-1112): sell frame step
  src/Apps/Sell/Mutations/useUpdateMyCollectionArtwork.tsx
  src/Apps/Sell/Routes/AdditionalRoutes/FrameRoute.tsx
  src/Apps/Sell/Routes/__tests__/FrameRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/__generated__/FrameRoute_Test_Query.graphql.ts
  src/__generated__/FrameRoute_submission.graphql.ts
  src/__generated__/sellRoutes_FrameRouteQuery.graphql.ts
  src/__generated__/useUpdateMyCollectionArtworkMutation.graphql.ts
Labels: Jira Synced

#14219 chore(ONYX-1128): update thank you step
  src/Apps/Sell/Routes/ThankYouRoute.tsx
  src/Apps/Sell/Routes/__tests__/ThankYouRoute.jest.tsx
Labels: Jira Synced, Squash On Green

#14224 fix(loading-bar): remove unnecessary prop
  src/System/Components/PageLoadingBar.tsx
Labels: Merge On Green

#14226 chore: update relay generated files
  src/__generated__/sellRoutes_ThankYouRouteQuery.graphql.ts
Labels: Jira Synced

#14218 feat: render consistent number of lines on artwork brick for collector signals
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListArtworksGrid.tsx
  src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx
  src/Components/Artwork/Details.tsx
  src/Components/ArtworkGrid/ArtworkGridContext.tsx
Labels: Merge On Green, Jira Synced

#14156 feat: adds activity cards for complete profile prompts
  src/Apps/Notifications/NotificationsApp.tsx
  src/Components/CompleteProfile/CompleteProfileCollectionDialog.tsx
  src/Components/CompleteProfile/CompleteProfileInformationDialog.tsx
  src/Components/Notifications/AlertNotification.tsx
  src/Components/Notifications/ArticleFeaturedArtistNotification.tsx
  src/Components/Notifications/ArtworkPublishedNotification.tsx
  src/Components/Notifications/ExpiresInTimer.tsx
  src/Components/Notifications/Mutations/markNotificationAsRead.ts
  src/Components/Notifications/Notification.tsx
  src/Components/Notifications/NotificationCollectorProfileUpdatePrompt.tsx
  src/Components/Notifications/NotificationItem.tsx
  src/Components/Notifications/NotificationItemCollectorProfileUpdatePrompt.tsx
  src/Components/Notifications/NotificationItemUnreadIndicator.tsx
  src/Components/Notifications/Notifications.tsx
  src/Components/Notifications/NotificationsList.tsx
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/PartnerShowOpenedNotification.tsx
  src/Components/Notifications/ViewingRoomPublishedNotification.tsx
  src/Components/Notifications/__tests__/Notification.jest.tsx
  src/Components/Notifications/__tests__/NotificationItem.jest.tsx
  src/__generated__/NotificationCollectorProfileUpdatePrompt_notification.graphql.ts
  src/__generated__/NotificationItemCollectorProfileUpdatePrompt_notificationItem.graphql.ts
  src/__generated__/NotificationItem_notification.graphql.ts
  src/__generated__/NotificationItem_test_Query.graphql.ts
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/NotificationsListNextQuery.graphql.ts
  src/__generated__/NotificationsListQuery.graphql.ts
  src/__generated__/NotificationsList_test_Query.graphql.ts
  src/__generated__/NotificationsList_viewer.graphql.ts
Labels: Jira Synced

#14234 fix(homepage): prefers larger version for rails
  src/Apps/Home/Components/HomeCurrentFairs.tsx
  src/__generated__/HomeCurrentFairsQuery.graphql.ts
  src/__generated__/HomeCurrentFairs_Test_Query.graphql.ts
  src/__generated__/HomeCurrentFairs_viewer.graphql.ts
Labels: Merge On Green

#14236 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14213 feat(ONYX-1114): add conditions step
  src/Apps/Artwork/Components/ArtworkDetails/ConditionInfoModal.tsx
  src/Apps/Sell/Components/SubmissionStepTitle.tsx
  src/Apps/Sell/Routes/AdditionalRoutes/ConditionRoute.tsx
  src/Apps/Sell/Routes/__tests__/ConditionRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/FrameRoute.jest.tsx
  src/Apps/Sell/Utils/conditionOptions.tsx
  src/__generated__/ConditionRoute_Test_Query.graphql.ts
  src/__generated__/ConditionRoute_submission.graphql.ts
  src/__generated__/sellRoutes_ConditionRouteQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#14232 Deploy
  .storybook/preview.js
  data/schema.graphql
  package.json
  src/Apps/Artwork/Components/ArtworkDetails/ConditionInfoModal.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListArtworksGrid.tsx
  src/Apps/Debug/debugRoutes.tsx
  src/Apps/Home/Components/HomeCurrentFairs.tsx
  src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx
  src/Apps/Notifications/NotificationsApp.tsx
  src/Apps/Sell/Components/SubmissionStepTitle.tsx
  src/Apps/Sell/Routes/AdditionalRoutes/ConditionRoute.tsx
  src/Apps/Sell/Routes/AdditionalRoutes/ShippingLocationRoute.tsx
  src/Apps/Sell/Routes/__tests__/ConditionRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/FrameRoute.jest.tsx
  src/Apps/Sell/Routes/__tests__/ShippingLocationRoute.jest.tsx
  src/Apps/Sell/Utils/conditionOptions.tsx
  src/Apps/Sell/sellRoutes.tsx
  src/Components/AppDownloadBanner.tsx
  src/Components/Artwork/Details.tsx
  src/Components/ArtworkGrid/ArtworkGridContext.tsx
  src/Components/CompleteProfile/CompleteProfileCollectionDialog.tsx
  src/Components/CompleteProfile/CompleteProfileInformationDialog.tsx
  src/Components/Notifications/AlertNotification.tsx
  src/Components/Notifications/ArticleFeaturedArtistNotification.tsx
  src/Components/Notifications/ArtworkPublishedNotification.tsx
  src/Components/Notifications/ExpiresInTimer.tsx
  src/Components/Notifications/Mutations/markNotificationAsRead.ts
  src/Components/Notifications/Notification.tsx
  src/Components/Notifications/NotificationCollectorProfileUpdatePrompt.tsx
  src/Components/Notifications/NotificationItem.tsx
  src/Components/Notifications/NotificationItemCollectorProfileUpdatePrompt.tsx
  src/Components/Notifications/NotificationItemUnreadIndicator.tsx
  src/Components/Notifications/Notifications.tsx
  src/Components/Notifications/NotificationsList.tsx
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/PartnerShowOpenedNotification.tsx
  src/Components/Notifications/ViewingRoomPublishedNotification.tsx
  src/Components/Notifications/__tests__/Notification.jest.tsx
  src/Components/Notifications/__tests__/NotificationItem.jest.tsx
  src/Components/__stories__/AppDownloadBanner.story.tsx
  src/__generated__/ConditionRoute_Test_Query.graphql.ts
  src/__generated__/ConditionRoute_submission.graphql.ts
  src/__generated__/HomeCurrentFairsQuery.graphql.ts
  src/__generated__/HomeCurrentFairs_Test_Query.graphql.ts
  src/__generated__/HomeCurrentFairs_viewer.graphql.ts
  src/__generated__/NotificationCollectorProfileUpdatePrompt_notification.graphql.ts
  src/__generated__/NotificationItemCollectorProfileUpdatePrompt_notificationItem.graphql.ts
  src/__generated__/NotificationItem_notification.graphql.ts
  src/__generated__/NotificationItem_test_Query.graphql.ts
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/NotificationsListNextQuery.graphql.ts
  src/__generated__/NotificationsListQuery.graphql.ts
  src/__generated__/NotificationsList_test_Query.graphql.ts
  src/__generated__/NotificationsList_viewer.graphql.ts
  src/__generated__/ShippingLocationRoute_Test_Query.graphql.ts
  src/__generated__/ShippingLocationRoute_me.graphql.ts
  src/__generated__/ShippingLocationRoute_submission.graphql.ts
  src/__generated__/sellRoutes_ConditionRouteQuery.graphql.ts
  src/__generated__/sellRoutes_ShippingLocationRouteQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#14240 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14241 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14243 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14245 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14246 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14235 chore(EMI-2005): remove useCollectorSignals() from ArtworkGridContext
  src/Components/ArtworkGrid/ArtworkGridContext.tsx
  src/__generated__/ArtworkGridContext_artworksConnection.graphql.ts
  src/__generated__/ArtworkGridContext_me.graphql.ts
Labels: Jira Synced

#14242 fix: removes unnecessary fetch from every request; adds preference to session
  src/Server/middleware/userPreferencesMiddleware.ts
  src/Server/passport/lib/options.js
  src/System/Contexts/SystemContext.tsx
  src/System/Contexts/__tests__/SystemContext.jest.tsx
  src/System/Router/Utils/clientAppContext.ts
  src/Typings/gravity.d.ts
  src/middleware.ts
Labels: Jira Synced

#14249 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/AdditionalDocumentsRoute_Test_Query.graphql.ts
  src/__generated__/ArtistRoute_Test_Query.graphql.ts
  src/__generated__/ConditionRoute_Test_Query.graphql.ts
  src/__generated__/CreateConsignSubmissionMutation.graphql.ts
  src/__generated__/DetailsRoute_Test_Query.graphql.ts
  src/__generated__/DimensionsRoute_Test_Query.graphql.ts
  src/__generated__/FrameRoute_Test_Query.graphql.ts
  src/__generated__/PhoneNumberRoute_Test_Query.graphql.ts
  src/__generated__/PhotosRoute_Test_Query.graphql.ts
  src/__generated__/PreviousSubmissionQuery.graphql.ts
  src/__generated__/PurchaseHistoryRoute_Test_Query.graphql.ts
  src/__generated__/ShippingLocationRoute_Test_Query.graphql.ts
  src/__generated__/SubmissionRoute_submission.graphql.ts
  src/__generated__/ThankYouRoute_Test_Query.graphql.ts
  src/__generated__/ThankYouRoute_submission.graphql.ts
  src/__generated__/TitleRoute_Test_Query.graphql.ts
  src/__generated__/UpdateConsignSubmissionMutation.graphql.ts
  src/__generated__/useCreateSubmissionMutation.graphql.ts
  src/__generated__/useUpdateSubmissionMutation.graphql.ts
Labels: Squash On Green

#14184 fix: switching from saved pickup back to shipping
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Routes/Shipping2/Utils/shippingUtils.ts
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
Labels: Jira Synced

#14255 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistCVGroupQuery.graphql.ts
  src/__generated__/ArtistShowsGroupQuery.graphql.ts
  src/__generated__/FairBoothsContainerQuery.graphql.ts
  src/__generated__/FairBoothsQuery.graphql.ts
  src/__generated__/FairBooths_Test_Query.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/Status_order.graphql.ts
Labels: Squash On Green

#14229 feat: My Collection artwork page submission status redesign
  src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResultMetaData.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkAboutTab.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkArtistMarket.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkDetailField.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkDetails.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkHeader.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkImageBrowser/MyCollectionArtworkImageBrowser.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkImageBrowser/__tests__/MyCollectionArtworkImageBrowser.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkMeta.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkRequestPriceEstimate.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkRequestPriceEstimateSection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWAHelpSection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWAHowItWorksModal.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASectionSubmitted.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarTitleInfo.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MetadataField.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/index.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSubmitForSale.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkTitle.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionPriceEstimateStatus.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkDetails.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSWAHowItWorksModal.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSWASubmissionStatus.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSubmitForSale.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkTitle.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtworkAboutTab.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/__tests__/MyCollectionArtwork.jest.tsx
  src/Apps/Sell/Routes/__tests__/DetailsRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Components/Notifications/AlertNotification.tsx
  src/__generated__/MyCollectionArtworkAboutTab_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkDetailsTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkDetails_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkHeader_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkInsights_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkRequestPriceEstimate_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkSWASection_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkSWASubmissionStatus_Test_Query.graphql.ts
  src/__generated__/MyCollectionArtworkSWASubmissionStatus_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkSidebar_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkSubmitForSale_Test_Query.graphql.ts
  src/__generated__/MyCollectionArtworkSubmitForSale_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTitleTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTitle_artwork.graphql.ts
  src/__generated__/MyCollectionArtwork_artwork.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#14258 feat: Set submission state when completing tier 2 flow
  src/Apps/Sell/Routes/__tests__/ConditionRoute.jest.tsx
  src/Apps/Sell/SellFlowContext.tsx
Labels: Jira Synced

#14260 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistCVGroupQuery.graphql.ts
  src/__generated__/ArtistShowsGroupQuery.graphql.ts
  src/__generated__/FairBoothsContainerQuery.graphql.ts
  src/__generated__/FairBoothsQuery.graphql.ts
  src/__generated__/FairBooths_Test_Query.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/Status_order.graphql.ts
Labels: Squash On Green

#14261 feat: in addition to cloudflare IPs, allow k8s internal IPs
  hokusai/production.yml
  hokusai/staging.yml
Labels: Merge On Green

#14266 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14267 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistCVGroupQuery.graphql.ts
  src/__generated__/ArtistShowsGroupQuery.graphql.ts
  src/__generated__/FairBoothsContainerQuery.graphql.ts
  src/__generated__/FairBoothsQuery.graphql.ts
  src/__generated__/FairBooths_Test_Query.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/Status_order.graphql.ts
Labels: Squash On Green
