Repository artsy/force, pull requests merged in 2024-03, with the labels that each got.

#13546 chore: Rename "following" notification type to "follows"
  src/Components/Notifications/NotificationsEmptyStateByType.tsx
  src/Components/Notifications/NotificationsList.tsx
  src/Components/Notifications/NotificationsPills.tsx
  src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx
  src/Components/Notifications/types.ts
Labels: Squash On Green

#13558 fix(nav-menu): Close artist and artworks dropdowns on nav item click
  src/Components/NavBar/NavBar.tsx
Labels: Merge On Green

#13547 feat(ONYX-728): address design changes in alerts management section
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
  src/__generated__/SavedSearchAlertListItem_item.graphql.ts
  src/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
  src/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
  src/__generated__/SavedSearchAlertsApp_me.graphql.ts
  src/__generated__/settingsRoutes_SavedSearchAlertsAppEditQuery.graphql.ts
  src/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts
Labels: Jira Synced

#13564 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13566 chore: Use totalCount for offer notifications
  src/Components/Notifications/NotificationsPills.tsx
  src/__generated__/NotificationsPillsQuery.graphql.ts
Labels: Jira Synced

#13563 Deploy
  data/schema.graphql
  package.json
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutWork.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkCondition.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkDetails.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkExhibitionHistory.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkMetadata.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkProvenance.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
  src/Components/Notifications/NotificationsPills.tsx
  src/__generated__/NotificationsPillsQuery.graphql.ts
  src/__generated__/PrivateArtworkCondition_artwork.graphql.ts
  src/__generated__/PrivateArtworkDetails_artwork.graphql.ts
  src/__generated__/PrivateArtworkMetadata_artwork.graphql.ts
  src/__generated__/PrivateArtworkProvenance_artwork.graphql.ts
  src/__generated__/SavedSearchAlertListItem_item.graphql.ts
  src/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
  src/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
  src/__generated__/SavedSearchAlertsApp_me.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/settingsRoutes_SavedSearchAlertsAppEditQuery.graphql.ts
  src/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#13567 fix: avoids remounting
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
Labels: Jira Synced

#13569 fix: NavBar categories menu links to emerging-art collection
  src/Components/NavBar/menuData.ts
Labels: Jira Synced

#13555 build(deps): bump passport-facebook from 2.1.1 to 3.0.0
  package.json
  yarn.lock
Labels: Jira Synced

#13572 feat(works-for-you): includes login prompt when logged out
  src/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx
  src/Apps/WorksForYou/WorksForYouApp.tsx
  src/Apps/WorksForYou/worksForYouRoutes.tsx
Labels: Jira Synced

#13577 fix: spacing on new alert counts
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
Labels: Jira Synced

#13579 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13581 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13578 feat (AMBER-534) Added remaining Sidebar data (private artworks)
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPrivateArtwork.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarPrivateArtwork.jest.tsx
  src/__generated__/ArtworkSidebarPrivateArtworkQuery.graphql.ts
  src/__generated__/ArtworkSidebarPrivateArtwork_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13580 fix: Show authentication dialog on the Notifications app when not logged in
  src/Apps/Notifications/NotificationsApp.tsx
  src/Components/Notifications/Notification.tsx
  src/Components/Notifications/NotificationErrorMessage.tsx
Labels: Jira Synced

#13583 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13584 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13585 refactor: password reset copy
  src/Components/AuthDialog/Views/AuthDialogForgotPassword.tsx
  src/Components/AuthDialog/Views/__tests__/AuthDialogForgotPassword.jest.tsx
Labels: Jira Synced, Squash On Green

#13574 fix(ONYX-826): fix performance after alert deletion
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
Labels: Jira Synced

#13587 Deploy
  package.json
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Components/Notifications/__tests__/Notifications.jest.tsx
  yarn.lock
Labels: Jira Synced

#13570 fix(AMBER-504): Fix Salesforce Chat Bubble for auctions
  src/Apps/Artwork/Components/ArtworkChatBubble.tsx
  src/__generated__/ArtworkChatBubble_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13597 Chore: Removing the Specialists page
  src/Apps/MeetTheSpecialists/MeetTheSpecialistsApp.tsx
  src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
  src/Apps/MeetTheSpecialists/meetTheSpecialistsRoutes.tsx
  src/Components/Footer/Footer.tsx
  src/Server/middleware/hardcodedRedirects.ts
  src/System/i18n/locales/en-US/translation.json
  src/routes.tsx
Labels: Jira Synced

#13609 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13603 chore (Amber-535): Private Artwork Page "About Artist" and "About Artwork" sections
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPrivateArtwork.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarPrivateArtwork.jest.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutWork.tsx
  src/Apps/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkAboutArtist.jest.tsx
  src/Apps/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkAboutWork.jest.tsx
  src/__generated__/ArtworkSidebarPrivateArtworkQuery.graphql.ts
  src/__generated__/ArtworkSidebarPrivateArtwork_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/PrivateArtworkAboutArtistQuery.graphql.ts
  src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
  src/__generated__/PrivateArtworkAboutWorkQuery.graphql.ts
  src/__generated__/PrivateArtworkAboutWork_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13613 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13614 fix(convos): Fix message bubble width
  src/Apps/Conversations/components/Message/ConversationMessage.tsx
  src/Apps/Conversations/components/Message/ConversationMessageBubble.tsx
  src/__generated__/ConversationMessageTestQuery.graphql.ts
  src/__generated__/ConversationMessage_message.graphql.ts
  src/__generated__/ConversationMessagesPaginationQuery.graphql.ts
  src/__generated__/ConversationMessagesTestQuery.graphql.ts
  src/__generated__/conversationsRoutes_DetailQuery.graphql.ts
  src/__generated__/useSendConversationMessageMutation.graphql.ts
Labels: Merge On Green

#13615 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_test_Query.graphql.ts
Labels: Squash On Green

#13611 Refactor: [EMI-1684] Refine relay queries in shipping refactor.
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Components/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/ShippingContext.tsx
  src/Apps/Order/Routes/Shipping2/Utils/computeOrderData.ts
  src/Apps/Order/Routes/Shipping2/Utils/shippingUtils.ts
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Order/orderRoutes.tsx
  src/__generated__/FulfillmentDetailsForm_me.graphql.ts
  src/__generated__/FulfillmentDetailsForm_order.graphql.ts
  src/__generated__/SavedAddresses2TestQuery.graphql.ts
  src/__generated__/Shipping2TestQuery.graphql.ts
  src/__generated__/Shipping2_me.graphql.ts
  src/__generated__/Shipping2_order.graphql.ts
  src/__generated__/ShippingContext_me.graphql.ts
  src/__generated__/ShippingContext_order.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/useCreateSavedAddressMutation.graphql.ts
  src/__generated__/useDeleteSavedAddressMutation.graphql.ts
  src/__generated__/useSaveFulfillmentDetailsMutation.graphql.ts
  src/__generated__/useSelectShippingQuoteMutation.graphql.ts
  src/__generated__/useUpdateSavedAddressMutation.graphql.ts
  src/__generated__/useUpdateUserDefaultAddressMutation.graphql.ts
Labels: Jira Synced

#13619 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13617 fix(ONYX-854): partner offer notification height - adding note v1
  src/Components/Notifications/PartnerOfferArtwork.tsx
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_notification.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_test_Query.graphql.ts
Labels: Jira Synced

#13621 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13622 feat: Implement app preferences + theme select
  src/Apps/AppPreferences/__tests__/appPreferencesServerRoutes.jest.ts
  src/Apps/AppPreferences/appPreferencesMiddleware.ts
  src/Apps/AppPreferences/appPreferencesServerRoutes.ts
  src/Apps/AppPreferences/useAppPreferences.tsx
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsThemeSelect.tsx
  src/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
  src/System/Router/Boot.tsx
  src/System/Router/buildServerApp.tsx
  src/Typings/sharify.d.ts
  src/middleware.ts
  src/server.ts
Labels: Jira Synced

#13618 Deploy
  data/schema.graphql
  package.json
  src/Apps/AppPreferences/__tests__/appPreferencesServerRoutes.jest.ts
  src/Apps/AppPreferences/appPreferencesMiddleware.ts
  src/Apps/AppPreferences/appPreferencesServerRoutes.ts
  src/Apps/AppPreferences/useAppPreferences.tsx
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Components/SavedAddresses2.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/AddressModal2.jest.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/SavedAddresses2.jest.tsx
  src/Apps/Order/Routes/Shipping2/ShippingContext.tsx
  src/Apps/Order/Routes/Shipping2/Utils/computeOrderData.ts
  src/Apps/Order/Routes/Shipping2/Utils/shippingUtils.ts
  src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
  src/Apps/Order/Routes/Shipping2/index.tsx
  src/Apps/Order/orderRoutes.tsx
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsThemeSelect.tsx
  src/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
  src/Components/Notifications/PartnerOfferArtwork.tsx
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx
  src/System/Router/Boot.tsx
  src/System/Router/buildServerApp.tsx
  src/Typings/sharify.d.ts
  src/__generated__/FulfillmentDetailsForm_me.graphql.ts
  src/__generated__/FulfillmentDetailsForm_order.graphql.ts
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_notification.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_test_Query.graphql.ts
  src/__generated__/SavedAddresses2TestQuery.graphql.ts
  src/__generated__/Shipping2TestQuery.graphql.ts
  src/__generated__/Shipping2_me.graphql.ts
  src/__generated__/Shipping2_order.graphql.ts
  src/__generated__/ShippingContext_me.graphql.ts
  src/__generated__/ShippingContext_order.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/useCreateSavedAddressMutation.graphql.ts
  src/__generated__/useDeleteSavedAddressMutation.graphql.ts
  src/__generated__/useSaveFulfillmentDetailsMutation.graphql.ts
  src/__generated__/useSelectShippingQuoteMutation.graphql.ts
  src/__generated__/useUpdateSavedAddressMutation.graphql.ts
  src/__generated__/useUpdateUserDefaultAddressMutation.graphql.ts
  src/middleware.ts
  src/server.ts
  yarn.lock
Labels: Jira Synced

#13626 feat: [EMI-1739] Show expired offer banner when expecting a partner offer id in query params
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkPageBanner.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkPageBanner.jest.tsx
  src/Apps/Artwork/artworkRoutes.tsx
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/ArtworkApp_me.graphql.ts
  src/__generated__/ArtworkPageBanner_Test_Query.graphql.ts
  src/__generated__/ArtworkPageBanner_artwork.graphql.ts
  src/__generated__/ArtworkPageBanner_me.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13627 Deploy
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkPageBanner.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkPageBanner.jest.tsx
  src/Apps/Artwork/artworkRoutes.tsx
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/ArtworkApp_me.graphql.ts
  src/__generated__/ArtworkPageBanner_Test_Query.graphql.ts
  src/__generated__/ArtworkPageBanner_artwork.graphql.ts
  src/__generated__/ArtworkPageBanner_me.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13632 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13633 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13635 fix(progressiveonboarding): simplifies alerts chain
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
  src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx
  src/Components/ArtworkFilter/index.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertCreate.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertReady.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertSelectFilter.tsx
  src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingAlerts.jest.tsx
  src/Components/ProgressiveOnboarding/progressiveOnboardingKeys.tsx
Labels: Jira Synced

#13636 ci(slack): Update slack notification to use circle context
  .circleci/config.yml
Labels: Merge On Green

#13565 fix: Update Alerts screen page to use split view
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormPlaceholder.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertsArtworks.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Apps/Settings/settingsRoutes.tsx
Labels: Jira Synced

#13642 fix(EMI-1770): refactor how we render prices in notification panel for partner offers
  src/Components/Notifications/PartnerOfferArtwork.tsx
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/PartnerOfferArtwork_artwork.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_notification.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_test_Query.graphql.ts
Labels: Jira Synced

#13643 feat(EMI-1773): update copy for saves page tooltips and modals
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListContent.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListForm/ArtworkListForm.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListItem.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/SelectArtworkListsModal/SelectArtworkListItem.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/__tests__/ArtworkListContent.jest.tsx
  src/System/i18n/locales/en-US/translation.json
Labels: Jira Synced

#13644 feat(collectorprofile): roughs in artists page
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListArtist.tsx
  src/Apps/CollectorProfile/Routes/Artists/CollectorProfileArtistsRoute.tsx
  src/Apps/CollectorProfile/Routes/Artists/__tests__/CollectorProfileArtistsRoute.jest.tsx
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/__generated__/CollectorProfileArtistsListArtist_userInterestEdge.graphql.ts
  src/__generated__/CollectorProfileArtistsListQuery.graphql.ts
Labels: Jira Synced

#13638 Deploy
  .circleci/config.yml
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListArtist.tsx
  src/Apps/CollectorProfile/Routes/Artists/CollectorProfileArtistsRoute.tsx
  src/Apps/CollectorProfile/Routes/Artists/__tests__/CollectorProfileArtistsRoute.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves/CollectorProfileSavesRoute.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/Actions/Mutations/useUpdateMeCollection.ts
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListContent.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListForm/ArtworkListForm.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListItem.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListsHeader.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/OfferSettingsModal/OfferSettingsListItem.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/OfferSettingsModal/OfferSettingsModal.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/OfferSettingsModal/__tests__/OfferSettingsListItem.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/OfferSettingsModal/__tests__/OfferSettingsModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/SelectArtworkListsModal/SelectArtworkListItem.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/__tests__/ArtworkListContent.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/__tests__/ArtworkListsHeader.jest.tsx
  src/Apps/CollectorProfile/collectorProfileRoutes.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormPlaceholder.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertsArtworks.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Apps/Settings/settingsRoutes.tsx
  src/Components/Notifications/PartnerOfferArtwork.tsx
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveOfferSettings.tsx
  src/Components/ProgressiveOnboarding/progressiveOnboardingKeys.tsx
  src/System/i18n/locales/en-US/translation.json
  src/__generated__/CollectorProfileArtistsListArtist_userInterestEdge.graphql.ts
  src/__generated__/CollectorProfileArtistsListQuery.graphql.ts
  src/__generated__/CollectorProfileSavesRoute_Test_Query.graphql.ts
  src/__generated__/CollectorProfileSavesRoute_me.graphql.ts
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/OfferSettingsListItem_item.graphql.ts
  src/__generated__/PartnerOfferArtwork_artwork.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_notification.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_test_Query.graphql.ts
  src/__generated__/collectorProfileRoutes_SavesRouteQuery.graphql.ts
  src/__generated__/useUpdateMeCollectionMutation.graphql.ts
Labels: Jira Synced

#13640 feat: enable pills and counts for the availability filter
  src/Components/Alert/AlertProvider.tsx
  src/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/ArtworkFilter/ArtworkFilters/AvailabilityFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/AvailabilityFilter.jest.tsx
  src/Components/ArtworkFilter/Utils/__tests__/countChangedFilters.jest.ts
  src/Components/ArtworkFilter/Utils/countChangedFilters.ts
  src/Components/SavedSearchAlert/Utils/__tests__/extractPills.jest.ts
  src/Components/SavedSearchAlert/Utils/extractPills.ts
  src/Components/SavedSearchAlert/constants.ts
  src/Components/SavedSearchAlert/types.ts
Labels: Jira Synced

#13647 feat: EMI-1736 Create partner-offer-order with purchase button if an active partner offer is present
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercialButtons.jest.tsx
  src/__generated__/ArtworkApp_me.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_me.graphql.ts
  src/__generated__/ArtworkSidebar_me.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13651 Deploy
  package.json
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercialButtons.jest.tsx
  src/Components/Alert/AlertProvider.tsx
  src/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/ArtworkFilter/ArtworkFilters/AvailabilityFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/AvailabilityFilter.jest.tsx
  src/Components/ArtworkFilter/Utils/__tests__/countChangedFilters.jest.ts
  src/Components/ArtworkFilter/Utils/countChangedFilters.ts
  src/Components/Footer/Footer.tsx
  src/Components/Footer/__tests__/Footer.jest.tsx
  src/Components/SavedSearchAlert/Utils/__tests__/extractPills.jest.ts
  src/Components/SavedSearchAlert/Utils/extractPills.ts
  src/Components/SavedSearchAlert/constants.ts
  src/Components/SavedSearchAlert/types.ts
  src/__generated__/ArtworkApp_me.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_me.graphql.ts
  src/__generated__/ArtworkSidebar_me.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#13657 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
