Repository artsy/force, pull requests merged in 2024-12, with the labels that each got.

#14934 fix(bundle-stats): Run on main
  .circleci/config.yml
Labels: Merge On Green

#14936 chore(bootstrap): remove client entrypoint streaming bundle
  webpack/bundleSplitting.js
Labels: Merge On Green

#14939 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/AddressModalTest2Query.graphql.ts
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/NotificationViewingRoom_viewingRoom.graphql.ts
  src/__generated__/PartnerViewingRoomsGrid_Test_Query.graphql.ts
  src/__generated__/PartnerViewingRoomsGrid_ViewingRoomsQuery.graphql.ts
  src/__generated__/ShowApp_Test_Query.graphql.ts
  src/__generated__/ShowViewingRoom_Test_Query.graphql.ts
  src/__generated__/ShowViewingRoom_show.graphql.ts
  src/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_DraftTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_LoggedOutTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_ScheduledTest_Query.graphql.ts
  src/__generated__/ViewingRoomCard_Test_Query.graphql.ts
  src/__generated__/ViewingRoomCard_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomMeta_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomPublishedNotification_test_Query.graphql.ts
  src/__generated__/ViewingRoomsApp_Test_Query.graphql.ts
  src/__generated__/ViewingRoomsFeaturedRail_featuredViewingRooms.graphql.ts
  src/__generated__/ViewingRoomsLatestGrid_ViewingRoomsAppQuery.graphql.ts
  src/__generated__/ViewingRoomsLatestGrid_viewingRooms.graphql.ts
  src/__generated__/partnerRoutes_ViewingRoomsQuery.graphql.ts
  src/__generated__/showRoutes_ShowQuery.graphql.ts
  src/__generated__/viewingRoomRoutes_ViewingRoomQuery.graphql.ts
  src/__generated__/viewingRoomRoutes_ViewingRoomsAppQuery.graphql.ts
Labels: Squash On Green

#14938 Deploy
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/UtilButton.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.jest.enzyme.tsx
  src/Apps/Order/Routes/Shipping/Components/AddressModal.tsx
  src/Apps/Order/Routes/Shipping/Components/__tests__/AddressModal.jest.enzyme.tsx
  src/Apps/Order/Routes/Shipping/Components/__tests__/AddressModal.jest.tsx
  src/Apps/Order/Routes/Shipping/Components/__tests__/SavedAddresses.jest.tsx
  src/Components/Address/AddressFormFields.tsx
  src/Components/Address/__tests__/AddressFormFields.jest.tsx
  src/Components/Address/__tests__/utils.ts
  src/Server/config.ts
  src/Server/setup_sharify.ts
  src/Typings/sharify.d.ts
  src/__generated__/AddressModalTest2Query.graphql.ts
Labels: Jira Synced

#14940 chore(performance): Optimize rehydration
  src/client.tsx
Labels: performance

#14943 fix(integrity): undo changes
  src/Apps/Components/AppShell.tsx
  src/client.tsx
Labels: Merge On Green

#14941 Deploy
  data/schema.graphql
  src/__generated__/AddressModalTest2Query.graphql.ts
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/NotificationViewingRoom_viewingRoom.graphql.ts
  src/__generated__/PartnerViewingRoomsGrid_Test_Query.graphql.ts
  src/__generated__/PartnerViewingRoomsGrid_ViewingRoomsQuery.graphql.ts
  src/__generated__/ShowApp_Test_Query.graphql.ts
  src/__generated__/ShowViewingRoom_Test_Query.graphql.ts
  src/__generated__/ShowViewingRoom_show.graphql.ts
  src/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_DraftTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_LoggedOutTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_ScheduledTest_Query.graphql.ts
  src/__generated__/ViewingRoomCard_Test_Query.graphql.ts
  src/__generated__/ViewingRoomCard_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomMeta_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomPublishedNotification_test_Query.graphql.ts
  src/__generated__/ViewingRoomsApp_Test_Query.graphql.ts
  src/__generated__/ViewingRoomsFeaturedRail_featuredViewingRooms.graphql.ts
  src/__generated__/ViewingRoomsLatestGrid_ViewingRoomsAppQuery.graphql.ts
  src/__generated__/ViewingRoomsLatestGrid_viewingRooms.graphql.ts
  src/__generated__/partnerRoutes_ViewingRoomsQuery.graphql.ts
  src/__generated__/showRoutes_ShowQuery.graphql.ts
  src/__generated__/viewingRoomRoutes_ViewingRoomQuery.graphql.ts
  src/__generated__/viewingRoomRoutes_ViewingRoomsAppQuery.graphql.ts
Labels: Merge On Green

#14944 perf(EMI-1685): re-enable slow test
  src/Apps/Order/Routes/Shipping/Components/__tests__/SavedAddresses.jest.tsx
  src/Components/Address/__tests__/utils.ts
Labels: Jira Synced

#14946 Deploy
  src/Apps/Order/Routes/Shipping/Components/__tests__/SavedAddresses.jest.tsx
  src/Components/Address/__tests__/utils.ts
  src/Components/NavBar/Menus/NavBarNotifications.tsx
Labels: Jira Synced

#14951 Revert "fix: Revert lazy loading notifications dropdown"
  src/Components/NavBar/Menus/NavBarNotifications.tsx
Labels: Squash On Green

#14955 chore(ONYX-1434): change Curators’ Picks title
  src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx
  src/Apps/Marketing/Routes/MarketingFindArtYouLoveRoute.tsx
Labels: Jira Synced, Squash On Green

#14957 refactor(EMI-1934): autocomplete input, now using useReducer
  src/Components/Address/AddressAutocompleteInput.tsx
  src/Components/Address/__tests__/AddressAutocompleteInput.jest.tsx
Labels: Jira Synced

#14960 Deploy
  src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx
  src/Apps/Marketing/Routes/MarketingFindArtYouLoveRoute.tsx
  src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
  src/Apps/Settings/Routes/Purchases/Components/__tests__/SettingsPurchases.jest.tsx
  src/Components/Address/AddressAutocompleteInput.tsx
  src/Components/Address/__tests__/AddressAutocompleteInput.jest.tsx
  src/__generated__/SettingsPurchasesQuery.graphql.ts
  src/__generated__/SettingsPurchasesRow_order.graphql.ts
  src/__generated__/SettingsPurchases_Test_Query.graphql.ts
  src/__generated__/settingsRoutes_PurchasesRouteQuery.graphql.ts
Labels: Jira Synced

#14963 fix(EMI-1934): address autocomplete keyboard navigation issue
  src/Apps/Order/Routes/Shipping/Components/FulfillmentDetailsForm.tsx
  src/Components/Address/AddressAutocompleteInput.tsx
  src/Components/Address/AddressFormFields.tsx
Labels: Jira Synced

#14956 chore(ONYX-1435): fix phone number validation on SWA submission flow
  src/Apps/Order/Routes/Shipping/Components/AddressModal.tsx
  src/Apps/Sell/Routes/AdditionalRoutes/FrameRoute.tsx
  src/Apps/Sell/Routes/DetailsRoute.tsx
  src/Apps/Sell/Routes/PhoneNumberRoute.tsx
  src/Apps/Sell/SellFlowContext.tsx
Labels: Jira Synced

#14971 chore(palette-charts): Bump 39.1.1 (fix bar chart)
  package.json
  src/Apps/Artwork/Components/__tests__/PricingContext.jest.enzyme.tsx
  yarn.lock
Labels: Merge On Green, Jira Synced

#14972 fix(404): Attempt to fix 404
  src/Server/startServer.ts
Labels: Merge On Green, Jira Synced

#14969 Deploy
  .circleci/config.yml
  cypress/e2e/404.cy.ts
  package.json
  src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
  src/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
  src/Apps/Artist/artistRoutes.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.jest.enzyme.tsx
  src/Apps/Artwork/Utils/createCollectUrl.tsx
  src/Apps/Auction/__tests__/AuctionApp.jest.enzyme.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Utils/categoryOptions.ts
  src/Apps/Order/Routes/Shipping/Components/AddressModal.tsx
  src/Apps/Order/Routes/Shipping/Components/__tests__/SavedAddresses.jest.tsx
  src/Apps/Sell/Routes/AdditionalRoutes/FrameRoute.tsx
  src/Apps/Sell/Routes/DetailsRoute.tsx
  src/Apps/Sell/Routes/PhoneNumberRoute.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Components/Alert/Components/Filters/__tests__/Medium.jest.enzyme.tsx
  src/Components/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
  src/Server/startServer.ts
  src/System/Components/RouterLink.tsx
  src/System/Components/__tests__/RouterLink.jest.tsx
  src/System/Hooks/__tests__/usePrefetchRoute.jest.tsx
  src/System/Hooks/usePrefetchRoute.tsx
  src/__generated__/ArtistWorksForSaleRoute_artist.graphql.ts
  src/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
  src/dev.ts
  src/server.ts
  yarn.lock
Labels: Jira Synced

#14811 chore: removing old chat code and cleaning up complexity
  src/Apps/Article/Components/__tests__/ArticleSeries.jest.tsx
  src/Apps/Article/Components/__tests__/ArticleVideo.jest.tsx
  src/Apps/Articles/Components/__tests__/ArticlesIndexArticles.jest.tsx
  src/Apps/Artist/Components/ArtistInsights/__tests__/ArtistInsightBadges.jest.tsx
  src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistRelatedGeneCategories.jest.tsx
  src/Apps/Artwork/Components/ArtworkChatBubble.tsx
  src/Apps/Auction/__tests__/AuctionApp.jest.enzyme.tsx
  src/Apps/Order/OrderApp.tsx
  src/Apps/Order/__tests__/OrderApp.jest.enzyme.tsx
  src/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileAboutYou.jest.tsx
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/SmsSecondFactor/__tests__/SmsSecondFactor.jest.tsx
  src/Components/Onboarding/Components/__tests__/OnboardingOrderedSet.jest.tsx
  src/Components/Onboarding/Components/__tests__/OnboardingSearchResults.jest.tsx
  src/Components/SalesforceWrapper.tsx
  src/Server/bootstrapSharify.ts
  src/Server/config.ts
  src/Typings/global.d.ts
  src/Typings/sharify.d.ts
Labels: Jira Synced

#14979 fix: specify correct non-crossorigin mode on image host preconnect hints
  src/Server/middleware/linkHeadersMiddleware.ts
  src/html.ts
Labels: performance

#14975 refactor(collections): modify redirects to be purely server-side
  cypress/e2e/collection.cy.js
  src/Apps/Collect/Server/__tests__/redirectCollectionToArtistSeries.jest.ts
  src/Apps/Collect/Server/redirectCollectionToArtistSeries.ts
  src/Apps/Collect/collectRoutes.tsx
  src/server.ts
Labels: Jira Synced, performance

#14982 feat(review-apps): Completely automate Review App creation
  .circleci/config.yml
  scripts/create-review-app-subdomain.js
Labels: Jira Synced

#14961 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#14998 fix: Allow creating alerts with multiple artists from Artist series page
  src/Apps/ArtistSeries/Components/ArtistSeriesArtworksFilter.tsx
Labels: Jira Synced

#15000 chore: avoid duplicating main artwork image elements, especially <link rel="preload"...
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
Labels: performance

#15003 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15002 fix: suppress `metric` from filter URLs
  src/Components/ArtworkFilter/Utils/isDefaultFilter.tsx
  src/System/Utils/fetchUserPreferences.ts
  src/__generated__/fetchUserPreferencesQuery.graphql.ts
Labels: Merge On Green

#15009 feat: Automatically opt into sharing collected artists with galleries
  src/Components/CollectorProfile/CollectorProfileArtistsAdd.tsx
Labels: Jira Synced

#15011 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15016 chore(AMBER-1209): Update the class name on css to match the component
  src/Components/SalesforceWrapper.tsx
Labels: Jira Synced

#15027 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15008 chore(perf): prefer preloading 2x quality images
  src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
  src/Apps/Artwork/Components/ArtworkLightbox.tsx
  src/Apps/Fair/Components/FairHeader/FairHeaderImage.tsx
  src/Utils/resized.ts
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkImageBrowserLarge_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowserSmall_Test_Query.graphql.ts
  src/__generated__/ArtworkLightboxTestQuery.graphql.ts
  src/__generated__/ArtworkLightbox_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: performance

#15030 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15032 fix(linter): Migrate exhaustive-deps ignore
  biome.json
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilterMobileActionSheet.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/KeywordFilter.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkErrorApp/ArtworkErrorApp.tsx
  src/Apps/Artwork/Components/ArtworkVideoPlayer/ArtworkVideoPlayer.tsx
  src/Apps/Auction/AuctionApp.tsx
  src/Apps/Auction/Routes/AuctionConfirmRegistrationRoute.tsx
  src/Apps/Auction/Routes/AuctionRegistrationRoute.tsx
  src/Apps/Auction/Routes/Bid/Components/PricingTransparency.tsx
  src/Apps/CollectorProfile/Routes/Saves/CollectorProfileSavesRoute.tsx
  src/Apps/Components/AppShell.tsx
  src/Apps/Conversations/components/ConversationReply.tsx
  src/Apps/Conversations/components/Sidebar/ConversationsSidebar.tsx
  src/Apps/Conversations/components/Sidebar/ConversationsSidebarItem.tsx
  src/Apps/Conversations/hooks/useLoadMore.ts
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormImages.tsx
  src/Apps/Order/Components/AddressVerificationFlow.tsx
  src/Apps/Order/Components/OrderStepper.tsx
  src/Apps/Order/Components/PriceOptions.tsx
  src/Apps/Order/Hooks/useStripePaymentBySetupIntentId.tsx
  src/Apps/Order/OrderApp.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Shipping/Components/AddressModal.tsx
  src/Apps/Order/Routes/Shipping/Components/FulfillmentDetails.tsx
  src/Apps/Order/Routes/Shipping/Components/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping/Components/SavedAddresses.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Utils/scrollToFieldError.tsx
  src/Apps/Page/PageApp.tsx
  src/Apps/Partner/Routes/Artists/ArtistsRoute.tsx
  src/Apps/PartnerOffer/Routes/PartnerOfferCheckout.tsx
  src/Apps/Sell/Components/ArtistAutocomplete.tsx
  src/Apps/Sell/Components/SubmissionHeader.tsx
  src/Apps/Sell/SellFlowContext.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Components/Address/AddressAutocompleteInput.tsx
  src/Components/Address/AddressForm.tsx
  src/Components/Artwork/useArtworkLists.ts
  src/Components/ArtworkFilter/ArtworkFilterMobileOverlay.tsx
  src/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/KeywordFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/AvailabilityFilter.jest.tsx
  src/Components/BankDebitForm/BankDebitProvider.tsx
  src/Components/DeepZoom/DeepZoom.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/Onboarding/Hooks/useOnboardingFadeTransition.tsx
  src/Components/PhotoUpload/Components/PhotoDropzone.tsx
  src/Components/Search/Mobile/Overlay.tsx
  src/Components/Search/Mobile/SearchResultsList.tsx
  src/DevTools/MockRouter.tsx
  src/System/Hooks/usePrefetchRoute.tsx
  src/Utils/Hooks/useClientQuery.ts
  src/Utils/Hooks/useDebounce.ts
  src/Utils/localImageHelpers.ts
Labels: Merge On Green

#15042 fix(dev): Simplify up logic
  src/dev.ts
Labels: Merge On Green

#15043 fix: Formatting perf
  .vscode/settings.json
Labels: Merge On Green
