Repository artsy/force, pull requests merged in 2024-04, with the labels that each got.

#13653 Deploy
  data/schema.graphql
  package.json
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListsHeader.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/OfferSettingsModal/OfferSettingsListItem.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/OfferSettingsModal/__tests__/OfferSettingsListItem.jest.tsx
  src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveOfferSettings.tsx
  yarn.lock
Labels: Jira Synced

#13667 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13668 feat: move availability filter to correct position
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
Labels: Squash On Green

#13655 Adds terms update dialog
  src/Components/TermsUpdateDialog.tsx
  src/System/Router/Boot.tsx
  src/tests.ts
Labels: Jira Synced

#13663 Deploy
  data/schema.graphql
  package.json
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/Components/AuthDialog/Components/AuthDialogSignUpPlaceholder.tsx
  src/Components/AuthDialog/Views/AuthDialogSignUp.tsx
  src/Components/AuthDialog/Views/__tests__/AuthDialogSignUp.jest.tsx
  src/Components/Inquiry/Views/InquirySignUp.tsx
  src/Components/Inquiry/__tests__/Views/InquirySignUp.jest.tsx
  src/Components/PhoneNumberInput/PhoneNumberInput.tsx
  src/Components/TermsUpdateDialog.tsx
  src/System/Router/Boot.tsx
  src/Typings/sharify.d.ts
  src/tests.ts
  yarn.lock
Labels: Jira Synced

#13672 Chore: changing navbar copy
  src/Components/NavBar/menuData.ts
Labels: Jira Synced

#13669 feat(MyC, SwA): present disambiguating info when selecting an artist
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx
  src/__generated__/ArtistAutocomplete_SearchConnection_Query.graphql.ts
Labels: Jira Synced

#13670 feat(EMI-1747): view artwork from notification panel for partner offers
  src/Components/Notifications/PartnerOfferArtwork.tsx
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_notification.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_test_Query.graphql.ts
Labels: Jira Synced

#13684 feat(collectorprofile): implements add artist to collection
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsAddDialog.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsAddResult.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
  src/Apps/CollectorProfile/Routes/Artists/CollectorProfileArtistsRoute.tsx
  src/Apps/CollectorProfile/Routes/Artists/__tests__/CollectorProfileArtistsRoute.jest.tsx
  src/__generated__/CollectorProfileArtistsAddDialogCreateUserInterestsMutation.graphql.ts
  src/__generated__/CollectorProfileArtistsAddDialogQuery.graphql.ts
  src/__generated__/CollectorProfileArtistsAddResult_artist.graphql.ts
  src/__generated__/CollectorProfileArtistsListArtistsQuery.graphql.ts
Labels: Jira Synced

#13675 Deploy
  .circleci/config.yml
  cypress.config.ts
  package.json
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercialButtons.jest.tsx
  src/Apps/Auction/Components/Form/ConditionsOfSaleCheckbox.tsx
  src/Apps/Auction/Components/Form/__tests__/ConditionsOfSaleCheckbox.jest.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsAddDialog.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsAddResult.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
  src/Apps/CollectorProfile/Routes/Artists/CollectorProfileArtistsRoute.tsx
  src/Apps/CollectorProfile/Routes/Artists/__tests__/CollectorProfileArtistsRoute.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
  src/Apps/Order/Components/ConditionsOfSaleDisclaimer.tsx
  src/Apps/Order/Routes/__tests__/Accept.jest.tsx
  src/Apps/Order/Routes/__tests__/Counter.jest.tsx
  src/Apps/Order/Routes/__tests__/Reject.jest.tsx
  src/Apps/Order/Routes/__tests__/Review.jest.tsx
  src/Components/AuthDialog/Views/__tests__/AuthDialogSignUp.jest.tsx
  src/Components/Footer/Footer.tsx
  src/Components/Footer/__tests__/Footer.jest.tsx
  src/Components/Inquiry/__tests__/Views/InquirySignUp.jest.tsx
  src/Components/NavBar/menuData.ts
  src/Components/Notifications/PartnerOfferArtwork.tsx
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx
  src/Components/TermsUpdateDialog.tsx
  src/__generated__/ArtistAutocomplete_SearchConnection_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_me.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/CollectorProfileArtistsAddDialogCreateUserInterestsMutation.graphql.ts
  src/__generated__/CollectorProfileArtistsAddDialogQuery.graphql.ts
  src/__generated__/CollectorProfileArtistsAddResult_artist.graphql.ts
  src/__generated__/CollectorProfileArtistsListArtistsQuery.graphql.ts
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_notification.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#13689 chore(AMBER-536) - Renders Condition, Provenance, and Exhibition History sections on private artwork listing
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkMetadata.tsx
  src/Apps/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkMetadata.jest.tsx
  src/__generated__/PrivateArtworkMetadataQuery.graphql.ts
  src/__generated__/PrivateArtworkMetadata_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13683 chore: AMBER-548 - adding exclusive access text to artwork
  src/Apps/Conversations/components/Details/ConversationArtwork.tsx
  src/Apps/Conversations/components/Sidebar/ConversationsSidebarItem.tsx
  src/__generated__/ConversationArtwork_conversation.graphql.ts
  src/__generated__/ConversationDetailsTestQuery.graphql.ts
  src/__generated__/ConversationsSidebar2PaginationQuery.graphql.ts
  src/__generated__/ConversationsSidebarItemTestQuery.graphql.ts
  src/__generated__/ConversationsSidebarItem_conversation.graphql.ts
  src/__generated__/ConversationsSidebarPaginationQuery.graphql.ts
  src/__generated__/ConversationsSidebarTestQuery.graphql.ts
  src/__generated__/conversationsRoutes_DetailQuery.graphql.ts
Labels: Jira Synced

#13690 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13691 feat(collectorprofile): implements artist private toggle
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListArtist.tsx
  src/__generated__/CollectorProfileArtistsAddDialogCreateUserInterestsMutation.graphql.ts
  src/__generated__/CollectorProfileArtistsListArtistUpdateMutation.graphql.ts
  src/__generated__/CollectorProfileArtistsListArtist_userInterestEdge.graphql.ts
  src/__generated__/CollectorProfileArtistsListArtistsQuery.graphql.ts
Labels: Jira Synced

#13688 chore(artist series filter): retire Unleash feature flag
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
  src/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilters.jest.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/ArtistSeriesFilterQuick.tsx
  src/Components/ArtworkFilter/ArtworkFiltersQuick/__tests__/ArtistSeriesFilterQuick.jest.tsx
Labels: Jira Synced

#13695 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13692 Chore/amber 522/remove rotating conversation messages
  src/Components/Inquiry/Hooks/useInquiryContext.tsx
  src/Components/Inquiry/Views/InquiryInquiry.tsx
  src/Components/Inquiry/__tests__/Views/InquirySpecialist.jest.tsx
Labels: Jira Synced

#13697 chore: update the text
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Components/__tests__/TransactionDetailsSummary.jest.tsx
Labels: Jira Synced

#13693 feat(ONYX-804): add Lots for You tab on Auction page
  src/Apps/Auctions/Components/CuritorialRailsTabBar.tsx
  src/Apps/Auctions/Components/__tests__/CuritorialRailsTabBar.jest.tsx
Labels: Jira Synced

#13703 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/NotificationQuery.graphql.ts
Labels: Squash On Green

#13706 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13711 feat: delete more onetrust references
  docs/adding_a_segment_destination.md
  src/Server/config.ts
  src/Server/setup_sharify.ts
  src/Typings/global.d.ts
  src/Typings/sharify.d.ts
Labels: Merge On Green, Jira Synced

#13717 fix: remove minHeight so that Partner Offers are fixed
  src/Components/Artwork/Details.tsx
Labels: Jira Synced

#13718 feat(terms): suppress terms dialog when within eigen
  src/Components/TermsUpdateDialog.tsx
Labels: Jira Synced

#13707 feat(dia-477): user sees artists as paginated list on web
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
  src/Apps/CollectorProfile/Routes/Artists/__tests__/CollectorProfileArtistsRoute.jest.tsx
  src/Components/Pagination/index.tsx
  src/__generated__/CollectorProfileArtistsListArtistsQuery.graphql.ts
Labels: Jira Synced

#13719 fix: Correctly initializing SWA form contact info on back press
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/formHelpers.ts
  src/__generated__/ContactInformation_SubmissionFlowTest_Query.graphql.ts
  src/__generated__/ContactInformation_submission.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
  src/__generated__/consignRoutes_contactInformationQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#13721 feat(EMI-1799): partner offer note redesign in notification panel
  src/Components/Notifications/NotificationItem.tsx
  src/Components/Notifications/PartnerOfferArtwork.tsx
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/PartnerOfferArtwork_artwork.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_test_Query.graphql.ts
Labels: Jira Synced

#13723 feat(dia-570): user can remove artist
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsDeleteDialog.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListArtist.tsx
  src/__generated__/CollectorProfileArtistsDeleteDialogMutation.graphql.ts
Labels: Jira Synced

#13702 feat(EMI-1800): update display to only have 2 active action buttons at a time
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercialButtons.jest.tsx
Labels: Jira Synced

#13722 Chore: [EMI-1804] show unavailable banner for unavailable partner offer
  src/Apps/Artwork/Components/ArtworkPageBanner.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkPageBanner.jest.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkPageBanner_Test_Query.graphql.ts
  src/__generated__/ArtworkPageBanner_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13728 feat(EMI-1782): display partner offer note in artwork listing
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercialButtons.jest.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_me.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13740 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13730 feat: reorganize CTAs on My Collection Artwork page
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkComparables.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkRequestPriceEstimateSection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtworkAboutTab.tsx
  src/Components/ArtistCurrentArticlesRail.tsx
  src/__generated__/MyCollectionArtworkInsights_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/MyCollectionArtwork_artwork.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13742 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13746 fix(terms): makes minor updates
  src/Components/TermsUpdateDialog.tsx
Labels: Jira Synced

#13713 Feat: add dedicated supplemental conditions of service page
  src/Apps/SaleAgreements/Components/SaleAgreementsFilter.tsx
  src/Apps/SaleAgreements/Components/SaleAgreementsList.tsx
  src/Apps/SaleAgreements/Components/SaleAgreementsListItem.tsx
  src/Apps/SaleAgreements/Routes/SaleAgreementRoute.tsx
  src/Apps/SaleAgreements/SaleAgreementsApp.tsx
  src/Apps/SaleAgreements/__tests__/SaleAgreementRoute.jest.tsx
  src/Apps/SaleAgreements/__tests__/SaleAgreementsApp.jest.tsx
  src/Apps/SaleAgreements/saleAgreementsRoutes.tsx
  src/__generated__/SaleAgreementRoute_Test_Query.graphql.ts
  src/__generated__/SaleAgreementRoute_saleAgreement.graphql.ts
  src/__generated__/SaleAgreementsApp_Test_Query.graphql.ts
  src/__generated__/SaleAgreementsApp_viewer.graphql.ts
  src/__generated__/SaleAgreementsFilter_viewer.graphql.ts
  src/__generated__/saleAgreementsRoutes_SaleAgreementQuery.graphql.ts
  src/__generated__/saleAgreementsRoutes_SaleAgreementsAppQuery.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#13736 refactor(private-artworks): Update private artwork page design
  src/Apps/Artwork/Components/ArtworkPageBanner.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutWork.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkDetails.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkMetadata.tsx
  src/Apps/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkAboutArtist.jest.tsx
  src/Apps/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkAboutWork.jest.tsx
  src/Apps/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkMetadata.jest.tsx
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Components/UnlistedArtworkBanner.tsx
  src/Components/__tests__/UnlistedArtworkBanner.jest.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkPageBanner_Test_Query.graphql.ts
  src/__generated__/ArtworkPageBanner_artwork.graphql.ts
  src/__generated__/PrivateArtworkAboutArtistQuery.graphql.ts
  src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
  src/__generated__/PrivateArtworkAboutWorkQuery.graphql.ts
  src/__generated__/PrivateArtworkAboutWork_artwork.graphql.ts
  src/__generated__/PrivateArtworkMetadataQuery.graphql.ts
  src/__generated__/PrivateArtworkMetadata_artwork.graphql.ts
  src/__generated__/UnlistedArtworkBanner_Test_Query.graphql.ts
  src/__generated__/UnlistedArtworkBanner_partner.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13751 feat(collector-profile): implements "search"
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListArtist.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListHeader.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsSearchResults.tsx
  src/Apps/CollectorProfile/Routes/Artists/CollectorProfileArtistsRoute.tsx
  src/__generated__/CollectorProfileArtistsSearchResultsQuery.graphql.ts
Labels: Jira Synced

#13255 feat: allow conditional editing of alert artist criteria
  src/Components/Alert/Components/CriteriaPills.tsx
Labels: Jira Synced

#13757 feat(collector-profile): adds simple empty state
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
Labels: Jira Synced

#13759 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13760 feat(ONYX-905): remove works for you on auction page
  src/Apps/Auctions/Components/CuritorialRailsTabBar.tsx
  src/Apps/Auctions/Components/__tests__/CuritorialRailsTabBar.jest.tsx
  src/__generated__/AuctionsApp_Test_Query.graphql.ts
  src/__generated__/CuritorialRailsTabBar_Test_Query.graphql.ts
  src/__generated__/CuritorialRailsTabBar_viewer.graphql.ts
  src/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
Labels: Jira Synced

#13762 chore: Fix Partner show notification test
  src/Components/Notifications/__tests__/PartnerShowOpenedNotification.jest.tsx
Labels: Squash On Green

#13761 fix(collector-profile): addresses q/a items
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListArtist.tsx
  src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListArtistDialog.tsx
  src/Apps/CollectorProfile/Routes/Artists/CollectorProfileArtistsRoute.tsx
  src/Components/EntityHeaders/EntityHeaderArtist.tsx
  src/__generated__/CollectorProfileArtistsAddDialogCreateUserInterestsMutation.graphql.ts
  src/__generated__/CollectorProfileArtistsDeleteDialogMutation.graphql.ts
  src/__generated__/CollectorProfileArtistsListArtistDialogUpdateMutation.graphql.ts
  src/__generated__/CollectorProfileArtistsListArtistDialog_userInterestEdge.graphql.ts
  src/__generated__/CollectorProfileArtistsListArtistUpdateMutation.graphql.ts
  src/__generated__/CollectorProfileArtistsListArtist_userInterestEdge.graphql.ts
  src/__generated__/CollectorProfileArtistsListArtistsQuery.graphql.ts
  src/__generated__/CollectorProfileArtistsSearchResultsQuery.graphql.ts
Labels: Jira Synced

#13769 fix: early exit from useEffect that checks for Private Artwork
  src/Components/Footer/FooterDownloadAppBanner.tsx
  src/Components/Footer/__tests__/Footer.jest.tsx
Labels: Merge On Green, Jira Synced

#13773 chore: AMBER-591 - adding tracking for private artwork page
  cypress/e2e/terms.cy.js
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtsyGuarantee.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPrivateArtwork.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarShippingInformation.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutWork.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkMetadata.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebarPartnerInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarPartnerInfo_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13774 fix: Suppress duplicate edition set info on private artwork pages AMBER-629
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
Labels: Squash On Green

#13776 fix(AMBER-625): Move About the Artist section on mobile web and adjust margins and font size
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkDetails.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkMetadata.tsx
Labels: Merge On Green, Jira Synced

#13777 Deploy
  cypress/e2e/terms.cy.js
  package.json
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtsyGuarantee.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPrivateArtwork.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarShippingInformation.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutWork.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkDetails.tsx
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkMetadata.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebarPartnerInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarPartnerInfo_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#13780 chore: AMBER-628- only rendering profile hyperlink if one exists
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPrivateArtwork.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebarPrivateArtworkQuery.graphql.ts
  src/__generated__/ArtworkSidebarPrivateArtwork_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13782 fix(AMBER-342): show submitted order modal for private artworks
  src/Apps/Artwork/ArtworkApp.tsx
Labels: Jira Synced

#13781 Deploy
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPrivateArtwork.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebarPrivateArtworkQuery.graphql.ts
  src/__generated__/ArtworkSidebarPrivateArtwork_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13785 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtworkSidebarCommercialButtonsOfferOrderMutation.graphql.ts
  src/__generated__/AuthIntentCreateOfferOrderMutation.graphql.ts
Labels: Squash On Green

#13788 chore: AMBER-637 - NoIndex Artwork ID URL
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkMeta.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkMeta.jest.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkMeta_Test_Query.graphql.ts
  src/__generated__/ArtworkMeta_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13796 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13799 fix(private-artworks): Ensure private artist bio is html
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/PrivateArtworkAboutArtistQuery.graphql.ts
  src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Merge On Green

#13802 chore: Wire in displayArtistBio flag on when to display artist bio
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/PrivateArtworkAboutArtistQuery.graphql.ts
  src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13784 feat: Reorganize sell page mWeb
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpeakToTheTeam.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SWAFooter.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SpeakToTheTeam.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
  src/Apps/Consign/Routes/MarketingLanding/Utils/marketingLandingTracking.ts
  src/Apps/Consign/consignFromCollectorProfileMyCollectionRoutes.tsx
  src/Apps/Consign/consignFromMyCollectionRoutes.tsx
  src/Apps/Consign/consignRoutes.tsx
Labels: Jira Synced

#13803 fix(artwork): only show partner bio if enabled
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
  src/Apps/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkAboutArtist.jest.tsx
Labels: Squash On Green

#13807 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13805 chore: remove old secialists and reorder the list
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/MeetTheSpecialists.jest.tsx
Labels: Jira Synced, Squash On Green

#13813 Deploy
  src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
Labels: Merge On Green

#13814 chore(ONYX-936): remove filters from the list of specialist on the sell page
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
Labels: Jira Synced

#13816 feat(admin): Add admin/navigate-to-route route
  src/Apps/Admin/NavigateToRoute.tsx
  src/Apps/Admin/adminRoutes.tsx
Labels: Merge On Green

#13818 chore: Adds visibility level to artwork pageview track events
  src/Apps/Artwork/ArtworkApp.tsx
Labels: Jira Synced

#13819 feat(EMI-1841): hide partner offer details if not available anymore
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercialButtons.jest.tsx
Labels: Jira Synced

#13821 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13811 feat(EMI-1849): support a counter to partner offer
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Order/Components/PriceOptions.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Utils/__tests__/offerUtils.jest.ts
  src/Apps/Order/Utils/offerUtils.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/PriceOptions_Test_Query.graphql.ts
  src/__generated__/PriceOptions_order.graphql.ts
  src/__generated__/orderRoutes_OfferQuery.graphql.ts
Labels: Jira Synced

#13826 fix(alerts): makes ui usable on all screens
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormPlaceholder.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertsArtworks.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
Labels: Jira Synced

#13828 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13823 fix: EMI-1806 partner offer timer re-mounts over and over
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
Labels: Jira Synced
