Repository artsy/force, pull requests merged in 2024-05, with the labels that each got.

#13822 Deploy
  data/schema.graphql
  package.json
  patches/found+0.5.5.patch
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/artworkRoutes.tsx
  src/Apps/Artwork/useRecordArtworkView.ts
  src/Apps/IdentityVerification/__tests__/routes.jest.tsx
  src/Apps/Order/Components/PriceOptions.tsx
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Accept.jest.tsx
  src/Apps/Order/Routes/__tests__/NewPayment.jest.tsx
  src/Apps/Order/Utils/__tests__/offerUtils.jest.ts
  src/Apps/Order/Utils/offerUtils.ts
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormPlaceholder.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertsArtworks.tsx
  src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
  src/Apps/Shows/showsRoutes.tsx
  src/DevTools/MockRouter.tsx
  src/System/Router/RenderStatus.tsx
  src/System/Router/Route.tsx
  src/System/Router/RouterLink.tsx
  src/System/Router/Utils/__tests__/findCurrentRoute.jest.ts
  src/System/Router/Utils/findRoutesByPath.ts
  src/System/Router/__tests__/RouterLink.jest.tsx
  src/System/Router/buildAppRoutes.tsx
  src/System/Router/buildClientApp.tsx
  src/System/Router/buildServerApp.tsx
  src/System/Router/getRouteConfig.ts
  src/System/Router/index.ts
  src/System/Router/interceptLinks.ts
  src/System/Router/useRouter.tsx
  src/Typings/found.d.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/PriceOptions_Test_Query.graphql.ts
  src/__generated__/PriceOptions_order.graphql.ts
  src/__generated__/orderRoutes_OfferQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#13835 feat: add backend support for LLM demos
  .env.oss
  package.json
  src/Apps/ArtAdvisor/01-Spike/server.ts
  src/Apps/ArtAdvisor/02-Markdown/App.tsx
  src/Apps/ArtAdvisor/02-Markdown/server.ts
  src/Apps/ArtAdvisor/03-Instruction-Experiments/00-prompt-lib/collector-profile-one.ts
  src/Apps/ArtAdvisor/03-Instruction-Experiments/00-prompt-lib/collector-profile-two.ts
  src/Apps/ArtAdvisor/03-Instruction-Experiments/App.tsx
  src/Apps/ArtAdvisor/03-Instruction-Experiments/server.ts
  src/Apps/ArtAdvisor/ArtAdvisorApp.tsx
  src/Apps/ArtAdvisor/ArtAdvisorRoutes.tsx
  src/Apps/ArtAdvisor/ArtAdvisorServerRoutes.ts
  src/server.ts
  yarn.lock
Labels: Squash On Green

#13842 chore: disable social login
  src/Components/AuthDialog/Components/AuthDialogSocial.tsx
Labels: Jira Synced

#13848 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13827 feat: pull secrets from vault
  hokusai/production.yml
  hokusai/staging.yml
Labels: Jira Synced

#13849 feat(onyx-913): use new consignmentSubmission MP fields when rendering submission state section
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASectionSubmitted.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/__tests__/MyCollectionArtwork.jest.tsx
  src/__generated__/MyCollectionArtworkSWASectionSubmitted_submissionState.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/MyCollectionArtwork_artwork.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13855 chore: bump detect-secrets baseline version
  .secrets.baseline
Labels: Jira Synced

#13825 feat(ONYX-906): update required fields on sell flow
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Mutations/UpdateConsignSubmissionMutation.ts
  src/Apps/Consign/Routes/SubmissionFlow/Utils/createOrUpdateConsignSubmission.ts
  src/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
Labels: Jira Synced

#13858 fix(ONYX-946): add MyBids on Auctions page
  src/Apps/Auctions/AuctionsApp.tsx
  src/Apps/Auctions/Components/MyBids/MyBids.tsx
Labels: Jira Synced, Squash On Green

#13847 chore: require authentication for submission
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HeaderSWA.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HowItWorksSteps.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SWAFooter.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
Labels: Jira Synced

#13853 Deploy
  .secrets.baseline
  data/schema.graphql
  package.json
  src/Apps/Auctions/AuctionsApp.tsx
  src/Apps/Auctions/Components/MyBids/MyBids.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HeaderSWA.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HowItWorksSteps.jest.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SWAFooter.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Mutations/UpdateConsignSubmissionMutation.ts
  src/Apps/Consign/Routes/SubmissionFlow/Utils/createOrUpdateConsignSubmission.ts
  src/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
  src/Apps/Home/Components/HomeFeaturedMarketNews.tsx
  src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping2/Components/__tests__/FulfillmentDetailsForm.jest.tsx
  src/Apps/Order/Utils/__tests__/scrollToFormikErrors.jest.tsx
  src/Apps/Order/Utils/scrollToFieldError.tsx
  src/Apps/SaleAgreements/Components/SaleAgreementsList.tsx
  src/Apps/ViewingRoom/Components/ViewingRoomsFeaturedRail.tsx
  src/Apps/ViewingRoom/__tests__/ViewingRoomsApp.jest.tsx
  src/Components/Cells/CellShow.tsx
  src/Utils/Hooks/useStableShuffle.ts
  yarn.lock
Labels: Jira Synced

#13861 Chore: change featured artists in navbar
  src/Components/NavBar/menuData.ts
Labels: Jira Synced

#13864 fix: fix url for duplicate artist
  src/Components/NavBar/menuData.ts
Labels: Merge On Green

#13867 chore: regenerate .secrets.baseline
  .secrets.baseline
  package.json
  scripts/detect-secrets.sh
Labels: Jira Synced

#13873 fix (Amber-583): "View More" button no longer renders on partner shows if there is no href
  src/Apps/Partner/Components/PartnerShows/ShowBanner.tsx
  src/Apps/Partner/Components/__tests__/PartnerShows/ShowBanner.jest.tsx
Labels: Merge On Green, Jira Synced

#13874 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13875 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13836 chore: cleanup sell routes
  src/Apps/Consign/consignFromCollectorProfileMyCollectionRoutes.tsx
  src/Apps/Consign/consignFromMyCollectionRoutes.tsx
  src/Apps/Consign/consignRoutes.tsx
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_contactInformationMeQuery.graphql.ts
  src/__generated__/consignFromCollectorProfileMyCollectionRoutes_uploadArtworkPhotosQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignFromMyCollectionRoutes_myCollectionArtworkQuery.graphql.ts
  src/__generated__/consignRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
  src/__generated__/consignRoutes_contactInformationMeQuery.graphql.ts
  src/__generated__/consignRoutes_myCollectionArtworkQuery.graphql.ts
  src/__generated__/consignRoutes_uploadArtworkPhotosQuery.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#13876 feat: update Institutions page title
  cypress/e2e/institutions.cy.ts
  src/Apps/Partners/Routes/InstitutionsRoute.tsx
Labels: Squash On Green

#13878 fix: update auth modal copy on SWA flow
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAFooter.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx
Labels: Jira Synced, Squash On Green

#13871 feat: add 04-Bio-Follows-Alerts app
  .secrets.baseline
  .vscode/settings.json
  src/Apps/ArtAdvisor/04-Bio-Follows-Alerts/App.tsx
  src/Apps/ArtAdvisor/04-Bio-Follows-Alerts/lib/functions.ts
  src/Apps/ArtAdvisor/04-Bio-Follows-Alerts/lib/metaphysics.ts
  src/Apps/ArtAdvisor/04-Bio-Follows-Alerts/lib/system-instructions.ts
  src/Apps/ArtAdvisor/04-Bio-Follows-Alerts/server.ts
  src/Apps/ArtAdvisor/ArtAdvisorApp.tsx
  src/Apps/ArtAdvisor/ArtAdvisorRoutes.tsx
  src/Apps/ArtAdvisor/ArtAdvisorServerRoutes.ts
Labels: Merge On Green

#13880 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/UsePartnerOfferCheckoutMutation.graphql.ts
Labels: Squash On Green

#13862 fix(EMI-1791): Fix unsaving artwork in multiple lists bug
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/SelectArtworkListsModal/__tests__/SelectArtworkListsModal.jest.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/SelectArtworkListsModal/useSelectArtworkLists.ts
  src/Components/Artwork/SaveButton/SaveArtworkToListsButton.tsx
  src/Components/Artwork/SaveButton/useSaveArtwork.ts
  src/Components/Artwork/SaveButton/useSaveArtworkToLists.ts
Labels: Jira Synced

#13879 chore: cleanup spelling, syntax and typos
  src/Apps/ArtAdvisor/02-Markdown/App.tsx
  src/Apps/ArtAdvisor/03-Instruction-Experiments/00-prompt-lib/collector-profile-one.ts
  src/Apps/ArtAdvisor/03-Instruction-Experiments/00-prompt-lib/collector-profile-two.ts
  src/Apps/ArtAdvisor/03-Instruction-Experiments/App.tsx
  src/Apps/ArtAdvisor/03-Instruction-Experiments/server.ts
  src/Apps/ArtAdvisor/04-Bio-Follows-Alerts/lib/system-instructions.ts
  src/Apps/ArtAdvisor/04-Bio-Follows-Alerts/server.ts
  src/Apps/ArtAdvisor/ArtAdvisorRoutes.tsx
  src/Apps/ArtAdvisor/ArtAdvisorServerRoutes.ts
Labels: Merge On Green

#13872 Feat: EMI-1866 Use partner offer in conversation purchase button
  src/Apps/Conversations/ConversationApp.tsx
  src/Apps/Conversations/ConversationsContext.tsx
  src/Apps/Conversations/components/ConversationCTA/ConversationCTA.tsx
  src/Apps/Conversations/components/ConversationCTA/ConversationConfirmModal.tsx
  src/Apps/Conversations/components/ConversationCTA/ConversationPurchaseButton.tsx
  src/Apps/Conversations/components/ConversationCTA/__tests__/ConversationCTA.jest.tsx
  src/Apps/Conversations/components/ConversationCTA/__tests__/ConversationPurchaseButton.jest.tsx
  src/Apps/Conversations/components/ConversationCTA/useConversationPurchaseButtonData.tsx
  src/Apps/Conversations/components/__tests__/ConversationReply.jest.tsx
  src/__generated__/ConversationApp_viewer.graphql.ts
  src/__generated__/ConversationCTA_Test_Query.graphql.ts
  src/__generated__/ConversationCTA_conversation.graphql.ts
  src/__generated__/ConversationReplyTestQuery.graphql.ts
  src/__generated__/ConversationsContext_viewer.graphql.ts
  src/__generated__/conversationsRoutes_DetailQuery.graphql.ts
Labels: Jira Synced, Do not merge

#13881 fix: add save ability to home works tab bar
  package.json
  src/Apps/Home/Components/HomeNewWorksForYouRail.tsx
  src/Apps/Home/Components/HomeRecentlyViewedRail.tsx
  src/Apps/Home/Components/HomeWorksByArtistsYouFollowRail.tsx
  yarn.lock
Labels: Jira Synced, Squash On Green

#13883 feat(EMI-1874): partner offer notification from abandoned order
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_notification.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_test_Query.graphql.ts
Labels: Jira Synced, Squash On Green

#13882 Deploy
  package.json
  src/Apps/Conversations/ConversationApp.tsx
  src/Apps/Conversations/ConversationsContext.tsx
  src/Apps/Conversations/components/ConversationCTA/ConversationCTA.tsx
  src/Apps/Conversations/components/ConversationCTA/ConversationConfirmModal.tsx
  src/Apps/Conversations/components/ConversationCTA/ConversationPurchaseButton.tsx
  src/Apps/Conversations/components/ConversationCTA/__tests__/ConversationCTA.jest.tsx
  src/Apps/Conversations/components/ConversationCTA/__tests__/ConversationPurchaseButton.jest.tsx
  src/Apps/Conversations/components/ConversationCTA/useConversationPurchaseButtonData.tsx
  src/Apps/Conversations/components/__tests__/ConversationReply.jest.tsx
  src/Apps/Home/Components/HomeNewWorksForYouRail.tsx
  src/Apps/Home/Components/HomeRecentlyViewedRail.tsx
  src/Apps/Home/Components/HomeWorksByArtistsYouFollowRail.tsx
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx
  src/__generated__/ConversationApp_viewer.graphql.ts
  src/__generated__/ConversationCTA_Test_Query.graphql.ts
  src/__generated__/ConversationCTA_conversation.graphql.ts
  src/__generated__/ConversationReplyTestQuery.graphql.ts
  src/__generated__/ConversationsContext_viewer.graphql.ts
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_notification.graphql.ts
  src/__generated__/PartnerOfferCreatedNotification_test_Query.graphql.ts
  src/__generated__/conversationsRoutes_DetailQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#13892 chore: AMBER-687 - private artwork multiple artists
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/PrivateArtworkAboutArtistQuery.graphql.ts
  src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#13894 fix(fair): fixes scroll to on load from trapping
  src/Apps/Fair/Routes/FairOverview.tsx
Labels: Jira Synced

#13895 fix(ONYX-969): add save artwork button to rails
  src/Apps/Home/Components/HomeAuctionLotsForYouRail.tsx
  src/Apps/Home/Components/HomeAuctionLotsRail.tsx
Labels: Jira Synced

#13893 Deploy
  src/Apps/Fair/Routes/FairOverview.tsx
  src/Apps/Home/Components/HomeAuctionLotsForYouRail.tsx
  src/Apps/Home/Components/HomeAuctionLotsRail.tsx
  src/Apps/Order/Components/OfferInput.tsx
  src/Apps/Settings/Routes/MyCollection/Components/MyCollectionArtworkGrid.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/__generated__/MyCollectionArtworkGrid_artworks.graphql.ts
  src/__generated__/MyCollectionRouteQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionRouteQuery.graphql.ts
Labels: Jira Synced

#13898 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13903 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13905 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13909 fix: fixes alerts redirects
  src/Server/middleware/hardcodedRedirects.ts
Labels: Merge On Green

#13901 fix(AMBER-696): Artwork dimensions in additional details dont change when different edition is selected
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetailsAdditionalInfo.jest.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarEditionSets.tsx
  src/Apps/Artwork/Components/SelectedEditionSetContext.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_artwork.graphql.ts
  src/__generated__/ArtworkSidebarEditionSets_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13908 fix(DIA-648): unifies breakpoints across Force
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/DevTools/MockBoot.tsx
  src/DevTools/__tests__/renderUntil.jest.tsx
  src/System/Router/Boot.tsx
  src/Utils/Responsive/DeprecatedResponsive.tsx
  src/Utils/Responsive/index.tsx
Labels: Jira Synced

#13904 Deploy
  .circleci/config.yml
  data/schema.graphql
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetailsAdditionalInfo.jest.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarEditionSets.tsx
  src/Apps/Artwork/Components/SelectedEditionSetContext.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/DevTools/MockBoot.tsx
  src/DevTools/__tests__/renderUntil.jest.tsx
  src/Server/middleware/hardcodedRedirects.ts
  src/System/Router/Boot.tsx
  src/Utils/Responsive/DeprecatedResponsive.tsx
  src/Utils/Responsive/index.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercialButtons_artwork.graphql.ts
  src/__generated__/ArtworkSidebarEditionSets_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#13910 fix: Edit profile settings location input arbitrary string support
  src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
  src/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileFields.jest.tsx
Labels: Jira Synced

#13913 fix(private-artworks): fix link hover
  src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
Labels: Jira Synced

#13914 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13916 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13917 Revert "fix(DIA-648): unifies breakpoints across Force"
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/DevTools/MockBoot.tsx
  src/DevTools/__tests__/renderUntil.jest.tsx
  src/System/Router/Boot.tsx
  src/Utils/Responsive/DeprecatedResponsive.tsx
  src/Utils/Responsive/index.tsx
Labels: Jira Synced

#13915 Deploy
  data/schema.graphql
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/DevTools/MockBoot.tsx
  src/DevTools/__tests__/renderUntil.jest.tsx
  src/System/Router/Boot.tsx
  src/Utils/Responsive/DeprecatedResponsive.tsx
  src/Utils/Responsive/index.tsx
Labels: Jira Synced

#13918 fix(DIA-648): unifies breakpoints across Force
  src/Apps/Artwork/Components/ArtworkErrorApp/ArtworkErrorAppOtherWorks.tsx
  src/Apps/Artwork/Components/ArtworkErrorApp/ArtworkErrorAppRelatedWorks.tsx
  src/Apps/Artwork/Components/OtherWorks/index.tsx
  src/Apps/Artwork/Components/RelatedWorks/index.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListArtworksGrid.tsx
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Settings/Routes/MyCollection/Components/MyCollectionArtworkGrid.tsx
  src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/Components/ArtworkFilter/index.tsx
  src/DevTools/MockBoot.tsx
  src/DevTools/__tests__/renderUntil.jest.tsx
  src/System/Router/Boot.tsx
  src/Utils/Responsive/DeprecatedResponsive.tsx
  src/Utils/Responsive/index.tsx
Labels: Jira Synced

#13902 fix(AMBER-678): Shows display on partner profile overview page but not in Events tab
  src/Apps/Partner/Routes/Shows/index.tsx
Labels: Jira Synced

#13920 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13885 tam-kis(ONYX-902): remove contact information step
  src/Apps/Consign/Hooks/useSubmissionFlowSteps.ts
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/formHelpers.ts
  src/Apps/Consign/Routes/SubmissionFlow/Utils/redirects.ts
  src/Apps/Consign/consignRoutes.tsx
  src/Apps/MyCollection/ContactInformation/ContactInformationForm.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
  src/__generated__/ArtworkDetails_me.graphql.ts
  src/__generated__/ContactInformation_SubmissionFlowTest_Query.graphql.ts
  src/__generated__/ContactInformation_submission.graphql.ts
  src/__generated__/consignRoutes_artworkDetailsQuery.graphql.ts
  src/__generated__/consignRoutes_artworkEditDetailsQuery.graphql.ts
  src/__generated__/consignRoutes_contactInformationMeQuery.graphql.ts
Labels: Jira Synced

#13919 Deploy
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkErrorApp/ArtworkErrorAppOtherWorks.tsx
  src/Apps/Artwork/Components/ArtworkErrorApp/ArtworkErrorAppRelatedWorks.tsx
  src/Apps/Artwork/Components/OtherWorks/index.tsx
  src/Apps/Artwork/Components/RelatedWorks/index.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListArtworksGrid.tsx
  src/Apps/Consign/Hooks/useSubmissionFlowSteps.ts
  src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
  src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
  src/Apps/Consign/Routes/SubmissionFlow/Utils/formHelpers.ts
  src/Apps/Consign/Routes/SubmissionFlow/Utils/redirects.ts
  src/Apps/Consign/consignRoutes.tsx
  src/Apps/MyCollection/ContactInformation/ContactInformationForm.tsx
  src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
  src/Apps/Partner/Routes/Shows/index.tsx
  src/Apps/Settings/Routes/MyCollection/Components/MyCollectionArtworkGrid.tsx
  src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
  src/Components/ArtworkFilter/index.tsx
  src/DevTools/MockBoot.tsx
  src/DevTools/__tests__/renderUntil.jest.tsx
  src/System/Router/Boot.tsx
  src/Utils/Responsive/DeprecatedResponsive.tsx
  src/Utils/Responsive/index.tsx
  src/__generated__/ArtworkDetails_me.graphql.ts
  src/__generated__/ContactInformation_SubmissionFlowTest_Query.graphql.ts
  src/__generated__/ContactInformation_submission.graphql.ts
  src/__generated__/consignRoutes_artworkDetailsQuery.graphql.ts
  src/__generated__/consignRoutes_artworkEditDetailsQuery.graphql.ts
  src/__generated__/consignRoutes_contactInformationMeQuery.graphql.ts
Labels: Jira Synced

#13922 fix(ONYX-902): update routes for submission flow
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/Apps/Consign/consignRoutes.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtworkAboutTab.tsx
Labels: Jira Synced

#13924 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13923 Deploy
  data/schema.graphql
  src/Apps/Auction/Components/AuctionDetails/AddToCalendar.tsx
  src/Apps/Auction/Components/AuctionDetails/AuctionDetails.tsx
  src/Apps/Auction/Components/AuctionDetails/AuctionDetailsStartTime.tsx
  src/Apps/Auction/Components/AuctionDetails/AuctionInfoSidebar.tsx
  src/Apps/Auction/Components/AuctionDetails/SaleDetailTimer.tsx
  src/Apps/Auction/Components/AuctionDetails/__tests__/AuctionInfoSidebar.jest.tsx
  src/Apps/Auction/Components/AuctionDetails/helpers.ts
  src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
  src/Apps/Consign/consignRoutes.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtworkAboutTab.tsx
Labels: Jira Synced

#13928 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#13930 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useCreateArtworkMutation.graphql.ts
  src/__generated__/useUpdateArtworkMutation.graphql.ts
Labels: Squash On Green

#13900 feat: My Collection form location autocomplete
  .secrets.baseline
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
  src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionEditArtwork.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkFormHelpers.ts
  src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkModel.ts
  src/Apps/MyCollection/Routes/EditArtwork/Utils/useCreateOrUpdateArtwork.ts
  src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MyCollectionArtworkSidebar.jest.tsx
  src/Components/LocationAutocompleteInput.tsx
  src/Components/__tests__/LocationAutocompleteInput.jest.tsx
  src/__generated__/MyCollectionArtworkSidebarMetadata_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkSidebarTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/MyCollectionEditArtworkTest_Query.graphql.ts
  src/__generated__/MyCollectionEditArtwork_artwork.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionArtworkFormQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_MyCollectionArtworkFormQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#13942 feat: pull secrets from vault
  hokusai/production.yml
  hokusai/staging.yml
Labels: Jira Synced
