Repository artsy/force, pull requests merged in 2025-08, with the labels that each got.

#15932 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15934 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15937 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15948 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15942 Deploy
  .circleci/config.yml
  data/schema.graphql
  package.json
  src/Apps/Articles/AuthorApp.tsx
  src/Apps/Articles/Components/AuthorArticlesGrid.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artists/Components/ArtistsByLetterMeta.tsx
  src/Apps/Artists/Components/__tests__/ArtistsByLetterMeta.jest.tsx
  src/Apps/Artists/Routes/ArtistsByLetter.tsx
  src/Apps/Artists/__tests__/ArtistsByLetter.jest.tsx
  src/Apps/Order/Routes/Details/Components/OrderDetailsPage.tsx
  src/Apps/Order/Routes/Details/Components/__tests__/OrderDetailsPage.jest.tsx
  src/Apps/Order2/Hooks/useOrder2Tracking.tsx
  src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/__tests__/Order2PaymentForm.jest.tsx
  src/Apps/Press/PressApp.tsx
  src/Apps/Shows/Routes/ShowsCity.tsx
  src/Apps/Shows/Routes/__tests__/ShowsCity.jest.tsx
  src/Components/AuthDialog/AuthDialogTitle.tsx
  src/Components/MetaTags.tsx
  src/Components/PaginatedMetaTags.tsx
  src/Components/__tests__/PaginatedMetaTags.jest.tsx
  src/Utils/__tests__/filterParams.jest.ts
  src/Utils/filterParams.ts
  src/__generated__/AuthorApp_author.graphql.ts
  src/__generated__/AuthorArticlesGridPaginationQuery.graphql.ts
  src/__generated__/AuthorArticlesGridQuery.graphql.ts
  src/__generated__/AuthorArticlesGrid_query.graphql.ts
  src/__generated__/Order2PaymentFormConfirmationTokenQuery.graphql.ts
  src/__generated__/OrderDetailsPage_Test_Query.graphql.ts
  src/__generated__/OrderDetailsPage_order.graphql.ts
  src/__generated__/articlesRoutes_AuthorQuery.graphql.ts
  src/__generated__/orderRoutes_DetailsQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#15956 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15973 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15981 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15988 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15993 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15994 chore: Use Message component with title for info box in Settings → Edit Profile
  src/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
Labels: Jira Synced

#15996 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15997 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15980 feat(EMI-2680): buyer can save and use saved ACH bank account to checkout
  data/schema.graphql
  src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
  src/Apps/Order2/Routes/Checkout/CheckoutContext/__tests__/Order2CheckoutContext.jest.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/__tests__/Order2PaymentForm.jest.tsx
  src/Apps/Order2/Routes/Checkout/Hooks/useStripePaymentBySetupIntentId.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/Apps/Order2/Utils/confirmationTokenUtils.ts
  src/__generated__/Order2CheckoutApp_order.graphql.ts
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2PaymentFormTestQuery.graphql.ts
  src/__generated__/Order2PaymentForm_me.graphql.ts
  src/__generated__/confirmationTokenUtilsQuery.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/useOrder2SetOrderDeliveryAddressMutation.graphql.ts
  src/__generated__/useOrder2SetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useOrder2SetOrderPaymentMutation.graphql.ts
  src/__generated__/useOrder2SetOrderPickupDetailsMutation.graphql.ts
Labels: Jira Synced

#16000 feat: alter fair experience for The Artsy Edition Shop
  src/Apps/Fair/Components/FairHeader/FairHeader.tsx
  src/Apps/Fair/Components/FairOverview/FairAbout.tsx
  src/Apps/Fair/Components/__tests__/FairHeader.jest.tsx
  src/Apps/Fair/Routes/__tests__/FairOverview.jest.tsx
  src/__generated__/FairAbout_fair.graphql.ts
  src/__generated__/FairApp_Test_Query.graphql.ts
  src/__generated__/FairHeaderTestQuery.graphql.ts
  src/__generated__/FairHeader_fair.graphql.ts
  src/__generated__/FairOverviewTestQuery.graphql.ts
  src/__generated__/fairRoutes_FairOverviewQuery.graphql.ts
  src/__generated__/fairRoutes_FairQuery.graphql.ts
Labels: Jira Synced

#16013 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#16010 Deploy
  .claude/settings.json
  data/schema.graphql
  package.json
  src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResultMetaData.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
  src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormMain.tsx
  src/Apps/MyCollection/Routes/EditArtwork/MyCollectionEditArtwork.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkDetailField.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkDetailFields.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkDetails.tsx
  src/Apps/Order/Routes/Details/Components/OrderDetailsMessage.tsx
  src/Apps/Order/Routes/Details/Components/OrderDetailsPage.tsx
  src/Apps/Order/Routes/Details/Components/__tests__/OrderDetailsMessage.jest.tsx
  src/Apps/Order/Routes/Details/Components/__tests__/OrderDetailsPage.jest.tsx
  src/Apps/Order/Routes/Details/OrderDetailsRoute.tsx
  src/Apps/Order2/Hooks/useOrder2Tracking.tsx
  src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2DeliveryForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2FulfillmentDetailsStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2SavedAddressOptions.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/__tests__/Order2DeliveryForm.jest.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/utils.ts
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/Apps/Order2/Utils/addressUtils.ts
  src/Apps/Order2/Utils/confirmationTokenUtils.ts
  src/Apps/Order2/Utils/getShippableCountries.ts
  src/Components/TopContextBar.tsx
  src/__generated__/Order2CheckoutApp_me.graphql.ts
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2DeliveryFormTestQuery.graphql.ts
  src/__generated__/Order2DeliveryForm_me.graphql.ts
  src/__generated__/Order2DeliveryForm_order.graphql.ts
  src/__generated__/Order2FulfillmentDetailsStep_me.graphql.ts
  src/__generated__/Order2PaymentFormTestQuery.graphql.ts
  src/__generated__/Order2PaymentForm_me.graphql.ts
  src/__generated__/OrderDetailsMessage_Test_Query.graphql.ts
  src/__generated__/OrderDetailsMessage_me.graphql.ts
  src/__generated__/OrderDetailsPage_Test_Query.graphql.ts
  src/__generated__/OrderDetailsPage_me.graphql.ts
  src/__generated__/OrderDetailsRoute_viewer.graphql.ts
  src/__generated__/confirmationTokenUtilsQuery.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/orderRoutes_DetailsQuery.graphql.ts
  src/__generated__/useOrder2SetOrderDeliveryAddressMutation.graphql.ts
  src/__generated__/useOrder2SetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useOrder2SetOrderPaymentMutation.graphql.ts
  src/__generated__/useOrder2SetOrderPickupDetailsMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#16028 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#16032 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#16031 feat(EMI-2457): Add address flow in checkout
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2DeliveryForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/SavedAddressOptions/AddAddressForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/SavedAddressOptions/Order2SavedAddressOptions.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/SavedAddressOptions/UpdateAddressForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/__tests__/Order2DeliveryForm.jest.tsx
  src/Apps/Order2/Routes/Checkout/Mutations/useOrder2CreateUserAddressMutation.ts
  src/__generated__/useOrder2CreateUserAddressMutation.graphql.ts
Labels: Jira Synced

#16035 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#16034 Deploy
  data/schema.graphql
  src/Apps/Articles/AuthorsApp.tsx
  src/Apps/Articles/Components/ArticlesAuthors.tsx
  src/Apps/Articles/articlesRoutes.tsx
  src/Apps/Artists/Routes/ArtistsByLetter.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2DeliveryForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/SavedAddressOptions/AddAddressForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/SavedAddressOptions/Order2SavedAddressOptions.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/SavedAddressOptions/UpdateAddressForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/__tests__/Order2DeliveryForm.jest.tsx
  src/Apps/Order2/Routes/Checkout/Mutations/useOrder2CreateUserAddressMutation.ts
  src/__generated__/ArticlesAuthorsQuery.graphql.ts
  src/__generated__/useOrder2CreateUserAddressMutation.graphql.ts
Labels: Jira Synced

#16038 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#16040 fix(EMI-2774): use correct SEPA type
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
Labels: Jira Synced

#16044 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#16046 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#16043 feat(EMI-2528): enable Wire Transfer as payment method
  src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/__tests__/Order2PaymentForm.jest.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2PaymentFormTestQuery.graphql.ts
  src/__generated__/Order2PaymentForm_order.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/useOrder2SetOrderDeliveryAddressMutation.graphql.ts
  src/__generated__/useOrder2SetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useOrder2SetOrderPaymentMutation.graphql.ts
  src/__generated__/useOrder2SetOrderPickupDetailsMutation.graphql.ts
Labels: Jira Synced

#16050 refactor: remove old force PhoneNumberInput component
  src/Apps/MyCollection/ContactInformation/ContactInformationForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2PickupForm.tsx
  src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
  src/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddressForm.tsx
  src/Components/Address/AddressFormFields.tsx
  src/Components/Address/utils/utils.ts
  src/Components/PhoneNumberInput/PhoneNumberInput.tsx
  src/Components/PhoneNumberInput/README.md
  src/Components/PhoneNumberInput/index.ts
  src/Components/PhoneNumberInput/validatePhoneNumber.ts
  src/__generated__/utilsValidatePhoneNumberQuery.graphql.ts
Labels: Jira Synced

#16056 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#16059 fix: change .gitignore to track claude.local.md
  .gitignore
Labels: Merge On Green
