Repository artsy/force, pull requests merged in 2025-04, with the labels that each got.

#15375 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15376 feat(DIA-1246): Artsy for Galleries and Collecting 101 pages
  src/Components/NavBar/NavBar.tsx
Labels: Jira Synced

#15378 Deploy
  data/schema.graphql
  src/Components/ArtsyShippingEstimate.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/menuData.ts
Labels: Jira Synced

#15381 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15384 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15385 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15388 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15390 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15391 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtsyShippingEstimate_Test_Query.graphql.ts
  src/__generated__/ArtsyShippingEstimate_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
Labels: Squash On Green

#15392 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15396 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15397 chore(DIA-1224): Removing feature flags
  src/System/Components/RouterLink.tsx
  src/System/Hooks/usePrefetchRoute.tsx
Labels: Jira Synced

#15383 fix(price filter): alignment of histogram and sliders
  src/Components/PriceRange/Histogram.tsx
Labels: Jira Synced

#15400 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15402 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15403 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15404 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15398 feat(EMI-2367): Add Apple Pay payment method
  src/Apps/Order/Components/ApplePayDetails.tsx
  src/Apps/Order/Components/PaymentMethodSummaryItem.tsx
  src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
  src/Apps/Settings/Routes/Purchases/Components/__tests__/SettingsPurchases.jest.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/PaymentMethodSummaryItem_order.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/SettingsPurchasesQuery.graphql.ts
  src/__generated__/SettingsPurchasesRow_order.graphql.ts
  src/__generated__/SettingsPurchases_Test_Query.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/orderRoutes_AcceptQuery.graphql.ts
  src/__generated__/orderRoutes_CounterQuery.graphql.ts
  src/__generated__/orderRoutes_RespondQuery.graphql.ts
  src/__generated__/orderRoutes_ReviewQuery.graphql.ts
  src/__generated__/orderRoutes_StatusQuery.graphql.ts
  src/__generated__/settingsRoutes_PurchasesRouteQuery.graphql.ts
Labels: Jira Synced

#15406 Deploy
  data/schema.graphql
  package.json
  src/Apps/Order/Components/ApplePayDetails.tsx
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUnsetOrderFulfillmentOptionMutation.ts
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckout.jest.tsx
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Order/Components/ExpressCheckout/index.tsx
  src/Apps/Settings/Routes/Purchases/Components/__tests__/SettingsPurchases.jest.tsx
  src/__generated__/useUnsetOrderFulfillmentOptionMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#15413 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15417 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15419 feat(EMI-2393): add ToS line below Apple Pay CTA
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
Labels: Jira Synced

#15372 fix(EMI-2375): testing Apple Pay in checkout app
  src/Apps/Checkout/ApplePay.tsx
  src/Apps/Checkout/checkoutRoutes.tsx
  src/__generated__/ApplePay_order.graphql.ts
  src/__generated__/checkoutRoutes_ApplePayQuery.graphql.ts
Labels: Jira Synced

#15414 Deploy
  data/schema.graphql
  package.json
  src/Apps/Checkout/ApplePay.tsx
  src/Apps/Checkout/checkoutRoutes.tsx
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Components/DeepZoom/DeepZoom.tsx
  src/__generated__/ApplePay_order.graphql.ts
  src/__generated__/checkoutRoutes_ApplePayQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#15429 Deploy
  package.json
  src/Apps/Fairs/Routes/FairsIndex.tsx
  src/__generated__/FairsIndex_Test_Query.graphql.ts
  src/__generated__/FairsIndex_viewer.graphql.ts
  src/__generated__/fairsRoutes_FairsQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#15431 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15433 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15434 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/ArtistSeriesOptionsQuery.graphql.ts
  src/__generated__/ArtistWorksForSaleRouteArtworksQuery.graphql.ts
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/CollectArtworkFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/__generated__/CollectionArtworksQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGridQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGrid_Test_Query.graphql.ts
  src/__generated__/FairArtworksFilterQuery.graphql.ts
  src/__generated__/FairArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/__generated__/GeneArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
  src/__generated__/SaleArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/SuggestedArtworksModalGridQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/TagArtworkFilterQuery.graphql.ts
  src/__generated__/TagArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/WorksFilterQuery.graphql.ts
  src/__generated__/WorksFilterRefetchQuery.graphql.ts
  src/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/saleRoutes_SaleQuery.graphql.ts
  src/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
Labels: Squash On Green

#15435 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15436 fix: padding on partner works screen
  src/Apps/Partner/PartnerApp.tsx
Labels: Merge On Green

#15437 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15418 chore(EMI-2387): update express checkout shipping display names
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
Labels: Jira Synced

#15432 Deploy
  data/schema.graphql
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/Util/useShowStoredErrorDialog.ts
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
  src/Apps/Partner/PartnerApp.tsx
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/ArtistSeriesOptionsQuery.graphql.ts
  src/__generated__/ArtistWorksForSaleRouteArtworksQuery.graphql.ts
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/CollectArtworkFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/__generated__/CollectionArtworksQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGridQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGrid_Test_Query.graphql.ts
  src/__generated__/FairArtworksFilterQuery.graphql.ts
  src/__generated__/FairArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/__generated__/GeneArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
  src/__generated__/SaleArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/SuggestedArtworksModalGridQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/TagArtworkFilterQuery.graphql.ts
  src/__generated__/TagArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/WorksFilterQuery.graphql.ts
  src/__generated__/WorksFilterRefetchQuery.graphql.ts
  src/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/saleRoutes_SaleQuery.graphql.ts
  src/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
Labels: Jira Synced

#15421 feat(EMI-2391): unset payment method on order reset
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUnsetOrderPaymentMethodMutation.ts
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/__generated__/useUnsetOrderPaymentMethodMutation.graphql.ts
Labels: Jira Synced

#15442 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15444 chore(EMI-2410): remove dot from checkout links
  src/Apps/Order/Components/BuyerGuarantee.tsx
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Components/__tests__/BuyerGuarantee.jest.tsx
Labels: Jira Synced

#15441 Deploy
  data/schema.graphql
  package.json
  src/Apps/Order/Components/BuyerGuarantee.tsx
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUnsetOrderPaymentMethodMutation.ts
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Components/__tests__/BuyerGuarantee.jest.tsx
  src/Server/bootstrapSharify.ts
  src/Server/middleware/__tests__/bootstrapSharifyAndContextLocalsMiddleware.jest.ts
  src/Server/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts
  src/System/Boot.tsx
  src/Typings/sharify.d.ts
  src/__generated__/useUnsetOrderPaymentMethodMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#15445 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15448 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15452 fix(DIA-1290): updated Collecting 101 url
  src/Components/NavBar/NavBar.tsx
Labels: Jira Synced

#15453 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15455 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15456 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15457 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15459 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15454 Deploy
  data/schema.graphql
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkDetails.tsx
  src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkDetails.jest.tsx
  src/Apps/Order/Components/ApplePayDetails.tsx
  src/Apps/Order/Components/CreditCardDetails.tsx
  src/__generated__/MyCollectionArtworkDetailsTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkDetails_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#15463 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15466 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15469 chore: update metaphysics graphql schema
  data/schema.graphql
  yarn.lock
Labels: Squash On Green

#15470 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/ArtistSeriesOptionsQuery.graphql.ts
  src/__generated__/ArtistWorksForSaleRouteArtworksQuery.graphql.ts
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/CollectArtworkFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/__generated__/CollectionArtworksQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGridQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGrid_Test_Query.graphql.ts
  src/__generated__/FairArtworksFilterQuery.graphql.ts
  src/__generated__/FairArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/__generated__/GeneArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
  src/__generated__/SaleArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/SuggestedArtworksModalGridQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/TagArtworkFilterQuery.graphql.ts
  src/__generated__/TagArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/WorksFilterQuery.graphql.ts
  src/__generated__/WorksFilterRefetchQuery.graphql.ts
  src/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/saleRoutes_SaleQuery.graphql.ts
  src/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
Labels: Squash On Green

#15460 feat(EMI-2208): rich phone input
  src/Apps/Auction/Components/Form/AddressFormWithCreditCard.tsx
  src/Apps/Checkout/Routes/CheckoutOverviewRoute.tsx
  src/Apps/Checkout/checkoutRoutes.tsx
  src/Apps/Invoice/Components/InvoicePaymentForm.tsx
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Routes/Shipping/Components/AddressModal.tsx
  src/Apps/Order/Routes/Shipping/Components/__tests__/AddressModal.jest.tsx
  src/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddressForm.tsx
  src/Components/Address/AddressFormFields.tsx
  src/Components/Address/__tests__/AddressFormFields.jest.tsx
  src/Components/Address/__tests__/utils.ts
  src/Components/Address/utils.ts
Labels: Jira Synced

#15386 fix: broken search input debouncing
  src/Components/Search/Mobile/Overlay.tsx
  src/Components/Search/SearchBarInput.tsx
Labels: Jira Synced

#15474 chore(EMI-2364): create order2 app for checkout and details pages
  src/Apps/Checkout/ApplePay.tsx
  src/Apps/Checkout/CheckoutApp.tsx
  src/Apps/Checkout/Routes/CheckoutOverviewRoute.tsx
  src/Apps/Checkout/checkoutRoutes.tsx
  src/Apps/Order/Routes/Details/Details.tsx
  src/Apps/Order/orderRoutes.tsx
  src/Apps/Order2/Order2App.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ExpressCheckoutSection.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Details/Components/Order2DetailsPage.tsx
  src/Apps/Order2/Routes/Details/Order2DetailsRoute.tsx
  src/Apps/Order2/order2Routes.tsx
  src/Components/Address/AddressFormFields.tsx
  src/__generated__/ApplePay_order.graphql.ts
  src/__generated__/Details_order.graphql.ts
  src/__generated__/ExpressCheckoutQuery.graphql.ts
  src/__generated__/ExpressCheckoutUI_Test_Query.graphql.ts
  src/__generated__/ExpressCheckoutUI_order.graphql.ts
  src/__generated__/ExpressCheckout_Test_Query.graphql.ts
  src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
  src/__generated__/Order2DetailsRoute_viewer.graphql.ts
  src/__generated__/Order2ExpressCheckoutSection_order.graphql.ts
  src/__generated__/checkoutRoutes_ApplePayQuery.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/order2Routes_DetailsQuery.graphql.ts
  src/__generated__/orderRoutes_DetailsQuery.graphql.ts
  src/__generated__/useSetFulfillmentOptionMutation.graphql.ts
  src/__generated__/useUnsetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useUnsetOrderPaymentMethodMutation.graphql.ts
  src/__generated__/useUpdateOrderMutation.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#15479 Deploy
  package.json
  src/Apps/Checkout/ApplePay.tsx
  src/Apps/Checkout/CheckoutApp.tsx
  src/Apps/Checkout/Routes/CheckoutOverviewRoute.tsx
  src/Apps/Checkout/checkoutRoutes.tsx
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Order/Routes/Details/Details.tsx
  src/Apps/Order/orderRoutes.tsx
  src/Apps/Order2/Order2App.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ExpressCheckoutSection.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Details/Components/Order2DetailsPage.tsx
  src/Apps/Order2/Routes/Details/Order2DetailsRoute.tsx
  src/Apps/Order2/order2Routes.tsx
  src/Components/Address/AddressFormFields.tsx
  src/__generated__/ApplePay_order.graphql.ts
  src/__generated__/Details_order.graphql.ts
  src/__generated__/ExpressCheckoutQuery.graphql.ts
  src/__generated__/ExpressCheckoutUI_Test_Query.graphql.ts
  src/__generated__/ExpressCheckoutUI_order.graphql.ts
  src/__generated__/ExpressCheckout_Test_Query.graphql.ts
  src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
  src/__generated__/Order2DetailsRoute_viewer.graphql.ts
  src/__generated__/Order2ExpressCheckoutSection_order.graphql.ts
  src/__generated__/checkoutRoutes_ApplePayQuery.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/order2Routes_DetailsQuery.graphql.ts
  src/__generated__/orderRoutes_DetailsQuery.graphql.ts
  src/__generated__/useSetFulfillmentOptionMutation.graphql.ts
  src/__generated__/useUnsetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useUnsetOrderPaymentMethodMutation.graphql.ts
  src/__generated__/useUpdateOrderMutation.graphql.ts
  src/routes.tsx
  yarn.lock
Labels: Jira Synced

#15481 chore(EMI-2364): Redirects for new order checkout/details routes
  src/Apps/Order/__tests__/OrderApp.jest.enzyme.tsx
  src/Apps/Order/orderRoutes.tsx
  src/Apps/Order/redirects.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Details/Order2DetailsRoute.tsx
  src/Apps/Order2/order2Routes.tsx
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/order2Routes_DetailsQuery.graphql.ts
Labels: Jira Synced

#15487 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/ArtistSeriesOptionsQuery.graphql.ts
  src/__generated__/ArtistWorksForSaleRouteArtworksQuery.graphql.ts
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/CollectArtworkFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/__generated__/CollectionArtworksQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGridQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGrid_Test_Query.graphql.ts
  src/__generated__/FairArtworksFilterQuery.graphql.ts
  src/__generated__/FairArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/__generated__/GeneArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
  src/__generated__/SaleArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/SuggestedArtworksModalGridQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/TagArtworkFilterQuery.graphql.ts
  src/__generated__/TagArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/WorksFilterQuery.graphql.ts
  src/__generated__/WorksFilterRefetchQuery.graphql.ts
  src/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/saleRoutes_SaleQuery.graphql.ts
  src/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
  src/__generated__/useUpdateOrderMutation.graphql.ts
Labels: Squash On Green

#15483 fix(EMI-2443): consider the state for arta shipping widget
  src/Components/ArtsyShippingEstimate.tsx
  src/Components/__tests__/ArtsyShippingEstimate.jest.tsx
Labels: Jira Synced

#15491 feat(EMI-2431): google pay
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
Labels: Jira Synced

#15488 Deploy
  data/schema.graphql
  docs/using_unleash.md
  package.json
  src/Apps/About/AboutApp.tsx
  src/Apps/Example/exampleRoutes.tsx
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Order/getRedirect.ts
  src/Components/ArtsyShippingEstimate.tsx
  src/Components/__tests__/ArtsyShippingEstimate.jest.tsx
  src/Server/featureFlags/unleashHelpers.ts
  src/System/Boot.tsx
  src/System/Contexts/SystemContext.tsx
  src/System/FeatureFlags/FeatureFlagContext.tsx
  src/System/FeatureFlags/unleashClient.ts
  src/System/FeatureFlags/unleashServer.ts
  src/System/Router/__tests__/clientRouter.jest.tsx
  src/System/Router/__tests__/serverRouter.jest.enzyme.tsx
  src/System/Router/clientRouter.tsx
  src/System/Router/serverRouter.tsx
  src/Utils/tests.legacy.ts
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/ArtistSeriesOptionsQuery.graphql.ts
  src/__generated__/ArtistWorksForSaleRouteArtworksQuery.graphql.ts
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/CollectArtworkFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/__generated__/CollectionArtworksQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGridQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGrid_Test_Query.graphql.ts
  src/__generated__/FairArtworksFilterQuery.graphql.ts
  src/__generated__/FairArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/__generated__/GeneArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
  src/__generated__/SaleArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/SuggestedArtworksModalGridQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/TagArtworkFilterQuery.graphql.ts
  src/__generated__/TagArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/WorksFilterQuery.graphql.ts
  src/__generated__/WorksFilterRefetchQuery.graphql.ts
  src/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/saleRoutes_SaleQuery.graphql.ts
  src/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
  src/__generated__/useUpdateOrderMutation.graphql.ts
  src/client.tsx
  src/server.ts
  src/tests.ts
  yarn.lock
Labels: Jira Synced

#15493 feat(EMI-2447): always show express checkout
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
Labels: Jira Synced

#15492 feat(EMI-2432): Add Google Pay icon to order history
  src/Apps/Order/Components/GooglePayDetails.tsx
  src/Apps/Order/Components/PaymentMethodSummaryItem.tsx
  src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
  src/Apps/Settings/Routes/Purchases/Components/__tests__/SettingsPurchases.jest.tsx
Labels: Jira Synced

#15497 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15499 fix(DIA-1232): removing lazy load for image rendering
  src/Components/Onboarding/Components/OnboardingFigure.tsx
Labels: Jira Synced

#15500 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15501 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15498 Deploy
  data/schema.graphql
  package.json
  src/Apps/Artwork/Components/ArtworkTopContextBar/ArtworkTopContextBarBreadcrumb.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/__tests__/ArtworkTopContextBar.jest.enzyme.tsx
  src/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.fixture.ts
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.jest.enzyme.tsx
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.jest.tsx
  src/Apps/Partner/Components/PartnerMeta/index.tsx
  src/Components/Onboarding/Components/OnboardingFigure.tsx
  src/Components/Seo/CreativeWork.tsx
  src/Components/Seo/LocalBusiness.tsx
  src/Components/Seo/Person.tsx
  src/Components/Seo/Product.tsx
  src/Components/Seo/StructuredData.tsx
  src/Components/Seo/__tests__/LocalBusiness.jest.enzyme.tsx
  src/Components/Seo/__tests__/StructuredData.jest.enzyme.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkMeta_Test_Query.graphql.ts
  src/__generated__/SeoDataForArtworkTestQuery.graphql.ts
  src/__generated__/SeoDataForArtwork_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#15506 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15507 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
