Repository artsy/force, pull requests merged in 2025-09, with the labels that each got.

#16055 refactor: using the address component in settings
  src/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddressForm.tsx
Labels: Jira Synced

#16071 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#16073 fix(AMBER-1966): Respect primary image setting on the artwork page
  CLAUDE.md
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.jest.tsx
  src/__generated__/ArtworkImageBrowserTestQuery.graphql.ts
Labels: Jira Synced

#16068 Deploy
  CLAUDE.md
  data/schema.graphql
  package.json
  src/Apps/About2/Components/AboutWhatWeDo.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.jest.tsx
  src/Apps/Order/Routes/Shipping/Components/FulfillmentDetailsForm.tsx
  src/Apps/Order/Routes/Shipping/Components/__tests__/FulfillmentDetailsForm.jest.tsx
  src/__generated__/ArtworkImageBrowserTestQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#16079 fix(EMI-2802): Fix SEPA/ACH checkout hanging on loading skeleton
  src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
Labels: Jira Synced

#16084 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#16088 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#16090 Deploy
  data/schema.graphql
  src/Apps/Articles/AuthorApp.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2DeliveryForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/__tests__/Order2DeliveryForm.jest.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
Labels: Jira Synced

#16094 Deploy
  package.json
  playwright/e2e/about.spec.ts
  src/Apps/About/AboutApp.tsx
  src/Apps/About/AboutArtworksRail.tsx
  src/Apps/About/Components/AboutContact.tsx
  src/Apps/About/Components/AboutDownload.tsx
  src/Apps/About/Components/AboutDownloadQRCode.tsx
  src/Apps/About/Components/AboutHeader.tsx
  src/Apps/About/Components/AboutHero.tsx
  src/Apps/About/Components/AboutJoin.tsx
  src/Apps/About/Components/AboutLayout.tsx
  src/Apps/About/Components/AboutMissionAndVision.tsx
  src/Apps/About/Components/AboutNav.tsx
  src/Apps/About/Components/AboutOurStory.tsx
  src/Apps/About/Components/AboutOurTeam.tsx
  src/Apps/About/Components/AboutPress.tsx
  src/Apps/About/Components/AboutPressShelf.tsx
  src/Apps/About/Components/AboutSection.tsx
  src/Apps/About/Components/AboutStats.tsx
  src/Apps/About/Components/AboutStructuredData.tsx
  src/Apps/About/Components/AboutTagline.tsx
  src/Apps/About/Components/AboutWhatWeDo.tsx
  src/Apps/About/Components/__tests__/AboutPressShelf.jest.tsx
  src/Apps/About/aboutRoutes.tsx
  src/Apps/About2/About2App.tsx
  src/Apps/About2/about2Routes.tsx
  src/Apps/Conversations/components/Message/ConversationMessage.tsx
  src/Apps/Conversations/components/Message/ConversationMessageBubble.tsx
  src/Apps/Conversations/components/Message/Utils/dateFormatters.tsx
  src/Apps/Conversations/components/Message/__tests__/ConversationMessageBubble.jest.tsx
  src/Apps/Conversations/components/Message/__tests__/ConversationMessages.jest.tsx
  src/Components/Footer/FooterDownloadAppBanner.tsx
  src/__generated__/AboutArtworksRailQuery.graphql.ts
  src/__generated__/AboutArtworksRail_marketingCollection.graphql.ts
  src/__generated__/ConversationMessageTestQuery.graphql.ts
  src/__generated__/ConversationMessage_message.graphql.ts
  src/__generated__/ConversationMessagesPaginationQuery.graphql.ts
  src/__generated__/ConversationMessagesTestQuery.graphql.ts
  src/__generated__/conversationsRoutes_DetailQuery.graphql.ts
  src/__generated__/useSendConversationMessageMutation.graphql.ts
  src/routes.tsx
  yarn.lock
Labels: Jira Synced

#16081 feat: adding billing address
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/__tests__/Order2PaymentForm.jest.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2PaymentFormTestQuery.graphql.ts
  src/__generated__/Order2PaymentForm_order.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/useOrder2SetOrderDeliveryAddressMutation.graphql.ts
  src/__generated__/useOrder2SetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useOrder2SetOrderPaymentMutation.graphql.ts
  src/__generated__/useOrder2SetOrderPickupDetailsMutation.graphql.ts
Labels: Jira Synced

#16103 feat(EMI-2785): artwork clickable
  src/Apps/Conversations/components/Details/ConversationArtwork.tsx
  src/Apps/Conversations/components/Details/__tests__/ConversationDetails.jest.tsx
Labels: Jira Synced

#16111 fix(EMI-2817): add setAsDefault checkbox to AddAddressForm
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2DeliveryForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/SavedAddressOptions/AddAddressForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/SavedAddressOptions/__tests__/AddAddressForm.jest.tsx
Labels: Jira Synced

#16129 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#16132 feat: migrate ingress to new controllers (production)
  hokusai/production.yml
Labels: Jira Synced

#16139 refactor: use phoneNumberParsed instead of formatPhoneNumber
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2DeliveryForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/SavedAddressOptions/Order2SavedAddressOptions.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/__tests__/utils.jest.ts
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/utils.ts
  src/Apps/Order2/Utils/__tests__/addressUtils.jest.ts
  src/Apps/Order2/Utils/addressUtils.ts
  src/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddress.tsx
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2DeliveryFormTestQuery.graphql.ts
  src/__generated__/Order2DeliveryForm_me.graphql.ts
  src/__generated__/SettingsShippingAddress_address.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/settingsRoutes_ShippingRouteQuery.graphql.ts
  src/__generated__/useAddAddressMutation.graphql.ts
  src/__generated__/useDeleteAddressMutation.graphql.ts
  src/__generated__/useEditAddressMutation.graphql.ts
  src/__generated__/useOrder2CreateUserAddressMutation.graphql.ts
  src/__generated__/useOrder2UpdateUserAddressMutation.graphql.ts
  src/__generated__/useOrder2UpdateUserDefaultAddressMutation.graphql.ts
  src/__generated__/useSetDefaultAddressMutation.graphql.ts
Labels: Jira Synced

#16143 fix(onyx-1919): view in room works for artworks with diameters
  src/Components/ViewInRoom/ViewInRoomArtwork.tsx
  src/Components/ViewInRoom/__tests__/ViewInRoomArtwork.jest.tsx
  src/__generated__/ArtworkActionsTestQuery.graphql.ts
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/ViewInRoomArtworkTestQuery.graphql.ts
  src/__generated__/ViewInRoomArtwork_artwork.graphql.ts
  src/__generated__/ViewInRoomTestQuery.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#16154 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/FulfillmentDetailsForm_me.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
Labels: Squash On Green

#16172 feat(EMI-2830): display order2 artsy shipping options
  src/Apps/Order2/Routes/Checkout/Components/DeliveryOptionsStep/Order2DeliveryOptionsForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/DeliveryOptionsStep/__tests__/Order2DeliveryOptionsForm.jest.tsx
  src/Apps/Order2/Routes/Checkout/Components/DeliveryOptionsStep/utils.ts
  src/__generated__/Order2DeliveryOptionsFormTestQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#16178 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#16171 fix(DIAM-103): Missing schema on the About Us page
  src/Apps/About/AboutApp.tsx
  src/Apps/About/Components/AboutStructuredData.tsx
  src/Apps/Home/Components/HomeStructuredData.tsx
  src/Apps/Home/HomeApp.tsx
Labels: Jira Synced
