Repository artsy/force, pull requests merged in 2025-07, with the labels that each got.

#15801 fix(feature): makes featured title/sub/text clickable
  src/Apps/Feature/Components/FeatureFeaturedLink.tsx
Labels: Jira Synced

#15779 chore(EMI-2595): add proper artwork metadata to review step
  src/Apps/Order2/Routes/Checkout/Components/Order2CollapsibleOrderSummary.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2ReviewStep_order.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/useSetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useSetOrderPickupDetailsMutation.graphql.ts
Labels: Jira Synced

#15798 Deploy
  .circleci/config.yml
  data/schema.graphql
  src/Apps/About2/Components/AboutDownload.tsx
  src/Apps/About2/Components/AboutDownloadQRCode.tsx
  src/Apps/About2/Components/AboutHero.tsx
  src/Apps/About2/Components/AboutJoin.tsx
  src/Apps/About2/Components/AboutMissionAndVision.tsx
  src/Apps/About2/Components/AboutOurStory.tsx
  src/Apps/About2/Components/AboutOurTeam.tsx
  src/Apps/Feature/Components/FeatureFeaturedLink.tsx
  src/Apps/Order2/Layouts/LayoutCheckout.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2CheckoutLoadingSkeleton.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2CollapsibleOrderSummary.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2ReviewStep_order.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/useSetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useSetOrderPickupDetailsMutation.graphql.ts
Labels: Jira Synced

#15802 chore(EMI-2636): remove emerald_hackathon-sale-total-raised feature flag
  src/Apps/Auction/Components/AuctionDetails/AuctionInfoSidebar.tsx
  src/Apps/Auction/Components/AuctionDetails/__tests__/AuctionInfoSidebar.jest.enzyme.tsx
Labels: Jira Synced

#15808 feat(EMI-2487): contact gallery to conversations
  src/Apps/Order2/Routes/Details/Components/Order2DetailsMessage.tsx
  src/Apps/Order2/Routes/Details/Components/__tests__/Order2DetailsMessage.jest.tsx
  src/__generated__/Order2DetailsMessage_Test_Query.graphql.ts
  src/__generated__/Order2DetailsMessage_order.graphql.ts
  src/__generated__/Order2DetailsPage_Test_Query.graphql.ts
  src/__generated__/order2Routes_DetailsQuery.graphql.ts
Labels: Jira Synced

#15811 Deploy
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkLightbox.tsx
  src/Apps/Artwork/Components/SubmittedOrderModal/SubmittedOrderModal.tsx
  src/Apps/Artwork/Components/SubmittedOrderModal/__tests__/SubmittedOrderModal.jest.tsx
  src/Apps/Artwork/Components/SubmittedOrderModal/index.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkLightbox.jest.enzyme.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/Order2ExpressCheckoutUI.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/Apps/Order2/Routes/Details/Components/Order2DetailsMessage.tsx
  src/Apps/Order2/Utils/navigationGuards.ts
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkImageBrowserLarge_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowserSmall_Test_Query.graphql.ts
  src/__generated__/ArtworkLightboxTestQuery.graphql.ts
  src/__generated__/ArtworkLightbox_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/SubmittedOrderModalQuery.graphql.ts
  src/__generated__/SubmittedOrderModal_Test_Query.graphql.ts
  src/__generated__/SubmittedOrderModal_submittedOrder.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#15819 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useUpdateOrderMutation.graphql.ts
Labels: Squash On Green

#15831 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useSubmitOrderMutation.graphql.ts
Labels: Squash On Green

#15826 feat(EMI-2537): Allow saving credit card when submitting an order
  src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
Labels: Jira Synced

#15833 fix(DIA-1407): artist bio credit on artwork pages
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Components/ArtistBio.tsx
  src/Components/__tests__/ArtistBio.jest.enzyme.tsx
  src/__generated__/ArtistBioTestQuery.graphql.ts
  src/__generated__/ArtistBio_bio.graphql.ts
  src/__generated__/ArtistInfoQuery.graphql.ts
  src/__generated__/ArtistInfo_Test_Query.graphql.ts
  src/__generated__/ArtistInfo_artist.graphql.ts
Labels: Squash On Green

#15834 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15845 feat(ONYX-1770): autoscroll to selected saved list, cleanup old implementation
  src/Apps/CollectorProfile/Routes/Saves/CollectorProfileSavesRoute.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListItem.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/SavesArtworks.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/SavesArtworksGrid.tsx
  src/Apps/CollectorProfile/Routes/Saves/Utils/useArtworkListVisibility.tsx
Labels: Jira Synced

#15853 feat(EMI-2539): Buyer can pay with a saved credit card
  src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentStep.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/__generated__/Order2PaymentFormSavedCreditCardsQuery.graphql.ts
Labels: Jira Synced

#15858 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15837 feat: add Artwork Recs rail to the home page
  src/Apps/ArtworkRecommendations/ArtworkRecommendationsApp.tsx
  src/Apps/ArtworkRecommendations/Components/ArtworkRecommendationsArtworksGrid.tsx
  src/Apps/ArtworkRecommendations/artworkRecommendationsRoutes.tsx
  src/Apps/Home/Components/HomeArtworkRecommendationsRail.tsx
  src/Apps/Home/Components/__tests__/HomeArtworkRecommendationsRail.jest.tsx
  src/Apps/Home/HomeApp.tsx
  src/__generated__/ArtworkRecommendationsApp_me.graphql.ts
  src/__generated__/ArtworkRecommendationsArtworksGridPaginationQuery.graphql.ts
  src/__generated__/ArtworkRecommendationsArtworksGrid_me.graphql.ts
  src/__generated__/HomeArtworkRecommendationsRailQuery.graphql.ts
  src/__generated__/HomeArtworkRecommendationsRail_Test_Query.graphql.ts
  src/__generated__/HomeArtworkRecommendationsRail_me.graphql.ts
  src/__generated__/artworkRecommendationsRoutes_TopLevelQuery.graphql.ts
  src/routes.tsx
Labels: Jira Synced

#15867 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15875 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15876 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15873 feat(EMI-2503): Fulfillment details step error handling
  src/Apps/Order/Components/ExpressCheckout/Util/mutationHandling.ts
  src/Apps/Order2/Routes/Checkout/Components/CheckoutErrorBanner.tsx
  src/Apps/Order2/Routes/Checkout/Components/DeliveryOptionsStep/utils.ts
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2DeliveryForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/__tests__/handleError.jest.ts
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/handleError.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/DevTools/mockStripe.ts
Labels: Jira Synced

#15880 feat: add Claude Code permissions to deny .env file access
  .claude/settings.json
Labels: Merge On Green

#15878 Deploy
  .claude/settings.json
  package.json
  src/Apps/Order/Components/ExpressCheckout/Mutations/useSubmitOrderMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Util/mutationHandling.ts
  src/Apps/Order2/Routes/Checkout/Components/CheckoutErrorBanner.tsx
  src/Apps/Order2/Routes/Checkout/Components/DeliveryOptionsStep/utils.ts
  src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/Order2ExpressCheckout.tsx
  src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/__tests__/Order2ExpressCheckout.jest.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2DeliveryForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/__tests__/handleError.jest.ts
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/handleError.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/DevTools/mockStripe.ts
  src/__generated__/useSubmitOrderMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#15893 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15894 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArticleBody_test_Query.graphql.ts
  src/__generated__/ArticleByline_article.graphql.ts
  src/__generated__/ArticleStructuredData_article.graphql.ts
  src/__generated__/ArtworkDetailsArticles_artwork.graphql.ts
  src/__generated__/ArtworkDetailsTestQuery.graphql.ts
Labels: Squash On Green

#15897 chore: ignore .claude/settings.local.json folder
  .gitignore
Labels: Merge On Green

#15899 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15901 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15904 chore(EMI-2669): track saved payment method interactions
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/__tests__/Order2PaymentForm.jest.tsx
  src/Apps/Order2/Routes/Checkout/Hooks/useCheckoutTracking.ts
Labels: Jira Synced

#15905 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15907 chore(EMI-2695): rename 'Save and Continue' to 'Continue to Review'
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/__tests__/Order2PaymentForm.jest.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
Labels: Jira Synced

#15927 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
