Repository artsy/force, pull requests merged in 2025-03, with the labels that each got.

#15264 Deploy
  data/schema.graphql
  hokusai/staging.yml
  src/Apps/Checkout/CheckoutApp.tsx
  src/Apps/Checkout/Routes/CheckoutOverviewRoute.tsx
  src/Apps/Checkout/checkoutRoutes.tsx
  src/routes.tsx
Labels: Jira Synced

#15272 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15271 Deploy
  data/schema.graphql
  package.json
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/__generated__/ExpressCheckoutUI_Test_Query.graphql.ts
  src/__generated__/ExpressCheckoutUI_order.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/useSaveFulfillmentDetailsMutation.graphql.ts
  src/__generated__/useSelectShippingQuoteMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#15274 fix(DIA-1100): Update copy on curators picks rail on homepage
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx
Labels: Jira Synced

#15278 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15280 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15277 Deploy
  data/schema.graphql
  src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/ArtworkTopContextBar.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/ArtworkTopContextBarBreadcrumb.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/ArtworkTopContextBarDynamicBreadcrumb.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/ArtworkTopContextBarFair.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/ArtworkTopContextBarSale.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/ArtworkTopContextBarShow.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/__tests__/ArtworkTopContextBar.jest.enzyme.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/__tests__/ArtworkTopContextBarDynamicBreadcrumb.jest.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/__tests__/ArtworkTopContextBarFair.jest.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/__tests__/ArtworkTopContextBarSale.jest.tsx
  src/Apps/Artwork/Components/ArtworkTopContextBar/__tests__/ArtworkTopContextBarShow.jest.tsx
  src/Apps/Components/AppShell.tsx
  src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Apps/Order/Routes/__tests__/Payment.jest.enzyme.tsx
  src/Components/TopContextBar.tsx
  src/System/Contexts/NavigationHistoryContext.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkTopContextBarBreadcrumb_artwork.graphql.ts
  src/__generated__/ArtworkTopContextBarFairQuery.graphql.ts
  src/__generated__/ArtworkTopContextBarFair_test_Query.graphql.ts
  src/__generated__/ArtworkTopContextBarSaleQuery.graphql.ts
  src/__generated__/ArtworkTopContextBarSale_test_Query.graphql.ts
  src/__generated__/ArtworkTopContextBarShowQuery.graphql.ts
  src/__generated__/ArtworkTopContextBarShow_test_Query.graphql.ts
  src/__generated__/ArtworkTopContextBar_Test_Query.graphql.ts
  src/__generated__/ArtworkTopContextBar_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#15283 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/CollectorProfileArtistsAddNewDialogCreateArtistMutation.graphql.ts
Labels: Squash On Green

#15279 fix(filters): allow "framed" and "signed" as filter criteria, but not alert criteria
  src/Components/Alert/AlertProvider.tsx
  src/Components/SavedSearchAlert/constants.ts
  src/Components/SavedSearchAlert/useActiveFilterPills.ts
Labels: Jira Synced

#15286 chore(MyC): put sharing widget behind a feature flag
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
Labels: Jira Synced

#15281 feat(EMI-2308): render Payment Element UI and enable dynamic payment methods for connected accounts
  src/Apps/Checkout/Components/PaymentForm.tsx
  src/Apps/Checkout/Routes/CheckoutOverviewRoute.tsx
Labels: Jira Synced

#15284 Deploy
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkLightbox.tsx
  src/Apps/Checkout/Components/PaymentForm.tsx
  src/Apps/Checkout/Routes/CheckoutOverviewRoute.tsx
  src/Apps/Order/Routes/Shipping/ShippingContext.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
  src/Components/Alert/AlertProvider.tsx
  src/Components/SavedSearchAlert/constants.ts
  src/Components/SavedSearchAlert/useActiveFilterPills.ts
  src/__generated__/CollectorProfileArtistsAddNewDialogCreateArtistMutation.graphql.ts
Labels: Jira Synced

#15287 fix(DIA-1084): Updates to nav bar links
  src/Components/NavBar/__tests__/NavBarSubMenu.jest.enzyme.tsx
  src/Components/NavBar/menuData.ts
Labels: Jira Synced

#15291 Deploy
  src/Components/NavBar/__tests__/NavBarSubMenu.jest.enzyme.tsx
  src/Components/NavBar/menuData.ts
Labels: Jira Synced

#15296 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15297 fix: unlink partner sharing from public list sharing
  src/Components/ShareCollectionDialog.tsx
Labels: Jira Synced

#15307 feat(onyx-1570): tracking share saves
  src/Apps/CollectorProfile/Routes/Saves/Components/SavesArtworksHeader.tsx
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
  src/Apps/User/Routes/UserCollectionRoute.tsx
  src/Components/ShareCollectionDialog.tsx
Labels: Jira Synced

#15311 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15316 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15313 fix(EMI-2311): another attempt to deal with empty line in partner offer notification
  src/Components/Artwork/Details/SaleMessage.tsx
  src/Components/Notifications/PartnerOfferArtwork.tsx
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx
Labels: Jira Synced

#15318 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15320 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15322 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15317 Deploy
  data/schema.graphql
  package.json
  src/Components/Artwork/Details/SaleMessage.tsx
  src/Components/Notifications/PartnerOfferArtwork.tsx
  src/Components/Notifications/PartnerOfferCreatedNotification.tsx
  src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx
  yarn.lock
Labels: Jira Synced

#15321 feat(EMI-2330): Set order shipping address and fulfillment type
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/Mutations/useSetFulfillmentOptionMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUpdateOrderMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Util/mutationHandling.ts
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/__generated__/useSetFulfillmentOptionMutation.graphql.ts
  src/__generated__/useUpdateOrderMutation.graphql.ts
Labels: Jira Synced

#15325 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/SavesArtworksHeaderQuery.graphql.ts
Labels: Squash On Green

#15324 feat(performance): Add support for prefetching route sub queries via `prefetchSubQueries` on hover
  docs/adding_new_app.md
  docs/caching.md
  src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
  src/Apps/Artist/artistRoutes.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavBarDropdownPanel.tsx
  src/System/Components/RouterLink.tsx
  src/System/Hooks/__tests__/usePrefetchRoute.jest.tsx
  src/System/Hooks/usePrefetchRoute.tsx
  src/System/Router/Route.tsx
Labels: performance

#15328 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15329 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15330 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15331 Revert "feat(performance): Add support for prefetching route sub queries via `prefetchSubQueries` on hover"
  docs/adding_new_app.md
  docs/caching.md
  src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
  src/Apps/Artist/artistRoutes.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavBarDropdownPanel.tsx
  src/System/Components/RouterLink.tsx
  src/System/Hooks/__tests__/usePrefetchRoute.jest.tsx
  src/System/Hooks/usePrefetchRoute.tsx
  src/System/Router/Route.tsx
Labels: Merge On Green

#15333 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15327 feat(collection sharing): update UI and allow un-sharing
  src/Apps/CollectorProfile/Routes/Saves/Components/SavesArtworksHeader.tsx
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
  src/Apps/User/Components/UserCollectionArtworks.tsx
  src/Components/ShareCollectionDialog.tsx
  src/Components/__tests__/ShareCollectionDialog.jest.tsx
  src/__generated__/MyCollectionRouteQuery.graphql.ts
  src/__generated__/MyCollectionRoute_me.graphql.ts
  src/__generated__/SavesArtworksHeaderQuery.graphql.ts
  src/__generated__/ShareCollectionDialogMutation.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionRouteQuery.graphql.ts
Labels: Jira Synced, Squash On Green

#15323 Deploy
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkLightbox.tsx
  src/Apps/CollectorProfile/Routes/Saves/Components/SavesArtworksHeader.tsx
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/Mutations/useSetFulfillmentOptionMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUpdateOrderMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Util/mutationHandling.ts
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
  src/Apps/User/Components/UserCollectionArtworks.tsx
  src/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/ArtistsFilter.jest.enzyme.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/ArtistsFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/AttributionClassFilter.jest.enzyme.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/AttributionClassFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.jest.enzyme.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/MaterialsFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/MaterialsTermFilter.jest.enzyme.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/MediumFilter.jest.enzyme.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/MediumFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/PartnersFilter.jest.enzyme.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/PartnersFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.jest.enzyme.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/WaysToBuyFilter.jest.enzyme.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/WaysToBuyFilter.jest.tsx
  src/Components/ShareCollectionDialog.tsx
  src/Components/__tests__/ShareCollectionDialog.jest.tsx
  src/__generated__/MyCollectionRouteQuery.graphql.ts
  src/__generated__/MyCollectionRoute_me.graphql.ts
  src/__generated__/SavesArtworksHeaderQuery.graphql.ts
  src/__generated__/ShareCollectionDialogMutation.graphql.ts
  src/__generated__/collectorProfileRoutes_MyCollectionRouteQuery.graphql.ts
  src/__generated__/useSetFulfillmentOptionMutation.graphql.ts
  src/__generated__/useUpdateOrderMutation.graphql.ts
Labels: Jira Synced

#15337 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15341 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15344 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ShowInfo_Test_Query.graphql.ts
  src/__generated__/showRoutes_ShowInfoQuery.graphql.ts
Labels: Squash On Green

#15345 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15350 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15339 Deploy
  data/schema.graphql
  docs/best_practices.md
  package.json
  src/Apps/Artwork/Components/ArtworkLightbox.tsx
  src/Apps/Order/Routes/Shipping/ShippingContext.tsx
  src/Apps/Order/Routes/Shipping/Utils/computeOrderData.ts
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Components/Notifications/NotificationItem.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkImageBrowserLarge_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowserSmall_Test_Query.graphql.ts
  src/__generated__/ArtworkLightboxTestQuery.graphql.ts
  src/__generated__/ArtworkLightbox_artwork.graphql.ts
  src/__generated__/MyCollectionArtworkImageBrowserTestQuery.graphql.ts
  src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
  src/__generated__/NotificationItem_notification.graphql.ts
  src/__generated__/NotificationItem_test_Query.graphql.ts
  src/__generated__/NotificationsListNextQuery.graphql.ts
  src/__generated__/NotificationsListQuery.graphql.ts
  src/__generated__/NotificationsList_test_Query.graphql.ts
  src/__generated__/ShippingContext_order.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/ShowInfo_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
  src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
  src/__generated__/orderRoutes_ShippingQuery.graphql.ts
  src/__generated__/showRoutes_ShowInfoQuery.graphql.ts
  src/__generated__/useSaveFulfillmentDetailsMutation.graphql.ts
  src/__generated__/useSelectShippingQuoteMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#15354 fix(EMI-2351): Add postal code to payload when selecting apple pay shipping address
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
Labels: Jira Synced

#15355 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15349 chore(EMI-2366): track express checkout viewed
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Order/Hooks/useOrderTracking.tsx
Labels: Jira Synced, Squash On Green

#15356 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15357 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15358 chore: update express checkout tracking
  package.json
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Order/Hooks/useOrderTracking.tsx
  yarn.lock
Labels: Squash On Green

#15361 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15362 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useUpdateOrderMutation.graphql.ts
Labels: Squash On Green

#15335 feat: submit apple pay order on confirm
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/Mutations/useSubmitOrderMutation.ts
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Order/Components/ExpressCheckout/index.tsx
  src/__generated__/useSubmitOrderMutation.graphql.ts
Labels: Jira Synced

#15364 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15360 chore(EMI-2355): Update line items and total order amount when order changes
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/Mutations/useSetFulfillmentOptionMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUpdateOrderMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Util/mutationHandling.ts
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Order/Components/ExpressCheckout/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/__generated__/ExpressCheckoutQuery.graphql.ts
  src/__generated__/ExpressCheckoutUI_Test_Query.graphql.ts
  src/__generated__/ExpressCheckoutUI_order.graphql.ts
  src/__generated__/useSetFulfillmentOptionMutation.graphql.ts
  src/__generated__/useUpdateOrderMutation.graphql.ts
Labels: Jira Synced

#15367 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15368 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15369 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15365 Deploy
  data/schema.graphql
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/Mutations/useSetFulfillmentOptionMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUpdateOrderMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Util/mutationHandling.ts
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Order/Components/ExpressCheckout/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/__generated__/ExpressCheckoutQuery.graphql.ts
  src/__generated__/ExpressCheckoutUI_Test_Query.graphql.ts
  src/__generated__/ExpressCheckoutUI_order.graphql.ts
  src/__generated__/useSetFulfillmentOptionMutation.graphql.ts
  src/__generated__/useUpdateOrderMutation.graphql.ts
Labels: Jira Synced
