Repository artsy/force, pull requests merged in 2025-05, with the labels that each got.

#15508 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/ArtistSeriesOptionsQuery.graphql.ts
  src/__generated__/ArtistWorksForSaleRouteArtworksQuery.graphql.ts
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/CollectArtworkFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/__generated__/CollectionArtworksQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGridQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGrid_Test_Query.graphql.ts
  src/__generated__/FairArtworksFilterQuery.graphql.ts
  src/__generated__/FairArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/__generated__/GeneArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
  src/__generated__/SaleArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/SuggestedArtworksModalGridQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/TagArtworkFilterQuery.graphql.ts
  src/__generated__/TagArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/WorksFilterQuery.graphql.ts
  src/__generated__/WorksFilterRefetchQuery.graphql.ts
  src/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/saleRoutes_SaleQuery.graphql.ts
  src/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
Labels: Squash On Green

#15509 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15505 Deploy
  data/schema.graphql
  docs/using_unleash.md
  package.json
  src/Apps/About/AboutApp.tsx
  src/Apps/Components/constants.ts
  src/Apps/Example/exampleRoutes.tsx
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Order/Hooks/useOrderTracking.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/__tests__/OrderApp.jest.enzyme.tsx
  src/Apps/Order/orderRoutes.tsx
  src/Apps/Order/redirects.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Details/Order2DetailsRoute.tsx
  src/Apps/Order2/order2Routes.tsx
  src/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
  src/System/Contexts/SystemContext.tsx
  src/System/Router/__tests__/clientRouter.jest.tsx
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/ArtistSeriesOptionsQuery.graphql.ts
  src/__generated__/ArtistWorksForSaleRouteArtworksQuery.graphql.ts
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/CollectArtworkFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/__generated__/CollectionArtworksQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGridQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGrid_Test_Query.graphql.ts
  src/__generated__/FairArtworksFilterQuery.graphql.ts
  src/__generated__/FairArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/__generated__/GeneArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
  src/__generated__/SaleArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/SuggestedArtworksModalGridQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/TagArtworkFilterQuery.graphql.ts
  src/__generated__/TagArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/WorksFilterQuery.graphql.ts
  src/__generated__/WorksFilterRefetchQuery.graphql.ts
  src/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/order2Routes_DetailsQuery.graphql.ts
  src/__generated__/saleRoutes_SaleQuery.graphql.ts
  src/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
  src/client.tsx
  src/server.ts
  yarn.lock
Labels: Jira Synced

#15511 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15517 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15521 style(EMI-2382): Static checkout flow, mobile
  src/Apps/Components/Layouts/LayoutLogoOnlyFullBleed.tsx
  src/Apps/Components/Layouts/index.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/order2Routes.tsx
  src/Components/Address/AddressFormFields.tsx
Labels: Jira Synced

#15518 Deploy
  data/schema.graphql
  package.json
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtworkTitle.tsx
  src/Apps/Components/Layouts/LayoutLogoOnlyFullBleed.tsx
  src/Apps/Components/Layouts/index.tsx
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/order2Routes.tsx
  src/Components/Address/AddressFormFields.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebarArtists_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarArtists_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#15523 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15527 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15522 chore(EMI-2414): order summary and review section components with some data
  src/Apps/Components/Layouts/LayoutLogoOnlyFullBleed.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2CollapsibleOrderSummary.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ExpressCheckoutStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
  src/__generated__/Order2CollapsibleOrderSummary_order.graphql.ts
  src/__generated__/Order2ExpressCheckoutStep_order.graphql.ts
  src/__generated__/Order2ReviewStep_order.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
Labels: Jira Synced

#15524 Deploy
  data/schema.graphql
  package.json
  src/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
  src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Components/Layouts/LayoutLogoOnlyFullBleed.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2CollapsibleOrderSummary.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ExpressCheckoutStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Details/Components/Order2DetailsHeader.tsx
  src/Apps/Order2/Routes/Details/Components/Order2DetailsPage.tsx
  src/Apps/Order2/Routes/Details/Components/__tests__/Order2DetailsPage.jest.tsx
  src/Apps/Order2/Routes/Details/Order2DetailsRoute.tsx
  src/Apps/Order2/order2Routes.tsx
  src/Components/NavBar/Menus/NavBarUserMenu.tsx
  src/Components/NavBar/NavBarLoggedInActions.tsx
  src/__generated__/ArtistApp_Test_Query.graphql.ts
  src/__generated__/ArtistHeader_artist.graphql.ts
  src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
  src/__generated__/Order2CollapsibleOrderSummary_order.graphql.ts
  src/__generated__/Order2DetailsHeader_order.graphql.ts
  src/__generated__/Order2DetailsPage_Test_Query.graphql.ts
  src/__generated__/Order2DetailsPage_order.graphql.ts
  src/__generated__/Order2DetailsRoute_viewer.graphql.ts
  src/__generated__/Order2ExpressCheckoutStep_order.graphql.ts
  src/__generated__/Order2ReviewStep_order.graphql.ts
  src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/order2Routes_DetailsQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#15532 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/ArtistSeriesOptionsQuery.graphql.ts
  src/__generated__/ArtistWorksForSaleRouteArtworksQuery.graphql.ts
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/CollectArtworkFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/__generated__/CollectionArtworksQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGridQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGrid_Test_Query.graphql.ts
  src/__generated__/FairArtworksFilterQuery.graphql.ts
  src/__generated__/FairArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/__generated__/GeneArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
  src/__generated__/SaleArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/SuggestedArtworksModalGridQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/TagArtworkFilterQuery.graphql.ts
  src/__generated__/TagArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/WorksFilterQuery.graphql.ts
  src/__generated__/WorksFilterRefetchQuery.graphql.ts
  src/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/saleRoutes_SaleQuery.graphql.ts
  src/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
Labels: Squash On Green

#15502 feat(EMI-2399): decouple address and payment method updates from express checkout orders
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUpdateOrderShippingAddressMutation.ts
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/__generated__/useUpdateOrderShippingAddressMutation.graphql.ts
Labels: Jira Synced

#15536 fix: update ExpressCheckoutUI specs
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
Labels: Squash On Green

#15534 Deploy
  data/schema.graphql
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUpdateOrderShippingAddressMutation.ts
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/ArtistSeriesOptionsQuery.graphql.ts
  src/__generated__/ArtistWorksForSaleRouteArtworksQuery.graphql.ts
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/CollectArtworkFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/__generated__/CollectionArtworksQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGridQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGrid_Test_Query.graphql.ts
  src/__generated__/FairArtworksFilterQuery.graphql.ts
  src/__generated__/FairArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/__generated__/GeneArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
  src/__generated__/SaleArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/SuggestedArtworksModalGridQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/TagArtworkFilterQuery.graphql.ts
  src/__generated__/TagArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/WorksFilterQuery.graphql.ts
  src/__generated__/WorksFilterRefetchQuery.graphql.ts
  src/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/saleRoutes_SaleQuery.graphql.ts
  src/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
  src/__generated__/useUpdateOrderShippingAddressMutation.graphql.ts
Labels: Jira Synced

#15537 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useUpdateOrderMutation.graphql.ts
Labels: Squash On Green

#15543 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15545 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15549 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15544 feat(about): adds structured data schema for article
  src/Apps/Article/ArticleApp.tsx
  src/Apps/Article/Components/ArticleStructuredData.tsx
  src/__generated__/ArticleApp_article.graphql.ts
  src/__generated__/ArticleStructuredData_article.graphql.ts
  src/__generated__/articleRoutes_ArticleQuery.graphql.ts
Labels: SEO

#15541 chore: load order summary lines from MP
  src/Apps/Order2/Routes/Checkout/Components/Order2CollapsibleOrderSummary.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2PricingBreakdown.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/__tests__/Order2PricingBreakdown.jest.tsx
  src/__generated__/Order2CollapsibleOrderSummary_order.graphql.ts
  src/__generated__/Order2PricingBreakdownTestQuery.graphql.ts
  src/__generated__/Order2PricingBreakdown_order.graphql.ts
  src/__generated__/Order2ReviewStep_order.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
Labels: Jira Synced

#15553 fix(EMI-2451): do not send address for pickup mode
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
Labels: Jira Synced, Squash On Green

#15552 Deploy
  package.json
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2CollapsibleOrderSummary.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2PricingBreakdown.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/__tests__/Order2PricingBreakdown.jest.tsx
  src/__generated__/Order2CollapsibleOrderSummary_order.graphql.ts
  src/__generated__/Order2PricingBreakdownTestQuery.graphql.ts
  src/__generated__/Order2PricingBreakdown_order.graphql.ts
  src/__generated__/Order2ReviewStep_order.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#15554 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15557 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15559 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15561 feat(dia-1319): add exhibition event json ld schema for viewing rooms
  .secrets.baseline
  src/Apps/Article/Components/ArticleStructuredData.tsx
  src/Apps/ViewingRoom/Components/ViewingRoomStructuredData.tsx
  src/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.enzyme.tsx
  src/__generated__/ArticleStructuredData_article.graphql.ts
  src/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_DraftTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_LoggedOutTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_ScheduledTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomStructuredData_viewingRoom.graphql.ts
  src/__generated__/articleRoutes_ArticleQuery.graphql.ts
  src/__generated__/viewingRoomRoutes_ViewingRoomQuery.graphql.ts
Labels: SEO

#15558 feat(EMI-2452): conditionally render pickup if available
  src/Apps/Order2/Routes/Checkout/Components/Order2DeliveryForm.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
Labels: Jira Synced

#15564 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15566 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15539 feat(EMI-2450): Add loading screen for express checkout submissions
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
  src/Apps/Order/Components/ExpressCheckout/index.tsx
  src/Apps/Order/Components/SubmittingOrderSpinner.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
Labels: Jira Synced, Squash On Green

#15569 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15573 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15579 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15574 fix(EMI-2442): Update Me Order argument type to ID
  data/schema.graphql
  src/Apps/Order/Components/ExpressCheckout/index.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Details/Order2DetailsRoute.tsx
  src/Apps/Order2/order2Routes.tsx
  src/__generated__/ExpressCheckoutQuery.graphql.ts
  src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
  src/__generated__/Order2DetailsRoute_viewer.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/order2Routes_DetailsQuery.graphql.ts
Labels: Jira Synced

#15582 Deploy
  data/schema.graphql
  package.json
  src/Apps/Order/Components/ExpressCheckout/index.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Details/Order2DetailsRoute.tsx
  src/Apps/Order2/order2Routes.tsx
  src/__generated__/ExpressCheckoutQuery.graphql.ts
  src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
  src/__generated__/Order2DetailsRoute_viewer.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/order2Routes_DetailsQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#15594 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15598 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15571 feat(EMI-2469): Set pickup fulfillment type and details on new checkout flow
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2DeliveryForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2FulfillmentDetailsCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2FulfillmentDetailsStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2PickupForm.tsx
  src/Apps/Order2/Routes/Checkout/Mutations/useSetOrderFulfillmentOptionMutation.ts
  src/Apps/Order2/Routes/Checkout/Mutations/useSetOrderPickupDetailsMutation.ts
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
  src/__generated__/Order2FulfillmentDetailsStep_order.graphql.ts
  src/__generated__/Order2PickupForm_order.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/useSetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useSetOrderPickupDetailsMutation.graphql.ts
Labels: Jira Synced

#15603 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15604 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15606 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15602 Deploy
  data/schema.graphql
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2DeliveryForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2FulfillmentDetailsCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2FulfillmentDetailsStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2PickupForm.tsx
  src/Apps/Order2/Routes/Checkout/Mutations/useSetOrderFulfillmentOptionMutation.ts
  src/Apps/Order2/Routes/Checkout/Mutations/useSetOrderPickupDetailsMutation.ts
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/Apps/SaleAgreements/Routes/SaleAgreementRoute.tsx
  src/Apps/SaleAgreements/SaleAgreementsApp.tsx
  src/System/Relay/createRelaySSREnvironment.ts
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
  src/__generated__/Order2FulfillmentDetailsStep_order.graphql.ts
  src/__generated__/Order2PickupForm_order.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/useSetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useSetOrderPickupDetailsMutation.graphql.ts
Labels: Jira Synced

#15608 chore(EMI-2504): Checkout context
  src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
  src/Apps/Order2/Routes/Checkout/CheckoutContext/types.ts
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2FulfillmentDetailsCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2FulfillmentDetailsStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2PickupForm.tsx
  src/Apps/Order2/Routes/Checkout/Hooks/__tests__/useLoadCheckout.jest.tsx
  src/Apps/Order2/Routes/Checkout/Hooks/useCheckoutContext.ts
  src/Apps/Order2/Routes/Checkout/Hooks/useLoadCheckout.ts
  src/Apps/Order2/Routes/Checkout/Mutations/useSetOrderFulfillmentOptionMutation.ts
  src/Apps/Order2/Routes/Checkout/Mutations/useSetOrderPickupDetailsMutation.ts
  src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/__generated__/Order2CheckoutApp_viewer.graphql.ts
  src/__generated__/Order2CheckoutContext_order.graphql.ts
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
  src/__generated__/Order2FulfillmentDetailsStep_order.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/useLoadCheckoutTestQuery.graphql.ts
  src/__generated__/useLoadCheckout_order.graphql.ts
  src/__generated__/useSetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useSetOrderPickupDetailsMutation.graphql.ts
Labels: Jira Synced

#15607 feat: Final wire details for the message section.
  src/Apps/Order2/Routes/Details/Components/Order2DetailsMessage.tsx
  src/Apps/Order2/Routes/Details/Components/WireTransferInfo.tsx
  src/Apps/Order2/Routes/Details/Components/__tests__/Order2DetailsMessage.jest.tsx
  src/__generated__/Order2DetailsMessage_Test_Query.graphql.ts
  src/__generated__/Order2DetailsMessage_order.graphql.ts
  src/__generated__/Order2DetailsPage_Test_Query.graphql.ts
  src/__generated__/order2Routes_DetailsQuery.graphql.ts
Labels: Jira Synced

#15616 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15615 feat(EMI-2326): Buyer can enter new credit card and continue
  src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2PaymentStep/Order2PaymentCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2PaymentStep/Order2PaymentStep.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/__generated__/Order2CheckoutApp_viewer.graphql.ts
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2PaymentFormConfirmationTokenQuery.graphql.ts
  src/__generated__/Order2PaymentStep_order.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
Labels: Jira Synced

#15611 Deploy
  data/schema.graphql
  package.json
  src/Apps/About/AboutApp.tsx
  src/Apps/Components/constants.ts
  src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
  src/Apps/Order/Components/ExpressCheckout/index.tsx
  src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
  src/Apps/Order2/Routes/Checkout/CheckoutContext/types.ts
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2FulfillmentDetailsCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2FulfillmentDetailsStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2PickupForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2PaymentStep/Order2PaymentCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2PaymentStep/Order2PaymentStep.tsx
  src/Apps/Order2/Routes/Checkout/Hooks/__tests__/useLoadCheckout.jest.tsx
  src/Apps/Order2/Routes/Checkout/Hooks/useCheckoutContext.ts
  src/Apps/Order2/Routes/Checkout/Hooks/useLoadCheckout.ts
  src/Apps/Order2/Routes/Checkout/Mutations/useSetOrderFulfillmentOptionMutation.ts
  src/Apps/Order2/Routes/Checkout/Mutations/useSetOrderPickupDetailsMutation.ts
  src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/Apps/Order2/Routes/Details/Components/Order2DetailsMessage.tsx
  src/Apps/Order2/Routes/Details/Components/WireTransferInfo.tsx
  src/Apps/Order2/Routes/Details/Components/__tests__/Order2DetailsMessage.jest.tsx
  src/Apps/Partner/Components/PartnerHeader/index.tsx
  src/Apps/Partner/Components/__tests__/PartnerHeader.jest.tsx
  src/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
  src/Apps/Show/__tests__/ShowArtworks.jest.enzyme.tsx
  src/Apps/Show/__tests__/ShowArtworks.jest.tsx
  src/Apps/Sitemaps/sitemapsServerApp.tsx
  src/Apps/Sitemaps/templates/llms.ts
  src/Components/Artwork/Details/__tests__/Details.jest.enzyme.tsx
  src/Components/Artwork/Details/__tests__/Details.jest.tsx
  src/Components/Footer/Footer.tsx
  src/Utils/factsAndFigures.ts
  src/__generated__/Details_Test_Query.graphql.ts
  src/__generated__/Order2CheckoutApp_viewer.graphql.ts
  src/__generated__/Order2CheckoutContext_order.graphql.ts
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
  src/__generated__/Order2DetailsMessage_Test_Query.graphql.ts
  src/__generated__/Order2DetailsMessage_order.graphql.ts
  src/__generated__/Order2DetailsPage_Test_Query.graphql.ts
  src/__generated__/Order2FulfillmentDetailsStep_order.graphql.ts
  src/__generated__/Order2PaymentFormConfirmationTokenQuery.graphql.ts
  src/__generated__/Order2PaymentStep_order.graphql.ts
  src/__generated__/PartnerApp_Test_Query.graphql.ts
  src/__generated__/PartnerHeader_Test_Query.graphql.ts
  src/__generated__/PartnerHeader_partner.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/order2Routes_DetailsQuery.graphql.ts
  src/__generated__/partnerRoutes_PartnerQuery.graphql.ts
  src/__generated__/useLoadCheckoutTestQuery.graphql.ts
  src/__generated__/useLoadCheckout_order.graphql.ts
  src/__generated__/useSetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useSetOrderPickupDetailsMutation.graphql.ts
  yarn.lock
Labels: Jira Synced

#15620 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15621 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15624 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useUpdateOrderMutation.graphql.ts
Labels: Squash On Green

#15612 feat: OrderSummary for order details page.
  src/Apps/Order2/Components/Order2PricingBreakdown.tsx
  src/Apps/Order2/Components/__tests__/Order2PricingBreakdown.jest.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2CollapsibleOrderSummary.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
  src/Apps/Order2/Routes/Details/Components/Order2DetailsOrderSummary.tsx
  src/Apps/Order2/Routes/Details/Components/Order2DetailsPage.tsx
  src/__generated__/Order2DetailsOrderSummary_order.graphql.ts
  src/__generated__/Order2DetailsPage_Test_Query.graphql.ts
  src/__generated__/Order2DetailsPage_order.graphql.ts
  src/__generated__/order2Routes_DetailsQuery.graphql.ts
Labels: Jira Synced

#15619 feat(EMI-2418): add express checkout to order2
  src/Apps/Order/Components/ExpressCheckout/Mutations/useSetFulfillmentOptionMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUnsetOrderFulfillmentOptionMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUnsetOrderPaymentMethodMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUpdateOrderMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUpdateOrderShippingAddressMutation.ts
  src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
  src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/Order2ExpressCheckout.tsx
  src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/Order2ExpressCheckoutUI.tsx
  src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/__tests__/Order2ExpressCheckout.jest.tsx
  src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/__tests__/Order2ExpressCheckoutUI.jest.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2DeliveryForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2FulfillmentDetailsCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2FulfillmentDetailsStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2PickupForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ExpressCheckoutStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentStep.tsx
  src/Apps/Order2/Routes/Checkout/Hooks/useCheckoutTracking.ts
  src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/System/Contexts/AnalyticsContext.tsx
  src/__generated__/Order2CheckoutApp_viewer.graphql.ts
  src/__generated__/Order2CheckoutContext_order.graphql.ts
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
  src/__generated__/Order2ExpressCheckoutQuery.graphql.ts
  src/__generated__/Order2ExpressCheckoutStep_order.graphql.ts
  src/__generated__/Order2ExpressCheckoutUI_Test_Query.graphql.ts
  src/__generated__/Order2ExpressCheckoutUI_order.graphql.ts
  src/__generated__/Order2ExpressCheckout_Test_Query.graphql.ts
  src/__generated__/Order2ExpressCheckout_order.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/useSetFulfillmentOptionMutation.graphql.ts
  src/__generated__/useUnsetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useUnsetOrderPaymentMethodMutation.graphql.ts
  src/__generated__/useUpdateOrderMutation.graphql.ts
  src/__generated__/useUpdateOrderShippingAddressMutation.graphql.ts
Labels: Jira Synced

#15631 Deploy
  src/Apps/Order/Components/ExpressCheckout/Mutations/useSetFulfillmentOptionMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUnsetOrderFulfillmentOptionMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUnsetOrderPaymentMethodMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUpdateOrderMutation.ts
  src/Apps/Order/Components/ExpressCheckout/Mutations/useUpdateOrderShippingAddressMutation.ts
  src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
  src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/Order2ExpressCheckout.tsx
  src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/Order2ExpressCheckoutUI.tsx
  src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/__tests__/Order2ExpressCheckout.jest.tsx
  src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/__tests__/Order2ExpressCheckoutUI.jest.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2DeliveryForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2FulfillmentDetailsCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2FulfillmentDetailsStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2PickupForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/Order2ExpressCheckoutStep.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentCompletedView.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentStep.tsx
  src/Apps/Order2/Routes/Checkout/Hooks/useCheckoutTracking.ts
  src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
  src/Apps/Order2/Routes/Details/Components/Order2DetailsMessage.tsx
  src/Apps/Order2/Routes/Details/Components/Order2DetailsOrderSummary.tsx
  src/Apps/Order2/Routes/Details/Components/Order2DetailsPaymentInfo.tsx
  src/System/Contexts/AnalyticsContext.tsx
  src/__generated__/Order2CheckoutApp_viewer.graphql.ts
  src/__generated__/Order2CheckoutContext_order.graphql.ts
  src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
  src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
  src/__generated__/Order2ExpressCheckoutQuery.graphql.ts
  src/__generated__/Order2ExpressCheckoutStep_order.graphql.ts
  src/__generated__/Order2ExpressCheckoutUI_Test_Query.graphql.ts
  src/__generated__/Order2ExpressCheckoutUI_order.graphql.ts
  src/__generated__/Order2ExpressCheckout_Test_Query.graphql.ts
  src/__generated__/Order2ExpressCheckout_order.graphql.ts
  src/__generated__/order2Routes_CheckoutQuery.graphql.ts
  src/__generated__/useSetFulfillmentOptionMutation.graphql.ts
  src/__generated__/useUnsetOrderFulfillmentOptionMutation.graphql.ts
  src/__generated__/useUnsetOrderPaymentMethodMutation.graphql.ts
  src/__generated__/useUpdateOrderMutation.graphql.ts
  src/__generated__/useUpdateOrderShippingAddressMutation.graphql.ts
Labels: Jira Synced

#15633 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15636 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15632 chore(EMI-2472): New checkout desktop layout
  src/Apps/Components/Layouts/LayoutLogoOnlyFullBleed.tsx
  src/Apps/Order2/Order2App.tsx
  src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentStep.tsx
  src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx
  src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
Labels: Jira Synced

#15639 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15641 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green
