Repository artsy/force, pull requests merged in 2025-01, with the labels that each got.

#15035 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15060 test: fix help article link
  src/Apps/Auctions/__tests__/AuctionsApp.jest.enzyme.tsx
Labels: Merge On Green

#15059 refactor: retire .well-known folder as it's moved to Cloudflare worker
  src/public/.well-known/apple-developer-domain-association.txt
  src/public/.well-known/assetlinks.json
Labels: Jira Synced

#15058 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15063 fix: include initial input/sort when prefetching artist artworks
  src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
  src/Apps/Artist/artistRoutes.tsx
  src/__generated__/ArtistWorksForSaleRoute_artist.graphql.ts
  src/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
Labels: Jira Synced

#15062 fix(EMI-2213): failed payment redirect
  src/Apps/Order/redirects.tsx
Labels: Jira Synced

#15067 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15065 Deploy
  data/schema.graphql
  package.json
  scripts/create-review-app-subdomain.js
  src/Apps/Order/redirects.tsx
  yarn.lock
Labels: Jira Synced

#15072 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15073 chore: add high fetch priority to preload links when applicable
  src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryFigure.tsx
  src/Apps/Artwork/Components/ArtworkLightboxPlaceholder.tsx
  src/Apps/Fair/Components/FairHeader/FairHeaderImage.tsx
  src/Components/HeaderIcon.tsx
Labels: performance

#15076 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15078 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15081 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15086 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15088 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15085 fix: add additional line to the artwork metadata placeholder
  src/Components/Artwork/Details/Details.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
Labels: Jira Synced

#15092 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15096 feat(performance): Add INP optimization strategy for mobile web
  src/Apps/Components/INPOptimizer.tsx
  src/Apps/Components/Layouts/index.tsx
  src/Apps/Components/__tests__/INPOptimizer.jest.tsx
  src/Components/Artwork/Details/PrimaryLabelLine.tsx
  src/Components/RouteTabs.tsx
Labels: Jira Synced

#15097 fix: remove errand right parens in artist works route
  src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
Labels: Merge On Green

#15101 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/useUpdateArtworkListMutation.graphql.ts
Labels: Squash On Green

#15102 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15103 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/ArtistSeriesOptionsQuery.graphql.ts
  src/__generated__/ArtistWorksForSaleRouteArtworksQuery.graphql.ts
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/CollectArtworkFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/__generated__/CollectionArtworksQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGridQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGrid_Test_Query.graphql.ts
  src/__generated__/FairArtworksFilterQuery.graphql.ts
  src/__generated__/FairArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/__generated__/GeneArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
  src/__generated__/SaleArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/SuggestedArtworksModalGridQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/TagArtworkFilterQuery.graphql.ts
  src/__generated__/TagArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/WorksFilterQuery.graphql.ts
  src/__generated__/WorksFilterRefetchQuery.graphql.ts
  src/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/saleRoutes_SaleQuery.graphql.ts
  src/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
Labels: Squash On Green

#15107 feat: show Auction total raised in sidebar
  src/Apps/Auction/Components/AuctionDetails/AuctionInfoSidebar.tsx
  src/Utils/Hooks/useSaleWebsocket.tsx
  src/__generated__/AuctionAppTestQuery.graphql.ts
  src/__generated__/AuctionDetailsTestQuery.graphql.ts
  src/__generated__/AuctionInfoSidebarTestQuery.graphql.ts
  src/__generated__/AuctionInfoSidebar_sale.graphql.ts
  src/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
  src/__generated__/useCreateBidderMutation.graphql.ts
Labels: hackathon

#15113 chore: update shipping from display to include pickup line and minor spacing adjustments
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarShippingInformation.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarShippingInformation.jest.tsx
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebarShippingInformation_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarShippingInformation_artwork.graphql.ts
  src/__generated__/ArtworkSidebarShippingLabels_artwork.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Labels: hackathon

#15114 chore: update metaphysics graphql schema
  src/__generated__/ArtworkSidebarShippingLabels_artwork.graphql.ts
Labels: Squash On Green

#15116 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
  src/__generated__/ArtistSeriesArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/ArtistSeriesOptionsQuery.graphql.ts
  src/__generated__/ArtistWorksForSaleRouteArtworksQuery.graphql.ts
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterQuery.graphql.ts
  src/__generated__/AuctionArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/CollectArtworkFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilterQuery.graphql.ts
  src/__generated__/CollectionArtworksFilter_Query.graphql.ts
  src/__generated__/CollectionArtworksQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGridQuery.graphql.ts
  src/__generated__/ConfirmationArtworksGrid_Test_Query.graphql.ts
  src/__generated__/FairArtworksFilterQuery.graphql.ts
  src/__generated__/FairArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/GeneArtworkFilterQuery.graphql.ts
  src/__generated__/GeneArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
  src/__generated__/SaleArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterQuery.graphql.ts
  src/__generated__/ShowArtworksFilterRefetchQuery.graphql.ts
  src/__generated__/SuggestedArtworksModalGridQuery.graphql.ts
  src/__generated__/SuggestedArtworksShelfQuery.graphql.ts
  src/__generated__/TagArtworkFilterQuery.graphql.ts
  src/__generated__/TagArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/WorksFilterQuery.graphql.ts
  src/__generated__/WorksFilterRefetchQuery.graphql.ts
  src/__generated__/exampleRoutes_ArtworkFilterQuery.graphql.ts
  src/__generated__/saleRoutes_SaleQuery.graphql.ts
  src/__generated__/searchRoutes_ArtworksViewerQuery.graphql.ts
Labels: Squash On Green

#15117 chore: update metaphysics graphql schema
  data/schema.graphql
  src/__generated__/SavesArtworksShareDialogMutation.graphql.ts
  src/__generated__/useUpdateArtworkListMutation.graphql.ts
Labels: Squash On Green

#15108 feat: add show only framed works filter
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
  src/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx
  src/Apps/Search/Components/SearchResultsArtworksFilters.tsx
  src/Components/Alert/AlertProvider.tsx
  src/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/ArtworkFilter/ArtworkFilterTypes.ts
  src/Components/ArtworkFilter/ArtworkFilters/FramedFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/FramedFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/index.tsx
  src/Components/ArtworkFilter/Utils/__tests__/urlFragmentFromState.jest.tsx
  src/Components/ArtworkFilter/Utils/allowedFilters.ts
  src/Components/SavedSearchAlert/Utils/__tests__/extractPills.jest.ts
  src/Components/SavedSearchAlert/Utils/extractPills.ts
  src/Components/SavedSearchAlert/constants.ts
  src/Components/SavedSearchAlert/types.ts
Labels: Squash On Green

#15111 feat: add signed as filter param to filterArtworksConnection
  src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
  src/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx
  src/Apps/Search/Components/SearchResultsArtworksFilters.tsx
  src/Components/Alert/AlertProvider.tsx
  src/Components/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/ArtworkFilter/ArtworkFilterTypes.ts
  src/Components/ArtworkFilter/ArtworkFilters/SignedFilter.tsx
  src/Components/ArtworkFilter/ArtworkFilters/__tests__/SignedFilter.jest.tsx
  src/Components/ArtworkFilter/ArtworkFilters/index.tsx
  src/Components/ArtworkFilter/Utils/allowedFilters.ts
  src/Components/SavedSearchAlert/Utils/__tests__/extractPills.jest.ts
  src/Components/SavedSearchAlert/Utils/extractPills.ts
  src/Components/SavedSearchAlert/constants.ts
  src/Components/SavedSearchAlert/types.ts
  src/__generated__/NotificationQuery.graphql.ts
  src/__generated__/NotificationViewingRoom_viewingRoom.graphql.ts
  src/__generated__/PartnerViewingRoomsGrid_Test_Query.graphql.ts
  src/__generated__/PartnerViewingRoomsGrid_ViewingRoomsQuery.graphql.ts
  src/__generated__/ShowApp_Test_Query.graphql.ts
  src/__generated__/ShowViewingRoom_Test_Query.graphql.ts
  src/__generated__/ShowViewingRoom_show.graphql.ts
  src/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_DraftTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_LoggedOutTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts
  src/__generated__/ViewingRoomApp_ScheduledTest_Query.graphql.ts
  src/__generated__/ViewingRoomCard_Test_Query.graphql.ts
  src/__generated__/ViewingRoomCard_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomMeta_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomPublishedNotification_test_Query.graphql.ts
  src/__generated__/ViewingRoomsApp_Test_Query.graphql.ts
  src/__generated__/ViewingRoomsFeaturedRail_featuredViewingRooms.graphql.ts
  src/__generated__/ViewingRoomsLatestGrid_ViewingRoomsAppQuery.graphql.ts
  src/__generated__/ViewingRoomsLatestGrid_viewingRooms.graphql.ts
  src/__generated__/partnerRoutes_ViewingRoomsQuery.graphql.ts
  src/__generated__/showRoutes_ShowQuery.graphql.ts
  src/__generated__/viewingRoomRoutes_ViewingRoomQuery.graphql.ts
  src/__generated__/viewingRoomRoutes_ViewingRoomsAppQuery.graphql.ts
Labels: Squash On Green

#15121 chore: update metaphysics graphql schema
  data/schema.graphql
Labels: Squash On Green

#15124 Deploy
  data/schema.graphql
  package.json
  rsbuild.config.ts
  src/Apps/Components/INPOptimizer.tsx
  src/Apps/Components/Layouts/index.tsx
  src/Apps/Components/__tests__/INPOptimizer.jest.tsx
  src/Apps/Order/Routes/Payment/ExpressCheckoutPrototype/ExpressCheckout.tsx
  src/Apps/Order/Routes/Payment/ExpressCheckoutPrototype/ExpressCheckoutProvider.tsx
  src/Apps/Order/Routes/Payment/PaymentContent.tsx
  src/Components/Artwork/Details/PrimaryLabelLine.tsx
  src/Components/ArtworkGrid/ArtworkGridContext.tsx
  src/Components/BankDebitForm/__tests__/BankDebitProvider.jest.enzyme.tsx
  src/Components/RouteTabs.tsx
  yarn.lock
Labels: Jira Synced

#15132 fix(nav): always persist Buy link
  src/Components/NavBar/NavBar.tsx
Labels: Merge On Green

#15130 Deploy
  package.json
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarShippingInformation.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebar.jest.tsx
  src/Components/ArtsyShippingEstimate.tsx
  src/Components/Artwork/SidebarExpandable.tsx
  src/Components/NavBar/NavBar.tsx
  src/Server/bootstrapSharify.ts
  src/Server/config.ts
  src/Typings/sharify.d.ts
  src/__generated__/ArtsyShippingEstimate_artwork.graphql.ts
  src/__generated__/ArtworkAppTestQuery.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#15131 chore(EMI-2277): add tests for shipping estimate widget
  src/Components/ArtsyShippingEstimate.tsx
  src/Components/__tests__/ArtsyShippingEstimate.jest.tsx
  src/__generated__/ArtsyShippingEstimate_Test_Query.graphql.ts
Labels: Jira Synced, Squash On Green
